### ISSUE TITLE
Desert Underground morphing won't morph stalactites and stalagmites.

### ISSUE THREAD

**Issue by FeawFeaw** [TEdit/Terraria-Map-Editor#1002]
## What were you doing when the issue occured?
Tried to morph a portion of the Desert Underground to Crimson, but it won't morph stalactites and stalagmites like the stone and ice biomes do.
See this image: https://i.gyazo.com/54fbe6683845a3302cba04724613de37.png
As you can see when morphing that area right in the middle it won't convert the stalagmites and stalactites, but naturally spread Crimson/Corruption/Hallow in-game do (as seen in the rest of the image).

Note that other deco tiles such as antlion hills and larger stalagmites don't ever change, even in-game, but the 1 tile wide ones do.

## Can you reproduce the issue?
Yes.

## What version of Terraria are you using?
1.3.5.3

## Post relevant contents of log or attach log file _**(very important)**_:
N/A

**Comment by BinaryConstruct** [comment]
Merging into #533
