### ISSUE TITLE
Any form of bricks leave slopes in world.

### ISSUE THREAD

**Issue by DragonStar123** [TEdit/Terraria-Map-Editor#1003]
I was trying to make a completely flat world with no biomes or anything when I realized there was a problem with any type of bricks I tried to use. It looks like it randomly hammers a block and it really annoys me when you can see it from the surface. I've only tried with bricks but it probably happens with other blocks as well.  

Anyone else seeing this and if so, how do you fix it? Version: 1.3.0.2
![weirdglitchterraria](https://user-images.githubusercontent.com/29680136/27511134-6b11539a-58db-11e7-96a6-e7578c17b03e.png)
![terrariagaps](https://user-images.githubusercontent.com/29680136/27511159-ad1e1408-58db-11e7-99f4-102565c73566.png)
![slopes](https://user-images.githubusercontent.com/29680136/27511165-d3f7deb0-58db-11e7-9f58-0a33814afae4.png)

**Comment by BinaryConstruct** [comment]
Check the "extras" full brick box. This will replace slopes.

**Comment by enigmaquip** [comment]
It's just maintaining the previous slope state of what the block was you
were replacing, unless you click the extras checkbox and the slope checkbox
as binary stated
