### ISSUE TITLE
Unhandled Exception Error

### ISSUE THREAD

**Issue by AlexanderStarship** [TEdit/Terraria-Map-Editor#1011]
## What were you doing when the issue occured?
Trying to open TEdit (Just bought Terraria on Steam, and then downloaded the latest version of TEdit)
## Can you reproduce the issue?
Yes
## What version of Terraria are you using?
1.3.5 (on Steam)
## Post relevant contents of log or attach log file _**(very important)**_:
[TEditLog.txt](https://github.com/TEdit/Terraria-Map-Editor/files/1151383/TEditLog.txt)

**Comment by Rocklucca32** [comment]
I'm with the same error

**Comment by sasha230** [comment]
[TEditLog.txt](https://github.com/TEdit/Terraria-Map-Editor/files/3332126/TEditLog.txt)
