### ISSUE TITLE
Mi tedit no quiere arrancar

### ISSUE THREAD

**Issue by UnoRev3** [TEdit/Terraria-Map-Editor#1012]
He intentado varios métodos para solucionar el problema, creo que ha nadie le ha pasado.
Al ejecutar tedit no aparece nada en pantalla, he incluso no arroja errores de ningún tipo.
He actualizado todos los drivers de video y complementos tales como xna, etc.

[TEditLog.txt](https://github.com/TEdit/Terraria-Map-Editor/files/1158383/TEditLog.txt)

**Comment by arduano** [comment]
Firstly,
Can you please speak English.

Secondly, 
I'm with the same error.

**Comment by arduano** [comment]
Try these things:
Turn off MSI Afterburner or any other GPU monitoring software
Update your graphics drivers
Re-install DX9 https://www.microsoft.com/en-in/download/details.aspx?id=34429

**Comment by UnoRev3** [comment]
Thanks, i'll try.



Enviado desde mi smartphone Samsung Galaxy.


-------- Mensaje original --------
De: arduano <notifications@github.com>
Fecha: 26/7/17 9:33 (GMT-04:00)
Para: TEdit/Terraria-Map-Editor <Terraria-Map-Editor@noreply.github.com>
Cc: UnoRev3 <cris_jeremy12@hotmail.com>, Author <author@noreply.github.com>
Asunto: Re: [TEdit/Terraria-Map-Editor] Mi tedit no quiere arrancar (#1012)


Try these things:
Turn off MSI Afterburner or any other GPU monitoring software
Update your graphics drivers
Re-install DX9 https://www.microsoft.com/en-in/download/details.aspx?id=34429
