### ISSUE TITLE
Help me! An unhandled exception  has ocurred!

### ISSUE THREAD

**Issue by BasileusEfialtes** [TEdit/Terraria-Map-Editor#1014]
Is there any administrator? I want to use the tedit but everytime I use it the Unhandled exception error pops up. I can't open it or nothing. I've done it a few times but is always the same, what should i do?

**Comment by 948145647** [comment]
我也是这样不知道怎么回事

**Comment by BinaryConstruct** [comment]
Be sure you extracted the zip file and post the file listed. I've removed the image, as it contained a name in it.

**Comment by exarobibliologist** [comment]
I'm also having this issue. Here's my TEdit log it told me to attach.
[TEditLog.txt](https://github.com/TEdit/Terraria-Map-Editor/files/1518244/TEditLog.txt)

**Comment by ValeryDav** [comment]
I have the same problem, I attach the error log. As I understood, in my case the error is quite rare.
[TEditLog.txt](https://github.com/TEdit/Terraria-Map-Editor/files/1627200/TEditLog.txt)
