### ISSUE TITLE
TEdit crash when i try to open it.

### ISSUE THREAD

**Issue by LjNAndreiFTW** [TEdit/Terraria-Map-Editor#1017]
TEdit crashes every time when i try to open it, i don't know what it have.I'm using Win 8.1, Terraria 1.3.5.3 Steam, and yes it appears in Task Manager, but crashes at 49 MB Using Ram. *I know, bad english :) *

A relevant part of the error:

08-07-2017 20:08:44: Starting TEdit 3.10.17116.2025
08-07-2017 20:08:44: OS: Microsoft Windows NT 6.2.9200.0 
08-07-2017 20:08:44: Terraria v1.3.5.3 
08-07-2017 20:08:44: Terraria Data Path: E:\SteamLibrary\steamapps\common\Terraria\Content 
08-07-2017 20:08:45: Creating Undo cache: C:\Users\Andrei\AppData\Roaming\TEdit\undo_777341275 
08-07-2017 20:08:45: Error - Adapter 'ATI Radeon HD 4300/4500 Series' does not support the Reach profile.
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice..ctor(GraphicsAdapter adapter, GraphicsProfile graphicsProfile, PresentationParameters presentationParameters)
   at TEdit.UI.Xaml.XnaContentHost.GraphicsDeviceService.CreateDevice(IntPtr windowHandle, Int32 width, Int32 height) in C:\projects\terraria-map-editor\TEditXna\UI\Xaml\XnaContentHost\GraphicsDeviceService.cs:line 72 
08-07-2017 20:08:45: Error - Failed to initialize GraphicsDeviceService. See inner exception for details.

Rest of the error in the .log file .
[TEditLog.txt](https://github.com/TEdit/Terraria-Map-Editor/files/1205575/TEditLog.txt)

**Comment by BinaryConstruct** [comment]
It appears your GPU is not supported. Try updating your driver https://support.amd.com/en-us/kb-articles/Pages/Driver-Support-for-AMD-Radeon%E2%84%A2-HD-4000,-HD-3000,-HD-2000-and-older-Series.aspx
