### ISSUE TITLE
Expanding Map Editor Across Multiple Screens Causes Crash

### ISSUE THREAD

**Issue by meleniumshane90** [TEdit/Terraria-Map-Editor#1019]
[TEditLog.txt](https://github.com/TEdit/Terraria-Map-Editor/files/1226832/TEditLog.txt)

**Comment by BananaCake2Day** [comment]
I seem to have no problem trying to recreate the bug. However, I dont have _three_ monitors so maybe that might be it
![image](https://user-images.githubusercontent.com/13282174/31391987-15548d80-ada6-11e7-911c-0fb39488aeca.png)
