### ISSUE TITLE
[CLOSED] Error Help!

### ISSUE THREAD

**Issue by leleever** [TEdit/Terraria-Map-Editor#1021]
Hi everyone! So i decided to download TEdit, and when I open it, it writes "An unhandled exception has occured. Please copy log from:
C:\Users\user_name\Documents\My Games\Terraria\TEditLog.txt
to the GitHub Issues list.
The program will now exit."
I tried everything.
I need your Help.

**Comment by Rakanovan** [comment]
same dude i got that massage  to

**Comment by leleever** [comment]
where is admins?

**Comment by BinaryConstruct** [comment]
Please make sure you extracted all files in the zip file to a folder such a c:\tedit before running the program. If you still experience issues be sure to paste the contents of the log file here. Without the logs it is very difficult to help diagnose your issue.

**Comment by leleever** [comment]
Done, but it's still not working
[TEditLog.txt](https://github.com/TEdit/Terraria-Map-Editor/files/1309639/TEditLog.txt)

**Comment by BinaryConstruct** [comment]
Based on your log, you should check issue #751 for some tips.

**Comment by leleever** [comment]
Okay but i really need to Install W10 or Update drivers? Maybe you can make a new version of this?
nvm

**Comment by BinaryConstruct** [comment]
Usually force reinstalling DirectX and GPU drivers resolve the issue.
However, in a few cases the computer will not run TEdit and another must be
used.

**Comment by leleever** [comment]
Alright thank you anyway. I will wait for spring to buy myself new RAM.

**Comment by leleever** [comment]
Wait should install the Latest DirectX?

**Comment by BinaryConstruct** [comment]
Yes there are instructions on issue #751

**Comment by max79083** [comment]
this is my issues,pls:

[TEditLog.txt](https://github.com/TEdit/Terraria-Map-Editor/files/5963922/TEditLog.txt)

**Comment by max79083** [comment]
The  TEdit only cant open one archive.That archive can be opened,problems arose after i copy a pyramid to this archive.
