### ISSUE TITLE
Blocks, Walls and Sprites Do Not Properly Load/Save

### ISSUE THREAD

**Issue by BrushieDoo** [TEdit/Terraria-Map-Editor#1023]
## What were you doing when the issue occured?
After saving an in-depth creation, I saved the .wld file and booted up Terraria. Upon spawning in, none of the set tiles/walls/sprites were even placed.
## Can you reproduce the issue?
Yes, I've tried to load this multiple times with the same result.
## What version of Terraria are you using?
1.3.0.5.
## Post relevant contents of log or attach log file _**(very important)**_:
![teditxna_2017-10-01_13-53-01](https://user-images.githubusercontent.com/32437679/31057434-7e9065b4-a6b0-11e7-8d51-bbabef5d11d2.png)
![capture 2017-10-01 13_56_27](https://user-images.githubusercontent.com/32437679/31057435-85dccf38-a6b0-11e7-83aa-499be32f2cb7.png)

**Comment by BinaryConstruct** [comment]
Sometimes this can happen if Terraria restores it's backup, due to file
corruption or having the game open. Could you please try a couple small
edits (just a few tile changes and no container changes) and saves to make
sure that is working?
