### ISSUE TITLE
[Feature Request] Ability to copy and paste chest contents

### ISSUE THREAD

**Issue by FrostBytesf** [TEdit/Terraria-Map-Editor#1025]
Im trying to make a world where in it contains all the starter wiring equipment, and scrolling down to "Dart Trap" every stack is annoying. If this isnt possible, at least please add some filter like sprites.

**Comment by BinaryConstruct** [comment]
I believe you should be able to type the first letter of what you are
looking for to jump a little faster.

**Comment by BananaCake2Day** [comment]
Still though, it does take a little while to scroll down to Spike Ball Traps when using the S key.

**Comment by BinaryConstruct** [comment]
How about a duplicate button?

**Comment by BinaryConstruct** [comment]
Chests now have full text editing.
