### ISSUE TITLE
Black screen after rendering is done

### ISSUE THREAD

**Issue by pribamello** [TEdit/Terraria-Map-Editor#1026]
![sem titulo](https://user-images.githubusercontent.com/31387194/31415769-c934f218-adfb-11e7-8880-21b73891dda0.png)
When I load a map, after TEdit says it's done rendering, it only shows a black screen. I don't know how it happened, yesterday TEdit was working just fine, but today, out of nowhere, this error appeared.

**Comment by BinaryConstruct** [comment]
Check #751

**Comment by pribamello** [comment]
My directX version is 11.1, I have a Intel HD 3000 as graphic card and I'm using windows 10. Couldn't solve with #751.

**Comment by BinaryConstruct** [comment]
Ok, thanks for trying. That usually resolves similar issues. Could you
please attach your log file?

**Comment by pribamello** [comment]
[TEditLog.txt](https://github.com/TEdit/Terraria-Map-Editor/files/1375814/TEditLog.txt)
