### ISSUE TITLE
unhandled exception

### ISSUE THREAD

**Issue by ter12xd** [TEdit/Terraria-Map-Editor#1027]
i double click tedit and it just goes to unhandled exception. it happens everytime and i play on 1.3.5. 
[TEditLog.txt](https://github.com/TEdit/Terraria-Map-Editor/files/1400980/TEditLog.txt)

**Comment by BinaryConstruct** [comment]
Did you unzip all files in the download to a folder, such as c:\games\tedit?

**Comment by ter12xd** [comment]
yes but do you just download one of the files like the top one?

**Comment by BinaryConstruct** [comment]
Yes, you only need one of the versions, usually the most recent.

**Comment by ter12xd** [comment]
ok but it still doesn't work. I have a gtx 1050 ti could that be the problem?

**Comment by BinaryConstruct** [comment]
Please ensure you have all the requirements installed
https://github.com/TEdit/Terraria-Map-Editor/wiki/Install-Requirements

**Comment by ter12xd** [comment]
i have done the requirements but it still doesn't work.
[TEditLog - Copy (2).txt](https://github.com/TEdit/Terraria-Map-Editor/files/1416965/TEditLog.-.Copy.2.txt)

**Comment by BinaryConstruct** [comment]
Your only option may be to use a different PC. Sometimes there is incompatible hardware or software that is difficult to track down.
