### ISSUE TITLE
Delete Paste Area before Paste Action

### ISSUE THREAD

**Issue by BinaryConstruct** [TEdit/Terraria-Map-Editor#1028]
Several issues can occur if the target of the paste area is not cleared before performing paste. 

See #887 and #914

**Comment by Kojirremer** [comment]
Indeed. However, at least on previous versions they also need to be validated after clearing the affected tiles, but before pasting over.
Haven't tried doing it recently, so I don't know if you still need to validate between operations.

**Comment by BinaryConstruct** [comment]
This logic should be applied to any framed tile that is touched, so the
rest of it's tiles are removed. No more half-chests.
