### ISSUE TITLE
Find and Replace Sprites

### ISSUE THREAD

**Issue by mikeymike027** [TEdit/Terraria-Map-Editor#1033]
I'd like to have the capability of finding and replacing sprites. Just to give you an idea of why I'd like to be able to do this.

We're doing a factions play-through with 4 different teams. Each team is required to carry a large gem on their characters and if another team kills them, they collect the gem to turn in to score points.

Finding and replacing the gems on the map prevents other teams from crafting large gems and turning in without legitimately killing another player. The find and replace tool works just fine with gems found in stone blocks, but in order to deal with gem sprites on the map, I have to manually scan the map and delete each sprite with the pencil tool, which takes forever.

**Comment by BinaryConstruct** [comment]
It seems you've just enabled the issue triaging. I'm just scraping all issues from your repository and will give you some more information about this in a few minutes or so.

Because of the rate limit we can't scrape all information (including all comments and authors) right now - our system is already set up to scrape this in the next days over which the predictions will become more precise every day.

**Sit tight!**

**Comment by GregariousJB** [comment]
This just became a highly sought-after feature after Redigit added and then removed [the Luck feature to torches in 1.4](https://terraria.gamepedia.com/Luck#Torch_Luck).

Also see: https://www.reddit.com/r/Terraria/comments/gnfvc7/fixed_it/

And: https://www.reddit.com/r/Terraria/comments/gnm5xw/bad_luck_is_gone/

New worlds (like mine) now have hundreds or even thousands of torches that we'd like to replace with the biome version. I've been using TEdit to systematically delete each and every normal torch using the Brush tool with the intent of running back through the area in-game to place the correct biome torches. Having a way to Find & Replace certain torches within a selection box would make this a hundredfold faster.

**Comment by BinaryConstruct** [comment]
Using #1273 for future work on sprite tools
