### ISSUE TITLE
An unhandled exception has occurred

### ISSUE THREAD

**Issue by PEWdiePUGxd** [TEdit/Terraria-Map-Editor#1036]
What were you doing when the issue occured?
I started Tedit
Can you reproduce the issue?
Yes
What version of Terraria are you using?
v1.3.5.1

[TEditLog.txt](https://github.com/TEdit/Terraria-Map-Editor/files/1492062/TEditLog.txt)

**Comment by BinaryConstruct** [comment]
Duplicate of #751
