### ISSUE TITLE
My TEdit Won't Start Up!

### ISSUE THREAD

**Issue by Demonic680** [TEdit/Terraria-Map-Editor#1037]
My TEdit will not start up at all!
   
Staring up tedit which i just installed

 Yes. By starting up the exe file

1.3.5.3

Application: TEditXna.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.TypeInitializationException
Stack:
   at TEditXna.App.Main()
and
Faulting application TEditXna.exe, version 3.10.17116.2025, time stamp 0x590164ae, faulting module KERNEL32.dll, version 6.0.6002.18449, time stamp 0x4da47b2f, exception code 0xe0434352, fault offset 0x00000000000170cd, process id 0x%9, application start time 0x%10.

**Comment by BinaryConstruct** [comment]
Be sure to unzip to a folder.

**Comment by Demonic680** [comment]
i have unzipped the folders

**Comment by BinaryConstruct** [comment]
Could you please try some of the steps on these wiki pages? Usually one of
them will resolves any issues launching.
https://github.com/TEdit/Terraria-Map-Editor/wiki/Install-Requirements and
https://github.com/TEdit/Terraria-Map-Editor/wiki/Troubleshooting If these
do not work, trying a different PC may be the only option.

**Comment by Dogeislove** [comment]
Maybe the system you are using then it might be something with your computer.
