### ISSUE TITLE
Crashing during literally every occurrence

### ISSUE THREAD

**Issue by Sans15Undertale15** [TEdit/Terraria-Map-Editor#1040]
## Before you submit an issue, please read
 * If you get an unhandled exception, please _**check your log before posting**_.
 * If your log includes _**DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved**_
   * This is a known issue, do not create a new issue, please add your comments to #751
   * People have had the most luck in Windows 7 with updating to DirectX 11.1
     This is found in windows update in the optional updates section or by
     following directions here 
   * https://support.microsoft.com/en-us/kb/179113
 * Please fill out the questions below
 * Instead of copy/pasting text you can attach the entire log file.
 * If your world file is less than 25MB, you can attach it as well.
   **It doesn't accept .wld files, sorry**

## What were you doing when the issue occured?
I was making a elevator, but with less effort, using your program. I then, went to sprites, to get a demon alter in my base, and then it crashed. I did this a number of times. Also, when loading it up, it seems to be having an issue showing the blocks for about 12 seconds the first time, and upon re-opening, the blocks only displayed if I zoomed in. (By displayed, I mean like visible, and not how they look in the game.)
## Can you reproduce the issue?
I have done this a lot, and they always crash... So yes!
## What version of Terraria are you using?
1.3.5.3
## Post relevant contents of log or attach log file _**(very important)**_:
[TEditLog.txt](https://github.com/TEdit/Terraria-Map-Editor/files/1511537/TEditLog.txt)

**Comment by BinaryConstruct** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are #1009 (Cannot Load World), and #998 (Whenever I try to load a world, it comes up with an unhandled exception).

**Comment by Sans15Undertale15** [comment]
wait, how did you respond so fast BinaryConstruct...

**Comment by BinaryConstruct** [comment]
Bots...

**Comment by BinaryConstruct** [comment]
Also, System.OutOfMemoryException was the issue. How much system ram do you have? TEdit is pretty RAM heavy, especially with large worlds and large operations such a a big fill.

**Comment by Sans15Undertale15** [comment]
I have 2 or 4 GB of ram, but that issue is also the reason my mods dont
load on tmodloader.... So if I get more ram will that be fixed?

**Comment by BinaryConstruct** [comment]
For large world's TEdit really needs a 64bit machine with 6+GB ram. Small
world __might__ work ok with less.
