### ISSUE TITLE
[Feature] Tile Search, Recently Used Tiles, Texture In selection window

### ISSUE THREAD

**Issue by ghost** [TEdit/Terraria-Map-Editor#1041]
I am using PC Terraria v1.3.5, and I suggest that a searchbar be added to the blocks and walls section, as it is very annoying to scroll through all of the blocks and walls to find the one I want.

**Comment by uselessscat** [comment]
I'm in favor of this, is dificult to paint scrolling the list. Also It is more difficult if you do not speak English or do not know the names of the blocks in English.

Another rather useful improvement would be to add a toolbar with the list of the last used blocks.

**Comment by BinaryConstruct** [comment]
Usability Improvements pt.2 #1274
