### ISSUE TITLE
Unhandled exception

### ISSUE THREAD

**Issue by krushl** [TEdit/Terraria-Map-Editor#1042]
[TEditLog.txt](https://github.com/TEdit/Terraria-Map-Editor/files/1527030/TEditLog.txt)
pls help

**Comment by BinaryConstruct** [comment]
[GitMate.io](https://gitmate.io) thinks a possibly related issue is #963: Unhandled exception.

**Comment by BinaryConstruct** [comment]
This is a duplicate of #751. Please see that issue for troubleshooting tips.
