### ISSUE TITLE
not working at all

### ISSUE THREAD

**Issue by ToMuchTNT** [TEdit/Terraria-Map-Editor#1043]
I am using the latest version of both tedit and terraria and the changes i am making in tedit are not doing anything at all in game. i have saved, multiple times. i just want to get rid of the corruption... please help me?

**Comment by BinaryConstruct** [comment]
It is possible that Terraria is loading the backup copy of your world. You can try and move this file while Terraria is closed and then make your edits. Once the new file is save launch Terraria and try to load it.
