### ISSUE TITLE
[FEATURE REQUEST] Biome maker

### ISSUE THREAD

**Issue by ThatsFluke** [TEdit/Terraria-Map-Editor#1047]
Please add a biome-maker that can spawn any biome in the certain box/rectangle. e.g a hell-biome, ocean biome, mushroom biome etc. but makes it inside the box.

-Tedit enthusiast/lover, Beastingaming36

**Comment by Kojirremer** [comment]
That feature used to be on the Morph setting, but it got simplified and most of those biomes were removed.

**Comment by BinaryConstruct** [comment]
Using #1262 for future work on world generation
Using #533 for future work on morph tool
