### ISSUE TITLE
[FEATURE] Pixel art injector

### ISSUE THREAD

**Issue by ThatsFluke** [TEdit/Terraria-Map-Editor#1049]
Please also add a **Pixel Art Injector** which if you get a grid pixel art, it will draw/place the blocks with appropriate color. This may be useful for Pixel Art people.

-_Tedit enthusiast/lover, Beastingaming36_

ADD ME ON STEAM: Beastingaming36

**Comment by JDSammy** [comment]
So lets say you got a pixel building or something, it would try and replicate the colours by placing a certain block? If so, could we also have it so it can paint the blocks to further the colours being made to the best of TEdit's ability?

**Comment by Beastingaming36** [comment]
Yes like that. It would be really useful.

-TEdit enthusiast/lover, Beastingaming36

**Comment by BinaryConstruct** [comment]
@ThatsFluke Have you tried these? https://github.com/TEdit/Terraria-Map-Editor/wiki/Image-Schematics
