### ISSUE TITLE
Morph tool feature request: cave decorations upon conversion

### ISSUE THREAD

**Issue by AkiraWhitlock** [TEdit/Terraria-Map-Editor#1053]
A major use of Tedit i use for my world is converting crimson/corruption/hallow back to its natural form
with that i have noticed when i convert an underground crimson biome to normal biome the cave decorations still are crimson 

I may be missing a feature that i do not know about but as a future suggestion:
: have it when biome blocks are replaced by natural counterparts the decorations are changed with them similar to how trees get converted

**Comment by AkiraWhitlock** [comment]
Maybe decorative grass too

**Comment by ZinMystery** [comment]
Yeah, i use it for the same purpose. Whenever I try to select those blocks it doesn't do anything so it would be great if we could select those and delete them or swap them to stone/ect.

**Comment by BinaryConstruct** [comment]
Using #533 for future work on morph tool
