### ISSUE TITLE
just started

### ISSUE THREAD

**Issue by GoldTheEevee** [TEdit/Terraria-Map-Editor#1054]
so i just started t edit and its controls feel awkward like you can place trees chest hearts and in general cant do many things. is this me being blind or is it just hard? and when you create a world its flat...NOTHING. its just bland.

**Comment by ahamling27** [comment]
Check out my guide on how to use TEdit 3. https://forums.terraria.org/index.php?threads/a-guide-to-tedit-3.44439/

That should help you get the basics of the program. TEdit is not meant to generate worlds like Terraria, you can use Terraria to generate worlds if you would like to generate a new world. 

Cheers!

**Comment by GoldTheEevee** [comment]
I can close it. Thanks!
