### ISSUE TITLE
Crash when starting it

### ISSUE THREAD

**Issue by manlego031** [TEdit/Terraria-Map-Editor#1057]
An unhandled execption has ocured. Please copy the log from:
C:/User/(mypcname)/Documents/My games/Terraria/TEditLog.txt
 to the GitHub Issues list.
The program will now exit.
[TEditLog.txt](https://github.com/TEdit/Terraria-Map-Editor/files/1635380/TEditLog.txt)

**Comment by porter2889** [comment]
Ami that happens to me, even when we can see a solution I hope it will be soon

**Comment by porter2889** [comment]
[TEditLog.txt](https://github.com/TEdit/Terraria-Map-Editor/files/1638461/TEditLog.txt)

**Comment by manlego031** [comment]
@porter2889 what windows do you have?

**Comment by porter2889** [comment]
I have already found a solution to the problem which is easy for you to flatten data pck plugins to windows
1.-  dotNetFx45_Full_setup
2.-  NDP46-KB3045557-x86-x64-AllOS-ENU
3.-  vcredist_x86
4.-  Windows6.1-KB2670838-x86
6,-  xnafx40_redist
  

I already had them but others I was missing so I could solve that error that marked

**Comment by porter2889** [comment]
windows 7

**Comment by manlego031** [comment]
sh** i have low memory

**Comment by AndROshAYTNC** [comment]
An unhandled execption has ocured. Please copy the log from:
C:/User/(mypcname)/Documents/My games/Terraria/TEditLog.txt
to the GitHub Issues list.
The program will now exit.
[TEditLog.txt](https://github.com/TEdit/Terraria-Map-Editor/files/1799250/TEditLog.txt)

**Comment by BinaryConstruct** [comment]
@AndROshAYTNC please see #751
