### ISSUE TITLE
Copy Paste cancelsl pencil

### ISSUE THREAD

**Issue by SwagnLag** [TEdit/Terraria-Map-Editor#1061]
When I use Copy Paste and then use the pencil or brush or Morph it doesnt work until I reset the programm

**Comment by BinaryConstruct** [comment]
If you still have a region selected, you will have to clear the selection first.

**Comment by SwagnLag** [comment]
how do I clear?

**Comment by BinaryConstruct** [comment]
Please see https://github.com/TEdit/Terraria-Map-Editor/wiki/Toolbar#selection-tool-s
