### ISSUE TITLE
Multiplying chests?

### ISSUE THREAD

**Issue by Lunasycthe** [TEdit/Terraria-Map-Editor#1062]
Hi, I'm really new to editing Terraria and I'm bad with technical stuff, so I'm hoping I just missed something here... I've been enjoying making a perfect world by copy pasting bits of other maps I generated together. I copied some underground desert/jungle structure with a single chest into the map, and now it keeps adding a treasure chest every time it tries to autosave or when I manually save... If I leave it open I end up with notification spam with increasing amounts of treasure chests from the autosave! As I type I now have 1005 when I started with 1001. I erased two chests to make room for that one chest in the structure, so I should start with 999... I read dressers sometimes count as chests, but I cant see anything else in the structure besides a bookcase, work tables, statues, a hanging and an anvil. I'm hoping this has happened before and has a fix I dont know about... I already lost an awesome coral reef to every single edited world save in the folder being corrupted for some reason. >.<' I'm having no luck and almost want to give up if I get anymore mysterious problems... I've included the broken world below if needed, the notifications happen when its left to autosave, or as soon as I try to save. I dont even know where 1000 chests can be hiding in a small mostly natural world without me adding tons... I'm using the most up to date Terraria and Tedit as far as I know, unless theres been an update in the last couple of days.

**Comment by BinaryConstruct** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/TEdit/Terraria-Map-Editor/issues/10 (Chest list improvement), https://github.com/TEdit/Terraria-Map-Editor/issues/387 (Chest issue), https://github.com/TEdit/Terraria-Map-Editor/issues/21 (Chest clicking), https://github.com/TEdit/Terraria-Map-Editor/issues/419 (Chest Row Selection), and https://github.com/TEdit/Terraria-Map-Editor/issues/32 (Incomplete Chest List).

**Comment by Lunasycthe** [comment]
A friend found the problem! They managed to locate a ting single square of chest that was throwing all sorts of errors because it wasnt in a whole piece, which was weird because I had nothing to do with it... So if anyone ever has this problem check you dont have a little chunk of chest somewhere lol.
