### ISSUE TITLE
TEdit3Installer.wixproj won't open

### ISSUE THREAD

**Issue by SirPuppet** [TEdit/Terraria-Map-Editor#1063]
The installer file cannot be opened, so I must use the .sln files to open TEdit, which is very tedious.
## Can you reproduce the issue?
Yes
## What version of Terraria are you using?
1.3.5.3

Do I need a special application to open the installer?

**Comment by BinaryConstruct** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/TEdit/Terraria-Map-Editor/issues/425 (world won't open), https://github.com/TEdit/Terraria-Map-Editor/issues/1005 (Tedit will not stay open), https://github.com/TEdit/Terraria-Map-Editor/issues/663 (tEdit won't open ), https://github.com/TEdit/Terraria-Map-Editor/issues/889 (I can't open edited worlds.), and https://github.com/TEdit/Terraria-Map-Editor/issues/215 (TConfig World Not Opening).

**Comment by SirPuppet** [comment]
No. No it is not.

**Comment by BinaryConstruct** [comment]
If you are trying to compile yourself, use TEditNoInstaller.sln. If you just want to use the application, you can use the precompiled version on the GitHub relases page.

**Comment by SirPuppet** [comment]
Ok, so I just messed up. I fixed it. Didn't check the bin folder. Thanks anyway!
