### ISSUE TITLE
TEdit Won't Even Open

### ISSUE THREAD

**Issue by pkpyre** [TEdit/Terraria-Map-Editor#1064]
TEdit refuses to open. Tells me: "An unhandled exception has occurred," and tells me to put the log here on the issues list. I've tried running as an administrator- doesn't work. The versions seem to be correct.
[TEditLog.txt](https://github.com/TEdit/Terraria-Map-Editor/files/1839511/TEditLog.txt)

**Comment by BinaryConstruct** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/TEdit/Terraria-Map-Editor/issues/663 (tEdit won't open ), https://github.com/TEdit/Terraria-Map-Editor/issues/344 (I can't open up TEdit...), https://github.com/TEdit/Terraria-Map-Editor/issues/759 (TEdit can't open any worlds, doesn't recognize them.), https://github.com/TEdit/Terraria-Map-Editor/issues/1005 (Tedit will not stay open), and https://github.com/TEdit/Terraria-Map-Editor/issues/964 (TEdit doesn't open).

**Comment by pkpyre** [comment]
The files were all extracted, tried extracting them to different locations, and have .NET 4.5 installed. Still not working.

**Comment by BinaryConstruct** [comment]
This is the same issue as #751
