### ISSUE TITLE
Whenever I change the name of my world, my mini-map data disappears? Help?

### ISSUE THREAD

**Issue by kodiak18** [TEdit/Terraria-Map-Editor#1067]
## Before you submit an issue, please read
 * If you get an unhandled exception, please _**check your log before posting**_.
 * If your log includes _**DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved**_
   * This is a known issue, do not create a new issue, please add your comments to #751
   * People have had the most luck in Windows 7 with updating to DirectX 11.1
     This is found in windows update in the optional updates section or by
     following directions here 
   * https://support.microsoft.com/en-us/kb/179113
 * Please fill out the questions below
 * Instead of copy/pasting text you can attach the entire log file.
 * If your world file is less than 25MB, you can attach it as well.

**Comment by BinaryConstruct** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/TEdit/Terraria-Map-Editor/issues/468 (World Name), https://github.com/TEdit/Terraria-Map-Editor/issues/773 (HELP!!!), https://github.com/TEdit/Terraria-Map-Editor/issues/584 (Unsaved world data), https://github.com/TEdit/Terraria-Map-Editor/issues/998 (Whenever I try to load a world, it comes up with an unhandled exception), and https://github.com/TEdit/Terraria-Map-Editor/issues/1039 (cannot apply mod).

**Comment by kodiak18** [comment]
Any additional help? cant find any results on the other pages

**Comment by BinaryConstruct** [comment]
This is a known "feature" of Terraria. Unfortunately, the only work around is to rename your world before you explore it. Also, any edits made will not be shown in minimap data.
