### ISSUE TITLE
TEdit randomly crashes, don't know why

### ISSUE THREAD

**Issue by stakkuu** [TEdit/Terraria-Map-Editor#1068]
[TEditLog.txt](https://github.com/TEdit/Terraria-Map-Editor/files/1865874/TEditLog.txt)

TL:DR Giving me "Index was out of range. Must be non-negative and less than the size of the collection." error

**Comment by BinaryConstruct** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/TEdit/Terraria-Map-Editor/issues/896 (Crashing), https://github.com/TEdit/Terraria-Map-Editor/issues/209 (Crash), https://github.com/TEdit/Terraria-Map-Editor/issues/121 (Crash), https://github.com/TEdit/Terraria-Map-Editor/issues/120 (Crash), and https://github.com/TEdit/Terraria-Map-Editor/issues/543 (TEdit crashes).
