### ISSUE TITLE
T edit crash 

### ISSUE THREAD

**Issue by Masab46** [TEdit/Terraria-Map-Editor#1069]
I try to open TEdit 3.10 for Terraria 1.3.5 , then I received a mistake.
![pymfufqbivq](https://user-images.githubusercontent.com/38030278/38234356-50b6c7c6-3726-11e8-9534-0050f6d8e345.jpg)
[TEditLog.txt](https://github.com/TEdit/Terraria-Map-Editor/files/1870512/TEditLog.txt)

Terraria ver - 1.3.5.3 , licensed.

**Comment by BinaryConstruct** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/TEdit/Terraria-Map-Editor/issues/543 (TEdit crashes), https://github.com/TEdit/Terraria-Map-Editor/issues/475 (TEDIT crashes), https://github.com/TEdit/Terraria-Map-Editor/issues/177 (World Crash), https://github.com/TEdit/Terraria-Map-Editor/issues/896 (Crashing), and https://github.com/TEdit/Terraria-Map-Editor/issues/120 (Crash).

**Comment by Masab46** [comment]
I can not even open it

**Comment by BinaryConstruct** [comment]
This is a duplicate of #751. Please see that issue for tips.
