### ISSUE TITLE
Load Failed, No Backup Found

### ISSUE THREAD

**Issue by asassajackal259** [TEdit/Terraria-Map-Editor#1071]
I am using Tedit V3.10 and Terraria V1.3.5.3 and every time I edit the world and try to load it IG the world won't load, not sure what to try. I checked the log and all it has is startup stuff, no errors or anything like that.

**Comment by BinaryConstruct** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/TEdit/Terraria-Map-Editor/issues/483 (Load Failed), https://github.com/TEdit/Terraria-Map-Editor/issues/482 (Load Failed), https://github.com/TEdit/Terraria-Map-Editor/issues/256 (Load Failed), https://github.com/TEdit/Terraria-Map-Editor/issues/233 (No Backup Found), and https://github.com/TEdit/Terraria-Map-Editor/issues/234 (Map Loading Issues "File not found" and "Backup not found" ).

**Comment by ahamling27** [comment]
Please head to the download page: http://www.binaryconstruct.com/downloads/

And download the third option as shown here: https://i.imgur.com/Rf2gkGE.png

You should be able to force load a world in it and re-save it so it will open in Terraria. The newest versions are not saving correctly and they need to be removed/fixed. The last TEdit for 1.3.5 that was released in 2017 seems to work better.

**Comment by BinaryConstruct** [comment]
These commits have been reverted and the offending versions removed from the github releases page. Let me know if the newer version work. Thanks!
