### ISSUE TITLE
tedit error (file cant open in terraria(corrupted) and tedit(error))

### ISSUE THREAD

**Issue by funterrariaxxx** [TEdit/Terraria-Map-Editor#1072]
## What were you doing when the issue occured?
using tedit
## Can you reproduce the issue?
yes
## What version of Terraria are you using?
1.3.5
## Post relevant contents of log or attach log file _**(very important)**_:
![tedt](https://user-images.githubusercontent.com/38351002/38732525-4ac4234a-3ed3-11e8-984d-c82b49089aca.PNG)

**Comment by BinaryConstruct** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/TEdit/Terraria-Map-Editor/issues/690 (Possible conflict opening TEdit too soon after closing Terraria), https://github.com/TEdit/Terraria-Map-Editor/issues/769 (tedit won't open error pops up), https://github.com/TEdit/Terraria-Map-Editor/issues/344 (I can't open up TEdit...), https://github.com/TEdit/Terraria-Map-Editor/issues/663 (tEdit won't open ), and https://github.com/TEdit/Terraria-Map-Editor/issues/797 (TEdit crashing on open).

**Comment by funterrariaxxx** [comment]
using 3.10 version (newest) tedit

**Comment by soufflenote** [comment]
Just chiming in to add I had the exact same issue, same error message! I haven't found a way around it yet either

**Comment by Thisnameisthebestname** [comment]
has anyone found how to fix this issue?

**Comment by ahamling27** [comment]
Please head to the download page: http://www.binaryconstruct.com/downloads/

And download the third option as shown here: https://i.imgur.com/Rf2gkGE.png

You should be able to force load a world in it and re-save it so it will open in Terraria. The newest versions are not saving correctly and they need to be removed/fixed. The last TEdit for 1.3.5 that was released in 2017 seems to work better.

**Comment by soufflenote** [comment]
This worked, thank you so much!

**Comment by ahamling27** [comment]
You are very welcome!

**Comment by BinaryConstruct** [comment]
These commits have been reverted and the offending versions removed from the github releases page. Let me know if the newer version work. Thanks!
