### ISSUE TITLE
No load

### ISSUE THREAD

**Issue by Thisnameisthebestname** [TEdit/Terraria-Map-Editor#1073]
https://gyazo.com/c6fefc90139e50509c9d392aca12c581 

Created a world through Tedit, steam version terraria, and tedit 3.10, 

world would not load in game, says no backup, try and reload it in tedit got the error that is in the screenshot. 

Edit 1, anyworld i save with tedit does this, no changes or minor changes, tedit is corrupting worlds just by saving them>?

**Comment by Thisnameisthebestname** [comment]
@BinaryConstruct can i get a admin or mod to help me solve this

**Comment by ahamling27** [comment]
Please head to the download page: http://www.binaryconstruct.com/downloads/

And download the third option as shown here: https://i.imgur.com/Rf2gkGE.png

You should be able to force load a world in it and re-save it so it will open in Terraria. The newest versions are not saving correctly and they need to be removed/fixed. The last TEdit for 1.3.5 that was released in 2017 seems to work better.

**Comment by BinaryConstruct** [comment]
These commits have been reverted and the offending versions removed from the github releases page. Let me know if the newer version work. Thanks!
