### ISSUE TITLE
Download links removed on Terraria Community Forums

### ISSUE THREAD

**Issue by Jofairden** [TEdit/Terraria-Map-Editor#1074]
The download links for this tool have been removed on TCF, because a mod didn't trust the links
Thread: https://forums.terraria.org/index.php?threads/tedit-terraria-map-editor.43822/
I think this is the best way to get the message known, since the thread's author's account states last seen on Sep 11, 2016

**Comment by BinaryConstruct** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/TEdit/Terraria-Map-Editor/issues/370 (Download), https://github.com/TEdit/Terraria-Map-Editor/issues/4 (Download?), https://github.com/TEdit/Terraria-Map-Editor/issues/395 (Download link down), https://github.com/TEdit/Terraria-Map-Editor/issues/389 (Download Problems), and https://github.com/TEdit/Terraria-Map-Editor/issues/957 (Direct Download).

**Comment by BinaryConstruct** [comment]
I've removed adfly from the download links. If the mod feels inclined they can add the links back. I'm not going to interfere with moderator actions on a forum.
