### ISSUE TITLE
TEdit crashes on startup

### ISSUE THREAD

**Issue by Bersalius** [TEdit/Terraria-Map-Editor#1078]
I instaled the program, and used it just 1 time (but no textures were visible). So I closed the program and tryied again, but it won't open. There is just a message of error, and a repport.

## What were you doing when the issue occured?
Trying to open TEdit.
## Can you reproduce the issue?
Yes, every time I try to run the Editor.
## What version of Terraria are you using?
1.3.5.3
## Post relevant contents of log or attach log file _**(very important)**_:
My video card is a AMD Radeon HD 6570.
I can run Terraria with no problem.
I have Windows 7 Ultimate Service Pack 1.

[TEditLog.txt](https://github.com/TEdit/Terraria-Map-Editor/files/1977163/TEditLog.txt)

**Comment by Bersalius** [comment]
Sorry if I'm being anoying, but, what can I do to fix this? I don't want to upgrade my Windows to 10, and I don't have a NVIDIA to check as the instructions... So, what can I do?

**Comment by Bersalius** [comment]
Hello again. I fixed the problem by updating my DirectX as BinaryConstruct said in the problem #751 down in the coments to smgamermat77.

He said to update the DirectX using this special link, because Windows 7 have a problem wiht DirectX versions, as the new ones are avaible only to the next generations. So, here is what he sent:

"DX 11.1 is included with the platform update. https://www.microsoft.com/en-us/download/details.aspx?id=36805"

After reiniciating my computer, the program worked with no problem.

**Comment by BinaryConstruct** [comment]
Thanks for the update, I'll make sure to put that at the top of 751 notes.
