### ISSUE TITLE
tEdit Instantly Closes on Startup

### ISSUE THREAD

**Issue by Sepheris** [TEdit/Terraria-Map-Editor#1079]
## What were you doing when the issue occured?
Trying to run the program

## Can you reproduce the issue?
Yes. Every time I attempt to run the program

## What version of Terraria are you using?
v1.3.5.3

## Post relevant contents of log or attach log file _**(very important)**_:
tEdit doesn't create an error log, though it does appear within my task manager whenever I make an attempt to run it. I had to grab the error log from the Event Viewer

https://pastebin.com/XGgKnBVw

**Comment by BinaryConstruct** [comment]
Be sure you have unzipped all files, have the lated .net framework 4. and the latest windows 7 service pack.
