### ISSUE TITLE
TEditor / <AltC>

### ISSUE THREAD

**Issue by DrWinterss** [TEdit/Terraria-Map-Editor#1080]
I have tried to get TEditor to work and it won't start and when I went looking for something to do, to fix it. I noticed that I have to change the "AltC", as I have not installed Terraria in the normal place.  But when I try it does not work and I can't figure out why 

I have installed terraria in this location:
This Pc /  (E): / Steam / steamapps / common / terraria 

I'm using Terraria 1.3.5
I can't post a log as it did not make one

Does anybody know what to do?
Is there someone who can write the line I have to put in or point me in a direction?
I am sorry if I'm not supposed to write here, but if I'm not where do I?

thanks in advance.

**Comment by BinaryConstruct** [comment]
Be sure you have unzipped all files to a folder, such as e:\games\tedit. You might try followed all the steps in troubleshooting on the wiki, or check issue #751 for how to install Windows 7 service pack.
