### ISSUE TITLE
Map Missing

### ISSUE THREAD

**Issue by SMARTY247** [TEdit/Terraria-Map-Editor#1084]
## What were you doing when the issue occurred?
I downloaded. Then I went on my worlds to go check, but it was not there. Also I checked everywhere (even the steam local files!) But nothing.
## Can you reproduce the issue?
Yes.
## What version of Terraria are you using?
1.3.5.2 (Tmodloader 0.10.4.1) T-Edit (NEWEST VERSION) Beta
## Post relevant contents of log or attach log file _**(very important)**_:
I use Tmodloader. I cant do the mods as sadly their in the KBs. Also there hidden.

**Comment by BinaryConstruct** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/TEdit/Terraria-Map-Editor/issues/213 (Add NPCs to map), https://github.com/TEdit/Terraria-Map-Editor/issues/561 (Map record Initiated?), https://github.com/TEdit/Terraria-Map-Editor/issues/644 (missing items), https://github.com/TEdit/Terraria-Map-Editor/issues/27 (Missing objects/tiles), and https://github.com/TEdit/Terraria-Map-Editor/issues/26 (Missing objects/tiles).

**Comment by SMARTY247** [comment]
I'm also using the newest (beta) version.

**Comment by SMARTY247** [comment]
None of them helped. Its more of. MY FILES ARE GONE?! Than CANT FIND WORLD.

**Comment by BinaryConstruct** [comment]
Tedit does not support modded worlds. However, it will give a warning and fail to load the files. Try looking in you "my games/Terraria" folder for backup files of you world, and rename them to .wld.

**Comment by SMARTY247** [comment]
## OK. I will find a way to get my worlds (I have a vanilla back up.)

**Comment by SMARTY247** [comment]
I had my world on cloud! that's why. xD (facepalm)
