### ISSUE TITLE
Can not run the TEdit

### ISSUE THREAD

**Issue by nibba123** [TEdit/Terraria-Map-Editor#1085]
It says copy the TEditlog to the github :v Any idea?
[TEditLog.txt](https://github.com/TEdit/Terraria-Map-Editor/files/2071845/TEditLog.txt)

**Comment by BinaryConstruct** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/TEdit/Terraria-Map-Editor/issues/864 (Cannot start tedit), https://github.com/TEdit/Terraria-Map-Editor/issues/146 (I can't use the TEdit!), https://github.com/TEdit/Terraria-Map-Editor/issues/344 (I can't open up TEdit...), https://github.com/TEdit/Terraria-Map-Editor/issues/757 (Can't load working world with TEdit), and https://github.com/TEdit/Terraria-Map-Editor/issues/699 (Failed to verify Terraria Paths. TEdit may not run properly. ).

**Comment by GZiddy** [comment]
I also seem to have this same issue.  Read though all the related issues and nothing fixes it or changes the error log.
[TEditLog.txt](https://github.com/TEdit/Terraria-Map-Editor/files/2087183/TEditLog.txt)

**Comment by BinaryConstruct** [comment]
The device removed error can occur if you have multiple applications that use the GPU and alt-tab or switch between them. Only a few GPUs and driver combos seem to have this issue. Will the application run with no other apps running?

**Comment by BinaryConstruct** [comment]
Most issues I've seen are windows 7 with Nvidia+Intel, but I think that is just what most people have, not necessarily the cause.

**Comment by BinaryConstruct** [comment]
If you have dual graphics, such as Intel integrated and Nvidia, try just using the Intel you for TEdit. Sometimes this helps
