### ISSUE TITLE
Error running TEdit

### ISSUE THREAD

**Issue by SanyGGame** [TEdit/Terraria-Map-Editor#1087]
When I turn on the program, it crashes with this log
[TEditLog.txt](https://github.com/TEdit/Terraria-Map-Editor/files/2114226/TEditLog.txt)
Help me pls

**Comment by BinaryConstruct** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/TEdit/Terraria-Map-Editor/issues/285 (TEdit Startup error), https://github.com/TEdit/Terraria-Map-Editor/issues/386 (TEdit Install Error), https://github.com/TEdit/Terraria-Map-Editor/issues/946 (Error.), https://github.com/TEdit/Terraria-Map-Editor/issues/703 (Error), and https://github.com/TEdit/Terraria-Map-Editor/issues/320 (Error).

**Comment by BinaryConstruct** [comment]
Please see #751
