### ISSUE TITLE
An unhandled exception has occured when using 'Find Chests With' plugin

### ISSUE THREAD

**Issue by asrielmeemurr** [TEdit/Terraria-Map-Editor#1088]
## What were you doing when the issue occured?
Using the 'Find Chests With' plugin to find chests containing the Lava Charm, an unhandled exception error occurs when I try to search for the item.

## Can you reproduce the issue?
Yes, this error occurs every time I try to use the plugin to search for chests containing a specific item, and other items as well, not just the Lava Charm.

## What version of Terraria are you using?
1.3.5.3

## Post relevant contents of log or attach log file _**(very important)**_:
[TEditLog.txt](https://github.com/TEdit/Terraria-Map-Editor/files/2152777/TEditLog.txt)

**Comment by BinaryConstruct** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/TEdit/Terraria-Map-Editor/issues/388 (An Unhandled exception?), https://github.com/TEdit/Terraria-Map-Editor/issues/1036 (An unhandled exception has occurred), https://github.com/TEdit/Terraria-Map-Editor/issues/1010 (Unhandled exception), https://github.com/TEdit/Terraria-Map-Editor/issues/1042 (Unhandled exception), and https://github.com/TEdit/Terraria-Map-Editor/issues/779 (Unhandled Exception).
