### ISSUE TITLE
World Corrupting after using TEdit

### ISSUE THREAD

**Issue by EastArctica** [TEdit/Terraria-Map-Editor#1089]
Ok. I'm not gonna lie i am using Terraria V1.3.3. So i can make a new map and it will run just fine. But once i load it into TEdit V3.10.18105 I can edit the world and all. For this example im not going to edit anything in the world.
I will make a Small Normal world Named `Test` for this example. Here is that 'Test.wld' File. Github says its not supported so i will upload it to GDrive: [Here You Go](https://drive.google.com/file/d/1lEti5oNAOi2zJvRhR2R724TiFmhTCHxC/view?usp=sharing)
Then i take that file and put it in TEdit dont edit anything and save the file. 
When i load it up in terraria it pops up as a Unknown Corrupted World.
Please help TY in advance
BTW i have used the 1.3.3 version  of TEdit and the same thing happens
Edit: ddint add corrupted file [Corrupted Version](https://drive.google.com/drive/folders/1-9QljvdOSoG6U_gZ_NXD90gu1B4vuEBh?usp=sharing)

**Comment by BinaryConstruct** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/TEdit/Terraria-Map-Editor/issues/301 (Terraria freezes after loading TEdit Ocean World), https://github.com/TEdit/Terraria-Map-Editor/issues/638 (TEdit crashes after loading world), https://github.com/TEdit/Terraria-Map-Editor/issues/754 (Tedit world creator closes), https://github.com/TEdit/Terraria-Map-Editor/issues/374 (Crash when saving a world generated by TEdit), and https://github.com/TEdit/Terraria-Map-Editor/issues/565 (Unable to open crashed Worlds with TEdit!).

**Comment by EastArctica** [comment]
it is none of the above

**Comment by BinaryConstruct** [comment]
For 1.3.3 you have to use an older version of TEdit. I recommend updating to the latest Terraria and using the latest TEdit.

**Comment by EastArctica** [comment]
oh yeah i forgot to add at the beginning that my game is torrented

**Comment by EastArctica** [comment]
so i ccant update
