### ISSUE TITLE
Can't launch TEdit

### ISSUE THREAD

**Issue by Chocolatines** [TEdit/Terraria-Map-Editor#1090]
Hi everyone,
Yes this is yet another post saying that TEdit won't launch, but after looking for a long time, I didn't find a solution to my problem.
I'm going to be as precise as possible.
I downloaded the TEdit 3.10 version for Terraria 1.3.5 from http://www.binaryconstruct.com/downloads/
So like any download, the file is in Download. I extracted it and the extraction went to Download. At this point, everything should be clear. But when i start the TEditXNA.exe, nothing happens. I looked on the process tab and the app launch for like 1 second and close. I haven't got a TEdit 3 folder on Program Files (x86) nor Program Files so I can't get a log.
What should I do to fix this ? I'm on Windows 10 by the way,
Thanks for the help,
Chocolatines

**Comment by BinaryConstruct** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/TEdit/Terraria-Map-Editor/issues/864 (Cannot start tedit), https://github.com/TEdit/Terraria-Map-Editor/issues/1085 (Can not run the TEdit), https://github.com/TEdit/Terraria-Map-Editor/issues/1045 (TEDIT DON'T WANT TO LAUNCH (unhandled exception)), https://github.com/TEdit/Terraria-Map-Editor/issues/344 (I can't open up TEdit...), and https://github.com/TEdit/Terraria-Map-Editor/issues/146 (I can't use the TEdit!).

**Comment by Chocolatines** [comment]
Well, none of these works :/

**Comment by BinaryConstruct** [comment]
Check tips here: https://github.com/TEdit/Terraria-Map-Editor/wiki#issues-crashes-

**Comment by Chocolatines** [comment]
Hey it just worked, apparently Bitdefender was blocking something and only notified me after 20 attempts.
Working fine now !

**Comment by TheBlueMoonrose** [comment]
I download TEdit and it's not working on my desktop but works on my HP Stream but the blocks wont show when i zoom in, like when i zoom in on the temple to remove the door i reli can't see the door... or anything just blur blocks also i have this issue also with the unhandled exception has occured ??? it only shows on my desktop
