### ISSUE TITLE
Can't find doors

### ISSUE THREAD

**Issue by SoupahKnux** [TEdit/Terraria-Map-Editor#1091]
Can't find any doors in the "Tile" Section. On ID 9 it just skips. Can you help me? (copy-pasting doesn't help)

**Comment by BinaryConstruct** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/TEdit/Terraria-Map-Editor/issues/869 (Cannot find file directory.), https://github.com/TEdit/Terraria-Map-Editor/issues/349 (TEdit 3 Cannot be Found), https://github.com/TEdit/Terraria-Map-Editor/issues/233 (No Backup Found), https://github.com/TEdit/Terraria-Map-Editor/issues/341 (File not found error), and https://github.com/TEdit/Terraria-Map-Editor/issues/1071 (Load Failed, No Backup Found).

**Comment by BinaryConstruct** [comment]
They are in the sprites. You can place them with the sprite tool.
