### ISSUE TITLE
Block stilying does not work properly.

### ISSUE THREAD

**Issue by cerebrain** [TEdit/Terraria-Map-Editor#1095]
I was editing for a really long Hellevator in a world, so I was putting my desired blocks and enabled the extras option, enabled Block Style and set it to Full Brick but when I used the brush to quick paint over my blocks there were some that didn't come as full blocks.

I'm not completely sure about this thing as I didn't pay much attention at first but this seems to happen when painting over blocks already placed in your selection, since it didn't happen to the blocks I placed on empty space (I'm almost sure of this since I manually erased most blocks and in that area it worked totally fine).

I'm using TEdit 3.10 and vanilla Terraria 1.3.5.

**Comment by BinaryConstruct** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/TEdit/Terraria-Map-Editor/issues/747 (Don't working), https://github.com/TEdit/Terraria-Map-Editor/issues/775 (TEdit does not work), https://github.com/TEdit/Terraria-Map-Editor/issues/1092 (TEdit Ain't Working Properly..), https://github.com/TEdit/Terraria-Map-Editor/issues/481 (Crash on Start // "TEditXna does not work anymore"), and https://github.com/TEdit/Terraria-Map-Editor/issues/440 (World Renaming doesn't work).

**Comment by BinaryConstruct** [comment]
There are some options that have to be toggles to make the still change. I don't have a pic for a example right now, but it should be on the brush config.
