### ISSUE TITLE
i have a problem

### ISSUE THREAD

**Issue by MR1Coffee021** [TEdit/Terraria-Map-Editor#1096]
when i try to open the TEdit.exe they send me an error they say "Unhandled Exeption"

[TEditLog.txt](https://github.com/TEdit/Terraria-Map-Editor/files/2195351/TEditLog.txt)

and this is te txt of the error

**Comment by BinaryConstruct** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/TEdit/Terraria-Map-Editor/issues/631 (Hi guys nice work but I have a problem. Uploaded TEditLog.txt), https://github.com/TEdit/Terraria-Map-Editor/issues/984 (Display problem i think), https://github.com/TEdit/Terraria-Map-Editor/issues/276 (TEdit schematic problems?), https://github.com/TEdit/Terraria-Map-Editor/issues/538 (My problem is still occuring and my post was "Closed"), and https://github.com/TEdit/Terraria-Map-Editor/issues/692 (TEdit v0.0.0.0 problem).

**Comment by BinaryConstruct** [comment]
Your user profile has a } in the name causing this issue. Try creating a user with no special characters.
