### ISSUE TITLE
I have an issue trying to open my worldfile in tedit

### ISSUE THREAD

**Issue by kenuj** [TEdit/Terraria-Map-Editor#1097]
long story short, i have a world gen previewer mod installed and also the spiritmod installed. While creating the world the game crashed and there was an error regarding the worldgen mod, however the world had still been created so i thought nothing of it and continued to play. after building a base and gathering a few npc's i started to explore the surface and noticed there were many glitches, for example there were no houses on sky islands, some trees were floating, unstable terrain generation etc. i only want to copy my house from this world into a new world to save the process of repeating everything exactly.
i believe the problem is that because the world was clearly incomplete upon creation the world file wont open in Tedit? if this is correct is there no hope for me?

   ## What were you doing when the issue occured?
trying to open the worldfile

## Can you reproduce the issue?
yes it happens everytime i try to open the worldfile

## What version of Terraria are you using?
v1.3.5.2

## Post relevant contents of log or attach log file _**(very important)**_:
[TEditLog.txt](https://github.com/TEdit/Terraria-Map-Editor/files/2237980/TEditLog.txt)

**Comment by BinaryConstruct** [comment]
TEdit does not support modded world files at this time.
