### ISSUE TITLE
Error when I open up 1.3.5 TEdit

### ISSUE THREAD

**Issue by TheTerrarianYT** [TEdit/Terraria-Map-Editor#1099]
It says i need to upload the TEditLog.txt to the issues list
![image](https://user-images.githubusercontent.com/41843184/43361520-50ff64d8-92c8-11e8-9834-f2c424f9714a.png)

**Comment by BinaryConstruct** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/TEdit/Terraria-Map-Editor/issues/978 (TEdit 1.3.5.1 Error), https://github.com/TEdit/Terraria-Map-Editor/issues/320 (Error), https://github.com/TEdit/Terraria-Map-Editor/issues/946 (Error.), https://github.com/TEdit/Terraria-Map-Editor/issues/703 (Error), and https://github.com/TEdit/Terraria-Map-Editor/issues/1017 (TEdit crash when i try to open it.).

**Comment by TheTerrarianYT** [comment]
Is it able to be fixed

**Comment by TheTerrarianYT** [comment]
[TEditLog.txt](https://github.com/TEdit/Terraria-Map-Editor/files/2238383/TEditLog.txt)

**Comment by BinaryConstruct** [comment]
Please unzip to a folder not in your user profile, such as c:\games\tedit

**Comment by thaurane** [comment]
[TEditLog.txt](https://github.com/TEdit/Terraria-Map-Editor/files/2343875/TEditLog.txt)
Same issue as TheTerrarianYT, crashes on start, unzipping to C:/ did not give a different result. Another issue said to use integrated graphics card which is not possible for me. fix in issue #976 didn't work but I don't think I understood the instructions well. Could you explain them further?
windows 7 home premium 64bit, ryzen 5 1600, nvidia 1060, 16gb 2133mhz ram
