### ISSUE TITLE
TEdit will not start

### ISSUE THREAD

**Issue by droolmagnet** [TEdit/Terraria-Map-Editor#1101]
TEdit will not start and nothing happens.

Log says something about the GPU I am using - already using the latest driver though it's no longer being supported. It plays Terraria fine though.

TEdit 3.9 starts up, but TEdit 3.10 and 3.11 does not.

## What were you doing when the issue occured?
Trying to get it to start. :c

## Can you reproduce the issue?
Yes

## What version of Terraria are you using?
1.3.5.3

## Post relevant contents of log or attach log file _**(very important)**_:
[TEditLog.txt](https://github.com/TEdit/Terraria-Map-Editor/files/2262920/TEditLog.txt)

**Comment by BinaryConstruct** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/TEdit/Terraria-Map-Editor/issues/1060 (TEdit won't to start), https://github.com/TEdit/Terraria-Map-Editor/issues/1052 (TEdit will not start.), https://github.com/TEdit/Terraria-Map-Editor/issues/562 (TEdit starts, nothing happens), https://github.com/TEdit/Terraria-Map-Editor/issues/955 (tedit doesn't start), and https://github.com/TEdit/Terraria-Map-Editor/issues/1066 (TEdit does not start).

**Comment by BinaryConstruct** [comment]
TEdit has higher system requirements that Terraria due to it's base rendering engine. Unfortunately, your hardware/os combination is not supported by monogame.
