### ISSUE TITLE
Can't find Corruption or Hallow blocks

### ISSUE THREAD

**Issue by CosmicTerrarian** [TEdit/Terraria-Map-Editor#1102]
In a world i've worked extremely hard on, i've used the morph tool to get rid of all the Hallow and Corruption to bring peace into my world. And it worked! Other than the fact when I talked to the Dryad, she told me my world wasn't purified and it was 1% Hallow and 1% Corruption! **The 200x200 square isn't large enough to quickly and/or effeciently cover my entire world**, and every time I join my world for a mere few minutes, I find HUGE patches of Hallow that I need to morph again! **I have no system that I can use to hone in on Hallow or Corruption blocks, despite being in desperate need of one.** What can I do to save my world?! Please help!

**Comment by BinaryConstruct** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/TEdit/Terraria-Map-Editor/issues/1091 (Can't find doors), https://github.com/TEdit/Terraria-Map-Editor/issues/573 (Cannot place any blocks!), https://github.com/TEdit/Terraria-Map-Editor/issues/913 ([Feature Request] Plugin: "Clean Crimson/Corruption/Hallow"?), https://github.com/TEdit/Terraria-Map-Editor/issues/233 (No Backup Found), and https://github.com/TEdit/Terraria-Map-Editor/issues/349 (TEdit 3 Cannot be Found).

**Comment by BinaryConstruct** [comment]
There is a replace blocks in the plugins section I believe.
