### ISSUE TITLE
TEdit will, (surprise,) not load.

### ISSUE THREAD

**Issue by Ethanotor** [TEdit/Terraria-Map-Editor#1103]
## "What were you doing when the issue occured?"
I had run the TEditXna.exe file in an unzipped folder. I have attempted the use of compatibility mode, and running it as an administrator. Neither were of any success.

**## "Can you reproduce the issue?"**
Yes, and have since noted that the program does in fact run for a very brief moment before ending it's task prematurely, according to task manager's "programs" function.

**## "What version of Terraria are you using?"**
1.3.5.3. I am in fact using mods. In case you're wondering, I do not run the Terraria client while attempting to access TEdit. I have found no success in any form.

## Post relevant contents of log or attach log file _**(very important)**_:
[TEditLog.txt](https://github.com/TEdit/Terraria-Map-Editor/files/2271315/TEditLog.txt)

Please note that I have tried my hand at using this client across several of it's different updates and each time have found no success. I am extremely upset to not be able to use this tool.

**Comment by BinaryConstruct** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/TEdit/Terraria-Map-Editor/issues/493 (tedit worlds dont load), https://github.com/TEdit/Terraria-Map-Editor/issues/1081 (Saved new world in Tedit, loaded fine a couple of times, won't load now.), https://github.com/TEdit/Terraria-Map-Editor/issues/427 (World Won't Load), https://github.com/TEdit/Terraria-Map-Editor/issues/558 (Worlds won't load), and https://github.com/TEdit/Terraria-Map-Editor/issues/750 (Not letting world load in tedit).

**Comment by Ethanotor** [comment]
The issue is not currently that any worlds will not load. The program file of TEdit itself is cut off as soon as I activate the TEditXna.exe file.
I just thought I should clarify.

**Comment by Ethanotor** [comment]
So, is there anything I could do now in the means of resolving this issue? I had to make an entire account on the site to finally be able to ask, I need answers.

**Comment by BinaryConstruct** [comment]
Have you tried a different PC? Sometimes hardware can cause an issue. The log is pretty empty, so I was unable to find a cause there.
