### ISSUE TITLE
Tedit Corrupting World files upon opening them(sometimes)

### ISSUE THREAD

**Issue by OGCursiv** [TEdit/Terraria-Map-Editor#1104]
## What were you doing when the issue occured?
Opening a world file
## Can you reproduce the issue?
Yes, and I have many times
## What version of Terraria are you using?
1.3.5
## Post relevant contents of log or attach log file _**(very important)**_:
[TEditLog.txt](https://github.com/TEdit/Terraria-Map-Editor/files/2291864/TEditLog.txt)

**Comment by BinaryConstruct** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/TEdit/Terraria-Map-Editor/issues/654 (Tedit wont open a world), https://github.com/TEdit/Terraria-Map-Editor/issues/580 (Unable to Open World in TEdit), https://github.com/TEdit/Terraria-Map-Editor/issues/1089 (World Corrupting after using TEdit), https://github.com/TEdit/Terraria-Map-Editor/issues/797 (TEdit crashing on open), and https://github.com/TEdit/Terraria-Map-Editor/issues/493 (tedit worlds dont load).

**Comment by BinaryConstruct** [comment]
Are you using mods?

**Comment by OGCursiv** [comment]
@BinaryConstruct No mods are being used... Just copying and pasting structures from one world to another, latest versions of both Tedit and Terraria.
