### ISSUE TITLE
World FIle Error

### ISSUE THREAD

**Issue by uhhidkman** [TEdit/Terraria-Map-Editor#1106]
I recently formatted my hard drive and forgot my Terraria saves on it. For reasons unknown to me, my world files (both .wld and .bak) were completely wiped with a size of 0kb. I was, however, able to retrieve the TEdit files. My problem is that attempting to open them with TEdit (latest version) yields the following:

There was an error reading the world file. This is usually caused by a corrupt save file or a world version newer than supported.
TEdit v3.10.18105.2203
TEdit Max World: 192    Current World: 3763819861
Do you wish to force it to load anyway?
The error is: Array dimensions exceed supported range.

This was a world I edited less than a month ago with the same version of TEdit. Have I any way to remedy this situation?

**Comment by BinaryConstruct** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/TEdit/Terraria-Map-Editor/issues/457 (World loading error), https://github.com/TEdit/Terraria-Map-Editor/issues/398 (Opening world error), https://github.com/TEdit/Terraria-Map-Editor/issues/363 (World File Error), https://github.com/TEdit/Terraria-Map-Editor/issues/451 (world file error), and https://github.com/TEdit/Terraria-Map-Editor/issues/626 (World file error).

**Comment by BinaryConstruct** [comment]
Sometimes, you can with source code using visual studio and fix issues as they are loaded. However, most of the time it doesn't work, and is very tedious.
