### ISSUE TITLE
Terraria world will not upload. PLEASE help.

### ISSUE THREAD

**Issue by gabrielhpeters** [TEdit/Terraria-Map-Editor#1111]
This is the mediafile link. Hope I am doing this right.

https://www.mediafire.com/view/pw1qr5jj3nav0o3/a4ce7b163832f35ffcbf560ca40974bccd5d4cd5.ico/file

## Before you submit an issue, please read
 * If you get an unhandled exception, please _**check your log before posting**_.
 * If your log includes _**DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved**_
   * This is a known issue, do not create a new issue, please add your comments to #751
   * People have had the most luck in Windows 7 with updating to DirectX 11.1
     This is found in windows update in the optional updates section or by
     following directions here 
   * https://support.microsoft.com/en-us/kb/179113
 * Please fill out the questions below
 * Instead of copy/pasting text you can attach the entire log file.
 * If your world file is less than 25MB, you can attach it as well.

**Comment by BinaryConstruct** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/TEdit/Terraria-Map-Editor/issues/301 (Terraria freezes after loading TEdit Ocean World), https://github.com/TEdit/Terraria-Map-Editor/issues/637 (My terraria world wont load up ), https://github.com/TEdit/Terraria-Map-Editor/issues/1059 (Opening a new world in Terraria), https://github.com/TEdit/Terraria-Map-Editor/issues/998 (Whenever I try to load a world, it comes up with an unhandled exception), and https://github.com/TEdit/Terraria-Map-Editor/issues/1039 (cannot apply mod).
