### ISSUE TITLE
Why does it read v3.10 for the 3.11 beta download...?

### ISSUE THREAD

**Issue by DumbJoe** [TEdit/Terraria-Map-Editor#1112]
https://github.com/TEdit/Terraria-Map-Editor/releases/tag/3.10.18105.218

**Comment by BinaryConstruct** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/TEdit/Terraria-Map-Editor/issues/370 (Download), https://github.com/TEdit/Terraria-Map-Editor/issues/4 (Download?), https://github.com/TEdit/Terraria-Map-Editor/issues/791 (Beta 3.7 doesn't work), https://github.com/TEdit/Terraria-Map-Editor/issues/185 (crash in loading world tedit 3 beta), and https://github.com/TEdit/Terraria-Map-Editor/issues/800 (TEdit 3.7 beta will not start.).

**Comment by DumbJoe** [comment]
> 
> 
> [GitMate.io](https://gitmate.io) thinks possibly related issues are #370 (Download), #4 (Download?), #791 (Beta 3.7 doesn't work), #185 (crash in loading world tedit 3 beta), and #800 (TEdit 3.7 beta will not start.).

What? This issue has nothing to do with the other issues, maybe the 404 one from the adfly one but I didn't get to here via the some paid link I got to there from: http://binaryconstruct.com/games/tedit/ which originated from here: https://terraria.gamepedia.com/Map_viewers

**Comment by BinaryConstruct** [comment]
Part of the automated builds that tag the version numbers. I'll resolve it for the next release

**Comment by DumbJoe** [comment]
> 
> 
> Part of the automated builds that tag the version numbers. I'll resolve it for the next release

Ahhh, thanks.....what's new in the next release?
