### ISSUE TITLE
TEdit won't start (Unhandled exception)

### ISSUE THREAD

**Issue by quadlego** [TEdit/Terraria-Map-Editor#1114]
## What were you doing when the issue occured?
It worked perfectly fine before but this one time when I try to start TEdit my computer bluescreened and since then when I try to start TEdit it shows the unhandled exception popup.

## Can you reproduce the issue?
Not the bluescreen part.

## What version of Terraria are you using?
1.3.5.2
also using tModLoader 0.10.1.5 (but no saves have any modded content, only items on a character)

## Post relevant contents of log or attach log file _**(very important)**_:

[TEditLog.txt](https://github.com/TEdit/Terraria-Map-Editor/files/2535329/TEditLog.txt)

**Comment by BinaryConstruct** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/TEdit/Terraria-Map-Editor/issues/1101 (TEdit will not start), https://github.com/TEdit/Terraria-Map-Editor/issues/1052 (TEdit will not start.), https://github.com/TEdit/Terraria-Map-Editor/issues/1006 (not start), https://github.com/TEdit/Terraria-Map-Editor/issues/1060 (TEdit won't to start), and https://github.com/TEdit/Terraria-Map-Editor/issues/990 (Unhandled Exeption).

**Comment by BinaryConstruct** [comment]
Please unzip all files instead of double clicking the exe inside the zip.

**Comment by BinaryConstruct** [comment]
It appears your config is corrupted, try deleting C:\Users\User\AppData\Local\TEditXna\TEditXna.exe_Url_pwayammrix3bsw4yubtmdxs4qkyrhcpm\3.10.0.0\user.config
