### ISSUE TITLE
Diagonal Line Tool

### ISSUE THREAD

**Issue by Leahcim4686** [TEdit/Terraria-Map-Editor#1115]
The Diagonal Line Tool (Brush: Shape: Diagonal...) does not matchup between the preview and what's placed.
![image](https://user-images.githubusercontent.com/45774770/49769619-17da1280-fc9e-11e8-8aa2-40b40abb1fea.png) ![image](https://user-images.githubusercontent.com/45774770/49769658-42c46680-fc9e-11e8-8d21-ae729ba86d28.png)

**Comment by BinaryConstruct** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/TEdit/Terraria-Map-Editor/issues/287 (Line), https://github.com/TEdit/Terraria-Map-Editor/issues/502 (Line Tool), https://github.com/TEdit/Terraria-Map-Editor/issues/325 (New Tool: Line Drawing), https://github.com/TEdit/Terraria-Map-Editor/issues/59 (Selection Tool), and https://github.com/TEdit/Terraria-Map-Editor/issues/239 (Picker Tool).
