### ISSUE TITLE
Issue With Extracting

### ISSUE THREAD

**Issue by ktheniscool** [TEdit/Terraria-Map-Editor#1118]
## Post relevant contents of log or attach log file _**(very important)**_: I cannot because it doesn't even extract all the files

When I was trying to download TEdit, whenever I extract the file to my desktop it would delete the .xna.exe whenever I tried.

**Comment by BinaryConstruct** [comment]
Are you downloading the zip from https://github.com/TEdit/Terraria-Map-Editor/releases/tag/3.10.18105.218
?
