### ISSUE TITLE
GOG Galaxy detects TEdit as running Terraria and disables the start button

### ISSUE THREAD

**Issue by vladtepesch** [TEdit/Terraria-Map-Editor#1122]
Terraria can not be started with the GOG Galaxy Client while TEdit is running, because it thinks that it is already running.

Maybe there is some easy fix by changing some window class or name or title or something.

**Comment by vladtepesch** [comment]
strange - currently iI can not reproduce this behaviour.

**Comment by tomek-i** [comment]
maybe your terraria process was running but the game did not show ... happened to me that way
