### ISSUE TITLE
Error when i try to open up TEdit 3.11 or 3.10

### ISSUE THREAD

**Issue by ExOL1ON** [TEdit/Terraria-Map-Editor#1129]
[TEditLog.txt](https://github.com/TEdit/Terraria-Map-Editor/files/3064940/TEditLog.txt)
![image](https://user-images.githubusercontent.com/49492520/55898443-41169b00-5bcb-11e9-9bf4-42f1cda32637.png)

**Comment by BinaryConstruct** [comment]
Duplicate of #751
