### ISSUE TITLE
tEdit don't opens!

### ISSUE THREAD

**Issue by Voltr0nVortex** [TEdit/Terraria-Map-Editor#1131]
Hello! I am having a problem when try to open tEdit.
When i double click on it, to open, it dont opens, no screen apear, no info, nothing...
I tried open Task Manager, to check if it was there, and it was, but nothing happened.
I checked some issues, i have all the pre requirements, but still nothing.
## What were you doing when the issue occured?
A: I tried to open the program, by double clicking, on it, tried Admin mode, but nothing too

## Can you reproduce the issue?
A: Yes, by doing what i said before, opening the program, but this happened to me, instead

## What version of Terraria are you using?
A: 1.3.5.3

## Post relevant contents of log or attach log file:
[TEditLog.txt](https://github.com/TEdit/Terraria-Map-Editor/files/3179603/TEditLog.txt)
I hope this is enough information.
Thanks!

**Comment by Variable-X** [comment]
Me too!

**Comment by Variable-X** [comment]
NVM

**Comment by Variable-X** [comment]
Try waiting OR https://github.com/TEdit/Terraria-Map-Editor/wiki/Getting-Started
