### ISSUE TITLE
TEdit does not start

### ISSUE THREAD

**Issue by mc-oofy** [TEdit/Terraria-Map-Editor#1137]
## What were you doing when the issue occured?
starting tedit
## Can you reproduce the issue?
yes,by starting tedit
## What version of Terraria are you using?
1.3.5.3

## Post relevant contents of log or attach log file _**(very important)**_:
[TEditLog.txt](https://github.com/TEdit/Terraria-Map-Editor/files/3431219/TEditLog.txt)

**Comment by zelding** [comment]
from your logs it seems it is the same case as these
#699 and #696
