### ISSUE TITLE
Cannot open Tedit

### ISSUE THREAD

**Issue by DjLego** [TEdit/Terraria-Map-Editor#1141]
## What were you doing when the issue occured?
Opening terraria edit
## Can you reproduce the issue?
yes , starting tedit
## What version of Terraria are you using?
1.3.5.3
## Post relevant contents of log or attach log file _**(very important)**_:
[TEditLog.txt](https://github.com/TEdit/Terraria-Map-Editor/files/3488614/TEditLog.txt)

**Comment by TheAlienWheatley** [comment]
Install **KB2670838 for Windows 7** !!!!!!!!!!!!!!!!!
