### ISSUE TITLE
Problems importing a .png

### ISSUE THREAD

**Issue by thatmagicstore** [TEdit/Terraria-Map-Editor#1142]
## What were you doing when the issue occured?
Trying to use the "Import Schematic or Image" and "Import False Color Image" Tools
## Can you reproduce the issue?
Reliably.
## What version of Terraria are you using?
1.3.5 and I'm also using the latest version of Tedit with the correct installation requirements and have correctly set the contents folder in settings.xml.
## What is the Issue?
Every time I import a .png file into Tedit, the full file doesn't appear. It's usually just a few pieces of dirt or stone wall. The only thing that does import is some of the green parts of 24 bit .png images and not even that is consistent.

**Comment by Tslasher11** [comment]
I can't get in the app
