### ISSUE TITLE
trojan?

### ISSUE THREAD

**Issue by kamakaz** [TEdit/Terraria-Map-Editor#1143]
when I scanned it with windows defender it said it found Trojan:Win32/Wacatac.A!m1

**Comment by BinaryConstruct** [comment]
https://www.virustotal.com/gui/search/https%253A%252F%252Fgithub.com%252FTEdit%252FTerraria-Map-Editor%252Freleases%252Fdownload%252F3.10.18105.218%252FTEdit3_v3.10.18105.218.zip

 TEdit from the official GitHub released page does not contain any viruses, malware or adware. Please only download from GitHub. I suggest scanning your computer completely.
