### ISSUE TITLE
[Feature Request] Resize an existing map

### ISSUE THREAD

**Issue by Commander238** [TEdit/Terraria-Map-Editor#1144]
Hi, 
Would it be possible to resize an existing map - add a padding around an existing world (top, right, bottom, left) and move all the point coordinates to match?
I could draw something inside the new empty area after that.

**Comment by tomek-i** [comment]
cant you use the erase brush and just remove the edges of the map? I dont understand your "feature" and what benefit it would give ... or do you mean turn a small world into a medium/large world ?

**Comment by Commander238** [comment]
Hi,
Thank you for your reply.

Sorry, that would not help me, because I need to make the map slightly larger than before.
And even if I wanted to make it smaller, the eraser would just make a big hole on the edges, and so the player would fall and die instead of reaching the edge.
I hope you understand me now.

One other thing:
If I create a new map in the editor, I am limited to multiples of 50.
If I create a new map inside the game, I can only choose from small/medium/large.
Then I wonder - Is the multiple of 50 important?
Does the game work with custom world sizes? 

You asked why am I requesting this feature.
I am trying to solve an inconvenient bug in Terraria Mobile 1.3.
It should help me if I managed to enlarge an existing map - add some tiles to all edges.
Ideally, the map should be exactly 30 tiles larger at each edge, so the resolition would add 60 tiles horizontally and 60 vertically. That might be rounded up to 100 tiles if the multiples of 50 are necessary.
I can explain more if you are interested.

In TEdit, I have already tried opening the existing map and copying the contents to a new bigger map.
That does not work very well. I lose all the metadata and NPCs that way. Also the map version conpatibility changes.

**Comment by tomek-i** [comment]
Whats the bug in mobile?

I am not owner of this project but, If you change the dimension of a map you can do so only by a full column or row. 
so for example a size of 800x600 (tiles) means changing it to 801x600 would add space for 600 new tiles... so your amount of tiles is limited by the resolution of the map hence you can not just extend it by 30 tiles unless yo have a map like N x 30 or 30 x N  
https://terraria.fandom.com/wiki/World_Size


I created a pull request where i fixed this version of tedit to work with mobile maps, i have only tested it on iOS (https://github.com/TEdit/Terraria-Map-Editor/pull/1146) and it retains all values (doesn't modify compatibility of map)

**Comment by Commander238** [comment]
About the bug: 
Terraria Mobile has a feature to convert 1.2 maps to 1.3 format. That seems to work, but:
The 1.2 small map has got the dimensions 1750x900, including an invisible margin of 12 blocks from each side. I measured that margin in TEdit.
The 1.3 converted map has got the dimensions 1750x900, including an invisible margin of 42 blocks from each side.
https://terraria.gamepedia.com/Map_size
If I open the map in 1.3 mobile app, the map is cut off and the player cannot reach 30 blocks at the edge.
This can be disappointing, if a player has built some houses and railways on the edge, which I also did.
For an example, see the video in this thread: 
https://forums.terraria.org/index.php?threads/mobile-maps-converted-from-1-2-to-1-3-0-7-are-cut-off-at-the-bottom.82433/

I got an idea: 
If the game engine needs to reserve 42 blocks from each side for the invisible margin,
How about adding additional 30 blocks to each side of the old map, so that we have the same accessible area as we had earlier.
I would need to edit a map and add 30 blocks to each side. All coordinates of objects etc. should shift 30 blocks to the center.
I think the map compatibility needs to remain "Compatible Version: 155".
Obviously, we don't have any data for the contents of those 30 block areas.
I would just fill those with some solid stone for underground and cavern, hellstone for hell, water for ocean, air for sky and space.
The algorithm might be difficult, so I can draw it manually in TEdit.

I am not sure, which map resolutions are actually allowed.
The game creates only 1750x900, 4200x1200, 6400x1800, 8400x2400.
TEdit can create any maps with dimensions that are multiple of 50. Is this restriction necessary by the file format?
I would need 1810x960. If that is not allowed, then 1850x1000.

A brave TEdit developer would create a new dialog to ask for the expanded margins (top, right, bottom, left).
Then he would allocate a bigger array for the map, and shift all the content coordinates to match.
A user like me could draw stone and water to the empty areas an pray to the Moonlord for a miracle, so that the Terraria Mobile 1.3 app would open the map correctly.

**Comment by tomek-i** [comment]
I haven't really tested it in-game but I made a quick plugin "Expand world" which takes the map size and you can increase it - similar when generating a new world. I tried it with a new world and expanding it and it worked in the editor. As I have limited time and can't test it in game right now (for the next week)

You can download the compiled version: https://we.tl/t-oEqSukYydt
under plugins you will find a new one called "expand world" give it a test and let me know how you went. Once its working I will create another pull request

**Comment by Commander238** [comment]
That's great. I will give it a try.

**Comment by Commander238** [comment]
I tested your build. Great job. It solves the main problem. I managed to expand my map and reach some parts which were cut off.
The old converted 1.2 map was actually 1750x1000, weird dimensions, but never mind. I expanded it to 1750x1100. I managed to load the map in mobile version and now I could reach the bottom, which is great. :)

* Would you know, if it is possible to expand the map by a number which is not a multiple of 50?
Otherwise it will require some more redrawing of the edges.
* So now I can expand the map, and then move the dirt and walls to the center. But the coordinates of the NPCs, respawn point, surface layer, etc. need to be shifted as well. I can do it manually, but an automated process would make it faster.

**Comment by tomek-i** [comment]
That’s good news. Yes I kept the default increments, I am sure that it can be changed and it was just a convenience to jump in bigger increments.

I thought it does recalculate the spawn point, it did seem so in the tedit preview. 
I can add the surface layer etc. sliders into the screen so you can edit it similiar to when creating a new map.

I won’t have time until somewhere next week to actually look at the code (nor submit my pull request)

**Comment by tomek-i** [comment]
I also don’t know if the repository owner is still active on this project :-D to merge/review them

**Comment by Commander238** [comment]
You could change the increments to 10, or add a radio button with 1/10/50 above the sliders.
I have tested the spawn point again. It moves as intended. But the dungeon entrance and the NPCs didn't move. 
Next week is fine, have a nice time. :) 
Hopefully someone still manages the project. It would be a shame since Terraria 1.4 will be released this year.

**Comment by Commander238** [comment]
Hi, 
if you find time, can you have a look at this plugin again? :-) 
I would appreciate an increment of 10 when resizing the existing map.

**Comment by tomek-i** [comment]
attached compiled version of 10 increments - you can use they keyboard as well if mouse is to cumbersome
[teditincrements.zip](https://github.com/TEdit/Terraria-Map-Editor/files/3732010/teditincrements.zip)

**Comment by Commander238** [comment]
Thanks, it works. Yes, the keyboard is more precise.
Finally the map is exactly the size I need. :-) I already tested the result in my phone.

For me, this is sufficient and you can leave it as is. You can make a pull request.

Maybe for a next update - 
Either, the previous map content would be centered, including properly aligned NPCs and tiles,
or the user would select all four margins in the plugin dialog (more work).

**Comment by tomek-i** [comment]
Glad to hear that. I will leave this as it and do a pull request.
