### ISSUE TITLE
[Request]Search/highlight feature

### ISSUE THREAD

**Issue by ajloveslily14** [TEdit/Terraria-Map-Editor#1147]
I was wondering if a search/highlight feature could be added. It would let you highlight all tiles of a certain type. I request this because I often use TEdit to get rid of corruption/hallow/whatever and there's random spots that have it and it can sometimes be hard to find those spots.

**Comment by tomek-i** [comment]
To make it easier, there should be a find & replace functionality where you select two tiles, the source and the tile it should be replaced/filled with. this way you could easily replace a tile with whatever you like and or remove it.
