### ISSUE TITLE
[Feature Request] Different Platform World File Support

### ISSUE THREAD

**Issue by 641i130** [TEdit/Terraria-Map-Editor#1152]
It'd be nice if Tedit supported world files from different platforms or world conversion. I've been trying to find a way to open an old file from when I played console. None of the similar versions of Tedit work.

**Comment by BinaryConstruct** [comment]
See https://forums.terraria.org/index.php?threads/official-505games-policy-regarding-console-mobile-hacking.35819/#post-1801576
