### ISSUE TITLE
I Dunno If Anyone has done this already but Welp can't start TEdit

### ISSUE THREAD

**Issue by PhoneticDragon** [TEdit/Terraria-Map-Editor#1157]
## What were you doing when the issue occured?
I Was Starting TEdit After It Crashed
## Can you reproduce the issue?
Yes Every Time I open TEdit It Happens
## What version of Terraria are you using?
Latest Version
## Post relevant contents of log or attach log file _**(very important)**_:
[TEditLog.txt](https://github.com/TEdit/Terraria-Map-Editor/files/3937317/TEditLog.txt)

**Comment by PhoneticDragon** [comment]
Can Anyone Help Me?

**Comment by Capt-Smoke** [comment]
well idk what the issue is but im having the same one...

**Comment by tomek-i** [comment]
Try my pull request, I made changes which prevent the upgrade of maps - which was important to make this work for mobile version of terraria as it’s behind.
