### ISSUE TITLE
Tedit doesn't work. (no error codes)

### ISSUE THREAD

**Issue by Zsno** [TEdit/Terraria-Map-Editor#1164]
## What were you doing when the issue occured?
Nothing.
## Can you reproduce the issue?
Yes. Every time I click anything on the app it just crashes.
## What version of Terraria are you using?
latest version.
## Post relevant contents of log or attach log file _**(very important)**_:
https://pastebin.com/tdaDvgKW ( the log is short so I'll post it here as well)

01-27-2020 14:46:50: Starting TEdit 3.10.18105.2203 
01-27-2020 14:46:50: OS: Microsoft Windows NT 6.2.9200.0 
01-27-2020 14:46:50: Terraria v1.3.5.3 
01-27-2020 14:46:50: Terraria Data Path: d:\steam\steamapps\common\terraria\Content 
01-27-2020 14:46:50: Creating Undo cache: C:\Users\venom\AppData\Roaming\TEdit\undo_87612457 
01-27-2020 14:46:58: Removing old undo cache: C:\Users\venom\AppData\Roaming\TEdit\undo_24403429 
01-27-2020 14:46:58: Removing old undo cache: C:\Users\venom\AppData\Roaming\TEdit\undo_246060180 
01-27-2020 14:46:58: Removing old undo cache: C:\Users\venom\AppData\Roaming\TEdit\undo_250836852 
01-27-2020 14:46:58: Removing old undo cache: C:\Users\venom\AppData\Roaming\TEdit\undo_311970157 
01-27-2020 14:46:58: Removing old undo cache: C:\Users\venom\AppData\Roaming\TEdit\undo_363613412 
01-27-2020 14:46:58: Removing old undo cache: C:\Users\venom\AppData\Roaming\TEdit\undo_382832459 
01-27-2020 14:46:58: Removing old undo cache: C:\Users\venom\AppData\Roaming\TEdit\undo_821036040 
01-27-2020 14:46:58: Removing old undo cache: C:\Users\venom\AppData\Roaming\TEdit\undo_840111211 
01-27-2020 14:46:58: Removing undo cache: C:\Users\venom\AppData\Roaming\TEdit\undo_87612457

**Comment by Zsno** [comment]
Nevermind found the problem. apparently having msi afterburner/rivatuner on (even on the task bar) makes it crash.

**Comment by Vaskyy** [comment]
u solved my problem
was about to give up, and than u came with this
TANK YOU :D

**Comment by BinaryConstruct** [comment]
Afterburner is known to cause issues with monogame applications.
