### ISSUE TITLE
How do I make TEdit show the sprites instead of coloured boxes?

### ISSUE THREAD

**Issue by SwagnLag** [TEdit/Terraria-Map-Editor#1171]
just asking a question

**Comment by ZhugeSong** [comment]
Firstly, make sure you are zoomed in enough. If you are zoomed out, you won't see the sprites (they probably would be hard to make out anyway.)

Secondly, make sure TEdit knows where Terraria is installed; it uses Terraria itself as the source for the graphics. I did this by editing the config settings in the file called `TEditXna.exe.config`. There is a user setting called `TerrariaPath`, and you can set the value to wherever Terraria is installed (e.g., `C:\somewhere\SteamLibrary\steamapps\common\Terraria`).

Alternatively, (and I think recommended), is to update the `settings.xml` file (also located in the same directory as the executable). The XML file has an element named `AltC`; uncomment it and change the value to wherever Terraria is installed.

Hope this helps.
