### ISSUE TITLE
 Will there be a map editor update?

### ISSUE THREAD

**Issue by Sterben2187** [TEdit/Terraria-Map-Editor#1179]
Hello. Will the map editor update on terraria journey end 1.4?

**Comment by BinaryConstruct** [comment]
Probably, however the update has not been released and I have no access to
it until release.

**Comment by x0rsw1tch** [comment]
Yay! Looking forward to it!

**Comment by Terrariamain** [comment]
How long is this approximately going to take?

**Comment by djdjdjdjdjd38w94** [comment]
update for 1.4 and we will stop begging u for updates

**Comment by djdjdjdjdjd38w94** [comment]
plz
update for 1.4

**Comment by djdjdjdjdjd38w94** [comment]
PLEASE

**Comment by micmou** [comment]
> 
> 
> PLEASE

TFW you have to triple post begging for a update on completely free open source project? If you want it updated so bad why dont you do it yourself :P

**Comment by heavyoak** [comment]
> PLEASE

stop spamming you bot

**Comment by BinaryConstruct** [comment]
Due to personal issues ETA is 4 weeks. If anyone wants to submit a pull request I will accept it and create a release.
