### ISSUE TITLE
It's been a day and a half now. When will this be updated?!

### ISSUE THREAD

**Issue by djdjdjdjdjd38w94** [TEdit/Terraria-Map-Editor#1181]
When is this gonna be updated? I would update it but I don't know terraria's coding language

**Comment by djdjdjdjdjd38w94** [comment]
I'm going to learn C# for the sole purpose of updating this since binaryconstruct is too lazy to update it himself

**Comment by Terrariamain** [comment]
be patient. as you've already said "it's been a day and a half now" so give it time.
