### ISSUE TITLE
Some ideas

### ISSUE THREAD

**Issue by Dogeislove** [TEdit/Terraria-Map-Editor#1184]
Maybe you can spawn an enemy in your world? Another request would be maybe being able to generate things like dungeons

**Comment by Pseuko** [comment]
Unfortunately, entities like enemies are removed when you quit out of a world and their data isn't saved to the world, with exception to the events, such as the celestial pillars (I'm not sure if their position or existence can be altered outside of the game or not). As to the other thing, the dungeon and other structures around the map are procedurally generated on world creation, your best bet would be to make a world, then copy the structure from there to wherever you'd like.
