### ISSUE TITLE
Its acting like its an older version

### ISSUE THREAD

**Issue by Willio2000** [TEdit/Terraria-Map-Editor#1185]
log: 
05-18-2020 08:04:21: Starting TEdit 4.0.20138.1323 
05-18-2020 08:04:21: OS: Microsoft Windows NT 6.2.9200.0 
05-18-2020 08:04:21: Terraria v1.4 
05-18-2020 08:04:21: Terraria Data Path: C:\Program Files (x86)\Steam\steamapps\common\Terraria\Content 
05-18-2020 08:04:21: Creating Undo cache: C:\Users\willi\AppData\Roaming\TEdit\undo_222008569 
05-18-2020 08:05:03: Removing old undo cache: C:\Users\willi\AppData\Roaming\TEdit\undo_569416897 
05-18-2020 08:05:03: Removing old undo cache: C:\Users\willi\AppData\Roaming\TEdit\undo_910643707 
05-18-2020 08:05:03: Removing undo cache: C:\Users\willi\AppData\Roaming\TEdit\undo_222008569 

the error says:
![error](https://user-images.githubusercontent.com/65547044/82216531-aebcec80-98de-11ea-98bc-5468c59ec7ff.png)

**Comment by Willio2000** [comment]
the save is not corrupted, i can still play it.

**Comment by Willio2000** [comment]
why is this closed? you should probably say something so that people arent confused

**Comment by BinaryConstruct** [comment]
Sorry, this is a known issue with beta releases. I added it to the known issues list.
