### ISSUE TITLE
Can't Save world. There is a loading bar that says "save creative powers" in the bottom right (where it should say save complete). The bar never finishes and just stays there forever.

### ISSUE THREAD

**Issue by dashingdrew** [TEdit/Terraria-Map-Editor#1188]
## Before you submit an issue, please read
 * If you get an unhandled exception, please _**check your log before posting**_.
 * If your log includes _**DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved**_
   * This is a known issue, do not create a new issue, please add your comments to #751
   * People have had the most luck in Windows 7 with updating to DirectX 11.1
     This is found in windows update in the optional updates section or by
     following directions here 
   * https://support.microsoft.com/en-us/kb/179113
 * Please fill out the questions below
 * Instead of copy/pasting text you can attach the entire log file.
 * If your world file is less than 25MB, you can attach it as well.
   
## What were you doing when the issue occured?
Trying to save my world

## Can you reproduce the issue?
Yes, everytime I try to save, it gets stuck and I get the message "save creative powers" in the bottom right where it would normally say save complete.

## What version of Terraria are you using?
1.4

## Post relevant contents of log or attach log file _**(very important)**_:
[TEditLog.txt](https://github.com/TEdit/Terraria-Map-Editor/files/4646994/TEditLog.txt)

**Comment by Guluad** [comment]
I have the same problem

**Comment by piegolf** [comment]
I have the same problem

**Comment by Relinquished001** [comment]
Issue for me too, I spent a few hours building stuff before I realized, good thing i saved some schematics.

**Comment by luigimain** [comment]
Same problem :(

**Comment by BinaryConstruct** [comment]
Could you attach a zip of your original world file? There might be something there that can help troubleshooting.

**Comment by Relinquished001** [comment]
I built a small hole since i started just doing survival, but this is my world, Its a journey world, might be why it doesnt save correctly.

[1st_Best.zip](https://github.com/TEdit/Terraria-Map-Editor/files/4648388/1st_Best.zip)

**Comment by GalacticRuler** [comment]
I've also encountered this bug, it seems to be related to Journey Mode (tried to change *to* Journey)

Mostly commenting so I get notifications of when this may potentially be fixed

**Comment by dashingdrew** [comment]
> Could you attach a zip of your original world file? There might be something there that can help troubleshooting.

Here you go


[Test World.zip](https://github.com/TEdit/Terraria-Map-Editor/files/4649099/Test.World.zip)

**Comment by archentar91** [comment]
same here but file is too big

**Comment by archentar91** [comment]
![2020 05 19-12 51](https://user-images.githubusercontent.com/65599574/82318053-7c3eec80-99cf-11ea-874c-26c4cfafefdd.png)

**Comment by archentar91** [comment]
![2020 05 19-12 52](https://user-images.githubusercontent.com/65599574/82318201-bdcf9780-99cf-11ea-862b-745812fd4167.png)

**Comment by archentar91** [comment]
[Worlds1.zip](https://github.com/TEdit/Terraria-Map-Editor/files/4649919/Worlds1.zip)

**Comment by archentar91** [comment]
[Worlds.zip](https://github.com/TEdit/Terraria-Map-Editor/files/4649920/Worlds.zip)

**Comment by BinaryConstruct** [comment]
Please try beta 3 and reopen if you are still having issues.

**Comment by BinaryConstruct** [comment]
> 
> 
> [Worlds.zip](https://github.com/TEdit/Terraria-Map-Editor/files/4649920/Worlds.zip)

I tested this and was able to save/load it in TEdit beta 3 and Terraria afterward.
