### ISSUE TITLE
TEdit Crashing when as soon as I load world

### ISSUE THREAD

**Issue by walurs** [TEdit/Terraria-Map-Editor#1189]
## Before you submit an issue, please read
 * If you get an unhandled exception, please _**check your log before posting**_.
 * If your log includes _**DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved**_
   * This is a known issue, do not create a new issue, please add your comments to #751
   * People have had the most luck in Windows 7 with updating to DirectX 11.1
     This is found in windows update in the optional updates section or by
     following directions here 
   * https://support.microsoft.com/en-us/kb/179113
 * Please fill out the questions below
 * Instead of copy/pasting text you can attach the entire log file.
 * If your world file is less than 25MB, you can attach it as well.
   
## What were you doing when the issue occured?
Trying to open a world in TEdit
## Can you reproduce the issue?
Attempted to create a new world, TEdit opened it fine.  Unable to reproduce outside of this world.  I also tried using the in-browser map editor called Terraria Map Editor and it had no problems loading the world file.
## What version of Terraria are you using?
1.4.0.2
## Post relevant contents of log or attach log file _**(very important)**_:
Log & world attached
[TEditLog.txt](https://github.com/TEdit/Terraria-Map-Editor/files/4647125/TEditLog.txt)
[Misty_Terrarium_of_Grass.zip](https://github.com/TEdit/Terraria-Map-Editor/files/4647131/Misty_Terrarium_of_Grass.zip)

**Comment by jerry123z** [comment]
Looks like this issue occurs when attempting to draw the NPC Overlay for the new Golfer NPC. The golfer is missing the npc.Name property.

**Comment by jerry123z** [comment]
Looks like the NPC Sprite ID for the golfer is incorrectly labeled as 589 instead of 588.

**Comment by BinaryConstruct** [comment]
Thanks, this info helps.

**Comment by BinaryConstruct** [comment]
This fix will be released in beta 3. Thank you for the PR.
