### ISSUE TITLE
Beta 2, can not set worlds to Expert

### ISSUE THREAD

**Issue by joshricker** [TEdit/Terraria-Map-Editor#1190]
On the new Tedit beta 2 you can not set the difficulty to Expert, make changing any world to or editing any expert worlds impossible with changing its difficulty.

 https://drive.google.com/uc?id=1OuSJYbSpAGf4iqnAev9MR_sUREAIn7A3

**Comment by jerry123z** [comment]
Attempting to change the world difficulty to Master currently sets it to Expert Mode in this version.

**Comment by joshricker** [comment]
Just tried that out but it looks like issue #1188 is stopping me from even attempting. Were you able to save a world? Setting my world type to any of the settings seems to never save as it looks like it never finishes saving.

**Comment by jerry123z** [comment]
I was able to save a brand new 1.4 world without encountering #1188. When saving a world being played I would encounter it.

**Comment by jerry123z** [comment]
It's actually just an error in the WorldPropertiesView.xaml, I've fixed it under #1191.

**Comment by BinaryConstruct** [comment]
This is fixed in code, will be released in beta 3.
