### ISSUE TITLE
EndOfStreamException loading Bestiary

### ISSUE THREAD

**Issue by SuperKael** [TEdit/Terraria-Map-Editor#1192]
## What were you doing when the issue occured?
Attempting to load a Terraria 1.4.0.2 world.

## Can you reproduce the issue?
Yes. Always.

## What version of Terraria are you using?
Terraria 1.4.0.2

## Post relevant contents of log or attach log file _**(very important)**_:
The log file contains nothing relevant whatsoever. It only even contains 5 lines of text.

So, upon attempting to load a world, this error popup appears: 
![image](https://user-images.githubusercontent.com/10406707/82276759-27aa5b80-9954-11ea-82d3-e6cc486935fd.png)

If I select Yes, load anyway, it just silently crashes seconds later. I wish there was more information I could provide, but there really is nothing more to add.

[The world I was attempting to load](https://github.com/TEdit/Terraria-Map-Editor/files/4647851/World.zip)

**Comment by jerry123z** [comment]
I think this issue is causing #1188 as well.
Once we fail to load bestiary data we don't load the CreativePowers either.

Both of these are preventing the world file from being saved.
