### ISSUE TITLE
my world crashas tedit when i open it

### ISSUE THREAD

**Issue by emberruby2520** [TEdit/Terraria-Map-Editor#1196]
when ever i try to open my world with tedit it crashes and i think it has something to do with the new blocks can you see if you can fix this problem theres a anoyingly placed hallow biome i wanna get rid of

**Comment by Timgo1996** [comment]
I have the same issue when i try to open an world from me. The world opens if I click on Ja (Yes) but nothing happened when i try to save it.


![error](https://user-images.githubusercontent.com/29038308/82302288-ac7b9080-99b9-11ea-8d56-392b64a4140f.png)

**Comment by atheran2** [comment]
For me, I can open one of my worlds but not the other. If it matters, I can open a journey world but not a master one.

**Comment by KatzBar** [comment]
I can only load Large worlds. Otherwise, I get the same crash

**Comment by BinaryConstruct** [comment]
Please try beta 3 and reopen if you still are having this issue.
