### ISSUE TITLE
When I click to save, it never finshes saving-  the bar on the lower right corner stops at "Save Bestiary..."

### ISSUE THREAD

**Issue by Claudia522t** [TEdit/Terraria-Map-Editor#1197]
## Before you submit an issue, please read
 * If you get an unhandled exception, please _**check your log before posting**_.
 * If your log includes _**DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved**_
   * This is a known issue, do not create a new issue, please add your comments to #751
   * People have had the most luck in Windows 7 with updating to DirectX 11.1
     This is found in windows update in the optional updates section or by
     following directions here 
   * https://support.microsoft.com/en-us/kb/179113
 * Please fill out the questions below
 * Instead of copy/pasting text you can attach the entire log file.
 * If your world file is less than 25MB, you can attach it as well.
   
## What were you doing when the issue occured?
 I was moving a building that I build in the wrong spot to another part of the world
## Post relevant contents of log or attach log file _**(very important)**_:
05-19-2020 12:42:22: Starting TEdit 4.0.20139.1401 
05-19-2020 12:42:22: OS: Microsoft Windows NT 6.2.9200.0 
05-19-2020 12:42:22: Terraria v1.4 
05-19-2020 12:42:22: Terraria Data Path: C:\Program Files (x86)\Steam\steamapps\common\Terraria\Content 
05-19-2020 12:42:22: Creating Undo cache: C:\Users\claud\AppData\Roaming\TEdit\undo_312799865

**Comment by Claudia522t** [comment]
I'd like to add that this is a journey world

**Comment by AquaDragon6629** [comment]
Mine actually just says Save God Powers forever, and never saves! very strange. Expert, survival world.
