### ISSUE TITLE
Cant load my world in TEdit

### ISSUE THREAD

**Issue by TyrManda** [TEdit/Terraria-Map-Editor#1198]
[TEditLog.txt](https://github.com/TEdit/Terraria-Map-Editor/files/4650565/TEditLog.txt)

   
## What were you doing when the issue occured? 
Just loaded the world

## Can you reproduce the issue?
 it always happens when i try to open it

## What version of Terraria are you using?
 1.4

## Post relevant contents of log or attach log file _**(very important)**_:
TEdit v4.0.20139.1401
TEdit Max World: 226 Current World: 226

the error is : Unexpected position: invalid tile Entities Section

System.IO.FileFormatException: Unexpected Position: Invalid Tile Entities Section
in TEditXNA.Terraria.World.LoadV2(BinaryReader b,String filename, World w)
in TEditXNA.Terraria.World.LoadWorld(String filename)

**Comment by BinaryConstruct** [comment]
This will be fixed with #1200. Please follow that issue for progress
