### ISSUE TITLE
TEdit wont open Small or Medium Worlds

### ISSUE THREAD

**Issue by KatzBar** [TEdit/Terraria-Map-Editor#1199]
## Before you submit an issue, please read
 * If you get an unhandled exception, please _**check your log before posting**_.
 * If your log includes _**DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved**_
   * This is a known issue, do not create a new issue, please add your comments to #751
   * People have had the most luck in Windows 7 with updating to DirectX 11.1
     This is found in windows update in the optional updates section or by
     following directions here 
   * https://support.microsoft.com/en-us/kb/179113
 * Please fill out the questions below
 * Instead of copy/pasting text you can attach the entire log file.
 * If your world file is less than 25MB, you can attach it as well.
   
## What were you doing when the issue occurred?

I was trying to edit the medium world I was playing at the moment.
When I selected the map I got the crashed attached.
After selecting Ja [Yes] It froze and crashed.
I tried a small world with the whIt same Results.
But on a Large world, It works Normal 

## Can you reproduce the issue?

Yes happens every time I load a small one or medIum one

## What version of Terraria are you using?

1.4.2

![TEdt](https://user-images.githubusercontent.com/65604630/82329893-5242f580-99e2-11ea-8edf-9385c35c9d81.PNG)

*edIt*
I Translated the one german phrase In there
[The error Is: Cannot read beyond the end of the data stream]

**Comment by richdog** [comment]
I'm seeing the same issue when loading in my large world.

**Comment by finleyuk8** [comment]
I am also getting this issue on a large world

**Comment by Shona1984** [comment]
> I am also getting this issue on a large world, anyone know of a fix?

This issue happens for me only if i  try to load a journey map. I can load a normal classic map without any issues.

**Comment by denormative** [comment]
Same with a small Journey world. Don't know enough C# to debug further unfortunately. :(

**Comment by BinaryConstruct** [comment]
Please try https://github.com/TEdit/Terraria-Map-Editor/releases/tag/4.0.0-beta3
