### ISSUE TITLE
Tile Entities Break World (Pylon, Hat Rack, Weapon Rack, Display Doll, Item Frame)

### ISSUE THREAD

**Issue by jerry123z** [TEdit/Terraria-Map-Editor#1200]
# What were you doing when the issue occurred?
Loading a world with existing Weapon Racks results in the Weapon Rack tiles being loaded empty. (Item doesn't show up in terraferma View)
Saving the world file without making any changes results in the deletion of items in the Weapon Rack.

## Can you reproduce the issue?
Yes

## This issue is being worked on here #1215

**Comment by jerry123z** [comment]
At the moment I'd guess it's an issue with the loading of container tiles.

**Comment by BinaryConstruct** [comment]
I was a little concerned with this section. The TileEntity and TileEntityItems are the relevant class files. https://github.com/TEdit/Terraria-Map-Editor/blob/master/TEditXna/Terraria/TileEntity.cs

**Comment by jerry123z** [comment]
Hi @BinaryConstruct, how did you get the save format for hack racks and display dolls? I'd like to look it over.

**Comment by BinaryConstruct** [comment]
Within visual studio you can add a reference to TerrariaServer. You can then Ctrl+Click (or F12 depending on your shortcuts) to navigate to definition for the WorldFile.

Alternatively, and probably easier, you can use [JustDecompile](https://www.telerik.com/products/decompiler.aspx) or [dotPeek](https://www.jetbrains.com/decompiler/).

**Comment by BinaryConstruct** [comment]
I also use [WinMerge](https://winmerge.org/?lang=en) for binary (hex) comparison of world files before and after saving. It can help track down anything that changed with the file. Open a world file, don't make changes. Click save as, compare the two files as binary in WinMerge.

**Comment by BinaryConstruct** [comment]
@jerry123z FYI, you might want to pull the latest changes before committing to much work. I reorganized the folder structure.

**Comment by jerry123z** [comment]
Sure, I haven't done anything yet just skimmed through the terrariaServer, I'm still at work for the day.

**Comment by atheran2** [comment]
Probably related to this are chests. Doesn't affect the already existing ones, at least I didn't notice anything, but if I place a chest from TEdit, the chest exists in my world but the contents are gone.

**Comment by jerry123z** [comment]
Looks like the issue for the weapon rack is in the world.validate() function. It's clearing the tileEntities collection during validation.

**Comment by atheran2** [comment]
Wish I could help more, but I'm a 3d artist and my programming is pretty basic, but if you need any help testing anything specific, please tell me and I will.

**Comment by BinaryConstruct** [comment]
Please try Beta 7. If you still have issues with 1.4.0.4 and 228 world files, reopen this ticket.
