### ISSUE TITLE
"Save Bestiary" infinite saving message

### ISSUE THREAD

**Issue by pvini07BR** [TEdit/Terraria-Map-Editor#1202]
## What were you doing when the issue occured?
i was trying to save changes in a world

## Can you reproduce the issue?
just try to save a world in tedit, and it will not save because there is the "Save Bestiary..." message that appears forever when trying to save

## What version of Terraria are you using?
1.4.0.2

## Post relevant contents of log or attach log file _**(very important)**_:
05-19-2020 15:17:37: Starting TEdit 4.0.20140.1015 
05-19-2020 15:17:37: OS: Microsoft Windows NT 6.1.7601 Service Pack 1 
05-19-2020 15:17:40: Terraria v1.4 
05-19-2020 15:17:40: Terraria Data Path: C:\Program Files (x86)\Steam\steamapps\common\Terraria\Content 
05-19-2020 15:17:44: Creating Undo cache: C:\Users\pvini07BR\AppData\Roaming\TEdit\undo_720950336

**Comment by BinaryConstruct** [comment]
Is this with beta 3? It might be related to #1200.

**Comment by pvini07BR** [comment]
> Is this with beta 3? It might be related to #1200.

yes it is

**Comment by BinaryConstruct** [comment]
Could you please attach a zip of your world file? Thanks.

**Comment by piegolf** [comment]
this problem is similar to #1188, I've had both problems

**Comment by pvini07BR** [comment]
> Could you please attach a zip of your world file? Thanks.

well, i just used the tedit itself to generate a flat world, and i just removed some dirt walls and tried to save

**Comment by BinaryConstruct** [comment]
> 
> 
> > Could you please attach a zip of your world file? Thanks.
> 
> well, i just used the tedit itself to generate a flat world, and i just removed some dirt walls and tried to save

Thanks! This comment helped me track down the issue. Will be resolved in Beta 4.
