### ISSUE TITLE
TEdit 4 Schematic Issues

### ISSUE THREAD

**Issue by BinaryConstruct** [TEdit/Terraria-Map-Editor#1203]
If you are having issues related to schematics, please attach your schematic here and leave a comment. Thanks!

**Comment by nosnowowie93347** [comment]
This schematic causes an Error: index out of range error
I don't remember if that was the exact message. See the other issue where I tagged u @BinaryConstruct 
here:
[Schematics.zip](https://github.com/TEdit/Terraria-Map-Editor/files/4654611/Schematics.zip)
I would help u with the coding, but I don't know CPP or C# yet only java, CSS and python

**Comment by nosnowowie93347** [comment]
I may be able to help u if u still need help next week
This week I will try to learn C#

**Comment by BinaryConstruct** [comment]
Start here: https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/
