### ISSUE TITLE
Stuck at "validating world" 

### ISSUE THREAD

**Issue by Estaslol** [TEdit/Terraria-Map-Editor#1205]
## Before you submit an issue, please read
 * If you get an unhandled exception, please _**check your log before posting**_.
 * If your log includes _**DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved**_
   * This is a known issue, do not create a new issue, please add your comments to #751
   * People have had the most luck in Windows 7 with updating to DirectX 11.1
     This is found in windows update in the optional updates section or by
     following directions here 
   * https://support.microsoft.com/en-us/kb/179113
 * Please fill out the questions below
 * Instead of copy/pasting text you can attach the entire log file.
 * If your world file is less than 25MB, you can attach it as well.
   
## What were you doing when the issue occured?
Tried to save the world after copy pasting a simple structure in a pre harmode world
## Can you reproduce the issue?
Yes, everytime i open my world and try copy/paste a structure and try to save 
## What version of Terraria are you using?
latest
## Post relevant contents of log or attach log file _**(very important)**_:

**Comment by Malteusa** [comment]
It seems to get stuck validating in worlds with a large amounts bestiary entries

**Comment by BinaryConstruct** [comment]
This is related to #1200
