### ISSUE TITLE
Pylons glitch when saving TEdit world

### ISSUE THREAD

**Issue by mikparil** [TEdit/Terraria-Map-Editor#1206]
## What were you doing when the issue occured?
I edited my world, went back into the game using the edited world, and the pylons were glitched

## Can you reproduce the issue?
Yes. Have 2 pylons down in separate towns, open and save with TEdit, and go back into game and they will not work anymore. A quick fix for now is to break them and place them back.

## What version of Terraria are you using?
1.4.1

**Comment by BinaryConstruct** [comment]
This is related to #1200
