### ISSUE TITLE
Issue placing tiles in TEdit v4.0.0.0 Beta 4. No errors, but only fill works for placements. Brush and pencil do not take any actions. Tried with multiple settings, room draw on and off. Terraria is 1.4.0.2. No log file errors found.

### ISSUE THREAD

**Issue by Miridarna** [TEdit/Terraria-Map-Editor#1207]
## Before you submit an issue, please read
 * If you get an unhandled exception, please _**check your log before posting**_.
 * If your log includes _**DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved**_
   * This is a known issue, do not create a new issue, please add your comments to #751
   * People have had the most luck in Windows 7 with updating to DirectX 11.1
     This is found in windows update in the optional updates section or by
     following directions here 
   * https://support.microsoft.com/en-us/kb/179113
 * Please fill out the questions below
 * Instead of copy/pasting text you can attach the entire log file.
 * If your world file is less than 25MB, you can attach it as well.

**Comment by Miridarna** [comment]
As a note - multiple close/reopen of the world file eventually allows feature use. No security software or other interference found

**Comment by BinaryConstruct** [comment]
Did you use the marquee "blue box" selection? This will only allow changes within the box. https://github.com/TEdit/Terraria-Map-Editor/wiki/Toolbar#selection-tool-s

**Comment by Miridarna** [comment]
I did not - I opened the map, waited for render, selected brush, and it just....wouldn't. It only seems to happen for one world that is freshly made for this version of Terraria, and it is ridiculously intermittent.

**Comment by Miridarna** [comment]
[TEditLogError.txt](https://github.com/TEdit/Terraria-Map-Editor/files/4660640/TEditLogError.txt)
And now, when opening any world, it is getting the attached error (renamed log so it did not overwrite)

**Comment by BinaryConstruct** [comment]
It looks like it is loosing control of your GPU. Do you have any other GPU applications running?

**Comment by Miridarna** [comment]
Nothing running but TEdit, Chrome (wiki, ads blocked, so no videos), and Discord (no active calls). I'm getting the same error with only TEdit running, with discord and chrome closed out as well, from a fresh (within 15 minutes) reboot (no fast startup).
Tried again with resource monitor running, nothing else is using GPU except the OS, and that only a fraction of a percent. I'm not sure why its tossing that string :(

**Comment by Miridarna** [comment]
Not sure if this makes any difference, but it always starts happening on a Journey world, then generates the error on every world after that.

**Comment by BinaryConstruct** [comment]
Have you tried updating your graphics drivers? Also, the only system I have to test on is Windows 10. If you have a machine with windows 10 could you please try it?

**Comment by Miridarna** [comment]
Graphics drivers confirmed as newest per nvidia, and all my machines are Windows 10 - I get the same error on my laptop as well as my desktop, different update levels of Windows 10 - one is 1903, the other 1809.

**Comment by BinaryConstruct** [comment]
Please try Beta 7. If you still have issues with 1.4.0.4 and 228 world files, reopen this ticket.
