### ISSUE TITLE
Changing a World From Expert to Master causes the world to fail on loading

### ISSUE THREAD

**Issue by zchilds** [TEdit/Terraria-Map-Editor#1209]
## What were you doing when the issue occured?
Attempting to change the world from Expert to Master

## Can you reproduce the issue?
I loaded a world that was in Master and converted it to Expert.
Upon trying to bring it back from Expert to Master, the world fails to load on startup.

## What version of Terraria are you using?
v1403

## Post relevant contents of log or attach log file _**(very important)**_:
Error does not occur directly within TEdit, but rather occurs upon trying to load the world in Terraria.

**Comment by BinaryConstruct** [comment]
Beta 5 adds support for 1403.

**Comment by zchilds** [comment]
You guys work fast. Thank you so much!
