### ISSUE TITLE
Trying to fix my world and cant load it into tedit

### ISSUE THREAD

**Issue by CVL02** [TEdit/Terraria-Map-Editor#1210]
This it the error code when i load it into tedit: https://gyazo.com/c992b6a621397399f5666f5a2de47c2e

This is the error when i try to load into the world from base game: https://gyazo.com/e568bb591ec34ee3fe92fe2212ca58d9

any help on either problem would be much thanks :)

also i've tryed restoring previous versions and there are none. Im fine with back tracking my world but i have a decent amount of stuff on there i wouldn't like to lose

**Comment by BinaryConstruct** [comment]
Beta 5 should fix this.

**Comment by BinaryConstruct** [comment]
Note #1200 is still an issue
