### ISSUE TITLE
Jouney Map Error on Loading

### ISSUE THREAD

**Issue by Shona1984** [TEdit/Terraria-Map-Editor#1211]
Terraria Version: 1.4.0.3
tEdit Version: 4.0.0 Beta 4
Map Size: Large
Game Mode: Journey
Last think i did: Defeted the Eye of Cthulhu

Error
![tedit_error](https://user-images.githubusercontent.com/1239650/82532292-56d1f000-9b41-11ea-8c2b-af5625e63e54.png)

**Comment by Shona1984** [comment]
Ok i saw the game got a small update which must be the problem

**Comment by BinaryConstruct** [comment]
Beta 5 should fix this.
