### ISSUE TITLE
Beta 4 does not load textures in

### ISSUE THREAD

**Issue by Relinquished001** [TEdit/Terraria-Map-Editor#1212]
The beta 4 seems to have an issue where loading in the world will sometimes stick the world without textures. Like when the world is zoomed out and everything is a colored square as opposed to the in game textures. I could only fix it by loading a previous version of my world

## What were you doing when the issue occured?
Loading a world.

## Can you reproduce the issue?
Yes. Every time I load the world it loads without textures.

## What version of Terraria are you using?
Latest.

## Post relevant contents of log or attach log file _**(very important)**_:
I do not know where to find the log but here is the world.
[1st_Best2.zip](https://github.com/TEdit/Terraria-Map-Editor/files/4661032/1st_Best2.zip)

**Comment by Relinquished001** [comment]
Also if the world doesnt correctly load the textures, It says it saves but when loading in game leads to a Loading Failed message.

**Comment by Jinrain** [comment]
Version 1.4.0.2 worlds are compatible with TEDIT Beta 4. Version 1.4.0.3 worlds are not supported with this version. Wait for beta 5 @Relinquished001.

**Comment by BinaryConstruct** [comment]
File loading should be fixed with beta 5. Textures means TEdit does not have access to or cannot located the terraria folder. https://github.com/TEdit/Terraria-Map-Editor/wiki/Install-Requirements#for-sprite-viewing
