### ISSUE TITLE
Unable to Use/Load T-edit'd worlds.

### ISSUE THREAD

**Issue by Cevet** [TEdit/Terraria-Map-Editor#1213]
To clarify right away, yes I obviously know this is new and very much in beta.

But it seems plenty of people are able to edit and save worlds, then actually play them afterwards. I'm able to load a world into Tedit, I'm able to "save" it, but anytime I go to load it, it instantly says the file is corrupted or it simply loads me into the world 'before' I ever opened it with Tedit.

I was wondering if anyone else has the same issue, or if someone can either confirm this is a known problem--OR can correct me on what I'm doing wrong?
   
## Post relevant contents of log or attach log file _**(very important)**_: I really don't know what to post other than the world file before and after trying to edit it. So I'll post both I guess.

Before Edit (loadable): 
[Mirage_Expanse.zip](https://github.com/TEdit/Terraria-Map-Editor/files/4661924/Mirage_Expanse.zip)

After Edit (Un-Loadable):
[Mirage_Expanse-Edited.zip](https://github.com/TEdit/Terraria-Map-Editor/files/4661957/Mirage_Expanse-Edited.zip)

**Comment by Limmy-P** [comment]
I have the same issue, made a new world today and went to copy/paste a base from my old world and the new one won't load. I assume the hotfix that just came out today broke something.

**Comment by Jinrain** [comment]
Version 1.4.0.2 worlds are compatible with TEDIT Beta 4. Version 1.4.0.3 worlds are not supported with this version. Wait for beta 5 @Cevet

**Comment by BinaryConstruct** [comment]
Should be fixed with beta 5.
