### ISSUE TITLE
When trying to load up world it stops at calculating colors.

### ISSUE THREAD

**Issue by LewdLewd** [TEdit/Terraria-Map-Editor#1217]
## Before you submit an issue, please read
 * If you get an unhandled exception, please _**check your log before posting**_.
 * If your log includes _**DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved**_
   * This is a known issue, do not create a new issue, please add your comments to #751
   * People have had the most luck in Windows 7 with updating to DirectX 11.1
     This is found in windows update in the optional updates section or by
     following directions here 
   * https://support.microsoft.com/en-us/kb/179113
 * Please fill out the questions below
 * Instead of copy/pasting text you can attach the entire log file.
 * If your world file is less than 25MB, you can attach it as well.
   
## What were you doing when the issue occured?
Opening my world in TEdit
## Can you reproduce the issue?
Every time I try to open my world in TEdit
## What version of Terraria are you using?
1.4
## Post relevant contents of log or attach log file _**(very important)**_:
Dont know where to find log.

An error show when I try to load it up that says: Unable to reach beyond the end of the stream.

**Comment by LewdLewd** [comment]
I can still play in the world. 
[The_Defecation_of_Falsehood.zip](https://github.com/TEdit/Terraria-Map-Editor/files/4664300/The_Defecation_of_Falsehood.zip)

**Comment by BinaryConstruct** [comment]
Sound like #1200

**Comment by BinaryConstruct** [comment]
Thanks for attaching a world file, this will help.

**Comment by BinaryConstruct** [comment]
This world loaded with beta 6 for me.

**Comment by TheDreamweaver** [comment]
@BinaryConstruct I still run into the same issue with my own world. It persists even with beta six.

**Comment by TheDreamweaver** [comment]
The world in question was generated in the initial 1.4 release. A world made in the 1.4.0.3 release seems to load fine though (there's also no pylons in this second world, so it may be that as well).

**Comment by TheDreamweaver** [comment]
[First World (the one getting locked at Calculating Colors)](https://mega.nz/file/e9sH1YqK#1BauIz3Gak0IAP9xvYcr-f5WBlbK7YlRSCCLkJi4PV8)

[Second World](https://mega.nz/file/j88HHAbK#UWgCvBlY6JLpXpNrkiq8AJccY9Za2imQUpEYM3HJzx0)
