### ISSUE TITLE
Load Failed - Failed to Load Textures

### ISSUE THREAD

**Issue by 7larson** [TEdit/Terraria-Map-Editor#1218]
## What were you doing when the issue occured?
Attempting to load a world edited in TEdit 4.0 Beta, I get a "Load Failed!" message. Checking the TEdit log reveals this to be due to a texture issue.

## Can you reproduce the issue?
Yes, any attempts to edit the world and load it still produce this issue.

## What version of Terraria are you using?
Journey's End - 1.4.0.3

## Post relevant contents of log or attach log file _**(very important)**_:
05-21-2020 14:55:31: Failed to load texture: Images\Tree_Branches_1029 
05-21-2020 14:55:31: The content file was not found. 
05-21-2020 14:55:31: Failed to load texture: Images\Tree_Tops_1029 
05-21-2020 14:55:31: The content file was not found. 

I thought this was possibly because of pasting a structure over some trees that then had the bottoms missing so it didn't know how to place the tops, but I removed any and all remaining bits of tree I could possibly find and stray blocks that didn't otherwise belong and I still can't find what's causing these two textures to fail to load. I might be missing something else obvious but I'm not sure what, would love advice!

EDIT: I realized that these two things are potentially not related. I just noticed that TEdit for whatever reason just has decided not to load the tops of trees, and that's probably what the log is referring to. Not sure why the game is not loading my world then as a result. Any further help would be appreciated. I have tested multiple worlds now in TEdit and none of them load the tops of trees (the actual leaves).

Last edit, I promise. Further testing shows that every world I edit in TEdit fails to load, too. Not sure why. Even if the only thing I do is open in TEdit, save, and then close and try to load in Terraria, it fails to load. Only other strange thing I notice in TEdit 4 is that the NPCs seem to be tiling strangely across 5 vertical tiles, rather than their usual 3 high. Not sure if this is related.

**Comment by BinaryConstruct** [comment]
Probably related to #1200

**Comment by 7larson** [comment]
Hmm, I haven't made any further changes to the world I was working on but now when I attempt to load it I'm getting an error and trying to force it to load doesn't work. The error is slightly different from the one mentioned in 1200, not sure if related but definitely possible.
![8f9d7e0111c1624b6396a8eeef678551](https://user-images.githubusercontent.com/43255525/82617875-02f1f600-9b97-11ea-9cad-b0812c967fb8.png)
 I hope I haven't lost it all, I'd worked pretty hard on a large building last night, I should have tested to make sure it was working before.

**Comment by 7larson** [comment]
Downloaded Beta 5 - I can now open the world again successfully and the treetops are displaying correctly. This seems to have solved the issue! Thank you for your hard work :)
