### ISSUE TITLE
cant put builds from world to world

### ISSUE THREAD

**Issue by Aced-Vulpes** [TEdit/Terraria-Map-Editor#1224]
I was taking a build from one of my worlds and putting it in a new one, whenever I save it it has an unown file location. I can reproduce it as I cant not to anything else. I use 1.4.0.3 with BETA 5

Log:I was taking a build from one of my worlds and putting it in a new one, whenever I save it it has an unown file location. 

I wish I could have someone do this for me, but its a fairly quick thing to do myself but this problem stops me from this

**Comment by BinaryConstruct** [comment]
#1200 might be your issue.

**Comment by Aced-Vulpes** [comment]
Now it saves and shows but my changes to the world dont show up

**Comment by Mancinix** [comment]
It won't load the saved world anymore, keep saying "load error, Load backup", which i have done. This has been happeneing since beta 4.

**Comment by BinaryConstruct** [comment]
Please try Beta 7. If you still have issues with 1.4.0.4 and 228 world files, reopen this ticket.
