### ISSUE TITLE
Load failed after basic tiles

### ISSUE THREAD

**Issue by KaruzoUTB** [TEdit/Terraria-Map-Editor#1225]
I read the rules of adding new question but
   
## What were you doing when the issue occured?

I just added couple of dirt and sand blocks to my world. Then I saved it and everytime I've tried to play on that map, it says that it couldn't been loaded.

## Can you reproduce the issue?
yes
## What version of Terraria are you using?
newest

**Comment by ThomasHillebrink** [comment]
I'm having the same issue, however only with one particular save file. Even changing nothing and only saving the file in TEdit will cause it to fail loading. TEdit version does not seem to make a difference.
It may or may not be related but it is a "drunk world" with seed 05162020


[Tranquil_Mesa_of_the_Tooth.zip](https://github.com/TEdit/Terraria-Map-Editor/files/4667856/Tranquil_Mesa_of_the_Tooth.zip)

**Comment by KaruzoUTB** [comment]
Oh yea, that sounds like the point. I got also mannequins..

**Comment by BinaryConstruct** [comment]
Sounds like #1200
