### ISSUE TITLE
TEdit4 beta 6 crash on right click on chest

### ISSUE THREAD

**Issue by usama8800** [TEdit/Terraria-Map-Editor#1226]
## What were you doing when the issue occurred?
Trying to edit chests (by right clicking on a chest) crashes the program. There is no error and nothing in the log file.

## Can you reproduce the issue?
Creating a new world and trying on a random chest produced the same issue

## What version of Terraria are you using?
1.4.0.3

## Entire log file:

    05-22-2020 07:41:41: Starting TEdit 4.0.0.0  
    05-22-2020 07:41:41: OS: Microsoft Windows NT 6.2.9200.0  
    05-22-2020 07:41:41: Terraria v1.4.0.3  
    05-22-2020 07:41:41: Terraria Data Path:  
    E:\Games\SteamLibrary\steamapps\common\Terraria\Content
    05-22-2020 07:41:42: Creating Undo cache:  
    C:\Users\usama\AppData\Roaming\TEdit\undo_56027618

**Comment by usama8800** [comment]
Could it be that the zip file for TEdit4-beta6 is not updated? It says `Starting TEdit 4.0.0.0 `

**Comment by BinaryConstruct** [comment]
I don't think so. I haven't been able to reproduce this issue yet.

**Comment by GregariousJB** [comment]
Trying to be slightly helpful, I just created a new world, right-clicked on several chests (in TEdit Beta 6) and it worked fine. He's right about the "You are using an outdated version of TEdit" message, though. Maybe that's throwing people off and they're going to the website to accidentally download an outdated version?

**Comment by ERMtn** [comment]
Whenever I edit and save a world with this Beta6, Terraria can't load the map, it says "Load failed!" everytime...
Any solution or just wait for new version?

**Comment by darianfall** [comment]
I am experiencing the same issue as Usama8800.

I have reinstalled the game, removed all Terraria data that is not inside the game folder, closed background programs, started a new world (one Journey and one Expert), save and exit the game, start TEDIT4 Beta 6, open up either world and right click on a chest (ones I placed myself and ones already in the world). The program freezes between 2-5 seconds and crashes to the desktop.

I am able to right click and edit signs and weapon racks successfully.

05-22-2020 20:30:19: Starting TEdit 4.0.0.0 
05-22-2020 20:30:19: OS: Microsoft Windows NT 6.2.9200.0 
05-22-2020 20:30:20: Terraria v1.4.0.3 
05-22-2020 20:30:20: Terraria Data Path: E:\Steam\steamapps\common\Terraria\Content 
05-22-2020 20:30:20: Creating Undo cache: C:\Users\user\AppData\Roaming\TEdit\undo_579111423 

Please let me know what I can do to help. I've tried adjusting various settings in each world to no avail. I cannot get TEDIT Beta 5 to reproduce this issue.

I am using Windows 10 Home Version 1909.

**Comment by usama8800** [comment]
I ran TEdit through the source code and got this error

```
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=TEdit
  StackTrace:
   at TEdit.Terraria.Item.ToString() in C:\Users\usama\Documents\Terraria-Map-Editor\src\TEdit\Terraria\Item.cs:line 120
```

https://github.com/TEdit/Terraria-Map-Editor/blob/e9cd8731ee661851edfa8a8f08fb6e47c1723c0a/src/TEdit/Terraria/Item.cs#L120

Changing it to `return ""` worked as a temporary fix. I don't know what it breaks tho

**Comment by usama8800** [comment]
Upon further inspection, I figured out the error occurs when trying to show the name of a null item (when the chest has empty slots) and I tested on a full chest and I was right.

**Comment by GregariousJB** [comment]
You need to make a better guide on how to reproduce this, because I'm not crashing when placing and right-clickinga an empty chest:

![image](https://i.imgur.com/jx2AqjP.png)

**Comment by ddbrown30** [comment]
FWIW, I am also getting the issue. Also, my version also shows v4.0.0.0 in the title bar even though I'm using beta 6. I can't promise this will reproduce the issue, but here's what I did:
1. Play the game
2. Find a chest in the world
3. Loot the chest and pick it up
4. Head home and place the chest in base
5. Save and exit the game
6. Load TEdit and load the world
7. Right click on the chest

I've also uploaded my world in case that will help. If you right click any of the gold chests in my home base, it will crash.

[The_Perpetual_Colony.zip](https://github.com/TEdit/Terraria-Map-Editor/files/4672155/The_Perpetual_Colony.zip)

**Comment by GregariousJB** [comment]
> I've also uploaded my world in case that will help. If you right click any of the gold chests in my home base, it will crash.
> 
> [The_Perpetual_Colony.zip](https://github.com/TEdit/Terraria-Map-Editor/files/4672155/The_Perpetual_Colony.zip)

I'm still not crashing.

TEdit Beta 6
Windows 10 64bit LTSC 1809

![image](https://i.imgur.com/h21B36F.png)

**Comment by usama8800** [comment]
https://youtu.be/R-eVJ0ag_RA

**Comment by GregariousJB** [comment]
There it is. Video evidence is about the best bug report you can give. Too bad it's not posting a crash log, though.

I was thinking maybe "Windows version" as I was typing mine out - 1809. I wonder if @BinaryConstruct is also on 1809, hence why he and I were unable to reproduce this.

Only other thing I can think of is XNA version. Looks like it should be 4.0, but TEdit is pretty good about checking that first before it runs, and even giving the user the option to download it if it isn't detected. I think this is all in Binary's hands now.

**Comment by ddbrown30** [comment]
My XNA redistributable is version 4.0 and I'm on Win 10 Pro 1909 AKA 10.0.18363.

**Comment by BinaryConstruct** [comment]
My machine is on Win 10 Pro 1909 with nvidia 445.87 so I don't think that is the issue.
