### ISSUE TITLE
When loading in an edited world, Terraria says "World Load Failed"

### ISSUE THREAD

**Issue by TheRogue12** [TEdit/Terraria-Map-Editor#1228]
## What were you doing when the issue occurred?
I had finished removing the Corruption from my world in TEdit and was loading it into Terraria
## Can you reproduce the issue?
Yes
## What version of Terraria are you using?
1.4.0.3
## Post relevant contents of log or attach log file _**(very important)**_:
[Log_20200522170058296.log](https://github.com/TEdit/Terraria-Map-Editor/files/4670802/Log_20200522170058296.log)

I also attached my world files from before and after the edit (Final Journey 2 is before, and Final Journey 3 is after).

[Final_Journey2.zip](https://github.com/TEdit/Terraria-Map-Editor/files/4670808/Final_Journey2.zip)
[Final_Journey3.zip](https://github.com/TEdit/Terraria-Map-Editor/files/4670809/Final_Journey3.zip)

------------------------------------------------------Edit----------------------------------------------------

TEdit claims that I am using an outdated version when I open it, despite having the latest beta installed (beta 6). Also, whenever I load this world in TEdit (Final Journey 3), it gives the error in the following screenshot: 

![Screenshot (179)](https://user-images.githubusercontent.com/45881539/82716969-19f41f00-9c4f-11ea-9c62-076045045ddb.png)

Despite this error, the world loads properly in TEdit.

Furthermore, when I try to save the world file, TEdit says "Final Journey was externally modified since your last save. Do you wish to overwrite" even though I hadn't "externally modified" it.

**Comment by JDSammy** [comment]
There's been issues with having a few specific entities on your world when trying to edit worlds: if you have any Pylons, Hat Racks, Mannequins (both types), Weapon Racks, or Item Frames, you get the error message that you see there. If it doesn't find any of these entities, I've found that it will usually work. So, try and get rid of each of these entities, then try editing the world. If it doesn't give you an error, it should allow you to be able to edit it.

**Comment by BinaryConstruct** [comment]
Please try [Beta 7](https://github.com/TEdit/Terraria-Map-Editor/releases/tag/4.0.0-beta7). If you still have issues with 1.4.0.4 and 228 world files, reopen this ticket.
