### ISSUE TITLE
My world stuck at Calculation Color, but my others worlds open fine

### ISSUE THREAD

**Issue by Thanos117** [TEdit/Terraria-Map-Editor#1230]
## Before you submit an issue, please read
 * If you get an unhandled exception, please _**check your log before posting**_.
 * If your log includes _**DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved**_
   * This is a known issue, do not create a new issue, please add your comments to #751
   * People have had the most luck in Windows 7 with updating to DirectX 11.1
     This is found in windows update in the optional updates section or by
     following directions here 
   * https://support.microsoft.com/en-us/kb/179113
 * Please fill out the questions below
 * Instead of copy/pasting text you can attach the entire log file.
 * If your world file is less than 25MB, you can attach it as well.
   
## What were you doing when the issue occured?
Im using Tedit
## Can you reproduce the issue?
My world stuck at calculation color, can't use selection tool, titles error etc
## What version of Terraria are you using?
1.4.0.3
## Post relevant contents of log or attach log file _**(very important)**_:
[Easy_World.zip](https://github.com/TEdit/Terraria-Map-Editor/files/4671061/Easy_World.zip)
Here is my world

**Comment by TheDreamweaver** [comment]
I run into the same issue. The only differences that I can think of that would matter are that the first world was made prior to 1.4.0.3 (it was made during the initial 1.4 release), and that the first world has pylons in it.

[First World (the one getting locked at Calculating Colors)](https://mega.nz/file/e9sH1YqK#1BauIz3Gak0IAP9xvYcr-f5WBlbK7YlRSCCLkJi4PV8)

[Second World](https://mega.nz/file/j88HHAbK#UWgCvBlY6JLpXpNrkiq8AJccY9Za2imQUpEYM3HJzx0)

**Comment by BinaryConstruct** [comment]
Please try [Beta 7](https://github.com/TEdit/Terraria-Map-Editor/releases/tag/4.0.0-beta7). If you still have issues with 1.4.0.4 and 228 world files, reopen this ticket.
