### ISSUE TITLE
Cant save some world files

### ISSUE THREAD

**Issue by dariyoos** [TEdit/Terraria-Map-Editor#1231]
I can open, edit and save all world files without a problem, but the world I actually want to play in gives me this error when I open it in TEdit. The world file is still playable so I dont think its corrupt? And when I force load it, I cant save the changes.
![hhh](https://user-images.githubusercontent.com/65815342/82730860-2a65d180-9d03-11ea-8b32-00a462b2eb1f.PNG)

**Comment by Reddey** [comment]
Just a shot in the dark but i have the exact same problem and someone told me that hat racks and mannequins bug the program, im gonna try removing the 2 hat racks and few mannequins i have in my world and reply if it worked or not.

**Comment by BinaryConstruct** [comment]
Please try [Beta 7](https://github.com/TEdit/Terraria-Map-Editor/releases/tag/4.0.0-beta7). If you still have issues with 1.4.0.4 and 228 world files, reopen this ticket.
