### ISSUE TITLE
Can't place full Fallen Logs(488).

### ISSUE THREAD

**Issue by JulienYR** [TEdit/Terraria-Map-Editor#1233]
The Fallen Log sprite is incomplete, only the top left tile is available. It needs the full sprite like the demon altar. 
I'm posting this issue because too many people destroyed them after worldgen, making  some of the new content unavailable.

**Comment by BinaryConstruct** [comment]
Could you paste a screenshot of what it should look like? Thanks,
https://github.com/TEdit/Terraria-Map-Editor/blob/master/src/TEdit/settings.xml#L5335

**Comment by JulienYR** [comment]
Of course, right now the sprite is pasted like this : 
https://imgur.com/a/uSByyrj

While it should look like this : 
https://imgur.com/6vARytl
https://gamepedia.cursecdn.com/terraria_gamepedia/1/10/Fallen_Log.png?version=eb039359f15b2caf822e414c91ee225f

**Comment by BinaryConstruct** [comment]
Perfect, thank you. I'll get this in beta 8
