### ISSUE TITLE
Adding the new fishing crate sprites

### ISSUE THREAD

**Issue by eraogon** [TEdit/Terraria-Map-Editor#1234]
Not sure if this was noticed but the new fishing crate sprites (ocean, oasis, obsidian, frozen and all the new hardmode equivalents) are missing and when the picker tool is used it selects the default wooden crate.

**Comment by BinaryConstruct** [comment]
If you have a world file with them placed please upload and send the tile x/y and I can add them.  Or feel free to submit a PR to add them to the settings.xml file here: https://github.com/TEdit/Terraria-Map-Editor/blob/master/src/TEdit/settings.xml#L4721-L4732
