### ISSUE TITLE
Error while opening the world.

### ISSUE THREAD

**Issue by SodaDudeTx** [TEdit/Terraria-Map-Editor#1235]
## Before you submit an issue, please read
 * If you get an unhandled exception, please _**check your log before posting**_.
 * If your log includes _**DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved**_
   * This is a known issue, do not create a new issue, please add your comments to #751
   * People have had the most luck in Windows 7 with updating to DirectX 11.1
     This is found in windows update in the optional updates section or by
     following directions here 
   * https://support.microsoft.com/en-us/kb/179113
 * Please fill out the questions below
 * Instead of copy/pasting text you can attach the entire log file.
 * If your world file is less than 25MB, you can attach it as well.
   
## What were you doing when the issue occured?
Trying to load the world
## Can you reproduce the issue?
Yes, every time I try to open the world
## What version of Terraria are you using?
1.4.0.3
## Post relevant contents of log or attach log file _**(very important)**_:
![Capture](https://user-images.githubusercontent.com/28163284/82737582-aa863a00-9cf7-11ea-97eb-919603f3df5d.PNG)

**Comment by TheRogue12** [comment]
Check the comments at issue #1228. If you don't want to read, basically the current version of TEdit has issues with Pylons, Mannequins, Hat Racks, Weapon Racks, and Item frames. Just remove these items from your terraria world before using TEdit (for now).

**Comment by BinaryConstruct** [comment]
Please try [Beta 7](https://github.com/TEdit/Terraria-Map-Editor/releases/tag/4.0.0-beta7). If you still have issues with 1.4.0.4 and 228 world files, reopen this ticket.
