### ISSUE TITLE
Stuck at Calculating Colors

### ISSUE THREAD

**Issue by TheDreamweaver** [TEdit/Terraria-Map-Editor#1236]
When attempting to open my world (initially made in 1.4.0.1), TEdit gets stuck in the "Calculating Colors" state. Removing Pylons doesn't make a difference. Opening other worlds generated after release of 1.4.0.3 (even using the same seed) work fine. Problem has persisted through TEdit releases 5, 6, and 7.
   
## What were you doing when the issue occured?
Opening my world in TEdit

## Can you reproduce the issue?
Yes, anytime I open this world.

## What version of Terraria are you using?
1.4.0.4

## Post relevant contents of log or attach log file _**(very important)**_:
Worlds:
[Worlds.zip](https://github.com/TEdit/Terraria-Map-Editor/files/4673089/Worlds.zip)
Le_Rêve_du_Gens: First world I made in initial 1.4 release. [Gets stuck]
Le_Rêve_du_Gens_Deux: World generated after 1.4.0.3, using same seed as first world. [Loads fine]
Weary_Dab_of_the_Moon: World generated in 1.4.0.3 using a different seed. [Loads fine]

**Comment by BinaryConstruct** [comment]
Please try beta 8 https://github.com/TEdit/Terraria-Map-Editor/releases/tag/4.0.0-beta8

**Comment by BinaryConstruct** [comment]
It looks like tile 4199,435 has a paint color not in TEdit. You can try this settings file to see if it fixes your issue. https://raw.githubusercontent.com/TEdit/Terraria-Map-Editor/master/src/TEdit/settings.xml

**Comment by TheDreamweaver** [comment]
Changing the settings xml file worked.
