### ISSUE TITLE
Can't save worlds

### ISSUE THREAD

**Issue by Raykiry** [TEdit/Terraria-Map-Editor#1237]
## Before you submit an issue, please read
 * If you get an unhandled exception, please _**check your log before posting**_.
 * If your log includes _**DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved**_
   * This is a known issue, do not create a new issue, please add your comments to #751
   * People have had the most luck in Windows 7 with updating to DirectX 11.1
     This is found in windows update in the optional updates section or by
     following directions here 
   * https://support.microsoft.com/en-us/kb/179113
 * Please fill out the questions below
 * Instead of copy/pasting text you can attach the entire log file.
 * If your world file is less than 25MB, you can attach it as well.
   
## What were you doing when the issue occured?
Purifying my world using the Morph tool
## Can you reproduce the issue?
yes, my worlds still dont save
## What version of Terraria are you using?
1.4.0.3
## Post relevant contents of log or attach log file _**(very important)**_:
05-24-2020 14:33:50: Starting TEdit 4.0.0.0 
05-24-2020 14:33:50: OS: Microsoft Windows NT 6.2.9200.0 
05-24-2020 14:33:50: Terraria v1.4.0.4 
05-24-2020 14:33:50: Terraria Data Path: D:\programs\steamapps\common\Terraria\Content 
05-24-2020 14:33:51: Creating Undo cache: C:\Users\Admin\AppData\Roaming\TEdit\undo_996737730

**Comment by BinaryConstruct** [comment]
Please try beta 8.
