### ISSUE TITLE
Error Net Framework 4.8

### ISSUE THREAD

**Issue by OrochiYagami** [TEdit/Terraria-Map-Editor#1239]
From BETa 2, it is mandatory to have Framework 4.8 installed on the computer ..... But my windows doesn't have NET framework 4.8 ... and I can't install it ... the program only works if you have the framework. ...
How do I make Tedit work without using the 4.8 framework?

**Comment by BinaryConstruct** [comment]
This was changed when restructuring the project. I dropped this back down to 4.6.2 with Beta 8. I hope this helps.
