### ISSUE TITLE
Issue with Tedit version and worlds 

### ISSUE THREAD

**Issue by RNFADED** [TEdit/Terraria-Map-Editor#1240]
My first issue happens each time I open Tedit. It says I have the wrong version and when I click yes to download the newest version, it shows the beta version I'm using as the newest. 
![image](https://user-images.githubusercontent.com/61030019/82775907-62097200-9e06-11ea-9b7b-f73b2e037273.png)

My second issue only happens with new worlds that were created in 1.4.0 or later. Whenever I open worlds that have been created after the past update, I get this error message. The world works fine in game and isn't corrupted. Does Tedit support worlds in 1.4.0.4 or would I have to wait for a newer version?
![image](https://user-images.githubusercontent.com/61030019/82776036-ca585380-9e06-11ea-9416-4188f7f5d97d.png)

**Comment by BinaryConstruct** [comment]
Please try beta 8 for the saving issue. The "out of date" only looks at the last release, so betas are always out of date.

https://github.com/TEdit/Terraria-Map-Editor/releases/tag/4.0.0-beta8
