### ISSUE TITLE
[Feature Request] Corrupt World Repair

### ISSUE THREAD

**Issue by Buddermario7** [TEdit/Terraria-Map-Editor#1243]
My (non-Tedited) world corrupted in and appears to be much smaller in filesize than normal large worlds (5 MB rather than 12). I don't know much about wld files, but is it possible that half the world is still intact and the other half is gone? If so, I think it'd be nice to have something that fills the rest of the world with empty space and adds whatever's necessary so it can still be loaded in the game.

**Comment by BinaryConstruct** [comment]
You can try to force load it in TEdit and copy/paste the working parts to a new world. World files are saved top-down, so usually if anything is left your buildings will be.
