### ISSUE TITLE
World not loading? Attach file here! v1.4.0.4

### ISSUE THREAD

**Issue by BinaryConstruct** [TEdit/Terraria-Map-Editor#1244]
## Do you have a broken world file? Try your backup first.

Terraria and TEdit both make backups of world files, Try locating your .wld, .bak and .TEdit files the following locations:

*  `%USERPROFILE%\Documents\My Games\Terraria\Worlds`
* Steam Cloud: https://support.steampowered.com/kb_article.php?ref=6736-QEIG-8941
  * Windows: `C:\Program Files (x86)\Steam\userdata\<userID>\105600\remote\worlds`
  * Mac: `~/Library/Application Support/Steam/userdata/<userID>/105600/remote/worlds`
  * Linux: `~/.local/share/Steam/userdata/<userID>/105600/remote/worlds`

## No backup? Try the TEdit recovery process.

* https://github.com/TEdit/Terraria-Map-Editor/wiki/Corrupted-World-Recovery

## Does the world work in Terraria, but TEdit won't save it? Attach it with the following info:
* TEdit Version: 
* Terraria Version Created:
* Terraria Version Last Played: 1.4.0.4
* Problem:
* Screenshot:

###  ⚠ A log file is not necessary, but the attached file **MUST** work in Terraria. ⚠

**Comment by Mattbarnhill** [comment]
TEdit Version: 4 beta 8
Terraria Version Created: 1.4.0.1.
Terraria Version Last Played: 1.4.0.4.
Problem: Does not load the zoomed out images but it will show up once you zoom in enough. This map is one I am currently playing, so it does work.

[Naughty_Boonies_of_Chests.zip](https://github.com/TEdit/Terraria-Map-Editor/files/4680388/Naughty_Boonies_of_Chests.zip)
![Zoomed out](https://user-images.githubusercontent.com/58931708/82869729-62803680-9ef4-11ea-9ed3-3f0f6ad33dc9.PNG)
![Zoomed in](https://user-images.githubusercontent.com/58931708/82869737-64e29080-9ef4-11ea-9035-625caece69b1.PNG)

**Comment by Nickakanickiam** [comment]
TEdit Version: 4 beta 8
Terraria Version Created: 1.4.0.0
Terraria Version Last Played: 1.4.0.4
The same problem with "Calculating colors"
[The Cursed Oasis.zip](https://github.com/TEdit/Terraria-Map-Editor/files/4681651/The.Cursed.Oasis.zip)

![image](https://user-images.githubusercontent.com/6378451/82892713-a0af4180-9f58-11ea-82b2-8dd23ced8316.png)
![image](https://user-images.githubusercontent.com/6378451/82892791-c63c4b00-9f58-11ea-9871-2f29b5b8f913.png)

**Comment by swahodle** [comment]
TEdit Version: 4 beta 8
Terraria Version Created: 1.4.0.0
Terraria Version Last Played: 1.4.0.4
The same problem with "Calculating colors" and zoom

[i_hate_you.zip](https://github.com/TEdit/Terraria-Map-Editor/files/4681978/i_hate_you.zip)

**Comment by BinaryConstruct** [comment]
All of these look to be related to the missing illuminate paint. https://github.com/TEdit/Terraria-Map-Editor/issues/1245 Beta 9 includes a fix.

**Comment by BinaryConstruct** [comment]
Please try beta 9 for the tally tab and missing Illuminant Paint calculating colors bug.

**Comment by Mattbarnhill** [comment]
I have no used the map since and it is still having the same issue.

**Comment by schrodingerspsycho** [comment]
TEdit Version: 4 beta 9, clean install
Terraria Version Created: 1.4.0.0
Terraria Version Last Played: 1.4.0.4
The same problem with "Calculating colors" and zoom as above, used illuminant paint on some buildings. Replacing settings.xml with one, mentioned in 1236 fixes my issue
[The_Hedge_of_the_Apple.zip](https://github.com/TEdit/Terraria-Map-Editor/files/4684682/The_Hedge_of_the_Apple.zip)

**Comment by BinaryConstruct** [comment]
@schrodingerspsycho please try beta 10.

**Comment by Mattbarnhill** [comment]
Mine is loading properly now. Thank you very much!

**Comment by schrodingerspsycho** [comment]
Beta10 fixed the issue with "calculating colors" hanging up

**Comment by Gviuck** [comment]
TEdit Version: 4 Beta 10
Terraria Version Created: 1.4.0.1
Terraria Version Last Played: 1.4.0.4
Problem: I dont know but when try to play the world that save, the game closes me, and the name form the world is red. Oh I almost forget it, does not load the sprites in TEdit. Help pls
Screenshot:
![Untitled](https://user-images.githubusercontent.com/41148168/83319832-a45ff400-a1f6-11ea-9ec2-fc41adb21374.png)
![image](https://user-images.githubusercontent.com/41148168/83319901-24865980-a1f7-11ea-8826-6112139ed22b.png)

**Comment by BinaryConstruct** [comment]
@Gviuck Please attach a zip of your world file.

**Comment by HedSut00** [comment]
Tedit version: 4.0.0-beta12
Terraria version created: 1.4.0.2
Terraria Version Last Played: 1.4.0.2 (I haven't updated the game yet)
Problem: Even if I only save the world file in Tedit Terraria says it is an unknown world and crashes after trying to load it.

[Files.zip](https://github.com/TEdit/Terraria-Map-Editor/files/4715060/Files.zip)

**Comment by BinaryConstruct** [comment]
Beta 12 saves worlds that are only compatible with 1.4.0.4.

**Comment by HedSut00** [comment]
I also tried it in beta11 and beta10 and it didn't work

**Comment by BinaryConstruct** [comment]
@HedSut00 `world.wld`  worked for me both before and after editing with TEdit beta 13.

**Comment by yungmax82** [comment]
TEdit Version: 4.0.0 Beta 14
Terraria Version Created: Not Sure, Sorry (Was Created December 3rd of 2016)
Terraria Version Last Played: 1.4.0.4
Problem: Whenever world is attempted to be opened, I get this message: 
![Screenshot (5)](https://user-images.githubusercontent.com/66404076/83717543-f773e580-a600-11ea-853c-2df2041d4a4a.png)

Whenever I attempt to open in TEdit I get this:
![Screenshot (3)](https://user-images.githubusercontent.com/66404076/83717567-02c71100-a601-11ea-9d51-d1890d44f329.png)

This is what TEdit shows when I force Edit it: (It saves my Boss Information/NPC Data on the right, but none of the blocks appear)
![Screenshot (4)](https://user-images.githubusercontent.com/66404076/83717591-183c3b00-a601-11ea-97ac-ea22fd080a08.png)

Screenshot:

**Comment by BinaryConstruct** [comment]
> TEdit Version: 4.0.0 Beta 14
> Terraria Version Created: Not Sure, Sorry (Was Created December 3rd of 2016)
> Terraria Version Last Played: 1.4.0.4
> Problem: Whenever world is attempted to be opened, I get this message:
> ![Screenshot (5)](https://user-images.githubusercontent.com/66404076/83717543-f773e580-a600-11ea-853c-2df2041d4a4a.png)
> 
> Whenever I attempt to open in TEdit I get this:
> ![Screenshot (3)](https://user-images.githubusercontent.com/66404076/83717567-02c71100-a601-11ea-9d51-d1890d44f329.png)
> 
> This is what TEdit shows when I force Edit it: (It saves my Boss Information/NPC Data on the right, but none of the blocks appear)
> ![Screenshot (4)](https://user-images.githubusercontent.com/66404076/83717591-183c3b00-a601-11ea-97ac-ea22fd080a08.png)
> 
> Screenshot:

@yungmax82 Looks like the world didn't attach, be sure to zip it first.

**Comment by yungmax82** [comment]
[worlds_2nd (3).zip](https://github.com/TEdit/Terraria-Map-Editor/files/4727682/worlds_2nd.3.zip)

**Comment by yungmax82** [comment]
^ sorry about that man! not sure if its fixable but if so will definitely paypal you, my little brother who shared my accounts been sad for days because of it

**Comment by yungmax82** [comment]
[2nd.zip](https://github.com/TEdit/Terraria-Map-Editor/files/4727802/2nd.zip)
^The first one is from userdata (Try this one first)

This one is downloaded from steam cloud:
[worlds_2nd (4).zip](https://github.com/TEdit/Terraria-Map-Editor/files/4727824/worlds_2nd.4.zip)

**Comment by BinaryConstruct** [comment]
@yungmax82 I'm sorry your world data was cut off and not recoverable. The new recovery features I added to get the data are now in beta 15. https://github.com/TEdit/Terraria-Map-Editor/releases/tag/4.0.0-beta15
