### ISSUE TITLE
Some world properties didn't save #2

### ISSUE THREAD

**Issue by FeaFrost** [TEdit/Terraria-Map-Editor#1246]
Hello! Thank you for the previous fix (#1229)!

I use beta9 right now and it is still had something wrong in other properties (I attached image).
Everything else changing just fine.

![redframes2](https://user-images.githubusercontent.com/65794994/82860666-f120a200-9f4c-11ea-9da3-f19c28dfc760.png)

### Steps to reproduce the issue?
1. Load any map.
2. Change one of the properties from image.
3. They won't be saved.

### What version of Terraria are you using?
1.4.0.4

### Attach world file
Any world.

**Comment by BinaryConstruct** [comment]
Thanks, I'll update the converter for these property types.
