### ISSUE TITLE
Left side world corruption

### ISSUE THREAD

**Issue by BluePlastics** [TEdit/Terraria-Map-Editor#1248]
**Describe the bug**
The left side of the world is showing weird blocks that aren't there when loading the world in game.

**To Reproduce**
1. Open the map
2. Scroll to the left side of the map
3. View weird blocks

**Expected behavior**
World should appear as it is in game.

**Screenshots**
https://i.imgur.com/7wLDJ4i.png

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version Tedit 4 beta 9
 - Terraria Version 1.4.0.4

**Additional context**
World download available at request.

**Comment by BinaryConstruct** [comment]
The game doesn't scroll all the way to the edge. This is normal.
