### ISSUE TITLE
Sprite Tab

### ISSUE THREAD

**Issue by Dcollins85** [TEdit/Terraria-Map-Editor#1249]
New to TEdit, and I am trying to figure out how the Sprites tab works. I have tried click and dragging, but that doesn't work. I'm 100% sure it's a me problem, how do I place things from the Sprites tab?

Thank you, and sorry about putting this under Bug Report. I didn't know how to properly label this.

**Comment by schrodingerspsycho** [comment]
![1](https://user-images.githubusercontent.com/61247526/83062294-769c7300-a06f-11ea-8e78-8b5bc754d9bb.png)

**Comment by BinaryConstruct** [comment]
https://github.com/TEdit/Terraria-Map-Editor/wiki/Toolbar#sprite-placer-tool-t
