### ISSUE TITLE
Flip X/Flip Y clears some sprites

### ISSUE THREAD

**Issue by FeaFrost** [TEdit/Terraria-Map-Editor#1250]
**Describe the bug**
Problem with Flip X/Flip Y functions on clipboard tab.
I use beta10 right now and when I try to flip by X or Y some area TEdit just crashes.

**In beta9 all worked fine but objects like chests, vases etc just disappeared upon flipping. (I believe it was ok then**

Now "object flipping" is working if selected area is small (like smaller than 150x150 blocks) and all objects remains . Or maybe it's not about the size of area but about the number of objects or smth else, I don't know for sure.

**To Reproduce**
1. Open World;
2. Select an area and copy it;
3. Go to 'Clipboard' tab (right menu);
4. Click on 'Flip X' or 'Flip Y';
5. TEdit crashes without any warning.

**Expected behavior**
Well, I expect normal flipping without crash.

**Screenshots**
![flip_bug](https://user-images.githubusercontent.com/65794994/83124764-3b4e8280-a109-11ea-95b6-d49ea269fd31.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Tedit 4 beta 10
 - Terraria 1.4.0.4

**Comment by BinaryConstruct** [comment]
It is more about the content. If the objects are in the settings.xml it works, if they aren't they get skipped since TEdit cannot identify them. I'm working on some things for improving the whole sprite thing, but it is a large project on it's own. Once that is complete this flip should work.

**Comment by FeaFrost** [comment]
Ok, thank you! I understand the skipping part, It how it should work and worked in previous betas,

I wrote this post mostly to say about the crashes. I had tested same areas and didn't find any connection between the objects to flip and TEdit crashes. But if instead of one large area we select two halves of it, the editor will not crash.
