### ISSUE TITLE
Transfer bestiary progression and the kill tally

### ISSUE THREAD

**Issue by Serenitor** [TEdit/Terraria-Map-Editor#1253]
I'd love to see a feature that enables the user to transfer bestiary progression and tally data from one to another world.

This could be accomplished with an export/import tool for the bestiary and tally.

The problem:
I have spent a significant amount of time on my old world working on completing the bestiary and collecting banners. I would now like to continue playing on a new 1.4 world and carry over a couple of elements of progression from the previous one, such as the bestiary and tally.

I have considered pasting elements from a new 1.4 world onto the old world file as a way to "update" the world, but I'd really rather use a fresh 1.4 world as basis.

**Comment by BinaryConstruct** [comment]
I will add it to the feature requests.
