### ISSUE TITLE
Software cannot be opened.

### ISSUE THREAD

**Issue by hanhailongpan** [TEdit/Terraria-Map-Editor#1254]
[TEditLog.txt](https://github.com/TEdit/Terraria-Map-Editor/files/4700603/TEditLog.txt)
**Before Submitting an Issue**
* If you are having issues loading a world, please attach it to the current version world thread (see pinned issues).
* If you get an unhandled exception or crash, please _**check your log before posting**_.
  * _Copy paste using code [block tags](https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks) into the issue as a comment_

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Version [TEdit 3.11 beta]
 - Terraria Version [1.4.0.4]

**Additional context**

**Comment by BinaryConstruct** [comment]
Please unzip before attempting to run. See https://github.com/TEdit/Terraria-Map-Editor/wiki/Install-Requirements
