### ISSUE TITLE
Software cannot be opened and it deletes itself when i restart my pc

### ISSUE THREAD

**Issue by CLGLXN** [TEdit/Terraria-Map-Editor#1255]
the title says it all.  The software works one time and when i close it and reopen it again it stops working then u turned off my pc and when its back on the files are gone from the place where i put them in

**Comment by BinaryConstruct** [comment]
Please try unzipping the download to a folder, such as c:\games\TEdit.  
See also, https://github.com/TEdit/Terraria-Map-Editor/wiki/Install-Requirements
