### ISSUE TITLE
Help Wanted Crash: Problem Event Name: CLR20r3, SharpDx

### ISSUE THREAD

**Issue by RhynzD** [TEdit/Terraria-Map-Editor#1256]
# Help Wanted

If you have this issue, could you please attach
* TEdit log
* gpu type
* Gpu driver version
* OS version
* Terraria Version
* TEdit Version
*  DirectX version
* Any troubleshooting steps performed, any other you applications running, steps to reproduce. E.g. does it work when no other applications are running, but not when Terraria is running?

DxDiag will show much of this information.

## Original Issue
Tedit before downloading terraria on steam it worked fine, but when I download terraria via steam it doesn't open and giving this error.

Problem Event Name: CLR20r3
   Problem 01 Signature: TEdit.exe
   Problem Signature 02: 4.0.0.0
   Problem 03 Signature: b0b82721
   Problem 04 Signature: SharpDX
   Problem 05 Signature: 4.0.1.0
   Problem Signature 06: 592da585
   Problem Signature 07: 136
   Problem Signature 08: 14
   Problem Signature 09: System.InvalidOperationException
   Operating system version: 6.1.7601.2.1.0.256.1
   Location ID: 1046
   Additional Information 1: 0a9e
   Additional Information 2: 0a9e372d3b4ad19135b953a78882e789
   Additional Information 3: 0a9e
   Additional Information 4: 0a9e372d3b4ad19135b953a78882e789

What could be happening? any file that is giving problem or lack of compatibility or something?

**Comment by BinaryConstruct** [comment]
This looks like you are missing .net framework. Please see requirements on the wiki.

**Comment by BinaryConstruct** [comment]
Could you please attach
* TEdit log
* gpu type
* Gpu driver version
* OS version
* Terraria Version
* TEdit Version
*  DirectX version

DxDiag will show much of this information.
