### ISSUE TITLE
Can't find some platforms under Sprites

### ISSUE THREAD

**Issue by DrakosAmatras** [TEdit/Terraria-Map-Editor#1257]
Hi! Could you add the missing platforms under Sprites when you have the time? I can't find Stone or Lunar Pillar platforms in there.
![TEdit_Lw9kpAqjj4](https://user-images.githubusercontent.com/57094178/83328797-12073100-a286-11ea-9d54-ac11f00d09e1.png)

**Comment by BinaryConstruct** [comment]
Could you please add the info requested here? This will help analyze the files and I can get them added to the settings. Thanks!

https://github.com/TEdit/Terraria-Map-Editor/issues/1259
