### ISSUE TITLE
Corrupted World File

### ISSUE THREAD

**Issue by MuffinLover69** [TEdit/Terraria-Map-Editor#1258]
The world file gets corrupted, neither playable by normal character nor by journey. Tedit Beta 10
![Terraria_ Error 5_31_2020 5_06_20 AM](https://user-images.githubusercontent.com/66187925/83341440-f428e300-a2fc-11ea-9f10-9743015e31e7.png)

**Comment by BinaryConstruct** [comment]
Please see instructions here #1244
