### ISSUE TITLE
Missing Sprites, please help!

### ISSUE THREAD

**Issue by BinaryConstruct** [TEdit/Terraria-Map-Editor#1259]
This is a community request! There are MANY missing sprites for Journey's End. If you find one, copy it to your clipboard (no surrounding tiles) and save a schematic. Attach the schematic here with a description of the sprite. For example:

* Sprite Name: Torch
* Description: Red torch, lit, left anchor
* Size: 1x1
* Schematic: [torch.TEditSch.zip](https://github.com/TEdit/Terraria-Map-Editor/files/4706924/torch.TEditSch.zip)
* Screenshot  
![image](https://user-images.githubusercontent.com/456755/83342023-a6d25480-a2af-11ea-88fd-6c07b0ce7937.png)

**Comment by DrakosAmatras** [comment]
Hi, is there a template for how to get all the necessary 1x1 sprites for each platform type? I can pitch in, but there seems to be multiple types of stair sprites and it's throwing me off.

**Comment by DrakosAmatras** [comment]
![image](https://user-images.githubusercontent.com/57094178/83353651-40ebd880-a354-11ea-8262-9f826f241214.png)
[Stone Platforms.zip](https://github.com/TEdit/Terraria-Map-Editor/files/4707706/Stone.Platforms.zip)

I tried to build the stone platforms like the wooden ones in the pic, and they came out looking properly in the game, but TEdit (beta10) doesn't seem to render them correctly.

**Comment by BinaryConstruct** [comment]
New sprite editor resolves this. The rendering of platforms is still an issue.
![image](https://user-images.githubusercontent.com/456755/83600871-23c23000-a535-11ea-99ff-159f4c881df3.png)
