### ISSUE TITLE
Chest limit of 1,000 is outdated and worlds beyond it can't be saved

### ISSUE THREAD

**Issue by Saint-in-Chief** [TEdit/Terraria-Map-Editor#1261]
Chest limit was changed to 8,000 in latest versions of the game, and even if you ignore the warning of going over 1,000 in TEdit and save anyway, it won't do it. Also, you can't read the contents of chests once you're above 1,000.

**Comment by BinaryConstruct** [comment]
I missed this one in the validation subroutine. Will be fixed in beta 12.

**Comment by BinaryConstruct** [comment]
Fixed in https://github.com/TEdit/Terraria-Map-Editor/releases/tag/4.0.0-beta12
