### ISSUE TITLE
Pylons Are All Set To Forest On Placing

### ISSUE THREAD

**Issue by Redstone-Hamster** [TEdit/Terraria-Map-Editor#1263]
All the pylons are set to forest when placed down

**To Reproduce**
1. Go to Sprites: and search for pylon
2. Click on a pylon that is not forest
3. Place
4. It will be forest

**Expected behavior**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Version [Tedit 4 beta 11]
 - Terraria Version [e.g. 1.4.0.4]

**Comment by BinaryConstruct** [comment]
Please see #1259
