### ISSUE TITLE
Morph purify tool deleting anything on mannequins or item displays.

### ISSUE THREAD

**Issue by kirby202** [TEdit/Terraria-Map-Editor#1266]
**Describe the bug**
See Title.

**To Reproduce**
1. Go to 'Morph'
2. Click on 'Purify with maximum selection size'
3. Drag tool across display furniture
4. See issue

**Expected behavior**
I expect all items on display will disappear, probably deleted.

**Screenshots**
![image](https://user-images.githubusercontent.com/66325766/83548345-a1eceb00-a4d1-11ea-84d8-1a169cdae341.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 4.0.0-beta12
 - Terraria Version 1.4.0.4

**Comment by BinaryConstruct** [comment]
Using #533 for future work on morph tool
