### ISSUE TITLE
[Feature Request]: Keybindings for toggling Tile & Wall drawing

### ISSUE THREAD

**Issue by GeneCupstid** [TEdit/Terraria-Map-Editor#1267]
**Is your feature request related to a problem? Please describe.**

I use the pencil & brush tools a lot, and switch between combinations of tile and wall constantly while fiddling with my creations. It would be *very* helpful to have keybindings for toggling tile and wall drawing, just like there is for toggling erase.

![example](https://user-images.githubusercontent.com/56445225/83552600-a2848200-a4cf-11ea-927c-66b13fb90009.png)

**Describe the solution you'd like**

1. A key assignment for each, while the appropriate tool (picker, pencil, brush, fill) is active.
2. Add the key binding assignments for each to `<ShortCutKeys>` in config so they can be changed.
3. It probably doesn't matter what the defaults are, but here are some ideas for tile and wall respectively, as far as I know they aren't in use:
    - `I` and `L`
    - `,` and `.`  (looks like `<` and `>`
    - `-` and `=`

**Describe alternatives you've considered**

I could write an AutoHotKey script, but thought others may find this useful to have in the application.

**Additional context**

I think it would be a fairly simple change, as it only impacts the view itself.  You would likely be able to add this much quicker than I could, but if you don't have time I can give it a shot.  I have extensive C# experience, but limited in WPF.

**Comment by BinaryConstruct** [comment]
I defaulted these to Q = tile, W = wall but you may change them in the settings.xml.

**Comment by GeneCupstid** [comment]
BC you are awesome.  Great tool!!

**Comment by BinaryConstruct** [comment]
@GeneCupstid Thanks!
