### ISSUE TITLE
Need add 2 moons

### ISSUE THREAD

**Issue by bipad88** [TEdit/Terraria-Map-Editor#1271]
4.0.0-beta13
Bug Fixes: Added all the moons

No, you added not all moons. Game have 9 regular moon (in TEdit lacks pink moon) + 1 Easter egg moon (crescent like smile + 2 stars).

**Comment by bipad88** [comment]
https://terraria.gamepedia.com/Moon_phase

**Comment by BinaryConstruct** [comment]
The other moons are not available to be set in the world file. I have added the missing pink moon.
