### ISSUE TITLE
[Tool] Selection Tool improvements

### ISSUE THREAD

**Issue by mBrandao99** [TEdit/Terraria-Map-Editor#1272]
**Is your feature request related to a problem? Please describe.**
Not at all, it is more of a quality of life implementation. I currently working with biome blocks and I always need to check the distance and quantity of blocks. It would be very handy to have these informations displaying on the screen.

**Describe the solution you'd like**
I would like to see the measures X and Y when I select an area. It could be done by using the "Extra Info" box on the bottom or showing the numbers next to the selection box. Other thing that would also be cool is to list the quantity of each block inside the selection, probably would need some restrictions.

Both would pair well with some options to the selection tool, such as: 
- option to toggle on/off the area measure tooltip
- option to toggle on/off the block quantity display
- temporarily selection, when checked, the selection is removed when you let go off the mouse button

All tooltips could only be shown when you hover the selection box unless temporarily selection is enabled. 

Tried my best to provide an image of part of the concept (open to see better): 
![concept](https://user-images.githubusercontent.com/54243841/83670141-19417e00-a5a9-11ea-9d94-2e46f49549d0.png)

**Describe alternatives you've considered**
Currently I use the brush tool or coordinates to measure the distance between blocks. I think it takes more time than it should. To count them I didn't find any good alternative other than register the quantity I place down on a notepad or making square shapes.

**Additional context**
Just showing the area of the current selection box would already be very helpful, since the other features probably are more complicated to implement. I'm not much familiar with C#.

I couldn't find anything about this already implemented, if it is already there I would really like to know how to use. In that case, this issue can be archived.

**Comment by BinaryConstruct** [comment]
Good job on the feature request. I think these are all good ideas, I will add them to the 4.0 milestone.

**Comment by BinaryConstruct** [comment]
I added a new status pane for the selection size. Analysis will probably be added to an improved "world analysis" tab in the future.
![image](https://user-images.githubusercontent.com/456755/83780893-624e0c80-a653-11ea-841f-6f46a783ae34.png)
