### ISSUE TITLE
[Bug] Cursor/click issues in the new Sprite interface

### ISSUE THREAD

**Issue by DrakosAmatras** [TEdit/Terraria-Map-Editor#1275]
When scrolling through a Sprite search, the dropdown menu doesn't seem to register the cursor hover on some of the items. Can't click on them when it happens either.
![WBForEkQrG](https://user-images.githubusercontent.com/57094178/83769550-4ca30c00-a680-11ea-81dd-1c57233e94aa.gif)

**Comment by BinaryConstruct** [comment]
If I may ask, what program do you use to create your screen gif?
