### ISSUE TITLE
Paintings are missing from Sprites list 

### ISSUE THREAD

**Issue by issuesubmitter** [TEdit/Terraria-Map-Editor#1278]
**Describe the bug**
The new sprite selection UI is great, but it may be excluding some sprites from the list (e.g., paintings).

**To Reproduce**
1. In the Sprites panel, enter "paint" in the the Filter and submit it.

**Expected behavior**
The dropdown contains all painting types. For example, 3x3 paintings should be included.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: Tedit 4 beta 16
 - Terraria Version: e.g. 1.4.0.4

**Comment by issuesubmitter** [comment]
Also, I really miss having the ability to filter by (for example...) "granite", to see all of the granite themed sprites available. This doesn't seem to work anymore. It would be nice if this were possible again.

**Comment by issuesubmitter** [comment]
I'm having a similar problem with Sofas. Usually I would just type in "sofa" to get a list of them all, but that's not working now. I can't figure out if Sofas are in a category I don't know the name of (I checked the Terraria wiki and also tried "furniture") or if they're missing from the sprites for some reason.

**Comment by issuesubmitter** [comment]
Would it be possible to apply the filter to both the category dropdown and the list of all sprites? While I was very excited about this UI change at first, I'm finding that I often don't think about sprites in terms of the categories that the game organizes them in. I typically type in "granite", "nebula", "medium", "single", etc., looking for a set of items that matches the filter in _some_ way. Maybe the categories dropdown could contain all categories that contain one of those items, even if the category name itself doesn't match the filter?

**Comment by BinaryConstruct** [comment]
The new sprite placer is still pretty new. Thank you for this feedback, I'll see if it can get the filtering working more effectively. I have a few ideas for implementation.

**Comment by BinaryConstruct** [comment]
This should be fixed with beta 18. Please reopen if you are still having issues.
