### ISSUE TITLE
[Feature Request] Allow typing in the paint color dropdown for tiles and walls

### ISSUE THREAD

**Issue by issuesubmitter** [TEdit/Terraria-Map-Editor#1279]
It would be nice if I could begin typing a color name when the paint dropdowns are open in order to select a color, like I can with the Tile and Wall dropdowns, e.g., if I open the Tile dropdown and start typing "gra", it selects "Grass Block".  

By the way, thank you for all of the updates to TEdit you've been making lately! It's my favorite Terraria tool.

**Comment by BinaryConstruct** [comment]
I have added this to the 4.0 milestone.
