### ISSUE TITLE
[Feature Request] Vertical tile/wall placement lock

### ISSUE THREAD

**Issue by issuesubmitter** [TEdit/Terraria-Map-Editor#1280]
When I use the right mouse button to place tiles/walls, it locks placement along the horizontal axis, so I get a straight, flat line as I move the mouse left/right, even if I accidentally move it up/down along the way.

It would be great if this also worked vertically (depending on which direction I first move the mouse in after placing the initial block, or maybe when I hold the Shift key while using right-click).

Thank you!

**Comment by Aimeryan** [comment]
Hey, try holding left+right mouse buttons at the same time.

**Comment by BinaryConstruct** [comment]
Yes, see this for more details https://github.com/TEdit/Terraria-Map-Editor/wiki/Toolbar#pencil-tool-e
