### ISSUE TITLE
Using the Picker tool no longer works on sprites

### ISSUE THREAD

**Issue by CaneCraft** [TEdit/Terraria-Map-Editor#1281]
The picker tool no longer works on sprites, and the sprite tool hotkey no longer works properly.

Previously, I used to be able to select the picker tool **(R)**, click on the top left square of a sprite, then press the sprite tool **(T)**, allowing me to quickly and effortlessly place that sprite again. This no longer works and is currently breaking my workflow, forcing me to remain on beta10.

The sprite hotkey (T) also no longer works, but this is a separate issue and has been documented here: #1277 
https://github.com/TEdit/Terraria-Map-Editor/issues/1277

- OS: Windows 7
- Version: TEdit beta 15 & 16 and possibly earlier

**Comment by BinaryConstruct** [comment]
Tracked in #1273
