### ISSUE TITLE
Mouse zoom does not center lock the screen properly (a furthest out zoom levels)

### ISSUE THREAD

**Issue by CaneCraft** [TEdit/Terraria-Map-Editor#1282]
In previous version of TEdit (confirmed on beta10 and below), zooming the map screen using the mouse wheel would center the resulting zoom on the mouse cursor, allowing us to quickly zoom out and in on specific spots. Now the mouse wheel simply zooms the view, forcing us to pan the view afterwards, which is very cumbersome.

**Do the following in beta10 vs beta16 to see the difference:**
1. Load a map
2. Hover the mouse over a spot, then use the scroll wheel to zoom in
3. Move the mouse cursor, zoom out, move it again, zoom in, looking at the screen positioning

Note how the view focuses on the mouse cursor in beta10, but doesn't in beta16.

 - OS: Windows 7 64-bit
 - Version [TEdit 4 beta16]

**Comment by BinaryConstruct** [comment]
The current way locks the tile under the cursor instead of center screen. I can add an option to go back to the old way.

**Comment by CaneCraft** [comment]
Are you sure? From your description that sounds reversed: The _old_ way was that it zoomed centered upon the mouse cursor, while the _new_ way just zooms closer to the center of the screen.

Either way, an option would be good.

**Comment by TheFOXsK** [comment]
> The current way locks the tile under the cursor instead of center screen. I can add an option to go back to the old way.

YES PLEASE 😄

**Comment by BinaryConstruct** [comment]
+/- keys. See beta 19.

**Comment by sata700** [comment]
i would like if this hotkey switches the modes itself
because using the selection tool was a lot easier before

**Comment by sym233** [comment]
I still confuse about the zoom mechanism and always can't find the area I was focusing on after zoom with mouse wheel, even in beta 19.

**Comment by BinaryConstruct** [comment]
The tile that your mouse is hovering should stay in the same spot on the screen. For example if you hover a tile in the corner, it should stay in that corner and all the tile should zoom around it.

**Comment by sym233** [comment]
> The tile that your mouse is hovering should stay in the same spot on the screen. For example if you hover a tile in the corner, it should stay in that corner and all the tile should zoom around it.

I tried just now, it didn't work as you said.

I recorded it.
https://youtu.be/D9ahy9oe-Ng

**Comment by BinaryConstruct** [comment]
Ahh, I think the issue here is the world is too small when zoomed all the way out so the scroll bars are forcing it to the min/max areas. 

It works properly when you are zoomed in more. I'll see if I can come up with a way to fix that.

**Comment by retep998** [comment]
Perhaps don't constrain the scroll bars to the world size, but allow us to pan outside the world somewhat?

**Comment by BinaryConstruct** [comment]
That is what I was thinking, same way Photoshop does it.

**Comment by BinaryConstruct** [comment]
Tracked with #1450
