### ISSUE TITLE
Missing Sprite for 3x2 Decors that are on top of "Giant Living Trees" and when zoomed out, they are magenta

### ISSUE THREAD

**Issue by skylerspark** [TEdit/Terraria-Map-Editor#1283]
**Describe the bug**
Missing sprites for 3x3 Decors on Giant Living Trees
![Capture](https://user-images.githubusercontent.com/44554976/83936450-a7785880-a791-11ea-8e0f-e501545a645a.PNG)

What they look like zoomed out
![Capture](https://user-images.githubusercontent.com/44554976/83936459-c70f8100-a791-11ea-9d78-e97c6336d813.PNG)

**PS: Living Wood Walls are also missing a color in the zoomed out stage. They are sprited when zoomed in though**

**To Reproduce**
1. Create a world with the Secret Seed "05162020"
2. Open in tEdit and find a giant living tree (there are many in that seed)

**Expected behavior**
They should be recognized and sprited objects. I suggest coloring them the same as Living Wood Leaves in the zoomed out stage.

**Screenshots**
posted above ^

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro (latest patch as of 6/6/2020)
 - Version: TEdit 1.4 Beta16
 - Terraria Version: 1.4.0.5

**Additional context**
none

**Comment by BinaryConstruct** [comment]
This issue has really good detail. Thank you! This has been added to the 4.0 milestone.
