### ISSUE TITLE
Problem with launch Tedit 4.0 Beta 16

### ISSUE THREAD

**Issue by RubberFruits** [TEdit/Terraria-Map-Editor#1286]
Hi guys, I have this problem from launche Tedit 4.0 Beta 16

`06-06-2020 19:54:43: Starting TEdit 4.0.0.0 

 06-06-2020 19:54:43: OS: Microsoft Windows NT 6.2.9200.0 

 06-06-2020 19:54:43: Terraria v1.4.0.5 

 06-06-2020 19:54:43: Terraria Data Path: D:\Games\Steam\steamapps\common\Terraria\Content 

 06-06-2020 19:54:43: Error - Не удалось загрузить тип "PROCESS_DPI_AWARENESS" из сборки 
 "WindowsBase, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35".

   в System.Windows.Media.Visual.AddVisualChild(Visual child)
   в System.Windows.Media.VisualCollection.ConnectChild(Int32 index, Visual value)
   в System.Windows.Media.VisualCollection.Add(Visual visual)
   в System.Windows.Controls.UIElementCollection.AddInternal(UIElement element)
   в MS.Internal.Xaml.Runtime.ClrObjectRuntime.Add(Object collection, XamlType collectionType, Object value, XamlType valueXamlType) 
06-06-2020 19:54:43: Error - Добавление значения в коллекцию типа "System.Windows.Controls.UIElementCollection" вызвало исключение.
   в System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   в System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   в System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   в System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   в System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   в System.Windows.Application.DoStartup()
   в System.Windows.Application.<.ctor>b__1_0(Object unused)
   в System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   в System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   в System.Windows.Threading.DispatcherOperation.InvokeImpl()
   в MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   в System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   в System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   в System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   в MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   в System.Windows.Threading.DispatcherOperation.Invoke()
   в System.Windows.Threading.Dispatcher.ProcessQueue()
   в System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   в MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   в MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   в System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   в System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   в System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   в MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   в MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   в System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   в System.Windows.Application.RunDispatcher(Object ignore)
   в System.Windows.Application.RunInternal(Window window)
   в TEdit.App.Main() `

**Comment by BinaryConstruct** [comment]
This looks like a .net framework or windows OS issue. Please see https://github.com/TEdit/Terraria-Map-Editor/wiki/Install-Requirements

**Comment by RubberFruits** [comment]
Thanks, I'l try it)

**Comment by RubberFruits** [comment]
It's dont't help me. I install latest version .net, upgrade graphics drivers
