### ISSUE TITLE
Sprites are more difficult to find in the experimental sprite placer

### ISSUE THREAD

**Issue by tracyfu** [TEdit/Terraria-Map-Editor#1287]
I’m having trouble with the implementation of this new feature.

**1. It’s harder to find the sprite you’re looking for by its name.**
When you entered ‘vase’ in the filter in the previous version of TEdit, you would get these results from matching display names.

![image](https://user-images.githubusercontent.com/270668/83954377-83526100-a7fd-11ea-8af3-99d98adb9607.png)

Now, in order to find the Pink Vase, you have to know that it falls under the Bottle category, and to find dungeon vases, you have to search one of the several statue categories. It’s not completely clear what items fall under which sprite categories without searching the wiki for the tile ID, and display names no longer appear.

![image](https://user-images.githubusercontent.com/270668/83954438-1be8e100-a7fe-11ea-8022-cf2deadbb55c.png)

Similarly, you can’t search for ‘cup’ despite the wiki having a weird separate designation for Cups [Internal Tile ID: 13 (4-7)]. The only result that gets returned are Golf Cups. These issues have more to do with the tile taxonomy than the feature, but I would like to be able to search by name again, and additionally, by the categories present on the wiki if possible.

**2. Rocket types appear to be missing.**
This is the only sprite that I’ve come across that is missing. The green, blue, and yellow rockets on the wiki do not appear to have their own tile ID [green: 216 (2)].

Old:
![image](https://user-images.githubusercontent.com/270668/83954568-2eafe580-a7ff-11ea-979f-98ff478b63dd.png)

New:
![image](https://user-images.githubusercontent.com/270668/83954551-0e802680-a7ff-11ea-9a24-42d3e07aa171.png)

**3. The tile type dropdown is overwhelming.**
While the new style grid is a huge improvement, the type dropdown makes it hard to narrow down what you’re looking for when you can only see about nine items at a time. I’ve had to scroll up and down through the list several times to guess which tile type I’m looking for. I don’t know what the solution is; nested drawer, tiled dropdown, sorting by something different (e.g. so all the plants are together)?

Overall, I like the direction of the feature and its attempt to improve the UX. I hope these comments provide constructive feedback.

**Comment by BinaryConstruct** [comment]
There are a few changes in beta 17, but the search improvements are still in development.

**Comment by Tamamo89** [comment]
I've noticed that several of the sprites are offset incorrectly as well. Makes choosing the right one difficult as well.
