### ISSUE TITLE
TEdit corrupts all files I open with it

### ISSUE THREAD

**Issue by Fleshwarper** [TEdit/Terraria-Map-Editor#1289]
Playing the new 1.4 update Journey's End, and about two weeks ago all the files I opened with TEdit showed up with red font and were unloadable in the game menu. I have made several test worlds and opened them in TEdit. Once I save the file in TEdit it somehow becomes corrupt. It happens with all world files I load and save. If I am doing something wrong please let me know! I love TEdit!

**Comment by RP5555** [comment]
Yeah, on the TEdit beta13 I did many changes to my world, then on the beta16 I worked for like 20 hours on my world, I clicked save everytime but didn't TEdit don't save as WLD, but as TEdit file, so I change it myself and I can't load it on Terraria, so I try to open it as TEdit/WLD on TEdit to save it again, and I only get half of my world.

I want my hours back, do something devs, or don't post your beta version, specially if you ask for get the new update when you start TEdit.

Thanks.

**Comment by BinaryConstruct** [comment]
TEdit files are only compatible with 1.4.0.4. Please be sure you have the latest update for Terraria. Terraria version 1.4.0.1 to1.4.0.4 introduced some breaking changes to the world file format.

**Comment by RP5555** [comment]
TEdit Version : Beta16
Terraria Version : 1.4.0.5
OS Version : Windows 10.0.18363

What issue : Loading a 11.3Mo .TEDIT file cut the save in half. 
If I "save as" the .TEDIT as .WLD : no error message, no bak file, but got a .wld file of 5,6Mo.
I tried to read it on Terraria, it says : "No Bak file" and it doesn't work.

**Comment by BinaryConstruct** [comment]
Are you trying to load a corrupted file in TEdit and recover it?

**Comment by RP5555** [comment]
Well, when I worked on the save during many hours I just pressed "Save" so it saved it as TEDIT file, few days later, I started Tedit, load the TEDIT file, no error message but only get half of the world. I tried to load the back up file I get earlier in the day, but still it only load half of the world.

**Comment by BinaryConstruct** [comment]
TEdit only saves as .wld normally. Only the rolling backups and save as will save a .TEdit file.  I would suggest finding your most recent working backup, then taking the content with copy paste from the world that is broken.
