### ISSUE TITLE
My TExTuReS ArE N0T Sh0WiNg (I very not like it :D )

### ISSUE THREAD

**Issue by TheFOXsK** [TEdit/Terraria-Map-Editor#1292]
**_I dont even know what should I say, my textures are not showing no matter what I do ( I think they are scared of me or something).  PLeAse hElP mE.   #🍜 is da best.

WINDOWS 10
64-bit
Everything should be fine except my IQ.

For Other InfOrmAtiOnS pLeAse coNtaCt mE._**

**Comment by Malteusa** [comment]
Do you mean the in-game textures or the colors ? 
If the in-game textures are not appearing then, you can go to 'display' menu on the top and check if "show textures" is enabled.

At the start of a fresh Tedit install, it asks for the location Terraria's folder you need to put the location of your Terraria folder for textures to appear.

**Comment by TheFOXsK** [comment]
Yeah, the option is enabled, I tried to reset it too, and I have done thing
with installation too. Still nothing...

**Comment by Tamamo89** [comment]
This might be related might not be.
I don't get (all) the textures to appear either. Mostly the newer ones. Such as large bamboo and smooth sandstone. However the walls do appear. As do the objects.

**Comment by TheFOXsK** [comment]
I might know what's the problem, I just installed ver. 17, but it haven't
showed me the window, where I am choosing the place for saves.

**Comment by BinaryConstruct** [comment]
Check here: https://github.com/TEdit/Terraria-Map-Editor/wiki/Install-Requirements#for-sprite-viewing

**Comment by TheFOXsK** [comment]
Thanx, I will try.

**Comment by TheFOXsK** [comment]
Guys, I solved it, only think that was needed was to move my data folder
into program files like it was said in the link, that one of u sent me.
Also guy says there, that none steam versions are not supported, but It
doesn't really matter, because everything works same like with steam
version.

  So thanx guys, if anybody will have same problem just sent them that
link, it will probably solve the problem.
