### ISSUE TITLE
World limit and random crash

### ISSUE THREAD

**Issue by Wawewow** [TEdit/Terraria-Map-Editor#1294]
![1](https://user-images.githubusercontent.com/66699508/84196540-077c4100-aaa9-11ea-8206-23f062075726.png)
ı am having those issues plese help

**Comment by BinaryConstruct** [comment]
I'm not sure how you got a world version 230. Are you using mods?

**Comment by Wawewow** [comment]
> I'm not sure how you got a world version 230. Are you using mods?

no

**Comment by BinaryConstruct** [comment]
Can you attach the world files that are not working? Also please indicate what version of Terraria you are using.
