### ISSUE TITLE
Is Russian localization needed?

### ISSUE THREAD

**Issue by nikitamatrosoff** [TEdit/Terraria-Map-Editor#1295]
I can translate the whole program to Russian and probably find people to translate it into other languages. Is it needed?

**Comment by BinaryConstruct** [comment]
> Got it.
> You can fetch items and tiles names from Terraria localization files automatically.

Good idea!

**Comment by sata700** [comment]
I might do Arabic translation if you want

**Comment by BinaryConstruct** [comment]
Sure! I'm about 3/4 of the way extracting all the english text from the UI. Once that is done I'll create the base Russian and Arabic language files to be translated.

**Comment by BinaryConstruct** [comment]
@nikitamatrosoff @sata700 I have added the language files for

* Russian ru-RU https://github.com/TEdit/Terraria-Map-Editor/blob/master/src/TEdit/Properties/Language.ru-RU.resx
* Arabic ar-BH (modern standard) https://github.com/TEdit/Terraria-Map-Editor/blob/master/src/TEdit/Properties/Language.ar-BH.resx

You can edit the xml directly by change the data in the `<value>` tags, or use [Visual Studio Community Edition](https://visualstudio.microsoft.com/vs/community/) for a spreadsheet format editor.

Thank you for offering to contribute!

![image](https://user-images.githubusercontent.com/456755/86406649-1f467f80-bc79-11ea-813c-3917f238924e.png)

**Comment by sata700** [comment]
imma check it now

**Comment by sata700** [comment]
well I made a file and placed the code but how to open it as a sheet?

**Comment by BinaryConstruct** [comment]
To get the view from my screenshot you have to install visual studio from the link above. It isn't required, but might make things easier.

**Comment by BinaryConstruct** [comment]
Also, you can submit a pull request to get the changes or paste the updated file here and I can make the changes.

**Comment by sata700** [comment]
> To get the view from my screenshot you have to install visual studio from the link above. It isn't required, but might make things easier.

ive done that but still dont know how to do it

**Comment by sata700** [comment]
just found out that i can open it in excel so I'm gonna start

**Comment by sata700** [comment]
just found out that i don't know what tile entities do and how it works

**Comment by BinaryConstruct** [comment]
Good to know about Excel. Tile entities are things that hold items or have interaction other than chests. For example, hat rack, mannequin, teleport pylons, weapon racks, dinner plates.

**Comment by BinaryConstruct** [comment]
Entity: game developer term for anything with code that shows up in game. See https://en.wikipedia.org/wiki/Entity_component_system

**Comment by BinaryConstruct** [comment]
I also found this https://github.com/salarcode/AutoResxTranslator but some of the translations failed or were strange. However, it might give a starting point if you want to try it.

**Comment by nikitamatrosoff** [comment]
I created a PR #1353. 
My Visual Studio can't open your project («The project file cannot be loaded.») so I wasn't able to test the translation. If you can compile a new version and send it to me for a test, it will be great!

**Comment by sata700** [comment]
yeah i couldnt clone it too so i made a new xml file and placed the code

**Comment by nikitamatrosoff** [comment]
No, @sata700, I definitely could clone the repository and open .resx file. There is other problem: VS couldn't open the whole project, sln or csproj file.

**Comment by BinaryConstruct** [comment]
@nikitamatrosoff Somehow I missed this entire comment! Anyway, I created a new project and solution with _just_ the language files here: https://github.com/TEdit/Terraria-Map-Editor/tree/master/src/LanguageEditor

You will still need to clone the whole project, but it should only have the language files in visual studio..

**Comment by nikitamatrosoff** [comment]
Okay. I need to copy my translation file to that folder or you can do it yourself?

**Comment by BinaryConstruct** [comment]
You can fork the project and submit a Github pull request, or if you upload the file to this attachment, I can add it to the project.

**Comment by BinaryConstruct** [comment]
Once you clone the project, open the LanguageEditor.sln in visual studio. It will link the the correct files in the project.

**Comment by nikitamatrosoff** [comment]
The file is located here in the repo: src/TEdit/Properties/Language.ru-RU.resx

**Comment by BinaryConstruct** [comment]
Closing as this seems to be successful so far.
