### ISSUE TITLE
Bestiary Tally Import Issue

### ISSUE THREAD

**Issue by Requias** [TEdit/Terraria-Map-Editor#1296]
**Describe the bug**
I'm trying to import the specific bestiary content from one world into another world, but using the import feature doesn't change anything, and just shows the current world's tally

**To Reproduce**
Open a world in the program
Click on the Tally panel
Click the Import option
Choose another world and double click

**Expected behavior**
The tally would show the selected world's kill counts and the bestiary would update ingame to the selected world's bestiary

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version Tedit 4 beta 17
 - Terraria Version 1.4.0.5

**Comment by BinaryConstruct** [comment]
I expect you did this, but did the world you open save successfully after importing the bestiary or did it get replaced with the backup file?

**Comment by Requias** [comment]
Yea, I saved it as a backup. I see the problem.

**Comment by BinaryConstruct** [comment]
Is this issue still open?
