### ISSUE TITLE
I changed the name of my world through T-edit and it deleted minimap data by changing the file to .bad

### ISSUE THREAD

**Issue by RNFADED** [TEdit/Terraria-Map-Editor#1297]
If you rename a world in T edit, it replaces the map data. Is there any way to get the minimap data back?

**Comment by BinaryConstruct** [comment]
Currently, no. The minimap format is completely separate from the map itself, and TEdit does not have format for loading it. I might reopen this later, but right now there isn't any solution other than not renaming the world.
