### ISSUE TITLE
Brush/Pencil Functions don't work after using copy+paste

### ISSUE THREAD

**Issue by lNKU** [TEdit/Terraria-Map-Editor#1298]
Describe the bug:
After using the Selection Tool, copying the selected region, and then pasting the selected area on the map - the Brush and Pencil tools refuse to work requiring the program to be closed and reopened. I have checked to make sure the painting options are enabled in the tile and background wall selection areas as well as made sure that the eraser isn't accidentally activated either.

To Reproduce:
1. Open any world in the program
2. Click on Selection Tool (with the blue square icon)
3. Select desired area
4. Copy selected area anywhere on the map
5. Paste selected area anywhere on the map
6. Attempt to paint with Brush or Pencil tools afterwards.

Expected behavior:
After using the copy+paste functions, Brush and Pencil functions should paint the tiles selected with the picker tool or selected via the dropdown list. 

Desktop (please complete the following information):

   * OS: Windows 10
   * Version Tedit 4 beta 17
   * Terraria Version 1.4.0.5

**Comment by BinaryConstruct** [comment]
Be sure to clear your selection with escape or ctrl+d
