### ISSUE TITLE
Oasis Plants are framed incorrectly

### ISSUE THREAD

**Issue by Tamamo89** [TEdit/Terraria-Map-Editor#1299]
**Describe the bug**
The oasis plants are incorrectly framed. (They're 1x1)

**To Reproduce**
1. Go to 'Sprite'
2. Filter 'Oasis Plants'
3. Select 'Oasis Plants'
4. See the Error.

**Expected behavior**
These should be 3x2 and 2x2.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version Tedit 4 beta 17
 - Terraria Version 1.4.0.5

**Comment by BinaryConstruct** [comment]
There is a known issue where the three deco tiles have multiple sizes in the same sprite sheet. I will have these updates in for the next beta.
