### ISSUE TITLE
dont run tedit

### ISSUE THREAD

**Issue by HaniSahar** [TEdit/Terraria-Map-Editor#1301]
06-12-2020 12:30:30: Starting TEdit 4.0.0.0 
06-12-2020 12:30:30: OS: Microsoft Windows NT 6.1.7601 Service Pack 1 
06-12-2020 12:30:30: OS Name: Microsoft Windows 7 Professional Service Pack 1 
06-12-2020 12:30:30: .NET Framework Version: 4.8 or later 
06-12-2020 12:30:31: Terraria v1.4.0.5 
06-12-2020 12:30:31: Terraria Data Path: E:\Steam\steamapps\common\Terraria\Content 
06-12-2020 12:30:31: Creating Undo cache: C:\Users\HaniSahar.555\AppData\Roaming\TEdit\undo_326013530 
06-12-2020 12:30:32: Failed to load texture: Images\NPC_17 
06-12-2020 12:30:32: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
06-12-2020 12:30:32: Failed to load texture: Images\NPC_18 
06-12-2020 12:30:32: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
06-12-2020 12:30:32: Failed to load texture: Images\NPC_19 
06-12-2020 12:30:32: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
06-12-2020 12:30:32: Failed to load texture: Images\NPC_20 
06-12-2020 12:30:32: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
06-12-2020 12:30:32: Failed to load texture: Images\NPC_22 
06-12-2020 12:30:32: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
06-12-2020 12:30:32: Failed to load texture: Images\NPC_37 
06-12-2020 12:30:32: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
06-12-2020 12:30:32: Failed to load texture: Images\NPC_38 
06-12-2020 12:30:32: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
06-12-2020 12:30:32: Failed to load texture: Images\NPC_54 
06-12-2020 12:30:32: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
06-12-2020 12:30:32: Failed to load texture: Images\NPC_105 
06-12-2020 12:30:32: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
06-12-2020 12:30:32: Failed to load texture: Images\NPC_106 
06-12-2020 12:30:32: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
06-12-2020 12:30:32: Failed to load texture: Images\NPC_107 
06-12-2020 12:30:32: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
06-12-2020 12:30:32: Failed to load texture: Images\NPC_108 
06-12-2020 12:30:32: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
06-12-2020 12:30:32: Failed to load texture: Images\NPC_123 
06-12-2020 12:30:32: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
06-12-2020 12:30:32: Failed to load texture: Images\NPC_124 
06-12-2020 12:30:32: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
06-12-2020 12:30:32: Failed to load texture: Images\NPC_142 
06-12-2020 12:30:32: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
06-12-2020 12:30:32: Failed to load texture: Images\NPC_160 
06-12-2020 12:30:32: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
06-12-2020 12:30:32: Failed to load texture: Images\NPC_178 
06-12-2020 12:30:32: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
06-12-2020 12:30:32: Failed to load texture: Images\NPC_207 
06-12-2020 12:30:32: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
06-12-2020 12:30:32: Failed to load texture: Images\NPC_208 
06-12-2020 12:30:32: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
06-12-2020 12:30:32: Failed to load texture: Images\NPC_209 
06-12-2020 12:30:32: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
06-12-2020 12:30:32: Failed to load texture: Images\NPC_227 
06-12-2020 12:30:32: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
06-12-2020 12:30:32: Failed to load texture: Images\NPC_228 
06-12-2020 12:30:32: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
06-12-2020 12:30:32: Failed to load texture: Images\NPC_229 
06-12-2020 12:30:32: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
06-12-2020 12:30:32: Failed to load texture: Images\NPC_353 
06-12-2020 12:30:32: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
06-12-2020 12:30:32: Failed to load texture: Images\NPC_354 
06-12-2020 12:30:32: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
06-12-2020 12:30:32: Failed to load texture: Images\NPC_357 
06-12-2020 12:30:32: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
06-12-2020 12:30:32: Failed to load texture: Images\NPC_368 
06-12-2020 12:30:32: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
06-12-2020 12:30:32: Failed to load texture: Images\NPC_369 
06-12-2020 12:30:32: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
06-12-2020 12:30:32: Failed to load texture: Images\NPC_376 
06-12-2020 12:30:32: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
06-12-2020 12:30:32: Failed to load texture: Images\NPC_377 
06-12-2020 12:30:32: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
06-12-2020 12:30:32: Failed to load texture: Images\NPC_441 
06-12-2020 12:30:32: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
06-12-2020 12:30:32: Failed to load texture: Images\NPC_446 
06-12-2020 12:30:32: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
06-12-2020 12:30:32: Failed to load texture: Images\NPC_448 
06-12-2020 12:30:32: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
06-12-2020 12:30:32: Failed to load texture: Images\NPC_453 
06-12-2020 12:30:32: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
06-12-2020 12:30:32: Failed to load texture: Images\NPC_484 
06-12-2020 12:30:32: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
06-12-2020 12:30:32: Failed to load texture: Images\NPC_485 
06-12-2020 12:30:32: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
06-12-2020 12:30:32: Failed to load texture: Images\NPC_486 
06-12-2020 12:30:32: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
06-12-2020 12:30:32: Failed to load texture: Images\NPC_487 
06-12-2020 12:30:32: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
06-12-2020 12:30:32: Failed to load texture: Images\NPC_548 
06-12-2020 12:30:32: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
06-12-2020 12:30:32: Failed to load texture: Images\NPC_550 
06-12-2020 12:30:32: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
06-12-2020 12:30:32: Failed to load texture: Images\NPC_579 
06-12-2020 12:30:32: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
06-12-2020 12:30:32: Failed to load texture: Images\NPC_588 
06-12-2020 12:30:32: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
06-12-2020 12:30:32: Failed to load texture: Images\NPC_606 
06-12-2020 12:30:32: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
06-12-2020 12:30:32: Failed to load texture: Images\NPC_633 
06-12-2020 12:30:32: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
06-12-2020 12:30:32: Failed to load texture: Images\NPC_637 
06-12-2020 12:30:32: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
06-12-2020 12:30:32: Failed to load texture: Images\NPC_638 
06-12-2020 12:30:32: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
06-12-2020 12:30:32: Failed to load texture: Images\NPC_656 
06-12-2020 12:30:32: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
06-12-2020 12:30:32: Failed to load texture: Images\Tiles_3 
06-12-2020 12:30:32: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
06-12-2020 12:30:32: Failed to load texture: Images\Tiles_4 
06-12-2020 12:30:32: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
06-12-2020 12:30:32: Failed to load texture: Images\Tiles_5 
06-12-2020 12:30:32: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
06-12-2020 12:30:32: Failed to load texture: Images\Tiles_10 
06-12-2020 12:30:32: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
06-12-2020 12:30:32: Failed to load texture: Images\Tiles_11 
06-12-2020 12:30:32: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
06-12-2020 12:30:32: Failed to load texture: Images\Tiles_12 
06-12-2020 12:30:32: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
06-12-2020 12:30:32: Failed to load texture: Images\Tiles_13 
06-12-2020 12:30:32: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
06-12-2020 12:30:32: Failed to load texture: Images\Tiles_14 
06-12-2020 12:30:32: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
06-12-2020 12:30:32: Failed to load texture: Images\Tiles_15 
06-12-2020 12:30:32: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
06-12-2020 12:30:32: Failed to load texture: Images\Tiles_16 
06-12-2020 12:30:32: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
06-12-2020 12:30:32: Failed to load texture: Images\Tiles_17 
06-12-2020 12:30:32: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
06-12-2020 12:30:32: Failed to load texture: Images\Tiles_18 
06-12-2020 12:30:32: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
06-12-2020 12:30:32: Failed to load texture: Images\Tiles_19 
06-12-2020 12:30:32: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
06-12-2020 12:30:32: Failed to load texture: Images\Tiles_20 
06-12-2020 12:30:32: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
06-12-2020 12:30:32: Failed to load texture: Images\Tiles_21 
06-12-2020 12:30:32: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
06-12-2020 12:30:32: Failed to load texture: Images\Tiles_24 
06-12-2020 12:30:32: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
06-12-2020 12:30:32: Failed to load texture: Images\Tiles_26 
06-12-2020 12:30:32: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
06-12-2020 12:30:32: Failed to load texture: Images\Tiles_27 
06-12-2020 12:30:32: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
06-12-2020 12:30:32: Failed to load texture: Images\Tiles_28 
06-12-2020 12:30:32: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
06-12-2020 12:30:32: Failed to load texture: Images\Tiles_29 
06-12-2020 12:30:32: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
06-12-2020 12:30:32: Failed to load texture: Images\Tiles_31 
06-12-2020 12:30:32: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
06-12-2020 12:30:32: Failed to load texture: Images\Tiles_33 
06-12-2020 12:30:32: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
06-12-2020 12:30:32: Failed to load texture: Images\Tiles_34 
06-12-2020 12:30:32: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
06-12-2020 12:30:32: Failed to load texture: Images\Tiles_35 
06-12-2020 12:30:32: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
06-12-2020 12:30:32: Failed to load texture: Images\Tiles_36 
06-12-2020 12:30:32: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
06-12-2020 12:30:32: Failed to load texture: Images\Tiles_42 
06-12-2020 12:30:32: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
06-12-2020 12:30:32: Failed to load texture: Images\Tiles_49 
06-12-2020 12:30:32: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
06-12-2020 12:30:32: Failed to load texture: Images\Tiles_50 
06-12-2020 12:30:32: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
06-12-2020 12:30:32: Failed to load texture: Images\Tiles_55 
06-12-2020 12:30:32: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
06-12-2020 12:30:32: Failed to load texture: Images\Tiles_61 
06-12-2020 12:30:32: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
06-12-2020 12:30:32: Failed to load texture: Images\Tiles_71

**Comment by BinaryConstruct** [comment]
Please see #751 and https://github.com/TEdit/Terraria-Map-Editor/wiki/Install-Requirements

Windows 7.1 is not officially supported.
