### ISSUE TITLE
converting worlds to 1.3.5.5

### ISSUE THREAD

**Issue by Tragez** [TEdit/Terraria-Map-Editor#1302]
**Is your feature request related to a problem? Please describe.**
i just wanted to build a house out of mushroom ( as the biome was taken over by crimson and hallowed) in tmodloader, it plays in 1.3.5.5, i used the newest version of the tedit, but it force-converted the world into the 1.4 without the option to reverse it, at least i didnt find that option

**Describe the solution you'd like**
it would be very satisfying to have a tool that allows a world to switch between 1.3.5 and 1.4, as tmodloader doesnt accept 1.4 worlds, even if there is no stuff that was added with 1.4.

**Describe alternatives you've considered**
to prevent that from hapen over and over again, it might be enough to ask the user, if he wants to convert the world from 1.3.x.x to 1.4, even though i wouldnt get my post-D.O.G.
 world back with this option

**Additional context**
i am also attaching the world file, in case it is any use to people here in returning it to 1.3

[DONT_FAVORIZE.zip](https://github.com/TEdit/Terraria-Map-Editor/files/4770925/DONT_FAVORIZE.zip)

**Comment by Tazawaki** [comment]
wow no luck man

**Comment by BinaryConstruct** [comment]
The world formats and tiles are very different, I don't think it would be possible to roll back a file from 1.4 to 1.3.x. However, you can use the 3.X version of TEdit to modify 1.3.X worlds. 

Additionally, TEdit does not support modded world files as they have custom sections that do not load properly. 

Finally, I will add a prompt if the version is not the current one when loading.

**Comment by Tragez** [comment]
surprisingly, it loads the worlds, but just leaves the modded parts unloaded, thanks for that quick response, but the only reason why i downloaded another verison is actually because the 1.3.x version couldnt find the terraria data, even though i lead it to the correct folder

**Comment by BinaryConstruct** [comment]
This prompt is in beta 19.
