### ISSUE TITLE
Sprite function don't work

### ISSUE THREAD

**Issue by Tazawaki** [TEdit/Terraria-Map-Editor#1303]
I cannot use the "Sprite" function. I searched, but i didn't find any way to use it. In a previous version (for the 1.3.0.5), the function were working perfectly fine!
I wanted to spawn a Plantera Bulb in an arena, but it seems I can't...

I thought i could just search a sprite, then place it down like before, but i can't.

 - OS: Windows 10
 - Version Tedit 4.0.0 Beta 18
 - Terraria Version : 1.4.0.4

**Comment by Tazawaki** [comment]
If anybody know how to help me, please do it!
My world is one of the one that doesn't generate Plantera's bulb, so I really need this!

**Comment by BinaryConstruct** [comment]
![image](https://user-images.githubusercontent.com/456755/84515757-82ed1680-ac92-11ea-81a0-81403a7954ab.png)

**Comment by Tazawaki** [comment]
> I updated the wiki for you: https://github.com/TEdit/Terraria-Map-Editor/wiki/Toolbar#sprite-placer-tool-t
THANK YOU SO, SO MUCH!
Also, I love the editor! ^^
