### ISSUE TITLE
Sprite function still don't work

### ISSUE THREAD

**Issue by Tazawaki** [TEdit/Terraria-Map-Editor#1304]
I KNOW i already submitted something about that here, but even with the answer, it still don't work!
For example, when i write, "bulb" (for the Plantera bulb), and then click on Filter, nothing appears!
Here is an image to show it : 
![image](https://user-images.githubusercontent.com/66832906/84517225-47247200-accf-11ea-8048-13246d6ff16d.png)
@BinaryConstruct already answered to my previous post, and added the Sprite function to the wiki, but still, nothing work.

**Comment by BinaryConstruct** [comment]
Check your log to make sure Terraria data was loaded. If it cannot find the Terraria install folder try the tips on the wiki here: https://github.com/TEdit/Terraria-Map-Editor/wiki/Install-Requirements#for-sprite-viewing

**Comment by BinaryConstruct** [comment]
Log is in the help menu.

**Comment by Tazawaki** [comment]
I already looked everywere, and yet, nothing work...

**Comment by Tazawaki** [comment]
But, well, if there is nothing i can do, guess i'll just give myself the loot, and change the world to make it as if i beated it...
