### ISSUE TITLE
Sprite generator adaptation

### ISSUE THREAD

**Issue by Tazawaki** [TEdit/Terraria-Map-Editor#1306]
My world doesn't generate Plantera bulbs.
I tried to use this software to add one, but non-Steam games don't support sprites additions!

Is it possible to put back the old sprite generator, or at least adapt the current one to non-Steam games? It would be very nice, 'cause i'm actually stuck rn.

**Comment by BinaryConstruct** [comment]
You have to edit the <AltC> tag in the settings.xml file to point to your terraria content folder.

**Comment by Tazawaki** [comment]
oh
