### ISSUE TITLE
Help me please!

### ISSUE THREAD

**Issue by Tazawaki** [TEdit/Terraria-Map-Editor#1307]
My game doesn't generate Plantera's bulbs, even if i do everything i could.
As I am a dumb*ss and i am too dumb to make TEdit add sprites, can somebody help me?

Can anyone take the world below and place 10 bulbs down in the big arena in the jungle? It would be very nice, and if nobody do it, i'm gonna stay stuck between the mech bosses and Plantera.

Thanks in advance!
[the_ultimate_return.zip](https://github.com/TEdit/Terraria-Map-Editor/files/4773132/the_ultimate_return.zip)

**Comment by Tazawaki** [comment]
Please don't question my world-naming skills ;)

**Comment by BinaryConstruct** [comment]
The forums would probably be a better place to ask for things like this. However, I have attached a schematic with 5 plantera bulbs.
[plantbulbx5.zip](https://github.com/TEdit/Terraria-Map-Editor/files/4773883/plantbulbx5.zip)

**Comment by Tazawaki** [comment]
OMG THANK YOU SOOOO MUCH
