### ISSUE TITLE
TEdit stuck on validating world.

### ISSUE THREAD

**Issue by agbgt** [TEdit/Terraria-Map-Editor#1308]
When I load my world into TEdit, the text on the bottom right gets stuck on "Validating world". It allows me to make edits to the world and everything but I can't save it. My terraria game is on another computer but I put the world file on this one, is that the issue?

**Comment by BinaryConstruct** [comment]
Would you attach a zipped world file please?

**Comment by agbgt** [comment]
[The_Dimension_of_Divinity.wld.zip](https://github.com/TEdit/Terraria-Map-Editor/files/4777024/The_Dimension_of_Divinity.wld.zip)
Sure thing, here it is.

**Comment by BinaryConstruct** [comment]
Work is in progress in this. The fix is a bit larger than I expected, may need another day.

**Comment by BinaryConstruct** [comment]
Please try beta 20: https://github.com/TEdit/Terraria-Map-Editor/releases/tag/4.0.0-beta20
