### ISSUE TITLE
Issues with new chest.

### ISSUE THREAD

**Issue by Tamamo89** [TEdit/Terraria-Map-Editor#1310]
**Describe the bug**
The new chest added in 1.4 have issues with the chest plugins as well as special tiles options.

**To Reproduce**
Issue 1:
1. Find a chest in the underground desert 
2. Right Click it.
3. Error: The chest type is not listed.

Issue 2:
1. Go to 'plugins'
2. Click on 'find chest with...'
3. Search for the from issue 1.
4. Error: No results.

**Expected behavior**
Issue 1: Chest type should be listed. (Note none of the new chest from 1.4 are listed as chest types types)
Issue 2: Should search contents of chest added in 1.4 and return results.

**Desktop**
 - OS: [e.g. Windows 10]
 - Version [Tedit 4 beta 19]
 - Terraria Version [e.g. 1.4.5]

**Comment by BinaryConstruct** [comment]
![image](https://user-images.githubusercontent.com/456755/84689019-ee8aea00-af05-11ea-838e-a40304fcef99.png)
 Should be fixed now.
