### ISSUE TITLE
Certain tiles not appearing, but worse is that they cannot be copied

### ISSUE THREAD

**Issue by Kitaragna** [TEdit/Terraria-Map-Editor#1311]
**Describe the bug**
Objects not recognized by TEdit, such as Bamboo and Sandstone furniture, are not visible and cannot be copied into the clipboard

**To Reproduce**
1. Place a Sandstone Dresser in the world ingame
2. Load the world in TEdit
3. Copy the area where the Dresser is in
4. Nothing gets copied. Cannot modify the area further as well

**Expected behavior**
Even without the visuals, the blocks should still be saved as a schematic

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version Tedit 4 beta 19
 - Terraria Version e.g. 1.4.0.5

**Comment by BinaryConstruct** [comment]
Thank you for the detail.

**Comment by BinaryConstruct** [comment]
Work is in progress in this. The fix is a bit larger than I expected, may need another day. Same issue as #1308
