### ISSUE TITLE
Biome Morph tool "Purify" does not work on Hallowed Golf Grass

### ISSUE THREAD

**Issue by sofakinng** [TEdit/Terraria-Map-Editor#1312]
## Before Submitting

* If you are having issues loading a world, please attach it to the current version world thread (see pinned issues).
* If you get an unhandled exception or crash, please _**check your log before posting**_.

### What were you doing when the issue occured?
Using the Biome Morph tool to try cleaning up an area

### Steps to reproduce the issue?
1) Set biome morph tool to purify
2) Use brush on area with "Hallowed Golf Grass"
3) Notice that no change occurs

### What version of Terraria are you using?
1.4.0.5

### Post relevant contents of log or attach log file _**(very important)**_:
_Copy paste using code [block tags](https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks) into the issue as a comment_
[TEditLog.txt](https://github.com/TEdit/Terraria-Map-Editor/files/4778830/TEditLog.txt)

### Attach world file

[Terrified_Alcove_of_Glass.zip](https://github.com/TEdit/Terraria-Map-Editor/files/4778817/Terrified_Alcove_of_Glass.zip)

**Comment by BinaryConstruct** [comment]
This will be addressed with #533
