### ISSUE TITLE
Edit Bestiary Percentages and Specific Finds/Stars

### ISSUE THREAD

**Issue by agbgt** [TEdit/Terraria-Map-Editor#1313]
It might be very useful to edit the bestiary of a certain world.

- [x] Ablility to detail edit it such as adding one specific monster to it. 
- [x] Also adding more 'stars' to already discovered monsters. A lot of monsters are close to impossible to find after hardmode and this would fix that issue for people who wanna complete it in their main world. 
- [x] fully Populate bestiary

**Comment by BinaryConstruct** [comment]
I updated this with some other feature requests. All bestiary features will be tracked here.

**Comment by RussDev7** [comment]
Commit https://github.com/TEdit/Terraria-Map-Editor/pull/1625 completes these tasks.
