### ISSUE TITLE
Wall ID 244 (Natural Living Wood Wall) has no name.

### ISSUE THREAD

**Issue by TrubluPlays** [TEdit/Terraria-Map-Editor#1314]
Walls with the ID of 244 (Which, according to the wiki, are Unsafe Living Wood Walls) don't have a name in the dropdown menu. Also, when placed while zoomed out, they appear as large pink blocks, but when zoomed in, have the correct texture.

1. Go to any tool that allows you to place walls
2. Click on the dropdown menu to select a wall
3. Scroll down to 244

![Wall244](https://user-images.githubusercontent.com/60411184/84721216-5f99c400-af3d-11ea-82a1-94c7b572a3dc.png)

![image](https://user-images.githubusercontent.com/60411184/84721571-3594d180-af3e-11ea-85e7-ea9ef76cc831.png)

 - OS: Windows 10
 - Version: TEdit v4.0.0-beta20
 - Terraria Version 1.4.0.5

Walls 272 (Marble Wall) and 273 (Granite Wall) also have no name, but appear to be copies of a different Marble/Granite Wall. All issues that apply to Wall 244 also apply to walls 272 and 273.

**Comment by BinaryConstruct** [comment]
This should be fixed with the next release.
