### ISSUE TITLE
TEdit stuck on validating specific world.

### ISSUE THREAD

**Issue by Godzii** [TEdit/Terraria-Map-Editor#1315]
Hi.
I had an issue with validating worlds and beta 20 update fixed it except one specific world that i'am currently playing on. I make edits to the world but I can't save it.
Could you please help me with that?
[The_Wild_Flatland.zip](https://github.com/TEdit/Terraria-Map-Editor/files/4785443/The_Wild_Flatland.zip)

**Comment by BinaryConstruct** [comment]
I checked this world and was able to make changes. However, I did notice that the world version was for Terraria 1.4.0.3 and TEdit saves are only compatible with 1.4.0.5. Have you made sure you have the latest Terraria version?

**Comment by Godzii** [comment]
I updated Terraria to 1.4.0.5 version and also updated TEdit to Beta 21. The problem is when i'am trying to save this world in TEdit it stucks on phase "Validating World" even if i only open this file and immediately try to save it without editing.
What am I doing wrong?
![TEdit](https://user-images.githubusercontent.com/66995822/85000493-8a656180-b163-11ea-87b6-f695ef2984a8.png)
[The_Wild_Flatland.zip](https://github.com/TEdit/Terraria-Map-Editor/files/4797497/The_Wild_Flatland.zip)

**Comment by Godzii** [comment]
TEdit Beta 23 fixed the issue. Thank you!
