### ISSUE TITLE
[Renderer] Fix Vanity Trees, Specialty grass

### ISSUE THREAD

**Issue by dalgrim** [TEdit/Terraria-Map-Editor#1318]
Obviously a low priority issue but just wanted to list some missing sprites:
tile 477: Golf Grass (zoomed in is blank, zoomed out is pink)
Vanity Trees have no leaves when zoomed in.
All pylons listed as tile 597 "jungle pylon" regardless of which pylon they are. * I do see items listed in "Tile Entities" with the correct x,y coords. So what I'm saying is: "You must construct additional pylons." :D

**Comment by BinaryConstruct** [comment]
Argh! Resource limits strike again. 

Some of these require adjustments to the render engine, such as vanity trees, golf grass, xenon moss. They _should_ still edit correctly. 

Pylons have been fixed.

**Comment by BinaryConstruct** [comment]
The renderer fixes are also listed in #1284, so I'll track further work there.
