### ISSUE TITLE
FInd item/tile with find next/prev and list. 

### ISSUE THREAD

**Issue by qjroundy** [TEdit/Terraria-Map-Editor#1319]
I would love a tool/plugin that would allow me to search the world for specific items/blocks etc. Like shadow chest, statues, heart canisters, specific pots, etc. would probably have to limit results (in case somebody searches for something like dirt....)

This would help people find items, locate chests (without using search in chest) statues, paintings, hearts, enchanted sword, and a lot of other things. Possible with a category search (all paintings, all gold chests, all statues etc)

**Comment by BinaryConstruct** [comment]
This is now a plugin
