### ISSUE TITLE
Old Color Scheme was way better. It actually matched the ingame map mostly.

### ISSUE THREAD

**Issue by Tamamo89** [TEdit/Terraria-Map-Editor#1323]
I'm kind of disappointed with the new color scheme. It's very dull and desaturated. It's very hard to tell tiles apart when zoomed out.  This one doesn't match the ingame map at all.

**Comment by BinaryConstruct** [comment]
Good idea to use the ingame map colors. I was mostly looking for a way to quickly add all the new tiles.
