### ISSUE TITLE
Mask for Biome Morph tool?

### ISSUE THREAD

**Issue by Sparrows413** [TEdit/Terraria-Map-Editor#1325]
I'd like to be able to use the Biome Morph tool to switch which side the 'stripe' of hardmode Hallow/Crimson/Corruption is on, but I'd also like to retain the original shape.

It'd be nice if there was a way to lock which biome the Morph tool applied to, so that I could, for example, have only Crimson tiles turn into their Hallow versions without affecting any pure tiles.

**Comment by ahamling27** [comment]
I mean, you could just use the regular brush tool, mask hallow and paint crimson, then do the opposite. That does exactly what you are describing and can be done really quick if you make the brush like 1 x 200.  

That being said, I'm not sure if the morph tool is ever going to do what everyone wants it to do. I'm guessing here, but generating crystals for hallow and the various decos for all biomes would not be easy to do in brush strokes the way the current morph tool works.

**Comment by BinaryConstruct** [comment]
I've added isolating biomes to the morph tool list #533. It will get checked off there when complete.
