### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by oneilmw** [TEdit/Terraria-Map-Editor#1326]
**Description**
When launching a clean installation of TEdit, the fails to launch.

**To Reproduce**
1. Install Terraria through GOG (might not be necessary)
2. Install TEdit [https://github.com/TEdit/Terraria-Map-Editor/releases/tag/4.0.0-beta21](url)
3. Unzip TEdit
4. Navigate to the TEdit installation directory
5. Launch TEdit

**Expected behavior**
The program GUI should appear

**Actual behavior**
The program displays an error message box with the following text:

**Unhandled Exception**
An unhandled exception has occured.  Please copy the log from:
C:\Users\Username\Documents\My Games\Terraria\TEditLog.txt to the GitHub Issues list.
The program will now exit.

Here is the log file:
[TEditLog.txt](https://github.com/TEdit/Terraria-Map-Editor/files/4801858/TEditLog.txt)

Versions:
 - OS: Windows 8.1
 - Tedit 4 beta 21
 - Terraria 1.4.0.5

**Comment by BinaryConstruct** [comment]
It looks like it cannot find the textures. Try the tips here: https://github.com/TEdit/Terraria-Map-Editor/wiki/Install-Requirements#for-sprite-viewing
