### ISSUE TITLE
After 1.4.0.5 Terraria refuses to load previously edited world.

### ISSUE THREAD

**Issue by Betailas** [TEdit/Terraria-Map-Editor#1329]
Here's a link to my [corrupted save](https://drive.google.com/file/d/1U4EcEpbu2BT8B2bFaZZZpER8HHTbp8l0/view?usp=sharing). My world where me and my friend spent almost 50 hours, has disappeared after we played some days ago 8 or 9 hours! When I finished playing, I decided to check some things and what did I see - my world could not be loaded and the same thing is for the backup. Terraria version is 1.4.0.5. Please, help with this issue.

[Also this is what do I get when trying to open my world:](https://i.imgur.com/LkBgqQj.png).

Is it possible to copy my world and paste it into a new file? I tried but it has been pasted very bad.

**Comment by BinaryConstruct** [comment]
I checked out your world file, it looks like it has an invalid header and is missing all the chest/sign/mannequin data. TEdit should load this, if you want your buildings. However, all the chests will be empty. I highly recommend loading your backup files to see if one of those works. If you ever opened this in TEdit before the corruption, it should have made some backups.
