### ISSUE TITLE
When placing items on a mannequin then loading into the world in terraria. The Items i placed chane to completely different items

### ISSUE THREAD

**Issue by masterarchitect1122** [TEdit/Terraria-Map-Editor#1331]
I placed necro armor on mannequins and other sets on different mannequins but when i loaded into the world. The items had changed into completely random items such as sunflowers and pickaxes.

**Comment by BinaryConstruct** [comment]
Does this happen to mannequins when you place the items in game and edit the world or only when modifying the contents in TEdit?

**Comment by masterarchitect1122** [comment]
I had placed the mannequins in t edit and put different sets of armor on
them in t edit. But when i loaded into the game, the items had all changed
to random things.
