### ISSUE TITLE
Brush Tool Spray

### ISSUE THREAD

**Issue by bottledichor** [TEdit/Terraria-Map-Editor#1332]
Good day, I'm sorry if this isn't the place to ask this, however, I've been missing really hard a spray-type brush in TEdit the more I use it. Round and rectangular brushes are good for what they do, but I believe that it would be a godsend if there was a spray option (Like the dithering that happens between some biomes). Namely, because most biome transitions in the game already generate in a spraying manner. Such as from forest to jungle. It would cut a lot of time when it comes down to making biomes look like they naturally transition into one another. That said, I don't follow the project up close enough to know whether such a feature is already planned down the line, so I hope this isn't beating a dead horse. Good work with the tool so far, either way.

**Comment by BinaryConstruct** [comment]
I've add this as a feature request. It will probably get merged into this massive request at some point. https://github.com/TEdit/Terraria-Map-Editor/issues/1274
