### ISSUE TITLE
?

### ISSUE THREAD

**Issue by SadTomaz** [TEdit/Terraria-Map-Editor#1334]
06-22-2020 11:32:51: Starting TEdit 4.0.0.0 
06-22-2020 11:32:51: OS: Microsoft Windows NT 6.1.7601 Service Pack 1 
06-22-2020 11:32:51: OS Name: Microsoft Windows 7 Ultimate Service Pack 1 
06-22-2020 11:32:51: .NET Framework Version: 4.8 or later 
06-22-2020 11:33:06: Terraria v1.4.0.5 
06-22-2020 11:33:06: Terraria Data Path: C:\Program Files (x86)\Steam\steamapps\common\Terraria\Content 
06-22-2020 11:33:10: Creating Undo cache: C:\Users\Thiago\AppData\Roaming\TEdit\undo_399157204 
06-22-2020 11:33:11: Failed to load texture: Images\NPC_17 
06-22-2020 11:33:11: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
06-22-2020 11:33:11: Failed to load texture: Images\NPC_18 
06-22-2020 11:33:11: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
06-22-2020 11:33:11: Failed to load texture: Images\NPC_19 
06-22-2020 11:33:11: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown

**Comment by BinaryConstruct** [comment]
See #751 for tips.
