### ISSUE TITLE
Multiple bugs with mannequins

### ISSUE THREAD

**Issue by trannel** [TEdit/Terraria-Map-Editor#1335]
I experience multiple bugs with mannequins, possibly related to #1331 and #1333.

1) When inspecting a mannequin with right-click the armor is wrong, e.g. one mannequin wears the stardust armor set (helmet, plate, leggings) ingame, but in TEdit the mannequin shows up as empty. The mannequin that wears the silver armor (helmet, chainmail and greaves) ingame, instead wears the titanium headgear, pumpkin shirt and fox pants in TEdit. I did not edit any equipment in TEdit, and when I saved the world no items on mannequins were changed ingame. Copying mannequins to another world with TEdit without changing any equipment also worked like intended.

2) Pasting mannequins with equipped items onto other mannequins with equipped items will leave the new mannequin with no items. I only tested this when both mannequins had the same items equipped. Deleting all 6 tiles of the old mannequin before pasting a mannequin works as intended and no items are lost. 

3) Mannequins are not showing up in TEdit, only the standee is shown, but it might have always been like that and this is intentional:
![image](https://user-images.githubusercontent.com/43033261/85317684-18707d80-b4bf-11ea-9782-8ebd5540bc4f.png)

**Desktop:**
 - OS: Windows 10
 - Version: TEdit 4 beta 23
 - Terraria Version: 1.4.0.5

**Comment by BinaryConstruct** [comment]
Not showing up is expected, not working and having the wrong items is not.
