### ISSUE TITLE
[Tool] Hammer Time

### ISSUE THREAD

**Issue by BinaryConstruct** [TEdit/Terraria-Map-Editor#1337]
Add a new "brush" mode that works like the hammer. Please add comments if you have ideas for this feature.

## Modes for consideration
- [ ] Turn stairs into slopes
- [ ] Randomly add slopes on terrain for a more natural look
- [ ] Add slopes to all tiles in area to smooth it out.
- [ ] Utilize tile masks

**Comment by Vehdrehl** [comment]
Excellent new tool, though it has trouble leaving sloped gaps and/or half brick gaps depending on brush size. Greater than 1x1 equals the former. Perhaps by default make it determine the tile and wall?

**Comment by BinaryConstruct** [comment]
> I was wonder if it would be too much pain to implement a tool that would give a random "hammering" to surface tiles only (ones touching air) in order to simulate how game creates surface tiles in caves or ground. I often create artificial hills or islands (or replace corruption shafts in middle of jungle) Since all those blocks are "full blocks", it is visible on a glance that the land was edited unless i go and randomly hammer individual tiles to slopes or halfblocks and pay close attention my hand does not slip from the surface and hammer an inside tile. When you modify some 400 tiles like this, it becomes quite tiresome. Of course, since I can always do just that, it is not a neccessary feature, just maybe something to think about someday.

**Comment by BinaryConstruct** [comment]
Here are some early previews.
![2020-07-28 21_39_10-](https://user-images.githubusercontent.com/456755/88750504-4af34300-d11b-11ea-8160-7183b4d30acd.png)

![2020-07-28 21_39_39-](https://user-images.githubusercontent.com/456755/88750505-4b8bd980-d11b-11ea-9d62-6aa368c4ec54.png)

![2020-07-28 21_40_22-](https://user-images.githubusercontent.com/456755/88750506-4b8bd980-d11b-11ea-9bb9-ae193c161795.png)

![2020-07-28 21_40_35-](https://user-images.githubusercontent.com/456755/88750508-4b8bd980-d11b-11ea-9af2-445aa4dd3fda.png)

**Comment by B00ie23** [comment]
Will there be a toggle to switch between the brush and the pencil for this tool?
(The brush being automatic as shown above, and the pencil being manual for individual tile hammering, to elaborate)

**Comment by Dan-Gamin** [comment]
The hammer tool is making unintended slopes in the terrain. 
 
![image](https://user-images.githubusercontent.com/58695417/89517521-7690c000-d7e2-11ea-82ac-52d36ee95103.png)

If you remove that then it will look really natural.

**Comment by BinaryConstruct** [comment]
> The hammer tool is making unintended slopes in the terrain.
> 
> ![image](https://user-images.githubusercontent.com/58695417/89517521-7690c000-d7e2-11ea-82ac-52d36ee95103.png)
> 
> If you remove that then it will look really natural.

This should be fixed now.
