### ISSUE TITLE
Pet selection

### ISSUE THREAD

**Issue by Vehdrehl** [TEdit/Terraria-Map-Editor#1338]
Being able to choose and name your pets would be amazing, even if the name selection is from the pre-approved list.
As quoted from the official Terreria forums;

> Apologies if this was already answered, "dog" was too small a word to use in the search.
> 
> Is there a way to change town pet skins using TEdit? I'd love to choose which dog I have instead of being assigned a random one per world.
> I wish there was a way, I had to kill the town animals over and over to get the desired skin..
Having a way to select the animal sprite from the sprite section would be amazing.

**Comment by BinaryConstruct** [comment]
Unfortunately this is not stored in world data, so there is no way for TEdit to modify these.

**Comment by Vehdrehl** [comment]
No way to fix these issues then?

**Comment by BinaryConstruct** [comment]
No, this would be mod territory since it requires in-game changes.
