### ISSUE TITLE
Zooming in with non-standard DPI is buggy

### ISSUE THREAD

**Issue by retep998** [TEdit/Terraria-Map-Editor#1339]
**Describe the bug**
When using the mouse wheel to zoom in/out with a DPI other than 100%, the zoom functionality does *not* zoom on the point where the cursor is.

**To Reproduce**
1. Set DPI in Windows to some value other than 100% (might need to restart Windows for DPI to take effect fully)
2. Run TEdit and load any world
3. Zoom in/out using the mouse wheel

**Expected behavior**
When zooming in and out, always keep the point on the map where the cursor is at the exact same point on the screen.

**Screenshots**
I can't capture a good gif of this as ShareX has its own bug with capturing the mouse cursor correctly in high DPI situations.

**Desktop:**
 - OS: Windows 10
 - Version: 4.0.0-beta26
 - Terraria Version: 1.4.0.5

**Comment by BinaryConstruct** [comment]
Ug, windows dpi settings are the worst. I'll look into it along with the other scroll issues.
