### ISSUE TITLE
I simply cannot open TEdit, it worked normally previously, and im using beta 27! it asks me to put the TEditlog.txt

### ISSUE THREAD

**Issue by Nilo101** [TEdit/Terraria-Map-Editor#1340]
**Before Submitting an Issue**
* If you are having issues loading a world, please attach it to the current version world thread (see pinned issues).
* If you get an unhandled exception or crash, please _**check your log before posting**_.
  * _Copy paste using code [block tags](https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks) into the issue as a comment_

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Version [Tedit 4 beta 9]
 - Terraria Version [e.g. 1.4.0.4]

**Additional context**

**Comment by BinaryConstruct** [comment]
Please attach the log, or include steps to reproduce the issue in the body. Be sure you are unzipping all files to a folder the program can write to, such as c:\games\tedit or similar.

**Comment by BinaryConstruct** [comment]
See https://github.com/TEdit/Terraria-Map-Editor/wiki/Troubleshooting#application-launch-or-map-loading-issue
