### ISSUE TITLE
Inconsistency between unfiltered and filtered sprites.

### ISSUE THREAD

**Issue by LadySaga** [TEdit/Terraria-Map-Editor#1341]
**Describe the bug**
If I just click on an unfiltered sprite category I usually get all, or most of what should be in there, but when we're working we constantly search for words as filters, since we might not want to scroll through the list for the category all the time, and in those cases things get wonky and not all options show up do to the sprites having names that doesn't include the search word.

Let's use torches as an example.
Clicking on it gives you all the 22 types, but searching for "torch" only gives 7 of them, because they have torch in their name, while the other 15 doesn't.

These are found when searching for "torch"
Torch, Desert, Coral, Corrupt, Crimson, Hallow & Jungle

If I want to find the other ones I need to search for their specific type, such as "yellow" for the Yellow Torch, or Ultrabright for the Ultrabright torch.
The ones who are excluded from "torch" are:
Purple, Yellow, Blue, Green, Red, Orange, White, Ice, Pink, Bone, Ultrabright, Demon, Cursed, Ichor and Rainbow. Ultrabright, Cursed, Demon.

I guess it's "just" a matter of renaming sprites. That said, I'm no coder/programmer, so I have no idea if that is a "just" or if it's a TON of work.

But yeah, you may already be aware of the issue, but just wanted to mention it just in case you weren't.
There are also other weird instances of this, where for instance searching for Toilet lists the regular, and the Golden in the Chair:15 category, and the other toilets in the Ebonwood Toiler:497.
Plus a whole lot of sprites that I have a hard time finding.

If you want, I could (try to) go through the sprite lists and see what inconsistencies we have when searching, or just clicking the unfiltered categories, and if I find something that's completely missing, and so on. Just let me know and I'll see what I can manage to find.

![sprites1](https://user-images.githubusercontent.com/37087535/85874213-98098f80-b7d2-11ea-8269-2fda3563f2c1.PNG) ![sprites2](https://user-images.githubusercontent.com/37087535/85874221-98a22600-b7d2-11ea-9cf1-47b9407ceee7.PNG)

Oh, and a side note about the Sprite window.
Would it be possible to add one of those scale things between the categories and the actual sprites? As you can see in the screenshots, the bottom box with the sprites doesn't show all the torches because they are enough to require scrolling, but the categories also take a lot more space, so if we could drag those two boxes up and down, that would help a lot, because once I'm IN the category, I'd rather see those, instead of just some, while the categories still take up 50% or more of the space.
(Maybe I should open a separate "issue/feature" about that on second thought, since I have other ideas about ui scaling... yeah I'll probably write something up about that, then I could take some screenshots as well to clarify stuff)

Thanks for doing so much amazing work, and constantly churning out updates so fast that sometimes when I update I even jump several numbers. :)

**Desktop (please complete the following information):**
 - OS: Windows 10 Home
 - Version: TEdit 4 beta 27

**Comment by BinaryConstruct** [comment]
Thank you for the feedback, I'll look into making the search more intuitive and a resize bar between two panels.

**Comment by BinaryConstruct** [comment]
Tracked with #1273
