### ISSUE TITLE
Timer sprites sometimes work, sometimes break completely

### ISSUE THREAD

**Issue by LadySaga** [TEdit/Terraria-Map-Editor#1342]
Some sprites can intentionally only be placed one at a time, and some others can be painted as with the brush, but the Timer sprites (1/4 1/2 1 3 5 on or off doesn't matter) seems to be living their own life.

I've noticed a whole bunch of issues with them.

Sometimes a Target Dummy is placed instead of the Timer, for some unknown reason.

It seems more common when you have a group of timers together, and/or place a timer ontop of another one, especially if you have a cluster of timers and click in the middle of it, then it's almost guaranteed.
But, it can still happen at any other time as well, be it a single Timer completely alone in the air, or surrounded by regular tiles and other sprites. It seems to be completely random.

The timers also seem to be more often the target of the issue where Undo doesn't work as intended all the time. So you eventually have to redo the part that was covered by the timer, and if it replaced a chest, or parts of a chest, then have fun having to also replace the chest -and- the contents it had (if it had any).

In the screenshot below here I opened up a map, and just proceded in this simple test.
I ONLY clicked in that systematic line, from left to right, once every 4x4 grid box.
The circles I marked is were weird things happened.

![timers](https://user-images.githubusercontent.com/37087535/85883128-ca21ee00-b7e0-11ea-971c-e23144893b77.PNG)

(I messed up the numbers for some reason, so... the actual 1234 order is apparently 1342... xD oh well, I'll describe the numbers where they are on the picture)

1: That diagonal line (without the target dummy) appeared by itself when I placed the 3rd timer in the top red circle.

3: When I clicked out that single timer to the right on the second row, then that -other- single timer right below the 5th one of the top row showed up by itself.

4: When I placed the 4th timer on the 3rd row, the Target Dummy appeared instead, (but with half of it's head covered by the timer from the previous diagonal blarf).

2: And when I added that last timer, another one was added close to the Target Dummy as well.

That concluded the first test.

Then I thought, what if it's just this map being weird?
So I loaded my other maps, and I can confirm that I had the same issues.

Then I made a NEW map, and that's where things went even weirder, and really broke.

I tried recording it, but my phone camera is too shitty, and OBS is complaining and doesn't want to record... But I'll try to explain, and I'll try adding a video in a comment later if I manage to fix that somehow.

So on a new map, I couldn't even paint them, only one at a time like some other sprites intentionally work.
...or so I thought.

turns out I was indeed painting them, but... in a VERY different place than where I was painting.

I noticed that when I tried to paint it it placed 1, but kept lagging as I held the mouse down, so I assumed something was going on, and scrolled out.
Lo and behold, it was painting them weirdly attached to the right edge of the map.

It also seems to be stuck in that Brush mode where you hold Shift, where you choose an origin point, and can use that to paint a larger area by drawing a continous straight line from that origin point.
Except I wasn't holding Shift.. or Ctrl.
And it certainly wasn't centered anywhere close to where I was clicking and/or painting.

If I did hold Shift, or Ctrl it seemed to move this origin point a bit, but not TO where I clicked, but kind of just dragged the origin point a bit from where it was, and it seemed to choose a random direction as well.

I also noticed two more things.

On new maps it's most often the right side of the map, but CAN apparently also be in other places.
While fiddling with video not working I did take a screenshot at least.
![timer-newmap](https://user-images.githubusercontent.com/37087535/85883428-43214580-b7e1-11ea-8d05-d33b0cd56b3c.PNG)
The RED areas are where i DID click and paint, but as you see, it all seemed to originate from that weird spot in the right side corner.
The BLUE marks is how it "worked" when I actually held Shift. It just made long thin lines, but didn't care which direction I moved my mouse either.

After several maps and tests (including restarting) these timers on the New Maps seem impossible to Undo, no matter if I use the regular Undo function, or that weird Undo+Redo trick... It's just stuck.

I did plug in another keyboard, just to make sure it's not my keyboard being weird and wonky as well, but I still had the same issues.

Windows 10, Tedit beta27.
Happens on all maps. Both current loaded maps, older maps (that tedit has to update), and completely new empty maps (which seems the most broken).

Let me know if you already know of this (I didn't find any issue posted about it) and/or if you want me to try to get a video of it somehow.

**Comment by BinaryConstruct** [comment]
Do you have windows zoom or any dpi settings enabled?

**Comment by BinaryConstruct** [comment]
Thanks for all the details 👍

**Comment by LadySaga** [comment]
Hi, sorry I completely missed the email that I had a reply, so I just saw this.

I have never actually heard about Windows Zoom, and while I know what the DPI letters stands for, I have no idea about any specific settings on the computer, but if you're not faster than me I'll see if I can google some info about both of these, so I know if the answer is yes or no to them. :P Cus right now, I have no idea, but I will take a look and find out! :)

And you're welcome! :) Hope it's just something on my end so it's less work for you, and if it's not, then I hope it's easy fixes (this one and the other ones I posted and might post later ^^)

**Comment by LadySaga** [comment]
Sorry it took a while to get back to you on this. I was low of mental spoons (don't need to get into that) and also other stuff that came in the way.

So I googled around a bit, and I was a bit confused about that Windows Zoom thing... I only found that Zoom video-call app, and... the Magnifier tool in Windows 10? Don't know if you meant the magnifier or anything, but that's completely deactivated at least.
I also found out there is an option in the Display Properties (right click desktop) called Scale and layout, but that's set to 100% (Recommended). so nothing there either.
So.... Windows Zoom.... if any of those I checked was what you meant, then I guess no, I do not have Windows Zoom, I guess?

I think I found the DPI settings, unless I got those wrong as well xD (I really had no clue about these before), but if I found the right stuff, they look pretty much off as well.
I'll attach a screenshot of the DPI settings I found, incase that was what you were looking for.
![tedit-dpisettings](https://user-images.githubusercontent.com/37087535/86838982-1e5e8500-c0a1-11ea-84e5-d225d1f86cf6.PNG)

If all the stuff I looked at were the wrong stuff, let me know where and what to look for. :P

**Comment by BinaryConstruct** [comment]
So I did some testing and was able to replicate some of the issues. 

From my testing, using shift can be unpredictable at times, usually when clicking outside of the map window such as to select a new sprite. It seem the functions for capturing focus (mouse hover, etc) are not always firing from the rendering engine. This is a bit tricky since it is a library I am using and didn't create all the low level hooks. I'll see if I can get it a little better, but I don't have a timeline.

**Comment by BinaryConstruct** [comment]
Seems to be resolved now.
