### ISSUE TITLE
Replace certain sprites

### ISSUE THREAD

**Issue by Aqre** [TEdit/Terraria-Map-Editor#1344]
**Is your feature request related to a problem? Please describe.**
I have pink illuminate moss but I want to make it blue. It works for the most part since the blue moss has a block form, but it also has a grass-like form. When I load my world, I find that it worked for the most part, but now its blue moss blocks with pink grass growing out of it. 

**Describe the solution you'd like**
With the same function as the "Replace all tiles" plugin, it would replace all sprites. Basically, it would replace all the blocks with a list of sprites (without pictures)
**Describe alternatives you've considered**
If the above solution doesn't work out, there could be a "Remove all sprites" and type in the exact name of the sprite from the sprite list on the right hand side of the screen and removes all of the specified sprites from the world

**Additional context**
![2020-06-26](https://user-images.githubusercontent.com/51094192/85912952-ccd71000-b7ed-11ea-9872-1dd3010fddcc.png)

**Comment by BinaryConstruct** [comment]
Tracked in #1273
