### ISSUE TITLE
can i ask?

### ISSUE THREAD

**Issue by ENDER-Jake** [TEdit/Terraria-Map-Editor#1347]
are their a way to change the pixel texture into a normal Terraria texture?
![Screenshot (3)](https://user-images.githubusercontent.com/67630666/86106146-69e5c180-baea-11ea-99da-ffc7285a96d6.png)

**Comment by BinaryConstruct** [comment]
Please see the wiki instructions: https://github.com/TEdit/Terraria-Map-Editor/wiki/Install-Requirements#for-sprite-viewing
