### ISSUE TITLE
I Can't rotate nothing

### ISSUE THREAD

**Issue by Ssucodemaracuja** [TEdit/Terraria-Map-Editor#1349]
**After me copy one and try to flip, the Tedit closes.**

**To Reproduce**
1. Copy some thing
2. Go to 'Clipboard'
3. Click on the 'Flip X' or 'Flip Y'

**Desktop:**
 - OS: [Windows 10]
 - Version [Tedit 4 beta 27]
 - Terraria Version [1.4.0.5]

**Comment by BinaryConstruct** [comment]
Terraria content files are required for this feature to work at the present time. See https://github.com/TEdit/Terraria-Map-Editor/wiki/Install-Requirements#for-sprite-viewing
