### ISSUE TITLE
TEdit Problem

### ISSUE THREAD

**Issue by Alxxmeurt** [TEdit/Terraria-Map-Editor#1350]
* If you get an unhandled exception or crash, please _**check your log before posting**_.
  * _Copy paste using code [block tags](https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks) into the issue as a comment_

**Describe the bug**
I cannot launch TEdit. Once i do , it brinch me a small pop up that tell me to send a bug report here.

Here is the TEdit Log.txt :

07-02-2020 17:11:24: Starting TEdit 4.0.0.0 
07-02-2020 17:11:24: OS: Microsoft Windows NT 6.1.7601 Service Pack 1 
07-02-2020 17:11:24: OS Name: Microsoft Windows 7 Professional Service Pack 1 
07-02-2020 17:11:24: .NET Framework Version: 4.8 or later 
07-02-2020 17:11:24: Failed to verify Terraria Paths. TEdit may not run properly. 
07-02-2020 17:11:24: Error - Élément racine manquant.
   à System.Xml.XmlTextReaderImpl.Throw(Exception e)
   à System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   à System.Configuration.XmlUtil..ctor(Stream stream, String name, Boolean readToFirstElement, ConfigurationSchemaErrors schemaErrors)
   à System.Configuration.BaseConfigurationRecord.InitConfigFromFile() 
07-02-2020 17:11:24: Error - Élément racine manquant. (C:\Users\ALEX\AppData\Local\TEdit\TEdit.exe_Url_djelqwaa3421xqpnwbctmvlx0hkbcwl0\4.0.0.0\user.config)
   à System.Configuration.ConfigurationSchemaErrors.ThrowIfErrors(Boolean ignoreLocal)
   à System.Configuration.BaseConfigurationRecord.ThrowIfParseErrors(ConfigurationSchemaErrors schemaErrors)
   à System.Configuration.ClientConfigurationSystem.OnConfigRemoved(Object sender, InternalConfigEventArgs e) 
07-02-2020 17:11:24: Error - Échec de l'initialisation du système de configuration
   à System.Configuration.ClientConfigurationSystem.OnConfigRemoved(Object sender, InternalConfigEventArgs e)
   à System.Configuration.Internal.InternalConfigRoot.OnConfigRemoved(InternalConfigEventArgs e)
   à System.Configuration.Internal.InternalConfigRoot.RemoveConfigImpl(String configPath, BaseConfigurationRecord configRecord)
   à System.Configuration.BaseConfigurationRecord.GetSectionRecursive(String configKey, Boolean getLkg, Boolean checkPermission, Boolean getRuntimeObject, Boolean requestIsHere, Object& result, Object& resultRuntimeObject)
   à System.Configuration.BaseConfigurationRecord.GetSection(String configKey)
   à System.Configuration.ConfigurationManager.GetSection(String sectionName)
   à System.Configuration.ClientSettingsStore.ReadSettings(String sectionName, Boolean isUserScoped)
   à System.Configuration.LocalFileSettingsProvider.GetPropertyValues(SettingsContext context, SettingsPropertyCollection properties)
   à System.Configuration.SettingsBase.GetPropertiesFromProvider(SettingsProvider provider)
   à System.Configuration.SettingsBase.GetPropertyValueByName(String propertyName)
   à System.Configuration.SettingsBase.get_Item(String propertyName)
   à System.Configuration.ApplicationSettingsBase.GetPropertyValue(String propertyName)
   à System.Configuration.ApplicationSettingsBase.get_Item(String propertyName)
   à TEdit.Properties.Settings.get_TerrariaPath()
   à TEdit.DependencyChecker.CheckPaths()
   à TEdit.App.OnStartup(StartupEventArgs e) 
07-02-2020 17:11:24: Unable to locate Terraria. No texture data will be available. 
07-02-2020 17:11:25: Error - Élément racine manquant.
   à System.Xml.XmlTextReaderImpl.Throw(Exception e)
   à System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   à System.Configuration.XmlUtil..ctor(Stream stream, String name, Boolean readToFirstElement, ConfigurationSchemaErrors schemaErrors)
   à System.Configuration.BaseConfigurationRecord.InitConfigFromFile() 
07-02-2020 17:11:25: Error - Élément racine manquant. (C:\Users\ALEX\AppData\Local\TEdit\TEdit.exe_Url_djelqwaa3421xqpnwbctmvlx0hkbcwl0\4.0.0.0\user.config)
   à System.Configuration.ConfigurationSchemaErrors.ThrowIfErrors(Boolean ignoreLocal)
   à System.Configuration.BaseConfigurationRecord.ThrowIfParseErrors(ConfigurationSchemaErrors schemaErrors)
   à System.Configuration.ClientConfigurationSystem.OnConfigRemoved(Object sender, InternalConfigEventArgs e) 
07-02-2020 17:11:25: Error - Échec de l'initialisation du système de configuration
   à System.Configuration.ConfigurationManager.PrepareConfigSystem()
   à System.Configuration.ConfigurationManager.RefreshSection(String sectionName)
   à System.Configuration.ClientSettingsStore.ReadSettings(String sectionName, Boolean isUserScoped)
   à System.Configuration.LocalFileSettingsProvider.GetPropertyValues(SettingsContext context, SettingsPropertyCollection properties)
   à System.Configuration.SettingsBase.GetPropertiesFromProvider(SettingsProvider provider)
   à System.Configuration.SettingsBase.GetPropertyValueByName(String propertyName)
   à System.Configuration.SettingsBase.get_Item(String propertyName)
   à System.Configuration.ApplicationSettingsBase.GetPropertyValue(String propertyName)
   à System.Configuration.ApplicationSettingsBase.get_Item(String propertyName)
   à TEdit.Properties.Settings.get_CheckUpdates()
   à TEdit.ViewModel.WorldViewModel..ctor()
   à TEdit.ViewModel.ViewModelLocator.CreateWorldViewModel()
   à TEdit.ViewModel.ViewModelLocator..cctor() 
07-02-2020 17:11:25: Error - Une exception a été levée par l'initialiseur de type pour 'TEdit.ViewModel.ViewModelLocator'.
   à TEdit.ViewModel.ViewModelLocator.get_WorldViewModel()
   à TEdit.View.SpriteView2..ctor() 
07-02-2020 17:11:25: Error - L'invocation du constructeur sur le type 'TEdit.View.SpriteView2' qui correspond aux contraintes de liaison spécifiées a levé une exception.
   à System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   à System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   à System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   à System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   à System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   à System.Windows.Application.DoStartup()
   à System.Windows.Application.<.ctor>b__1_0(Object unused)
   à System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   à System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   à System.Windows.Threading.DispatcherOperation.InvokeImpl()
   à MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   à System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   à System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   à System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   à MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   à System.Windows.Threading.DispatcherOperation.Invoke()
   à System.Windows.Threading.Dispatcher.ProcessQueue()
   à System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   à MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   à MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   à System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   à System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   à System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   à MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   à MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   à System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   à System.Windows.Application.RunDispatcher(Object ignore)
   à System.Windows.Application.RunInternal(Window window)
   à TEdit.App.Main() 

**Expected behavior**
I would like a magical miracle solution that would allow me to  launch TEdit (im not too good at computer , so idk what to write here)

- OS: [Windows 7 pro]
 - Version [Tedit 4 beta 27]
 - Terraria Version [1.4.0.5]

**Comment by BinaryConstruct** [comment]
I looks like your settings file is corrupt. Try to delete this folder `C:\Users\ALEX\AppData\Local\TEdit\`

**Comment by Alxxmeurt** [comment]
Thank you so much for your help, it did work and i am gratefull. i can barely enjoy terraria without editing it XD

**Comment by BinaryConstruct** [comment]
Great! I'll see if I can make resolving this issue automatic with the next release or two.
