### ISSUE TITLE
Tables and chairs disappear

### ISSUE THREAD

**Issue by scd87** [TEdit/Terraria-Map-Editor#1351]
## Before Submitting

* If you are having issues loading a world, please attach it to the current version world thread (see pinned issues).
* If you get an unhandled exception or crash, please _**check your log before posting**_.

### Steps to reproduce the issue?
1) 

### Post relevant contents of log or attach log file _**(very important)**_:
_Copy paste using code [block tags](https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks) into the issue as a comment_

### Attach world file

I downloaded the latest version of beta (27) and had the same problem I had 2 betas ago. I put chairs and tables down in tEdit and when I load the World everything else I've done in tEdit is there but you cant see the tables and chairs, they're invisible because they still take up space and you can still break them and collect them but they still don't show if you place them back down.

Thank you for the great work, though. First time using this and I'm loving it :)
![Invisible furniture](https://user-images.githubusercontent.com/67382998/86483158-5ab17e80-bd4b-11ea-9460-96b527f286c4.jpg)
![sitting on air](https://user-images.githubusercontent.com/67382998/86483163-5be2ab80-bd4b-11ea-9c91-9a34803872be.jpg)

**Comment by scd87** [comment]
It happened to all the furniture on the right side of the World (Ocean) and
then there's ghost items that seem to show if I go in a certain direction,
normally away from it.
I checked yesterday after many changes and saves to the World and the
furniture in the ocean biome is not seen but is there

**Comment by BinaryConstruct** [comment]
Could you attach a zip of the world file please?

**Comment by scd87** [comment]
There you go :) The ghost furniture is on the far right (ocean pylon) and
when you first spawn you'll see ghost train tracks as well just below where
you spawn. Thank you
