### ISSUE TITLE
Terraria load world before editing it with Tedit

### ISSUE THREAD

**Issue by NoOneAsked** [TEdit/Terraria-Map-Editor#1352]
Hi, im using Terraira 1.4.0.5 from Steam.
Im also using Tedit 4.0.0-beta26
I have saved the world and - it loads the backup from the world
I dont know what to do
I think, it is, because Tedit is out for 1.4.0.. but I dont know

**Comment by BinaryConstruct** [comment]
TEdit supports 1.4.0.5. First, be sure to make a copy of your working world file .wld or the .bak. 

Once that is done, I suggest opening a copy in TEdit, and use save-as with a new file name. At first, don't make any edits, just open then save as. If this new file works, then try making some edits. If not please attach the file that _works_ in Terraria as a zip to this issue and I can see if something in it isn't loading properly.
