### ISSUE TITLE
Ore Generator only generates dirt if you create the world using TEdit.

### ISSUE THREAD

**Issue by masetrhitman** [TEdit/Terraria-Map-Editor#1357]
Preface: I'm using Beta26.

Steps to replicate:
-Make sure Terraria is closed.
-Run TEdit.exe
-File>New
-Max out width and height
-Click 'Create'
-Let the world generate
-Set up world ores using the options in the menu on the right
(I specifically picked Copper, Iron, Tungsten, Platinum, Palladium, Orichalcum, Titanium, if that helps)
-Plugins>Simple Ore Generator
-Watch as the generator only generates dirt
-Run the plugin 6 more times just in case
-Die inside

Please message me if this isn't enough info to work with. I'm also going to save this mistake, and then enter and exit the world, then generate ores again to see if the changes just needed to be saved before those ores will generate.

**Comment by LadySaga** [comment]
I can confirm the same, with and without ore setup.

**Comment by BinaryConstruct** [comment]
Thanks for the report. This will be part of #1262.
