### ISSUE TITLE
Flip on X (or Y) axis of certain selection causes unhandled exception and crashes every time

### ISSUE THREAD

**Issue by Tman7077** [TEdit/Terraria-Map-Editor#1359]
**Bug Description**
This unhandled exception (which results in the program closing) occurs when I make a selection of a certain part of this world, copy it, and attempt to flip it on the X axis. I also tested, and will produce the same unhandled exception when flipping on the Y axis, but the X axis is the one I want it to mirror over. The exact selection I've made, I exported as a schematic and is attached, as well as the TEdit log files and the world from which the selection originated.

**To Reproduce**
1. Open TEdit beta 27
2. Open [this world](https://github.com/TEdit/Terraria-Map-Editor/files/4914674/Dwarven.Mines.zip)
3. EITHER use the select tool to select from coordinates 1902,236 to 2137,465 then copy, OR import [this schematic](https://github.com/TEdit/Terraria-Map-Editor/files/4914666/problematic_schematic.zip)
4. In the clipboard, select "Flip X" to get an unhandled exception resulting in [this error log,](https://github.com/TEdit/Terraria-Map-Editor/files/4914728/TEditLog.txt) or select "Flip Y" to get an unhandled exception resulting in [this error log.](https://github.com/TEdit/Terraria-Map-Editor/files/4914732/TEditLog.txt)

**Expected behavior**
I have used the flip X feature many times before on other selections, and flip Y occasionally, so I expected them to work as they normally do, but this one refuses to. I do not know well enough how to read the code that is output in the log, so I do not know what is causing the problem. However, in pure speculation, there may be a problem with a sprite that doesn't like being flipped: perhaps, a lava plant, the Cavern pylon, or some other furniture new in 1.4. I have not taken the time to try this repeatedly without certain sprites in it to test if that is the problem.

**Desktop Information:**
 - OS: Windows 10
 - Version: Tedit 4.0.0-beta27
 - Terraria Version: 1.4.0.5

**Additional context**
This unhandled exception occurs whether I attempt to flip the selection/schematic in all ways or places: if I select it and copy it, then attempt to flip it; if I upload the schematic then attempt to flip it; whether it is in the world from which it originated or attempted in another world; if I attempt to flip it on the X axis or Y axis. Also, to be completely clear, the problem arises from touching the "Flip [X or Y]" button, NOT after it has flipped and I attempt to paste it ─ I have never gotten that far.

**Comment by BinaryConstruct** [comment]
Thanks for the detailed feedback. I will look into this issue.
