### ISSUE TITLE
TEdit isn't showing sprites.

### ISSUE THREAD

**Issue by GooUckd** [TEdit/Terraria-Map-Editor#1360]
**To Reproduce**
1. Go to 'TEdit'
2. Click on 'Sprites'
3. See error. 

**Expected behavior**
I expected to see the sprites, like in the videos.

**Desktop:**
 - OS: Windows 10
 - Version TEdit v4.0.0-beta 27
 - Terraria Version: 1.4.0.5

I have no idea why there are no sprites. I am using the GoG version.
(I just wanted to place a chest with 2 zeniths stacked ;-;)
Screenshot:
![image](https://user-images.githubusercontent.com/62660100/87449190-84995980-c605-11ea-8b6b-ad9bbe46d935.png)

**Comment by GooUckd** [comment]
Also I had no idea what to click. So I clicked on bug. ._.

**Comment by BinaryConstruct** [comment]
See if this helps https://github.com/TEdit/Terraria-Map-Editor/wiki/Install-Requirements#for-sprite-viewing

**Comment by GooUckd** [comment]
I will try.

**Comment by GooUckd** [comment]
It didn't work...
I changed the thingy to "C:\GOG Games\Terraria\Content", and still no sprites. Am I doing something wrong?

**Comment by GooUckd** [comment]
It looks like this:
![image](https://user-images.githubusercontent.com/62660100/87457245-b95ede00-c610-11ea-94e0-344761434692.png)
Am I doing something wrong?

**Comment by GooUckd** [comment]
Oh and I ran it admin and non admin.

**Comment by BinaryConstruct** [comment]
Be sure to remove the `<!--` and `-->`

**Comment by GooUckd** [comment]
Oh, okay!

**Comment by GooUckd** [comment]
It worked! Thank you!
I am now gonna close this..!
