### ISSUE TITLE
TEdit Opened Yesterday Worked Fine But doesnt Work now

### ISSUE THREAD

**Issue by ToastedAi** [TEdit/Terraria-Map-Editor#1361]
So I Downloaded Tedit Yesterday to help wit hsome world building i need to do it worked fine yesterday then i turned it off and came back the next day and now it wont start up at all tried running it wit hadministrator checked my Antivirus everything was fine nothing is blocked i have everything i need to run it It still wont Start up??

**Comment by BinaryConstruct** [comment]
You might try deleting your %appdata%\tedit folder

**Comment by ToastedAi** [comment]
> You might try deleting your %appdata%\tedit folder and the %localappdata%\tedit folder. Also, check the log file in My Games\terraria\teditlog.txt

Ive Done that then restarted my pc but it still does not work

**Comment by BinaryConstruct** [comment]
Is there anything in the log file?

**Comment by ToastedAi** [comment]
![Capture](https://user-images.githubusercontent.com/68349564/87721816-f8c33100-c7ae-11ea-8f33-df869baa3a2e.PNG)

**Comment by ToastedAi** [comment]
> Is there anything in the log file?

yeah its up here ^^^^

**Comment by BinaryConstruct** [comment]
Interesting, it all looks ok. Maybe try windows update and a reboot?

**Comment by ToastedAi** [comment]
tried it still does not work

**Comment by BinaryConstruct** [comment]
Have you tried looking at processes (ctrl+shift+esc) to see if the exe launches then exits?

**Comment by ToastedAi** [comment]
it doesnt open at all

**Comment by ToastedAi** [comment]
> Have you tried looking at processes (ctrl+shift+esc) to see if the exe launches then exits?

it Still does not open at all i updated my pc to max and then redownloaded tedit restarted pc and then opened it it still does not opne

**Comment by BinaryConstruct** [comment]
Ok, may I ask a few questions?

Did you unzip all the files?
Does the program have write access to the folder it was extracted to? for example c:\games\tedit usually works.
What antivirus are you using?
Is your antivirus blocking TEdit as "unknown software"? This has been known to happen with Symantec.

**Comment by ToastedAi** [comment]
> Ok, may I ask a few questions?
> 
> Did you unzip all the files?
> Does the program have write access to the folder it was extracted to? for example c:\games\tedit usually works.
> What antivirus are you using?
> Is your antivirus blocking TEdit as "unknown software"? This has been known to happen with Symantec.

my antivures has not blocked anything i use bitdefender

**Comment by BinaryConstruct** [comment]
Please see new troubleshooting steps here: https://github.com/TEdit/Terraria-Map-Editor/wiki/Troubleshooting#application-launch-or-map-loading-issue
