### ISSUE TITLE
4.0.0-Beta27 is not properly labeled on the download screen. The option is completely blank.

### ISSUE THREAD

**Issue by masetrhitman** [TEdit/Terraria-Map-Editor#1362]
http://www.binaryconstruct.com/downloads/

**Comment by masetrhitman** [comment]
![image](https://user-images.githubusercontent.com/68140459/87650156-72efa900-c70e-11ea-8ef6-1616887b7280.png)

**Comment by BinaryConstruct** [comment]
Thanks, I'll look into it. https://github.com/TEdit/Terraria-Map-Editor/releases this works.

**Comment by BinaryConstruct** [comment]
Fixed.
