### ISSUE TITLE
Tedit Visual Studio Proplems

### ISSUE THREAD

**Issue by MasterMiner177** [TEdit/Terraria-Map-Editor#1364]
Every time when I try to open t edit on visual I keep on getting this error, What am I missing. - Thank YOu

![Capture](https://user-images.githubusercontent.com/68193916/87880841-c893b200-c9a9-11ea-94fe-e85eb3f7eade.PNG)
![Caddpture](https://user-images.githubusercontent.com/68193916/87880842-ca5d7580-c9a9-11ea-98a8-ccd9b338f937.PNG)

**Comment by BinaryConstruct** [comment]
You will need Visual Studio 2019 with the dotnet core and .net framework workloads installed. https://visualstudio.microsoft.com/vs/

**Comment by MasterMiner177** [comment]
Thank you so much you are awesome :)
