### ISSUE TITLE
TEdit won't start at all, it gives only error message "an unhandled exception has occured. Please copy log from"

### ISSUE THREAD

**Issue by O2241** [TEdit/Terraria-Map-Editor#1365]
When starting TEdit, programm not appears, appears only error message saying that I should copy the log and post it to github issues list. But I think I installed it incorrectly. here is a log:
[TEditLog.txt](https://github.com/TEdit/Terraria-Map-Editor/files/4948460/TEditLog.txt)

**Comment by O2241** [comment]
It says something like : failed to load textures

**Comment by BinaryConstruct** [comment]
This is the same as #751, please see that thread for troubleshooting tips.
