### ISSUE TITLE
Textures require an additional zoom level to render with v.4.0-beta28 than beta27 did.

### ISSUE THREAD

**Issue by RobotMan73** [TEdit/Terraria-Map-Editor#1366]
## Before Submitting

* If you are having issues loading a world, please attach it to the current version world thread (see pinned issues).
* If you get an unhandled exception or crash, please _**check your log before posting**_.

### Steps to reproduce the issue?
1) Load up a world and zoom (with scroll wheel) until textures are rendered. 

### What version of Terraria are you using?
1.4.05

### Post relevant contents of log or attach log file _**(very important)**_:
_Copy paste using code [block tags](https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks) into the issue as a comment_

https://photos.app.goo.gl/JNd2tSpryU4ghJyn8

The first photo is of TEdit beta27 and shows the minimum zoom level required for textures to render. The 2nd and 3rd are of TEdit beta28; the first is a screenshot of the same level of zoom as the first photo, but textures aren't rendered. The 3rd photo shows the minimum level of zoom required for textures to render in beta28.

**Comment by BinaryConstruct** [comment]
This is an intended change. The higher zoom level for textures was causing performance issues on some machines. I will attempt to make it a setting at some point so higher end machines can show textures further out.

**Comment by RobotMan73** [comment]
Oh gotcha. I considered it being intended but was leaning more towards not. Thanks for the response and info.
