### ISSUE TITLE
Tried Using TEdit but I cant install net framework 4.6.2 on windows 8, are there any versions of TEdit for 1.4.0.5?

### ISSUE THREAD

**Issue by ZyrtecX** [TEdit/Terraria-Map-Editor#1369]
**Before Submitting an Issue**
* If you are having issues loading a world, please attach it to the current version world thread (see pinned issues).
* If you get an unhandled exception or crash, please _**check your log before posting**_.
  * _Copy paste using code [block tags](https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks) into the issue as a comment_

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Version [Tedit 4 beta 9]
 - Terraria Version [e.g. 1.4.0.4]

**Additional context**

**Comment by BinaryConstruct** [comment]
Unfortunately, only Windows 10 is officially supported due to changes in the underlying frameworks TEdit relies upon. You _might_ be able to get it to work with the latest service packs installed.
