### ISSUE TITLE
Beta28 shift line not working in brush mode only pencil mode

### ISSUE THREAD

**Issue by afridley** [TEdit/Terraria-Map-Editor#1370]
**Describe the bug**
When you try to make a line while holding shift with the brush it does not work, only with the pencil tool does it work

**To Reproduce**
Select brush tool hold shift click once to place the start click somewhere else to place the end. Notice that the two points are not connected

**Expected behavior**
Two points will be connected like with the pencil tool

**Screenshots**

**Desktop (please complete the following information):**
windows 10 tedit 4.0.0Beta28

**Additional context**

**Comment by BinaryConstruct** [comment]
Is this still an issue in the latest versions?

**Comment by afridley** [comment]
I will double check tonight

**Comment by afridley** [comment]
@BinaryConstruct This issue is still present in 4.2.7

TEdit4.0.0-beta26 was the last version to have it working I believe. 
I happened with the refactor of the brush tool to make it more performant. Right before the hammer tool was added

![line](https://user-images.githubusercontent.com/34749972/113233390-bd955f00-9264-11eb-9942-0aa2ae8daf92.gif)

**Comment by ZunLise** [comment]
As of 4.3.0 this bug is still active.
<img width="492" alt="paint-line-bug" src="https://user-images.githubusercontent.com/79867593/117145113-6fbbcb80-adbb-11eb-90f3-2d8d9c300d20.PNG">
