### ISSUE TITLE
Cannot open TEdit 4.0.0-beta28. Crash log included.

### ISSUE THREAD

**Issue by exarobibliologist** [TEdit/Terraria-Map-Editor#1371]
**Describe the bug**
beta28 crashes on open. Box pops up telling me to submit the crash log here... so here you go.

**Expected behavior**
I expected it to open

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Version [Tedit 4.0.0-beta28]

[TEditLog.txt](https://github.com/TEdit/Terraria-Map-Editor/files/4989532/TEditLog.txt)

**Comment by BinaryConstruct** [comment]
This is the same as #751, please see the tips in that issue.
