### ISSUE TITLE
Hammering Cannot Be Undone

### ISSUE THREAD

**Issue by B00ie23** [TEdit/Terraria-Map-Editor#1374]
**Bug Description:**
Hammering a lot of the time cannot be undone, the only way to force undo is to reload the world (at the cost of all changes in the editing session being undone.)

**Steps to Reproduce the Behavior:**
1. Open any world, or create a random hill
2. Click on the Hammer tool
3. Use the Hammer's brush on the hill
4. Try to undo Step 3. The end result should (otherwise frequently will) look like the GIF attached below.

**Expected Behavior**
Tiles under/aside the desired slope should be ignored when dragging the brush.

**Screenshots/Sources:**
![SaIjRoJbZM](https://user-images.githubusercontent.com/45867359/89151229-58db0680-d515-11ea-8cf9-e7f997d297d7.gif)
(If it's hard to notice, watch the grass above the slopes change when I undo)

**Desktop Environment & Versions:**
 - Operating System: Windows 10 [Home Edition]
 - TEdit v4.0 [Beta 29]
 - Terraria v1.4.0.5

**Additional Context**
Although the hammer function is in early stages, this is an easy-to-encounter bug, even during normal practices.

**Comment by BinaryConstruct** [comment]
This will be fixed with the next release.
