### ISSUE TITLE
I want to be able to change the language

### ISSUE THREAD

**Issue by Doodlinka** [TEdit/Terraria-Map-Editor#1375]
Google translate russian is very hard to understand. I'd like to be able to change the language to english in the settings. So far the language the program is using seems to depend on the system language, but an option to change it to something else is necessary - nobody would like to change system language every time they use TEdit.

**Comment by BinaryConstruct** [comment]
Ah yes, I will add an option for this. This was an attempt at getting something started for a contributor who said they would make a russian translation but I guess I failed to realize that it would actually go into effect.

**Comment by BinaryConstruct** [comment]
![image](https://user-images.githubusercontent.com/456755/90088692-28e5ed00-dce5-11ea-97e8-99248c6ed19c.png)
This will be in the next release.

**Comment by BinaryConstruct** [comment]
This setting is saved per user, but takes an application restart to apply.
