### ISSUE TITLE
Editor stops rendering map when the window is wider than 4400px

### ISSUE THREAD

**Issue by vincent-lu** [TEdit/Terraria-Map-Editor#1376]
**Describe the bug**
Editor stops rendering map when the window is wider than (around) 4400px.

See screenshot attached.

**To Reproduce**
1. Open editor
2. Resize the editor window to be greater than 4400px
3. Will notice the edit panel on the right hand start to overlap, also the map will stops update/render

**Expected behavior**
The editor should work as is normally even when its wider than 4400px.

**Screenshots**
<img width="2186" alt="Capture" src="https://user-images.githubusercontent.com/390546/89627706-9ad1c700-d8de-11ea-8e4f-c9eb18ea0804.PNG">

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version Tedit 4 beta 29
 - Terraria Version 1.4.0.5

**Comment by BinaryConstruct** [comment]
Hmm, this is definitely outside the scope of things I can test. I'm not sure the rendering engine from Monogame would be capable of rendering at this resolution when embedded in a window. I'll look into it.

**Comment by vincent-lu** [comment]
Thanks @BinaryConstruct. Yeah I understand the resolution is a bit rare.

Maybe it can be tested in a virtual environment.

**Comment by BinaryConstruct** [comment]
This is fixed with the latest versions using a new HiDef profile.
