### ISSUE TITLE
Tedit not launching

### ISSUE THREAD

**Issue by peterbarn123890** [TEdit/Terraria-Map-Editor#1377]
**Describe the bug**
Tedit is not opening at all by opening the tedit.exe file. I've used tedit before and have all the requirements to launch it but now 
it doesn't open. When i use task manager and open it nothing shows up either.

**To Reproduce**
I don't know as it just randomly stopped working when I upgraded the version.

**Expected behavior**
The window should pop up and i should be able to open my world and edit it.

**Screenshots**

**Desktop (please complete the following information):**
  - OS: Windows 10
 - Version Tedit 4 beta 29
 - Terraria Version 1.4.0.5

**Additional context**

**Comment by BinaryConstruct** [comment]
The window takes a few minutes to load, but the process should show up in task manager.  

Additionally, see if any of these help: https://github.com/TEdit/Terraria-Map-Editor/wiki/Install-Requirements

**Comment by Tazawaki** [comment]
I have the exact same problem! Yesterday, it was working fine, and now, it doesn't even open...

**Comment by FusionBolt13** [comment]
> The window takes a few minutes to load, but the process should show up in task manager.
> 
> Additionally, see if any of these help: https://github.com/TEdit/Terraria-Map-Editor/wiki/Install-Requirements

Does it work with DirectX 12? Because if so, I don't know why miine won't launch.

**Comment by BinaryConstruct** [comment]
Make sure to unzip to a clean folder with write access. You may try deleting the cache folder in local app data as well. Finally, make sure TEdit has read access to the Terraria game folder.

**Comment by zkksch** [comment]
Have a similar problem.

Event log:
```
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
    <System>
        <Provider Name="Application Error" />
        <EventID Qualifiers="0">1000</EventID>
        <Version>0</Version>
        <Level>2</Level>
        <Task>100</Task>
        <Opcode>0</Opcode>
        <Keywords>0x80000000000000</Keywords>
        <TimeCreated SystemTime="2020-12-15T19:03:07.0859070Z" />
        <EventRecordID>13627</EventRecordID>
        <Correlation />
        <Execution ProcessID="0" ThreadID="0" />
        <Channel>Application</Channel>
        <Computer>-</Computer>
        <Security />
    </System>
    <EventData>
        <Data>TEdit.exe</Data>
        <Data>4.2.2.0</Data>
        <Data>a0b25d33</Data>
        <Data>d3d9.dll</Data>
        <Data>10.0.19041.662</Data>
        <Data>4653c355</Data>
        <Data>c0000005</Data>
        <Data>000000000000a1fc</Data>
        <Data>9c</Data>
        <Data>01d6d314eb84facd</Data>
        <Data>C:\Users\zkksch\Downloads\TEdit4.2.2\TEdit.exe</Data>
        <Data>C:\WINDOWS\SYSTEM32\d3d9.dll</Data>
        <Data>4ce72cec-7086-4fe8-8856-930415eac692</Data>
        <Data></Data>
        <Data></Data>
    </EventData>
</Event>
```

**Comment by BinaryConstruct** [comment]
@zkksch Please see the instructions here: https://github.com/TEdit/Terraria-Map-Editor/wiki/Troubleshooting#application-launch-or-map-loading-issue

**Comment by pumpkinking2** [comment]
So I have a similar issue but I try opening TEdit and nothing happens, I try running it in administrator nothing happens. Nothing pops up in task manager. There is one way to get it open, when I download the folder and unzip etc etc then move the file for the first time it opens for some reason. then after will not open again. So currently I just redownload any time i want to look at my world. This is really annoying. Any fixes?

**Comment by BinaryConstruct** [comment]
TEdit does not need administrator rights. You can check the logs to see if something is stopping it there, or check your windows event viewer.

**Comment by Riddles96** [comment]
Just reinstall it it will work fine.
