### ISSUE TITLE
Using latest version of TEdit, I encountered the "stuck on loading colors" bug.

### ISSUE THREAD

**Issue by CornPortal** [TEdit/Terraria-Map-Editor#1380]
It's as the title says. TEdit hangs on "loading colors".
I'm using the latest version of TEdit. I created the world a couple days ago, _after_ updating, so everything done to this world was done within the latest version of the program.
(I tried to attach a copy of the world file, as instructed, but it's not supported by the site).
I hope you'll forgive me, I am new to this. I'm trying to include as much info as possible.
I haven't had any bugs while editing my world before today (this issue manifested the first time I tried to load this world today, this wasn't happening last night).
Any files I need to attach, let me know, I will attach them ASAP.

PC specs:
Processor - Intel(R) Core i3-6100U @2.30GHz
RAM - 4gb
OS - 64 bit, x64-based

**Comment by BinaryConstruct** [comment]
Is there anything in your log file? It should be in mygames\terraria.

**Comment by CornPortal** [comment]
Not a thing. The log file is empty.
I attempted to reproduce the problem by reloading an earlier instance of the build and rebuilding everything a had before exactly as it was, or at least as close as I could get to the way it was and the problem didn't occur again.
Now I'm faced with another problem...
My PC began to lag really bad and I opened TEdit from the taskbar, then my PC froze, so I had to force shutdown. Once I restarted it, I tried to start up TEdit and now it just won't start. I opened task manager and the process for it isn't even running.
When I click it, the mouse loading icon indicates something is loading for like 2 seconds, then it goes back to the regular mouse and TEdit never actually loads.

**Comment by CornPortal** [comment]
I said f--k it and deleted the old TEdit folder with all the stuff in it, redownloaded the latest version, and it works now.
Sorry about all that. User errors, not app errors.
Anyway, thanks for the solid app; I have more fun with this than I do playing the actual game.

**Comment by BinaryConstruct** [comment]
Interesting. I'll add this to the wiki troubleshooting steps.
