### ISSUE TITLE
"None" liquid causes worlds to become weird/corrupted

### ISSUE THREAD

**Issue by Sirehub** [TEdit/Terraria-Map-Editor#1381]
**Describe the bug**
Placing "No liquid" using any of the liquid tools causes worlds to become weird/corrupted.

**To Reproduce**
1. Click on Pencil, Brush or Bucket Tool
2. Toggle Liquid Placing
3. Place "No Liquid" into the world
4. Save World
5. Re-open the world.

**Expected behavior**
"No Liquid" should place no liquid, rather than a _none_ that corrupts your world.

**Screenshots**
![Crash Replicating P1](https://user-images.githubusercontent.com/56782158/90332187-9cda0b00-dfed-11ea-8805-c27aeb355dbc.png)
![Crash Replicating P2](https://user-images.githubusercontent.com/56782158/90332192-a19ebf00-dfed-11ea-974c-512492bbfac5.png)
![Crash Replicating P3](https://user-images.githubusercontent.com/56782158/90332272-0eb25480-dfee-11ea-9d34-bd80c4a9bbc7.png)

 - OS: Windows 7
 - Version TEdit v4.0.0-beta 30
 - Terraria Version Latest

**Additional Info**
Strangely enough, this doesn't crash TEdit and no errors can be found in my log

**Comment by BinaryConstruct** [comment]
This should be fixed with the next release.
