### ISSUE TITLE
Brush tool shortcuts do not work q and w

### ISSUE THREAD

**Issue by afridley** [TEdit/Terraria-Map-Editor#1383]
**Describe the bug**
Brush tool shortcuts do not work q and w to toggle block / wall

**To Reproduce**
When using the brush tool hit q or w to toggle wall and block, notice that neither does anything. Switch to the pencil tool and toggling will work

**Expected behavior**
When q is hit it will toggle block when using brush
when w is hit it will toggle wall when using brush

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Version [Tedit 4 beta 31]
 - Terraria Version [e.g. 1.4.0.4]

**Additional context**

**Comment by BinaryConstruct** [comment]
This will be tracked with #1452
