### ISSUE TITLE
"Save Tile Entities Section..." TEdit v4.0.0-beta31

### ISSUE THREAD

**Issue by KuraudoSoruja7** [TEdit/Terraria-Map-Editor#1384]
My _painful_, **unending** save bug...

**Describe the bug**
For the last few releases of TEdit I have had a massive issue in saving my world(s) after certain things are done in adding. When I go to save my world it often gets stuck with the message "Save Tile Entities Section..." on the Save Progress Bar at the bottom. This happens regardless of if I leave auto-save on or do it manually from the File menu. It will stay like that permanently with no change. Regardless of what I click on. The only way to remedy the issue is to load another world (or an earlier save), or close the program down and reopen.

There doesn't appear to be a specific rhyme or reason that this happens other than certain things seem to disagree with the programme. Some of the occurrences of this fault come after the following but are limited to:

-Certain wall tiles being placed over other wall tiles (such as Corrupt Mass Wall being placed over Ebonstone Wall)
-Certain Sprites are placed on the world (Corruption Torches - specifically Torch_108, Relics & paintings (some that have been in since before Terraria V4.0)

**To Reproduce** (_This is one sure fire way of getting the problem to occur_)
1. Go to the 'Sprite Placer' tool on the left-hand tool bar.
2. Click on 'Sprites Tab' then 'Torch:4' then in the below 'Torch Style' box select 'Torch_108'
3. Place sprite anywhere on world and then click Save from File Menu.
4. See error in continuous message of "Save Tile Entities Section..."

**Expected behavior**
I would expect in any normal circumstance that it would save after a couple of seconds, maybe even quicker. It does when i'm only placing Terrain for example.

**Screenshots**
![image](https://user-images.githubusercontent.com/69923823/90683882-2b08f800-e25f-11ea-977f-c7ab42adbc37.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 (v.2004) 64-bit
 - Version: Tedit v4.0.0 beta-31
 - Terraria VersionL v1.4.0.5

**Additional context**
This was not happening until a build in late teens, Beta 18 or 19 but I can't be sure. Whatever the case is, it is now a lot worse than it was. Much more frequent. 
This is happening on multiple worlds. 
The system isn't crashing - so their is nothing in the TEdit log of any use sadly.

PS: plz send help. Thanks in advance.

**Comment by KuraudoSoruja7** [comment]
**UPDATE** It seemingly happens when I use the ctrl+z option. Could it be this all along? I will test further and if it does *not* seem the be that. I will post that in here.

**Comment by KuraudoSoruja7** [comment]
*Update* Ok true believers I think I may have an answer to what may have been happening.

I wasn't wholly sure what "Tile Entities" actually was. But I discovered the tab next to Sprites and Tally. When I loaded it up I saw a very very long list of co-ordinate positions with values. So I went to them and I realised it was in fact the list of hat racks, item frames etc. etc. 

Now this started to thatch a cunning plan. If I backed up my world - then deleted all of the frames etc. Would this fix the issue (Some of the entity listings looked odd showing that some items had 0 items in where as others had 8 (98% of the entities I had) which was odd as the item frames obviously only had one item. Anyway! I am pleased to say that may have worked.

To further explain and help someone piece this problem together I can show you I had well over a thousand entities (part of a project where I was going to show off every item and every armour on mannequins and weapon racks etc.). Was it the sheer amount of entities? Was it specific ones? Was it a problem that occurred with the mannequins from an earlier build? (as I remember them being mentioned in the release notes as a bug) Who knows. Maybe you can decide as now I need to go put at least the item frames in my banks back up so I can see what I am dumping.

*IN THE MEANTIME* have a laugh at the amount of entities I had....

![image](https://user-images.githubusercontent.com/69923823/90769309-ed9c7d00-e2e7-11ea-99a6-66fb4db8af66.png)

**Comment by KuraudoSoruja7** [comment]
I haven't had the problem since but also I have feigned away from having a single hat rack/mannequin or otherwise in my world.

Am I ok to start adding them (banking is a pain without pictures help you see)

**Comment by BinaryConstruct** [comment]
I think so. Try it and let me know if you have issues.
