### ISSUE TITLE
TEdit Is Not Loading?

### ISSUE THREAD

**Issue by 0DiNForTwo** [TEdit/Terraria-Map-Editor#1385]
So, verison of TEdit I’m using beta31. Windows 10. And 1.4.0.5 verison of terraria I’m using. 

So my problem as the title states it’s doesn’t load I have clicked on run administrator didn’t work and ran it normally didn’t work I also reinstalled and got rid of old TEdit files and now I’m stuck here with it not working. I used to use TEdit in my modded worlds never in vinialla (srry can’t spell) now it not wanting to work?!! 

So let me know if your able to help I really wanna use it I have a project I’m going to do on it but I want to speed my building process up

**Comment by 0DiNForTwo** [comment]
Whoops
My bad I clicked wrong thing

**Comment by BinaryConstruct** [comment]
TEdit does not currently support modded worlds as they use a different file format. See https://github.com/TEdit/Terraria-Map-Editor/issues/1075
