### ISSUE TITLE
Hope to add a new language in TEdit

### ISSUE THREAD

**Issue by Palacedar** [TEdit/Terraria-Map-Editor#1386]
Hi there, TEdit is an excellent software, and I appreciate your contributions. When using it, I am not a native English speaker, I always get confuse with several block names and functions, so I hope to add new languages.

Would you mind adding Simplified Chinese to TEdit? I can be responsible or provide the content that needs to be translated.

I tried to edit some language files (in the attachment), but found that TEdit did not put the tile name into this file. Is there another language file that can be added or is it currently not supported to modify the tile/wall name?

[zh-CN.zip](https://github.com/TEdit/Terraria-Map-Editor/files/5100800/zh-CN.zip)

**Comment by BinaryConstruct** [comment]
Hi! A Chinese language was submitted recently and will be included with the next release https://github.com/TEdit/Terraria-Map-Editor/pull/1391. Currently this only works for the TEdit menu items. I am working on loading tile and item names from Terraria game files, but I have not had time to do this yet. I hope to have it before TEdit 4 is done with beta. Thanks!
