### ISSUE TITLE
Path Crash

### ISSUE THREAD

**Issue by Tazawaki** [TEdit/Terraria-Map-Editor#1394]
When i put my "Content" folder's path in the "settings.xml", TEdit crash, showing the following error message.
![image](https://user-images.githubusercontent.com/66832906/91331581-34e4ab00-e7cb-11ea-9510-cba07132f6ee.png)

Here are the code lines, to be sure i did it correctly : 
<--                                                                                    
   Uncomment the following and set Terraria/Content path.                                                                                    
   Perhaps useful if Terraria isn't installed locally or in a custom location.                                                                                    
-->
<<AltC>C:\Users\Utilisateur\Desktop\Terraria\Content</AltC>>

**Comment by BinaryConstruct** [comment]
I think you need the properly formatted xml of: 

`<AltC>C:\Users\Utilisateur\Desktop\Terraria\Content</AltC>`
