### ISSUE TITLE
TEdit don't work

### ISSUE THREAD

**Issue by Tazawaki** [TEdit/Terraria-Map-Editor#1395]
**Describe the bug**
When i try to open TEdit, it don't work. I tried to run it as an administrator, but still nothing. I doesn't even show an error message.

**To Reproduce**
I have no idea how it happened, 'cause it was still working fine yesterday.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version Tedit 4 beta 31
 - Terraria Version 1.4.0.5

**Comment by Tazawaki** [comment]
Okay, so, by retesting with an older version of TEdit, I realized that i were comming from my computer, and not from the software, ans i don't work either.

**Comment by Tazawaki** [comment]
So i looked at the "Requirements" page, and redid everything : i have the latest version of .NET, and i have DirectX 1.12.
I have no idea what to do!

**Comment by bai1996** [comment]
TEdit relies on .NET Framework v4.6.2， You can try it ， After downloading and installing this version, try to start 
[https://dotnet.microsoft.com/download/dotnet-framework/thank-you/net462-web-installer](url)

**Comment by Tazawaki** [comment]
It just says : ".NET Framework 4.6.2 or a newer version is already installed on this computer."
I dont know what to do...

**Comment by bai1996** [comment]
Can log files be provided,Net Framework version installed 
Logs are located in My Documents\My Games\Terraria\TEditLog.txt
You can take a look at this [https://github.com/TEdit/Terraria-Map-Editor/wiki/Troubleshooting](url)
