### ISSUE TITLE
I cant see textures or sprites 

### ISSUE THREAD

**Issue by 01BruceTheBeast** [TEdit/Terraria-Map-Editor#1398]
![image](https://user-images.githubusercontent.com/70790435/92297946-b389d700-ef87-11ea-8225-2bf9b6f2c253.png)

![image](https://user-images.githubusercontent.com/70790435/92297954-c8ff0100-ef87-11ea-8b24-d781d27396b5.png)

**Comment by terrariaplayer1336** [comment]
im having the same issue

**Comment by BinaryConstruct** [comment]
https://github.com/TEdit/Terraria-Map-Editor/wiki/Install-Requirements#for-sprite-viewing

**Comment by BinaryConstruct** [comment]
Please try this

**Comment by terrariaplayer1336** [comment]
@BinaryConstruct i tried doing it but it did not work
