### ISSUE TITLE
TEdit won't open Beta 32 4.0.0

### ISSUE THREAD

**Issue by NedgyDC** [TEdit/Terraria-Map-Editor#1399]
So I just updated TEdit to the latest update, however when i try to open, the logo appears in the screen, then just closes. After that nothing. I checked the task manager, and whenever i open it, it keeps showing up with the suspended thing next to it. Whats happening here?

**Comment by ErdeLien** [comment]
I had the same issue but later I figured out it is my antivirus closing the process. Maybe you can try to add it to the antivirus exceptions.
