### ISSUE TITLE
Sprite placement first value remains after undo

### ISSUE THREAD

**Issue by Holsteadtyler** [TEdit/Terraria-Map-Editor#1401]
**Before Submitting an Issue**
* If you are having issues loading a world, please attach it to the current version world thread (see pinned issues).
* If you get an unhandled exception or crash, please _**check your log before posting**_.
  * _Copy paste using code [block tags](https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks) into the issue as a comment_

**Describe the bug**
When placing sprites (let's say you are dragging 20 wood platforms across) the very first sprite placement remains even after undo.  

**To Reproduce**

 
See above.  Replicates every time.

**Expected behavior**
See above

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 
 - Version Tedit 4 beta 32
 - Terraria Version 4.0.5

**Additional context**

**Comment by BinaryConstruct** [comment]
Tracked with #1343
