### ISSUE TITLE
Not working after Windows update

### ISSUE THREAD

**Issue by GattoSasso** [TEdit/Terraria-Map-Editor#1403]
The program worked fine, then windows updated and now when I open it the logo appears and then the message "TEdit has stopped working" appears. I'm on Windows 8.1, TEdit version is 4.0.0 beta32 and the updates are: Microdoft Windows update (KB4576486), security update for Microsoft Windows (KB4577066) and Microsoft Windows update (KB4486118). I'm blaming those updates because I haven't changed anything else and before installing them it worked fine.

**Comment by BinaryConstruct** [comment]
Be sure to extract all files to a clean folder, and perhaps reinstall .net framework.

**Comment by GattoSasso** [comment]
Reinstalled .net framework, downloaded beta33 and it worked. Restarted pc and it doesn't work again.

**Comment by GattoSasso** [comment]
Found the cause, it was AVG. I noticed that .net framework installation had to close some programs to continue, and a restart would have opened those programs again. So I tried to close these programs one by one and after disabling AVG protection, TEdit worked. Now I added it to the antivirus exceptions and it works fine.
