### ISSUE TITLE
erase with liquids

### ISSUE THREAD

**Issue by moe41** [TEdit/Terraria-Map-Editor#1405]
brush eraser mode.
tile/wall mode
tile and wall checked
the others still default
 - OS: Windows 10
 - Version Tedit4beta32
 - Terraria Version1.4.0.5

**Comment by moe41** [comment]
before
![before](https://user-images.githubusercontent.com/66813644/93010394-f91d5400-f5c6-11ea-9d5b-384233ed18df.png)

**Comment by moe41** [comment]
after
![after](https://user-images.githubusercontent.com/66813644/93010409-266a0200-f5c7-11ea-8404-d18b0f99eff7.png)

**Comment by BinaryConstruct** [comment]
I see, this will be fixed with the next release.
