### ISSUE TITLE
help

### ISSUE THREAD

**Issue by opgamertheman** [TEdit/Terraria-Map-Editor#1406]
tedit dont open and it says and message and it disapears after 3
[TEditLog.txt](https://github.com/TEdit/Terraria-Map-Editor/files/5212949/TEditLog.txt)
sec

**Comment by bai1996** [comment]
The reason for the error in the log is 【Error - Could not find file 'C:\Users\Zemyna\AppData\Local\Temp\Rar$EXa7124.3258\settings.xml'.】 Check that the zip file is complete

**Comment by BinaryConstruct** [comment]
Please be sure to fully extract all files to a folder. See the wiki for install instructions.
