### ISSUE TITLE
Music Boxes

### ISSUE THREAD

**Issue by Crystalfishes** [TEdit/Terraria-Map-Editor#1408]
**Is your feature request related to a problem? Please describe.**
Only two music sprites exist; I can't find any of the existing ones (both pre and post 1.4).

**Describe the solution you'd like**
Allowing us to place all music boxes, and possibly other missing sprites I haven't noticed.

**Additional context**
If I pop open a world with a music box in it, it shows up, but I can't edit in new ones.

**Comment by BinaryConstruct** [comment]
Tracked with #1273
