### ISSUE TITLE
Not able to place sprites

### ISSUE THREAD

**Issue by terrariaplayer1336** [TEdit/Terraria-Map-Editor#1409]
i am not able to see any sprites in the sprite tab, even if i have the sprite placer tool equipped
i dont know how to fix it and the bug is very annoying as i cant place chests for my house
![Screenshot_95](https://user-images.githubusercontent.com/71885155/94270191-fe23c100-ff3f-11ea-9aa5-33da3b5f0969.png)
i would appreciate some help

thank you

**Comment by Ira-Shadebane** [comment]
I have the same problem. I am going to try duplicating my terraria folder and placing a Tedit folder inside it.

**Comment by BinaryConstruct** [comment]
Please see the wiki: https://github.com/TEdit/Terraria-Map-Editor/wiki/Install-Requirements#for-sprite-viewing

**Comment by lhunath** [comment]
This URL is now dead.

**Comment by Cathub132** [comment]
the thing happend to me how to fix it?
