### ISSUE TITLE
My thing isnt saving

### ISSUE THREAD

**Issue by loganbadagan** [TEdit/Terraria-Map-Editor#1411]
So what happened is im using beta 32 instead of beta 33 because of a plugin that is on 32 but now matter what i cant do i cant save the worlds. Well i can try, but it never starts on the loading bar and never saves. Why isnt it loading? Is it because im using the newest version of terraria and **one** beta number less? Im not sure so please help

**Comment by BinaryConstruct** [comment]
Possibly, the versions are tied to specific Terraria/world file versions.
