### ISSUE TITLE
lost everything (3.6)

### ISSUE THREAD

**Issue by realsolaris** [TEdit/Terraria-Map-Editor#1413]
Note: I have to use 3.6 in order to create maps for mobile devices.

I was trying to save something I'd been working on for a decent portion of time, but the load was taking a while, so I attempted to save what I created as a schematic and got hit with a fantastic message: "index was outside the bounds of the array". I tried this three times breaking it into individual saves with the same result. It eventually just pulled a fast one on me and brought up an unexpected error and closed it automatically. There wasn't anything on the log indicating an issue.

Reproduction
The saving worked just fine on a large world with a lot more blocks as opposed to not working on the one that had the error of which was a default world with less block variations.

More info
The save status bar kept going back and forth when it was saving tiles.
![load](https://user-images.githubusercontent.com/72039071/94468224-b6907580-0189-11eb-96e2-0fc83d7b5377.PNG)

**Comment by BinaryConstruct** [comment]
TEdit only supports the desktop version of Terraria.

**Comment by realsolaris** [comment]
what does that have to do with saving something in the application
