### ISSUE TITLE
Can't import PNG images into clipboard

### ISSUE THREAD

**Issue by JensMann** [TEdit/Terraria-Map-Editor#1414]
So I'm trying to import an image into the clipboard to make pixel art in my world but when I import the image it is just some dirt and stone.

1. Go to 'Clipboard'
2. Click on 'Import Schematic or image'
3. 'Select png file'
4. See Schematic as a few blocks of dirt and stone

**Expected behavior**
Should make the image into terraria blocks. Want to be able to import and paste an image into a world. 

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version Tedit 4 beta 33
 - Terraria Version 1.4.0.5

**Comment by BinaryConstruct** [comment]
PNG images have to use either the false color channels or match the color settings.xml exactly. https://github.com/TEdit/Terraria-Map-Editor/wiki/Image-Schematics
