### ISSUE TITLE
TEdit crashes on start

### ISSUE THREAD

**Issue by fgRuslan** [TEdit/Terraria-Map-Editor#1415]
**Describe the bug**
The bug is that TEdit doesn't start. There are many exceptions related to DXGI in the log.

**To Reproduce**
1. Start TEdit.exe
4. See an error

**Expected behavior**
Running TEdit

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Version Tedit 4 beta 33
 - Terraria Version 1.4.0.5

**Comment by fgRuslan** [comment]
[TEditLog.txt](https://github.com/TEdit/Terraria-Map-Editor/files/5360992/TEditLog.txt)

**Comment by AriDrSteam** [comment]
I'm having this same issue, I'm not sure what it is. It happens with beta 32, 33 and 4.1.1
