### ISSUE TITLE
Zooming in and out on 4k monitor doesn't work properly

### ISSUE THREAD

**Issue by PortalFan15** [TEdit/Terraria-Map-Editor#1417]
**Before Submitting an Issue**
* If you are having issues loading a world, please attach it to the current version world thread (see pinned issues).
* If you get an unhandled exception or crash, please _**check your log before posting**_.
  * _Copy paste using code [block tags](https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks) into the issue as a comment_

**Describe the bug**
Zooming in and out on a 4k monitor can have unexpected results, like zooming in on the wrong point, suddenly jumping to the opposite side of the map. Resizing the window does not seem to help either.

**To Reproduce**
1. Use a 4k monitor (I might be able to record some short videos of it happening if you do not have access to a 4k monitor)
2. Open the app and load in a world
3. Use either the scroll wheel, toolbar buttons, or shortcut keys to zoom in and out on the map

**Expected behavior**
It should zoom in relative to where my mouse is on the map, and zoom out 
relative to where my mouse is on the map.
**Screenshots**
Not really applicable.

**Desktop (please complete the following information):**
 - OS: Microsoft Windows 10 Home 10.0.19041
 - Version: TEdit v4.0.0-beta33
 - Terraria Version: 1.4.1

**Additional context**
World used was size large, and changing my resolution to 1920x1080 and reopening the program seemed to have fixed it, although going back to 4k causes it to break again.

**Comment by BinaryConstruct** [comment]
I was also able to reproduce this issue when crossing monitor boundaries on a multi-monitor system. I think this might be lower level in either the SharpDX or Monogame framework and may an underlying limitation. I'm not sure there is anything I can do for this.

**Comment by BinaryConstruct** [comment]
Please try https://github.com/TEdit/Terraria-Map-Editor/releases/tag/4.2.0
