### ISSUE TITLE
Specific issue with new princess NPC causing null value for key and unreadable world as long as she is present

### ISSUE THREAD

**Issue by EndraCelestial** [TEdit/Terraria-Map-Editor#1419]
I had to test this thoroughly before reporting this but I found that if a world has the princess present TEdit cannot load a world in the newest version. I got around it by submerging her in lava but she respawns quickly so I have to do this each time I need to access the program. I'm pretty sure there is no overlay for her, which is why it cant load. Please fix this soon.

**Comment by deadlypants905** [comment]
that fudging princess ruined my day-  night... 3:41 am? technically that's day

**Comment by EndraCelestial** [comment]
Hey Deadly, I just killed her and temporarily removed all available housing. I know its frustrating but we all need to stay calm.

**Comment by EndraCelestial** [comment]
If you have a lot of houses remove her and quickly open up TEdit and delete the requirements that way.

**Comment by BinaryConstruct** [comment]
See #1427
