### ISSUE TITLE
Doesn't let me start it

### ISSUE THREAD

**Issue by GameRTerraria** [TEdit/Terraria-Map-Editor#1420]
**Before Submitting an Issue**
* If you are having issues loading a world, please attach it to the current version world thread (see pinned issues).
* If you get an unhandled exception or crash, please _**check your log before posting**_.
  * _Copy paste using code [block tags](https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks) into the issue as a comment_

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Version [Tedit 4 beta 9]
 - Terraria Version [e.g. 1.4.0.4]

**Additional context**
[TEditLog.txt](https://github.com/TEdit/Terraria-Map-Editor/files/5379910/TEditLog.txt)

Generally doesn't allow me to install it from previous version when going into 1.4.1

**Comment by GameRTerraria** [comment]
[TEditLog.txt](https://github.com/TEdit/Terraria-Map-Editor/files/5379898/TEditLog.txt)
I was supposed to paste this to here when I started it up. It doesn't allow me to install its new version.

**Comment by BinaryConstruct** [comment]
See #1427
