### ISSUE TITLE
Crashes when trying to open up a certain world.

### ISSUE THREAD

**Issue by bonanooo** [TEdit/Terraria-Map-Editor#1421]
TEdit crashes when trying to open up a spesific world that I want to tamper with.Is the world itself corrupt or something else is happening?

[TEditLog.txt](https://github.com/TEdit/Terraria-Map-Editor/files/5387389/TEditLog.txt)

**Comment by EndraCelestial** [comment]
https://github.com/TEdit/Terraria-Map-Editor/issues/1419

**Comment by EndraCelestial** [comment]
Your world should be fine. Submerge the princess in lava and remove all vacant housing options.

**Comment by bonanooo** [comment]
> Your world should be fine. Submerge the princess in lava and remove all vacant housing options.

Yeah,I realized that shortly after too.First I thought it was related to 1.4.1 bush stuff she sells,because I tried other map editors and they worked after removing these(probably because that program didn't acknowledge NPCs).However TEdit still refused to load,I thought it's probably because of the Princess,I wasn't sure though.

**Comment by EndraCelestial** [comment]
They'll probably fix it as soon as we get a coder to read the issues. I would think it wont be too hard to fix this specific issue. All they need to do is add in an overlay image of her and code it in.

**Comment by BinaryConstruct** [comment]
See #1427
