### ISSUE TITLE
World not loading 

### ISSUE THREAD

**Issue by Mindcontroller6669** [TEdit/Terraria-Map-Editor#1422]
World doesn't load when trying to open it from TEdit

**To Reproduce**
1. Go to 'Open'
2. Click on the World
3. Let it try to load the tiles etc.

**Expected behavior**
Loaded up the world, making it free to edit

![56ADc1oDbJ](https://user-images.githubusercontent.com/16727066/96209181-e1b5eb80-0f23-11eb-955e-789e14c29e0e.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Version [Tedit 4 beta 33]
 - Terraria Version [e.g. 1.4.1]

The Log: 
[TEditLog.txt](https://github.com/TEdit/Terraria-Map-Editor/files/5388987/TEditLog.txt)

**Comment by FlyingDutchman1007** [comment]
Something goes wrong when loading NPC. I guess that's caused by the princess in 1.4.1

**Comment by EndraCelestial** [comment]
Yeah. I reported this issue earlier. No one's seen it. She doesnt have an overlay. You know the image that zooms in and out with the camera. There is probably more detail but it shouldnt be hard to fix. I'm not skilled in coding even though I'd like to help.

**Comment by Mindcontroller6669** [comment]
> Yeah. I reported this issue earlier. No one's seen it. She doesnt have an overlay. You know the image that zooms in and out with the camera. There is probably more detail but it shouldnt be hard to fix. I'm not skilled in coding even though I'd like to help.

It seems like you both are right, I didn't even know/get the notification that the Princess was moving in

**Comment by deadlypants905** [comment]
AHA! STUPID PRINCESS RUINED MY DAY! I DONT CARE ABOUT ANY FREAKIN VANITYS!!!!

**Comment by EndraCelestial** [comment]
Ikr! I hope a developer adds in a commit soon.

**Comment by BinaryConstruct** [comment]
See #1427
