### ISSUE TITLE
Terraria 1.4.1.1 - Princess Problems

### ISSUE THREAD

**Issue by BinaryConstruct** [TEdit/Terraria-Map-Editor#1427]
World file format has been updated, code changes are in progress and a new version will be released soon. 10-18-2020

Until then, drop the princess in LAVA.

**Comment by LeaveYouStan** [comment]
For the people that want a quick temporary fix. Just stand on the princess at night and summon a boss. When then princess dies save and exit and you can edit again until she respawns.

**Comment by BinaryConstruct** [comment]
Does anyone have a non-working test world they could attach to this issue? Thanks!
