### ISSUE TITLE
right click a sprite with sprite placer to pick it

### ISSUE THREAD

**Issue by krazybluemonkey** [TEdit/Terraria-Map-Editor#1430]
**Is your feature request related to a problem? Please describe.**
could've have sworn that the picker allowed you to pick sprites for the sprite placer at one point. doesn't seem to work in 4.1.1. my next thought was that maybe it was a button combo or something. that was not the case.

**Describe the solution you'd like**
i feel like right clicking to change the sprite placer's selected sprite to the sprite the cursor is hovering over would flow well control wise.

**Describe alternatives you've considered**
allow the picker tool to change the sprite placer's selected sprite would be just as good.

**Comment by BinaryConstruct** [comment]
Tracked in #1273
