### ISSUE TITLE
Error when attempting to run

### ISSUE THREAD

**Issue by xZeroX13** [TEdit/Terraria-Map-Editor#1432]
**Describe the bug**
"TEdit has stopped working" (see screenshots and additional context.)

**To Reproduce**
Attempt to open program.

**Expected behavior**
Program should open.

**Screenshots**
![tedit error](https://user-images.githubusercontent.com/73309670/96915176-f0485980-1473-11eb-8a1b-d6ab90c2317b.JPG)
![tedit error 2](https://user-images.githubusercontent.com/73309670/96915706-96945f00-1474-11eb-80c1-23461d99b2b5.JPG)

**Desktop (please complete the following information):**
 - OS: Window 7 x64 Ultimate
 - Version: TEdit 4.1.2 & TEdit 4.1.1
 - Terraria Version: 1.4.1

**Additional context**
Repaired .net Framework; already using 4.8 - performed repair of files, restarted PC, error persists.
Running DirectX 11 up to date.
Attempted to run as administrator; error persists.
Attempted to run in compatibility mode with every option; error persists with each change.
TEdit is not playing nice with mscorlib.

EDIT: Additionally, no log file was created.

**Comment by BinaryConstruct** [comment]
Please ensure you have unzipped tedit to a folder where it has write access, such as c:\games\tedit. TEdit does not (and should not ever) be using administrator access. My guess is this is related to it not being able to load the settings file or save the user settings file.

**Comment by xZeroX13** [comment]
Firstly, thank you for the reply.

I moved the TEdit folder to: C:\Users\<me>\Documents\My Games\Terraria\TEdit412
Also provided full control to all users in the security tab of the folder's properties, and disabled read-only access.
![tedit properties](https://user-images.githubusercontent.com/73309670/97062174-bb1d3380-1567-11eb-9af6-0957d047b6c5.JPG)
![tedit security](https://user-images.githubusercontent.com/73309670/97062291-47c7f180-1568-11eb-8253-6b9bfb342a8a.JPG)

I'm receiving the same error when opening TEdit.
This folder was a fresh download from here, I've never updated the program, just replaced the old one completely.

**Comment by xZeroX13** [comment]
Additionally, these are the complete contents of the TEdit folder, is there anything missing?
![tedit contents](https://user-images.githubusercontent.com/73309670/97062614-afcb0780-1569-11eb-9140-80862964ec1d.JPG)

**Comment by xZeroX13** [comment]
Woo! I changed the permissions and read-only setting in the Terraria folder in my Steam directory, and moved the TEdit folder to the same folder with Terraria.exe - no more error message, took a few seconds, but now it's running!

Although it did ask if I wanted to update, what I was running an older version of TEdit, is that normal?

**Comment by BinaryConstruct** [comment]
Changing permission on the Terraria folder is something I had not considered. I think this tip may allow me to make some code change to fix this issue, or at least provide a dialogue box with info on how to fix. Thanks!

**Comment by xZeroX13** [comment]
Oh no problem! I'm not sure if that helped fix the issue, but, glad I could help :)

Btw;
![world edit](https://user-images.githubusercontent.com/73309670/97068133-c20d6b80-1592-11eb-8a26-c1f830ea44e2.JPG)

I can't see anything...

**Comment by xZeroX13** [comment]
Saw post #1434 - I'll try 4.1.3

**Comment by BinaryConstruct** [comment]
There are a few things to try

1. Deleting TEdit settings cache in LOCAL
1. Deleting the TEdit folder and unzipping a fresh copy
1. Ensure TEdit has WRITE access to it's own folder and READ access to Terraria folder

**Comment by xZeroX13** [comment]
Everything working perfectly now, thank you!
