### ISSUE TITLE
World no longer loads in latest version

### ISSUE THREAD

**Issue by bobasaurus** [TEdit/Terraria-Map-Editor#1433]
The latest version 4.1.2 no longer loads my world properly, which worked fine in 4.0.0-beta33.  I've attached the world file.  It seems to finish loading, but nothing is displayed except for the NPC sprites, unless I zoom in greatly then the tile sprites show up.  

I'm running Terraria 1.4.1.

**Comment by bobasaurus** [comment]
[Mewville.zip](https://github.com/TEdit/Terraria-Map-Editor/files/5426972/Mewville.zip)

Oops, forgot the attachment.  Here it is.

**Comment by BinaryConstruct** [comment]
Thank you for attaching a world file. Could you please try version 4.1.3? I was able to load the world with this version.

![image](https://user-images.githubusercontent.com/456755/96953461-b77da400-14b6-11eb-8225-26a2a9f9245b.png)

**Comment by BinaryConstruct** [comment]
On a side note, there is an issue with the underlying monogame framework where it will not render if the window crosses monitor borders.

**Comment by bobasaurus** [comment]
I just downloaded and tried 4.1.3, but the error is still happening.  The NPCs show up, but no tiles:

![badwindow](https://user-images.githubusercontent.com/450407/97097094-2c291d80-1632-11eb-9c13-4ac1dad9c493.PNG)

But it still loads fine in 4.0.0-beta33:

![goodwindow](https://user-images.githubusercontent.com/450407/97097103-42cf7480-1632-11eb-8f4c-df841cc3d225.PNG)

**Comment by bobasaurus** [comment]
I only have a single monitor, 2560x1440 resolution.  I'm not running any other games/programs simultaneously except for firefox.  I'm on the latest updated version of Windows 10 x64.  Maybe some problem with monogame rendering conflicting with something else installed on my machine (I have many steam games installed)?  But then why is it still working in the old 4.0.0-beta33?

**Comment by BinaryConstruct** [comment]
The only major difference between beta33 and 4.1+ is it switches from Terraria 1.4.0.X to Terraria 1.4.1.1+.

**Comment by BinaryConstruct** [comment]
Could you please try deleting the folders listed here?
https://github.com/TEdit/Terraria-Map-Editor/wiki/Troubleshooting#application-launch-or-map-loading-issue

This has resolved a similar issue with many other people.
