### ISSUE TITLE
Setting the rain-related world settings causes Terraria to hang on loading world.

### ISSUE THREAD

**Issue by Kwonunn** [TEdit/Terraria-Map-Editor#1435]
[rainworld.zip](https://github.com/TEdit/Terraria-Map-Editor/files/5430369/rainworld.zip)

I loaded the world in Terraria after having set the world rain info to the settings found in the world file. The game hung, with the music still playing. It seems Terraria was running into something while first loading the world.

### What version of Terraria are you using?
1.4.1.1

**Comment by BinaryConstruct** [comment]
Very interesting. It does indeed seem this file causes Terraria to crash. I have tracked this to the "MaxRain" parameter. It only accepts 0 and 1 from what I can tell, so I will switch it to a checkbox. MaxRain makes the world _always_ rain.
