### ISSUE TITLE
Black screen after rendering is done

### ISSUE THREAD

**Issue by METABYTECODE** [TEdit/Terraria-Map-Editor#1436]
![image](https://user-images.githubusercontent.com/62258232/97058318-2120af80-1596-11eb-8297-15fde1b82052.png)

**Comment by METABYTECODE** [comment]
10-24-2020 01:17:06: Starting TEdit 4.1.3.0 
10-24-2020 01:17:06: OS: Microsoft Windows NT 10.0.19041.0 
10-24-2020 01:17:06: OS Name: Microsoft Windows 10 Pro  
10-24-2020 01:17:06: .NET Framework Version: 4.8 or later 
10-24-2020 01:17:06: Terraria v1.4.1.1 
10-24-2020 01:17:06: Terraria Data Path: D:\Program Files (x86)\Steam\steamapps\common\Terraria\Content 
10-24-2020 01:17:07: Creating Undo cache: D:\Users\novva\AppData\Roaming\TEdit\undo_302205913 
10-24-2020 01:17:21: Error - Ссылка на объект не указывает на экземпляр объекта.
   в TEdit.ViewModel.WorldViewModel.<>c__DisplayClass376_0.<LoadWorld>b__3(Task`1 t)

**Comment by BinaryConstruct** [comment]
Thank you for the report, I will investigate.

**Comment by xPXpanD** [comment]
Getting the same, same log output as well. (though in English, "Object reference not set to an instance of an object.")

Zooming in far enough appears to make proper textures show up, but if you go out one tick too far (or turn off textures) everything disappears. NPC sprites show up.

**Comment by BinaryConstruct** [comment]
Please try https://github.com/TEdit/Terraria-Map-Editor/releases/tag/4.2.0

**Comment by xPXpanD** [comment]
Same issue, it seems. Same log output as well:

> 10-26-2020 09:50:37: Starting TEdit 4.2.0.0 
> 10-26-2020 09:50:37: OS: Microsoft Windows NT 10.0.19041.0 
> 10-26-2020 09:50:37: OS Name: Microsoft Windows 10 Pro  
> 10-26-2020 09:50:37: .NET Framework Version: 4.8 or later 
> 10-26-2020 09:50:37: Terraria v1.4.1.1 
> 10-26-2020 09:50:37: Terraria Data Path: D:\Steam\steamapps\common\terraria\Content 
> 10-26-2020 09:50:40: Creating Undo cache: C:\Users\[user]\AppData\Roaming\TEdit\undo_305010799 
> 10-26-2020 09:51:15: Error - Object reference not set to an instance of an object.
>    at TEdit.ViewModel.WorldViewModel.<>c__DisplayClass376_0.<LoadWorld>b__3(Task`1 t)

**Comment by goofri** [comment]
I have same issue on 4.1.3 and 4.2.0 . Currently using 4.0.0 beta33 it seems works fine with Terraria v1.4.1.1

**Comment by BinaryConstruct** [comment]
This issue seems to come from TEdit not having access to either the folder it is in or having access to the Terraria game folder.

**Comment by xPXpanD** [comment]
For what it's worth, I tried running it from both a folder directly on my C: drive (user-created, no specific permissions set) and from a folder within the Terraria install folder itself.

**Comment by goofri** [comment]
Found a workaround just enable telemetry.

**Comment by BinaryConstruct** [comment]
> Found a workaround just enable telemetry.

This should be resolved with v4.2.2
