### ISSUE TITLE
Worlds do not save

### ISSUE THREAD

**Issue by CaptainCrazeh** [TEdit/Terraria-Map-Editor#1437]
I recently updated to TEdit 4.1.3, because my previous version started crashing every time on startup.

The "save" and "save as" features don't seem to work properly.
When I click "save", the world isn't updated. When I click "save-as", no new files are created (even though I named it and clicked "save" in the save-as window)

I don't know what I'm doing wrong here...

**Comment by Smeef420** [comment]
I'm having the exact same issue. Can't save at all. I also can't see the rendered map unless i'm at a specific zoom level.

**Comment by BinaryConstruct** [comment]
Could you please try TEdit 4.2.1 and let me know if that is any better?

**Comment by CaptainCrazeh** [comment]
Nope, 4.2.1 has the same problem. Maps don't render unless zoomed in, and the saving feature is broken.

**Comment by BinaryConstruct** [comment]
I just pushed another update to fix an issue with telemetry disabled breaking some things. Could you please try https://github.com/TEdit/Terraria-Map-Editor/releases/tag/4.2.2

**Comment by CaptainCrazeh** [comment]
YES. Version 4.2.2 indeed works. The zoom/render and save issues aren't present in this version. Success!

**Comment by BinaryConstruct** [comment]
Could you try editing some tiles to see if those save?

**Comment by CaptainCrazeh** [comment]
YES. I placed some silver ore near spawn and re-named the Princess. I don't know what I did, but the changes were saved.
It works!

**Comment by BinaryConstruct** [comment]
Great!
