### ISSUE TITLE
Terraria GOG

### ISSUE THREAD

**Issue by Jimmy2048** [TEdit/Terraria-Map-Editor#1438]
so i have the gog version of terraria and i get this
10-26-2020 19:03:43: Starting TEdit 4.2.0.0 
10-26-2020 19:03:43: OS: Microsoft Windows NT 6.3.9600.0 
10-26-2020 19:03:43: OS Name: Microsoft Windows 8.1 Pro  
10-26-2020 19:03:43: .NET Framework Version: 4.8 or later 
10-26-2020 19:03:43: Unable to locate Terraria. No texture data will be available. 
10-26-2020 19:03:43: Creating Undo cache: C:\Users\[user]\AppData\Roaming\TEdit\undo_970956668 

here is settings.xml

[settings.zip](https://github.com/TEdit/Terraria-Map-Editor/files/5441825/settings.zip)

please tell me why this happens

**Comment by BinaryConstruct** [comment]
See instructions here - https://github.com/TEdit/Terraria-Map-Editor/wiki/Install-Requirements#for-sprite-viewing

You can uncomment this line to test:
![image](https://user-images.githubusercontent.com/456755/97249247-7ac0ee00-17d1-11eb-95ee-955553319720.png)

After:
![image](https://user-images.githubusercontent.com/456755/97249305-91ffdb80-17d1-11eb-9071-89e7d95a52bf.png)

**Comment by Jimmy2048** [comment]
ok thank you
