### ISSUE TITLE
Please upload version Beta27 - accidently deleted mine. (or allow textures to render at lower zoom levels)

### ISSUE THREAD

**Issue by RobotMan73** [TEdit/Terraria-Map-Editor#1439]
**Is your feature request related to a problem? Please describe.**
So back when beta28 was first released, I submitted a bug report stating that the textures were requiring an additional step in zoom level to be rendered. You advised that it was intended but would maybe implement an option in the future to give users the choice. I have since been using beta27 99% of the time, but just now accidently deleted it when I was removing another version. Looks like beta27 was recently removed from GitHub.

**Describe the solution you'd like**
Could you please submit beta27 to be downloaded if you still have it? Or send me a copy?

**Describe alternatives you've considered**
Maybe you could help me figure out how to edit TEdit myself so that textures render at a lower zoom level? When viewing TEdit.exe through dnSpy, I found an area that I think may be where the edit would be needed.

Going to TEdit.View -> WorldRenderXna -> DrawTileTextures
there is a line: "if (visibleBounds.Height * visibleBounds.Width < 20000)"
But there are a bunch of compile errors (before any edits) and I don't know how to get dnSpy to ignore them and allow me to save any edits and test to see if changing that number works or not. Not sure if "ignoring" them is even possible for it to be compiled, or really, what compiling even is.

**Additional context**

**Comment by BinaryConstruct** [comment]
Are you still using Terraria 1.4.0.5? I will add this option in the next release, but it will only be compatible with 1.4.1.1

**Comment by RobotMan73** [comment]
No i'm using Terraria 1.4.1.1. That would be sweet though, thank you! I'm kind of surprised that I've been the only one talking about this. What's funny, even before beta 28, i was wanting textures to render at an even lower level of zoom. I appreciate you accommodating the only person who seems to want this :)
