### ISSUE TITLE
World not loading in.

### ISSUE THREAD

**Issue by SethMeth** [TEdit/Terraria-Map-Editor#1440]
So when i download TEdit everything was going fine. Then when i opened it i got this message

https://gyazo.com/c703102f5e2290217e37ca0fe737c6b3

I thought nothing happened but it didnt let me load the world and i got this message

https://gyazo.com/7de30a664d515bf0920ee3d3041b6f8b

i was using version 4.2.1 please tell me what is happening

**Comment by BinaryConstruct** [comment]
Can you attach the world file? It looks as though your system may not have enough memory to allocate to TEdit, for large worlds up to 8GB may be needed.

**Comment by SethMeth** [comment]
It does not let me attach the world file because this file type isn't supported

**Comment by BinaryConstruct** [comment]
> It does not let me attach the world file because this file type isn't supported
It should work as a zip.
