### ISSUE TITLE
Worlds become unknown worlds after saving

### ISSUE THREAD

**Issue by neutron116** [TEdit/Terraria-Map-Editor#1441]
I've recently updated to the 4.2.1 version since 4.1.3 wouldn't load worlds properly. Although they load properly now, everytime I save, it would appear in the terraria world selection menu as a unknown world, and then it would tell me to load a backup, which doesn't include the edit changes. Could you please fix this?

**Comment by BinaryConstruct** [comment]
Could you please post the version of Terraria you are using? Thanks.

**Comment by BinaryConstruct** [comment]
Additionally, could you post a zip of 2 files, one of a world file that works before editing and a copy of the same world that does not work after editing so I can compare the format? Thanks.

**Comment by LJoacks** [comment]
this also happened to me, i had the latest version of Terraria and the latest version of TEdit and when i opened the world and later saved it and closed it it became an unknown world and also told me that only non-journey characters may enter a non-journey word. Even thought my character was a journey and it said that the world was journey in the editor too.
