### ISSUE TITLE
How to deactivate textures?

### ISSUE THREAD

**Issue by Spickyy** [TEdit/Terraria-Map-Editor#1442]
I want to deactivate the textures of blocks because my pc really can't handle it as it a low-end one. In past versions the textures deactivated automatically but when i try to do it now nothing shows up. I really need help with this.

**Comment by RobotMan73** [comment]
Under the "Layers" menu tab, you can uncheck textures. They won't load at all if you unselect it.

**Comment by BinaryConstruct** [comment]
![image](https://user-images.githubusercontent.com/456755/97586276-11570000-19c8-11eb-8ff6-648a8da55ebe.png)
