### ISSUE TITLE
Mi mundo no se actualiza despues de los cambios

### ISSUE THREAD

**Issue by MaaxxMaster** [TEdit/Terraria-Map-Editor#1443]
**Before Submitting an Issue**
* If you are having issues loading a world, please attach it to the current version world thread (see pinned issues).
* If you get an unhandled exception or crash, please _**check your log before posting**_.
  * _Copy paste using code [block tags](https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks) into the issue as a comment_

**Describe the bug**
mi mundo no se actualiza despues de que lo edite y aparece este me4nsaje no guarda los cambios y luego cuando entro aparece que cargue una copia de seguridad

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/54819785/97577523-8c66e900-19bd-11eb-9a64-0c4d9147e4c8.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10] Windows 10
 - Version [Tedit 4 beta 9] Ultima version
 - Terraria Version [e.g. 1.4.0.4] 1.4

**Additional context**
[](url)

**Comment by BinaryConstruct** [comment]
The latest version only supports Terraria 1.4.1.1. Please see https://github.com/TEdit/Terraria-Map-Editor/releases for older versions.
