### ISSUE TITLE
NPE when telemetry is disabled

### ISSUE THREAD

**Issue by goofri** [TEdit/Terraria-Map-Editor#1444]
I debugged TEdit with dnspy a bit and found that in ErrorLogging.cs InitializeTelemetry method sets _telemetry variable to null if telemetry setting is disabled by user. This causes a lot of NPE in various places. For example WorldViewModel.cs LoadWorld ErrorLogging.TelemetryClient.TrackEvent(nameof(LoadWorld)); will fail and we receive issue described [here](https://github.com/TEdit/Terraria-Map-Editor/issues/1436)

**Comment by BinaryConstruct** [comment]
Thanks for the report. I will fix this immediately.

**Comment by BinaryConstruct** [comment]
This version fixes the issue https://github.com/TEdit/Terraria-Map-Editor/releases/tag/4.2.2
