### ISSUE TITLE
Sprite filter dont work

### ISSUE THREAD

**Issue by ViniciusGreff** [TEdit/Terraria-Map-Editor#1445]
*exemple, Plantera's bulb dont appear when searched, even dirt dont appear on sprite

**Comment by ViniciusGreff** [comment]
i wanna put plantera bulbs in my jungle but when i search into sprite filter dont appear anything

**Comment by Lungenpest** [comment]
You should check where is your Terraria Folder and write it in your settings.xml.

https://github.com/TEdit/Terraria-Map-Editor/wiki/Install-Requirements#for-sprite-viewing

My Terraria folder is here:

![image](https://user-images.githubusercontent.com/64774660/97721574-85c19a00-1ac1-11eb-8fc3-31b015ac0c37.png)

So in need to edit the settings.xml of TEdit:

![image](https://user-images.githubusercontent.com/64774660/97721795-cfaa8000-1ac1-11eb-913d-546da6b96749.png)

I hope this helps for you

**Comment by BinaryConstruct** [comment]
@Lungenpest thanks for the screenshots, I hope you don't mind me using them here: https://github.com/TEdit/Terraria-Map-Editor/wiki/Install-Requirements
