### ISSUE TITLE
Textures don't show and sprites don't work

### ISSUE THREAD

**Issue by Miguel4387** [TEdit/Terraria-Map-Editor#1448]
### When I zoom in, textures are suposed to show, well, they don't, and the sprites don't work either.

 I'm using TEdit 4.0.0 and terraria 1.4.1.

I've been trying to fix it for a while, I've seen people with similar problems that have been fixed but when I try to fix them it doesn't work, please help.

This is how it shows up. (As you can see in the image I have textures turned on so that can't be it, right?)
![image](https://user-images.githubusercontent.com/73842824/97891895-a858ea80-1d2f-11eb-859e-d7d6686353ce.png)

**Comment by BinaryConstruct** [comment]
Check out the tips here: https://github.com/TEdit/Terraria-Map-Editor/wiki/Install-Requirements#for-sprite-viewing

**Comment by simonstackhub** [comment]
You need to have Terraria installed in the default Steam directory. External drives won't work.

**Comment by eliximinatus** [comment]
Is there no way without steam?

**Comment by RussDev7** [comment]
> Is there no way without steam?

Try taking a look at [This Link.](https://docs.binaryconstruct.com/install-requirements#for-sprite-viewing) Using settings.xaml, you can change the default texture location.
