### ISSUE TITLE
Problem with my textures.

### ISSUE THREAD

**Issue by Spickyy** [TEdit/Terraria-Map-Editor#1449]
I already made a post about this, but the solution that was given to me didn't work. For reasons i don't know the simple textures don't load in when i zoom away or when i deactivate the textures mark, and i can't have it activated since my pc can't handle it. Also i had to use the 4.1.2 version because the most recent one wasn't letting me load my world no matter how many times i tried. Please help i desperatly need to do something in my world.

![Captura](https://user-images.githubusercontent.com/73608914/98503394-c7bdaf00-222a-11eb-96b2-3596a390a4bd.PNG)

**Comment by BinaryConstruct** [comment]
Version 4.1.2 is no longer supported.

If you attach your world file as a zip I can take a look and see if I there is something I can do to get it to load. Please ensure you are using the latest version of Terraria as well.

**Comment by BinaryConstruct** [comment]
Also, please try deleting the folders listed here:

https://github.com/TEdit/Terraria-Map-Editor/wiki/Troubleshooting#application-launch-or-map-loading-issue

**Comment by Spickyy** [comment]
> Version 4.1.2 is no longer supported.
> 
> If you attach your world file as a zip I can take a look and see if I there is something I can do to get it to load. Please ensure you are using the latest version of Terraria as well.

Sure, here it is. 
[The_Ass_Whooping_Experience .zip](https://github.com/TEdit/Terraria-Map-Editor/files/5513960/The_Ass_Whooping_Experience.zip)

**Comment by Spickyy** [comment]
> Version 4.1.2 is no longer supported.
> 
> If you attach your world file as a zip I can take a look and see if I there is something I can do to get it to load. Please ensure you are using the latest version of Terraria as well.

And also, here is the error s

**Comment by Bluejey** [comment]
I have a problem with textures to, all tho the texture setting is clicked the textures dont show up on the screen and its just square plain boxes
![photo](https://user-images.githubusercontent.com/75180345/100523800-e07f0c00-31bb-11eb-8ac7-01d282ce3bd2.png)

**Comment by BinaryConstruct** [comment]
@Bluejey it looks like you have the slider for texture visibility set all the way to maximum zoom in. Try setting it to 6. Also see the wiki for texture settings if you are not using Steam.
