### ISSUE TITLE
Change zooming while viewing world

### ISSUE THREAD

**Issue by ernieIzde8ski** [TEdit/Terraria-Map-Editor#1451]
**Is your feature request related to a problem? Please describe.**
I'm used to using ctrl+scroll to zoom, scroll to zoom to navigate pages, so it became frustrating to work with the scroll button on the sidebar.

**Describe the solution you'd like**
Change the scrolling to use the following combinations:
- ctrl+scroll adjusts zoom
- scroll wheel adjust the vertical scrolling
- shift+scroll adjusts the horizontal scrolling

**Comment by BinaryConstruct** [comment]
Some shortcut keys are customizable in the config xml file.
