### ISSUE TITLE
Wo/Mannequins Don't Display Correctly

### ISSUE THREAD

**Issue by BadScientist** [TEdit/Terraria-Map-Editor#1459]
In TEdit version 4.2.2, mannequins and womannequins don't display properly (only the base can be seen) and the inputs and dropdowns for them in the Special Tiles tab overlap each other in the first line.

1. Open TEdit v4.2.2
2. Create a new world or open an existing one.
3. Place a mannequin or womannequin with the sprite placer tool.
4. Right click the placed mannequin or womannequin with the arrow tool.

**Expected behavior**
The full sprite should be displayed and inputs should not overlap.

**Screenshots**
![image](https://user-images.githubusercontent.com/29133943/102142412-faf5ee00-3e27-11eb-99e7-b82d33df57d6.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version Tedit v4.2.2
 - Terraria Version N/A

**Comment by RussDev7** [comment]
This is no longer an issue in TE5.
