### ISSUE TITLE
Cant load sprites to place.

### ISSUE THREAD

**Issue by TheConfusedlol** [TEdit/Terraria-Map-Editor#1460]
Bug:  Cant select sprites to place with Sprite Placer.

To reproduce: Open up sprites in the Utilities tab and try to search up any sprite
 
Expected Behavior: I expected to never be able to place sprites. 
![bug](https://user-images.githubusercontent.com/69022214/103122063-be5a9b80-464c-11eb-8ad8-0f59c717f171.JPG)

Info: OS: Windows 10. 
Version:  4.2.3
Terraria Version:  1.4.1.2

**Comment by BinaryConstruct** [comment]
Please see https://github.com/TEdit/Terraria-Map-Editor/wiki/Install-Requirements#for-sprite-viewing
