### ISSUE TITLE
TEdit 4.2.3 won't open

### ISSUE THREAD

**Issue by tanarUNDERSCORE** [TEdit/Terraria-Map-Editor#1461]
When I go to open TEdit, it is in my downloads folder, it pulls up the splash screen and then it disappears and nothing happens. I try opening it as administrator, still the same thing happens. I have task manager up, TEdit pops up and then it says on the status that it is suspended. I have looked at its properties and it has write access so I don't know what to do now.
OS: Windows 10
Version: TEdit 4.2.3
Terraria Version: 1.4.1

**Comment by BinaryConstruct** [comment]
Please see https://github.com/TEdit/Terraria-Map-Editor/wiki/Troubleshooting#general-troubleshooting
