### ISSUE TITLE
No Sprites on the Sprite Tab 

### ISSUE THREAD

**Issue by marvelgill3** [TEdit/Terraria-Map-Editor#1463]
**Describe the bug**
The Sprites tab is not displaying any sprites so therefore I am unable to place chests, doors, etc
**To Reproduce**
1. Go to 'TEedit'
2. Click on 'Sprites Tab'
3. See error

Screenshot
![Capture](https://user-images.githubusercontent.com/76768185/103336021-ba5ecb80-4adb-11eb-9ad0-285cca024dc7.PNG)

Computer Info
 - OS: Windows 10
 - Version TEedit 4.2.3
 - Terraria Version 1.4.1.2
 - 64-bit Operating

**Comment by BinaryConstruct** [comment]
Please see https://github.com/TEdit/Terraria-Map-Editor/wiki/Install-Requirements#for-sprite-viewing
