### ISSUE TITLE
<Bug> Not Loading at all

### ISSUE THREAD

**Issue by kmaz121** [TEdit/Terraria-Map-Editor#1464]
**Describe the bug**
When going to open TEdit, it doesn't open at all. I get the little logo pop up, but that's it.

**To Reproduce**
Double Click on Exe.
Nothing happens.

**Expected behavior**
It to load.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 4.23
 - Terraria Version 1.4.1.2

**Additional context**
Not sure what I might have done wrong. I downloaded TEdit from the link on the forum, but after running the .exe it just shows the logo for a couple seconds, shows its loading, and then closes :(

**Comment by BinaryConstruct** [comment]
Please see the tips on https://github.com/TEdit/Terraria-Map-Editor/wiki/Install-Requirements and https://github.com/TEdit/Terraria-Map-Editor/wiki/Troubleshooting#application-launch-or-map-loading-issue
