### ISSUE TITLE
It still doesn't work even after trying that

### ISSUE THREAD

**Issue by marvelgill3** [TEdit/Terraria-Map-Editor#1466]
My sprites don't come up in the tab and i've tried editing the settings.xml file.

**Comment by BinaryConstruct** [comment]
Check the log file from the file menu in TEdit. It may give you some direction.

**Comment by marvelgill3** [comment]
> Check the log file from the file menu in TEdit. It may give you some direction.

it says unable to locate terraria so how do I fix it

**Comment by BinaryConstruct** [comment]
You have to edit the settings file to point to the correct location.
