### ISSUE TITLE
it just crashes and doesnt start at all

### ISSUE THREAD

**Issue by matijoss** [TEdit/Terraria-Map-Editor#1468]
**Describe the bug**
as soon as I start it, it just doesn't work. In the task manager, I see the program starts, then suspends a few times, and then just crashes. It still creates the log file, yet the file is empty with no logs. Tried everything both on the troubleshooting and install requirements page. I have no idea what's happening.

**To Reproduce**
TEdit version: 4.2.3 (zip)
Terraria version: 1.4.1.2 (steam)
Location: C:\Program Files (x86)\Steam\steamapps\common\Terraria\Content (yes i did set it in settings.xml on line 115)
newest DotNet framework version (4.8)
DirectX 12

**Expected behavior**
To work (what kind of question is this)

**Screenshots**

**Desktop (please complete the following information):**
already said in the "**to reproduce**" section

**Additional context**
I don't know what else to say.

**Comment by Goddhoward** [comment]
Does it say the current world 234, the current max 233

**Comment by BinaryConstruct** [comment]
By everything I'm assuming you mean you have:

1. Delete any old folder you have unzipped TEdit into and download a fresh copy from releases.
1. Unzip the download to a clean folder with write access, such as `c:\games\TEdit4.2.3`
1. Delete the cache folder `%appdata%\tedit`
1. Delete the settings folder `%localappdata%\tedit`
1. Unzip the new download into an empty folder, such as `c:\games\tedit`.
1. Make sure that your `setting.xml` file is correctly formatted or use one from the zip file without modification.

**Comment by matijoss** [comment]
Goddhoward it just doesn't start. doesn't go past the TE4 screen

BinaryConstruct
1. yes
2. yes
3. no cache folder was created
4. no settings folder was created (only an empty log folder)
5. yes
6. I'm not quite sure what you mean by "correctly formatted", but i did try using the settings.xml file without modification, and then changed line 115 to point to my terraria folder.

**Comment by BinaryConstruct** [comment]
You might try event viewer to see if there are any application issues when you try to start TEdit.

![image](https://user-images.githubusercontent.com/456755/104058425-501fe800-51b9-11eb-91c1-7a09d1de4e49.png)

![image](https://user-images.githubusercontent.com/456755/104058444-5a41e680-51b9-11eb-91b4-97c900875efb.png)

**Comment by matijoss** [comment]
Opened event viewer and then afterwards TEdit. Nothing changed in EV. (at least i think so it is my first time using Event Viewer, in the table there was nothing new, and also i did go to the application section under windows logs)
![image](https://user-images.githubusercontent.com/77113726/104094713-e247ef00-5292-11eb-876e-aafda32eeae3.png)

**Comment by BinaryConstruct** [comment]
Can you list your gpu/cpu/windows version?

**Comment by BinaryConstruct** [comment]
Sometimes with an Intel+nVidia/amd gpu it will not automatically pick the better gpu and will attempt to run using the Intel Integrated graphics.

**Comment by matijoss** [comment]
Ah, i see. So my setup is as follows:
Latest Windows 10 version
GTX 1060 6GB
i5-9400F
16GB RAM

And more than enough free space for it to work.

**Comment by matijoss** [comment]
Now how do i set it to use my GPU instead of the Integrated intel one?

**Comment by BinaryConstruct** [comment]
Well, that was a dead end, the F series cpu do not have integrated graphics.

**Comment by BinaryConstruct** [comment]
Can you try this release? https://github.com/TEdit/Terraria-Map-Editor/releases/tag/4.2.4

**Comment by Goddhoward** [comment]
Binaryconstruct can you pleaseTedit to be compatible with 1.4.1.2?
I don't want to risk causing a file corruption
