### ISSUE TITLE
does not open

### ISSUE THREAD

**Issue by KillerTRM** [TEdit/Terraria-Map-Editor#1469]
I just downloaded tedit and tried to run the .exe in the folder but I get an error and I don't know how to fix it

![Untitled](https://user-images.githubusercontent.com/77172784/104061320-523c7380-51c6-11eb-85fe-8905959704da.png)

**Comment by BinaryConstruct** [comment]
Please see

https://github.com/TEdit/Terraria-Map-Editor/wiki/Install-Requirements
and 
https://github.com/TEdit/Terraria-Map-Editor/wiki/Troubleshooting
