### ISSUE TITLE
I cant use sprites like plants, pots etc

### ISSUE THREAD

**Issue by ylljon** [TEdit/Terraria-Map-Editor#1471]
So I dont know if it is in the new update or do I need to download sprites like pots, I didnt see anything in the internet about this so if someone can help that would be appreciated. And the  blocks dont have detail when u zoom in do I need to change a setting for that

**Comment by BinaryConstruct** [comment]
Please see https://github.com/TEdit/Terraria-Map-Editor/wiki/Install-Requirements#for-sprite-viewing
