### ISSUE TITLE
TEdit will show the logo, then will not start.

### ISSUE THREAD

**Issue by Spookysaw** [TEdit/Terraria-Map-Editor#1472]
I was attempting to open TEdit after several months of not using it. The only things open were Steam, Discord, and my browser (Brave). I had an older version (which I have now removed) and it no longer worked. So, I cleared my PC of that version, and all the files said to be deleted within the troubleshooting guide. I download the new TEdit version from the BinaryConstruct website (4.2.3) and extract it using WinRar. I put it both on desktop, and in the downloads folder. Neither folders worked, and the logo was shown for around ~2 seconds, and then disappeared, with TEdit not opening.  I downloaded it from Github after deleting the old one. Didn't work. I deleted the old log from August earlier, and whenever I start TEdit, none of the files that the troubleshooter recommended to delete appeared. No log either. When I start TEdit, it is in task manager background processes for as long as the logo is up there, and then deletes itself. I saw it say, "Suspended" one time. Keep in mind, this worked a few months back.
Here is everything I did, in order:
1) Download TEdit.
2.) Unzip using WinRar
3.) Open the TEdit.exe file within the folder.

I am using Terraria version 1.4.1.2. This has been going on for a few days now.

**Comment by BinaryConstruct** [comment]
Does the previous release work?

**Comment by Spookysaw** [comment]
> Does the previous release work?

A couple of months ago, yes, but now, out of the blue, no.

**Comment by Spookysaw** [comment]
> Does the previous release work?

I'm not sure if you were referring to the one I used back in around August, or 4.2.2. If you were referring to 4.2.2, that does work. I believe I am having the same issue as #1470

**Comment by BinaryConstruct** [comment]
Can you try this release? 

https://github.com/TEdit/Terraria-Map-Editor/releases/tag/4.2.4
