### ISSUE TITLE
Linux

### ISSUE THREAD

**Issue by LegendaryDirtBlock** [TEdit/Terraria-Map-Editor#1473]
So, i am a Linux user. I've been looking around for ways to make and edit maps online, as basically no editors actually work on Linux, which i have recently had to switch to. I have been using TEdit for 8 years and was extremely dissapointed when i saw no Debian versions exist. Please make one :)

**Comment by BinaryConstruct** [comment]
Unfortunately, microsoft chose not to make directX and WPF available on Linux. These are both core technologies used for the TEdit interface. You can use it with a VM on Linux.

**Comment by DraconicNEO** [comment]
> Unfortunately, microsoft chose not to make directX and WPF available on Linux. These are both core technologies used for the TEdit interface. You can use it with a VM on Linux.

A VM on linux is not a real solution to this problem, many people can't afford the overhead of running a VM just to run this dinky little program. 

A good solution might be to switch to Avalonia since it's cross platform.

**Comment by BinaryConstruct** [comment]
Avalonia is actually on the road map, there are a few technical hurdles with switching to Vulkan for the renderer, but the direction is pretty clear.
