### ISSUE TITLE
Block/Wall drop-down menu change

### ISSUE THREAD

**Issue by Nocturnes18** [TEdit/Terraria-Map-Editor#1475]
In previous versions of Tedit, I could open the block/wall drop down and type words to fast scroll to my block. The style was like this example: "blueee" Typing extra 'e' would scroll down to the 3rd block named 'Blue'. This is very fast block/wall selection when memorized.

At present time clicking on the Block/Wall name for drop-down makes it so you type into the bar, which allows for Control+V, but the fast scrolling I used is no longer available. My Tedit working speed is slightly reduced from not being able to select blocks by doing 'blueee' 'irr'

Discord user BinaryConstruct mentioned word filter, and it will work good as long as the options change instantly.

Based on everything, I think the best is to keep the new typing into the bar because it allows Control+V, and then I think click on the drop down arrow should be the old way with no text typing in the bar. This way everyone can choose between typing the word, Control+V, or doing 'irrr'.

Having my old way back is nice because it is maximum efficiency, I memorize the blocks on the list and know what I get when I type an extra letter.

**Comment by BinaryConstruct** [comment]
![image](https://user-images.githubusercontent.com/456755/106618076-c1db1f80-6534-11eb-9193-30543ed295c4.png)
