### ISSUE TITLE
TEDIT doesn't show coloured tiles/walls on feed

### ISSUE THREAD

**Issue by Bortzu** [TEdit/Terraria-Map-Editor#1477]
## Before Submitting
After downloading the latest versions of TEDIT, the program stopped showing the coloured tiles/walls
### Before 4.0
![1611793026896](https://user-images.githubusercontent.com/77899929/106394791-ba195f00-63fe-11eb-942d-894c40b674bd.png)
### After 4.0 (late versions)
![Screenshot_1](https://user-images.githubusercontent.com/77899929/106394792-bbe32280-63fe-11eb-9f52-77463bf731d9.png)

**Comment by BinaryConstruct** [comment]
By colored, are you referring to the "paint" feature?
