### ISSUE TITLE
Option to add same item with any given amount to all slots in a container

### ISSUE THREAD

**Issue by DesignerJay** [TEdit/Terraria-Map-Editor#1478]
**Is your feature request related to a problem? Please describe.**
Ability in TEdit to apply one slot's assigned contents and quantity to all others in that chest.

**Describe the solution you'd like**
Say you want to put 999 *insert item* in every slot in an empty chest. Currently, you must use the arrow tool, select the chest, then enter in each slot manually for all slots in the chest. An option to make this faster would be a time saver for so many different circumstances. Could create a popup menu that when right clicked, would give the option to "apply to all slots" for the chest menu. Or have the ability to hold the shift key and the down arrow key and select all the slots in the chest menu? 

**Describe alternatives you've considered**
N/A in this case.

**Additional context**
![image](https://user-images.githubusercontent.com/54563193/106685565-a3a60b80-6596-11eb-9f66-4d7e2ff067da.png)

Jay#0915 from discord!

**Comment by BinaryConstruct** [comment]
This will be in the next release. I also increased the stack size limit.
