### ISSUE TITLE
I can't see the sprites

### ISSUE THREAD

**Issue by JoseAV10** [TEdit/Terraria-Map-Editor#1479]
I can't see the sprites or the textures, how could I see them? my computer is considerably good so I don't think that's why.
![Captura de pantalla (1)](https://user-images.githubusercontent.com/78555947/106928452-305ce080-66e1-11eb-9580-cc237d044e88.png)

**Comment by BinaryConstruct** [comment]
Please see https://github.com/TEdit/Terraria-Map-Editor/wiki/Install-Requirements#for-sprite-viewing

**Comment by BinaryConstruct** [comment]
Also, you have to zoom in enough for them to show up.
