### ISSUE TITLE
Initial Spawn Issue via Custom Map 600 Block Width or Under

### ISSUE THREAD

**Issue by TheBambino** [TEdit/Terraria-Map-Editor#1480]
# New World bug fixes
- [x] Initial Spawn should be center of map
- [x] Creation time should be current time, not 1900-0-0 00:00

# Original Issue
**Describe the bug**
When using a custom map under 600 blocks in width & using vanilla Terraria server, or TShock for that matter, players do not initially spawn at the worlds spawn point. Instead, they spawn in the middle of the air on the very left edge of the map. Any spawns, for whatever reason, after the initial login work fine. Single player also works fine.

Would this be a client limitation?

**Steps to reproduce the behavior:**
1. Create a new custom map with a width less than 600 blocks.
2. Use the map via terrariaserver.exe
3. Connect to the server hosting the map.
4. When you first spawn in you will experience this issue.

**Expected behavior**
On initial spawn, should spawn at the maps spawn point.

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Version: [TEdit4.2.7]
 - Terraria Version: [1.4.1.2]

**Comment by BinaryConstruct** [comment]
Thanks for this. I added another issue I noticed and I'll work on them together. Expect a fix in the next release.
