### ISSUE TITLE
Mac Support?

### ISSUE THREAD

**Issue by GhostieSpook** [TEdit/Terraria-Map-Editor#1481]
Is it possible to run on mac even? If not that would be cool if you could. I wanna get into map making, but don't have another computer.

**Comment by BinaryConstruct** [comment]
https://github.com/TEdit/Terraria-Map-Editor/wiki#linux-mac-dont-want-to-download-files

**Comment by GhostieSpook** [comment]
Thank you kindly.

**Comment by BinaryConstruct** [comment]
Sure thing!

**Comment by antandpets** [comment]
hi, did you get it working? if so could you tell me how, i cant get it working, thanks

**Comment by BinaryConstruct** [comment]
Mac support is not present, but boot camp or a windows virtual should work.

**Comment by antandpets** [comment]
Do you know how I would install boot camp or windows virtual? if possible could you provide a link to download, thanks :)

**Comment by BinaryConstruct** [comment]
https://kb.parallels.com/4729
