### ISSUE TITLE
TEdit cant open the only save

### ISSUE THREAD

**Issue by max79083** [TEdit/Terraria-Map-Editor#1482]
This archive was can be open in TEdit but failure to open now.
I use the seed,05162020.
The loot frame of The Corruption Wall,the treasure monster....all of features shows the world was corruption ,but those characteristics are now translated into bloody.I don't know if this have something contact with my issue.
And my "TEditLog.txt" are following:
[TEditLog.txt](https://github.com/TEdit/Terraria-Map-Editor/files/6000181/TEditLog.txt)
Thanks very much!

**Comment by BinaryConstruct** [comment]
Can you attach a .zip of your world .wld file and world file .bak?

**Comment by max79083** [comment]
this?
[worlds.zip](https://github.com/TEdit/Terraria-Map-Editor/files/6006879/worlds.zip)

**Comment by BinaryConstruct** [comment]
I couldn't find anything wrong with these files. I do know that the seed `05162020` usually has `crimson` and `corruption` on it.

**Comment by BinaryConstruct** [comment]
Are you still having issues?

**Comment by max79083** [comment]
![4115115](https://user-images.githubusercontent.com/78890100/108944926-a88e4480-7696-11eb-8ea8-04d5dabdf62d.png)
Not yet...it seems a little intractable...

**Comment by BinaryConstruct** [comment]
This is a very old version, can you please update to the latest version on https://github.com/TEdit/Terraria-Map-Editor/releases

**Comment by max79083** [comment]
It solved!Thanks!

**Comment by BinaryConstruct** [comment]
Great!

**Comment by max79083** [comment]
Some things are just so amazing that it's easy to see them from the outside,but those closely involved cannot see clearly XD
