### ISSUE TITLE
Additional worldfile documentation

### ISSUE THREAD

**Issue by Broken-Admin** [TEdit/Terraria-Map-Editor#1483]
**Is your feature request related to a problem? Please describe.**
Per this project being impossible to port to the Linux platform it would be greatly appreciated to have further documentation of the format of world, possibly for the development of a Linux-specific version in the future.

**Describe the solution you'd like**
Possibly an MD or textfile which documents the bytesize of the file's properties, possibly even the types.

**Describe alternatives you've considered**
Although it is understandable the possibility to run this program via WINE, it would be much preferred to have a native Linux program to modify or at least view files in the future.

**Additional context**
If provided information I would be happy to contribute in any way possible, although I am not a fluent C# programmer.

**Comment by BinaryConstruct** [comment]
Unfortunately the core library for rendering (directx) and the ui (wpf) are not supposed on Linux. However see https://github.com/TEdit/Terraria-Map-Editor/wiki#linux-mac-dont-want-to-download-files

**Comment by Broken-Admin** [comment]
I believe you're missing my point in which this issue is asking about additional documentation rather than an implementation by yourself.

I would rather like to implement it myself if you do not believe it is within the scope of this project to port to other operating systems.

However I believe it would swiftly improve the speed at which a port can be done if I had supplementary information about the save file layout.

TD;DR, please provide documentation about the order of save files so that others may work with them.

**Comment by Broken-Admin** [comment]
Additionally the "online editor" you've linked is outdated; I wanted to purely make it rain in my save, and instead I received a Goblin army event.

**Comment by BinaryConstruct** [comment]
There are numerous sources for the save file documented already, I would suggest using one of those. This one is a bit outdated but might get you started! http://ludwig.schafer.free.fr/ The format has not changed much from 1.3 to 1.4.

**Comment by Broken-Admin** [comment]
All's well, I certainly appreciate your help. I was looking over your LoadV2 and LoadV1 function headers, although I couldn't conclusively understand due to my lack of experience in C#.
Possibly expect a PR with documentation in the future, hope to see this project keep on rocking.
