### ISSUE TITLE
Help Me, I Cant see Textures which requirements for it

### ISSUE THREAD

**Issue by TerrraBoy** [TEdit/Terraria-Map-Editor#1484]
![Screenshot (128)](https://user-images.githubusercontent.com/79494816/108799174-a0120d00-75b5-11eb-8b8c-5bf8f143bda5.png)
****

**Comment by BinaryConstruct** [comment]
Please see https://github.com/TEdit/Terraria-Map-Editor/wiki/Install-Requirements#for-sprite-viewing
