### ISSUE TITLE
Dog and Cat sprites not showing up properly

### ISSUE THREAD

**Issue by ZWORX52** [TEdit/Terraria-Map-Editor#1487]
### What were you doing when the issue occurred?

TEdit things, in a world where a dog and cat had moved in

### Steps to reproduce the issue?
1) Take any world (you might need to make a new one) and get a dog or cat ingame (it might not show up if you place one with TEdit)
2) Open the world with TEdit
3) Observe as the dog does this (down) and the cat, less noticeably but you can see the top of its head.
![image](https://user-images.githubusercontent.com/66217856/110655252-e312d980-818c-11eb-9377-3f030dff5fb3.png)

### What version of Terraria are you using?
1.4.1.2

### Post relevant contents of log or attach log file _**(very important)**_:
03-10-2021 09:50:43: Starting TEdit 4.2.7.0 
03-10-2021 09:50:43: OS: Microsoft Windows NT 10.0.19042.0 
03-10-2021 09:50:43: OS Name: Microsoft Windows 10 Home  
03-10-2021 09:50:43: .NET Framework Version: 4.8 or later 
03-10-2021 09:50:43: Terraria v1.4.1.2 
03-10-2021 09:50:43: Terraria Data Path: C:\Program Files (x86)\Steam\steamapps\common\Terraria\Content 
03-10-2021 09:50:44: Creating Undo cache: C:\Users\[user]\AppData\Roaming\TEdit\undo\undo_20210310095044 
I don't think any of it is relevant...

### Possible fix
Add an exception to the sprite drawing so that it properly draws abnormally sized sprites

### Other comments
what did I just witness o_O

**Comment by BinaryConstruct** [comment]
Thank you for the report. This looks similar to the bunny issue reported a while back.
