### ISSUE TITLE
Textures do not show up, i have textures enabled, and already wrote the directory for my custom directory installation

### ISSUE THREAD

**Issue by FishyBusinessYT** [TEdit/Terraria-Map-Editor#1490]
I had Just installed TEdit and there were no textures. From the beginning.
I don't know how you could reproduce the issue, I just unzipped TEdit and it never ever worked...
I'm on Terraria 1.4.1.2, and TEdit 4.2.7
I also don't know where to find the log... I will attach it once I find out.

World File:
[TEdit Test World.zip](https://github.com/TEdit/Terraria-Map-Editor/files/6171790/TEdit.Test.World.zip)
Settings File:
[settings.zip](https://github.com/TEdit/Terraria-Map-Editor/files/6171800/settings.zip)

**Comment by TagGamer555** [comment]
Have same issue.

**Comment by BinaryConstruct** [comment]
Please read https://docs.binaryconstruct.com/install-requirements#for-sprite-viewing
