### ISSUE TITLE
Can't open edited world on TModLoader

### ISSUE THREAD

**Issue by UpsidePlayz** [TEdit/Terraria-Map-Editor#1492]
I am not using any mods that add new blocks to the game, neither are there any modded tiles in the world I'm trying to make. I have seen people use TEdit on 1.3.5.3 worlds and have had no issues. I'm just trying to create an empty world with no tiles, but it always changes the world's version to 1.4. Is there some kind of way to change the world's version? Also, I can't even attach the world file since github doesn't support .wld files.

**Comment by BinaryConstruct** [comment]
TModLoader may change the world file format to one that is not compatible with the base game and TEdit. 

You can download an older release of TEdit for 1.3.5.3, such as https://github.com/TEdit/Terraria-Map-Editor/releases/tag/3.10.18105.218

To attach a world file, you must zip it first.
