### ISSUE TITLE
Can't load world with non-standart size

### ISSUE THREAD

**Issue by Geecko16** [TEdit/Terraria-Map-Editor#1496]
**Describe the bug**:
After update world with non-standart size fails to load, crashes the Terraria

**Steps to reproduce the behavior**:
Just try to load world with any non-standart size(not small, normal or big)

**Expected behavior**:
Loading the world :P

**Desktop:**
 - Windows 10
 - Last release of TEdit
 - Terraria v1.4.2.1

**Crash log**:
[client-crashlog.txt](https://github.com/TEdit/Terraria-Map-Editor/files/6249405/client-crashlog.txt)

**Comment by Geecko16** [comment]
I tried on multiple devices btw

**Comment by BinaryConstruct** [comment]
It looks as though custom sizes are no longer supported. I'll change the UI to only support sm/md/lg

**Comment by Geecko16** [comment]
Sad :(

**Comment by BinaryConstruct** [comment]
I did manage to get them to load in the latest desktop version, but only occasionally. It seems there are some size/cave/surface level heights that don't work.

I added the standard sizes to the wiki, so if you want to try custom size worlds, start with settings near these.
https://docs.binaryconstruct.com/basics/basics#world-sizes

**Comment by Geecko16** [comment]
Thanks!
