### ISSUE TITLE
I can`t launch TEdit, it always crushing

### ISSUE THREAD

**Issue by quadrya** [TEdit/Terraria-Map-Editor#1497]
I was trying to launch it for hundreds times, installed different versions, re-installed terraria. There's no even crush logs!

**Comment by quadrya** [comment]
actually, trying to launch TEdit 3.10 made me see error log and here it is (it`s on russian language but i`m sure you can put it in translator)
[TEditLog.txt](https://github.com/TEdit/Terraria-Map-Editor/files/6254152/TEditLog.txt)

**Comment by ReconditeDeity** [comment]
Did you run the installer or are you using a zipped version?

**Comment by quadrya** [comment]
> Did you run the installer or are you using a zipped version?

I am using unzipped version ofc. I followed all the install instructions

**Comment by ReconditeDeity** [comment]
04-04-2021 12:07:58: Starting TEdit 3.10.18105.2203 
Does the newest version work? It looks like you're trying to run a version from 4 years ago. The latest version can be found here: https://github.com/TEdit/Terraria-Map-Editor/releases/tag/4.2.7

**Comment by ReconditeDeity** [comment]
Is there a reason you need to use version 3.10?

**Comment by BinaryConstruct** [comment]
It looks as though the requirements are not met. Please see https://docs.binaryconstruct.com/install-requirements
