### ISSUE TITLE
sprites don't work

### ISSUE THREAD

**Issue by endecraft** [TEdit/Terraria-Map-Editor#1499]
I want to edit a world of mine using sprites, but when I go to the sprites tab it appears empty, even when I search for something, I use version 4.2.7 of the program and 1.4.1.2 of terraria

![image](https://user-images.githubusercontent.com/77405629/113874644-63c4f580-978c-11eb-9e8a-39c97dfbcccd.png)
![image](https://user-images.githubusercontent.com/77405629/113874993-b56d8000-978c-11eb-9f74-577c9ed0e15a.png)

I don't know if I'm doing something wrong or what, but I looked at videos and saw that they only put the sprites tab and everything appeared

**Comment by BinaryConstruct** [comment]
Please read https://docs.binaryconstruct.com/install-requirements#for-sprite-viewing

**Comment by endecraft** [comment]
Thank you so much!!
