### ISSUE TITLE
Settle Sand should also settle all other gravity affected blocks (Slit/Slush)

### ISSUE THREAD

**Issue by VedaantAchuthan** [TEdit/Terraria-Map-Editor#1501]
Was trying to create a seafloor made of sand and silt, however contrary to expectations, sand was the only one that settled and not silt, even though they're both affected by gravity. Would be helpful if it either settled all blocks affected by gravity, or opened a pop up to select which blocks to settle.

**Comment by BinaryConstruct** [comment]
Thank you for the report. This can probably be added to the plugin.
