### ISSUE TITLE
TEdit-4.3.0.msi detected as virus

### ISSUE THREAD

**Issue by hellothere565** [TEdit/Terraria-Map-Editor#1503]
Hi i have donwload the msi installer from the releases and i am pretty sure its just a misunderstang from side of windows defender, but still just to make sure. It has detected the .msi file as Trojan:Script/Wacatac.B!ml.(just to make it clear i 100% downloaded it from https://github.com/TEdit/Terraria-Map-Editor/releases)

**Comment by BinaryConstruct** [comment]
Windows defender will pick up any installer that has not been downloaded enough _times_ as potentially malicious. 

Here is a virus total report for the MSI.

https://www.virustotal.com/gui/url/fe412edad5e7ba738a3c828ea4a8b5fa9dab2f0bceafa244acbcce48eda57c4e/detection

**Comment by hellothere565** [comment]
oh ok thank you kind sir

**Comment by BinaryConstruct** [comment]
I also added some authenticity and integrity checks you can run on your end to make sure the file has not been tampered with.
https://github.com/TEdit/Terraria-Map-Editor/releases/tag/4.3.0
