### ISSUE TITLE
I cant open

### ISSUE THREAD

**Issue by KainseruI** [TEdit/Terraria-Map-Editor#1505]
# READ THIS FIRST
- **Sprite Issues?** See https://github.com/TEdit/Terraria-Map-Editor/wiki/Install-Requirements#for-sprite-viewing
- **Won't Start?** See https://github.com/TEdit/Terraria-Map-Editor/wiki/Troubleshooting#application-launch-or-map-loading-issue
- **Map not loading?** See https://github.com/TEdit/Terraria-Map-Editor/wiki/Troubleshooting#application-launch-or-map-loading-issue

# If the Wiki did not help, fill out this form completely! If you are missing steps to reproduce your issue will be closed. Thank you.

**Before Submitting an Issue**
* If you are having issues loading a world, please attach it to the current version world thread (see pinned issues).
* For a crash, please check the log.

**Describe the bug**
What is the problem.

1. Click on '....'

**Expected behavior**
What you expected to happen.

**Screenshots**
Add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Version [Tedit 4 beta 9]
 - Terraria Version [e.g. 1.4.0.4]

**Comment by ReconditeDeity** [comment]
Can not reproduce issue. More details needed. What can't you open?

Join us on discord: https://discord.gg/xHcHd7mfpn
