### ISSUE TITLE
TEdit v3.10.18105.2203 Copy/pasting freezes pencil and brush tools.

### ISSUE THREAD

**Issue by Swiftrender** [TEdit/Terraria-Map-Editor#1507]
New to leaving bug reports, but I'll describe as best I can. When copy and pasting some tiles/sprites, after pasting it will freeze the pencil and brush tools. I can select a block but cannot place/remove blocks. Doesn't seem to be consistent. Closing and reopening the program fixes it. I know I'm on an older version of TEdit but I'm using a world in TModLoader, which has not been updated to 1.4 yet. Has this issue been addressed in later versions, and/or is there a potential hotfix that can be made? Thanks

**Comment by BinaryConstruct** [comment]
Pasting can freeze for a few seconds depending on the size of the paste. The brush/pencil should not be blocked _unless_ you have a selection active.

**Comment by Swiftrender** [comment]
I've tried unselecting whatever I had selected, to no avail. And the size of the paste has nothing to do with it, it seems. It's frozen with just a couple tiles.

**Comment by BinaryConstruct** [comment]
Can you try TEdit 4.5.0 beta with support for old worlds? There might still be some bugs, but the more people who try it and give feedback help get those resolved quicker.
