### ISSUE TITLE
Drag and drop world file into TEdit to load it.

### ISSUE THREAD

**Issue by jbro129** [TEdit/Terraria-Map-Editor#1509]
The ability to be able load a world file into TEdit via dragging and dropping the file into TEdit. 
A confirmation warning popup could popup if you are drag and drop a world into Tedit just in case another world is already loaded.

**Comment by jbro129** [comment]
@BinaryConstruct Do you think this feature could be added?

**Comment by BinaryConstruct** [comment]
Yes, this actually used to be a feature. I'll look into it

**Comment by shadowcat1010** [comment]
can we start editing???
