### ISSUE TITLE
Incompatible with new v1.4.2.3 map files

### ISSUE THREAD

**Issue by dringdahl** [TEdit/Terraria-Map-Editor#1511]
from the popup window:

TEdit v4.3.0
TEdit Max World: 234      Current World: 238

Force loading does not work. Gets to calculating colors and then nothing happens.

**Comment by fluxxdog** [comment]
I don't get this. Open a 1.4.2.3 world, log follows. Though, notably, I used 05162021 for the seed to generate a Celebration world.
`05-16-2021 13:25:13: Starting TEdit 4.3.0.0 
05-16-2021 13:25:13: OS: Microsoft Windows NT 10.0.19042.0 
05-16-2021 13:25:13: OS Name: Microsoft Windows 10 Home  
05-16-2021 13:25:13: .NET Framework Version: 4.8 or later 
05-16-2021 13:25:13: Terraria v1.4.2.3 
05-16-2021 13:25:13: Terraria Data Path: d:\steam\steamapps\common\terraria\Content 
05-16-2021 13:25:14: Creating Undo cache: C:\Users\[user]\AppData\Roaming\TEdit\undo\undo_20210516132514`
I did use the generator to make a sample house and put it in the world, then saved. Tried to load into the same world in game and the load failed, had to use the backup.

**Comment by Hazzy2** [comment]
Same for me

**Comment by dringdahl** [comment]
Ok, my loading into TEdit problem seems to be only affecting drunk worlds, as far as I can tell (seed 05162020). These are worlds that were generated prior to the update and saved in 1.4.2.3.

**Comment by ambushing** [comment]
This affects me in non-drunk world seeds, from my world prior to 1.4.2.3

**Comment by Ghrege** [comment]
Any world I open in the 1.4.2.3 update does not load properly when I open it in Tedit and if I save in Tedit the world will fail to load in Terraria. No issues if I haven't opened the world in the 1.4.2.3 update. So the problem only seems to happen after you opened and saved a world in the 1.4.2.3 update or created it in 1.4.2.3.

**Comment by BinaryConstruct** [comment]
Please update https://github.com/TEdit/Terraria-Map-Editor/releases/tag/4.4.0

**Comment by dringdahl** [comment]
TEdit v4.4.0 will load the files, but anything saved out of TEdit will not load in Terraria for me.

**Comment by Hazzy2** [comment]
> 
> 
> This affects me in non-drunk world seeds, from my world prior to 1.4.2.3

same for me but any world after said update

**Comment by BinaryConstruct** [comment]
Please try 4.4.1
