### ISSUE TITLE
World file edited and saved in TEdit v4.4.0 will not load in Terraria v1.4.2.3

### ISSUE THREAD

**Issue by dringdahl** [TEdit/Terraria-Map-Editor#1512]
Terraria offers to load backup file after failing to load edited world. World is a drunk world. Windows 10, Steam version of Terraria.

**Comment by Ghrege** [comment]
Had same issue where world would not load after editing on a normal randomly generated world.

**Comment by BinaryConstruct** [comment]
Here is a hotfix https://github.com/TEdit/Terraria-Map-Editor/releases/tag/4.4.1
