### ISSUE TITLE
HOW TO CONVERT WORLD FROM 236 TO 230??

### ISSUE THREAD

**Issue by SolusUprise** [TEdit/Terraria-Map-Editor#1513]
I got tedit v4.0 and was about to create a world when i got a command prompt from the program saying it'll upgrade my world from 230 to 236 i completely ignored this and here i am after 20 hrs spent creating this world on terraria v1.4.0.5 for cross platforming now it won't load on that version of the game please help !!!

The overall experience of using the program was 10/10 btw. Cheers

**Comment by BinaryConstruct** [comment]
This is a planned feature, however for now there is not a way to downgrade worlds.

**Comment by BinaryConstruct** [comment]
You can try this BETA release, but use with caution and make world file backups. https://github.com/TEdit/Terraria-Map-Editor/releases/tag/4.5.0-beta1
