### ISSUE TITLE
It doesn't work under the virtual machine win10 x64

### ISSUE THREAD

**Issue by t812206236** [TEdit/Terraria-Map-Editor#1514]
I installed DotNet 4.7,directx11, and even terraria can run in the VirtualBox, but TEdit can't open and doesn't give any feedback. 

i can't see anything related to logs in documents / my games / terraria.

What should I do next?

**Comment by t812206236** [comment]
> You can try to clone the source code and see if it will run from visual studio.

Thank you for your reply. Instead of trying to compile the project by myself, I chose to use the cheatsheet module instead of the map editor. I will not study this issue anymore, so I closed this issue.

**Comment by BinaryConstruct** [comment]
You can also try the alternative https://www.terraria-map-editor.com
