### ISSUE TITLE
About replacing blocks..

### ISSUE THREAD

**Issue by NostalgicHistory** [TEdit/Terraria-Map-Editor#1515]
So, I know, I know. This feature has been requested hundreds (if not thousands) of times. But don't start hating me for still requesting it, everyone.

What I want is an actual working plugin or real implemented-to-TEdit feature. That plugin/feature is replacing blocks.
What I'm saying is - I'm working on a world that I don't want to have hell, and by that I mean converting all ash blocks to grass, all lava (in hell, not in the entire world) replaced by water, all hellstone replaced by various ores.

Binary Source or whatever your name is again, please add this. I BEG YOU. This will make my project so much easier as I don't have any more hope to finish my project. My world is LARGE so this would take almost a week for me, but for some of you dedicated builders - like 24-48 hours. C'mon. Add the feature. I gave up on this project and lied about finishing it.

If you don't help me, I don't know what will.

**Comment by SinisterStairs** [comment]
So what you're saying is:  There's a feature you really, really want for your enjoyment; and you'd like some unpaid volunteers to spend 24-48 hours -- a work week -- to make it for you; but you can't even be bothered to spend 1 minute to look BC's name?

I know _I'm_ motivated, Nostalgic Manners or whatever your name is.

**Comment by BinaryConstruct** [comment]
This can already be done using the replace block plugin and brushes with masks.  It doesn't do the whole biome, rather one block type at a time. I will consider this for the morph tool as well.

**Comment by BinaryConstruct** [comment]
> So what you're saying is: There's a feature you really, really want for your enjoyment; and you'd like some unpaid volunteers to spend 24-48 hours -- a work week, for which they _would_ be paid -- to make it for you; but you can't even be bothered to spend 1 minute to look up BC's name?
> 
> I know _I'm_ motivated, Nostalgic Manners or whatever your name is.

I understand the sentiment here, but I also do not wish to have this type of discussion on issues. Thank you for your understanding.

**Comment by SinisterStairs** [comment]
My apologies to both BinaryConstruct and NostalgicHistory -- my comment was inappropriate in this context, and it didn't contribute anything.  I deleted my original comment (not a "moderator"), but you can still see it in BC's response if anyone happens to be digging around closed issues.

**Comment by BinaryConstruct** [comment]
@SinisterStairs Fixed. Thank you for the update. Feel free to ping me on discord.
