### ISSUE TITLE
TEdit malfunctioning all the time..

### ISSUE THREAD

**Issue by NostalgicHistory** [TEdit/Terraria-Map-Editor#1517]
So TEdit seems to malfunction now and then. Crashes and corrupts my experimentation worlds..
I don't know what the hell is happening but it seems to just not load the sprite part.. I just can't explain it well as my first language is not English. It just seems that I can't place sprites or load them using TEdit. It looks fine but the sprite placer tool just doesn't work. It doesn't load any sprites at all. Even with filters - Nothing. I just don't seem like using TEdit anymore.
And I understood nothing from the last problem "Resolved".

**Comment by SolarPH** [comment]
Please state more of the problem. Most likely to say how it doesn't work, like the procedures and stuff. There are some pointers to place sprites anywhere on the world.

1. Make sure you don't have any open selection on the world.
2. When on sprite tool, make sure that you also have selected a sprite to put into your world.
3. In the stable version so far, it was kind of seen that mannequins have not been working the way it should work, as well as putting a chest over an already-existing one corrupts the chest (seen mostly when doing a clipboard paste).
4. Make sure you are saving the world. I set my autosave to be disabled so it will save the ones that is intended, and is finished.

**Comment by NostalgicHistory** [comment]
I quite literally understood.. Nothing.

2021-06-16, tr, 13:05 SolarPH ***@***.***> rašė:

**Comment by BinaryConstruct** [comment]
@NostalgicHistory Please read https://docs.binaryconstruct.com/install-requirements#for-sprite-viewing

**Comment by BinaryConstruct** [comment]
As for crashing, please include your log file.
