### ISSUE TITLE
Chests become empty after copying

### ISSUE THREAD

**Issue by Palamontus** [TEdit/Terraria-Map-Editor#1518]
the bug is pretty simple.
When: i open a chest to view its contents in the "special tiles" tab, i copy a section that contains a chest (any chest) with the selection tool, i load another world and paste the selected area || the chests copyed do not contain any items that were previously in them.

The version of the editor is 4.4.1 - PC

The fix is to close (save or cancel) the opened chest in the special tiles tab before loading another world, this way it copyes the hole selected content when loading another world

i dont know if this was reported before, i lost my way trying to find a report page, i hope this didnt waste your precious time

**Comment by SolarPH** [comment]
Try to use the Beta Version. TEdit 4.4.1 have this problem if you paste a chest over an existing chest.

**Comment by BinaryConstruct** [comment]
Beta 4.8*
