### ISSUE TITLE
4.5.0 beta3 Tiles and Walls don't show properly for selection

### ISSUE THREAD

**Issue by Kenshin210R** [TEdit/Terraria-Map-Editor#1521]
![Screenshot (50)](https://user-images.githubusercontent.com/86787008/124134759-d3950480-da8b-11eb-8b68-255bc6eaae73.png)
![Screenshot (51)](https://user-images.githubusercontent.com/86787008/124134764-d4c63180-da8b-11eb-8d8f-86a318f0c946.png)

**Comment by BinaryConstruct** [comment]
Backspacing the text should clear the filter

**Comment by Kenshin210R** [comment]
Thank you!

Στις Παρ, 2 Ιουλ 2021 στις 7:16 πμ ο χρήστης BinaryConstruct <
***@***.***> έγραψε:

**Comment by BinaryConstruct** [comment]
Please try https://github.com/TEdit/Terraria-Map-Editor/releases/tag/4.5.0-beta4

**Comment by Kenshin210R** [comment]
Thank you again for the quick fix!

**Comment by BinaryConstruct** [comment]
Please let me know how the fix works for you. This filter control is new and the more feedback the better. Thanks!

**Comment by Kenshin210R** [comment]
The problem still exists in some cases, for example when you try the
replace plugin for tiles then the tiles have the same problem as before and
backspace doesn’t seem to fix it…

Στις Παρ, 2 Ιουλ 2021 στις 5:31 μμ ο χρήστης BinaryConstruct <
***@***.***> έγραψε:
