### ISSUE TITLE
My Tedit doesn't work

### ISSUE THREAD

**Issue by INiPvP** [TEdit/Terraria-Map-Editor#1522]
My Tedit doesn't work, when I open it, it's just on the news screen like the first photo below.
when I click on close it just closes and a message appears that it stopped working.
I already checked the log [my games/terraria/tedit] and it doesn't have the Tedit folder, just a few files named
![image](https://user-images.githubusercontent.com/74480825/124373183-7c975700-dc66-11eb-9876-1d575a3e8f9f.png)
![image](https://user-images.githubusercontent.com/74480825/124373185-828d3800-dc66-11eb-8ac3-7aca4478d365.png)

**Comment by BinaryConstruct** [comment]
Please post the contents of TEditlog.txt
