### ISSUE TITLE
[Clipboard] Disabling "Paste empty tiles" option no longer works.

### ISSUE THREAD

**Issue by Kojirremer** [TEdit/Terraria-Map-Editor#1523]
Disabling "Paste empty tiles" option does not appear to work properly. It appears to always default to pasting empty tiles regardless of the checkbox setting.

1. Cut or import a structure with empty areas.
2. Uncheck the "Paste empty tiles" checkbox.
3. Paste the clipboard on an area full of tiles.
4. The tiles get completely overwritten by the full clipboard, including empty spaces.

**Expected behavior**
The pasted structure should only modify the tiles being overwritten while leaving the rest intact.

**Screenshots**
![imagen](https://user-images.githubusercontent.com/6130142/124703017-7cde5f00-debf-11eb-9ecc-f6b14dde1159.png)
![imagen](https://user-images.githubusercontent.com/6130142/124703094-a5feef80-debf-11eb-9477-9721bff775d3.png)

**Desktop:**
 - OS: Windows 10
 - Version Tedit 4.5.0 beta 4
 - Terraria Version 1.4.2.3

**Comment by BinaryConstruct** [comment]
Could you attach this schematic as a zip file? Thanks!

**Comment by Kojirremer** [comment]
Sure. I didn't use a schema for the screenshots (I directly copy/pasted), but I do have it as a schema as well.
[Consola - Altar Corazon.zip](https://github.com/TEdit/Terraria-Map-Editor/files/6774485/Consola.-.Altar.Corazon.zip)

**Comment by BinaryConstruct** [comment]
This will be fixed with the next beta release.
