### ISSUE TITLE
Can't draw liquids over certain vine/rope tiles

### ISSUE THREAD

**Issue by Kojirremer** [TEdit/Terraria-Map-Editor#1525]
**Describe the bug**
If you try to either use the _Brush_, _Pencil_ or _Fill_ tools to place any liquid on certain non-solid vines/ropes, the tools will not allow you to do so, as if they were solid. If there already was liquid over then, the tool will actually **remove** it.
**Affected tiles are:**
Vines (52), Jungle Vines (62), Hallowed Vines (115), Crimson Vine (205), Vine Rope (353), Vine Flowers (382), Silk Rope (365), Web Rope (366).

Mushroom vines, normal and mystic snake ropes, and chains work as intended.

1. Place/find any of the affected tiles mentioned above in the world.
2. Select _Brush_, _Pencil_ or _Fill_ tools in liquid mode to place any liquid over them.
3. Placed liquid will avoid the mentioned tiles; existing liquid over said tiles will be removed.

**Expected behavior**
The liquid should be drawn over the mentioned tiles, like how it happens on the unaffected ones mentioned above. The screenshot below shows both affected and unaffected vine/rope tiles right after using the brush tool to paint honey over them.

**Screenshots**
![imagen](https://user-images.githubusercontent.com/6130142/125160810-fdfe5600-e14c-11eb-9740-7bed08278338.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version Tedit 4.5.0 beta 4
 - Terraria Version 1.4.2.3

**Comment by RussDev7** [comment]
Thank you for this report. As it stands right now, not being able to place liquid on active solid tiles is intentional, however I went ahead and added an exclusion for this. I do agree these should not count.
