### ISSUE TITLE
Textures don't come!

### ISSUE THREAD

**Issue by SenZe19** [TEdit/Terraria-Map-Editor#1526]
The textures won't come, like they will be just singled colored blocks no textures. please someone help me! it is hard to use it without  textures.

No matter how much I zoom in it won't show the textures 
![image](https://user-images.githubusercontent.com/83814869/125187011-7d1f8700-e23e-11eb-8ecb-da49faf5e3e0.png)

**Comment by nighplasmage** [comment]
Did you look under the top drop down  menus, File/Edit/Layer/Plugin.
Layer Drop down Menu options:
Show Layers 
checkbox Texture
checkbox show layout grid

and at the bottom:  Textures Visible   slider   3-10

**Comment by SolarPH** [comment]
If you have Terraria installed via steam, the textures should show up. If you have the GOG version, make sure to make some configurations, especially the AltC property

**Comment by BinaryConstruct** [comment]
Please read https://docs.binaryconstruct.com/install-requirements
