### ISSUE TITLE
The Replace All Tiles Plugin Does Not Work

### ISSUE THREAD

**Issue by Shteiny** [TEdit/Terraria-Map-Editor#1527]
I tried to replace all coper ore tiles with tin ore. I unchecked the Wall checkbox. Chose copper ore. picked Edit Masking for Mask Mode. Picked Tin ore for Mask. Clicked replace. saved. when I opened the world copper was still copper, and in TEdit copper was also still copper.
I also did the same for Copper Tier under World Properties
![image](https://user-images.githubusercontent.com/75817604/126876536-153e0f66-e4ea-41bf-ae76-f194b08b227e.png)
![image](https://user-images.githubusercontent.com/75817604/126876541-e82b9e82-40eb-423e-9859-404bc4114d10.png)
![image](https://user-images.githubusercontent.com/75817604/126876550-1ef7fa24-3c9e-466e-b796-c619656d208e.png)

**Comment by BinaryConstruct** [comment]
Please reopen this issue if it has not been fixed by v4.7.1
