### ISSUE TITLE
Tedit don't open

### ISSUE THREAD

**Issue by italorbrabor** [TEdit/Terraria-Map-Editor#1529]
When I click to open the Tedit.exe 

![image](https://user-images.githubusercontent.com/87943816/126907009-47d714f4-fc93-47d2-9d85-3f06a487dec0.png)
He opens this but after a while, it still doesn't open. And I've been waiting for 30 minutes to open.
When I opened for the first time, it appeared the latest news and I clicked the close button but the same thing happened.

The version is 4.4.1

**Comment by BinaryConstruct** [comment]
Please try 4.5.0-beta4

**Comment by BinaryConstruct** [comment]
Please see https://docs.binaryconstruct.com/install-requirements
