### ISSUE TITLE
Snow Tree Type Won't Change After Editing

### ISSUE THREAD

**Issue by dioneon** [TEdit/Terraria-Map-Editor#1530]
# READ THIS FIRST
- **Sprite Issues?** See https://github.com/TEdit/Terraria-Map-Editor/wiki/Install-Requirements#for-sprite-viewing
- **Won't Start?** See https://github.com/TEdit/Terraria-Map-Editor/wiki/Troubleshooting#application-launch-or-map-loading-issue
- **Map not loading?** See https://github.com/TEdit/Terraria-Map-Editor/wiki/Troubleshooting#application-launch-or-map-loading-issue

# If the Wiki did not help, fill out this form completely! If you are missing steps to reproduce your issue will be closed. Thank you.

**Before Submitting an Issue**
* If you are having issues loading a world, please attach it to the current version world thread (see pinned issues).
* For a crash, please check the log.

**Describe the bug**
After selecting Snow BG 4 (the one that changes the tree sprite to a green spruce tree not covered in snow) and then saving, my world is still showing the dead-looking trees when I enter the snow biome in-game. I've tried changing the background to Snow 0, 1, 2, and 3, but this isn't changing how the trees look at all, even though the tree sprite changes to what is expected on TEdit. The in-game background changes to what is expected, but the trees won't.

I generated a new world as well, and changing the Snow BG number isn't changing how the trees look in those worlds either. 

**Expected behavior**
I expected the tree type in-game to reflect the sprite shown on the TEdit app after customizing and saving, but this isn't happening. They appear to be unchangeable.

**Screenshots**
Add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version Tedit 4.5.0 beta4, as well as Version TEdit v4.4.1
 - Terraria Version 1.4.2.3

**Comment by RussDev7** [comment]
Is this issue still unsolved? I recreated it and had no issues.

**Comment by RussDev7** [comment]
I'll be closing this due to no further activity. If the problem continues to persist please feel free to open a new ticket.
