### ISSUE TITLE
Typing in the wall search causes the program to error and close.

### ISSUE THREAD

**Issue by dragon3025** [TEdit/Terraria-Map-Editor#1531]
**Describe the bug**
When typing in the search bar for Walls, it gives the message:

"An unhandled exception has occurred. You may continue using TEdit, but operation may be unstable until the application has been restarted.

Then it freezes up and closes the program.

1. Click on pencil tool.
2. Click on wall search bar.
3. Start typing a block, for example: "Wood Wall"
4. It gives the error, freezes up, then closes.

**Expected behavior**
Filtering walls.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version TEdit v4.5.1
 - Terraria Version 1.4.2.3

EDIT: I didn't know where the logs where, but I found it:
[TEditLog_20210731164350.txt](https://github.com/TEdit/Terraria-Map-Editor/files/6911985/TEditLog_20210731164350.txt)

EDIT: It just did it when typing in the block search bar. This really hinders TEdit. My only thought is to search block/wall IDs so I can scroll through the list and find them.

**Comment by SolarPH** [comment]
This still appears on TEdit 4.5.2

**Comment by BinaryConstruct** [comment]
If this issue is still present in v4.7.1, please reopen this.

**Comment by a1russell** [comment]
This is still present in 4.7.2. The last good version was 4.4.1.
