### ISSUE TITLE
*\TEdit-4.5.1\zh-CN folder are empty

### ISSUE THREAD

**Issue by HUGETY** [TEdit/Terraria-Map-Editor#1533]
Cant change language to chinese cus zh-CN folder are empty but why?

**Comment by CharlesHim** [comment]
It seems that every other languages' folder has one .dll file inside, but not Chinese.  I wonder if Chinese support is yet to be added into the editor？

**Comment by BinaryConstruct** [comment]
It is supported, but a compile bug might have broken it. It might be missing some of the new entries causing it to get dropped.

**Comment by Harriser** [comment]
Yes, I cannot change the language, I just discovered this question.
Copy from Version 4.3.0.

**Comment by Misor63** [comment]
i find the file missed after the version 4.5.0 beta2,and copy the file to 4.7.0 still can work

**Comment by xieryuwo** [comment]
The new version is suspected to have fixed this problem（4.7.2）

**Comment by BinaryConstruct** [comment]
This is an upstream bug in the dotnet compiler. I will continue to manually add the files as required.
