### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by BigmenPixel0** [TEdit/Terraria-Map-Editor#1536]
Please, add support for Linux, dotnet 5.0 support it

**Comment by DiegoG1019** [comment]
They'd probably have to do a pretty lengthy migration seeing as the project is set for .NET Framework 4
Plus, Windows Forms is for Windows Only, they'd also have to redo the entire GUI from scratch, which would also mean significant changes to the rest of the codebase - Might as well be making a new app

**Comment by BinaryConstruct** [comment]
This app is .Net Framework 4 and DirectX based. Please see https://www.terraria-map-editor.com as an alternative for linux.
