### ISSUE TITLE
Feature Request: Resize/crop existing worlds

### ISSUE THREAD

**Issue by unmoving-javi** [TEdit/Terraria-Map-Editor#1537]
I was watching [a video by Wand of Sparking](https://www.youtube.com/watch?v=gc0l7j3Oxh0) in which they used TEdit to shrink the world upon killing each boss. I noticed that in their video, the process was very labor-intensive and required them to remake the world each time, copying over the remaining land from their previous world.

If a feature to make this easier could be included in TEdit, challenges like these could be much more easily accessible. If an existing world can either be cropped down or have its world borders moved, you could not only do shrinking worlds but also growing ones, with more space appearing as you defeated more bosses. Of course, you'd still have to do it manually, but it'd be much easier. This might also be of use for testing out the functionality of worlds that have had their size changed.

Of course, you can still do this in the editor by making a new world and copying over the old one. However, I think it would be preferable to work with existing worlds.

As for specific functionality, it would be nice if you could specify both world size and where to cut the blocks from, [similar to the image editor Paint.NET's canvas size tool.](https://imgur.com/a/ixASvhH) The anchor point here just refers to how pixels are to be added. If it's in the middle, they'll be split evenly (or as evenly as they can be) to either side. If it's at the top, it'll only add pixels to the bottom. The same could easily be done with blocks, though of course in the case of odd numbers of blocks you might end up with some inconsistencies.

Of course, I don't have any real knowledge of the engine, so if this is impossible with Terraria's world format, feel free to let me know and close the issue.

**Comment by BinaryConstruct** [comment]
This is a really cool idea! Thanks for pointing out the video. I'll see if I can get this in for the next release or two.

**Comment by unmoving-javi** [comment]
Just as a note, apparently waterfalls out-of-bounds can cause the game to crash, so it might also be worth considering a checkbox to toggle removing liquids outside of world bounds.
