### ISSUE TITLE
Game Directory choice in-software

### ISSUE THREAD

**Issue by Tazawaki** [TEdit/Terraria-Map-Editor#1538]
I personally never found where to change the game directory in the settings.xml file, so I cannot use the tiles tool, nor can TEdit show the sprites.

It would be nice to have a menu inside the software that allows you to set a custom game directory, or maybe just somewhere where it says precisely where you have to put your custom path.

(I am not sure if directory is the right word, hope its still understandable)

**Comment by BinaryConstruct** [comment]
Hi, this file is actually located in the same folder as TEdit.exe. It should be called `settings.xml`. To locate your Terraria game content folder when you are using steam, you can open the properties menu
![image](https://user-images.githubusercontent.com/456755/131407555-c29c7c73-b487-461a-99dc-b131635483dc.png)
and select "Local Files" then "Browse.
![image](https://user-images.githubusercontent.com/456755/131407627-0119f5f8-a6fe-485d-8592-7115c41d5d67.png)
This should allow you to find the content folder.
![image](https://user-images.githubusercontent.com/456755/131407704-0dc56daa-a2d7-4045-9b66-f6b31039736a.png)

Once you have completed this, edit the settings.xml file as shown on https://docs.binaryconstruct.com/install-requirements#for-sprite-viewing

**Comment by Tazawaki** [comment]
Thanks!
Sorry, i had not seen that one on the requirements page.
Just tried it out, it works just fine, thanks for the help!
