### ISSUE TITLE
TEdit - World won't load.

### ISSUE THREAD

**Issue by Deathzac** [TEdit/Terraria-Map-Editor#1542]
Hello everyone. 
I've been trying to use Tedits for many, many, many, days. It used to work pretty well, however, it would keep saving the worlds in .TMP formats. I decided to use an older version of TEdit (4.4.1, or the latest stable version). It saved properly. 
However, upon making an attempt at loading the worlds, I receive the error message: "Load Failed, no Backup".
I tried everything to do with changing .wld to .wld.bak to removing chests from my world and trying, to no avail. I would love if someone could try and tell me what is happening and why it is not working. 
Thank you.
![Screenshot (65)](https://user-images.githubusercontent.com/75154692/132428239-198f26ea-a3c3-4647-862c-0b4dea7c008a.png)

[Worlds.zip](https://github.com/TEdit/Terraria-Map-Editor/files/7124985/Worlds.zip)

**Comment by BinaryConstruct** [comment]
If this issue is still present in v4.7.1, please reopen this.
