### ISSUE TITLE
Sprite cannot be placed with Sprite Tool + Sprites Filter not working

### ISSUE THREAD

**Issue by SolarPH** [TEdit/Terraria-Map-Editor#1548]
**Describe the bug**
While selecting sprites while having the Sprites Tool active, it doesn't bring up any sprites that can be placed. Searching specific sprite groups by name filter doesn't give any result either.

1. Click on Sprite Tool
2A. Select any sprite from the Sprite Selection
2B. Search any sprites using the Filter Bar (for the other related bug)
3. Bring the mouse and try to select any sprites on the scene. In this case, the sprite won't even show its overlay clone.

**Expected behavior**
The expected behavior is that whenever the sprite tool is active and a sprite gets selected, the sprite overlay will show up. Typing a name and hitting the filter button should also filter out items.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version Tedit 4.5.2
 - Terraria Version 1.4.2.3

**Comment by BinaryConstruct** [comment]
If this issue is still present in v4.7.1, please reopen this.
