### ISSUE TITLE
Can't choose anything. Can't search either.

### ISSUE THREAD

**Issue by Catstik** [TEdit/Terraria-Map-Editor#1550]
Whenever I choose a new block to place only that block shows up and I can't choose anything (with any block/wall placing thing).
I also can't choose a block or wall with the picker.

**Comment by Catstik** [comment]
![image](https://user-images.githubusercontent.com/91972350/136059548-88be9f18-2d3d-403c-baf3-05eca53b3cc6.png)

**Comment by Catstik** [comment]
![image](https://user-images.githubusercontent.com/91972350/136060369-fc357b49-54e8-4ebf-a53f-3f5acfb5c275.png)

**Comment by Catstik** [comment]
![image](https://user-images.githubusercontent.com/91972350/136060645-24775102-1436-4175-8014-445b3eea0f5d.png)

**Comment by BinaryConstruct** [comment]
Please try v4.7.1
