### ISSUE TITLE
[Minor BUG] Word name wont change when using "save as"

### ISSUE THREAD

**Issue by holinov** [TEdit/Terraria-Map-Editor#1560]
World name is not changed according to filename when using "Save as". 

1. Open any existing world
2. Press "save as" and give diferent name
3. In game in world list you will see 2 world with same name (but 2 different files in World directory)

**Expected behavior**
After "Save as" world sould have same name as file (or may-be alert/promt to force user to change worlds name)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10] win10
 - Version [Tedit 4 beta 9] 4.5.5-beta
 - Terraria Version [e.g. 1.4.0.4] 1.4.1

**Comment by BinaryConstruct** [comment]
The in-game world name is separate from the file name intentionally. 
Please use this control to edit the in-game displayed name.
![image](https://user-images.githubusercontent.com/456755/140118653-dc66a1ff-df67-4384-b5b7-5c218a96ae33.png)

**Comment by BinaryConstruct** [comment]
However, I will look into adding a prompt on the save-as to ask if you want to rename the world name to match.

**Comment by holinov** [comment]
as for me it seems like bes behaivour is to change worlds name to file as provided from "save as" dialog

**Comment by holinov** [comment]
or maybe you could update "creation time" as for "save as" was pressed but not to make "identical clones" on world loading menu
