### ISSUE TITLE
4.5.5 isn't latest version?(2021/11/07)

### ISSUE THREAD

**Issue by moe41** [TEdit/Terraria-Map-Editor#1561]
![無題](https://user-images.githubusercontent.com/66813644/140647119-0fd20df5-9407-40a2-a756-60ea344db926.png)

**Comment by moe41** [comment]
when 4.5.5, but it says"you are using an outdated version of tedit. do you wish to download the update?"

**Comment by RussDev7** [comment]
It's a bug with the beta version releases. This is indeed the latest release.
