### ISSUE TITLE
Terraria Content not Found 

### ISSUE THREAD

**Issue by dickyharper** [TEdit/Terraria-Map-Editor#1562]
## Before Submitting

* If you are having issues loading a world, please attach it to the current version world thread (see pinned issues).
* If you get an unhandled exception or crash, please _**check your log before posting**_.

### Steps to reproduce the issue?
1) When TEdit starts, Terraria searches for the Steam version and cannot find it because the gog version is installed.

### What version of Terraria are you using?
Terraria 1.4.0.5 (38803)
### Post relevant contents of log or attach log file _**(very important)**_:
_Copy paste using code [block tags](https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks) into the issue as a comment_

### Attach world file
![TEdit_8I8GKbG54I](https://user-images.githubusercontent.com/50758669/141336686-db6763bc-0498-41b2-a780-95b36275ad6a.png)

![Ekran Görüntüsü (88)](https://user-images.githubusercontent.com/50758669/141336714-bd2a2eca-3e85-4007-9588-63072fedfaf2.jpg)

**Comment by dickyharper** [comment]
> 
> ## Before Submitting
> 
>     * If you are having issues loading a world, please attach it to the current version world thread (see pinned issues).
> 
>     * If you get an unhandled exception or crash, please _**check your log before posting**_.
> 
> 
> ### What were you doing when the issue occured?
> ### Steps to reproduce the issue?
> 
>     1. When TEdit starts, Terraria searches for the Steam version and cannot find it because the gog version is installed.
> 
> 
> ### What version of Terraria are you using?
> 
> Terraria 1.4.0.5 (38803)
> ### Post relevant contents of log or attach log file _**(very important)**_:
> 
> _Copy paste using code [block tags](https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks) into the issue as a comment_
> ### Attach world file
> 
> ![TEdit_8I8GKbG54I](https://user-images.githubusercontent.com/50758669/141336686-db6763bc-0498-41b2-a780-95b36275ad6a.png)
> 
> ![Ekran Görüntüsü (88)](https://user-images.githubusercontent.com/50758669/141336714-bd2a2eca-3e85-4007-9588-63072fedfaf2.jpg)

I found the solution to my  first problem. 

![TEdit_BqyV445oQB](https://user-images.githubusercontent.com/50758669/141338890-43309952-c1a5-4930-9927-e47c671f2a4c.png)
And now looking at the sky again, TEdit shows that it's not the sky

**Comment by BinaryConstruct** [comment]
Please try https://github.com/TEdit/Terraria-Map-Editor/releases/tag/4.5.7 

Version 4.5.6 had a ground level bug that shifted the ground.

**Comment by dickyharper** [comment]
> 
> 
> Please try https://github.com/TEdit/Terraria-Map-Editor/releases/tag/4.5.7
> 
> Version 4.5.6 had a ground level bug that shifted the ground.

Everything looks fine. Thanks for the quick fix. And in this great software
