### ISSUE TITLE
My sky has turned into a cave wall

### ISSUE THREAD

**Issue by ch-IsOd** [TEdit/Terraria-Map-Editor#1563]
I don’t know how it happened, but now instead of the sky, a cave wall appeared on the surface. Then I tried to create a new world, at first it was normal, and then I opened the world again through the program and this background appeared again.
I used app version 4.5.6. Installed 4.5.8 it didn't work anymore, but I still can't fix my world.

Screen: https://imgur.com/a/BlgJp1r

**Comment by BinaryConstruct** [comment]
There are sliders in the world properties for cave level and surface level

**Comment by ch-IsOd** [comment]
OOOOOH THANKS!!! I only used the slider for the cave level, I thought the surface level should be 0 so did not touch
