### ISSUE TITLE
Unable to recognize new items from Terraria 1.4.3 in containers

### ISSUE THREAD

**Issue by BassBuilt** [TEdit/Terraria-Map-Editor#1566]
### Summary
TEdit v4.6.0 does not recognize the new items added in Terraria 1.4.3. The items show up as [empty] when viewing a container's contents in TEdit. However, as long as the user doesn't edit the contents of the container, the world can be manipulated in TEdit, saved, and loaded in Terraria 1.4.3 with no issues.

### Steps to reproduce the issue?
1) Put newly-added items from Terraria 1.4.3 into a container
2) Save the world, open in TEdit
3) TEdit recognizes the stack quantities, but not the item types, showing as [empty] instead

### What version of Terraria are you using?
Terraria 1.4.3

### Attach world file
[Starving_Alone.zip](https://github.com/TEdit/Terraria-Map-Editor/files/7567702/Starving_Alone.zip)

**Comment by BinaryConstruct** [comment]
This should be fixed with https://github.com/TEdit/Terraria-Map-Editor/releases/tag/4.6.1 or by updating [settings.xml](https://github.com/TEdit/Terraria-Map-Editor/releases/download/4.6.0/settings.xml).
