### ISSUE TITLE
Abigail's Flower shows up as INVALID TILE and isn't available from the Sprite Placer

### ISSUE THREAD

**Issue by BassBuilt** [TEdit/Terraria-Map-Editor#1568]
**Summary**
The new plant sprite/summoning weapon Abigail's Flower shows up as "INVALID TILE (624)" when viewed in TEdit. Similarly, the plant sprite is not available from the Sprite Placer menu. However, TEdit is still able to load/edit/save worlds with Abigail's Flower in them, extending even to copying and pasting the INVALID TILE using the clipboard.

1. Load a 1.4.3 world with Abigail's Flower in it, and mouse over the flower's location

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Version [TEdit 4.6.1]
 - Terraria Version [1.4.3]
 - World [Starving_Alone.zip](https://github.com/TEdit/Terraria-Map-Editor/files/7573469/Starving_Alone.zip)

**Comment by RussDev7** [comment]
This issue was brought to attention and is aware. Thanks for taking the time to wright in!

**Comment by RussDev7** [comment]
This issue is known and will soon be fixed. Thanks for taking the time to wright in!
