### ISSUE TITLE
Export Schematic "The given key was not present in the dictionary"

### ISSUE THREAD

**Issue by jlyon87** [TEdit/Terraria-Map-Editor#1569]
# READ THIS FIRST
- **Sprite Issues?** See https://github.com/TEdit/Terraria-Map-Editor/wiki/Install-Requirements#for-sprite-viewing
- **Won't Start?** See https://github.com/TEdit/Terraria-Map-Editor/wiki/Troubleshooting#application-launch-or-map-loading-issue
- **Map not loading?** See https://github.com/TEdit/Terraria-Map-Editor/wiki/Troubleshooting#application-launch-or-map-loading-issue

# If the Wiki did not help, fill out this form completely! If you are missing steps to reproduce your issue will be closed. Thank you.

**Before Submitting an Issue**
* If you are having issues loading a world, please attach it to the current version world thread (see pinned issues).
* For a crash, please check the log.

**Describe the bug**
What is the problem.
Schematics appear to save, despite an error prompt. But when I restart tedit, I get an error when I try to import the schematic.

1. Open TEdit
2. Add something to the clipboard.
3. Click Export on the clipboard item.
4. Enter a file name and save. (Screenshot 1)
5. Restart TEdit
6. Open the Clipboard
7. Click Import Schematic
8. Select Schematic from Step 4
9. Click Open (Screenshot 2)

**Expected behavior**
I expect that saving an importing schematics feature works can save a schematic to local disk then recover that file when I import the schematic later.

**Screenshots**
Add screenshots to help explain your problem.
Screenshot 1 (Step 4)
![image](https://user-images.githubusercontent.com/9729366/142711629-0c011b65-4de8-438b-8475-4f40af4ac031.png)
Screenshot 2 (Step 9)
![image](https://user-images.githubusercontent.com/9729366/142711640-88622372-7997-4b36-99e5-5b092eac9f5a.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Version [Tedit 4 beta 9]
 - Terraria Version [e.g. 1.4.0.4]

```sh
11-19-2021 20:33:35: Starting TEdit 4.6.1.0 
11-19-2021 20:33:35: OS: Microsoft Windows NT 10.0.19042.0 
11-19-2021 20:33:35: OS Name: Microsoft Windows 10 Pro  
11-19-2021 20:33:35: .NET Framework Version: 4.8 or later 
11-19-2021 20:33:36: Terraria v1.4.3 
11-19-2021 20:33:36: Terraria Data Path: C:\Program Files (x86)\Steam\steamapps\common\Terraria\Content 
11-19-2021 20:33:36: Creating Undo cache: C:\Users\[user]\AppData\Roaming\TEdit\undo\undo_20211119203336 
```

**Comment by seftonsg** [comment]
One of my friends seems to still have this issue on TEdit 4.6.2 using a map that was recently opened in Terraria 1.4.3.2.  They're worlds made yesterday.  I presume the hotfixes re-broke the dictionary?

**Comment by phruh** [comment]
Yeah? So, where's the fix to this?

**Comment by BinaryConstruct** [comment]
The settings.xml update is present in 4.6.2. Can you attach a world file so I can test? Thanks

**Comment by AkiSan0** [comment]
I have the same issues with every world created after the 1.4.3 Hotfix. Here is one of the worlds where it happens.  hope this helps! :)   thanks for your awesome tool and the insane support over the years! ultra much appreciated! :)
[san3.zip](https://github.com/TEdit/Terraria-Map-Editor/files/7627097/san3.zip)

**Comment by BinaryConstruct** [comment]
Can you please check [v4.7.1](https://github.com/TEdit/Terraria-Map-Editor/releases/tag/4.7.1)?
