### ISSUE TITLE
Picker tool on wires treats green as blue and vice versa

### ISSUE THREAD

**Issue by BassBuilt** [TEdit/Terraria-Map-Editor#1572]
**Describe the bug**
When using the picker tool (dropper) in the wire paint mode, clicking on a green wire (or green as a component of multicolor wire) tile instead selects blue wire. Likewise, clicking on a blue wire tile instead selects green wire.

**Expected behavior**
Clicking a green wire tile with the picker tool selects green wire, and clicking a blue wire tile with the picker tool selects blue wire, just as the other wire colors do.

**Screenshots**
![image](https://user-images.githubusercontent.com/44708916/143526867-70c50a08-6a05-4730-a487-40c4529838f6.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Version [Tedit 4.6.2]
 - Terraria Version [e.g. 1.4.3.2]

**Comment by RussDev7** [comment]
I will look into this. Thanks for the report.

**Comment by BinaryConstruct** [comment]
Fixed with 4.7.
