### ISSUE TITLE
Cannot Save As Version, dialog box does not appear

### ISSUE THREAD

**Issue by Nykorin** [TEdit/Terraria-Map-Editor#1573]
**Describe the bug**
Cannot change the world version using "Save as Version". Dialog box to save the world doesn't appear. The dialog box does appear on TEdit 4.6.1.

1. Start TEdit.
2. Click on open world and select any of the worlds.
3. Click on "File".
4. Click on "Save As Version".
5. Select any versions listed.
6. Dialog box to save the world does not appear.

**Expected behavior**
The dialog box should appear after selecting the version from the list.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - TEdit Version: 4.6.2
 - Terraria Version: 1.4.3.2

**Comment by RussDev7** [comment]
This issue is confirmed and has been corrected. Next TEdit release will have fixed this.

**Comment by BinaryConstruct** [comment]
This should be fixed with 4.7
