### ISSUE TITLE
Unhandled exception when attempting to open or save a world file. (Windows 11 running in parallels on M1 mac)

### ISSUE THREAD

**Issue by LuneAttic** [TEdit/Terraria-Map-Editor#1575]
**Describe the bug**
*Running in Windows 11 in parallels desktop on an M1 MacBook pro* 
TEdit opens and runs normally, I can create a new world and edit it, however when attempting to open an existing world, or save a newly created one, the 'Unhandled Exception' error is thrown. I have attempted to open a file with previous versions, back to 4.5.1, the same issue occurs.

1. Open TEdit
2. Select 'open' in the File menu
3. 'an unhandled exception has occurred'
*or:
1. Open TEdit
2. Create a new world
3. select 'save' from the File menu
4. 'an unhandled exception has occurred' 

**Expected behavior**
A screen should appear when 'open' is selected in the file menu, and a world may be selected and opened.  Also, a new world created in TEdit should be saved as a file when 'save' is selected in the File menu. 

**Screenshots**
Add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: Windows 11 (running in parallels on an M1 MacBook Pro)
 - Version: Tedit 4.6.2
 - Terraria Version: 1.4.0

**Comment by BinaryConstruct** [comment]
TEdit is not supported on ARM processors.
