### ISSUE TITLE
empty language folder

### ISSUE THREAD

**Issue by Arsha-s** [TEdit/Terraria-Map-Editor#1581]
the language folder about zh-CN is empty, even if I unzip the file for the first time.It is not supported yet or it is a mistake?

**Comment by Arsha-s** [comment]
4.7.0 btw

**Comment by BinaryConstruct** [comment]
[TEdit.resources.dll.zip](https://github.com/TEdit/Terraria-Map-Editor/files/7681844/TEdit.resources.dll.zip)

Here you go. I'll see what is going on with the packaging process.

**Comment by BinaryConstruct** [comment]
I've also re-uploaded the 4.7.1 release, ensuring this file is present. https://github.com/TEdit/Terraria-Map-Editor/releases/tag/4.7.1

**Comment by BinaryConstruct** [comment]
https://github.com/dotnet/msbuild/issues/3897 It looks like this is related to an upstream msbuild issue.

**Comment by Arsha-s** [comment]
> It looks like this is related to an [upstream msbuild issue](https://github.com/dotnet/msbuild/issues/3897)

Got it. And Thanks for such a covenient tools that you create and I like it very much!

**Comment by BinaryConstruct** [comment]
Glad you are enjoying it!
