### ISSUE TITLE
Typo in legacy warning message

### ISSUE THREAD

**Issue by Happylama25** [TEdit/Terraria-Map-Editor#1584]
**Describe the bug**
There is a small typo on the legacy warning message

1. Open a file that is "legacy" (example, a TModLoader world file)

**Expected behavior**
"corruption" instead of "corrpution"

**Screenshots**
![image](https://user-images.githubusercontent.com/49815691/146665023-7ce44536-96e1-4074-842f-e7bc29bc7ec2.png)
![image](https://user-images.githubusercontent.com/49815691/146665075-a42a3f5b-6a40-4881-9dca-7636fa9b4400.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version TEdit v4.7.2
 - Terraria Version I assume its v1.3.5.3 since I'm using a TMod world file 
![image](https://user-images.githubusercontent.com/49815691/146665052-ae4e6db9-e4b8-4b34-8b4b-4928e5ad3fd3.png)

**Comment by RussDev7** [comment]
@BinaryConstruct Has this issue been resolved?
