### ISSUE TITLE
Not sure that's intentional: heart statues not included in the new "find blocks" feature

### ISSUE THREAD

**Issue by OliverFrWTFalreadyTakenComeOnNow** [TEdit/Terraria-Map-Editor#1588]
Hi!

Tedit 4.7.3 here, Terraria 1.4.3.2, Windows 10.

I thought I'd give the new promising "find block or wall" feature a go, and searched for "heart statue" in both block and wall fields.
There were zero returned results, even though I know for sure there's at least 3, since it's statues I found and planted in my home area.

No log file was created upon this running of Tedit. I closed the program, ran it a second time to try searching again, to no difference.

I'm not asking for support, not intending to rant, I just thought this may not be intentional, and that reporting it might then be of help. If I didn't properly read the contents of the update and missed the part where statues are excluded, my apologies then!

I attached the world in which I made the search for proper testing.

Cheers, and thanks for the insanely useful program!

**EDIT:** my bad, I didn't experiment enough. I found why, every statue, no matter of what it is a statue (heart, star, slime, et caetera), is only called "statue" in the block search results.

**Comment by RussDev7** [comment]
Have you tried to just search “heart” within the tile or wall entrees? Maybe we have an issue with .Contains()

**Comment by BinaryConstruct** [comment]
@RussDev7 I think the search needs to go through all the frame variants as well as just the block title in the initial search loop. The block title is just something like "deco large" for a lot of these, and the variant has the actual details. This might add some complexity, as it would also need to search for UV coords in conjunction with title text. E.g. each item added to the search list would be a tile ID and if framed, UV coords.

**Comment by OliverFrWTFalreadyTakenComeOnNow** [comment]
I should have experimented further, if github allows, I'll edit my original post with this new info: I found out EVERY statue is called "statue", and nothing more, in the search feature. That's why the specific "heart" part wasn't found, it wasn't part of the returned results

**Comment by RussDev7** [comment]
@BinaryConstruct Yes this certainly needs to be incorporated if that is what is actually going on here. When I get some time and get back, I will make this a priority to fix.

**Comment by RussDev7** [comment]
Should this be marked as closed? I believe this issue has been resolved.
