### ISSUE TITLE
Android World Support

### ISSUE THREAD

**Issue by yavash** [TEdit/Terraria-Map-Editor#1590]
load android map failed 
![legacy world](https://yavash.github.io/images/a.png)
![world file error](https://yavash.github.io/images/b.png)

[https://yavash.github.io/images/Tt.wld](https://yavash.github.io/images/Tt.wld)

**Comment by BinaryConstruct** [comment]
Is this a modded world?

**Comment by BinaryConstruct** [comment]
Thanks for the world file! I'll check it out.

**Comment by TreeBranches** [comment]
I came across this as Windows Phone will be shutting off their Xbox achievements in May. I was wondering if there's been any progress?

**Comment by BinaryConstruct** [comment]
PC legacy maps are mostly supported. Console and phone maps are a different format.

**Comment by 11EzZ** [comment]
![3a7c55d40ffa8ba9dc189ef397291d6](https://user-images.githubusercontent.com/106471092/170863199-8510909b-09d0-4902-ad65-ab6558ac4f47.png)
![e8c1b27bab0f0abd8a44634dde18a81](https://user-images.githubusercontent.com/106471092/170863201-28b37a3b-c965-4cd3-8e90-08e439f13f65.png)

I want to edit the android maps of terraria v1.4.10024 but failed,

**Comment by RussDev7** [comment]
> ![3a7c55d40ffa8ba9dc189ef397291d6](https://user-images.githubusercontent.com/106471092/170863199-8510909b-09d0-4902-ad65-ab6558ac4f47.png) ![e8c1b27bab0f0abd8a44634dde18a81](https://user-images.githubusercontent.com/106471092/170863201-28b37a3b-c965-4cd3-8e90-08e439f13f65.png)
> 
> I want to edit the android maps of terraria v1.4.0.5(taptap terraria version 1.4.10024) but failed. this is the map:https://1drv.ms/u/s!Aqg8klAOYX7Ae01qZNsiHDWzV1U?e=60Nh4q

I was able to open and save this in TEdit 4.11. Please consider updating. Closing this for now.
