### ISSUE TITLE
TEditor not work

### ISSUE THREAD

**Issue by EvanHsieh0415** [TEdit/Terraria-Map-Editor#1592]
I've checked the requirements in [https://docs.binaryconstruct.com/install-requirements#required](https://docs.binaryconstruct.com/install-requirements#required) and they are met, but it still won't start

[![image](https://i.imgur.com/kNXEbgE.png)](https://imgur.com/kNXEbgE)

**Comment by BinaryConstruct** [comment]
Can you try putting it in `c:\TEdit-4.7.4`? Sometimes it has issues with unicode characters in the path of the exe or the user folder.
