### ISSUE TITLE
Textures error

### ISSUE THREAD

**Issue by ItzVirux** [TEdit/Terraria-Map-Editor#1602]
hello, my Tedit textures do not work correctly, any solution? I was reading that the terraria installed on the pc is necessary, but I don't know if the version works. I use version 1.4.0.5 of the game and windows 8

![piramide](https://user-images.githubusercontent.com/99940842/154620671-45e36956-7a11-4bfd-b967-d7b52e9db642.jpg)

**Comment by BinaryConstruct** [comment]
Please see https://docs.binaryconstruct.com/install-requirements#for-sprite-viewing
