### ISSUE TITLE
Or prompt the following picture when importing and exporting circuit diagrams and pictures.what's to be done

### ISSUE THREAD

**Issue by apk5418** [TEdit/Terraria-Map-Editor#1604]
![20220227101603](https://user-images.githubusercontent.com/100498941/155865610-068bf28b-b81e-4c08-8b75-071fa70c7a8e.png)
![20220227101612](https://user-images.githubusercontent.com/100498941/155865613-16a937cd-3a27-4ab8-b20d-d25577fc2ee9.png)

**Comment by BinaryConstruct** [comment]
Thanks, this should be fixed.
