### ISSUE TITLE
Feature proposition: handle zooming in and out differently

### ISSUE THREAD

**Issue by OliverFrWTFalreadyTakenComeOnNow** [TEdit/Terraria-Map-Editor#1607]
Hello, TEdit 4.7.4 here, on a Windows10 PC, Geforce Ti750, system DPI at 125% and not the default 100%, loading a Terraria 1.4.3.6 map, but been observing that behaviour ever since using TEdit, which puts us 6 monts prior.

I wouldn't call it a bug report, it's more like a feature/improvement proposition.

If you don't understand what I mean (I'm not sure I chose the right words), or you don't face the same issue yourselves, just ask, and I'll record things on video to illustrate it better.

**Context and reproduction**: 

Root of the issue, it's just that, prior to zooming in and out, TEdit appears to be arbitrarily deciding where the "middle" will be.

When having a map open in TEdit, when I zoom in or zoom out with the central roller on my mouse, the program does NOT focus the center of the map on a recognizable element. Neither on the location where my mouse pointer was, nor on the location that used to be at the center of my TEdit map display. Zooming out, this makes it very hard to keep track of where is located what we were seeing in close up, two mouse scrolls, and good luck finding it unless it's a huge structure.
Imagine I have a chest in mind. It's in the middle of the TEdit vizualization window. I zoom out once, it's now in the upper left corner. Or bottom right corner. No idea how it's decided. I zoom out twice, it's now impossible to predict where the chest is located anymore on the TEdit display.

And yet, there's some logic with how TEdit handles zoom, I simply do not get which it is. 
If I do NOT move my mouse pointer at all, I can alternate full zoom in and zoom out multiple times, we'll be back to the same location displayed. That location will neither be the former initial location of my mouse pointer, nor the former location of the middle of the TEdit map display, but once the program has decided on what that spot is, alternating zooming in and out will not make us stray off its location.
Same with the "+" and "-" buttons in the left column in the user interface: it's not a mouse scroll issue, the zoom buttons yield the same results, arbitrarily choosing a new "middle" but then sticking to it.

**Feature proposition**: 

Split between (1) using the mouse to zoom, and (2) using the UI's + and - buttons to zoom.

(1) When using the mouse scroll, that zooming in and zooming out are systematically centered on the mouse pointer' location 

(2) When using the UI's "+" and "-" buttons in the left-side column, that the current middle of the display before hitting those buttons remains the new middle of the screen's display after zooming.

(Humble apologies, this suggestion took far too long to read, I struggled to find how to express my idea without being too confusing, sorry)

**Comment by BinaryConstruct** [comment]
Have you tried using the mousewheel + shift zoom mode? This is the alternative method and can be set at the default.

**Comment by OliverFrWTFalreadyTakenComeOnNow** [comment]
I didn't know of this Shift effect, thank you, first! Testing follows,

*

**With the shift key pressed, I tested with the UI's + and - buttons**.

+
-
examine screen, remember what it's like. Do not touch mouse at all
+ - + - + -, etc.
still the same
Move the mouse
+ - 
Different location now

*

**With the Shift key pressed, testing with the mouse scroll**,

I notice the effect of Shift. Now, as long as I do NOT move at all my mouse pointer, and zoom out with the mouse, what was the the center of the display, stays on the center of the display.
Much different from before, when what was at the center was pushed away in some apparently randomly picked corner.

Way as I understand it, the "point of focus" is locked as soon as the Shift key is pressed and the move doesn't mouse, zooming out and back in takes us back to the same spot and that spot stays in the middle of the display.
Good, what I needed, thank you!

However, moving the mouse pointer even a single pixel during one of the zoom out test steps redefines a new central locked location where the pointer is.
In that case, maybe have the lock location become intangible, impossible to change, for as long as Shift remains pressed? Otherwise, we're led to believe it's a bug and not a feature?

**Comment by RussDev7** [comment]
Honestly I found that the `mousewheel + shift zoom mode` mode solves this issue.
