### ISSUE TITLE
Exporting schematics fails

### ISSUE THREAD

**Issue by Quiantkbw123** [TEdit/Terraria-Map-Editor#1609]
# READ THIS FIRST
- **Sprite Issues?** See https://github.com/TEdit/Terraria-Map-Editor/wiki/Install-Requirements#for-sprite-viewing
- **Won't Start?** See https://github.com/TEdit/Terraria-Map-Editor/wiki/Troubleshooting#application-launch-or-map-loading-issue
- **Map not loading?** See https://github.com/TEdit/Terraria-Map-Editor/wiki/Troubleshooting#application-launch-or-map-loading-issue

# If the Wiki did not help, fill out this form completely! If you are missing steps to reproduce your issue will be closed. Thank you.

**Before Submitting an Issue**
* If you are having issues loading a world, please attach it to the current version world thread (see pinned issues).
* For a crash, please check the log.

**Describe the bug**
What is the problem.
I can't export schematics and load them in

1. copy a selection
2. export the selection
3. "the given key was not present in the dictionary" error occurs (pic 1)
4. delete "exported" selection from clipboard
5. import schematic
6. selecting the exported schematic produces "unable to read beyond the end of the stream" error (pic 2)
7. schematic isn't loaded

**Expected behavior**
I expected the exported selection to save without errors and to be able to import it later on.

**Screenshots**
Add screenshots to help explain your problem.
![1st pic](https://user-images.githubusercontent.com/101226549/157344717-52ac58d3-2a5a-4485-bc84-cfc9efb1e9ff.PNG)
![2nd pic](https://user-images.githubusercontent.com/101226549/157344723-0a6deb5f-6ede-4ddb-8c6f-481aa94af7d8.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 
 - Terraria Version v4.7.4

**Comment by MaksDragon** [comment]
+ have this problem too

**Comment by AymaxLi** [comment]
i have this problem too

**Comment by nojonsko** [comment]
I think an update broke the schematic feature again, because I think it was fixed in 4.7.1.
I tried exporting a schematic in 4.7.1 as well and it didn't work either.

**Comment by nojonsko** [comment]
tried the new 4.7.5 update, it still doesn't seem to export properly
the schematics that are provided with tedit seem to import fine, i wonder why?

**Comment by dalgrim** [comment]
I have this exact same issue. It's been present for the past few releases.

**Comment by RussDev7** [comment]
I have juat pushed a merge that will finally fix this issue. Next release this issue will be resolved.
