### ISSUE TITLE
Nintendo 3DS Legacy Importing Glitched

### ISSUE THREAD

**Issue by Flipnoodle** [TEdit/Terraria-Map-Editor#1611]
When attempting to import Nintendo 3DS worlds (.w) into TEdit, the program will press forward to no avail. None of the proper data will load.

Run on:
 - New Nintendo 3DS (Using TEdit on Windows 10)
 - TEdit 4.7.4
 - Terraria 3DS 1.05

Take these two perfectly fine Terraria 3DS savefile as an example. If anymore, freshly generated files are required, I'm willing to give. I just want to continue my world on PC.

[v2.zip](https://github.com/TEdit/Terraria-Map-Editor/files/8317259/v2.zip)

(If exporting as .w for 3DS again would be possible too, I'd love that!)

**Comment by RussDev7** [comment]
The .w files are not officially supported as of now.

**Comment by RussDev7** [comment]
> I see. By “as of now”, do you mean you’re at least _planning_ at some point to add it? Fair enough if you’re not. 3DS versions of games are kinda dead in the ground at this point.

No discussions have been made for it that I am aware of. For TEdit to make a compatibility for something it is either donated from a git push or their has to be a demand for it. It would require a bunch of effort to make a stable build that caters to both vanilla and 3ds. If anything new comes up i'll reopen this.
