### ISSUE TITLE
Not an issue, just a question 

### ISSUE THREAD

**Issue by Xanthor** [TEdit/Terraria-Map-Editor#1612]
I'm in the process of repairing a hard drive that the PCB fried last year. Drive lasted a good 10 years and took forever to find a PCB for the same model. Moving the bios chip over will be the hard part lol. 
Anyways, my goal is to upgrade my old world's to 1.3, and it dawned on me there was an issue back in the days of worlds with 1000+ chests bugging out if edited. Was wondering if that ever got fixed? It was a game issue, not Tedits, but figure this is the best place to ask, especially if anything new propped up I should be aware of. Thanks again, and very very glad this utility still exists!!! It's impressive to see a developer outlast me and my equipment lol.

**Comment by BinaryConstruct** [comment]
It depends on the version of the world file.

Newer worlds (and Tedit) support more chests. Older worlds are still limited to 1k chests.
