### ISSUE TITLE
Terraria T-Edit "Loading Failed... No Backup Found".

### ISSUE THREAD

**Issue by BzzAA** [TEdit/Terraria-Map-Editor#1614]
Okay so I am trying to copy and paste a build from one world to another. Everything in TEdit works fine but when I try and load the world up in-game it doesn't save what I did in TEdit. I have the latest version. I have saved it 20 times, renamed the files from TEdit to .wld and .wld.bak. I have tried every suggestion there is online with no fix. Can I please get assistance ASAP?

**Comment by RussDev7** [comment]
Sorry for the late response, is the world modded (TModloader)?
