### ISSUE TITLE
Save as v1.4.0，then I open with TEdit v4.0.0, it panic

### ISSUE THREAD

**Issue by Yonio-Lee** [TEdit/Terraria-Map-Editor#1615]
**Describe the bug**
What is the problem.

1. Load a map by TEdit v4.7.5
2. Save as terraria v1.4.1
3. Load step2 by TEdit v4.0.0
4. TEdit v4.0.0 panic

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: TEdit 4.0.0
 - Terraria Version:  v1.4.3.6  saved as v1.4.1 by TEdit 4.7.5

here is the panic log

04-04-2022 12:11:35: Starting TEdit 4.0.0.0 
04-04-2022 12:11:35: OS: Microsoft Windows NT 10.0.19042.0 
04-04-2022 12:11:35: OS Name: Microsoft Windows 10 Education  
04-04-2022 12:11:35: .NET Framework Version: 4.8 or later 
04-04-2022 12:11:36: Terraria v1.4.3.6 
04-04-2022 12:11:36: Terraria Data Path: G:\Steam\steamapps\common\Terraria\Content 
04-04-2022 12:11:36: Creating Undo cache: C:\Users\Yonoi\AppData\Roaming\TEdit\undo_672569578 
04-04-2022 12:12:51: Error - 值不能为 null。
参数名: key
   在 System.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   在 System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   在 TEdit.View.WorldRenderXna.DrawNpcOverlay(NPC npc)
   在 TEdit.View.WorldRenderXna.DrawNpcTexture(NPC npc)
   在 TEdit.View.WorldRenderXna.DrawPoints()
   在 TEdit.View.WorldRenderXna.Render(GraphicsDeviceEventArgs e)
   在 TEdit.View.WorldRenderXna.xnaViewport_RenderXna(Object sender, GraphicsDeviceEventArgs e)
   在 TEdit.UI.Xaml.XnaContentHost.GraphicsDeviceControl.CompositionTarget_Rendering(Object sender, EventArgs e)
   在 System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   在 System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   在 System.Windows.Threading.DispatcherOperation.InvokeImpl()
   在 MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   在 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   在 MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   在 System.Windows.Threading.DispatcherOperation.Invoke()
   在 System.Windows.Threading.Dispatcher.ProcessQueue()
   在 System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   在 System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   在 MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   在 MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   在 System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   在 System.Windows.Application.RunDispatcher(Object ignore)
   在 System.Windows.Application.RunInternal(Window window)
   在 TEdit.App.Main()

**Comment by RussDev7** [comment]
Try using the latest TEdit to load and save your world. We are working on a backward's compatibility thus you do not need to downgrade TEdit to edit older versions.
