### ISSUE TITLE
Unable to purify walls by using biome morph

### ISSUE THREAD

**Issue by QuantumWormhole** [TEdit/Terraria-Map-Editor#1617]
Version: 1.4

**Comment by QuantumWormhole** [comment]
Please help

**Comment by QuantumWormhole** [comment]
It's been 4 days help pls

**Comment by RussDev7** [comment]
I personally have been testing this and see no issues. Can you link some images or even post some wall ID's effected?

**Comment by RussDev7** [comment]
Can confirm this is an issue. After some testing, "natural walls" are not being converted.

In-game using clem, `Crimson 4 (natural) (195)` -> `Rocks 4 (natural) (215)`.

**Comment by QuantumWormhole** [comment]
Thank you.
