### ISSUE TITLE
error while opening a map from v.1.4.3.2 build 863

### ISSUE THREAD

**Issue by abcdboss** [TEdit/Terraria-Map-Editor#1619]
hello im new on this site i playing terraria on my ps5 its the ps4 version and i got this error when im opening the world in the top terraria version can you help me or bring a fix please
![Bild_2022-04-28_002451737](https://user-images.githubusercontent.com/104534084/165641303-049971f4-b47e-480c-8059-4af50d71a53b.png)

the system is in german if you can translate please thanks

**Comment by RussDev7** [comment]
I have just tested a newly generated v1.4.3.2 world. Seems to be perfectly fine. Being it says your current world is "1" I assume its safe to say its corrupted.
