### ISSUE TITLE
4.8.1 Biome Morph Purify broken

### ISSUE THREAD

**Issue by smashgrape** [TEdit/Terraria-Map-Editor#1627]
When using the latest version, I attempted to purify parts of my world using the biome morph tool. Using any size and set to purify the tool would not purify the blocks of any biome. 

Can confirm tool is working on TEdit version 4.7.6

**Steps to reproduce the behavior:**
1. Load world.
2. Click on Biome Morph tool.
3. Attempt to purify blocks.

**Desktop Information**
 - OS: Windows 10
 - Version: 4.8.1
 - Terraria Version: 1.4.3.6

**Comment by RussDev7** [comment]
Just tested this feature. Working as intended with the same information provided within your _Desktop Information_. Would you mind dropping us your world save file? I could do some testing with this as well. Otherwise I do not see any issues with this and see this as closed.
