### ISSUE TITLE
Translation errors

### ISSUE THREAD

**Issue by 777-Scorpion-777** [TEdit/Terraria-Map-Editor#1631]
The Russian translation to the new version of the editor contains errors.
The ones I found are next:

New tool "Crop World"
Instead of "Мир урожая" ->
"Обрезать мир"

Section "Tally", buttons "Load" "Clear", "Complete"
Instead of "Груз", "Ясно", "Полный", "Сохранить", "Имя", "Побежденный", "Близко", "Чат" -> 
"Загрузить", "Очистить", "Заполнить", "Сохранить", "Имя", "Побеждено", "Близко", "Чат" (the last two are not quite correct but they'll not fit into the field otherwise.)

Also, for world seeds:
Drunk World
Good World
Tenth Anniversary
Don't Starve World
Not The Bees World
Crimson

instead of
«Пьяный» мир
Goo World
Десятилетие
Не голодайте мир
Не мир пчел
Кримзон

->
Пьяный мир
Хороший мир
Десятая годовщина
Мир Don't Starve
Мир "Только не пчёлы!"
Багрянец

I tried to edit the file myself, but I didn't figure out how to do it. I hope the one who doing the translation will read and correct it.

 - OS: Windows 10
 - Version of TEdit: 4.8.1
 - Terraria Version: any

**Comment by RussDev7** [comment]
I will look into this thanks!

**Comment by RussDev7** [comment]
This will be merged into next release.

**Comment by 777-Scorpion-777** [comment]
👍
