### ISSUE TITLE
Unhandled Exceptions when saving and exiting out of world

### ISSUE THREAD

**Issue by alvinnm** [TEdit/Terraria-Map-Editor#1633]
[Log_20220509184454780.log](https://github.com/TEdit/Terraria-Map-Editor/files/8655924/Log_20220509184454780.log)

**Describe the bug**
Frequent crashes when saving and exiting a world that has been edited by TEdit. Sometimes crashes randomly when dying or just moving around, but happens most frequently when saving and exiting. DOES NOT HAPPEN 100% OF THE TIME. I don't how to reproduce it all the time, but the game will crash about 50% of the time when I save and exit.

**Steps to reproduce the behavior**
Character dies or just save and exit out of world. Game will crash and world does not save. DOES NOT ALWAYS HAPPEN but is very very frequent.

**Expected behavior**
Game saves and exits normally.

**Desktop (please complete the following information):**
 - OS: Windows 11 Beta Insider
 - TEdit 4.8.1
 - Terraria Version 1.4.3.6

Here is the world and the player I am currently using: [World.and.Player.zip](https://github.com/TEdit/Terraria-Map-Editor/files/8656012/World.and.Player.zip)

**Comment by alvinnm** [comment]
I attached my world and player
[World and Player.zip](https://github.com/TEdit/Terraria-Map-Editor/files/8655928/World.and.Player.zip)
 to this comment as well.

**Comment by RussDev7** [comment]
I will check this out. Thanks for the player and world.

**Comment by alvinnm** [comment]
Thanks for checking it out. I also checked Event Viewer and it says that it's a .NET Runtime error and that the faulting module name is kernelbase.dll. Any help would be appreciated.

**Comment by RussDev7** [comment]
> Thanks for checking it out. I also checked Event Viewer and it says that it's a .NET Runtime error and that the faulting module name is kernelbase.dll. Any help would be appreciated.

Alright so... I have set a macro up to open and close (save & exit) the world. This has run for over 275 times now and I am yet to crash. I have used a freshly generated `My Games\Terraria` and your provided player and world file for the tests.

For testing player death's, I dug a hole at the spawn and put lava so I continuously keep dying. After 45 minutes the game is yet to crash.

After reviewing the log file `Exception: System.IO.IOException: The system cannot find message text for message number 0x%1 in the message file for %2.` is caused from a various of issues. Unfortunately most seems to be outside of .NET applications being able to translate. This means that the best bet is to check Event Viewer and look for the error code and do some research on it. I personally would try to reinstall .NET and maybe the game first.

**Comment by alvinnm** [comment]
Really appreciate the effort to look into the bug! I will definitely look into researching the error on Event Viewer. Tried a bunch of things like repairing/reinstalling .NET Runtime, XNA 4.0, wiping the Documents folder and reinstalling Terraria. Might just be something up with my system that I need to look into. Thank you so much again!
