### ISSUE TITLE
Create .MAP Files using world information

### ISSUE THREAD

**Issue by antonioleonhu** [TEdit/Terraria-Map-Editor#1641]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
A ".MAP File" is the minimap data for a world for a certain character. I would like TEdit to have the functionality to creat a .MAP file through the map information available. This would allow a character to have the whole world explored.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by RussDev7** [comment]
So most of the code for making these files is from coping pre-rendered in-game maps and saving the map data to a file. I still attempted to do this however from raw code, and I believe it could be possible. I will leave this topic open for a while.
![105600_20220527194259_1](https://user-images.githubusercontent.com/33048298/170838286-ebdfff7e-c1b2-4e8e-aca8-eb3dccf7aa36.png)

**Comment by RussDev7** [comment]
This will be thought of for a future release maybe. For now I will close this.
