### ISSUE TITLE
cant open worlds

### ISSUE THREAD

**Issue by Gravitrax39** [TEdit/Terraria-Map-Editor#1643]
when i open tedit and click on "open" it gives an unhandled exception then crashes. in my attempts to fix it i did two things so far, changed the AltC in the settings to be where terraria is (i have it in d drive), which then caused it to crash upon opening, but from looking at the logs i found that it disliked that pina colada had the n with the little "~" over it so i changed that to a normal n. now were back to crashing when i click "open" to try and select a world.

1. Open Tedit
2. hover over file
3. click open

**Expected behavior**
i click open and it opens a file to select which world i want to edit

 - OS: Windows 10
 - Version: Tedit 4.8.5
 - Terraria Version: 1.4.3.6

Error log:
[TEditLog_20220531230608.txt](https://github.com/TEdit/Terraria-Map-Editor/files/8810971/TEditLog_20220531230608.txt)

**Comment by RussDev7** [comment]
Can you please share your world file?

**Comment by Gravitrax39** [comment]
Ah, sorry about that. and sorry for the late response, i just got home. here are the files

[World files.zip](https://github.com/TEdit/Terraria-Map-Editor/files/8819411/World.files.zip)

**Comment by RussDev7** [comment]
So using the world provided, and all the steps in your post, I cannot get a crash or error.
![Capture](https://user-images.githubusercontent.com/33048298/171552626-ace6444b-3c0c-45da-891d-6f3cbd637b60.PNG)
Try loading the application and world from the same drive.

**Comment by Gravitrax39** [comment]
ok i think i may know the problem. both the tedit and terraria steam files are in the d drive. the my games terraria file where the worlds are saved is also in the d drive, but i have a symlink in the documents folder (in the c drive) that links to the my games folder in the d drive. so maybe tedit thinks that the world folders are in the c drive and it isnt able to follow the link to the d drive so it just doesnt work.
