### ISSUE TITLE
Wiki Sprite Actuation Incomplete Information

### ISSUE THREAD

**Issue by Antonoir** [TEdit/Terraria-Map-Editor#1644]
# READ THIS FIRST
- **Sprite Issues?** See https://github.com/TEdit/Terraria-Map-Editor/wiki/Install-Requirements#for-sprite-viewing
- **Won't Start?** See https://github.com/TEdit/Terraria-Map-Editor/wiki/Troubleshooting#application-launch-or-map-loading-issue
- **Map not loading?** See https://github.com/TEdit/Terraria-Map-Editor/wiki/Troubleshooting#application-launch-or-map-loading-issue

# If the Wiki did not help, fill out this form completely! If you are missing steps to reproduce your issue will be closed. Thank you.

**Before Submitting an Issue**
* If you are having issues loading a world, please attach it to the current version world thread (see pinned issues).
* For a crash, please check the log.

**Describe the bug**
Incorrect/Unclear information found on the Wiki,

In World Component/Actuator
It is possible to place actuator on a sprite which can be usefull for platform and teleporter.

While the Wiki doesn't explicitely mention it's impossible to place Actuator on Sprites, It would be nice for it to be mentionned and explained on the wiki.

1. Place any Sprite
2. Select the Pencil or Brush tool
3. Uncheck the Tile option
4. Make sure Wall And Extra are toggled On
5. Select Sky Block for Wall, and disable mask
6. In Extra Select Is Actuator ('Actuator/Tile InActive' can be either on or off)
7. Use Pencil/Brush on Sprite

**Expected behavior**
Platform and teleporter connected to Actuator work as intended
Other Sprites tested (Bookcase, Heavy Workbench, Candelabra, Candle, Chest, Bed, Number Statue) are unaffected
    Note, if Selected 'Actuator/Tile InActive', Sprite will behave as actuated tile (passtrough[ex, cant stand on bookshelf] and darker) until 
              first activation where they regain normal behaviour and wont change back to actuated.
    Note, Its possible to set sprite to actuated state without placing actuator and to partially actuate a sprite

**Screenshots**
Add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Version [Tedit 4.8.5]
 - Terraria Version [e.g. 1.4.3.6]

**Comment by RussDev7** [comment]
I will have this revived thank you.
