### ISSUE TITLE
World is not saving after editing

### ISSUE THREAD

**Issue by WesDev132** [TEdit/Terraria-Map-Editor#1647]
I am trying to edit 2 heart statues into a world cause I'm too lazy to find them myself and i cant find any seeds for the current version of terraria (1.4.3.6). But every time i try to, the world doesn't save after editing it and clicking the save button, then when i go to play the world, the statues aren't there. i have the latest version of TEdit I think (4.8.5). Do i also need to download the two source codes and do something with them or are they irrelevant.

**Comment by BinaryConstruct** [comment]
Be sure that Terraria is closed when editing.

**Comment by BinaryConstruct** [comment]
Also, check the wiki for more tips https://docs.binaryconstruct.com
