### ISSUE TITLE
World isn't saving

### ISSUE THREAD

**Issue by TheCristianBoss222** [TEdit/Terraria-Map-Editor#1650]
So, I was trying to purify my world because it was completely full of corruption and hollow, I cleaned most of it using the Biome Morph Tool, and then saved the world that I just made changes on. When I entered Terraria, the world didn't clean at all. I tried several amount of times to do the same thing, thinking it would be just a saving error or malfunction, turns out it never worked, can somebody help please? Note that I always had Terraria closed when editing the world.
Also, I wanna mention that I use cracked Terraria, hope that isn't the problem at all.

**Comment by RussDev7** [comment]
TEdit does not support cracked clients. Make sure to try the latest release.
