### ISSUE TITLE
The "y" in Journey Game Mode selector is cut off

### ISSUE THREAD

**Issue by Kyx-001** [TEdit/Terraria-Map-Editor#1652]
**Bug Description**
The "y" in "Journey" selector for "Game Mode" in "World Properties" tab is cut off at the bottom

**Steps to reproduce the behaviour:**
1. Open up TEdit
2. Open up a world
3. Go to World Properties
4. Put it on Journey mode

**Expected behaviour**
the "y" to be shown in full

**Screenshots**
![image](https://user-images.githubusercontent.com/65960423/182971997-4c612649-ed85-432b-b3e3-a449e8613a55.png)

**Environment**
 - OS: [Windows 11 build 25169]
 - Version [TEdit v4.8.5]

**Comment by RussDev7** [comment]
Thank you for pointing this out.
