### ISSUE TITLE
Worlds created in versions 1.3+ no longer load

### ISSUE THREAD

**Issue by TollyH** [TEdit/Terraria-Map-Editor#1659]
**Describe the bug**
After building the most recent commits, 1.3 and 1.4 worlds no longer load, giving an "Invalid Header" error almost immediately. The bug seems have to come from something in commit 2d12cc0558567da388928c74a6eb41db2f01eb93, though I can't say for certain.

1. Load any world created in 1.3+, the included test world files cause the issue for example.

**Screenshots**
![image](https://user-images.githubusercontent.com/34184902/187798690-008e11ab-8bcd-4c4d-b3b6-c6fda79c8c35.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Home x64 19044.1949
 - Version TEdit 4.9.0 (f2b464294ab7ff1a91de2e6ef63aac396f7e1497)
 - Terraria Version 1.3.0.1 - 1.4.3.6

**Comment by RussDev7** [comment]
Was this using the release version or the current code released on github?
