### ISSUE TITLE
unable to read the world after update

### ISSUE THREAD

**Issue by justry666** [TEdit/Terraria-Map-Editor#1664]
tedit is a very nice editor, i have been using it for a long time and it worked fine until yesterday with the labor of love update i get this.

There was an error reading the world file.
This is usually caused by a corrupt save file or a world version newer than supported.
TEdit v4.10.0
TEdit Max World: 248
Current World: 269
Do you wish to force it to load anyway?
WARNING: This may have unexpected results including corrupt world files and program crashes.
The error is:
无法在流的结尾之外进行读取。
System.1O.EndOfStreamException：无法在流的结尾之外进行读取。在System.IO._Error.End@fFile0
在 System.IO.BinaryReader.ReadString0
在TEdit.Terraria.World.LoadHeaderFlags(BinaryReader r, World w, Int32 expectedPosition, TextWriter debugger)在 TEdit.Terraria.World.LoadV2(BinaryReader b, World w, TextWriter debugger)
在 TEdit.Terraria.World.LoadWorld(String filename, Boolean showWarnings)

**Comment by SonicMaster519** [comment]
Did you read the error? It's because you're using a newer version of Terraria that TEdit doesn't support at the moment. Please be patient as I'm sure it will be updated soon.

**Comment by RussDev7** [comment]
We have been tracking this thanks!

**Comment by justry666** [comment]
Thank you for your timely reply. I think the problem may be caused by something else and the latest version can solve the problem

**Comment by hufang360** [comment]
The 1.4.4 is updated.

**Comment by RussDev7** [comment]
Tedit 4.11 closes this post.
