### ISSUE TITLE
World load failed

### ISSUE THREAD

**Issue by Verepone** [TEdit/Terraria-Map-Editor#1671]
**What is the problem.**
After editing a world and saving the file i cant load into the world on terraria and get an error saying failed to load

**Steps to reproduce the behavior:**
1. Edit a world in tedit
2. Save the world file
3. Try to load into the world on terreria

**Expected behavior**
It should load into the world but im getting an error loading

![image](https://user-images.githubusercontent.com/114864174/193455735-8a08487a-ea7a-437b-a1b0-9cf3a5edc14a.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 4.11.0-beta
 - Terraria Version 1.4.4.2

In the case that you want my world file here it is: 

[Neglected_Harbor.zip](https://github.com/TEdit/Terraria-Map-Editor/files/9692633/Neglected_Harbor.zip)

**Comment by RussDev7** [comment]
What within TEdit did you change to reproduce this error?

**Comment by Verepone** [comment]
I removed 2 floating islands and moved a floating island with a huge puddle in it closer to the ground and i was going to replace it with shimmer liquid in game

**Comment by Verepone** [comment]
no matter what i do even if i add 1 dirt block in the air  and only that it still doesn't load

**Comment by RussDev7** [comment]
Would you mind attaching the world file you saved with TEdit.

**Comment by RussDev7** [comment]
> no matter what i do even if i add 1 dirt block in the air and only that it still doesn't load

Do you happen to have a copy of the original file still? Even the .TEdit file works.

**Comment by DerpNebulae** [comment]
Saving will not work because TEdit does not currently support Terarria 1.4.4+ worlds.

**Comment by Moonwhisper45** [comment]
TEdit doesn't have 1.4.4 support yet. I really wish it did, and I'm sure It's being worked on.

**Comment by XORandom** [comment]
In order to make the world unsuitable for terraria, you do not need to edit anything in TEdit, just open world and click save.

When reopened, the world will be like this:
![Screenshot_7](https://user-images.githubusercontent.com/40043238/193479571-5cf8b900-3ce4-435d-8904-269858b01539.png)
![Screenshot_8](https://user-images.githubusercontent.com/40043238/193479574-a5770b69-8399-43c7-bfd3-c154db767bea.png)

**Comment by RussDev7** [comment]
> TEdit doesn't have 1.4.4 support yet. I really wish it did, and I'm sure It's being worked on.

It does support 1.4.4 in the latest release.

**Comment by RussDev7** [comment]
> In order to make the world unsuitable for terraria, you do not need to edit anything in TEdit, just open world and click save.
> 
> When reopened, the world will be like this: ![Screenshot_7](https://user-images.githubusercontent.com/40043238/193479777-fc6f2a25-f3c6-4aa3-9932-6c29048c0643.png)
> 
> ![Screenshot_8](https://user-images.githubusercontent.com/40043238/193479785-2b24cd31-ca9c-47fd-8e20-8695167cc429.png)
> 
> The same thing happens when I save a file with a different name without overwriting the original one.
> 
> ![Screenshot_11](https://user-images.githubusercontent.com/40043238/193480280-192be0c2-fa3a-4eda-ad83-4c635b645d90.png)
> 
> To some extent, it's even beautiful, it's a pity it won't open in the Terraria
> 
> ![Screenshot_10](https://user-images.githubusercontent.com/40043238/193479794-975c347a-7405-45fd-981d-e640f9b81001.png)
> 
> World File, Before corruption:
> 
> [Barton_v22.10.03.zip](https://github.com/TEdit/Terraria-Map-Editor/files/9693747/Barton_v22.10.03.zip)
> 
> After Corruption
> 
> [Barton.zip](https://github.com/TEdit/Terraria-Map-Editor/files/9693754/Barton.zip)

Thanks for this.

**Comment by Xenobellow** [comment]
Same error loading world. Using Beta2
I didn't do any block placement. Just save.
OS: Windows 10 Pro
Version 4.11.0-beta2
Terraria Version 1.4.4.2
<img width="1920" alt="Screenshot 2022-10-04 092704" src="https://user-images.githubusercontent.com/115019496/193846322-8c3dd73f-9af7-46ca-b614-677ba25f21a3.png">
