### ISSUE TITLE
The blocks in the plug-in are not being replaced.

### ISSUE THREAD

**Issue by Arkon1209** [TEdit/Terraria-Map-Editor#1674]
World version: 1.4.4.2
TEdit version: 4.11.0-beta

Not replacing ore via plugin. And not just ores. Almost all the blocks are impossible to replace.

![image](https://user-images.githubusercontent.com/114945699/193643060-9cf84ddf-9f31-4b2f-9f1f-e5a8e84f2d40.png)
![image](https://user-images.githubusercontent.com/114945699/193643110-637d3c04-5fd1-45ba-ad64-d6e80f8625f8.png)

**Comment by RussDev7** [comment]
Thanks for the report, will look into it.

**Comment by Arkon1209** [comment]
Everything works. Turns out you should have switched the ores around. Although I think it was different before.
![image](https://user-images.githubusercontent.com/114945699/194177347-8e20e76e-4c03-4153-8682-6aa256d9083e.png)
