### ISSUE TITLE
Unexpected Exception has made schematics not work, and I can't save my progress.

### ISSUE THREAD

**Issue by MakoSorbetto** [TEdit/Terraria-Map-Editor#1675]
I'm trying to build a custom work from scratch using TEdit for the large environmental changes as a passion and until the newest update it's worked perfectly, so I'm wondering what's happening and what to do.

What were you doing when the issue occurred?
- I tried exporting a schematic, and the Unexpected Exception error occurred, closing the application. (I've tried deleting the user config file, I've tried deleting all TEdit files and reinstalling, It changes nothing.)
- Trying to save (any kind, I've tried them all) shows "Validation Complete..." in the bottom corner for several minutes then "World Save Complete..." but if I load the world in Terraria or open the world in TEdit again all my progress goes away.

Steps to reproduce the issue?
1) Clicking Export on a copied blueprint, or Import Schematic or Image. (I believe other actions cause this error but I don't remember completely.)
2) Trying to Save in any fashion

What version of Terraria are you using?

- I have the most recent update, 1.4.4.2 and I'm using Tedit 4.11.0 beta

Attach world file:
 (This is the main world I try to edit but my issues occur on any world, new or older)
[Canvas World.zip](https://github.com/TEdit/Terraria-Map-Editor/files/9700975/Canvas.World.zip)

Thank you for any time, this definitely could be something on my end but I don't know where to start to fix the issue if it is. I've tried what I could find and nothing seems to work for me. Thank you again.

**Comment by RussDev7** [comment]
I was unable to re-create this.

**Comment by MakoSorbetto** [comment]
> I was unable to re-create this.

Any ideas as to why my worlds wont save any of my work?

**Comment by RussDev7** [comment]
> > I was unable to re-create this.
> 
> Any ideas as to why my worlds wont save any of my work?

Try the new bata we released.

**Comment by loacractos** [comment]
i can save world after copy and past few schematics 
when i open it again then all world become **_blank_**. nothing block, liquid, and nothing all in world.

this issue from beta 1 and beta 2.

**Comment by RussDev7** [comment]
Beta 3 is on the way, hopefully this resolves this.

**Comment by loacractos** [comment]
> Beta 3 is on the way, hopefully this resolves this.
with 4.1.1.2:
still empty world after: editing -> save -> load it again

**Comment by RussDev7** [comment]
Fixed now, if issue still exists in our latest updates, let me know I will re-open this.

**Comment by loacractos** [comment]
> Fixed now, if issue still exists in our latest updates, let me know I will re-open this.

4.11.3-beta2: if load an empty edge world: stuck at 'Saving Tiles' -> manual closed Tedit
i try with 'Run as administrator' but nothing change.
![2022-10-10___02](https://user-images.githubusercontent.com/115051699/194803526-e3b9ad4c-01c0-4ca8-ad29-ea7f9b5fa9ca.jpg)

note: dont see error while edit - saving on normal worldgen 1.4.4.4-1.4.4.5. 
so. i  think you can bypass problem 'empty edge world' and focus on new issue. because 'empty world' almost use for storage 'schematic'. i can bring all them to normal worldgen 1.4.4.4
