### ISSUE TITLE
[UI] IsHouse filter

### ISSUE THREAD

**Issue by YokujinKaze** [TEdit/Terraria-Map-Editor#1685]
utilize IsHouse tag to filter safe+natural walls

**Additional context**
![image](https://user-images.githubusercontent.com/32940095/193966727-ba74c2c4-edf7-4291-bd2e-b55864a3d993.png)

**Comment by RussDev7** [comment]
I will talk this over with some people thanks for the recommendation. I will re-open this when something comes up.
