### ISSUE TITLE
[UI] simplified names toggle

### ISSUE THREAD

**Issue by YokujinKaze** [TEdit/Terraria-Map-Editor#1687]
**Is your feature request related to a problem? Please describe.**
a toggle somewhere in the settings that would use ingame item names or simplified names

1.4.4 added craftable natural walls like: cursed blue dungeon brick, some people either dont like the naming scheme or dont know what the item is

the toggle would either use the item names as is provided by the game or make them simplified; removing prefixes such as cursed, treacherous, invested and adds (natural) as suffixes

examples:
treacherous sandstone > sandstone (natural)
invested spider wall > spider wall (natural
cursed dungeon wall > dungeon wall (natural)
...

**Comment by RussDev7** [comment]
I tried to make this argument before they changed it but it got overlooked. You're more then welcome to fork and edit the settings.xaml and create a pull request.

**Comment by YokujinKaze** [comment]
wdym?
i can add the other name variant easily but without a toggle in some preferences setting it wouldnt do much
