### ISSUE TITLE
Unable to morph Crimson and Corruption Jungle Grass types to Purify and vice versa.

### ISSUE THREAD

**Issue by Declava** [TEdit/Terraria-Map-Editor#1688]
**Describe the bug**
Unable to morph Crimson and Corruption Jungle Grass types introduced in 1.4.4 to Purify and vice versa.

1. Open a world in TEdit.
2. Head to Biome Morph on the left sidebar.
3. Set Morph to Biome to Crimson, Corruption, or Purify.

**Expected behavior**
That the given Jungle Grass type morphs into a different, yet desired type.

**Screenshots**
![TEdit Biome Morph](https://user-images.githubusercontent.com/63688300/193996158-e2433eca-8672-445a-9e51-6e53f2c61fb1.gif)

**Desktop:**
 - OS: [Windows 11]
 - Version [TEdit 4.11.2]
 - Terraria Version [1.4.4.4]

**Comment by RussDev7** [comment]
These grasses are new I believe, they have to be added in.

**Comment by Declava** [comment]
> These grasses are new I believe, they have to be added in.

Yes, added in 1.4.4. Perhaps an oversight?

**Comment by RussDev7** [comment]
> > These grasses are new I believe, they have to be added in.
> 
> Yes, added in 1.4.4. Perhaps an oversight?

Not an oversight but rather we haven’t gotten to them yet. I have personally been trying to figure out all the new evil tiles. I onow these grasses exists now but also getting rumors demonite and crimtane now count torwards the world evil. When I get time I can test / implement.

**Comment by RussDev7** [comment]
This issue has been fixed in our latest dev build. Thanks.
