### ISSUE TITLE
Unable to save with a "Validating Complete..."

### ISSUE THREAD

**Issue by Jacie1krece** [TEdit/Terraria-Map-Editor#1695]
**Describe the bug**
The world can't save, instead leaving the saving prograss bar pernamently empty with a "Validating Complete..." message

1. Load a world
2. Click on 'Save'

**Expected behavior**
The world will actually save.

**Screenshots**
![Zrzut ekranu 2022-10-07 175443](https://user-images.githubusercontent.com/33695007/194596422-b5a6e79e-d0fc-4c29-874f-cb33e8d900ef.png)

**Desktop:**
 - OS: Windows 10
 - TEdit:  v4.11.2
 - Terraria: v1.4.4.5

**Comment by mappy11** [comment]
I also had this problem.log file

- _Error - The given key was not present in the dictionary.
-    at System.ThrowHelper.ThrowKeyNotFoundException()
-    at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
-    at TEdit.Editor.Undo.UndoBuffer.SaveTileData()
-    at TEdit.Editor.Undo.UndoBuffer.Close()
-    at TEdit.Editor.Undo.UndoManager.SaveUndo(Boolean updateMax)
-    at TEdit.Editor.Tools.PencilTool.MouseUp(TileMouseState e)
-    at TEdit.ViewModel.WorldViewModel.MouseUpTile(TileMouseState e)
-    at TEdit.View.WorldRenderXna.xnaViewport_HwndLButtonUp(Object sender, HwndMouseEventArgs e)
-    at TEdit.UI.Xaml.XnaContentHost.GraphicsDeviceControl.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)_

**Comment by mappy11** [comment]
still don't know how to fix that

**Comment by RussDev7** [comment]
Resolved in our latest builds. If this issue continues to appear in later builds let me know.

**Comment by mappy11** [comment]
> 

thanks,but some problem occurs,I can't correctly run the PS1 file.
