### ISSUE TITLE
Biom morph does not work

### ISSUE THREAD

**Issue by Kingbrus** [TEdit/Terraria-Map-Editor#1697]
**Describe the bug**
Biom Morph tool does not work

1. Use Biom Morph tool

**Expected behavior**
Biom morphs to set biom

**Screenshots**
----

**Desktop (please complete the following information):**
 - OS: Win 10
 - Version: 4.11.2
 - Terraria Version: 1.4.4.4

**Comment by Aite08** [comment]
all not work...
one use, next does not work=(

**Comment by Kingbrus** [comment]
yea its very inconsistent, I restarted Tedit and it works but next launch it does not

**Comment by Kingbrus** [comment]
Mask mode is even buged cant edit crimson/halow

**Comment by mappy11** [comment]
same

**Comment by OwONaw** [comment]
Yeah it doesnt work anymore for some reson

**Comment by RussDev7** [comment]
Resolved in our latest builds. Thanks.
