### ISSUE TITLE
Biome Paint not working after resizing brush

### ISSUE THREAD

**Issue by Calxcalibur** [TEdit/Terraria-Map-Editor#1704]
The biome paint feature doesn't work after resizing the brush.
What is the problem.

1. Click on Biome Morph tool
2. Change size to something that isn't 20x20
3. Try to paint

Expected behavior:
Biome is painted to the selected biome

Actual behaviour:
Biome is not painted

**Desktop (please complete the following information):**
 - OS: Win10
 - Version: Tedit 4.11.2
 - Terraria Version: 1.4.4.4

**Comment by RussDev7** [comment]
Resolved in our latest builds. Thanks.
