### ISSUE TITLE
Biome Painter wont paint if shimmer is in world

### ISSUE THREAD

**Issue by FenrirUwU** [TEdit/Terraria-Map-Editor#1706]
Biome painter doesn't seem to work on new worlds because of shimmer.

1. Tried to purify crimson, corruption or hallow
2. Doesn't purify nothing happens then breaks.

 - OS: [Windows 10]
 - Version [Tedit 4.11.2]
 - Terraria Version [1.4.4.4]

**Comment by RussDev7** [comment]
This has been fixed in our recent builds. Thanks.
