### ISSUE TITLE
Cannot do anything related to left-click in TEdit

### ISSUE THREAD

**Issue by GoldH2O** [TEdit/Terraria-Map-Editor#1708]
This issue happens in multiple cases. I am simply using TEdit to place sprites or blocks, or to change blocks with biome morph, and it suddenly stops placing anything or changing anything, no matter where I click. Restarting does not consistently fix the issue, and when it does it only works for another second or so. It also doesn't change when I open different worlds.

I am on the latest version of TEdit, on Windows 10.

### Steps to reproduce the issue?
1) Open a world in TEdit
2) Begin placing blocks/sprites/biome morphing
3) stops working at some point here, unaware of exactly why

### What version of Terraria are you using?
Terraria 1.4.4

### Post relevant contents of log or attach log file _**(very important)**_:
[TEditLog_20221008111700.txt](https://github.com/TEdit/Terraria-Map-Editor/files/9740056/TEditLog_20221008111700.txt)

### Attach world file
All of these worlds were tested with the same result, so I do not believe it is a world related issue
https://drive.google.com/drive/folders/1-_OqtvEpvXiDpHmilEg2TTxyrYRou9o_?usp=sharing

**Comment by RussDev7** [comment]
Terraria version 1.4.4 or 1.4.4.5?

**Comment by RussDev7** [comment]
Tested 1.4.4 or 1.4.4.5 in our latest build, seems to be fixed now. If this continues after our next release let me know. I will re-open this.
