### ISSUE TITLE
TEdit Undo Crash

### ISSUE THREAD

**Issue by Brkkmanne** [TEdit/Terraria-Map-Editor#1709]
For some reason, whenever I try to undo in my imported world, my program straight up crashes. It works for generated worlds, but I don't know why it doesn't on SPECIFICALLY this one.  I'd really appreciate an explanation...

[Parkour Parlor.zip](https://github.com/TEdit/Terraria-Map-Editor/files/9740108/Parkour.Parlor.zip)
![image](https://user-images.githubusercontent.com/114095118/194723543-52423471-9137-4b5a-8089-2c4b7aa11996.png)

**Comment by RussDev7** [comment]
This has been resolved in our latest build. Thanks.

**Comment by Brkkmanne** [comment]
Oh, ok. That was quick ! 👍
