### ISSUE TITLE
Issue with anything that uses left-click

### ISSUE THREAD

**Issue by Itchydrix** [TEdit/Terraria-Map-Editor#1710]
Whenever I try to use the biome morph or use the pencil tool, nothing happens. I have noticed that the morph tool works for a literal second and then refuses to continue morphing. After that, any other tool that modifies tiles (pencil, brush, etc.) refuses to work either. Chest search plugin works perfectly. If I use the select tool and then delete a selection when in this error state, the app crashes and the dialogue box states a fatal exception has occurred. I tried loading a legacy save and the issue did not replicate there, so it only seems to occur on version 1.4.4.5 saves. 

1. Load a terraria version 1.4.4.5. world on TEdit 4.11.2 Latest.
2. Select the Morph Tool and set it to Purify.
3. Attempt to purify Corrupt/Crimson. 
4. Check to see if the tool worked for a second, then refuses to work anymore. 
5. Using the selection tool, select any patch of dirt tiles or other solid blocks.
6. Delete said selection, check if app crashes and releases error message. 

**Expected behavior**
Morph tool working as intended; pencil and brushes placing/ erasing tiles. 

**Screenshots**

![selection error](https://user-images.githubusercontent.com/115372774/194726699-83efa1d3-7edf-4589-87e4-33c30ce05461.png)
![Morph tool error](https://user-images.githubusercontent.com/115372774/194726705-cbad5939-65f0-4ff1-84a4-adc60e079d4b.png)

**Desktop (**
 - OS: Windows 10 
 -  - Version TEdit 4.11.2
 - Terraria Version 1.4.4.5

**Comment by BinaryConstruct** [comment]
1.4.4.5 is not supported. A new version should be out in a day or so.

**Comment by Itchydrix** [comment]
> 1.4.4.5 is not supported. A new version should be out in a day or so.

Thanks for clarifyng!
