### ISSUE TITLE
Tools/biome morph stop working during use

### ISSUE THREAD

**Issue by prochiral** [TEdit/Terraria-Map-Editor#1711]
**Describe the bug**
The problem is that all tools stop working shortly after beginning world editing. Problem may be caused by use of biome morph tool, unclear. Problem occurs w/ one world (which I think was created in Terraria v 1.4.1.2, but not in another world (shows as a legacy world, possibly from Terraria 1.3.x). Issue persists after program restart and restarting computer.

1. Use biome morph tool.
2. Biome morph tool stops working after a delay of about one second.
3. Other tools have stopped working (no response after click/click+drag), however, program does not seem frozen. 

**Expected behavior**
I expected the tools to work like normal.

**Screenshots**
Screenshot shows partially morphed biome. 

**Desktop (please complete the following information):**
 - OS: Windows 10 Home 21H2 Build 19044.2006
 - Version Tedit 4.1.1.2
 - Terraria Version 1.4.4.5

I am attaching log file and problematic world file. Please let me know if you would like me to undertake any more troubleshooting or investigation steps. Please let me know if I've submitted this wrong.

Thank you very much for this tool, I greatly enjoy using it. 
![Screenshot](https://user-images.githubusercontent.com/85304991/194732927-80091708-cd9d-43eb-94f1-8a79d960ccf2.PNG)
![Zip of world and log](https://github.com/TEdit/Terraria-Map-Editor/files/9740551/Bugreport.zip)

**Comment by MobiuSRIT** [comment]
Likely same issue as [1688](https://github.com/TEdit/Terraria-Map-Editor/issues/1688)

**Comment by RussDev7** [comment]
This issue has been fixed in our latest dev build. Thanks.

**Comment by prochiral** [comment]
Thank you guys! I'll let you know if it's not fixed in the next update.
