### ISSUE TITLE
Issue Saving Worlds

### ISSUE THREAD

**Issue by falconz204** [TEdit/Terraria-Map-Editor#1712]
Whenever I try to make any changes to my world, I get stuck on "validating complete..." and an empty loading bar. I have tried reinstalling TEdit and other possible solutions but have gotten no where.

https://user-images.githubusercontent.com/115382769/194734515-e4c668f6-f07c-498f-b133-7a439921bfac.png

I am on Windows 10 with the newest version of both Terraria and TEdit. I am not using tModLoader.

**Comment by BinaryConstruct** [comment]
There is an updating in progress for 1.4.4.5 that will be out soon. Check back tomorrow for updates.

**Comment by BinaryConstruct** [comment]
https://github.com/TEdit/Terraria-Map-Editor/releases/tag/4.11.3-beta2 This is a beta for supporting 1.4.4.5
