### ISSUE TITLE
Crash when deleting selected area, also cant save world

### ISSUE THREAD

**Issue by Kingbrus** [TEdit/Terraria-Map-Editor#1716]
**Describe the bug**
Tedit crashes when i try remove selected area, even when selecting air or one block. Cant also save world, changes i do are not saved, when saving. On any world (Weird, i broke tedit i guess)

1. Select area
2. Use "Delete selection" tool
3. Enjoy crash :D

**Expected behavior**
Selected area is deleted. World is saved

**Screenshots**
![dfgfgdfgdfg](https://user-images.githubusercontent.com/97199006/194745004-810ed19f-6e36-44d7-a6ed-0a3c84bb3307.PNG)
[TEditLog_20221009100655.txt](https://github.com/TEdit/Terraria-Map-Editor/files/9741059/TEditLog_20221009100655.txt)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 4.11.0-beta and 4.11.2
 - Terraria Version 1.4.4.5

**Comment by Niko-Star-boop** [comment]
I have the same problem, and i can't paste anything with the clipboard

**Comment by WerdoGuy** [comment]
me to, can copy but then can't paste

**Comment by BinaryConstruct** [comment]
https://github.com/TEdit/Terraria-Map-Editor/releases/tag/4.11.3-beta2 is the first beta to add support for 1.4.4.5
