### ISSUE TITLE
Can't edit anything.

### ISSUE THREAD

**Issue by Sprity777** [TEdit/Terraria-Map-Editor#1718]
So, I load my Don't starve world, and I cant purify, edit, or do anything. after one mouse movement, the program freezes inside and it won't let me do anything. Can't erase, place, purify, edit, place or remove anything. Also it wont save,and it still locked up after a new world gets loaded in.
latest Terraria version and TEdit.

Also when I try "undo" it crashes
![kép_2022-10-09_121328152](https://user-images.githubusercontent.com/109874924/194751004-9539db91-097a-4946-a4d0-867051c9846d.png)

**Comment by WerdoGuy** [comment]
I have the same. if I copy in a new world I cant paste and when I try to undo it crashes.

**Comment by CamaleaoFormal** [comment]
i have the same, I can only edit once and after that TEdit doesn't work anymore.

**Comment by pinkyyroo** [comment]
I'm having the same problem as well, current updates for both terraria and tedit.

**Comment by Kingbrus** [comment]
tru

**Comment by BinaryConstruct** [comment]
1.4.4.5 support has only just been added with the latest update.

https://github.com/TEdit/Terraria-Map-Editor/releases/tag/4.11.3-beta2
