### ISSUE TITLE
[Feature] Swap torch sprites with biome morph

### ISSUE THREAD

**Issue by okay-lol** [TEdit/Terraria-Map-Editor#1720]
In the current build, biome morph [ignores torches](https://user-images.githubusercontent.com/58677633/194775583-561db308-5d73-497e-91cc-e86cb4e6ffcb.gif) and swaps only tiles, walls, and decorations.

It's just a minor quality-of-life thing for people who like to maximize their torch luck, but would it be possible to add an option to make biome morph affect torches as well? So that if you purify an area with a crimson torch, or otherwise change the biome with biome morph, the torch will also change to reflect the new biome?

**Comment by RussDev7** [comment]
The in-game clentaminator does not do this. The goal of the morph tool is to make is exactly as it would function in-game. You might want to refurbish this request as something for the tile drop-down or sprite masking.

**Comment by okay-lol** [comment]
Ah, it makes sense that it was designed to mimic the clentaminator. I don't honestly know enough about the tool to write a coherent feature request for sprite masking or the like, so I'll just close this and leave it at that.
