### ISSUE TITLE
Undo not working

### ISSUE THREAD

**Issue by Quiantkbw123** [TEdit/Terraria-Map-Editor#1721]
# READ THIS FIRST
- **Sprite Issues?** See https://github.com/TEdit/Terraria-Map-Editor/wiki/Install-Requirements#for-sprite-viewing
- **Won't Start?** See https://github.com/TEdit/Terraria-Map-Editor/wiki/Troubleshooting#application-launch-or-map-loading-issue
- **Map not loading?** See https://github.com/TEdit/Terraria-Map-Editor/wiki/Troubleshooting#application-launch-or-map-loading-issue

# If the Wiki did not help, fill out this form completely! If you are missing steps to reproduce your issue will be closed. Thank you.

**Before Submitting an Issue**
* If you are having issues loading a world, please attach it to the current version world thread (see pinned issues).
* For a crash, please check the log.

**Describe the bug**
Undo (ctrl + z) stopped working or is at least inconsistent in working. I'm trying to undo something but nothing is happens, I believe it worked in version 4.11.1 but not 4.11.0 or at least something happened that stopped it from working. Not sure if has anything to do with the erase keybind (z) or if it's something else. Additionally if you "force" undo using the left toolbar it crashes (not sure where to find logs).

*It seems to be based on the world, as saving it under another named fixed it after a bit (possibly explaining the inconsistency between versions). If loading a 'good' save after coming from a 'broken' one I have to select something, delete and then I can undo stuff.

*couldn't attach a world file and couldn't find the 'current version world thread'

UPDATE
Seems to be caused by editing a map in game and then reloading the change in tedit. It also makes it so you can't save in tedit and made the select tool stop working (till I reloaded the map again, though that just fix the select tool)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Version [4.11.2]
 - Terraria Version [e.g. 1.4.4.5]

**Comment by RussDev7** [comment]
Is this working in TEdit 4.11.3-beta2?

**Comment by Quiantkbw123** [comment]
Seems to have been fixed in 4.11.3 though I can't confirm what caused the issue in the older versions (to see if the bug want away and came back or not). 

I'll see if I can test those older ones to see if the bug came back and want away several times or was just fixed in this update.

**Comment by Quiantkbw123** [comment]
Seems like it was bugged for both previous versions (with the inconsistence being based on reloading an edited file), with it being fixed in the current version.

**Comment by RussDev7** [comment]
Glad it’s working now!
