### ISSUE TITLE
An autosave issue

### ISSUE THREAD

**Issue by hououkira** [TEdit/Terraria-Map-Editor#1729]
The autosave will continue working even if the map has not been edit, It may casue memory leak.

1. Opened any world file.
2. Did not close the TEdit, and lasted for a long time.

Beacuse of the need of viewing the whole map of the world, I usually not close the TEdit, and after 5 days, the system notice me of the low system storage. And I found 27GB of the TEdit autosave file. It saves for every 3 minute and total 2437 times.

![( (N~0HI(1RI`U6~`TQU 9](https://user-images.githubusercontent.com/81728409/195386574-07b9a7f9-efd5-47ef-b2bf-979b60024424.png)

As you see I did't edit anything, but the world had save again and again, I know the autosave is important, but not saving while the world is not edited is absolutely okay. What's more, a num limit of the autosave file may avoid this kind of issue, as it can override the oldest file.

 So I don't know if there's a lot guy got the same issue, but this can easelly reproduce while normal use, so I guess it's better to fix this. Thanks!

**Comment by RussDev7** [comment]
You can disable this from the `File > Enable Autosave`. Might look into adding a feature not to save it if the file has not changed.
