### ISSUE TITLE
Painting Tiles

### ISSUE THREAD

**Issue by Xenobellow** [TEdit/Terraria-Map-Editor#1736]
# Illuminant, and Echo coating

**Describe the bug**
Try to paint the illuminant coating on temple, but upon loading the world didn't show up.

1. Open Tedit
2. Click Draw, or Paint. (I did fill)
3. Select illuminant paint (doesn't matter tile, or wall)
4. Paint what ever tiles/walls (Preferably in the dark areas, or night)
5. Save world
6. Load Terraria.
<img width="1920" alt="Screenshot 2022-10-16 161617" src="https://user-images.githubusercontent.com/115019496/196060258-8413b3d8-990a-4b3d-8873-b60fc82b602c.png">

**Expected behavior**
There would be illuminant coating with any color
<img width="322" alt="Screenshot 2022-10-16 193459" src="https://user-images.githubusercontent.com/115019496/196066946-bb9ba24f-de26-4c39-a981-d754fb234c4e.png">

**Extra**
I don't see echo coating as an option to paint, but would be nice addition.
I believe the cause of bug is that after Terraria updated to 1.4.4. They convert illuminant paint to illuminant coating.
Same goes with echo coating.

 - OS: Windows 10 Pro
 - Version Tedit 4.11.3 
 - Terraria Version 1.4.4.5

**Comment by BinaryConstruct** [comment]
Combining with #1719
