### ISSUE TITLE
code update for forest and desert morphers

### ISSUE THREAD

**Issue by YokujinKaze** [TEdit/Terraria-Map-Editor#1744]
we need 2 pieces of new codes to make forest and desert morphs work properly

desert morpher:
if any block turns into sand and there is a non-solid tile (air, sprites) below the block, turn it into hardened sand instead
![image](https://user-images.githubusercontent.com/32940095/196655406-bc008729-7d0c-4a73-a03d-c5373345f960.png)

forest morpher:
if any block turns into dirt and there is at least 1 non-solid tile (air, sprite) in a 3x3 area, turn it to grass instead 
![image](https://user-images.githubusercontent.com/32940095/196655468-ff813ad9-9a43-4bad-b11f-06081bb0e61a.png)

ideally adding that to the json via
"replaceGravity": blockID
"airProximity": blockID

maybe also adding some way to  control which ids get used for surface, ug, caverns

**Comment by RussDev7** [comment]
These are now supported in the latest dev build.
