### ISSUE TITLE
Change world's version 

### ISSUE THREAD

**Issue by Mauroarts** [TEdit/Terraria-Map-Editor#1747]
I just want to change the version of a world to an older version, let's say I have world from the 1.4.4.1 and I want to change it to 1.4.4 version

I'll say that be nice to have it to do that, put an option in "world properties" that say "world's version" and on the side a button that says the version and when you press it, it display the version you can change it

If there is a way in the program to do that, tell me how

**Comment by BinaryConstruct** [comment]
I'm assuming since this is closed you found the answer. For anyone coming here in the future, use the "Save as Version" from the file menu, or the "Save as" command and select a version from the dropdown.

**Comment by Mauroarts** [comment]
Yes, I find out, thanks for checking out if I find it, have a great day,
afternoon or night
