### ISSUE TITLE
Tally counter fix

### ISSUE THREAD

**Issue by WhiteScorpion7** [TEdit/Terraria-Map-Editor#1752]
In the new version, the editor no longer resets the mob count, but the worlds opened in the old ones remain damaged. Maybe you can create something like a plugin that will copy the mob count from the Bestiary to the Tally counter?

**Comment by pjpollina** [comment]
Seconded, a way to edit the tally manually would be nice, would do it myself if my C# was better.

**Comment by RussDev7** [comment]
Fixed in the latest dev build.
