### ISSUE TITLE
dynasty table is set to 3x2 rather than 3x1

### ISSUE THREAD

**Issue by YokujinKaze** [TEdit/Terraria-Map-Editor#1754]
![image](https://user-images.githubusercontent.com/32940095/197403052-3b35ffc0-10e6-4edd-af99-c069d047de7e.png)

**Comment by BinaryConstruct** [comment]
![image](https://user-images.githubusercontent.com/456755/199641263-23ea556e-995b-4a87-b7f9-49743f81167d.png)

Size override per item is now allowed.
