### ISSUE TITLE
Tedit restarting when trying to do anything with the selector.

### ISSUE THREAD

**Issue by 555666777888999101010** [TEdit/Terraria-Map-Editor#1760]
Tedit version: 4.11.4 BETA
Terraria version: 1.4.4.7
Windows version: Windows 11 C: and D:
When I try to delete the selection it says "an unhandled exception has occured: you may continue to use Tedit, but the operation will be unstable until it is restarted." and a couple of seconds later it crashes. This happens every single time.
Edit: corrected 1.11.4 to 4.11.4

**Comment by 555666777888999101010** [comment]
I MEANT 4.11.4 BETA

**Comment by BinaryConstruct** [comment]
Can you post your log file?

**Comment by 555666777888999101010** [comment]
I am unsure how to access the log file
I am updated to the latest version. Can you please explain?

**Comment by RussDev7** [comment]
I'm unable to re-create this. Can you please provide the world you're trying to delete a selection from?

**Comment by 555666777888999101010** [comment]
Do you mean the seed? The seed is 1162954592

**Comment by 555666777888999101010** [comment]
I attempted this at the BETA 6 and it now works - I think it has been fixed.
Maybe a temporary internal error?

**Comment by 555666777888999101010** [comment]
It seems that when I used TEdit for the delete - it was in BETA 4 yet Terraria was in 1.4.4.7 but the TEdit support was 1.4.4.6.
Im going to update to BETA 9
