### ISSUE TITLE
Biome Painting Doesn't Work

### ISSUE THREAD

**Issue by SoulessLifeform** [TEdit/Terraria-Map-Editor#1761]
- OS: Windows 10
 - Version: 4.11.4-beta5
 - Terraria Version: 1.4.4.7
 
Biome Painting stops working after a short while. Just paint a bit of corruption, purify around it, and then try to re-purify it and nothing changes.

**Comment by BinaryConstruct** [comment]
This is currently in progress with https://github.com/TEdit/Terraria-Map-Editor/pull/1766
