### ISSUE TITLE
Illuminant coating interaction with paints

### ISSUE THREAD

**Issue by EratoTiaTuatha** [TEdit/Terraria-Map-Editor#1764]
**Is your feature request related to a problem? Please describe.**
Currently there is no way to display whether an item has been painted with illuminant (or echo) coating in addition to being painted, and it also leads to inability to mass coat entire areas without affecting the paints, as well as inconsistencies between TEdit-illuminant items and ones made in game (sometimes the game interprets TEdit-made illuminant paint as old illuminant paint and sorts it out into illuminant coating on its own on world boot. Key word being sometimes. Other times it's not present at all in-game or just makes the map display grayscale for the painted items.)

**Describe the solution you'd like**
Some kind of yes/no toggle for coatings would be ideal, the way actuators and inactive tiles are handled

**Comment by BinaryConstruct** [comment]
Combining with #1719
