### ISSUE TITLE
TEdit crashes when I try update tally count from bestiaryy

### ISSUE THREAD

**Issue by ikablue** [TEdit/Terraria-Map-Editor#1770]
I tried to update tally count from bestiary with new button. When I click the button "update kill tally" TEdit crashes. It happens every time, with different worlds.

1. Click on 'open world', than 'tally", then "load", than "update kill tally".

**Expected behavior**
I expected tally to be updated from the bestiary

**Screenshots**
![image](https://user-images.githubusercontent.com/116747091/198082818-6a6e569b-ac1c-4cfc-8185-0330b68dbd9e.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Version [Tedit 4 beta 8]
 - Terraria Version [1.4.4.7]

**Comment by pjpollina** [comment]
Also having this issue, got this from the log after it crashed:
```
10-26-2022 13:21:45: Error - Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.ObjectModel.Collection`1.set_Item(Int32 index, T value)
   at TEdit.ViewModel.BestiaryViewModel.UpdateKillTally() 
10-26-2022 13:21:45: Error - Exception has been thrown by the target of an invocation.
```

**Comment by BinaryConstruct** [comment]
This will be fixed with the next beta.
