### ISSUE TITLE
Brushes suddenly stop working until i relaunch TEdit

### ISSUE THREAD

**Issue by Igniferi** [TEdit/Terraria-Map-Editor#1776]
### **Describe the bug**
When using various brushes they stop working after a few seconds mid brush. It happens when using the biome morph tool, the "normal" brush and the pencil. 
The more blocks I change, or the bigger the area I choose the faster the bug happens.
If I use max size it only changes a portion of the area it is supposed to change.
At that point, all tools seem to break, I cant use the pencil, I cant place sprites, the fill tool is not working.
Re-opening the world file does not solve the issue, closing and re-opening TEedit does.
I Can't even change a few 100 blocks before it happens, basically making TEdit unusable.

I have the latest version of DotNet Framework and DirectX

### **Steps to reproduce the behavior:**
It seems to happen on 1.4.4 or later worlds
I have a world from 21.Sep 2019, and it is not affected. (V 1.3.5.3)
But my world from 2.Oct 2022 is affected. (V 1.4.4.2)
I tried creating a new world, and it happens there aswell (V 1.4.4.7)

Happens quickly after starting to use tools.

### **Desktop (please complete the following information):**
 - OS: Windows 11 Home
 - Version [Tedit 4.11.3] (Had the same problem in 4.11.2 aswell)
 - Terraria Version [e.g. 1.4.4.7] (Had the same problem in 1.4.4.6 also, not sure about previous versions)

**Comment by BinaryConstruct** [comment]
Can you attach your log file, please?

**Comment by Igniferi** [comment]
Of course. sorry :)
[TEditLog_20221027225149.txt](https://github.com/TEdit/Terraria-Map-Editor/files/9883068/TEditLog_20221027225149.txt)

**Comment by pjpollina** [comment]
See if downloading a more recent version helps, I had this happen as well with older builds, but the most recent beta builds seem to have fixed this for me.

**Comment by Igniferi** [comment]
> See if downloading a more recent version helps, I had this happen as well with older builds, but the most recent beta builds seem to have fixed this for me.

This does seems to have removed the issue yes. For me atleast.

**Comment by WonderSquid** [comment]
Issue persists on latest stable for me.

[TEditLog_20221117221203.txt](https://github.com/TEdit/Terraria-Map-Editor/files/10037656/TEditLog_20221117221203.txt)
