### ISSUE TITLE
Importing schematic error

### ISSUE THREAD

**Issue by Elfcobbler45** [TEdit/Terraria-Map-Editor#1778]
**Describe the bug**

I get a Schematic File Error, the description of which reads: Unable to read beyond the end of the stream.

1. Click on 'Import Schematic or Image'
2. Select any previously exported schematic files and click open
3. Error pops up with windows sound, 'Unable to read beyond the end of the stream.'
The error pops up with or without and world being opened.

**Screenshots**

![image](https://user-images.githubusercontent.com/116857755/198475976-36ddfdf6-8b95-40e7-ac16-42bedb2aef25.png)

**Desktop:**
 - OS: Windows 10
 - Version Tedit v4.11.4-beta9
 - Terraria Version 1.4.4.7

Here are a couple of the schematics I'm having the error with, though I'm getting it with any file I try to use.
https://drive.google.com/file/d/16fdpMUCBwHaqV_duuyyx5gxQQUEBwNrT/view?usp=sharing
https://drive.google.com/file/d/1fu1Vdw__m9zzN7X90C_f5nqc9gZJfsXq/view?usp=sharing
https://drive.google.com/file/d/1E2qB5Hmjc-X7WUEoyG87EV91eOmRGMbt/view?usp=sharing

**Comment by RussDev7** [comment]
Please try the latest TEdit release. If the issue is still occurring, I will reopen this.
