### ISSUE TITLE
cant undo sprites after placing them

### ISSUE THREAD

**Issue by YokujinKaze** [TEdit/Terraria-Map-Editor#1783]
after placing down a sprite ctrl+z doesnt undo it (but does go back 1 step), crtl+y will unto the sprite
after placing down a sprite ctrl+y doesnt undo it (has no effect)
after placing down a sprite ctrl+z doesnt undo it, using ctrl+z again will undo previously placed blocks but not the sprite

**Comment by RussDev7** [comment]
This seems to be fixed in the latest update. If it continues please let us know.
