### ISSUE TITLE
Release 4.11.5 exe reports it's 4.11.4

### ISSUE THREAD

**Issue by blob1807** [TEdit/Terraria-Map-Editor#1794]
Release 4.11.5 executable reports it's 4.11.4.
It's causing the update check to say there's a new version.
Executables are different, checked with sha256.

**Comment by RoLYroLLs** [comment]
Same. I thought I was doing something wrong.

**Comment by BinaryConstruct** [comment]
The new builds are automatic, and the old release process had a "manual" way of updating the versions. These two processes have not yet been reconciled.
