### ISSUE TITLE
Can't launch TEdit.

### ISSUE THREAD

**Issue by AGrimmFate** [TEdit/Terraria-Map-Editor#1797]
I have downloaded the most recent verson of TEdit, and yet there is no exe file at all in the entire thing. I downloaded it from: [ http://www.binaryconstruct.com/downloads/](url) and it does not work.

**Comment by RussDev7** [comment]
> I have downloaded the most recent verson of TEdit, and yet there is no exe file at all in the entire thing. I downloaded it from: [ http://www.binaryconstruct.com/downloads/](url) and it does not work.

Please try and download it from the [github releases](https://github.com/TEdit/Terraria-Map-Editor/releases). If further issues exist, create a new issue ticket.
