### ISSUE TITLE
Undo Crash

### ISSUE THREAD

**Issue by Xenobellow** [TEdit/Terraria-Map-Editor#1799]
**Describe the bug**
What is the problem?
Undo crash each time I want to undo

1. Use brush any tile on the map.
2. Then click undo

**Expected behavior**
Supposed to undo a process

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Version Tedit 4.11.5
 - Terraria Version 1.4.4.7

**Comment by BinaryConstruct** [comment]
Could you please try 4.11.6?

**Comment by Xenobellow** [comment]
Undo works now for 4.11.7, but all the wall paint colors reset upon saving world..

**Comment by RussDev7** [comment]
> Undo works now for 4.11.7, but all the wall paint colors reset upon saving world..

This has also been resolved in the latest TEdit release. If issues continue I will re-open this.
