### ISSUE TITLE
All colored paint on the walls is automatically removed

### ISSUE THREAD

**Issue by bloodstone1476** [TEdit/Terraria-Map-Editor#1800]
1. Open a map with tedit
2. Do nothing but（or anything and）save the map
3. Open the terraria game itself
4. You will find that all the paint behind the air blocks that will change the color of the wall has disappeared (but the invisible paint  are still there)

 - OS: [ Windows 10]
 - Version [Tedit 4.11.6](wont happen before this verison)
 - Terraria Version [e.g. 1.4.4.8]

**Comment by TurboPinky** [comment]
this issue still exists as of 4.11.7

**Comment by BinaryConstruct** [comment]
Thanks for the report.

**Comment by Xenobellow** [comment]
It resetted my wall paint

Before
<img width="1920" alt="Screenshot 2022-11-10 184652" src="https://user-images.githubusercontent.com/115019496/201236383-8d0438bc-3a28-4e29-8578-97d6e11630b2.png">

After
<img width="1920" alt="Screenshot 2022-11-10 184725" src="https://user-images.githubusercontent.com/115019496/201236396-376a5ffa-143f-446f-8ced-ae2c649324e4.png">

**Comment by XORandom** [comment]
It may be worth changing the paint menu in the tedit itself, since there is still an illuminant paint there, while in the terraria itself there is an echo coating and an illuminant coating.

**Comment by RussDev7** [comment]
> It may be worth changing the paint menu in the tedit itself, since there is still an illuminant paint there, while in the terraria itself there is an echo coating and an illuminant coating.

This is still tricky, as TEdit has to support all versions of Terraria.

**Comment by XORandom** [comment]
> > It may be worth changing the paint menu in the tedit itself, since there is still an illuminant paint there, while in the terraria itself there is an echo coating and an illuminant coating.
> 
> This is still tricky, as TEdit has to support all versions of Terraria.

Then maybe you should write "illuminant paint (before 1.4.4)". And also make a separate category and coating layer (1.4.4+).
So where it will be paint, it will remain paint (unless you run it in a terrariq where it will turn it into a coating). But it will be possible to work with coatings in tedit.
