### ISSUE TITLE
Can't interact with just one world

### ISSUE THREAD

**Issue by CatMaster8232** [TEdit/Terraria-Map-Editor#1803]
I recently made a world to play hide and seek on, and i cropped it to be smaller. I wanted to add another flying island into the area, but it wasn't pasting. I tried pasting it onto another world, and it worked fine. I discovered that I can't edit the world in any way, it just refuses to place or delete anything. I'm gonna attach the world to see if it works for anyone else.
[find.zip](https://github.com/TEdit/Terraria-Map-Editor/files/9986288/find.zip)

**Comment by XORandom** [comment]
I tried, right, I can't draw with a brush, I can't insert a schematic into your world. Version 4.11.8

**Comment by RussDev7** [comment]
Seems to have been resolved in the later TEdit releases.
