### ISSUE TITLE
Item ID Omit

### ISSUE THREAD

**Issue by wdfcf222** [TEdit/Terraria-Map-Editor#1804]
terraria Currently, there are 5455 item IDs  
But tedit There are only 5452 pieces 
This is a particularly stupid question  
1.4.4.5 Secretly added three new items  

- OS: [e.g. Windows 10]
 - Version [TEdit-4.11.8]
 - Terraria Version [e.g. 1.4.4.8.1]

**Comment by RussDev7** [comment]
The file `TerrariaVersionTileData.json` is reflecting `5455` for version `1.4.4.5+` correctly. Where did you get the `5452` items from?

**Comment by wdfcf222** [comment]
![Screenshot_20221111_164542](https://user-images.githubusercontent.com/104006896/201301982-e50b841f-eadf-4b89-ac2c-e2c6f2c56cf3.jpg)
![IMG_20221111_164659](https://user-images.githubusercontent.com/104006896/201302003-e0a706ad-95b2-485b-89b5-3f8a5b02884e.jpg)

**Comment by RussDev7** [comment]
The numbers within `TerrariaVersionTileData.json` are taken right from the games source code. Until this causes issues I will re-open this. Nontheless thanks for the report.
