### ISSUE TITLE
Error in the Treasure Chest Editor 

### ISSUE THREAD

**Issue by wdfcf222** [TEdit/Terraria-Map-Editor#1805]
Treasure Chest Editor cannot edit the following three items  
5453:Guide to Critter Companionship (Inactive)
5454:Guide to Environmental Preservation (Inactive)
5455:Guide to Peaceful Coexistence (Inactive)
These three items can not be read properly and can not be added  
 This may be the omission of these three items in the settings file  
The item ID in the settings file only reached 5452  ，That should be the cause of the problem  
When I manually add these three items  ，This problem is solved

**Comment by RussDev7** [comment]
Can you please confirm this is an issue in the current build?

**Comment by wdfcf222** [comment]
> 你能确认这是当前版本的问题吗?

I am pretty sure  
Even with the latest version 4.11.8  ,This error still exists  
I hope you guys fix this in version 4.11.9  ,Because the solution to this problem is very simple  ,Even an ordinary person can do it  ,It'll only take a minute to fix  
I'll thank you

**Comment by wdfcf222** [comment]
> Can you please confirm this is an issue in the current build?

I am pretty sure
Even with the latest version 4.11.8 ,This error still exists
I hope you guys fix this in version 4.11.9 ,Because the solution to this problem is very simple ,Even an ordinary person can do it ,It'll only take a minute to fix
I'll thank you

**Comment by RussDev7** [comment]
This appears to be fixed in TEdit 4.12.0.
