### ISSUE TITLE
Simple Ore Generator dosent work as documentation describes it

### ISSUE THREAD

**Issue by Smokedeuch** [TEdit/Terraria-Map-Editor#1807]
**Describe the bug**
What is the problem.

Simple Ore Generator simply doesn't work as documentation or the wiki describes it

1. Select the entire world using the selection tool and then click on simple ore generator under the plugins tab and it will just generate hollow dirt blobs all over the world including air tiles

**Expected behavior**
What you expected to happen.

A popup menu to come up with options and for it to not just generate hollow dirt blobs

**Screenshots**
![Save](https://user-images.githubusercontent.com/77568373/201444256-9954b58f-c13b-446e-a8aa-d0163f5c3a31.png)

**Desktop (please complete the following information):**
 - OS: Windows 11  22H2
 - Version Tedit 4.11.8
 - Terraria Version 1.4.4.8.1

**Comment by owensilj** [comment]
This is because the selected block by default is a dirt block. You should use the picker or tile placer tools to edit the selected block.
> A popup menu to come up with options and for it to not just generate hollow dirt blobs

A pop-up would be more intuitive but not necessary for the plugin to work.

**Comment by Smokedeuch** [comment]
Yeah definitely needs clarification 
![Uh](https://user-images.githubusercontent.com/77568373/202344673-4d314fa6-256c-47c9-90c5-11cadc0b6a92.png)

**Comment by RussDev7** [comment]
I will pass this on for more documentation thank you.
