### ISSUE TITLE
Validating complete

### ISSUE THREAD

**Issue by MrJ935115** [TEdit/Terraria-Map-Editor#1810]
# READ THIS FIRST
- **Sprite Issues?** See https://github.com/TEdit/Terraria-Map-Editor/wiki/Install-Requirements#for-sprite-viewing
- **Won't Start?** See https://github.com/TEdit/Terraria-Map-Editor/wiki/Troubleshooting#application-launch-or-map-loading-issue
- **Map not loading?** See https://github.com/TEdit/Terraria-Map-Editor/wiki/Troubleshooting#application-launch-or-map-loading-issue

# If the Wiki did not help, fill out this form completely! If you are missing steps to reproduce your issue will be closed. Thank you.

**Before Submitting an Issue**
* If you are having issues loading a world, please attach it to the current version world thread (see pinned issues).
* For a crash, please check the log.

**Describe the bug**
What is the problem.
I cannot make changes to the world such as biome morphing and I am not able to save. when attempting to save the bottom right corner only shows a "validating complete" message and nothing saves. 
1. Click on '....'
It happens as soon as I open the program.
**Expected behavior**
What you expected to happen.
To be able to use the program 
**Screenshots**
Add screenshots to help explain your problem.
![Uploading Validating complete .png…]()

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version Tedit 4.11.8
 - Terraria Version 1.4.4.8.1

**Comment by RussDev7** [comment]
This was posted after Terraria v1.4.4.9 released. Are you sure you're still on v1..4.4.8.1? If so then post #1809 will resolve this issue.
