### ISSUE TITLE
Salamander, Crawdad and Giant Shelly spawning configuration

### ISSUE THREAD

**Issue by eGhpGZeMqhlAIRtA1soVFK4JCDnrsxAXjirz97L** [TEdit/Terraria-Map-Editor#1818]
In a given Terraria world only two of these enemies can spawn, while the third is left out.
Is this hard-coded or would it be possible to add a setting to allow any combination of spawns?

**Comment by RussDev7** [comment]
TEdit cannot change what monsters can spawn or not sorry. This would be hard coded.
