### ISSUE TITLE
ReplaceAllPlugin masking function giving different outputs with walls 256-346 selected

### ISSUE THREAD

**Issue by eGhpGZeMqhlAIRtA1soVFK4JCDnrsxAXjirz97L** [TEdit/Terraria-Map-Editor#1829]
Windows 10
Tedit Version 4.12.0
Terraria 1.4.4.9

Trying to apply any wall between Green Mossy Wall (256) and Helium Moss Brick Wall (346) using the masking function inside of ReplaceAllPlugin gives a different output.
Masking normally using pencil or brush tools doesn't lead to this problem.
Here is an example of trying to apply reef walls but getting grass walls instead.

![Screenshot 2022-12-22 235952](https://user-images.githubusercontent.com/74626960/209239483-f7dcffc1-9d1d-44aa-aa29-b0923db0cc10.png)
![Screenshot 2022-12-23 000027](https://user-images.githubusercontent.com/74626960/209239487-213d4878-1160-4e37-98f6-b7b4e5212f25.png)
![Screenshot 2022-12-23 000058](https://user-images.githubusercontent.com/74626960/209239491-c8050ffa-791a-4ed6-a421-14cd0b5b30c4.png)

**Comment by RussDev7** [comment]
This plugins backend code probably just needs updated from all the recent changes. I will put this on the tracker thanks.
