### ISSUE TITLE
Tedit did not work (Did not save the file)

### ISSUE THREAD

**Issue by TheMrKras** [TEdit/Terraria-Map-Editor#1831]
For some reason the last time Tedit worked for me was when the rars were named with the version number like " TEdit-4.11.4-beta5.zip " " TEdit-4.11.4.zip ". I tried all other archives that were named " TEdit_main.zip " and it did not work. The latest version with that zip name "[4.12.0](https://github.com/TEdit/Terraria-Map-Editor/releases/tag/4.12.0)" "4.12.0" did work in placing some dirt blocks but I haven't checked the full functionality.

It was a problem for me because all the changes I made within Tedit were not being saved.

**Comment by RussDev7** [comment]
Could you please attach your latest log?
