### ISSUE TITLE
*Time modification issue* 

### ISSUE THREAD

**Issue by St3fanekM** [TEdit/Terraria-Map-Editor#1832]
Recently, I was playing terraria and decided to try the time modification feature on Tedit, however, after trying to restore time speed to the regular speed with Tedit again, it did not work as everytime I went back into game the time speed would still be on max speed from before. Before you say this, yes I did save my changes each time after modifying them, and I did also save the world file after, yet it just simply doesn't seem to work. 

Any suggestions and help would be appreciated thank you.

**Comment by RussDev7** [comment]
We are aware of this issue. Issue is similar to post 1795.

**Comment by oafmasm** [comment]
is there any way to fix this? or to return to normal?

**Comment by ibimcoll** [comment]
If you still experience this bug, put the world to journey, restart the game and then put the time speed down with the power menu

**Comment by CoverKun** [comment]
> If you still experience this bug, put the world to journey, restart the game and then put the time speed down with the power menu

this doesn't work

**Comment by Terra-formed** [comment]
I have found a way to undo it. I got it to work twice.
1. Set the world to journey mode.
2. Close TEdit.
3. Launch the world.
4. Use the powers menu to change time to normal speed.
5.  Save and quit .
6. Completely uninstall TEdit. 
7. Launch the world again (may not be necessary but I did it anyway to double check time was still at normal speed).
8. Reinstall TEdit.
9. Set world back to classic or expert or master, whatever you want.

**Comment by BinaryConstruct** [comment]
You can probably simplify the above to

1. set world to journey mode
2. save and close tedit
3. load world in terraria 
4. use journey mode controls to set speed
5. save and exit terraria
6. load world in tedit and modify other parameters as required

**Comment by Terra-formed** [comment]
Unfortunately you can’t, if you don’t delete TEdit first, when you try to change the world type back from journey mode it puts the time back into superspeed

**Comment by RussDev7** [comment]
Issue fixed in pull request 1874.
