### ISSUE TITLE
[Feature Request] Nintendo Switch support

### ISSUE THREAD

**Issue by fennectech** [TEdit/Terraria-Map-Editor#1836]
Id love to be able to edit terraria switch save worlds    i can provide a few world files upon request as well as testing on discord

**Comment by fennectech** [comment]
https://cdn.discordapp.com/attachments/1042735368266584084/1059400258049822720/Home.wld  Here is a copy of my world

**Comment by RussDev7** [comment]
The switch uses a completely different file format along with some console versions. These will not be added for a while.

**Comment by RussDev7** [comment]
To clear confusion, support for consoles (and switches) was added in 76d18f8ed925c67f91d4a2bad909e5181d84275d.
