### ISSUE TITLE
Erratic zooming when using mouse wheel

### ISSUE THREAD

**Issue by Rouche** [TEdit/Terraria-Map-Editor#1839]
# READ THIS FIRST

**Before Submitting an Issue**

**Describe the bug**
I have a Large world on a 4K screen. When i use mouse wheel for zooming. Instead of centering the position on cursor, it goes in a completelly random position.

1. Open a large map
2. Wheel in center

**Expected behavior**
The position under my cursor before zoom become the center of the screen

**Screenshots**
A bit hard to screenshot this.  Dont think it will help, if you really need i will.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version 4.13
 - Terraria Version [e.g. 1.4.4.9

**Comment by BinaryConstruct** [comment]
Are you using any DPI scaling? Sometimes this causes issues.

**Comment by Rouche** [comment]
I have removed the scaling, restarted and it still have the same behavior.

Also its not only with mouse wheel but the zoom button too.
But if you say its ok on your side it might be because im on a TV screen
and not computer at 3840 x 2160

**Comment by RussDev7** [comment]
I'm unable to re-create this. For now I will close this. Feel free to ask for a reopen if issues continue with TE5+.
