### ISSUE TITLE
I can load sprites and textures

### ISSUE THREAD

**Issue by lulemule** [TEdit/Terraria-Map-Editor#1840]
so basicly its just colors and nothing else EVEN WHEN I ZOOM IN i have it enabled....
i got to sprites tab and just filter and style?
![Snimak ekrana 2023-01-17 231133](https://user-images.githubusercontent.com/122939824/213023712-e906ac68-8aa9-49b8-ac9f-ae3d29199299.png)
![Snimak ekrana 2023-01-17 231100](https://user-images.githubusercontent.com/122939824/213023724-f41da7e8-8e56-406a-80ad-621a553568ab.png)

**Comment by RussDev7** [comment]
Check this link for a fix: 
https://docs.binaryconstruct.com/install-requirements#for-sprite-viewing
