### ISSUE TITLE
Modify publishing arguments to produce compact releases.

### ISSUE THREAD

**Issue by csmir** [TEdit/Terraria-Map-Editor#1841]
### Is your feature request related to a problem? Please describe.

TEdit is currently packaged as a regular build output. This comes with a number of disadvantages:

- If the user does not have the correct .NET version installed (they should, but who knows), launch will fail.
- Users who are not very familiar with browsing file folders may be confused at their contents.
- The files are bloated and with the exception of a mere few, useless to the user.

### Describe the solution you'd like
On publish, consider packaging with the following parameters:

```xml
<!--Inform publish that you want to output a single file app.-->
	<PublishSingleFile>true</PublishSingleFile>
	
<!--https://learn.microsoft.com/en-us/dotnet/core/deploying/#publish-self-contained-->
	<SelfContained>true</SelfContained>
	
<!--Publish as win64, this depends on the platform the application is launched on. 
I am quite sure TEdit is not compatible with other platforms though (without mono), due to use of the windows drawing libs.-->
	<RuntimeIdentifier>win-x64</RuntimeIdentifier> 
	
<!--https://learn.microsoft.com/en-us/dotnet/core/deploying/ready-to-run#impact-of-using-the-readytorun-feature-->
	<PublishReadyToRun>true</PublishReadyToRun>
	
<!--Removes the .pdb file from the output directory and embeds it into the executable, reducing file bloat even more.-->
	<DebugType>embedded</DebugType>
```

### Describe alternatives you've considered
Being a suggestion towards the build output of the application, this question isn't very relevant.

### Additional context
Using this in my own applications seriously reduces bloat, making it nicer to work with:

#### Old
![image](https://user-images.githubusercontent.com/68127614/213862652-2738c4ed-c2be-4281-be7e-140c97663997.png)

#### New
![image](https://user-images.githubusercontent.com/68127614/213862661-71df26bb-5cdf-4d43-933b-ba36fa1b547a.png)

### Important notes:
While this reduces bloat in the directory, the size of the executable is seriously inflated. Ready to run is mostly responsible for this, and could potentially be skipped if file size is a serious issue.

**Comment by BinaryConstruct** [comment]
I will keep this in mind once TEdit is on a newer version of .Net instead of legacy .Net Framework 4.6
