### ISSUE TITLE
Linux

### ISSUE THREAD

**Issue by MaksDragon** [TEdit/Terraria-Map-Editor#1845]
Hey, does have any way to run it on linux without virtual machines? Web version is very very bad solution.

**Comment by MaksDragon** [comment]
> > Hey, does have any way to run it on linux without virtual machines?
> 
> Wine?

Wine dont open tedit

**Comment by DraconicNEO** [comment]
> > Hey, does have any way to run it on linux without virtual machines?
> 
> Wine?

Wine Doesn't support this app's use of WPF, won't open it.

**Comment by Zylquinal** [comment]
![image](https://github.com/TEdit/Terraria-Map-Editor/assets/80770188/170ab0bc-1055-487a-9e19-8313261e851a)

It works after installing version 4.6.2 of .NET

### Environment
- Wine: `wine-7.0.r0.g2fc92f8b` using Bottle
- Kernel: `Linux arch 6.4.2-zen1-1-zen`

**Comment by RussDev7** [comment]
This should be closed now with TE5+.
