### ISSUE TITLE
doesn't work with crossover on mac

### ISSUE THREAD

**Issue by duncan4567545676** [TEdit/Terraria-Map-Editor#1852]
here is my specs
 - CrossOver Version 22.1 (22.1.0.35672)
 - OS: mac os monterey 12.6
 - Version Tedit 4.13.0
 - Terraria Version 1.4.4.9 
 - when i tried to install tedit and this happend
<img width="817" alt="Screen Shot 2023-04-20 at 12 23 50 pm" src="https://user-images.githubusercontent.com/131324562/233241599-cee5bca1-290f-43f5-88dc-a63a298ce989.png">
but it is the newest Version  of Tedit  please help. 
I restarted the application but it kept crashing

in future can you make a version for Mac  please

**Comment by BinaryConstruct** [comment]
Your best option is probably to use a VM or bootcamp at this point.
