### ISSUE TITLE
ChromeOS?

### ISSUE THREAD

**Issue by sebper616** [TEdit/Terraria-Map-Editor#1855]
Can't figure out how to install this application on ChromeOS using the Linux capabilities present on the device. Currently running Linux 10 ("Buster"), if that helps. Keep in mind that I have basically zero knowledge of how to use Linux beyond opening the terminal and have been trying (and failing) to follow along with tutorial videos I found online.

**Comment by BinaryConstruct** [comment]
You would have to use a windows virtual machine, which would require a dual boot setup.
