### ISSUE TITLE
TEdit Crashes upon doing any search for "corrupt"

### ISSUE THREAD

**Issue by Sabre2k2** [TEdit/Terraria-Map-Editor#1859]
What were you doing when the issue occurred? 
Searched for "corrupt" while trying to get rid of the corruption in my world with TEdit's aid.

Steps to reproduce the issue?
1) Open the plugin to find Sprite, Tile or Wall.
2) Input "corrupt" "cor" "ruption" or any partial word that refers to corrupted. - Unhandled exception occurs that leads to fatal crash.

What version of Terraria are you using?
4.14 (Latest)

Log file attached.
[TEditLog_20230601015030.txt](https://github.com/TEdit/Terraria-Map-Editor/files/11623318/TEditLog_20230601015030.txt)

**Comment by BinaryConstruct** [comment]
Thanks for the log!
