### ISSUE TITLE
Problems with the Time Function in the game

### ISSUE THREAD

**Issue by FastzinDasBurlas** [TEdit/Terraria-Map-Editor#1873]
![image](https://github.com/TEdit/Terraria-Map-Editor/assets/111142289/28787708-956c-4a78-bc80-a5f681720039)
I open teedit, load the world normally, I was messing with the time inside the game to be able to "trigger" the invasion of mars faster, I did it, the days passed quickly and it came, but when I go to teedit and change the option of time to 1, and I open the game again, the time doesn't change, it keeps circling very quickly.

can someone help me?

**Comment by RussDev7** [comment]
This is a confirmed issue, we plan to fix this soon. Please be patient. You can try and switching the world to journey and using the ingame slider adjust the time manually, then switch back.
