### ISSUE TITLE
Mod Compatibility, with a theoretical solution

### ISSUE THREAD

**Issue by Itsappuru** [TEdit/Terraria-Map-Editor#1885]
**Is your feature request related to a problem? Please describe.**
Can't edit a modded world

**Describe the solution you'd like**
Ability to put mod files into the editor in order to load the files it doesn't normally have, ex: Calamity Tiles

**Describe alternatives you've considered**
Whilst reading the world file, once it detects a non-vanilla tile, it reads which mod its from and loads said mod into TEdit, but thats probably harder

**Additional context**
No additional context

**Comment by JUCAGIO1** [comment]
so... is this going to be a thing or not?
