### ISSUE TITLE
please make a mac & Linux port for TEdit in the next update please

### ISSUE THREAD

**Issue by mrxplasma** [TEdit/Terraria-Map-Editor#1890]
please make a mac & Linux port for TEdit in the next update please  it will help the terraria players as well

**Comment by begota98** [comment]
For me, running it with wine doesn't work.

When i run `wine TEdit.exe` i get the output:

> 002c:fixme:winediag:loader_init wine-staging 9.1 is a testing version containing experimental patches.
> 002c:fixme:winediag:loader_init Please mention your exact version when filing bug reports on winehq.org.
> 0118:fixme:mscoree:parse_supported_runtime sku=L".NETFramework,Version=v4.6.2" not implemented
> 0118:fixme:mscoree:parse_supported_runtime sku=L".NETFramework,Version=v4.6.2" not implemented
> 0118:err:module:import_dll Library iconv.dll (which is needed by L"Z:\\usr\\share\\wine\\mono\\wine-mono-8.1.0\\bin\\libmono-2.0-x86_64.dll") not found
> 0118:err:mscoree:load_mono Could not load Mono into this process

I have made a symlink at **~/.wine/drive_c/Program Files (x86)/Steam** to point to **~/.var/app/com.valvesoftware.Steam/.steam/steam** (i'm using steam flatpak), but still it's the same error.

**Comment by icdragn** [comment]
That error suggests an issue with .net/mono... and that version of .net (4.6.2) seems to be old. When was your wine space generated? I just installed winehq-stable for the first time on my ubuntu 22.04 LTS machine, double clicked on `TEdit.exe` from a linux file explorer window, and wine started setting stuff up, including downloading and installing .net. TEdit started right up once that was done. I didn't use ubuntu's build of wine, though; I added winehq's repository and installed their build of wine as recommended in winehq's install docs.

So, I guess a good first question is this: how did you install wine? Through your distro's package manager or from winehq? For ubuntu 22.04, it looks like 6.something is installed when I issue `apt install wine` through the official repositories, but winehq installed 9.0. Installing an older version of wine may be the reason behind the old .net.

**Comment by icdragn** [comment]
Ah, I missed that... 9.1 is in the devel branch according to winehq. Did you install your wine by following https://wiki.winehq.org/Fedora or just `dnf install wine`?

If it isn't wine (which I'm not sure about unless you get the same error with the winehq builds), then I wonder at the .net/mono install inside that installation. I would suggest renaming `~/.wine` and then trying to start `TEdit.exe` again to try to regenerate your wine space. If you do that, is there a message about installing .net?

**Comment by GetPsyched** [comment]
Sucks that successful Linux support through Wine is taken as the easy route these days :(

I don't mean to fault the devs for it, I understand; it just sucks to have to do it this way as an end user (compatibility also never perfect).
