### ISSUE TITLE
Prroblemas con TEdit

### ISSUE THREAD

**Issue by enmanuel791** [TEdit/Terraria-Map-Editor#1892]
Tengo un problema con el TEdit, cuando lo abro todo me carga bien y puedo modificar bien el mapa y todo pero los sprite no me los carga y las texturas de los bloques tmp, ya he probado varias cosas y no me funciona, tmp lo encuentro por internet, si alguien pudiera ayudarme estaria muy agradecido, aclaro que uso el TEdit4.16:(

**Comment by BinaryConstruct** [comment]
> I have a problem with TEdit, when I open it everything loads fine and I can modify the map and everything but the sprites and the textures of the tmp blocks do not load, I have already tried several things and it does not work for me, tmp I find it online, if someone could help me I would be very grateful, I clarify that I use TEdit4.16:(

https://docs.binaryconstruct.com/install-requirements#for-sprite-viewing
