### ISSUE TITLE
trying to do anything with the default brush just place dirt blocks

### ISSUE THREAD

**Issue by chickenbutt1** [TEdit/Terraria-Map-Editor#1905]
the issue:
literally just the title

1. use the brush tool 2.  try to place/erase anything 

**Expected behavior**
i expected it to place/erase the blocks 🙀🙀🙀

**Screenshots**
cant really do much with screenshots but ill put a video i guess (limit is 10mb smh had to put on youtube also my computer is ass so laggy recording 😼😼) https://youtu.be/9osyezH_-Qs

 - OS: [windows 11]
 - Version [Tedit 5.0.0 beta2]
 - Terraria Version [1.4.0.4]

**Comment by BinaryConstruct** [comment]
This is fixed with beta3 and beta4
