### ISSUE TITLE
Taptap(xindong) version canot recognize saved world

### ISSUE THREAD

**Issue by maisfly** [TEdit/Terraria-Map-Editor#1931]
No matter what kind of  change in TEdit is made, the saved wld file cannot be open in andriod Terraria.

Terraria version: Taptap(xindong), 1.4.49560(301305)

**Comment by RussDev7** [comment]
Could you please attach your world file?

**Comment by maisfly** [comment]
2 wld files attached.

蕨草之寓言.wld is the original world,6688 KB. After edited in TE ,you cannot directly save it ,TE will stuck in "validating complete" step ,as the "saving_file.png" shows.

However, "save as version" function can work,TE will generate a 21964 KB wld file (modified.wld). This wld file cannot open in game.

[worlds.zip](https://github.com/user-attachments/files/16434928/worlds.zip)
![saving_file](https://github.com/user-attachments/assets/417392e0-6693-46b0-9507-db69c7a4409a)
![saving_file](https://github.com/user-attachments/assets/85f5ce4b-c9a8-4b90-ac6b-da206115665b)

**Comment by RussDev7** [comment]
Thank you for the report. This has actually been solved in #1915 (Beta-8). Either wait for a release or feel free to download the latest source code and compile it yourself using `build.ps1`. I'll close this for now, if future issues occur, let me know!

![Working](https://github.com/user-attachments/assets/de0dabc9-2ddd-4d6b-bb07-96cc7d302ed9)
