### ISSUE TITLE
Palm tree problem

### ISSUE THREAD

**Issue by Dedegaming09** [TEdit/Terraria-Map-Editor#1946]
the palm tree texture is incorrect and when i place normal palm tree it shows corruption palm tree when i open the world and all of them is corruption palm tree pls fix it:(

**Comment by BinaryConstruct** [comment]
I think this is the same issue as #1891, so going to close this as a dupe. Thanks for the report.

**Comment by Dedegaming09** [comment]
but will this gonna be fixed?

**Comment by BinaryConstruct** [comment]
It requires quite a bit of work on the rendering engine, so it may be a while.

**Comment by BinaryConstruct** [comment]
> There’s a new problem the oasis plant is cannot spawn in terraria or cannot be seen but in tedit can be seen is this gonna be fix (idk if you ignore this) I have full requirements btw

Can you attach a screenshot and maybe a schematic (zipped)?

**Comment by Dedegaming09** [comment]
Tedit version
![TEdit v5 0 0-beta8+4c8662871d35f4dc5d6d4b43d68e69c8eb455ff9 TEdit World wld 27_08_2024 17_08_19](https://github.com/user-attachments/assets/ec7533df-0ebd-4ef1-9fe5-1b8f31bd69ee)
terraria version
![Uploading Terraria_ The Grass is Greener on This Side 27_08_2024 17_12_34.png…]()

**Comment by Dedegaming09** [comment]
terraria version
(sorry it cannot be open this is the new one)
![Uploading Terraria_ The Grass is Greener on This Side 27_08_2024 17_12_34.png…]()
