### ISSUE TITLE
Sprite Remover Tool

### ISSUE THREAD

**Issue by Mystil** [TEdit/Terraria-Map-Editor#281]
Is there any way to move and/or delete sprites without affecting either walls or tiles? I've searched and haven't found an answer to this, and it's getting irritating to have to replace the walls in my structure I'm building.

Thank you! TEdit is an amazing tool!

~Mystil

**Comment by som-dude** [comment]
the new version seems to not respond after selecting something and then copy/pasting it once. also the 'sprite' button seems to have an empty selection. ([beta version may be unstable] TEdit 3.11 beta for Terraria 1.3.5)
