### ISSUE TITLE
New Tool: Random Sprite placement Forest, corrupt, jungle, hallowed grass, crystal shards, corals

### ISSUE THREAD

**Issue by zaqen** [TEdit/Terraria-Map-Editor#308]
I'm wondering if it would be possible to make a tool that can generate a random selection of the sprites of grass, crystal shards, corals and perhaps tree trunks. 
When trying to imitate a lush area you have to place each specific sprite to make it look natural and random but this takes a huge amount of time if the map is big. The other option is leave a server running with no mob spawns and let the grass grow. The problem with that is that grass can only grow under certain requirements and that makes it an issue. 

If there was a tool like the morphing tool that added, not modified, sprites to simulate a lush area with random growth it would be great. 

This would sort of imitate how the placement of these items work ingame, like corals and crystal shards.

**Comment by BinaryConstruct** [comment]
Using #1262 for future work on world generation
