### ISSUE TITLE
I downloaded Tedit to my computer and double tap the application and it won't open at all?

### ISSUE THREAD

**Issue by vgrantv** [TEdit/Terraria-Map-Editor#330]
Please help me I am very irritated I have tryed downloaded it and repairing it and even deleting it from my computer then re downloading it and it still won't open.

**Comment by Shzuki** [comment]
I'm having a similar issue as described above. Ive downloaded from the official site, waited a few seconds to skip the add, downloaded the installer zip and then installed TEditXna. I've tried opening it from the short cut and through the link in Program files. On all occasions a loading circle will appear for a brief second, it will appear in my task manager for a brief second, then nothing happens. I have checked all my requisites and still have found no issues. I dont see the log.txt file in my TEdit Program files folder though.  Any advice would be greatly appreciated :)

**Comment by Walkman100** [comment]
All, if you are running on Windows 7 (I think even Vista and 8 do this) and you have installed TEdit to `Program Files`, check the `Compatibility files` folder for the log:
![image](https://cloud.githubusercontent.com/assets/5454764/6972993/bca60b90-d987-11e4-9614-94f2fa4cf762.png)
If you don't have that button, it should take you to `%localappdata%\VirtualStore`
There should be a `Program Files` folder in there, which should have a `TEdit 3` folder, and the `log.txt` might be there.

**Comment by Shzuki** [comment]
Thanks for the quick response, I am running Windows 8 and am having trouble finding the compatibility files folder. Can you give me explicit instructions on how I might find it?

**Comment by Walkman100** [comment]
Well it was a general response that should be in whatever FAQ there is :smile: 
To find the folder (if that button doesn't appear), open a File Explorer window, and paste `%localappdata%\VirtualStore` in the location bar (where it shows the current folders), then press enter.

**Comment by Shzuki** [comment]
Welp, the virtual store folder was empty too. Any other suggestions?

thanks again for all your help thus far

**Comment by Walkman100** [comment]
Well. Just checked [the wiki](https://github.com/TEdit/Terraria-Map-Editor/wiki#issues-crashes-), and apparently logs are saved at `"My Documents"\My Games\Terraria\TEditLog.txt` -_-
Try checking there

**Comment by Shzuki** [comment]
Thanks so much. managed to find TEditlog.txt

the contents of the file are:

04-13-2015 01:00: Starting TEdit 3.5.14228.27 
04-13-2015 01:00: OS: Microsoft Windows NT 6.2.9200.0 


There is also a file called TEditlog.txt.old if that is of any interest

thanks again

**Comment by DogTheBoss** [comment]
I also have a problem with TEdit working. I launch it, and it only appears in task manager. I have .NET Framework v4.6, could this be because of my outdated Vista computer?

**Comment by DogTheBoss** [comment]
Latest log (note: I have DX 11):
[TEditLog.txt](https://github.com/TEdit/Terraria-Map-Editor/files/397943/TEditLog.txt)

**Comment by BenTheArmy** [comment]
I have terraria version 1.3.2.1, and these are my logs : 
08-20-2016 11:55:55: Starting TEdit 3.8.16233.1744 
08-20-2016 11:55:55: OS: Microsoft Windows NT 6.1.7600.0 
08-20-2016 11:55:55: Terraria Data Path: C:\Program Files (x86)\Steam\steamapps\common\Terraria\Content 
08-20-2016 11:55:56: Creating Undo cache: C:\Users\David\AppData\Roaming\TEdit\undo_884784120 
Idk why its not working, it does open at all and doesnt show in the task manager, even though I double click. Any help?
