### ISSUE TITLE
Unable to locate Terraria. No texture data will be available. 

### ISSUE THREAD

**Issue by kolobokk** [TEdit/Terraria-Map-Editor#360]
I cannot do anything with it. I've read about it, you said that "launching as Admin or replacing the application" can help. So i tried, but without any result. If you know, building without textures is a rather hardly)

TEdit Log --------------------

08-05-2013 20:47: Starting TEdit 3.3.12322.1200 
08-05-2013 20:47: OS: Microsoft Windows NT 6.1.7601 Service Pack 1 
08-05-2013 20:47: .Net >= 4.0 
08-05-2013 20:47: XNA 4.0 
08-05-2013 20:47: Unable to locate Terraria. No texture data will be available. 

---

That's all.

Hopefully you'll help, regards, Oleg.

**Comment by Jimmy2048** [comment]
What about the GOG release?

**Comment by AlifKhairulFallah** [comment]
i have moved my terraria folder to steamapps but its still not working

**Comment by AlifKhairulFallah** [comment]
oh sorry i dont moving it to common
