### ISSUE TITLE
General Improvement Ideas

### ISSUE THREAD

**Issue by RlonRyan** [TEdit/Terraria-Map-Editor#416]
- [x] Display path to log file on error messages. (Someone asked where the logs were in one of the issues)
- [ ] Display a first-use message pointing to a tutorial.
- [ ] Make the wiki and help pages easier to find. (To keep people from making pointless issues)
- [x] Add an optional update checker that displays a link to the latest version. (To keep people from making an issue about an already resolved issue)
- [ ] Add a report error troubleshooter that checks version and other common mistakes before pointing to the issue list.
- [x] Have the installer replace/update the old version. (Optional though, as some may wish to keep older versions)
- [x] Use more checkboxes.
- [ ] Add a startup tip box / announcement message box to announce news and help new users. (Optional)(Should be easily turned off)
- [ ] Make certain things download quick patches or be end-user editable (aka the settings file) (The quick patches idea would bring revenue down as it would not require users to go through ad-fly to update, too bad this can't be integrated into the installer code, as I understand hosting can be costly)

**Comment by BinaryConstruct** [comment]
Migrated the rest to #1274
