### ISSUE TITLE
New Sprite and Item Picker

### ISSUE THREAD

**Issue by Aimeryan** [TEdit/Terraria-Map-Editor#422]
Any chance the sprites could be tagged in some way based on what they are/do? 

I would like to be able to filter by such a tag, either using the filter textbox (and a hashtag?) or via a drop-down menu.

Examples would be all sprites that are furniture related, all plant/flower related ones, all paintings, all lighting, all crafting stations, etc.

Thanks to the recent patch the sprite list is getting huge and items of a similar function are dispersed throughout. They could just be sorted, but such sorting would probably require identifying like things anyway, so might as well tag them while at it.

**Comment by BinaryConstruct** [comment]
A new sprite tool is now with a different take on usage.
