### ISSUE TITLE
[Renderer] Paint Color support

### ISSUE THREAD

**Issue by BinaryConstruct** [TEdit/Terraria-Map-Editor#454]
Add rendering and editing of Paint Colors

**Comment by enigmaquip** [comment]
Rendering is interesting on this one.
Doing simple coloration in theory isn't hard, was playing with that already
But Terraria itself uses an Effect pixel shader. Which we can't just load and use as monogame doesn't like XNA compiled effects....

**Comment by BinaryConstruct** [comment]
For textured tiles (zoomed in), the spritebatch.draw method takes a color to overlay on the final image

such as:
_spriteBatch.Draw(wallTex, dest, source, Color.White, 0f, default(Vector2), SpriteEffects.None, LayerTileWallTextures);

https://github.com/TEdit/Terraria-Map-Editor/blob/master/TEditXna/View/WorldRenderXna.xaml.cs#L496

For the pixel tiles, this method will need to be updated to alpha blend the paint color (similar to the way wires work).
https://github.com/TEdit/Terraria-Map-Editor/blob/master/TEditXna/Render/PixelMap.cs#L39

**Comment by enigmaquip** [comment]
Paints are in the settings.xml, and iirc when I added paint editing I have the zoomed out pixel map showing paint colors I believe.... and they color overlay is the way I was playing with simple coloration as I said, if that's the route we want to go that's easy to do.... It's just that when you look at the way paints are rendered in Terraria that things get more complex, hence the effects shader. For example trees, regular paints will only color the leaves, while deep paints cause the trunks to get painted as well. Certain wall types will also only show coloration if it's a deep paint or higher.. > 13 I believe, it may be all of them I didn't investigate that deep

**Comment by BinaryConstruct** [comment]
For trees there might have to be some additional flags captured in this vicinity 
https://github.com/TEdit/Terraria-Map-Editor/blob/master/TEditXna/View/WorldRenderXna.xaml.cs#L559

To adjust the the color here
https://github.com/TEdit/Terraria-Map-Editor/blob/master/TEditXna/View/WorldRenderXna.xaml.cs#L941
