### ISSUE TITLE
Add search function for sprites and chest contents with cycling through instances / highlighting on the map

### ISSUE THREAD

**Issue by uxlapogi** [TEdit/Terraria-Map-Editor#473]
I think it would be highly useful to be able to find all instances of a given sprite.

This does not even need to select them all, just to be able to find every instance of it. Maybe like text search in text editors, F3 jumps to the next occurrence and centers it at full zoom.

Shading the map darker and highlighting every instance would be another option.

Both would be awesome.

In addition, searching for chest contents would probably be a second subtype of searching, that could a) give a list of all chests that contain that item, b) give a list of all items present in the world in a tree view with the corresponding chests in a subtree or c) just list all chests and their contents with the possibility to add filters.

I think I'd prefer option b).

**Comment by 503geek** [comment]
Since this issue still appears very high in Google search queries about this feature as of 2022, I think it's worth mentioning that there is now a plugin for searching chests that ships with the default release.
