### ISSUE TITLE
New mask option: "Edit !="

### ISSUE THREAD

**Issue by kyoma** [TEdit/Terraria-Map-Editor#490]
As the title says.

**Comment by SinisterStairs** [comment]
Anyone working on this?  I'll take a look at it this weekend if no one else has.

**Comment by SinisterStairs** [comment]
I'm not able to assign myself to this, for whatever reason.

Anyways, can you look at my commit above:  Does my logic in WorldViewModel.Editor.cs SetTile() look correct?  I'm not sure if I'm handling Tile.IsActive correctly.

Is the IsActive flag a Terraria setting, like in/active blocks/actuators, or in/active sprites like lamps, or is it a setting that TEdit uses?

**Comment by SinisterStairs** [comment]
There's a logical defect in my code so all inactive tiles could be affected.  (Missed a pair of parentheses.)  I'll fix it tonight.
