### ISSUE TITLE
How do I stop automatic backups

### ISSUE THREAD

**Issue by Snowyflakes** [TEdit/Terraria-Map-Editor#542]
The program is making tons of backups for stuff that is not even for terraria, like terraria world backups for a notepad file or random files from other games. I tried uninstalling and deleting the extra files but it still makes new ones? How do I stop this because I really like the program but this is really bothering me.

**Comment by sorcelon** [comment]
Go to My Documents\My Games\Terraria, then open config.json file and set "RollbacksToKeep" : 0,


Hope u fix it
