### ISSUE TITLE
Placing multiple sprites (e.g. minecart track)

### ISSUE THREAD

**Issue by jgbishop** [TEdit/Terraria-Map-Editor#554]
It would be super awesome if there was a way to place multiple sprites at once; sort of a _pencil_ mode for sprites, say. This would make placing minecart tracks (or other long runs of sprites) a lot easier. If there's already a way to do this, then I missed it.

**Comment by enigmaquip** [comment]
What use would you see for this besides minecart tracks and platforms? As this was something I had thought about taking a crack at

**Comment by ahamling27** [comment]
Another option could be biome specific grass, but in order for it to not looks repetitive, it would need to be randomized with each placement. That may just be too hard to implement, then again, I'm no programmer, so I have no idea.

**Comment by BinaryConstruct** [comment]
Using #1273 for future work on sprite tools
