### ISSUE TITLE
Cannot place any blocks!

### ISSUE THREAD

**Issue by Kirbyrocket** [TEdit/Terraria-Map-Editor#573]
OS: Windows Vista

So I was trying to make a map. Something simple. I needed to use the pencil and brush tool. When all of a sudden it wouldn't write anything. I was confused. I tried to do toy with it and press a couple buttons or two and it still did the same thing. I undid what I had just done and still no progress. Any help here?

**Comment by lowryder574** [comment]
Ah, and yet four years later the issue is still going on.

**Comment by PepperedJerky** [comment]
After selecting an area with the select tool, ensure you right-click with the select tool enabled to remove your selection, otherwise any modifications you make will be limited to that selected area.

**Comment by TheCToTheY** [comment]
Can't place a damn thing. Can't paste anything either, schematics etc. Only for one map. I tried restarting, issue persists on one map. Made sure there was no selection.

**Comment by RussDev7** [comment]
> Can't place a damn thing. Can't paste anything either, schematics etc. Only for one map. I tried restarting, issue persists on one map. Made sure there was no selection.

What TEdit version you finding the issue in?

**Comment by TheCToTheY** [comment]
> > Can't place a damn thing. Can't paste anything either, schematics etc. Only for one map. I tried restarting, issue persists on one map. Made sure there was no selection.
> 
> What TEdit version you finding the issue in?

I was using 4.11.4
