### ISSUE TITLE
Unsaved world data

### ISSUE THREAD

**Issue by Adeonek** [TEdit/Terraria-Map-Editor#584]
hey, my laptop suddenly overheated and shutted down while playing Terraria...laptop is ok, but my Terraria world is somehow corrupted, or injured, so I can´t launch it...I tried to replace my world.wld by world.wld.bak but it didn´t worked, could you look at it? could it be saved? :D :( https://www.dropbox.com/s/lvnoum79z3cacn4/Worlds.rar?dl=0

**Comment by Walkman100** [comment]
https://github.com/TEdit/Terraria-Map-Editor/issues/246#issuecomment-74345662
