### ISSUE TITLE
TEdit Autosave Issue

### ISSUE THREAD

**Issue by kewlies** [TEdit/Terraria-Map-Editor#587]
TEdit pauses intermittently letting me know it is autosaving. I see the little progress bar saying it's autosaving. I spent 5 hours working on a project and when I stepped away from the comp for 3 mins, the screensaver kicked on and crashed the program. No biggie, right? because it was autosaving...

Wrong.

I have no idea where to find this alleged autosave data. I reopened the world and it was blank with nothing on it.

Is this a bug that's being looked at or am I insane?

**Comment by Walkman100** [comment]
> the screensaver kicked on and crashed the program

Pretty sure this is a known problem. I don't know about the data being lost though...

**Comment by kewlies** [comment]
Oh, it was lost. 100%

All I was able to do to prevent it from happening again is disable the "auto-save" (which I think is just sarcasm since it doesn't actually save anything) and make Ctrl+S my new best friend... also disabled my screensaver.
