### ISSUE TITLE
Tedit (latest version) not working visually

### ISSUE THREAD

**Issue by Palhum** [TEdit/Terraria-Map-Editor#590]
Alright, so i decide to start trying stuff out with tedit, so i download it for the first time.
Thing is, once i open it, edit starts up with a white screen on the visual menu. and once i open it into full screen, it goes like this
![523eee7b4757639772285a84c53b6f71](https://cloud.githubusercontent.com/assets/12251770/7472090/f8b6c14a-f32e-11e4-982f-4e73d5b49b16.png)
loading a world doesnt help, it's still with the same buggy screen, but i can see the minimap on the top right. tedit seems to detect what kind of squares is my cursor on. but visually it doesn't show up anything at all
there is no error log, and i have terraria bought on steam.

**Comment by Walkman100** [comment]
Is this the same PC that you can run Terraria on? It sounds like a graphics (card or drivers) issue, try running it on another PC if you can.
