### ISSUE TITLE
Can remove Hallow in certain biomes but not in snow biome D:

### ISSUE THREAD

**Issue by XNightShadeX** [TEdit/Terraria-Map-Editor#594]
Ok i've been havings some issues with Tedit lately i've been purifying my world with Tedit and I got rid of all the Crimson now I moved on to the Hallow and I got rid of it all in the grass biome but now I started to do it in the snow biome but I can't do it for some reason. I don't feel like using the brush because I wanna keep all the caves and stuff so if anyone knows what's going on or has another way to do it please help me out :dash:

**Comment by Walkman100** [comment]
> but I can't do it for some reason.

That's not very explanatory, how are you converting/purifying? And I don't think it would be relevant, but TEdit version? Terraria version?

> I don't feel like using the brush because I wanna keep all the caves and stuff

Not sure why you would ever use the brush for converting biomes, you should be using the morph tool...

**Comment by BinaryConstruct** [comment]
Use the morph tool.
