### ISSUE TITLE
.net framework 4 and 4.5.2

### ISSUE THREAD

**Issue by sweetloo32** [TEdit/Terraria-Map-Editor#602]
I have the latest .net framework. It wont let me properly use TEdit, yet when I uninstall it and get framework 4 it works. here lies the problem, I want to be able to use TEdit but there are other things that i have that require the latest framework. Can anyone confirm this is the problem and if so how i can make both things work.

**Comment by Walkman100** [comment]
Can you not install framework 4, then the latest on top of it? also, I thought the .Net framework was designed so if you have the latest version then all previous versions are supported...

**Comment by SBlogic** [comment]
I'm running Windows 7 SP1 64bit with .NET 4.52 installed, no problems getting TEdit to run.  Generally the framework versions should be backward compatible, as far as I'm aware.  Could you elaborate on "won't let me properly use" it?  Does the program run at all?  Is it partially usable but crashes?  Is there an error message?  Check in your Documents\My Games\Terraria folder for a TEditLog.txt file and paste the contents?
