### ISSUE TITLE
Trying to get my corrupt world back, on TEdit It doesn't even show the world, etc

### ISSUE THREAD

**Issue by Verzachi** [TEdit/Terraria-Map-Editor#607]
Title was pretty much what I was trying to do. But then when I tried to my other worlds, not corrupted, it gave me this error: http://prntscr.com/7piyxy
And they won't show up either because of this error.
Here's the TEditLog for me trying to load up my corrupt world: http://prntscr.com/7pj0gv
All help is appreciated.

**Comment by SBlogic** [comment]
We're still working out support for 1.3, so the current released version isn't going to read a 1.3.0.x world correctly.  Hang tight, we're getting there.

**Comment by Verzachi** [comment]
Oh, didn't know, sorry 'bout that. Any idea when TEdit maybe ready to read those types of worlds?

**Comment by SBlogic** [comment]
Some basic 1.3 functionality is working but hasn't been compiled into a distribution yet.  I'd love to give an ETA on it, but I don't have the final say -- I'm just one of the humble peasants helping to make it happen.  =)

**Comment by Verzachi** [comment]
Alrighty then. Thanks for your help.

**Comment by ZAchAttach2354** [comment]
It works when you create a world from TEdit but i don't know how to use it so
