### ISSUE TITLE
Won't open "Open World" Window or Save as or even save at all.

### ISSUE THREAD

**Issue by Greifherz** [TEdit/Terraria-Map-Editor#612]
It starts just fine, but it fails to open a Windows Window to select a world to open or one to save the world.

I know it isnt supported at 1.3 yet, but I'm trying to create an empty world. It does create but cannot save.

If i try to send an existing world file as parameter it does open, but still does not save.

Checked the TEdit log, here it is:

07-14-2015 09:56: Starting TEdit 3.5.15047.30 
07-14-2015 09:56: OS: Microsoft Windows NT 6.1.7600.0 
07-14-2015 09:56: .Net >= 4.0 
07-14-2015 09:56: XNA 4.0 
07-14-2015 09:56: Terraria Data Path: D:\Program Files (x86)\Steam\steamapps\common\Terraria\Content 
07-14-2015 09:56: Creating Undo cache: C:\Users\Douglas Barbara\AppData\Roaming\TEdit\undo_259328080 
07-14-2015 09:56: Error - This method does not accept null for this parameter.
Parameter name: data
   at Microsoft.Xna.Framework.Graphics.Texture2D.CopyData[T](Int32 level, Nullable`1 rect, T[] data, Int32 startIndex, Int32 elementCount, UInt32 options, Boolean isSetting)
   at Microsoft.Xna.Framework.Graphics.Texture2D.GetData[T](Int32 level, Nullable`1 rect, T[] data, Int32 startIndex, Int32 elementCount)
   at TEditXna.View.WorldRenderXna.LoadTerrariaTextures(GraphicsDeviceEventArgs e) 
07-14-2015 09:56: Error - Arithmetic operation resulted in an overflow.
   at TEditXna.View.WorldRenderXna.LoadTerrariaTextures(GraphicsDeviceEventArgs e)

**Comment by Walkman100** [comment]
Is that the latest from http://www.binaryconstruct.com/games/tedit/?

**Comment by Greifherz** [comment]
Yep.

Tried some other versions both portable and installing too.

Tried:
TEdit3Installer_3.5.14267.29
TEdit3Installer_3.5.14228.27 (used to work when i played back in 2014)
TEdit3Installer_3.5.1547.30

**Comment by TheHoodedTeddy13** [comment]
You realize that it hasn't been updated for 1.3 yet, right?  Be patient.

**Comment by Walkman100** [comment]
@TheHoodedTeddy13
> I know it isnt supported at 1.3 yet, but I'm trying to create an empty world. It does create but cannot save.

**Comment by Walkman100** [comment]
> TEdit3Installer_3.5.1547.30

Where did you get that? If I try to download from http://www.binaryconstruct.com/games/tedit/ it gives me `TEdit3Installer_3.5.14228.27`, and the last release on the Releases page of this repo was on Oct 2013...

**Comment by SBlogic** [comment]
Those three versions (all available [here](http://www.binaryconstruct.com/downloads/)) are old builds that only support 1.2.4.1.  They're not compatible with 1.3.0.x worlds.

**Comment by Greifherz** [comment]
From this link
http://www.binaryconstruct.com/downloads/

it's still the same domain, so it's still legit as far as I can tell.

Btw, tried downloading the git and rebuilding.

**Comment by TheHoodedTeddy13** [comment]
How do you rebuild from The data anyway?  I would love to test out all these guys' hard work, but I have no idea how.

**Comment by Greifherz** [comment]
@TheHoodedTeddy13 

There is a .bat that will execute all the build stuff called build.bat or something.
Can't check atm, will edit later.

**Comment by TheHoodedTeddy13** [comment]
Will that edit the version that is shortcutted already on my desktop?  Or is there a new .exe hidden somewhere?
