### ISSUE TITLE
Bug: Won't open when world is on Hardmode

### ISSUE THREAD

**Issue by flight391** [TEdit/Terraria-Map-Editor#616]
So recently TEdit stopped working when I entered hardmode, This was a bit annoying, Maybe a fix within the next 10 weeks?

**Comment by flight391** [comment]
Btw, I don't know what was causing the Error

**Comment by speeder** [comment]
What version of TEdit?

**Comment by flight391** [comment]
It's fine now, I figured my anti virus blocked it

**Comment by Walkman100** [comment]
Then you should close the issue.

**Comment by gogobebe2** [comment]
^
