### ISSUE TITLE
Unhandled Exception of Type ''System.OutOfMemoryException' for Schematics

### ISSUE THREAD

**Issue by 32GreyWolf** [TEdit/Terraria-Map-Editor#618]
Hi. I have been getting this message 'Exception of type ''System.OutOfMemoryException' was thrown.' every time I try and import a schematic from TEdit's Schematics folder. I have uninstalled the programme, reinstalled it, ran it in Admin mode but always get the same damn message :/
![tedit bug](https://cloud.githubusercontent.com/assets/13406703/8767101/4fd179f2-2e49-11e5-97f6-4f90a18d0bdf.jpg)

**Comment by CyberZHG** [comment]
Could be the same issue with #632.
Importing the schematics with the size of large map will use about 3GB memory.
