### ISSUE TITLE
Can't Open .wld files.

### ISSUE THREAD

**Issue by KlaxoMartin** [TEdit/Terraria-Map-Editor#623]
I can open Tedit v.3.5.14228.27. And can select "Open". When i select a .wld file, it gives crash.

"There was an error reading the world file. Do you wish to force it to load anyway?

WARNING: This may have unexpected results including corrupt world files and program crashes.

The Error is:
System.IO.FileFormatExpection: Unexpected Position: Invalid File Format
Position: TeditXNA.Terraria.World.LoadV2. (Binary Reader b, String filename, World w)
C:/Atlassian/ApplicationData/Bamboo/xml-data/build-dir/TED-CI-JOB1/TeditXNA/Terraria/WorldFileV2.cs In: line 486

C:/Atlassian/ApplicationData/Bamboo/xml-data/build-dir/TED-CI-JOB1/TeditXNA/Terraria/World.cs In: line 110"

But i have not Atlassian folder in C. What should i do?

**Comment by Walkman100** [comment]
First of all, check that you are using a supported Terraria and World version (latest 1.2.4.1)

**Comment by Elgodeorn** [comment]
I hae exactly the same problem.

**Comment by RabblerouserGT** [comment]
So this doesn't support 1.3 worlds? Then the Terraria wiki is lying?

**Comment by Walkman100** [comment]
@RabblerouserGT Good idea.

**Comment by TheHoodedTeddy13** [comment]
Can someone link the fork?

**Comment by BinaryConstruct** [comment]
binaryconstruct.com/downloads
