### ISSUE TITLE
Cant open worlds

### ISSUE THREAD

**Issue by CookieGamer084** [TEdit/Terraria-Map-Editor#624]
07-27-2015 17:06: Starting TEdit 3.5.14228.27 
07-27-2015 17:06: OS: Microsoft Windows NT 6.1.7601 Service Pack 1 
07-27-2015 17:06: .Net >= 4.0 
07-27-2015 17:06: XNA 4.0 
07-27-2015 17:06: Terraria Data Path: D:\Games\Steam\steamapps\common\Terraria\Content 
07-27-2015 17:06: Creating Undo cache: C:\Users\Nudelino\AppData\Roaming\TEdit\undo_101885236 
07-27-2015 17:06: Error - This method does not accept null for this parameter.
Parametername: data
   bei Microsoft.Xna.Framework.Graphics.Texture2D.CopyData[T](Int32 level, Nullable`1 rect, T[] data, Int32 startIndex, Int32 elementCount, UInt32 options, Boolean isSetting)
   bei TEditXna.View.WorldRenderXna.LoadTerrariaTextures(GraphicsDeviceEventArgs e) 
07-27-2015 17:06: Error - Die arithmetische Operation hat einen Überlauf verursacht.
   bei TEditXna.View.WorldRenderXna.LoadTerrariaTextures(GraphicsDeviceEventArgs e) 
07-27-2015 17:07: Removing old undo cache: C:\Users\Nudelino\AppData\Roaming\TEdit\undo_101653216 
07-27-2015 17:07: Removing undo cache: C:\Users\Nudelino\AppData\Roaming\TEdit\undo_101885236

**Comment by Walkman100** [comment]
https://github.com/TEdit/Terraria-Map-Editor/issues/619#issuecomment-124245234

**Comment by CookieGamer084** [comment]
Thanks but here it sais it's compatible with 1.3 Link: http://terraria.gamepedia.com/Map_viewers

**Comment by Walkman100** [comment]
Ok, I'll change it. Please read through the existing discussions to see the status of TEdit.

**Comment by Walkman100** [comment]
Oh it's already been changed :+1:
