### ISSUE TITLE
How can I install Tedit?

### ISSUE THREAD

**Issue by CookieGamer084** [TEdit/Terraria-Map-Editor#625]
There is no .exe file or an installation programm!

**Comment by Walkman100** [comment]
http://www.binaryconstruct.com/games/tedit/

You have to extract it, it's in a zipped file

Also note that TEdit only works with Terraria 1.2.4.1

**Comment by Walkman100** [comment]
Also see https://github.com/TEdit/Terraria-Map-Editor/wiki/Getting-Started
