### ISSUE TITLE
World file error

### ISSUE THREAD

**Issue by mantisUK** [TEdit/Terraria-Map-Editor#626]
Hey just got tedit, i used to before a long time ago and it worked fine but now with the 3.5 update i get this.

There was an error reading the world file, do you wish to force it to load anyway? 

the error is: 
System.IO.FileFormat Expception:unexpcted Position:invailed file format section 
 at TEditNA. Terraria.World.LoadV2(BinaryReader b, String filename. World w)
 at TEditXNA. Terraria. World.LoadWorld(String filename)

**Comment by Walkman100** [comment]
Are you using a 1.3+ world?

**Comment by mantisUK** [comment]
yup

**Comment by Walkman100** [comment]
Please see http://terraria.gamepedia.com/Map_viewers#TEdit. The official TEdit (this repo) only supports Terraria v1.2.4.1

**Comment by mantisUK** [comment]
ah any idea when it updated to work on 1.3?

**Comment by Walkman100** [comment]
If you look on the page I linked, you will see there is a download for a 1.3 compatible version (it says (alternate download)) - please note it's unofficial and beta.

**Comment by mantisUK** [comment]
yeah i tried that one. I cant get that working for a start the installer is a .wixproj which i have never heard of

**Comment by SBlogic** [comment]
[WiX Toolset](http://wixtoolset.org/) is needed to build the .msi installer, but it's not technically required.  It should still build the binaries required to run a portable-type version that could be run from any location.

**Comment by mantisUK** [comment]
Installed that program and it did nothing to running the installer. Ill just wait for the proper .msi installer release, this is to technical and way over my hand. I just want to make pretty maps :).

**Comment by Walkman100** [comment]
> yeah i tried that one. I cant get that working for a start the installer is a .wixproj which i have never heard of

What? The `(alternate download)` link under `TEdit (1.3-compatible fork)` on http://terraria.gamepedia.com/Map_viewers#TEdit goes to https://dl.dropboxusercontent.com/u/21952217/TEdit%20(fromSource).zip, which contains a `TEdit3Installer.msi` file... not sure where you got a `WiXProj` file...

**Comment by mantisUK** [comment]
i clicked the normal download not the alt one thanks, ill give that one a try.

**Comment by mantisUK** [comment]
yeah that worked thanks :)
