### ISSUE TITLE
Support for Steam Cloud worlds

### ISSUE THREAD

**Issue by SinisterStairs** [TEdit/Terraria-Map-Editor#628]
I'm submitting this as an issue because I haven't used Github in a long time and can't figure out how to message someone directly:

I'm going to try adding support for Steam Cloud worlds this weekend.  Should I fork from @BinaryConstruct's project or @SBLogic's fork?  I'd like my change to make it back to the master, but SBLogic's fork is the more active/usable version.

**Comment by SBlogic** [comment]
I'd prefer that new features aren't submitted against my fork.  Please fork from the master, and then create a PR in your fork comparing to mine to get the consolidated (and not yet merged) updates from myself, @speeder, @enigmaquip, and @CyberZHG.  Merge that into your fork and go from there.

**Comment by enigmaquip** [comment]
What support are you thinking of adding? Loading worlds is just a matter of pointing to the right folder.... be it My Documents\My Games\Terraria\Worlds.... which is the default for offline worlds and where TEdit initially opens the open map dialog or... Program Files\Steam\userdata\(user_id)\(app_id)\remote\worlds
app_id is 105600 for terraria
user_id is unique and there could be more than one depending on how many log into steam on that computer

**Comment by SinisterStairs** [comment]
Thanks.

Yes, my update will be quite modest:  I'm just going to add an optional <SteamUserId> to settings.xml that, if uncommented out, will allot TEdit open worlds from the Steam userdata rather than My Documents.
