### ISSUE TITLE
No texture displayed when the first time TEdit was opened

### ISSUE THREAD

**Issue by CyberZHG** [TEdit/Terraria-Map-Editor#629]
![1](https://cloud.githubusercontent.com/assets/853842/9020397/fe12775e-383b-11e5-8f0a-5ffd389d8149.jpg)

Maybe the order of loading and locating is not correct.

**Comment by SBlogic** [comment]
What's the state of the "Show Textures" item in the Display menu?  Was it unchecked?  (This is probably a good thing since having an invalid/outdated settings.xml will usually cause a crash with unknown textures.)

**Comment by CyberZHG** [comment]
It is checked.
![image](https://cloud.githubusercontent.com/assets/853842/9030607/84a750e0-39d7-11e5-9f10-d36b2652c9d4.png)

The textures will show correctly after the first time.
