### ISSUE TITLE
Add hand tool to drag the map

### ISSUE THREAD

**Issue by CyberZHG** [TEdit/Terraria-Map-Editor#630]
![image](https://cloud.githubusercontent.com/assets/853842/9020413/585c91ee-383d-11e5-99a4-e0c0f37ecb86.png)

**Comment by Shona1984** [comment]
Press the middle mouse button aka the whell down and you have your hand toll =)

**Comment by CyberZHG** [comment]
...it hides so deep....

**Comment by isochronous** [comment]
Could I possibly convince you guys to add a keyboard-based shortcut for this? Say, holding down the space bar, the same way a VAST majority of graphics editing programs do? Not only do I think that would be WAY more intuitive and discoverable for anyone who's ever used any graphics editing program, I also find that holding down my mouse wheel and moving my mouse is not a very comfortable thing to do.

**Comment by BinaryConstruct** [comment]
Sure! Most of the shortcuts are based on paint.net. I plan on adding a settings menu to update keyboard commands, but for now you can update settings.xml for some shortcuts.

**Comment by isochronous** [comment]
Awesome, thank you!
