### ISSUE TITLE
Hi guys nice work but I have a problem. Uploaded TEditLog.txt

### ISSUE THREAD

**Issue by ValkyrieCain** [TEdit/Terraria-Map-Editor#631]
Thank you for this awesome project and helping me.

08-01-2015 12:39: Starting TEdit 3.5.15209.1427 
08-01-2015 12:39: OS: Microsoft Windows NT 6.2.9200.0 
08-01-2015 12:39: .Net >= 4.0 
08-01-2015 12:39: XNA 4.0 
08-01-2015 12:39: Terraria Data Path: F:\!KorumaYok!\Ekrem\Diger\Terraria By Bioma BK\Content 
08-01-2015 12:39: Creating Undo cache: C:\Users\ekrem\AppData\Roaming\TEdit\undo_216763210 
08-01-2015 12:40: Error - Nesne başvurusu bir nesnenin örneğine ayarlanmadı.
   konum: TEditXna.ViewModel.WorldViewModel.MouseMoveTile(TileMouseState e)
   konum: TEditXna.View.WorldRenderXna.xnaViewport_HwndMouseMove(Object sender, HwndMouseEventArgs e)
   konum: TEdit.UI.Xaml.XnaContentHost.GraphicsDeviceControl.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   konum: System.Windows.Interop.HwndHost.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   konum: MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   konum: System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   konum: MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   konum: System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   konum: MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   konum: MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   konum: System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   konum: System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   konum: System.Windows.Threading.Dispatcher.Run()
   konum: System.Windows.Application.RunDispatcher(Object ignore)
   konum: System.Windows.Application.RunInternal(Window window)
   konum: System.Windows.Application.Run(Window window)
   konum: TEditXna.App.Main() 

Edit: Language is Turkish.

**Comment by CyberZHG** [comment]
Which release are you using and what were you doing when TEdit crashed?

**Comment by Shona1984** [comment]
@CyberZHG

Quote:" 08-01-2015 12:39: Starting TEdit 3.5.15209.1427 "

He is using the 1.3 Fork, i have the same problems sometimes if i delete blocks or if i copy and paste blocks

Translation of "08-01-2015 12:40: Error - Nesne başvurusu bir nesnenin örneğine ayarlanmadı."
---> "Error - Object reference not set to an instance of an object."

**Comment by CyberZHG** [comment]
@Shona1984 

What you said might be the known issue #627 that the application might crash if the left-top corner is chest/sign/grave/dresser.

However, #627 should not happen while moving the mouse, and the top of the call stack is:
```
TEditXna.ViewModel.WorldViewModel.MouseMoveTile(TileMouseState e)
```

![image](https://cloud.githubusercontent.com/assets/853842/9025027/6989d274-3923-11e5-9c09-a66245daa798.png)

**Comment by Shona1984** [comment]
@CyberZHG 
Nope it is not the issue #627 i mean because i do not copy & paste chest.

If he is doing this ok, but i don't i delete & paint, cut out and paste it but never chests i don't need my chests again. I have enough with enough crap in it ^^

**Comment by CyberZHG** [comment]
@Shona1984 

I'm sorry I failed to understand the second paragraph...

**Comment by Walkman100** [comment]
> Terraria Data Path: F:!KorumaYok!\

Woah. Nice path hacking :stuck_out_tongue_winking_eye: 
> Error - Object reference not set to an instance of an object.

Most useless & dreaded error in programming.
> TEditXna.ViewModel.WorldViewModel.MouseMoveTile(TileMouseState e)

Probably the most important line in this log, but still not very helpful...
