### ISSUE TITLE
"System.OutOfMemoryException" 

### ISSUE THREAD

**Issue by Shona1984** [TEdit/Terraria-Map-Editor#632]
Are you planing a 64bit Version?

Because i run all the time out of memory and i have 8GB but 32bit can only use max. 2GB per process. Tedit using the most time 1.1 - 2+GB so it crashes. Also it runs really slow on my SSD.

I know it is only a fork but please think about a 64bit Version, please. :)

--------------------------
Terraria 1.3.0.7
TEdit: 3.5.15209.1427 
Log:

08-02-2015 07:37: Starting TEdit 3.5.15209.1427 
08-02-2015 07:37: OS: Microsoft Windows NT 6.1.7601 Service Pack 1 
08-02-2015 07:37: .Net >= 4.0 
08-02-2015 07:37: XNA 4.0 
08-02-2015 07:37: Terraria Data Path: d:/steam\steamapps\common\terraria\Content 
08-02-2015 07:37: Creating Undo cache: C:\Users\Shona\AppData\Roaming\TEdit\undo_888831694 
08-02-2015 08:05: Error - Eine Ausnahme vom Typ "System.OutOfMemoryException" wurde ausgelöst.
   bei TEditXna.Editor.Tools.BrushTool.MouseDown(TileMouseState e) in c:\Users\Erwan Le Pape\Documents\Visual Studio 2013\Projects\Terraria Map Editor\SBlogic - Copy\TEditXna\Editor\Tools\BrushTool.cs:Zeile 34.
   bei TEditXna.ViewModel.WorldViewModel.MouseDownTile(TileMouseState e) in c:\Users\Erwan Le Pape\Documents\Visual Studio 2013\Projects\Terraria Map Editor\SBlogic - Copy\TEditXna\ViewModel\WorldViewModel.cs:Zeile 639.
   bei TEditXna.View.WorldRenderXna.xnaViewport_HwndLButtonDown(Object sender, HwndMouseEventArgs e) in c:\Users\Erwan Le Pape\Documents\Visual Studio 2013\Projects\Terraria Map Editor\SBlogic - Copy\TEditXna\View\WorldRenderXna.xaml.cs:Zeile 1592.
   bei TEdit.UI.Xaml.XnaContentHost.GraphicsDeviceControl.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled) in c:\Users\Erwan Le Pape\Documents\Visual Studio 2013\Projects\Terraria Map Editor\SBlogic - Copy\TEditXna\UI\Xaml\XnaContentHost\GraphicsDeviceControl.cs:Zeile 482.
   bei System.Windows.Interop.HwndHost.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   bei MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   bei MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   bei System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   bei MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   bei MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   bei System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   bei System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   bei System.Windows.Threading.Dispatcher.Run()
   bei System.Windows.Application.RunDispatcher(Object ignore)
   bei System.Windows.Application.RunInternal(Window window)
   bei System.Windows.Application.Run(Window window)
   bei TEditXna.App.Main() in c:\Users\Erwan Le Pape\Documents\Visual Studio 2013\Projects\Terraria Map Editor\SBlogic - Copy\TEditXna\obj\x86\Release\App.g.cs:Zeile 0.

**Comment by CyberZHG** [comment]
Right click TEditXna -> Properties and:

![image](https://cloud.githubusercontent.com/assets/853842/9025555/3c5089a2-393b-11e5-9889-57a1664563e8.png)

**Comment by Shona1984** [comment]
Of i Right click TEditXna -> Properties it definitely don't look like this.
What are u using? Is it Microsoft Visual Studio?

**Comment by Hecatoncheyr** [comment]
Yes, he's using Microsoft Visual Studio. It does build a x64 version to use, but it doesn't help the crashes.

08-02-2015 09:44: Starting TEdit 3.5.15214.0843 
08-02-2015 09:44: OS: Microsoft Windows NT 6.2.9200.0 
08-02-2015 09:44: .Net >= 4.0 
08-02-2015 09:44: XNA 4.0 
08-02-2015 09:44: Terraria Data Path: C:\Program Files (x86)\Steam\steamapps\common\Terraria\Content 
08-02-2015 09:44: Creating Undo cache: C:\Users\heca\AppData\Roaming\TEdit\undo_797559263 
08-02-2015 09:45: Error - Exception of type 'System.OutOfMemoryException' was thrown.
   at TEditXna.Editor.Tools.SpriteTool.MouseDown(TileMouseState e) in c:\Users\heca\Downloads\Terraria-Map-Editor-master\Terraria-Map-Editor-master\TEditXna\Editor\Tools\SpriteTool.cs:line 63
   at TEditXna.ViewModel.WorldViewModel.MouseDownTile(TileMouseState e) in c:\Users\heca\Downloads\Terraria-Map-Editor-master\Terraria-Map-Editor-master\TEditXna\ViewModel\WorldViewModel.cs:line 639
   at TEditXna.View.WorldRenderXna.xnaViewport_HwndLButtonDown(Object sender, HwndMouseEventArgs e) in c:\Users\heca\Downloads\Terraria-Map-Editor-master\Terraria-Map-Editor-master\TEditXna\View\WorldRenderXna.xaml.cs:line 1601
   at TEdit.UI.Xaml.XnaContentHost.GraphicsDeviceControl.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled) in c:\Users\heca\Downloads\Terraria-Map-Editor-master\Terraria-Map-Editor-master\TEditXna\UI\Xaml\XnaContentHost\GraphicsDeviceControl.cs:line 482
   at System.Windows.Interop.HwndHost.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at TEditXna.App.Main() in c:\Users\heca\Downloads\Terraria-Map-Editor-master\Terraria-Map-Editor-master\TEditXna\obj\x64\Release\App.g.cs:line 0

**Comment by CyberZHG** [comment]
Brush Tool:
![image](https://cloud.githubusercontent.com/assets/853842/9026413/1c2fd53a-3961-11e5-95f1-5ef09af48c8d.png)

Sprite Tool:
![image](https://cloud.githubusercontent.com/assets/853842/9026417/3077967c-3961-11e5-89e8-eaccb1ea3f02.png)

It's strange because the large map is 8400 x 2400, and the bool array requires less than 80 MB memory.
I could not figure out why this would happen.

**Comment by CyberZHG** [comment]
![image](https://cloud.githubusercontent.com/assets/853842/9055198/08330ee8-3abb-11e5-8c6c-1a6443cb6730.png)

If you want to use more than 1.3GB memory, the option "__Enable the Visual Studio hosting process__" should not be checked. There is no need to compile the code to x64 since there is a post-build script to change the memory limit to 4GB and it is enough for TEdit.

![1](https://cloud.githubusercontent.com/assets/853842/9055206/1c2fb9aa-3abb-11e5-8774-5b41a47c063e.jpg)

**Comment by Shona1984** [comment]
@CyberZHG
Please write next time that i need the master files because i dowloaded it here http://terraria.gamepedia.com/TEdit#Terraria_Map_Editor with the Alternate Link and thought how can i change the .exe O.o

---

Damn can't open the files with my old Visual Studio 2008 xD 
So i have to wait for a release....

**Comment by Walkman100** [comment]
> Damn can't open the files with my old Visual Studio 2008 xD 

You can get Visual Studio Express 2013 for Windows Desktop, it's free, aulthough it's a ridiculous size.

**Comment by Hecatoncheyr** [comment]
TEdit chose to crash before I could crash it. lol. All I  tried to do was load the sprite tab. 

> An unhandled exception of type 'System.OutOfMemoryException' occurred in PresentationCore.dll

> System.OutOfMemoryException was unhandled
 HResult=-2147024882
 Message=Exception of type 'System.OutOfMemoryException' was thrown.
  Source=TEditXna
  StackTrace:
       at TEditXna.App.CurrentDomain_UnhandledException(Object sender,  UnhandledExceptionEventArgs e) in C:\Users\heca\Desktop\Terraria-Map-Editor-master\Terraria-Map-Editor-master\TEditXna\App.xaml.cs:line 106
  InnerException: 

Okay so fine, tried again only just using pencil tool. 

> System.OutOfMemoryException was unhandled
  HResult=-2147024882
  Message=Exception of type 'System.OutOfMemoryException' was thrown.
  Source=TEditXna
  StackTrace:
       at TEditXna.App.CurrentDomain_UnhandledException(Object sender, UnhandledExceptionEventArgs e) in C:\Users\heca\Desktop\Terraria-Map-Editor-master\Terraria-Map-Editor-master\TEditXna\App.xaml.cs:line 106
  InnerException: 

Interestingly enough, I played around with small and medium sized worlds. Absolutely no effect. I can change tens of thousands of blocks at once, the exact same way. Using/placing sprites, runs just fine. Only large worlds seem to be effected by this error in TEdit.

Unticking the ""Enable the Visual Studio hosting process" does not seem to have an effect with regards to the exception. Its a mystery to me.

**Comment by Walkman100** [comment]
And the platform target? does that make any difference? I expect setting it to x86 (32-bit) would make it worse, at least.

**Comment by Hecatoncheyr** [comment]
Nah doesnt seem to affect it either. Crashes just the same x86 or x64. Its either something super obvious or just totally beyond me. :D

**Comment by CyberZHG** [comment]
Here is a x86 binary: 
[55a2c97](https://drive.google.com/file/d/0BzGgvgeRcwOYejZYNm9xbWdOajQ/view?usp=sharing)

You can try substituting `TEditXna.exe` with this one. The binary should have a memory limit of 4GB and it shall not crash while editing the big map.

**Comment by Walkman100** [comment]
Why not x64? then the limit is even higher :D

**Comment by CyberZHG** [comment]
@Walkman100 

Because whatever I do with the big map (copy & paste the entire map several times, open big map's schematics file, init sprite tool), the memory will not exceed 2.7GB, thus I guess 4GB is enough for most conditions. And x86 has a better compatibility.

**Comment by Shona1984** [comment]
@Walkman100 
I know i can get VS 2013 for free but i have it somewhere. I got it on my education days but i can't find it, i only found the 2008 version^^

@CyberZHG 
The Problem are not only the 2GB Limit, it also crash with the error under 2GB if you are faster then the program. As i wrote in the beginning it is really slow on my SSD, so if i paint to fast or changing the tools to fast it crashes with "System.OutOfMemoryException" or it loads 10-30 seconds and then you see the mess after the "lag".

Also you can create a x86 and a x64 exe so everyone can choose ;)

**Comment by BinaryConstruct** [comment]
The current version with SharpDX and MonoGame is x64.
