### ISSUE TITLE
System.IO.FileFormatException

### ISSUE THREAD

**Issue by gartho33** [TEdit/Terraria-Map-Editor#639]
Version: TEdit v3.5.14228.27

Given Error info: 
"System.IO.FileFormatException: Unexpected Position: Invalid File
Format Section
   at TEditXNA.Terraria.World.LoadV2(BinaryReader b, String filename, World w)
   at TEditXna.Terraia.World.LoadWorld(String filename)"

**Comment by gartho33** [comment]
If anyone can tell me where to find any additional log info please do, as it is not in any obvious place.

**Comment by CyberZHG** [comment]
v3.5.14228.27 is only compatible with Terraria 1.2.4.
You should try a newer one: [TEdit](https://dl.dropboxusercontent.com/u/21952217/TEdit%20(fromSource).zip)
