### ISSUE TITLE
'package.bat' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by wog24435** [TEdit/Terraria-Map-Editor#640]
I get that error when I run nightly.bat

When I run it as admin, I get this:

Building Solution...
Microsoft (R) Build Engine version 4.0.30319.34209
[Microsoft .NET Framework, version 4.0.30319.34209]
Copyright (C) Microsoft Corporation. All rights reserved.

MSBUILD : error MSB1009: Project file does not exist.
Switch: .\TEditNoInstaller.sln
'package.bat' is not recognized as an internal or external command,
operable program or batch file.
Press any key to continue . . .

**Comment by BinaryConstruct** [comment]
I fixed the file. Please note you will need to download nuget packages before running this command. This can be done by opening the solution and compiling in visual studio or running "nuget.exe restore" from the command line. You will need nuget on your system.

see https://docs.nuget.org/consume/command-line-reference
