### ISSUE TITLE
X is defined in an assembly that is not referenced. You must add a reference to assembly

### ISSUE THREAD

**Issue by wog24435** [TEdit/Terraria-Map-Editor#642]
When running build_beta.bat I get the following error:

http://pastebin.com/ybreYTEA

When running it as admin I get this error:

http://pastebin.com/r9xP9yPk

**Comment by Atheran** [comment]
I have the exact same problem as well since the last update. I couldn't find a way to parse the text so I didn't post an issue

**Comment by BinaryConstruct** [comment]
Do you have visual studio installed?
https://www.visualstudio.com/downloads/download-visual-studio-vs
 Or at least Visual Studio 2015 build tools?
https://go.microsoft.com/fwlink/?LinkId=615458
