### ISSUE TITLE
cant open worlds with version TEdit 3.5.14228.27

### ISSUE THREAD

**Issue by Baerht** [TEdit/Terraria-Map-Editor#645]
did a clean install of version TEdit 3.5.14228.27  and when I try and open a world I get this http://imgur.com/4MMPwMx.

the log shows ;  08-12-2015 15:54: Starting TEdit 3.5.14228.27 
08-12-2015 15:54: OS: Microsoft Windows NT 6.0.6002 Service Pack 2 
08-12-2015 15:54: .Net >= 4.0 
08-12-2015 15:54: XNA 4.0 
08-12-2015 15:54: Terraria Data Path: D:\Program file\Steam\steamapps\common\Terraria\Content 
08-12-2015 15:54: Creating Undo cache: C:\Users\Baer\AppData\Roaming\TEdit\undo_505647172 
08-12-2015 15:54: Error - This method does not accept null for this parameter.
Parameter name: data
   at Microsoft.Xna.Framework.Graphics.Texture2D.CopyData[T](Int32 level, Nullable`1 rect, T[] data, Int32 startIndex, Int32 elementCount, UInt32 options, Boolean isSetting)
   at Microsoft.Xna.Framework.Graphics.Texture2D.GetData[T](Int32 level, Nullable`1 rect, T[] data, Int32 startIndex, Int32 elementCount)
   at TEditXna.View.WorldRenderXna.LoadTerrariaTextures(GraphicsDeviceEventArgs e) 
08-12-2015 15:54: Error - Arithmetic operation resulted in an overflow.
   at TEditXna.View.WorldRenderXna.LoadTerrariaTextures(GraphicsDeviceEventArgs e) 
 
There was a windows update today so not sure is that did anything

**Comment by SBlogic** [comment]
That's an old version that doesn't support Terraria 1.3.  Download the latest beta version [here](http://www.binaryconstruct.com/downloads/) if you're trying to edit a 1.3 world.

**Comment by Baerht** [comment]
the 'Lastest Stable ' button takes me to a link that downloads 3.5.14228.27 . i guesse the beta is that latest one then?

**Comment by ahamling27** [comment]
He said to go here: http://www.binaryconstruct.com/downloads/
There's actually a link in his reply, if you didn't notice. Latest stable takes you to the last official, non-beta build that supports Terraria 1.2.4.1.

**Comment by ahamling27** [comment]
Whoops, totally misunderstood you. Yes, the top links that say Beta 3.6 are the latest beta's that work with 1.3.

**Comment by Baerht** [comment]
np ,I should read things better myself
