### ISSUE TITLE
v0.0.0.0 (not responding)

### ISSUE THREAD

**Issue by bloodindigo** [TEdit/Terraria-Map-Editor#648]
Sorry for posting this here too, but I want to be sure that others with the same problem can find it here. :smile: 

Everytime I try to open ANY version of the beta I get a blank, white TEdit screen labelled version 0.0.0.0 (not responding) - The not responding label appears only when I try to click the window.
(I tried every version : from v3.6.15224.0651 to 3.6.15225.0743.)

I hope you can find the problem, as always and bring us tears of joy! Keep the good work! :wink: 

![untitled](https://cloud.githubusercontent.com/assets/13783157/9252420/eced4fea-41e0-11e5-9527-368da4ab5d89.png)

**Comment by Mad-Harry** [comment]
I have the same problem, Can someone explain why? and perhaps someone has a solution

**Comment by Michaelangel007** [comment]
I'm running into a similar issue.  TEdit log file can be found here: `%userprofile%\Documents\My Games\Terraria\TEditLog.txt`

    08-20-2015 11:37: Starting TEdit 3.6.150812.0114 
    08-20-2015 11:37: OS: Microsoft Windows NT 6.1.7601 Service Pack 1 
    08-20-2015 11:37: Terraria Data Path: c:/program files (x86)/steam\steamapps\common\terraria\Content 
    08-20-2015 11:37: Creating Undo cache: C:\Users\XXX\AppData\Roaming\TEdit\undo_761671410 
    08-20-2015 11:37: Failed to load texture: Images\NPC_17 
    08-20-2015 11:37: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 

Older installed version, 3.5.14218.23, starts fine (with pre-Terraria v1.3 worlds of course.)

**Comment by ahamling27** [comment]
Have you tried the latest beta build? It was released yesterday: http://www.binaryconstruct.com/downloads/

**Comment by Michaelangel007** [comment]
Still no joy. Same problem:

| Version | Status |
|:---|:---|
| 3.5.1547.30 | Loads |
| 3.6.15224.0651 | Hangs loading |
| 3.6.15233.0300 | Hangs loading |
| 3.6.15233.1522 | Hangs loading |

**Comment by ipstheboss** [comment]
same dam thing plz help fix this

**Comment by THEJaxster** [comment]
I had a similar error until I update .NET.  Have you updated the .NET to the latest?

**Comment by Michaelangel007** [comment]
Trying [.NET 4.5.2](https://www.microsoft.com/en-us/download/details.aspx?id=42643) ...

**Comment by Baerht** [comment]
have been getting the same thing  . Finally looked at the log to find this  ;
08-24-2015 02:44: DirectX 10 unsupported. DirectX 11 or higher is required. 
08-24-2015 02:44: Terraria Data Path: D:\Program file\Steam\steamapps\common\Terraria\Content 
08-24-2015 02:44: Creating Undo cache: C:\Users\xxxxxx\AppData\Roaming\TEdit\undo_37400974

**Comment by Baerht** [comment]
so I checked  dxdiag and it says I have Direct X 11

**Comment by camelothorse** [comment]
Having the same problem. Dialog pops up saying an update has been found do you want to download it?. Clicking yes or no doesn't matter end result is the same. The program does open, and I can load a world and view its properties on the side bar. But the window where you can edit things is completely blank and clicking on it with any tool instantly crashes the program. Every version of the new beta for 1.3 does this. I downloaded latest versions of directX and .net with no difference. I am running windows 7 64 bit with the latest version of Terraria on Steam.

**Comment by LOK098** [comment]
I'm having the exact same problem as camelothehorse. I currently have Windows 10 and the latest version of Terraria.

**Comment by dinnsdale** [comment]
I'm also having this problem, except my log only ever says "Starting TEdit". I can run it fine if I delete everything, restart my computer, and grab a beta build, but running it a second time renders the blank window with "Not Responding", and if I then close it (and even stopping the process from Task Manager), and try to reopen, the process appears, but no window even appears. Then I have to remove all the files, restart comp, redownload, etc. etc.

**Comment by BinaryConstruct** [comment]
Even if you have DirectX 11 software do you have a DirectX 11 compatible graphics device?

**Comment by Baerht** [comment]
ooo good question ... for me its " Driver Version: 8.15.0010.2202 (English)
      DDI Version: 10 " Iam guessing  that my card isn't Direct x 11 compatible . well that explains my problem then.

**Comment by liquid600pgm** [comment]
Mine log is like this
12-23-2015 16:08: Starting TEdit 3.6.150812.0114 
12-23-2015 16:08: OS: Microsoft Windows NT 6.1.7600.0 
12-23-2015 16:08: Terraria Data Path: c:/program files (x86)/steam\steamapps\common\terraria\Content 
12-23-2015 16:08: Creating Undo cache: C:\Users\gaba\AppData\Roaming\TEdit\undo_877498588

**Comment by caiodesign** [comment]
Same problem here...

TEdit Log:
01-08-2016 05:00: Starting TEdit 3.6.150812.0114 
01-08-2016 05:00: OS: Microsoft Windows NT 6.1.7600.0 
01-08-2016 05:00: Terraria Data Path: c:/program files (x86)/steam\steamapps\common\terraria\Content 
01-08-2016 05:00: Creating Undo cache: C:\Users\mypc\AppData\Roaming\TEdit\undo_399371322

**Comment by karma12gaming** [comment]
I'm also having this issue with Direct X11 Net 4.5.2 & Win 7. Please fix or add support for Direct X9 / Open GL

**Comment by BinaryConstruct** [comment]
Please watch #751 for progress on this known issue.
