### ISSUE TITLE
The world display window doesn't scale correctly

### ISSUE THREAD

**Issue by SinisterStairs** [TEdit/Terraria-Map-Editor#651]
When you resize TEdit to a smaller size, the world display/edit window does not scale properly.  You can see in the screenshot that the world doesn't fully fill its window.  Even if I resize back to the original app size, it doesn't fully scale (but Windows' Maximize does).  This behavior is on the master branch, Windows 7 x64.

![screenshot 2015-08-15 08 38 47](https://cloud.githubusercontent.com/assets/1282348/9288827/4130e2bc-4329-11e5-8b35-b4fb37a02af8.png)

**Comment by SinisterStairs** [comment]
To reproduce:

1. Launch TEdit and open a world
2. Manually resize the TEdit app window to make it smaller, and the world will no longer fully fill its display/edit window

Note that 1a. You can increase the TEdit window and the world will fill accordingly; it's when you decrease the TEdit window that this behavior occurs.

**Comment by enigmaquip** [comment]
I too have seen this problem, you'll notice too when you are using a tool that it will no longer match up properly with the tile the mouse is over

**Comment by SinisterStairs** [comment]
Thank you for adding that -- that's the most critical part of this issue, that the tool cursor no longer matches the tile/position that's being selected.

**Comment by dragon3025** [comment]
I'm still having this problem. I noticed the lower the mouse cursor is, the more the TEdit drawing cursor is higher than the mouse cursor. The more zoomed in you are, the less it will do this.
