### ISSUE TITLE
Can't open TEditXna.exe

### ISSUE THREAD

**Issue by Drflash55** [TEdit/Terraria-Map-Editor#652]
When I try out the latest beta version, v3.6.15225.0743, when I try to open it, I just get an error saying it's not a valid win32 application, implying that it's meant for X64 instead of X86...

![ss 2015-08-17 at 10 33 17](https://cloud.githubusercontent.com/assets/13694448/9307251/69393036-44cb-11e5-8c3b-4b2d7f69e4af.png)

Was this intended, or can it be fixed?

**Comment by BinaryConstruct** [comment]
Please unzip the file before running and see https://github.com/TEdit/Terraria-Map-Editor/wiki/Install-Requirements

**Comment by Drflash55** [comment]
Should probably close this, since I found out a long time ago that most of the programs use Windows 7.

Windows XP sucks, but I can't change it.
