### ISSUE TITLE
Some error in my Computer

### ISSUE THREAD

**Issue by macchandev** [TEdit/Terraria-Map-Editor#653]
Hello, I'm love this Editor, but I've get some error here:

First, when I open TEditXna, it had alert: "Unable to check version."

And I've always been like this error when you open a world.
http://i.imgur.com/P04kQfD.png

I'm using Windows 10. Can any body help me?

**Comment by tanpro260196** [comment]
DuocNham on Vn-S?

**Comment by DuocNham** [comment]
Yeah, I'm DuocNham on VnS

**Comment by tanpro260196** [comment]
Bác sửa được lỗi chưa?

**Comment by DuocNham** [comment]
Chưa ;; _ ;;

**Comment by enigmaquip** [comment]
looks like you are trying to open a newer map in an older version of TEdit, make sure you are running one of the newer beta's that works with 1.3 files

**Comment by DuocNham** [comment]
I'm using latest version of TEdit, not any older version.

**Comment by hbarudi** [comment]
I am also getting this error message in the latest version of Tedit :( Totally unable to edit my map in any way.
