### ISSUE TITLE
Tedit wont open a world

### ISSUE THREAD

**Issue by pn256170** [TEdit/Terraria-Map-Editor#654]
The lod file says: 

 09:06: Starting TEdit 3.5.15047.30 
08-18-2015 09:06: OS: Microsoft Windows NT 5.1.2600 Service Pack 3 
08-18-2015 09:06: .Net >= 4.0 
08-18-2015 09:06: XNA 4.0 
08-18-2015 09:06: Terraria Data Path: D:\Program Files\Steam\steamapps\common\Terraria\Content 
08-18-2015 09:06: Creating Undo cache: D:\Documents and Settings\Taza Potter\Application Data\TEdit\undo_451364326 
08-18-2015 09:06: Error - This method does not accept null for this parameter.
Parameter name: data
   at Microsoft.Xna.Framework.Graphics.Texture2D.CopyData[T](Int32 level, Nullable`1 rect, T[] data, Int32 startIndex, Int32 elementCount, UInt32 options, Boolean isSetting)
   at TEditXna.View.WorldRenderXna.LoadTerrariaTextures(GraphicsDeviceEventArgs e) 
08-18-2015 09:06: Error - Arithmetic operation resulted in an overflow.
   at TEditXna.View.WorldRenderXna.LoadTerrariaTextures(GraphicsDeviceEventArgs e) 
08-18-2015 09:07: Removing undo cache: D:\Documents and Settings\Taza Potter\Application Data\TEdit\undo_451364326

**Comment by ahamling27** [comment]
TEdit 3.5 is only for Terraria version 1.2.4.1 and earlier. To open 1.3 worlds, please download a beta build from here: http://www.binaryconstruct.com/downloads/

**Comment by rarefushion** [comment]
i had the same problem and i crated it on 1.3 gonna delete TEdit and re install it see if that works
