### ISSUE TITLE
World Corrupted just by saving

### ISSUE THREAD

**Issue by tanpro260196** [TEdit/Terraria-Map-Editor#656]
My world is a large world and quite old. When I use the latest beta (20th August, 2015), I just open the world and click save, when I open it in Terraria, It said "Load Failed".
I didn't do anything, just open the world and click save. Then my world is corrupted.
After that, I open this world in tedit again, it still read my world properly, however, I can't open it in terraria.

**Here is the link for my world:** https://mega.nz/#!VBwyzLQS!0GJcIlriaB3ND4vr5pAvbvcFUsaHmo7WMAd3W73S-bw

*Just open and click save, nothing else.*
![screenshot 4](https://cloud.githubusercontent.com/assets/12226439/9404622/f3692b80-47a5-11e5-8a5c-2605739d6ae1.png)

*And it's corrupted!*
![screenshot 3](https://cloud.githubusercontent.com/assets/12226439/9404589/b4bf6dfe-47a5-11e5-8b33-71d396c149a6.png)

**Comment by ahamling27** [comment]
Have you tried opening it in the lastest beta build released today? TEdit3_BETA_v3.6.15233.1522 was released this morning(http://www.binaryconstruct.com/downloads/). Try loading it with that and saving then seeing if it'll open in Terraria.

Thanks!

**Comment by tanpro260196** [comment]
@ahamling27 I did, still the same, can't open in Terraria even I just open and click save.

**Comment by ahamling27** [comment]
were you able to find the .bak that you never opened in TEdit and open that back up in Terraria?

**Comment by tanpro260196** [comment]
I create mt own blackup everytime I use tedit. And everytime a new beta come out, I restore the backup and try again. Still, nothing changes.

**Comment by ahamling27** [comment]
Okay, whew, I was worried you completely lost your world. Not sure what would be making it corrupt though. Was there any new 1.3 items you recently added to your world, in Terraria?

**Comment by tanpro260196** [comment]
Yes, I build a new house using new blocks in 1.3. It took me 6 months to build that world, not gonna let it go easy. :)
And this have happened since the experimental release. But I waited until the offical BETA to report it.

**Comment by ahamling27** [comment]
I'm sure if you upload the world file here, some of the more knowledgeable folks can dig through your world and hopefully they can figure out what the hangup is.

You should be able to just drag and drop the world file into the text box and it'll upload it. Thanks!

**Comment by ahamling27** [comment]
Ha! Maybe I need to learn to read, I see you did that in the OP. Thanks!

**Comment by tanpro260196** [comment]
Yeah, maybe bacause my grammar kinda suck. Will edit the post for better reading experience. :)

**Comment by ahamling27** [comment]
Usually you can drop files in here, but it is larger than 10MB so it wouldn't work anyway.

**Comment by tanpro260196** [comment]
Yeah, I just tried, not working. :)
Thanks for your help anyway. :)

**Comment by ahamling27** [comment]
I have downloaded the world from the OP, opened it in the newest TEdit, saved it, and I can totally reproduce this. Also, I see some familiar structures in there. It looks like part of the beginning of my adventure map, A Link to Terraria. ;)

**Comment by tanpro260196** [comment]
Exactly, I just love those castle so I bring them to my world lol... :)

**Comment by ahamling27** [comment]
No worries! That's the power of TEdit. :D

**Comment by tanpro260196** [comment]
And does it corrupted when you saved it?

**Comment by tanpro260196** [comment]
Somebody please help??

**Comment by enigmaquip** [comment]
Doing a diff on a file pre save and post save I'm seeing some places where they don't match, looking into the save code now.... Seems to be in the sign handling portion

**Comment by tanpro260196** [comment]
@enigmaquip Thank you so much. Hope you can identify the problem soon. :)

**Comment by enigmaquip** [comment]
welp, I sorta did..... the problem lies at the end of the Chest code, not the beginning of the Sign code....... In 1.3 Dressers became 'Chests', there is a hard limit of 1000 chests allowed and your world has 1072 with dressers included and the save code is saving them all, which is where Terraria is crapping out. I'll have to look into the Terraria code to see why it's not causing issues when it saves the file itself

**Comment by tanpro260196** [comment]
@enigmaquip So if I reduce the number of chest in my world, will it fix the problem?

**Comment by enigmaquip** [comment]
Give it a try, the analyze tab will show you your count, bring it down to
1000 or less and let me know if it works then

**Comment by tanpro260196** [comment]
@enigmaquip Where is that analyze tab?

**Comment by tanpro260196** [comment]
Never mind, I think I found it.

**Comment by tanpro260196** [comment]
IT WORK!!!!!!!!!!!!!!

**Comment by tanpro260196** [comment]
Applied to another world, this time it has 1500 chests...... -_-
OMG, now I have to hunt down 500 chest...............................

**Comment by enigmaquip** [comment]
There is a plugin tool that removes empty chests (only chests and not dressers)

**Comment by tanpro260196** [comment]
Terraria seem to handle those extra chests pretty well, so there should be a way to apply it to TEdit, right?

**Comment by enigmaquip** [comment]
Terraria literally only saves the first 1000 chests in the array

**Comment by tanpro260196** [comment]
So all of those extra chests are just for show?

**Comment by BinaryConstruct** [comment]
This is a Terraria limitation.
