### ISSUE TITLE
Tree tops not rendering correctly on snow

### ISSUE THREAD

**Issue by ahamling27** [TEdit/Terraria-Map-Editor#657]
It doesn't happen on every one, as the frame is (22,242) on all of them. If you need any other info, just let me know and I can upload the world file or get you that info.
![2015-08-21_15-04-06](https://cloud.githubusercontent.com/assets/13699138/9417977/4bbfb6a8-4816-11e5-914f-7cf4f78166ce.png)

**Comment by enigmaquip** [comment]
The treetops that are rendering are showing what should be the 242 treetop frame..... are these manually placed sprites or naturally grown trees? I'm guessing the former

**Comment by enigmaquip** [comment]
Go ahead and upload your file and I'll play with it to find the cause

**Comment by ahamling27** [comment]
They're all manually placed trees. I'll get the world file uploaded here. Once sec.

**Comment by ahamling27** [comment]
http://www.curseforge.com/media/files/895/287/A_Link_To_Terraria_3.0b.zip

**Comment by ahamling27** [comment]
It's on the snowy mountain, it's the only snowy area on the map. :)
