### ISSUE TITLE
Mask Mode - Edit Matching placing over empty tiles

### ISSUE THREAD

**Issue by ahamling27** [TEdit/Terraria-Map-Editor#659]
Like the title says, when using Edit Matching for the Mask Mode, it doesn't strictly adhere to the mask, placing tiles in empty spaces too. Previously, this only placed the new tiles only on the mask and not filling in empty tiles.

Before: 
![2015-08-21_19-46-30](https://cloud.githubusercontent.com/assets/13699138/9421684/64d8c874-483d-11e5-8f99-f279da8fd500.png)

After, where masking is covering blank space:
![2015-08-21_19-44-49](https://cloud.githubusercontent.com/assets/13699138/9421686/70bb506c-483d-11e5-9e97-d873cfdfd313.png)

**Comment by SinisterStairs** [comment]
I think that's my fault -- thanks for catching it.

**Comment by SinisterStairs** [comment]
I don't think my changes for Issue #490 caused what you experienced; but it does have a defect that affects all inactive tiles.
