### ISSUE TITLE
Where's the sink?

### ISSUE THREAD

**Issue by TMiner99** [TEdit/Terraria-Map-Editor#660]
the sink doesn't appear in the sprites menu and don't show up if you have it in your world

**Comment by SBlogic** [comment]
When I built the 1.3 data, I ran into an issue making sinks work correctly.  The upper sub frames are 16x16 while the lower sub frames are 16x18.  I was having some problems getting TEdit to load and render the tiles properly, so I opted to leave them out for the short term.  After doing a bit of re-testing, it looks like I can probably fix this by just ignoring the bottom two pixels in the lower sub frames (the game appears to work this way anyhow).  I'll run some more tests on this, and if it works, I should have a patch for this shortly.
