### ISSUE TITLE
Chests and Signs

### ISSUE THREAD

**Issue by enigmaquip** [TEdit/Terraria-Map-Editor#665]
Terraria will fault out on map load if there are more than 1000 chests or 1000 signs saved.
Should we add some popup errors on Save attempts that break this? Maybe in the validate function that runs before map save? Or just truncate and only save the first 1000 in the list?
This was seen to be the cause in #656 and with Dressers becoming chests in 1.3 I can see this maybe being the cause for some of the map errors I see reported around.

**Comment by SinisterStairs** [comment]
IMO it's better to warn the user, rather than automatically truncating...

- But if we truncate, we should remove empty chests first
- Ideally we could warn the user when they place/paste a chest; but it'd be simpler to warn on save.
- Perhaps the same check/warning should be used when we load the world too

Just curious, how does Terraria behave if you world has 1000 chests/signs and you try placing the 1001st?

**Comment by tanpro260196** [comment]
@SinisterStairs When I moved to 1.3, my world have 1072 chests, Terraria still load normally, it just won't allow me to put down any more chests. And it currupted after saved in TEdit.
I have another world with 999 chests, I still alble to place 2 more chests with no problem. Not sure why.

**Comment by enigmaquip** [comment]
So I finally spent the time to fully test this. When 1.3.0.1 happened all dressers became storage, When Terraria loads a world file from pre 1.3.0.1 (version < 115) is runs FixDresserChests at the end of the LoadChests function, this converts dressers to chests, up to the 1000 chest limit. All dressers after that do not function as storage. You can pick up a non storage dresser, but will not be able to set it back down since you would be above the 1000 chest limit. If you pick up a storage item, you will be able to set it back down because the dressers are never checked again. The world will be saved in the current version and the FixDresserChests function will not run again, these non storage dressers will remain as non storage until picked up and placed again.

TEdit sees all dressers and chests as storage and makes them so and does the 'conversion' every time it loads the map, it currently doesn't have a check for a chest cap over 1000. 

So we should certainly throw an message to the user that they are over the 1000 limit and give them the opportunity to fix it.
