### ISSUE TITLE
Schematic Loading Error

### ISSUE THREAD

**Issue by AspiringScientist** [TEdit/Terraria-Map-Editor#670]
Whenever I try to open up a schematic it either doesn't do anything, or it gives me an error message saying "Index is outside bounds of array". At first I thought it had to do with using the 3.6 beta versions, but I tried using the 3.5 versions and it did the same thing. Help?

**Comment by davin79** [comment]
I'm getting the same thing or something very similar. I've tried uninstalling it, choosing different beta versions, using the latest stable release... and every time I get the same error for any world I try to view. 

This is a ss of the error; https://www.dropbox.com/s/6gxq6rcnqqxadxu/tediterror.png?dl=0

When I click Yes the background goes dark and nothing ever loads. If I click No, nothing happens.

**Comment by enigmaquip** [comment]
Please try the latest version 3.6.15246.1434 and let me know if that corrected the loading issues

**Comment by enigmaquip** [comment]
@davin79 that stable version is 3.5 which is not compatible with worlds made from 1.3 of Terraria, you need one of the 3.6 Beta version to load a world
