### ISSUE TITLE
Won't load textures

### ISSUE THREAD

**Issue by lynkfox** [TEdit/Terraria-Map-Editor#672]
World opens, the render says as complete, the mini map shows a picture of the world, but the main display area remains white. can mouse across and get info box's at bottom to show information.

Using steam.
reinstalled 4.5 .net to be certain.

when trying to extend the window, issues arise in the main display area (ghost images)
![tedit issue](https://cloud.githubusercontent.com/assets/14082243/9618792/91369296-50d7-11e5-8edd-525eb9fa20f1.png)

full log available if needed, but mostly looks like this

09-01-2015 18:25: Starting TEdit 3.6.150812.0114 
09-01-2015 18:25: OS: Microsoft Windows NT 6.1.7601 Service Pack 1 
09-01-2015 18:25: Terraria Data Path: c:/program files (x86)/steam\steamapps\common\terraria\Content 
09-01-2015 18:25: Creating Undo cache: C:\Users\Phuriel\AppData\Roaming\TEdit\undo_690809655 
09-01-2015 18:25: Failed to load texture: Images\NPC_17 
09-01-2015 18:25: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
09-01-2015 18:25: Failed to load texture: Images\NPC_18 
09-01-2015 18:25: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
09-01-2015 18:25: Failed to load texture: Images\NPC_19 
09-01-2015 18:25: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
09-01-2015 18:25: Failed to load texture: Images\NPC_20 
09-01-2015 18:25: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
09-01-2015 18:25: Failed to load texture: Images\NPC_22 
09-01-2015 18:25: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
09-01-2015 18:25: Failed to load texture: Images\NPC_37 
09-01-2015 18:25: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
09-01-2015 18:25: Failed to load texture: Images\NPC_38 

could completely believe this is something wrong with my computer, as I did just build it a few months ago.

**Comment by lynkfox** [comment]
also a lot of errors like this:

09-01-2015 18:25: Error - HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown
   at SharpDX.Result.CheckError()
   at SharpDX.Direct3D11.Device.CreateTexture2D(Texture2DDescription& descRef, DataBox[] initialDataRef, Texture2D texture2DOut)
   at Microsoft.Xna.Framework.Graphics.Texture2D.CreateTexture()
   at Microsoft.Xna.Framework.Graphics.Texture.GetTexture()
   at TEditXna.View.WorldRenderXna.LoadTerrariaTextures(GraphicsDeviceEventArgs e) in C:\a\1af8616d\TEdit\Terraria-Map-Editor\TEditXna\View\WorldRenderXna.xaml.cs:line 237

**Comment by ahamling27** [comment]
Same, but I just get a grey screen. I can't seem to get any previous versions to work either. This is weird...
![2015-09-02_12-32-31](https://cloud.githubusercontent.com/assets/13699138/9638909/cb9648fe-516e-11e5-8ea5-f6a8f7673baa.png)

The log doesn't say anything for me though:
09-02-2015 12:34: Starting TEdit 3.6.150812.0114 
09-02-2015 12:34: OS: Microsoft Windows NT 6.2.9200.0 
09-02-2015 12:34: Terraria Data Path: c:/program files (x86)/steam\steamapps\common\terraria\Content 
09-02-2015 12:34: Creating Undo cache: C:\Users\Andrew\AppData\Roaming\TEdit\undo_456381808 
09-02-2015 12:34: Removing undo cache: C:\Users\Andrew\AppData\Roaming\TEdit\undo_456381808

**Comment by ahamling27** [comment]
Nothing I do can get it to render the world. I mean, It says it renders, the minimap shows it, and if I mouse over the world it shows that it's there, I just get no actual visual of the world. And the fact that this happens with every version, for the past like 7 or 8 updates, is very odd. It has to be something outside of the program, like a new .NET version or something screwing with it.

**Comment by ahamling27** [comment]
And just like that it seems to work again? I'm on Nvidia drivers 353.62, which is two releases back. Not sure if that's what fixed it, as it didn't work right after rolling back the second time.

I don't know. I just tried it again for kicks and it rendered the world fine.

**Comment by SinisterStairs** [comment]
As far as testing if this is driver related, I haven't experienced this problem with the latest Nvidia WHQL drivers that were released in August (Windows 7 x64).

**Comment by BinaryConstruct** [comment]
These issues are due to the change to Monogame from XNA. Since XNA is a discontinued product and not 64 bit compatible it needed to be replaced. 

Monogame uses SharpDX for the core rendering, however it adds some new dependencies including having a DX11 compatible graphics card and functional driver, whereas XNA would work even with out of date hardware. 

Unfortunately, it also introduced some graphics related bugs, but there are new versions of SharpDX and Monogame coming out soon that should resolve some of these.

**Comment by lynkfox** [comment]
So I take it then that this isn't something that can be fixed until new versions of SharpDX and Monogame are released? (as I am definitely using DX11 and a compatible gfx card.)

No worries if so, I'll just have to wait :)

**Comment by BinaryConstruct** [comment]
Basically, yes.

**Comment by xxpx2** [comment]
I was able to overcome this by going to my nvida control panel and forcing Tedit to use my integrated graphics card. Just in-case this helps anyone with an on-board video card.

forced it from a gtx 960m to intel hd graphics 4600, windows 10.

**Comment by eXXOtaku** [comment]
Had this problem too. And maybe, I got a solution.

I use an old version of win7 home Prem with SP1.
It`s weird, after an Windows update( yeah, I never update, 'cause my SSD doesn't have much space on it) for my DirectX 11 (since applications use their ownen renderer, based on DX11) this bug is gone. Yeah, the programm needs my path of the game, and violá ! It works. Hope someone helped this in future :3

greetings eXXO'

**Comment by BinaryConstruct** [comment]
Please watch #751 for progress on this known issue.
