### ISSUE TITLE
Can't Check Version/Won't Load Worlds

### ISSUE THREAD

**Issue by Stephenator0316** [TEdit/Terraria-Map-Editor#675]
Just installed tEdit via the installer, and when I open it, it immediately says "Unable to check version." Then when I try to open a world, it shows this: 
![screenshot 5](https://cloud.githubusercontent.com/assets/9485353/9648756/fde301b2-51b9-11e5-849f-4c8d90766eb4.png)

**Comment by enigmaquip** [comment]
Ver 3.5 is compatible up to 1.2.4, you need a 3.6 beta for 1.3

**Comment by Stephenator0316** [comment]
1Well, I hit the download latest version and this is what it gave me.... Thanks for the help! :D

**Comment by Stephenator0316** [comment]
Doesn't appear to work well with W10... keeps saying its a virus then takes a couple of minutes to stop saying not responding, and then just all around goes very slowly... :/

**Comment by Stephenator0316** [comment]
Ok, new update fixed everything! Thanks! o3o
