### ISSUE TITLE
Painting colors 1-12 don't work

### ISSUE THREAD

**Issue by wog24435** [TEdit/Terraria-Map-Editor#677]
I've tried painting some blocks and the colors with the numbers 1 to 12 don't work. They appear painted in TEdit, but not in game. Their deep counterparts work fine. This is only a issue with blocks; walls get painted correctly with all the paint colors.

I am using TEdit3_BETA_v3.6.15247.0301

**Comment by SBlogic** [comment]
What type of block did you paint?  The normal paints inherit saturation levels of the painted block while deep paints override the saturation.  Normal paints tend to have little noticeable effect on certain blocks, like stone and gray brick especially.  You'd probably get the same results with the corresponding paints used in game.

**Comment by wog24435** [comment]
I tried it on dirt. You were right, it got painted. Please close this issue.
