### ISSUE TITLE
Worlds Not Loading

### ISSUE THREAD

**Issue by agdistis13** [TEdit/Terraria-Map-Editor#678]
I downloaded the newest update. However, upon opening it, it tells me that I'm not using the latest version and when I try to load any world, it says that it cannot open those files.

Here's a png of it:
https://41.media.tumblr.com/d47371e502473e46443bb085cce2b7c5/tumblr_nua4ieGGTx1qzipwpo1_1280.png

Would it be possible to receive an installer with the latest update?

**Comment by Lakaini** [comment]
I have same issue, except that it does not check latest version.

**Comment by BinaryConstruct** [comment]
Please try the latest beta versions.
