### ISSUE TITLE
unknow world file error :c

### ISSUE THREAD

**Issue by keiuzami** [TEdit/Terraria-Map-Editor#680]
anybody please can help-me with this error? she appear if o load all my maps :/ here image link http://prntscr.com/8f1oo9

**Comment by enigmaquip** [comment]
Looks like you're trying to load a 1.3 file in the older TEdit 3.5, that only supports map files up to 1.2.4.... you need one of the newer 3.6 betas to open the newer map files

**Comment by keiuzami** [comment]
oh thanks brah c:
