### ISSUE TITLE
Doesn't work when runned on VMWare Fusion

### ISSUE THREAD

**Issue by Dogstalotl** [TEdit/Terraria-Map-Editor#681]
I tried running the program on VMWare and it didn't load, i have 2 GB and 2 cores allocated, help!

Also will it be coming to Mac?

**Comment by enigmaquip** [comment]
with it being built on monogame it might be possible to install mono and run the executable through there. I'm not entirely sure on that, just a guess, but worth a try

**Comment by BinaryConstruct** [comment]
I don't think mono supports WPF. http://www.mono-project.com/docs/gui/wpf/

**Comment by TheMaxShaft** [comment]
Can you possibly port it to mac

**Comment by TheMaxShaft** [comment]
Wineskin does not support TEdit: http://wineskin.urgesoftware.com/tiki-index.php

**Comment by BinaryConstruct** [comment]
I might look into cross platform implementations once .net core has a few more releases. https://dotnet.github.io/
