### ISSUE TITLE
Lunar ore

### ISSUE THREAD

**Issue by Keaft** [TEdit/Terraria-Map-Editor#683]
Lunar ore causes tedit to fail to save. Lunar brick wall does not.

Map being edited was pre chlorophyte and therefore pre lunar ore, but chlorophyte doesn't cause issue. 

Without saves fine:
![without lunar ore](https://cloud.githubusercontent.com/assets/68153/9890969/582b9af2-5bc0-11e5-9aa3-512eca3dc244.PNG)

With causes save to hang:
![with lunar ore](https://cloud.githubusercontent.com/assets/68153/9890991/6ac7451c-5bc0-11e5-9a20-c3433fd732fd.PNG)

**Comment by enigmaquip** [comment]
So this is a pre 1.3 saved world? I'm having no issues saving with lunar ore placed on my map...

**Comment by Keaft** [comment]
Yes it is. I mentioned that it was pre-chlorophyte, but that is apparently untrue as there is some naturally generated. So pre 1.3 world. Interesting.

**Comment by enigmaquip** [comment]
Hmmmm I can't seem to replicate it, but I don't have an old world.....

**Comment by Keaft** [comment]
If you would like the world simply for the experiment or some sort of save to newest version thing I would be more than happy to fish it over.

Otherwise I'll move everything to a newer world and call it good :D. Thanks!

**Comment by enigmaquip** [comment]
if you can upload this world that is having issues it would help me track down the bug, that would be great

**Comment by Keaft** [comment]
Here's the world:
http://filebin.ca/2FnmOwmNZW3n

**Comment by enigmaquip** [comment]
Well, that error certainly pops up for me now :-)
Working on it

**Comment by Keaft** [comment]
Interesting, it appears that living mahogany leaves also cause an issue. The save bar get stuck sooner.

**Comment by enigmaquip** [comment]
I'm guessing you put them further left on the map, the prograss bar updates
as it encodes the tile data going across the map

**Comment by Keaft** [comment]
Yup I did. I expected that might be the case with the progress bar.

**Comment by enigmaquip** [comment]
It was actually the case of using any tile > 314 (ie from 1.3), this should be corrected when my changes get merged and a new version built

**Comment by enigmaquip** [comment]
@Keaft Give it a try with the latest Beta and let me know

**Comment by Keaft** [comment]
Sweet! Everything worked out! How do you like that project by the way? Just so you know this whole thing is only conceivable because of the work that you've done with Tedit! Thanks a bunch!!!

**Comment by enigmaquip** [comment]
Love that big tree, looks nice....
Feel free to close this issue now that it's dealt with
