### ISSUE TITLE
Slopes for certain blocks aren't saved upon loading

### ISSUE THREAD

**Issue by Baconfry** [TEdit/Terraria-Map-Editor#686]
Hammered Living Rich Mahogany blocks revert to full-brick form when the world is loaded. Not sure if this is the only block affected.

**Comment by enigmaquip** [comment]
Were they hammered in game or was the slope set in TEdit?

**Comment by Baconfry** [comment]
The slopes were reset both when hammered in-game and set in TEdit.

**Comment by enigmaquip** [comment]
Living Mahogany, Living Mahogany Leaves and Crystal Block were missing a flag that cause brickstyle not to be loaded from the save file, this will be corrected in my next code push
