### ISSUE TITLE
Main Viewer not rendering properly

### ISSUE THREAD

**Issue by xxpx2** [TEdit/Terraria-Map-Editor#689]
![bug report](https://cloud.githubusercontent.com/assets/14962163/10267151/03cad9dc-6ad4-11e5-821a-d8d531b4101b.png)

The world loads just fine but the main window doesn't render.

 + tried compatibility modes
 + tried on on-board video card and nvidia gtx 960m
 + tried multiple beta versions all had same issue

+ last stable version works but wont load 1.3.0.8 maps

**Comment by enigmaquip** [comment]
This is the same error as #672
