### ISSUE TITLE
TEdit3_BETA_v3.6.15282.0242 causing unknown error preventing world load after edit

### ISSUE THREAD

**Issue by Xanthor** [TEdit/Terraria-Map-Editor#691]
I been using Tedit for a month now, and update it by deleting entire files and pasting new and haven't had any issues till updating to TEdit3_BETA_v3.6.15282.0242. When I go to make changes to the world map, I always save to another folder then just paste the new map while the server is off and client is not loaded back into the worldsave folder and normally if there is an error, I am told what the error is on the tshock console which is version 4.3.9.0 or in the crash file but am not getting any error report other then the console telling me the the server has failed to load. If I revert back to an earlier save I have no issues, its just when I try to edit the world save after the update. For now Im going to revert to an earlier version of tedit. By the way, reason Im using tedit today other then designing new homes is one of my ops accidentally used a new item that when it exploded seriously messed up many of the surrounding houses so to make a fast fix, went into a backup and copied the housing using the copy paste feature, then pasted it into the worldmap then saved. Ive used this method before after a griefer messed up the land using some program and put lava into peoples homes. Much easier to paste huge sections then to sit in world block by block.

**Comment by enigmaquip** [comment]
do you remember the last Beta you used that didn't cause a problem.... the latest update was only rendering stuff so it wouldn't have changed how the map was saved

Can you post your world file somewhere?

**Comment by Xanthor** [comment]
Sorry took so long replying. For some reason, its happening with the earlier versions too and have a feeling it is with the copy pasting I'm doing. I only been doing this for little over a month. I tried uploading the file here but wouldn't let me. I'm going to see about setting up a server to put it there ten post link.

**Comment by enigmaquip** [comment]
something like dropbox or google drive will work fine

**Comment by enigmaquip** [comment]
One issue I've found in the past is to check your Chest count, go to the World Analysis tab and scroll down to the chest section and see if you have greater than 1000 chests

**Comment by Xanthor** [comment]
The chests seem to be the issue. Oh, I tried the newest update yesterday
and it crashes when you try loading it. I re-downloaded it in case a file
was bad, but still wont load. Seems chests caused an issue with a highly
downloaded map called builder, and removing them would of been counter to
why the map was designed. The work around for that was easy, the designer
made a huge world map, no quests, just 11,000 bytes of wood and a set of
shops. I used Tedit to copy just the shops and saved it as a single item,
then made a fresh small map on Tedit and pasted the shops in then filled
the void with dirt blocks instead. Saved it, and it loaded with no errors
despite going over 1000 chests. Original map had no issues with vanilla,
only Tshock. Now it runs fine. Great program by the way.

**Comment by enigmaquip** [comment]
Yea i messed up the latest build, good before that

**Comment by Xanthor** [comment]
Have one last question. You were right when it came to the chests being the problem with loading eddited worlds. Is there a future fix planned or a workaround? I'm running 8 servers and zeroing out the chests and adding them later worked great but one map is a set of shops to help in designing different types of homes so removing them defeats the purpose of the shop server. One last thing, can you send me your paypal info so I can send a donation Friday? I want to make sure you get it. There are too many fake links trying to get money for your work and for the life of me, have no clue how I found this message location. Only way I been able to respond and find it again is looking in my email.

**Comment by enigmaquip** [comment]
The latest build will notify you when you try to save if you've gone over 1000 chest/dressers, but doesn't do anything to fix it for you. It's a weird situation to try to deal with, because the cause is a very tight window. I've discussed it in other issues, but the upgrade from 1.2.4 to 1.3.0.1 is really the root cause as dressers because storage. During the first loading of a map that was from 1.2.4 Terraria will convert dressers to storage, but only up to the 1000 limit, so some dressers don't get converted, and this only happens once. On all future loads it will just ignore these non-storage dressers, whereas TEdit will always convert them to be in line with the most recent rules of the game (ie all chests and dressers are storage) and so it will break if you go over 1000.

**Comment by Xanthor** [comment]
I just got back into Terraria, and brought 6 others with me from my old Tshock server. We decided to start a new map, with new version, and planned to use Tedit to pull our buildings off the old map, and place them in the new, which is when it hit me to come back here and ask if that chest issue was ever fixed, and to also make sure nothing else has come up I should be careful of, since I haven't played the game or server since 2015. I was so glad to see this is still made, but curious to know if I'm talking to the same person or if someone else took over as what I am seeing, is different from 2015. Your map editor was such a godsend back in the days, and this past week been going nuts looking to see if the old mod application that worked with it still exists. The mod allowed one to use Tedit while in game, to mark land plots around buildings, and save them to file, to import them lator on. Similar to Minecraft map editor. I see your doing Patreon now, so going to sign up after writing this. Again, great to see your still here!

**Comment by BinaryConstruct** [comment]
The chest/sign issue is back in 4.5.1 with the addition of "old" file support. This should be resolved in the next update ETA 9/20/2021

**Comment by Xanthor** [comment]
Thank you for replying so fast. I'll also let my friends on Tshock know as
well. This definitely explains the issues I been having, but at least I can
load up the older version that I backed up, manually remove the extra
chests, then export the buildings to be used in new map. I would have
removed all chests using that great feature of Tedit, but was warned if I
hadn't played since 2015, I'd risk removing chest specific to quests.
Thanks again and take care.
