### ISSUE TITLE
TEdit v0.0.0.0 problem

### ISSUE THREAD

**Issue by Doomsguardian** [TEdit/Terraria-Map-Editor#692]
When I open the latest version, it will only show v0.0.0.0 and ask me to update it. Here is it.
![default](https://cloud.githubusercontent.com/assets/5691913/10430151/2f1dc7e0-7130-11e5-861b-0ce5a677d510.PNG)

**Comment by enigmaquip** [comment]
All the Beta's currently will tell you they are out of date. You can ignore that, say no and turn off check for updates from the file menu

**Comment by Doomsguardian** [comment]
Thank you very much, it really helps.
