### ISSUE TITLE
Game Code Injection

### ISSUE THREAD

**Issue by TheMaxShaft** [TEdit/Terraria-Map-Editor#694]
Could there be a feature where you could inject a command into Terraria with (ex. F11) and it pauses the game and opens TEdit for live simulations?

**Comment by TheMaxShaft** [comment]
I thought if i created it on is:open label:"Planned Feature"  then it would be a "planned feature" my bad

**Comment by enigmaquip** [comment]
why not just have it open in the background and alt tab into it?
you can't live edit a map in TEdit while it's open in Terraria, so what's the need?
