### ISSUE TITLE
TEdit saves too many chests to world?

### ISSUE THREAD

**Issue by tysonstrange** [TEdit/Terraria-Map-Editor#698]
Here is a copy of my Original world file, which loads in TShock and Vanilla. It has 997 Chests...
http://vps.tls.id.au/orig.wld

Here is the world, literally no changes made, just opened and saved in a version of TEdit. Suddenly its showing 1045 chests and will no longer load...
http://vps.tls.id.au/tedit.wld

If you open the world again in Tedit and just Select and delete 45~ chests and save it again, the world will load again, but why is this happening?

Related Issue logged with TSAPI (TShock) https://github.com/NyxStudios/TerrariaAPI-Server/issues/40

**Comment by tysonstrange** [comment]
Also was informed off this code that checks chests which is commented out, which might be causing this issue.

https://github.com/TEdit/Terraria-Map-Editor/blob/bf61469b669a14c237a869f143916df04ef57f38/TEditXna/Terraria/World.FileV2.cs#L573-L574

**Comment by enigmaquip** [comment]
See #665 
TEdit makes all chests and dressers into chests, so dressers that weren't originally chests may become chests. This is due to the changes in Terraria that made dressers also chests in 1.3.0.1...
Terraria added a function in when loading the world file called FixDresserChests which does this conversion but it only runs if the world file is less than version 115. Is why there is some mismatch between TEdit and Terraria

**Comment by tysonstrange** [comment]
Right, but TEdit is breaking the world file. Are you able to stop it from doing this?

**Comment by enigmaquip** [comment]
It will now notify the user they have too many chests and that will break the save file.... it will be up to the user to get under 1000 chests

**Comment by tysonstrange** [comment]
Right.... but the containers/chests worked already prior to the world being loaded in tedit and tedit si still breaking the world by saving them a different way...

**Comment by enigmaquip** [comment]
having too many chests is breaking the world

**Comment by tysonstrange** [comment]
Ok, but why is it that Loading/saving the world with the actual terrariaserve.exe doesn't break the world? some are chests, some dressers. the dressers are being changed into chests when saved by tedit and push the count over 1k

**Comment by enigmaquip** [comment]
for exactly the reason I said above.... dressers are chest now, terraria converted them when the save file was upgraded from 1.2.4 to 1.3.0.1, but only that one time, and only up to the 1000 max, so some dressers are not chests in game. TEdit does this conversion every time it saves a map.

**Comment by tysonstrange** [comment]
yeah... why does it do it every time though? as it's breaking the world files...

**Comment by enigmaquip** [comment]
because, the current rule for a current map is ALL dressers and chests are storage, and you are only allowed 1000 storage items. If you in your current world, tried to pick up one of the non storage dressers and put it back down when you are at 1000 storage items, it wouldn't let you, so you would lose that dresser

**Comment by tysonstrange** [comment]
Right, in the example world i provided, the dressers its re saving ARE currently containers and ARE working fine, its only when opened and saved in TEdit that it breaks.

**Comment by enigmaquip** [comment]
you're at 997 storage items..... go into your world and find 4 of the 50 dressers than you can't open as storage, pick them up and put them back down, tell me what happens on the 4th

**Comment by tysonstrange** [comment]
Alright.

Side request: Have one of the chest management plugins to Remove all Empty chests, quick easy way to reduce the chest count a little bit...

**Comment by enigmaquip** [comment]
There is actually a plugin that does that

**Comment by enigmaquip** [comment]
Here's the world I made quick in TEdit 3.5 the other day to test exactly what happens in Terraria if you want to take a look quick, easier to see an example of what I'm talking about. It's saved as a 1.2.4 world so it will convert dressers the first time it's opened. it has 990 chests and 15-20 dressers, you'll see after the first 10 they don't work as chests anymore

https://drive.google.com/file/d/0B5p2gC_8_WDGTWk0bEdRWlhMWkk/view

**Comment by tysonstrange** [comment]
Right.. but the world i have was made and saved in 1.3.0.3...

**Comment by enigmaquip** [comment]
you either went over 1000 pre 1.3.0.1 or used a very early tedit 3.6 beta that didn't have dresser as storage yet

**Comment by enigmaquip** [comment]
you either put dressers in pre 1.3.0.1 when it didn't count making it over 1000 chests + dressers or used a very early tedit 3.6 beta that didn't have dresser as storage yet

**Comment by tysonstrange** [comment]
mmm could be i was on an eearlier version... but it was definately a new world file.


Im using the latest tedit from your webpage now though and that that issue

will try again with this latest build

**Comment by BinaryConstruct** [comment]
This is a terraria limitation. Some mods allow you to have more.
