### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by gosek900** [TEdit/Terraria-Map-Editor#703]
10-18-2015 10:51: Starting TEdit 3.6.150812.0114 
10-18-2015 10:51: OS: Microsoft Windows NT 6.1.7601 Service Pack 1 
10-18-2015 10:51: Failed to verify Terraria Paths. TEdit may not run properly. 
10-18-2015 10:51: Error - Tag początkowy „Tiles” w wierszu 105 na pozycji 4 nie pasuje do tagu końcowego „Frames”. wiersz 4122, pozycja 9.
   w System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)
   w System.Xml.XmlTextReaderImpl.ThrowTagMismatch(NodeData startTag)
   w System.Xml.XmlTextReaderImpl.ParseEndElement()
   w System.Xml.XmlTextReaderImpl.ParseElementContent()
   w System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r)
   w System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r, LoadOptions o)
   w System.Xml.Linq.XElement.ReadElementFrom(XmlReader r, LoadOptions o)
   w System.Xml.Linq.XElement.Load(XmlReader reader, LoadOptions options)
   w System.Xml.Linq.XElement.Load(String uri, LoadOptions options)
   w TEditXNA.Terraria.World.LoadObjectDbXml(String file) w C:\a\1\s\TEditXna\Terraria\World.Settings.cs:wiersz 132
   w TEditXNA.Terraria.World..cctor() w C:\a\1\s\TEditXna\Terraria\World.Settings.cs:wiersz 49 
10-18-2015 10:51: Error - Inicjator typów zgłosił wyjątek dla typu 'TEditXNA.Terraria.World'.
   w TEditXna.DependencyChecker.CheckPaths() w C:\a\1\s\TEditXna\DependencyChecker.cs:wiersz 20
   w TEditXna.App.OnStartup(StartupEventArgs e) w C:\a\1\s\TEditXna\App.xaml.cs:wiersz 52 
10-18-2015 10:51: Unable to locate Terraria. No texture data will be available. 
10-18-2015 10:51: Error - Tag początkowy „Tiles” w wierszu 105 na pozycji 4 nie pasuje do tagu końcowego „Frames”. wiersz 4122, pozycja 9.
   w System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)
   w System.Xml.XmlTextReaderImpl.ThrowTagMismatch(NodeData startTag)
   w System.Xml.XmlTextReaderImpl.ParseEndElement()
   w System.Xml.XmlTextReaderImpl.ParseElementContent()
   w System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r)
   w System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r, LoadOptions o)
   w System.Xml.Linq.XElement.ReadElementFrom(XmlReader r, LoadOptions o)
   w System.Xml.Linq.XElement.Load(XmlReader reader, LoadOptions options)
   w System.Xml.Linq.XElement.Load(String uri, LoadOptions options)
   w TEditXNA.Terraria.World.LoadObjectDbXml(String file) w C:\a\1\s\TEditXna\Terraria\World.Settings.cs:wiersz 132
   w TEditXNA.Terraria.World..cctor() w C:\a\1\s\TEditXna\Terraria\World.Settings.cs:wiersz 49 
10-18-2015 10:51: Error - Inicjator typów zgłosił wyjątek dla typu 'TEditXNA.Terraria.World'.
   w TEditXNA.Terraria.World.get_TileBricks() 
10-18-2015 10:51: Error - Obiekt docelowy wywołania zgłosił wyjątek.
   w System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   w System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   w System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   w System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   w System.Windows.Markup.StaticExtension.GetFieldOrPropertyValue(Type type, String name, Object& value)
   w System.Windows.Markup.StaticExtension.ProvideValue(IServiceProvider serviceProvider)
   w MS.Internal.Xaml.Runtime.ClrObjectRuntime.CallProvideValue(MarkupExtension me, IServiceProvider serviceProvider) 
10-18-2015 10:51: Error - Operacja podawania wartości elementu „System.Windows.Markup.StaticExtension” wywołała wyjątek.
   w System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   w System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   w System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   w System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   w System.Windows.Application.LoadComponent(Uri resourceLocator, Boolean bSkipJournaledProperties)
   w System.Windows.Application.DoStartup()
   w System.Windows.Application.<.ctor>b__1(Object unused)
   w System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   w MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   w System.Windows.Threading.DispatcherOperation.InvokeImpl()
   w System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   w System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   w System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   w System.Windows.Threading.DispatcherOperation.Invoke()
   w System.Windows.Threading.Dispatcher.ProcessQueue()
   w System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   w MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   w MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   w System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   w MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   w System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   w MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   w MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   w System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   w System.Windows.Application.RunInternal(Window window)
   w System.Windows.Application.Run()
   w TEditXna.App.Main() w C:\a\1\s\TEditXna\obj\Release\App.g.cs:wiersz 0

**Comment by enigmaquip** [comment]
Same as #696 
This was a bad build, go back one version until the next build appears

**Comment by enigmaquip** [comment]
New build available, this has been fixed
