### ISSUE TITLE
Map not loading....

### ISSUE THREAD

**Issue by DragosStan** [TEdit/Terraria-Map-Editor#706]
I downloadedTEdit like 2 months ago and it worked....i uninstalled it an dnow when i install it and try to open my map it say Render Complete.....but map dont show up......a black image shows up....

What i can do?

**Comment by enigmaquip** [comment]
Check out Issue #672 
I believe it's the same issue, doesn't look like there's a resolution though

**Comment by BinaryConstruct** [comment]
Please watch #751 for progress on this known issue.
