### ISSUE TITLE
still error

### ISSUE THREAD

**Issue by gamer112oj** [TEdit/Terraria-Map-Editor#707]
10-20-2015 19:07: Starting TEdit 3.6.150812.0114 
10-20-2015 19:07: OS: Microsoft Windows NT 6.2.9200.0 
10-20-2015 19:07: Failed to verify Terraria Paths. TEdit may not run properly. 
10-20-2015 19:07: Error - De begincode Tiles op regel 105, positie 4, komt niet overeen met de eindcode Frames. Regel 4122, positie 9.
   bij System.Xml.XmlTextReaderImpl.Throw(Exception e)
   bij System.Xml.XmlTextReaderImpl.ThrowTagMismatch(NodeData startTag)
   bij System.Xml.XmlTextReaderImpl.ParseEndElement()
   bij System.Xml.XmlTextReaderImpl.ParseElementContent()
   bij System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r)
   bij System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r, LoadOptions o)
   bij System.Xml.Linq.XElement.ReadElementFrom(XmlReader r, LoadOptions o)
   bij System.Xml.Linq.XElement.Load(XmlReader reader, LoadOptions options)
   bij System.Xml.Linq.XElement.Load(String uri, LoadOptions options)
   bij TEditXNA.Terraria.World.LoadObjectDbXml(String file) in C:\a\1\s\TEditXna\Terraria\World.Settings.cs:regel 129
   bij TEditXNA.Terraria.World..cctor() in C:\a\1\s\TEditXna\Terraria\World.Settings.cs:regel 49 
10-20-2015 19:07: Error - De type-initialisatiefunctie voor TEditXNA.Terraria.World heeft een uitzondering veroorzaakt.
   bij TEditXna.DependencyChecker.CheckPaths() in C:\a\1\s\TEditXna\DependencyChecker.cs:regel 20
   bij TEditXna.App.OnStartup(StartupEventArgs e) in C:\a\1\s\TEditXna\App.xaml.cs:regel 52 
10-20-2015 19:07: Unable to locate Terraria. No texture data will be available. 
10-20-2015 19:07: Error - De begincode Tiles op regel 105, positie 4, komt niet overeen met de eindcode Frames. Regel 4122, positie 9.
   bij System.Xml.XmlTextReaderImpl.Throw(Exception e)
   bij System.Xml.XmlTextReaderImpl.ThrowTagMismatch(NodeData startTag)
   bij System.Xml.XmlTextReaderImpl.ParseEndElement()
   bij System.Xml.XmlTextReaderImpl.ParseElementContent()
   bij System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r)
   bij System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r, LoadOptions o)
   bij System.Xml.Linq.XElement.ReadElementFrom(XmlReader r, LoadOptions o)
   bij System.Xml.Linq.XElement.Load(XmlReader reader, LoadOptions options)
   bij System.Xml.Linq.XElement.Load(String uri, LoadOptions options)
   bij TEditXNA.Terraria.World.LoadObjectDbXml(String file) in C:\a\1\s\TEditXna\Terraria\World.Settings.cs:regel 129
   bij TEditXNA.Terraria.World..cctor() in C:\a\1\s\TEditXna\Terraria\World.Settings.cs:regel 49 
10-20-2015 19:07: Error - De type-initialisatiefunctie voor TEditXNA.Terraria.World heeft een uitzondering veroorzaakt.
   bij TEditXNA.Terraria.World.get_TileBricks() 
10-20-2015 19:07: Error - Het doel van een aanroep heeft een uitzondering veroorzaakt.
   bij System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   bij System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   bij System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   bij System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   bij System.Windows.Markup.StaticExtension.GetFieldOrPropertyValue(Type type, String name, Object& value)
   bij System.Windows.Markup.StaticExtension.ProvideValue(IServiceProvider serviceProvider)
   bij MS.Internal.Xaml.Runtime.ClrObjectRuntime.CallProvideValue(MarkupExtension me, IServiceProvider serviceProvider) 
10-20-2015 19:07: Error - De opgegeven waarde in System.Windows.Markup.StaticExtension heeft een uitzondering veroorzaakt.
   bij System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   bij System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   bij System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   bij System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   bij System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   bij System.Windows.Application.DoStartup()
   bij System.Windows.Application.<_ctor>b__0(Object unused)
   bij System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   bij System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   bij System.Windows.Threading.DispatcherOperation.InvokeImpl()
   bij System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bij System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bij System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   bij System.Windows.Threading.DispatcherOperation.Invoke()
   bij System.Windows.Threading.Dispatcher.ProcessQueue()
   bij System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   bij MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   bij MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   bij System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   bij System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   bij System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   bij MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   bij MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   bij System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   bij System.Windows.Application.RunDispatcher(Object ignore)
   bij System.Windows.Application.RunInternal(Window window)
   bij TEditXna.App.Main() in C:\a\1\s\TEditXna\obj\Release\App.g.cs:regel 0

**Comment by enigmaquip** [comment]
#696

**Comment by enigmaquip** [comment]
Fixed in latest build
