### ISSUE TITLE
I can run TEdit 3.6 without Directx11 (With screenshot and Youtube video)

### ISSUE THREAD

**Issue by halterc** [TEdit/Terraria-Map-Editor#709]
Hi all,

created an account just to post this awesome, somewhat miraculous bug/finding:

I can run TEdit version TEdit3_BETA_v3.6.15293.2023.zip on my notebook with a NVidia GeForce GT9600m (which can only run Directx 10!!! although there is Directx 11 installed)

I found it by incident. I had Terraria installed under "C:\GOG Games" and TEdit didn't work. Upon opening a window (TEdit v0.0.0.0) appeared, filled completely black, which turned white when I clicked it and didn't respond.

Then I noticed TEdit's default directory is "C:\Program Files\Steam\steamapps\common" so I placed my whole game folder there.

NOW for the miraculous part:
When I try to run TEdit now it asks where my Terraria folder is located. I indicate:
"C:\Program Files\Steam\steamapps\common\Terraria"
and TADAAA: TEdit starts and runs just perfectly (although it still says "TEdit v0.0.0.0" in the window title).

This was yesterday. Today I tried again and again but it didn't work, so I shifted the Terraria folder back and forth again and...it worked again!!!!

Hope someone sees this post and can reproduce my finding!
I have absolutely no clue how this is even possible but it works!

Hmm, in the screenshot it says TEdit's version is 3.6.150812.0114, dunno why. Also when I click Help>About in the TEdit window nothing happens.
The Log file is from Help>View Log

Edit: I uploaded a Youtube video of it :D
https://www.youtube.com/watch?v=5EazPLU39js

Cheers! :)
![screenshot](https://cloud.githubusercontent.com/assets/15263618/10692314/fcd885ae-7990-11e5-91a5-6400068c16a4.jpg)

**Comment by BinaryConstruct** [comment]
The system requirements are base on the minimum version known to be working on all platforms. So far, all DX11 compatible cards seem to all be compatible. However, some DX10 and DX9 platforms, epsecially older intel integrated chipsets are not compatible.
