### ISSUE TITLE
v0.0.0.0 in title bar

### ISSUE THREAD

**Issue by ev1l0rd** [TEdit/Terraria-Map-Editor#711]
I'm currently getting this on the title bar when launching the latest beta. The bug is similar to issue #648, except for the fact that TEdit only claims that I have an older version of the software. Aside from that, the program works.

**Comment by enigmaquip** [comment]
the v 0.0.0.0 seems to happen at times on the beta builds, and all the betas will notify you it's not the current version, you can turn off the update check from the file menu.... If it's working for you fine you can ignore the above two issues

**Comment by KenAlin** [comment]
Hi,
In fact, there is a weird error with the [AssemblyInfo file](https://github.com/TEdit/Terraria-Map-Editor/blob/master/TEditXna/Properties/AssemblyInfo.cs) at line 47/48. If I change "150812" by, let's say, 15812, the file version will be valid and will be correctly displayed as window title.

I personnally use this. I'm not annoyed anymore by the update checker, and it solves the problem ... but I don't know at all if that's a good solution.

```cs
[assembly: AssemblyVersion("3.6.15360.*")]
//[assembly: AssemblyFileVersion("3.6.0.0")]
```

**Comment by karma12gaming** [comment]
I have this same issue. The beta says v0.0.0.0 and then immediately crashes after asking me if I want to update. I tried the stable build and that doesn't work either.

**Comment by BinaryConstruct** [comment]
Please watch #751 for progress on this known issue.
