### ISSUE TITLE
Tedit crashed! What's happening?!!!!

### ISSUE THREAD

**Issue by Justranger** [TEdit/Terraria-Map-Editor#712]
I have tried to use Tedit to manage my map, but it doesn't start. The screen of map in Tedit is white. And whenever I try to do something, it is closed.

Here's my log.

10-30-2015 18:02: Starting TEdit 3.6.150812.0114 
10-30-2015 18:02: OS: Microsoft Windows NT 6.1.7601 Service Pack 1 
10-30-2015 18:02: Terraria Data Path: c:/program files (x86)/steam\steamapps\common\terraria\Content 
10-30-2015 18:02: Creating Undo cache: C:\Users\admin\AppData\Roaming\TEdit\undo_500641809 
10-30-2015 18:02: Failed to load texture: Images\NPC_17 
10-30-2015 18:02: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
10-30-2015 18:02: Failed to load texture: Images\NPC_18 
10-30-2015 18:02: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
10-30-2015 18:02: Failed to load texture: Images\NPC_19 
10-30-2015 18:02: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
10-30-2015 18:02: Failed to load texture: Images\NPC_20 
10-30-2015 18:02: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
10-30-2015 18:02: Failed to load texture: Images\NPC_22 
10-30-2015 18:02: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
10-30-2015 18:02: Failed to load texture: Images\NPC_37 
10-30-2015 18:02: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
10-30-2015 18:02: Failed to load texture: Images\NPC_38 
10-30-2015 18:02: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
10-30-2015 18:02: Failed to load texture: Images\NPC_54 
10-30-2015 18:02: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
10-30-2015 18:02: Failed to load texture: Images\NPC_107 
10-30-2015 18:02: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
10-30-2015 18:02: Failed to load texture: Images\NPC_108 
10-30-2015 18:02: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
10-30-2015 18:02: Failed to load texture: Images\NPC_124 
10-30-2015 18:02: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
10-30-2015 18:02: Failed to load texture: Images\NPC_142 
10-30-2015 18:02: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
10-30-2015 18:02: Failed to load texture: Images\NPC_160 
10-30-2015 18:02: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
10-30-2015 18:02: Failed to load texture: Images\NPC_178 
10-30-2015 18:02: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
10-30-2015 18:02: Failed to load texture: Images\NPC_207 
10-30-2015 18:02: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
10-30-2015 18:02: Failed to load texture: Images\NPC_208 
10-30-2015 18:02: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
10-30-2015 18:02: Failed to load texture: Images\NPC_209 
10-30-2015 18:02: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
10-30-2015 18:02: Failed to load texture: Images\NPC_227 
10-30-2015 18:02: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
10-30-2015 18:02: Failed to load texture: Images\NPC_228 
10-30-2015 18:02: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
10-30-2015 18:02: Failed to load texture: Images\NPC_229 
10-30-2015 18:02: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
10-30-2015 18:02: Failed to load texture: Images\NPC_353 
10-30-2015 18:02: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
10-30-2015 18:02: Failed to load texture: Images\NPC_369 
10-30-2015 18:02: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
10-30-2015 18:02: Failed to load texture: Images\NPC_441 
10-30-2015 18:02: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
10-30-2015 18:02: Failed to load texture: Images\NPC_422 
10-30-2015 18:02: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
10-30-2015 18:02: Failed to load texture: Images\NPC_493 
10-30-2015 18:02: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
10-30-2015 18:02: Failed to load texture: Images\NPC_507 
10-30-2015 18:02: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
10-30-2015 18:02: Failed to load texture: Images\NPC_517

**Comment by Justranger** [comment]
10-30-2015 18:02: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
10-30-2015 18:02: Error - HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown
   위치: SharpDX.Result.CheckError()
   위치: SharpDX.Direct3D11.Device.CreateTexture2D(Texture2DDescription& descRef, DataBox[] initialDataRef, Texture2D texture2DOut)
   위치: Microsoft.Xna.Framework.Graphics.Texture2D.CreateTexture()
   위치: Microsoft.Xna.Framework.Graphics.Texture.GetTexture()
   위치: TEditXna.View.WorldRenderXna.LoadTerrariaTextures(GraphicsDeviceEventArgs e) 파일 C:\a\1af8616d\TEdit\Terraria-Map-Editor\TEditXna\View\WorldRenderXna.xaml.cs:줄 237 
10-30-2015 18:02: Error - HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown
   위치: SharpDX.Result.CheckError()
   위치: SharpDX.Direct3D11.Device.CreateTexture2D(Texture2DDescription& descRef, DataBox[] initialDataRef, Texture2D texture2DOut)
   위치: Microsoft.Xna.Framework.Graphics.Texture2D.CreateTexture()
   위치: Microsoft.Xna.Framework.Graphics.Texture.GetTexture()
   위치: TEditXna.View.WorldRenderXna.LoadTerrariaTextures(GraphicsDeviceEventArgs e) 파일 C:\a\1af8616d\TEdit\Terraria-Map-Editor\TEditXna\View\WorldRenderXna.xaml.cs:줄 237 
10-30-2015 18:02: Error - HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown
   위치: SharpDX.Result.CheckError()
   위치: SharpDX.Direct3D11.Device.CreateTexture2D(Texture2DDescription& descRef, DataBox[] initialDataRef, Texture2D texture2DOut)
   위치: Microsoft.Xna.Framework.Graphics.Texture2D.CreateTexture()
   위치: Microsoft.Xna.Framework.Graphics.Texture.GetTexture()
   위치: TEditXna.View.WorldRenderXna.LoadTerrariaTextures(GraphicsDeviceEventArgs e) 파일 C:\a\1af8616d\TEdit\Terraria-Map-Editor\TEditXna\View\WorldRenderXna.xaml.cs:줄 237 
10-30-2015 18:02: Error - HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown
   위치: SharpDX.Result.CheckError()
   위치: SharpDX.Direct3D11.Device.CreateTexture2D(Texture2DDescription& descRef, DataBox[] initialDataRef, Texture2D texture2DOut)
   위치: Microsoft.Xna.Framework.Graphics.Texture2D.CreateTexture()
   위치: Microsoft.Xna.Framework.Graphics.Texture.GetTexture()
   위치: TEditXna.View.WorldRenderXna.LoadTerrariaTextures(GraphicsDeviceEventArgs e) 파일 C:\a\1af8616d\TEdit\Terraria-Map-Editor\TEditXna\View\WorldRenderXna.xaml.cs:줄 237 
10-30-2015 18:02: Error - HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown
   위치: SharpDX.Result.CheckError()
   위치: SharpDX.Direct3D11.Device.CreateTexture2D(Texture2DDescription& descRef, DataBox[] initialDataRef, Texture2D texture2DOut)
   위치: Microsoft.Xna.Framework.Graphics.Texture2D.CreateTexture()
   위치: Microsoft.Xna.Framework.Graphics.Texture.GetTexture()
   위치: TEditXna.View.WorldRenderXna.LoadTerrariaTextures(GraphicsDeviceEventArgs e) 파일 C:\a\1af8616d\TEdit\Terraria-Map-Editor\TEditXna\View\WorldRenderXna.xaml.cs:줄 237 
10-30-2015 18:02: Error - HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown
   위치: SharpDX.Result.CheckError()
   위치: SharpDX.Direct3D11.Device.CreateTexture2D(Texture2DDescription& descRef, DataBox[] initialDataRef, Texture2D texture2DOut)
   위치: Microsoft.Xna.Framework.Graphics.Texture2D.CreateTexture()
   위치: Microsoft.Xna.Framework.Graphics.Texture.GetTexture()
   위치: TEditXna.View.WorldRenderXna.LoadTerrariaTextures(GraphicsDeviceEventArgs e) 파일 C:\a\1af8616d\TEdit\Terraria-Map-Editor\TEditXna\View\WorldRenderXna.xaml.cs:줄 237 
10-30-2015 18:02: Error - HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown
   위치: SharpDX.Result.CheckError()
   위치: SharpDX.Direct3D11.Device.CreateTexture2D(Texture2DDescription& descRef, DataBox[] initialDataRef, Texture2D texture2DOut)
   위치: Microsoft.Xna.Framework.Graphics.Texture2D.CreateTexture()
   위치: Microsoft.Xna.Framework.Graphics.Texture.GetTexture()
   위치: TEditXna.View.WorldRenderXna.LoadTerrariaTextures(GraphicsDeviceEventArgs e) 파일 C:\a\1af8616d\TEdit\Terraria-Map-Editor\TEditXna\View\WorldRenderXna.xaml.cs:줄 237 
10-30-2015 18:02: Error - HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown
   위치: SharpDX.Result.CheckError()
   위치: SharpDX.Direct3D11.Device.CreateTexture2D(Texture2DDescription& descRef, DataBox[] initialDataRef, Texture2D texture2DOut)
   위치: Microsoft.Xna.Framework.Graphics.Texture2D.CreateTexture()
   위치: Microsoft.Xna.Framework.Graphics.Texture.GetTexture()
   위치: TEditXna.View.WorldRenderXna.LoadTerrariaTextures(GraphicsDeviceEventArgs e) 파일 C:\a\1af8616d\TEdit\Terraria-Map-Editor\TEditXna\View\WorldRenderXna.xaml.cs:줄 237 
10-30-2015 18:02: Error - HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown
   위치: SharpDX.Result.CheckError()
   위치: SharpDX.Direct3D11.Device.CreateTexture2D(Texture2DDescription& descRef, DataBox[] initialDataRef, Texture2D texture2DOut)
   위치: Microsoft.Xna.Framework.Graphics.Texture2D.CreateTexture()
   위치: Microsoft.Xna.Framework.Graphics.Texture.GetTexture()
   위치: TEditXna.View.WorldRenderXna.LoadTerrariaTextures(GraphicsDeviceEventArgs e) 파일 C:\a\1af8616d\TEdit\Terraria-Map-Editor\TEditXna\View\WorldRenderXna.xaml.cs:줄 237 
10-30-2015 18:02: Error - HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown
   위치: SharpDX.Result.CheckError()
   위치: SharpDX.Direct3D11.Device.CreateTexture2D(Texture2DDescription& descRef, DataBox[] initialDataRef, Texture2D texture2DOut)
   위치: Microsoft.Xna.Framework.Graphics.Texture2D.CreateTexture()
   위치: Microsoft.Xna.Framework.Graphics.Texture.GetTexture()
   위치: TEditXna.View.WorldRenderXna.LoadTerrariaTextures(GraphicsDeviceEventArgs e) 파일 C:\a\1af8616d\TEdit\Terraria-Map-Editor\TEditXna\View\WorldRenderXna.xaml.cs:줄 237 
10-30-2015 18:02: Error - HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown
   위치: SharpDX.Result.CheckError()
   위치: SharpDX.Direct3D11.Device.CreateTexture2D(Texture2DDescription& descRef, DataBox[] initialDataRef, Texture2D texture2DOut)
   위치: Microsoft.Xna.Framework.Graphics.Texture2D.CreateTexture()
   위치: Microsoft.Xna.Framework.Graphics.Texture.GetTexture()
   위치: TEditXna.View.WorldRenderXna.LoadTerrariaTextures(GraphicsDeviceEventArgs e) 파일 C:\a\1af8616d\TEdit\Terraria-Map-Editor\TEditXna\View\WorldRenderXna.xaml.cs:줄 237 
10-30-2015 18:02: Error - HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown
   위치: SharpDX.Result.CheckError()
   위치: SharpDX.Direct3D11.Device.CreateTexture2D(Texture2DDescription& descRef, DataBox[] initialDataRef, Texture2D texture2DOut)
   위치: Microsoft.Xna.Framework.Graphics.Texture2D.CreateTexture()
   위치: Microsoft.Xna.Framework.Graphics.Texture.GetTexture()
   위치: TEditXna.View.WorldRenderXna.LoadTerrariaTextures(GraphicsDeviceEventArgs e) 파일 C:\a\1af8616d\TEdit\Terraria-Map-Editor\TEditXna\View\WorldRenderXna.xaml.cs:줄 237 
10-30-2015 18:02: Error - HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown
   위치: SharpDX.Result.CheckError()
   위치: SharpDX.Direct3D11.Device.CreateTexture2D(Texture2DDescription& descRef, DataBox[] initialDataRef, Texture2D texture2DOut)
   위치: Microsoft.Xna.Framework.Graphics.Texture2D.CreateTexture()
   위치: Microsoft.Xna.Framework.Graphics.Texture.GetTexture()
   위치: TEditXna.View.WorldRenderXna.LoadTerrariaTextures(GraphicsDeviceEventArgs e) 파일 C:\a\1af8616d\TEdit\Terraria-Map-Editor\TEditXna\View\WorldRenderXna.xaml.cs:줄 237

**Comment by enigmaquip** [comment]
It's a SharpDX issue, see #648

**Comment by BinaryConstruct** [comment]
Please watch #751 for progress on this known issue.
