### ISSUE TITLE
TEdit world customizing technical issue.

### ISSUE THREAD

**Issue by Mrogurt** [TEdit/Terraria-Map-Editor#713]
When i open my world in TEdit then in the 'customizing area' is just white color, when i try to maximize it then all buttons just bug in to the customizin area, when  open the world there is nothing. and when i want to customize it by pressing brush and other buttons it just bugs and there comes the error icon to send TEdit log file to here. if would someone help me it would be so much cool and sorry for my english, too bad in english because im from czech republic :) And my Tedit log cannot be uploaded because i can only uplad PNG,GIF or JPG so i put it on Mediafire so you can download it and open it :) thx for help! http://www.mediafire.com/view/2qhqhse5s507mba/TEditLog.txt

**Comment by BinaryConstruct** [comment]
Please watch #751 for progress on this known issue.
