### ISSUE TITLE
Add ability to change world between normal mode and expert mode

### ISSUE THREAD

**Issue by OCDSquirrel** [TEdit/Terraria-Map-Editor#714]
This would be greatly appreciated. World analysis shows a line world.ExpertMode: True/False.

**Comment by SBlogic** [comment]
There's an "Expert Mode" check box on the World Properties panel.

**Comment by enigmaquip** [comment]
![expert](https://cloud.githubusercontent.com/assets/6134440/11162256/acbb80f4-8a56-11e5-8077-ab5617d29d19.PNG)
