### ISSUE TITLE
[Feature Request] Mask expand usage

### ISSUE THREAD

**Issue by Keaft** [TEdit/Terraria-Map-Editor#715]
So I'm working on that tree again.

I've been experimenting with the "Actuator/Tile inactive" to achieve a nice looking background in combination with all sorts of other shannanaginry.

It would be cool if the mask worked on the extra's tab too.

For instance Leaves as the tile, with a mask of matching, and leaves as the matching. Then when I enable Extra's, Actuator/Tile Inactive, it will only turn leaves into inactive tiles. 

I was trying to think if there would be an easier way to do it, but I think your existing mask could do that very well. (As far as intuitiveness is concerned.)

**Comment by BinaryConstruct** [comment]
Usability Improvements pt.2 #1274
