### ISSUE TITLE
2 first run glitches, and a possible issue with block styles

### ISSUE THREAD

**Issue by dmg122884** [TEdit/Terraria-Map-Editor#719]
On first run, the current beta (BETA_v3.6.15327.2018), the exe failed to load. The task manager showed 3 instances of TEditXna.exe, and was unable to close any of them. the solution was to reboot. On subsequent tries it appears to load correctly

On first run textures/images do not load for map tiles, so that only colors are shown to indicate tile content. Appears to work correctly on subsequent runs.

When any block is overwritten, or a block is placed where a block had once been, the new block takes the style of the previous block. Meaning if there was once a left slanted block, and it is replaced the new block will be left slanted. Or if a left slanted block is deleted and a new block inserted at that position sometime later it will start as left slanted. It does not appear to matter if the original block was removed in game, rather than via tEdit. Is this intentional behavior?

**Comment by BinaryConstruct** [comment]
Sort of intentional. You have to enable editing of block slants manually. The intentional part is so if you just want to change the tile type and not the tilt.

![image](https://cloud.githubusercontent.com/assets/456755/13714762/34291168-e796-11e5-9361-e2a897f72174.png)
