### ISSUE TITLE
Mac support?

### ISSUE THREAD

**Issue by cloutz** [TEdit/Terraria-Map-Editor#721]
I was wondering if you guys plan on making a Mac supported version now that we have a Mac version of Terraria? I don't like using virtual machines or anything like that and prefer native applications on my Mac.

**Comment by BinaryConstruct** [comment]
Unfortunately mono doesn't support WPF, and other than a VM I don't know of any other good way to run .net on mac.

http://www.mono-project.com/docs/gui/wpf/
