### ISSUE TITLE
unhandled exception

### ISSUE THREAD

**Issue by hexonine** [TEdit/Terraria-Map-Editor#726]
so i downloaded the TEdit and open it but it appear some pops up saying unhanled exception and close the TEdit.
i already look for the solution in the internet but none were working

[TEditLog.txt](https://github.com/TEdit/Terraria-Map-Editor/files/66238/TEditLog.txt)

**Comment by karma12gaming** [comment]
I just edited a map and closed the program. Everything was working fine but 20 minutes later I can't launch the program. (I'm using the current beta.) It asks me if I want to download the current version. Then it immediately crashes with an unhandled exception. The program window is solid white. My log file looks a lot like the OP's .

**Comment by BinaryConstruct** [comment]
Please watch #751 for progress on this known issue.
