### ISSUE TITLE
not working after restart map editor

### ISSUE THREAD

**Issue by JuanJJ** [TEdit/Terraria-Map-Editor#729]
when I download works fine, but after you restart map deitor stops working.
thanks.

[TEditLog.txt](https://github.com/TEdit/Terraria-Map-Editor/files/72219/TEditLog.txt)

**Comment by eXXOtaku** [comment]
My suggestion, try other build.
maybe it is crashy

Do you use .Net 4,5 and updatet you're DirectX ?

**Comment by BinaryConstruct** [comment]
Please watch #751 for progress on this known issue.
