### ISSUE TITLE
Unable to: Verify version/ Load Map

### ISSUE THREAD

**Issue by Lakaini** [TEdit/Terraria-Map-Editor#730]
I just downloaded the latest version for the fourth or fifth time. I have the latest version. When it starts, it checks for the latest version but immediate reports the error "Unable to Check Version".
After continuing, I attempt to open a map, any map and get an error. 
![worldfileerror](https://cloud.githubusercontent.com/assets/16449853/12009096/1050c598-ac30-11e5-99a0-be911efb41f3.jpg)
Any help would be appreciated!

**Comment by eXXOtaku** [comment]
Looks like, you use a stable branche. Try one of the Beta Builds (3.6). They`re ready für 1.3
http://www.binaryconstruct.com/downloads/

**Comment by helpmeoutbro** [comment]
ugh exact same thing noone can help fix this terrible mod

**Comment by BinaryConstruct** [comment]
TEdit beta should support the current version of Terraria. Older versions have very limited support.
