### ISSUE TITLE
Unable to start TEdit

### ISSUE THREAD

**Issue by PeterTehDumb** [TEdit/Terraria-Map-Editor#731]
I've just recently downloaded .NET 4.5 and installed TEdit. I couldn't seem to open the file, the process terminates itself after a few seconds with no error messages.

Log:
01-09-2016 01:24: Starting TEdit 3.5.14135.0 
01-09-2016 01:24: OS: Microsoft Windows NT 6.1.7600.0 
01-09-2016 01:24: .Net >= 4.0 
01-09-2016 01:24: XNA 4.0 
01-09-2016 01:24: Terraria Data Path: C:\Program Files\Steam\steamapps\common\Terraria\Content 
01-09-2016 01:24: Error - This method does not accept null for this parameter.
Parameter name: data
   at Microsoft.Xna.Framework.Graphics.Texture2D.CopyData[T](Int32 level, Nullable`1 rect, T[] data, Int32 startIndex, Int32 elementCount, UInt32 options, Boolean isSetting)
   at TEditXna.View.WorldRenderXna.LoadTerrariaTextures(GraphicsDeviceEventArgs e) 
01-09-2016 01:24: Error - Arithmetic operation resulted in an overflow.
   at TEditXna.View.WorldRenderXna.LoadTerrariaTextures(GraphicsDeviceEventArgs e)

**Comment by KenAlin** [comment]
Please download the latest beta version, if you are playing Terraria 1.3.0.8 (TEdit 3.5.14135.0 is an old version)
http://www.binaryconstruct.com/downloads/
Hope this will help

**Comment by BinaryConstruct** [comment]
Please watch #751 for progress on this known issue.
