### ISSUE TITLE
There was an error reading the world file

### ISSUE THREAD

**Issue by josh9** [TEdit/Terraria-Map-Editor#734]
Hi, first off I would like to say I really enjoy the program. It's well done and easy to use. 

My issue started when I updated my version of Terraria. Old world files will load fine but new ones are giving me trouble (it's been almost a year since I played). When I go to open a new world I created, TEditor pops up with "There was an error reading the world file, do you wish to force it to load anyway". Clicking yes or no results in nothing loading. I'm running Windows 7 64bit with DirectX 11.

Below is a screenshot of the error and my log file. Please let me know if you need anything else and I will be happy to supply it.

![tedit-errorloadingworldfile](https://cloud.githubusercontent.com/assets/12531069/12372726/35991d28-bc2f-11e5-83fd-501afa19dd27.jpg)

log file:
01-16-2016 08:27: Starting TEdit 3.5.14135.0 
01-16-2016 08:27: OS: Microsoft Windows NT 6.1.7601 Service Pack 1 
01-16-2016 08:27: .Net >= 4.0 
01-16-2016 08:27: XNA 4.0 
01-16-2016 08:27: Terraria Data Path: C:\Program Files (x86)\Steam\steamapps\common\Terraria\Content 
01-16-2016 08:27: Error - This method does not accept null for this parameter.
Parameter name: data
   at Microsoft.Xna.Framework.Graphics.Texture2D.CopyData[T](Int32 level, Nullable`1 rect, T[] data, Int32 startIndex, Int32 elementCount, UInt32 options, Boolean isSetting)
   at Microsoft.Xna.Framework.Graphics.Texture2D.GetData[T](Int32 level, Nullable`1 rect, T[] data, Int32 startIndex, Int32 elementCount)
   at TEditXna.View.WorldRenderXna.LoadTerrariaTextures(GraphicsDeviceEventArgs e) 
01-16-2016 08:27: Error - Arithmetic operation resulted in an overflow.
   at TEditXna.View.WorldRenderXna.LoadTerrariaTextures(GraphicsDeviceEventArgs e)

**Comment by KenAlin** [comment]
Hi,
It seems you use the stable version of TEdit. This version is not compatible with 1.3 worlds. You should download the latest beta version here : http://www.binaryconstruct.com/downloads/
(Don't worry, although it is labelled as "beta", it is usable)

Hope this helped you :)

**Comment by josh9** [comment]
That worked! Thank you for the speedy response!
