### ISSUE TITLE
Opens world partly, unable to read beyond stream

### ISSUE THREAD

**Issue by vieziis** [TEdit/Terraria-Map-Editor#735]
so, i'll let screenshot talk for itself and add the world file. much work behind this, help me if you can. 
![capture](https://cloud.githubusercontent.com/assets/16787910/12436241/1db4634e-bf1c-11e5-9d78-b14a6e9f63eb.JPG)

**Comment by vieziis** [comment]
Here's the world file. https://drive.google.com/file/d/0B6CkKf7_YzT9d1UwVmNQajNUVzQ/ 

If by solving the error itself, you can manage to get the world working, i would be forever thankful

**Comment by enigmaquip** [comment]
Wow, that is an old save file, I will take a look

**Comment by vieziis** [comment]
@enigmaquip yes, it is, dating back to 2013, I saved it in Google Drive and try to tackle this issue from time to time. If you manage to get it working, you'll see that a lot of effort has gone into it. Thank you in advance

**Comment by KenAlin** [comment]
If I remember well, each time Terraria is updated, your worlds are converted into the new format. I think if you open your world with Terraria 1.3.0.8 (the latest version), you'll then be able to open this world with TEdit beta.

**Comment by vieziis** [comment]
@KenAlin can't open, the world is corrupted. no backup. i come from ancient times

**Comment by BinaryConstruct** [comment]
Support for old worlds is limited, the beta should support the current version of Terraria.

**Comment by enigmaquip** [comment]
@vieziis Sorry I never came back to comment, but the world was corrupted..... just turns into empty data about halfway through the world
