### ISSUE TITLE
TEdit not rendering the world

### ISSUE THREAD

**Issue by ranguy** [TEdit/Terraria-Map-Editor#737]
http://i.imgur.com/Etv2VAu.png

strangely enough, when I open up the logs there's a ton of error messages - and it looks like it's the same error over and over again.

Error - HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown
   bei SharpDX.Result.CheckError()
   bei SharpDX.Direct3D11.Device.CreateTexture2D(Texture2DDescription& descRef, DataBox[] initialDataRef, Texture2D texture2DOut)
   bei Microsoft.Xna.Framework.Graphics.Texture2D.CreateTexture()
   bei Microsoft.Xna.Framework.Graphics.Texture.GetTexture()
   bei TEditXna.View.WorldRenderXna.LoadTerrariaTextures(GraphicsDeviceEventArgs e) in C:\a\1\s\TEditXna\View\WorldRenderXna.xaml.cs:Zeile 238.

I'm on a German Computer, so there's two words you wanna know: 
"bei" would roughly translate to "in" or "on" or "at" 
and "Zeile" means "line".
But with all translations, the correct wording depends on the context you're given

**Comment by BinaryConstruct** [comment]
Please watch #751 for progress on this known issue.
