### ISSUE TITLE
Morph Tool does not work with Ice Blocks.

### ISSUE THREAD

**Issue by kphillisjr** [TEdit/Terraria-Map-Editor#739]
The morph tool does not allow for easy biome translation for [Ice Blocks.](http://terraria.gamepedia.com/Ice_Block) (This is a link to the official terraria wiki page) These Types are as follows...

- Corrupt Ice Biome - This usually produces a lot of Purple Ice blocks.
- Crimson Ice Biome -The main feature of this is Red Ice Blocks.
- Hallow Ice  Biome - This features Pink Ice Block

Also as a quick note I tested using TEdit version v3.6.16020.0359, and the map itself is from Terraria version 1.3.0.8.

Also as a side note, the the log itself misidentifies TEdit as version 3.6.150812.0114 .

**Comment by tanpro260196** [comment]
I second this, morth tool also does not work with special cave wall and harden sand block.

**Comment by BinaryConstruct** [comment]
I'm merging this with #533 and closing this issue.

> Also as a side note, the the log itself misidentifies TEdit as version 3.6.150812.0114 .
This should be fixed with 3.6.16071 and up.
