### ISSUE TITLE
TEdit doesn't work on latest update!?

### ISSUE THREAD

**Issue by helpmeoutbro** [TEdit/Terraria-Map-Editor#742]
TEdit3_BETA_v3.6.16020.0359.zip

Thats what I Downloaded and when i extract the files, and click TEdit.exe
the thing opens it is white and blank and says TEdit v0.0.0.0.
After that it says 
"TEdit has stopped working; windows is trying to find a solution to the problem"
then
"TEdit has stopped working; A problem caused the program to stop working correctly."
Then I have to close the program.
If I try and download the latest *non-beta version*, it  tells me to download the update which is this, and then everything above happen. If I skip  the download some window with errors pops open when I try and load a world. **HELP!**

I *do* have -DirectX 11
                  -DotNet Framework 4.5 Full
Errorlog--
[TEditLog.txt](https://github.com/TEdit/Terraria-Map-Editor/files/120360/TEditLog.txt)

**Comment by KenAlin** [comment]
The error is "Error - Arithmetic operation resulted in an overflow.".
L249 : `var color = new Color[source.Height * source.Width];`

That's kinda strange for you to have an overflow here ... Are you using a 32-bits OS or a 64-bits one ?
Just in case, it seems you use Windows 8 : you should upgrade to Windows 8.1.

**Comment by BinaryConstruct** [comment]
Please watch #751 for progress on this known issue.
