### ISSUE TITLE
Download is on Risky site

### ISSUE THREAD

**Issue by Leumas-Eleets** [TEdit/Terraria-Map-Editor#744]
The site that you have to get TEdit from is a site that has been reported for unwanted programs being downloaded. I just had to do a factory reset on my computer because of unwanted programs. I would appreciate it if you could offer the download elsewhere.

**Comment by Leumas-Eleets** [comment]
Never mind about the download available elsewhere but you still probably want to not have it associated with that site.

**Comment by THEJaxster** [comment]
There is nothing wrong with this download.  Just follow the timer count down in the top left and click it after 5 seconds to skip.  Enjoy the awesome program.

**Comment by BinaryConstruct** [comment]
You can also bypass the adds by copying the URL to clipboard and just getting the last part, e.g.
http://www.binaryconstruct.com/downloads/TEdit3_BETA_v3.6.16050.1539.zip

This doesn't help pay for hosting, but I do understand the desire to bypass them from time to time.
