### ISSUE TITLE
What file do you run to use TEdit

### ISSUE THREAD

**Issue by Leumas-Eleets** [TEdit/Terraria-Map-Editor#745]
I don't want to take any risks

**Comment by Leumas-Eleets** [comment]
The files under install can not be run on my computer because my computer can not read the types of files they are. Any suggestions?

**Comment by KenAlin** [comment]
First, unzip the file downloaded. Then, double click on "TEditXna.exe" to launch TEdit.
Remember : TEdit is only for Windows.

**Comment by Leumas-Eleets** [comment]
I have Windows, I unzipped the folder, I just searched for TEditXna.exe in the unzipped files, there is no .exe under that name. The closest file is TEditXna.csproj which can not be run by my computer.

**Comment by Leumas-Eleets** [comment]
Any suggestions?

**Comment by Leumas-Eleets** [comment]
The only .exe in the entirety of the folders is nuget.exe which does nothing when I try to launch it.

**Comment by KenAlin** [comment]
Make sure you download the latest beta version from this page : http://www.binaryconstruct.com/downloads/
