### ISSUE TITLE
Can't Run Program

### ISSUE THREAD

**Issue by blazingstardust** [TEdit/Terraria-Map-Editor#748]
Every time I try to start TEdit, I get the same error - 'unable to check version'. I have the latest TEdit version and the latest Terraria version, so I'm not sure what the problem is.
[TEditLog.txt](https://github.com/TEdit/Terraria-Map-Editor/files/147315/TEditLog.txt)

**Comment by BinaryConstruct** [comment]
Please watch #751 for progress on this known issue.
