### ISSUE TITLE
Not letting world load in tedit

### ISSUE THREAD

**Issue by T3Deliciouz** [TEdit/Terraria-Map-Editor#750]
I've installed the latest version, however trying to load a world gives me this error. 

http://i.imgur.com/AqXlVVA.png

**Comment by enigmaquip** [comment]
You are not using the latest version, you are using one of the 3.5 versions which only supports up to v1.2 worlds.... you need a 3.6 install

**Comment by T3Deliciouz** [comment]
I didn't see that version in their download page

**Comment by BinaryConstruct** [comment]
http://www.binaryconstruct.com/downloads/
