### ISSUE TITLE
Texture Loading DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved

### ISSUE THREAD

**Issue by BinaryConstruct** [TEdit/Terraria-Map-Editor#751]
## Potential Solutions:
Update to Windows 10.

NVIDIA Control Panel -> Manage 3d Settings -> Set preferred graphics processor to integrated graphics card.

Updated DirectX for Windows7 SP1 using the manual installer.
https://www.microsoft.com/en-us/download/details.aspx?id=36805
  https://support.microsoft.com/en-us/kb/179113

---
## Issue

This is a known issue with MonoGame that is actively being worked on.
https://github.com/mono/MonoGame/pull/4337

See https://github.com/TEdit/Terraria-Map-Editor/issues/751#issuecomment-209800956 for possible solutions.

DXGI Error. GraphicsDevice is being disposed in some occasions during texture load leading to several issues.

Known conditions:
- Older Intel cards
- nVidia Cards in SLI
- nVidia cards 
  - nVidia 770 GTX

Please leave logs and tests for this issue here. Thank you.

3.6.16071 is the first version to attempt to implement a fix for this issue.

**Comment by Sl3ith** [comment]
Crash on launch with the latest beta.
I have a nvidia card (gtx 770), drivers 361.91, I'm on windows 7.
Log:
[TEditLog.txt](https://github.com/TEdit/Terraria-Map-Editor/files/170354/TEditLog.txt)

**Comment by BinaryConstruct** [comment]
@Sl3ith Would you try 364.51 WHQL http://www.nvidia.com/download/driverResults.aspx/99512/en-us ?

**Comment by Sl3ith** [comment]
Did a moment ago, still crash on launch.
This is the log 
[TEditLog.txt](https://github.com/TEdit/Terraria-Map-Editor/files/177846/TEditLog.txt)

I guess the fact that I have the 1.2 TEdit installed in another directory doesn't conflict with the latest Beta I've downloaded, right?

**Comment by BinaryConstruct** [comment]
No, it should not conflict.

**Comment by jennaelf** [comment]
Hi BC, 

I was having the exact same issue (and running a GeForce 750 Ti). I seem to have "fixed" my problem, but I am not sure whether it will help other users. As I came here via redirection from another bug thread, I thought it would be helpful to share anyway...

I am currently running Nvidia Driver 362.00, released 3/1/16.

I used the TEdit Requirements page to double-check and update my Framework.net and DirectX installations. Framework.net was up to date (or newer) and I was already running DirectX 11, but I downloaded the update, ran it, rebooted... and TEdit's latest beta opened up just fine. I was able to edit a 1.3 map, save, close, and then load (in Terraria) with no problems. 

I believe the DirectX update was slightly newer than the installation I was running (from last year - I don't automatically load all of MS's optional updates). If there's any way you know of for me to verify that, I'm happy to provide you with more information. But for now - I wanted to let you know of at least one situation where an Nvidia card having the same exact problem has been made to work.

**Comment by BinaryConstruct** [comment]
@jennaelf Thank you for the report

**Comment by Sl3ith** [comment]
I tried what jennaelf said and... it worked O_O
Whaaaat the heeeeeeeeeeellllll????? I would have done this months ago -_-

**Comment by JackShade** [comment]
Well, I have the common issue. The 3.6 beta versions don't work for me. I use Win7 x64; dx11, pack of framewoks, and C++ are installed too. I want to say that I was using some 3.6 version earlier but a month ago i reinstalled Windows (after my HDD has died), and now all these TEdit versions crash while loading with the message "go and check the log file". Can you help me and tell which soft have I missed this time? Thank you.

[TEditLog.txt](https://github.com/TEdit/Terraria-Map-Editor/files/191762/TEditLog.txt)

**Comment by BinaryConstruct** [comment]
@jackshade what GPU/driver version are you using? This may help identify the underlying issue. Thanks

**Comment by JackShade** [comment]
@BinaryConstruct it's AMD Radeon HD 8600/8700M, version 15.200.1062.0
I believe it's the same driver or newer than the driver i've used before my last Windows reinstall a month ago or so.

**Comment by JackShade** [comment]
Hi again.

Just updated (or tried to update 'cause many programs were updated yet) all the soft I could again: directX, Java Virtual Machine, .net Framework, XNA Framework, C++, dispaly driver and video driver. TEdit Beta (v3.6.16071.2036) still deosn't work for me. It is embarrassing even more 'cause I was using the TEdit beta last summer on the same notebook (Lenovo g500).
Well, may be one die you will solve the problevm :C
The drivers I use from today:
- AMD Radeon HD 8600/8700M, version 16.150.2211.0 (from 21.03.2016);
- Intel HD graphics 4000, version 10.18.10.4226 (from 25.05.2015).

And here is the log file: 
[TEditLog.txt](https://github.com/TEdit/Terraria-Map-Editor/files/214799/TEditLog.txt)

**Comment by jadexalshain** [comment]
I'm having the same troubles. I'm using the NVIDIA GeForce GTX 970 and my current driver version is 9.18.13.4411. I'm on DirectX 11. My error log appears to be identical to JackShade's. I'm gonna try updating my DirectX manually and see if that fixes it.

**Comment by JackShade** [comment]
> Update I updated my DirectX for Windows7 SP1 using the manual installer I found on https://support.microsoft.com/en-us/kb/179113 and now it's working! Hope this works for others too

Thank you very much! Your advice works for me too. I've downloaded the Windows6.1-KB2670838-x64.msu file from here http://www.microsoft.com/en-us/download/details.aspx?id=36805 (DirectX 11.1 for Windows 7 SP1 and Windows Server 2008 R2 SP1), and now the TEdit beta works without any error messages.

**Comment by mistzzt** [comment]
hi BC:
Name: NVIDIA GeForce GT 520M
thx
[TEditLog.txt](https://github.com/TEdit/Terraria-Map-Editor/files/222193/TEditLog.txt)

**Comment by DKPGROWTOPIA** [comment]
I did everything and it didnt work . My graphics card is Radeon and all my Dll`s and things are updated I also says in "Problem details" Its some kind of thing called "SharpDX" I searched everywhere and i cant find it Please help

**Comment by dfdtrtyftr** [comment]
[TEditLog.txt](https://github.com/TEdit/Terraria-Map-Editor/files/672284/TEditLog.txt)
i have 64 bit os
windows 7
8 gigabytes of ram
intel i5 core processor

**Comment by Andy22725** [comment]
I have tried everything you have said to fix this and it still errors
[TEditLog.txt](https://github.com/TEdit/Terraria-Map-Editor/files/691470/TEditLog.txt)

**Comment by retardedhorsie** [comment]
[TEditLog.txt](https://github.com/TEdit/Terraria-Map-Editor/files/778198/TEditLog.txt)

Apparently says the same thing, looks like the same error.
It's either something about my videocard (ATI Mobility Radeon HD4200 "crappy laptop.") or the fact that I am still using .NET Framework 4.5.2.

**Comment by Miotrestoked** [comment]
[TEditLog.txt](https://github.com/TEdit/Terraria-Map-Editor/files/816450/TEditLog.txt)
Here is my file, Please help me :(

**Comment by awbRED** [comment]
[TEditLog.txt](https://github.com/TEdit/Terraria-Map-Editor/files/842408/TEditLog.txt)

**Comment by awbRED** [comment]
Someone help me, my log is up

**Comment by BinaryConstruct** [comment]
Monogame has been updated to v3.6. Can anyone with this issue see if it is resolved with the latest version?

**Comment by GhaleonZ** [comment]
I ran TEdit yesterday with this builder world that has nothing but a huge warehouse full of items. It worked fine, loaded up and I fiddled around, then I shut it off and didn't think about it again.

Today I run TEdit, nothing has changed on my system. Yet suddenly Tedit is crashing with the DXGI issue killing it, and telling me Unhandled Exception.

Not sure how this can change from one day to the next, with absolutely no changes to the system, aside from it being powered down between issues.

**Comment by alabasca** [comment]
[TEditLog.txt](https://github.com/TEdit/Terraria-Map-Editor/files/1053312/TEditLog.txt)
that still says "Unhandled Exception" please help :(

**Comment by GhaleonZ** [comment]
I posted a trick you can do.
 
Rename the folder where your Terraria install is located.
Then when you run Tedit, it will ask you to point it to the Terraria 
folder, and run fine.
 
You have to do this each time before running Tedit, so it's not perfect. 
But it is better than nothing.


{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/TEdit/Terraria-Map-Editor","title":"TEdit/Terraria-Map-Editor","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/TEdit/Terraria-Map-Editor"}},"updates":{"snippets":[{"icon":"PERSON","message":"@alabasca in #751: [TEditLog.txt](https://github.com/TEdit/Terraria-Map-Editor/files/1053312/TEditLog.txt)\r\nthat still says \"Unhandled Exception\" please help :("}],"action":{"name":"View Issue","url":"https://github.com/TEdit/Terraria-Map-Editor/issues/751#issuecomment-306324919"}}}

**Comment by alabasca** [comment]
I already tried, but It still say like that. And it's not let me point it to the terraria folder :(
Can you show me how to do that on picture, because I'm not sure I'm do it right or wrong :)
Thank you.

**Comment by GhaleonZ** [comment]
I don't know how 
yours is. You just need to find where your Terraria.exe file is located. Rename 
the folder that is in. Like I switch mine from Terraria 1.3.5.3 to Terraria 
1.3.5.3a and back.
 
When running Tedit again, it should require you to point to where your 
Terraria is.


{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/TEdit/Terraria-Map-Editor","title":"TEdit/Terraria-Map-Editor","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/TEdit/Terraria-Map-Editor"}},"updates":{"snippets":[{"icon":"PERSON","message":"@alabasca in #751: I already tried, but It still say like that. And it's not let me point it to the terraria folder :(\r\nCan you show me how to do that on picture, because I'm not sure I'm do it right or wrong :)\r\nThank you."}],"action":{"name":"View Issue","url":"https://github.com/TEdit/Terraria-Map-Editor/issues/751#issuecomment-306357289"}}}

**Comment by alabasca** [comment]
what would you do? You change name the Terraria folder in Document or somewhere else?
Or what you change?

**Comment by GhaleonZ** [comment]
No, you change the 
folder where the Terraria install is.
 
If you run via Steam, it'd probably in inside the Steam folder inside 
Program Files.

**Comment by alabasca** [comment]
That said it's run somewhere else and don't let me change it :(

**Comment by GhaleonZ** [comment]
Do a search on your 
PC for Terraria.exe
 
The folder that is in, is the one you rename.


{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/TEdit/Terraria-Map-Editor","title":"TEdit/Terraria-Map-Editor","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/TEdit/Terraria-Map-Editor"}},"updates":{"snippets":[{"icon":"PERSON","message":"@alabasca in #751: That said it's run somewhere else and don't let me change it :("}],"action":{"name":"View Issue","url":"https://github.com/TEdit/Terraria-Map-Editor/issues/751#issuecomment-306359151"}}}

**Comment by alabasca** [comment]
I already try to change the terraria.exe file. But it's still worth, still said unhandled exception

**Comment by GhaleonZ** [comment]
You don't rename 
Terraria.exe.
 
You rename the folder it is in.

**Comment by alabasca** [comment]
I can't, It's said it run somewhere else, don't let me rename :(

**Comment by GhaleonZ** [comment]
Something on your PC 
is using the folder. Steam maybe. You need to open the Task Manager and kill 
Steam to rename it. Shut off Steam if it is running.


{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/TEdit/Terraria-Map-Editor","title":"TEdit/Terraria-Map-Editor","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/TEdit/Terraria-Map-Editor"}},"updates":{"snippets":[{"icon":"PERSON","message":"@alabasca in #751: I can't, It's said it run somewhere else, don't let me rename :("}],"action":{"name":"View Issue","url":"https://github.com/TEdit/Terraria-Map-Editor/issues/751#issuecomment-306361759"}}}

**Comment by alabasca** [comment]
It's still not, but thank anyway :)

**Comment by BinaryConstruct** [comment]
@GhaleonZ , you may wish to update your api key as your mail client is leaving it in all of your comments.

**Comment by TerraristAndrew** [comment]
@GhaleonZ, your tip with renaming Terraria folder actually worked for me, I finally was able to launch TEdit and it even saved all the world changes! Thank you!

**Comment by FrustrationReality** [comment]
[SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved]
===
08-28-2017 17:08:05: Starting TEdit 3.10.17116.2025 
08-28-2017 17:08:05: OS: Microsoft Windows NT 6.1.7601 Service Pack 1 
08-28-2017 17:08:05: Terraria v1.3.5.3 
===
Operating System: Windows 7 Enterprise 64-bit
           Card name: NVIDIA GeForce GTX 760
      NVIDIA Driver: 362

**Comment by SlxGamer** [comment]
Hello, I tried to start TEdit v3.10 and it won't start because of unhandled exception...

This is the whole log... 
[TEditLog.txt](https://github.com/TEdit/Terraria-Map-Editor/files/1269980/TEditLog.txt)

Operating System: Windows 7 Ultimate 64-bit
DirectX Version: DirectX 11
Graphics Card: ATI Mobility Radeon HD 5650

**Comment by ReddAkel** [comment]
I came across this problem as well. I thought about doing the possible solutions, but didn't really feel like it. 

So I instead went to the Terraria World save folder in My Documents. Right clicked on the map file I wanted to edit and clicked "open with" and selected TEdit as the program to "open with".... it worked. I exited and tried again and it worked again.

I thought it would be good to post this here for anyone else who is still having this problem.

**Comment by smgamermat77** [comment]
For any Windows 7 users out there **who don't possess separate integrated graphics** to supplement their GTX 770 (or 760 like me), **you are literally fucked.**

Microsoft doesn't allow windows 7 users to acquire DX 11.2, meaning you are literally unable to fix the problem that T_Edit has.

[Read more here on this issue](http://www.tomshardware.com/answers/id-2365432/directx-windows.html)

**Comment by BinaryConstruct** [comment]
DX 11.1 is included with the platform update. https://www.microsoft.com/en-us/download/details.aspx?id=36805

**Comment by ItzAdel** [comment]
BinaryConstruct I have GPU AMD R7 250X, and i instsled drivers today

**Comment by Gabrielyolo** [comment]
when i open TEDIT it says "unhandled exception" , about a year ago i was using the same version and then it disappeared now it keeps on saying unhandled exception and i cant fix it plz help me and my terraria version is 1.3.5.3

**Comment by Gabrielyolo** [comment]
TEditLog.txt

**Comment by ZEkA10000** [comment]
[TEditLog.txt](https://github.com/TEdit/Terraria-Map-Editor/files/3439503/TEditLog.txt)
I have Issue 
Windows 7 DirectX 11
Terraria 1.3.5.3 (Steam)

**Comment by MakroxMiau** [comment]
The program doesn't start, Terraria v1.3.5.3 Steam, Win7, Directx 11 (Can't update to 11.1)
[TEditLog.txt](https://github.com/TEdit/Terraria-Map-Editor/files/4124474/TEditLog.txt)

**Comment by Sleepy0761** [comment]
Unhandled Exception

Terraria 1.4.2.3

Tedit Version 4.5.3

Windows 10

I have DirectX 12, but i still have this issue.

[TEditLog.txt](https://github.com/TEdit/Terraria-Map-Editor/files/7537046/TEditLog.txt)
