### ISSUE TITLE
Tedit xbox 360 world

### ISSUE THREAD

**Issue by RomanGCastillo** [TEdit/Terraria-Map-Editor#753]
[TEditLog.txt](https://github.com/TEdit/Terraria-Map-Editor/files/171328/TEditLog.txt)

**Comment by enigmaquip** [comment]
TEdit will only read desktop version save files, the console versions have
a different save format

**Comment by RomanGCastillo** [comment]
ok thanks

**Comment by 641i130** [comment]
How would one even open or convert this different save format? I'd be willing to learn how to use C# just for this problem.

**Comment by BinaryConstruct** [comment]
See https://forums.terraria.org/index.php?threads/official-505games-policy-regarding-console-mobile-hacking.35819/#post-1801576

**Comment by 641i130** [comment]
This makes me sad. Now I really need to learn C# and do it myself 😂. Any pointers on where I would start for converting save files? Is there a type of header for each file version the corresponds to the platform or do I need to start at the basics? I know that it's not as simple as a JSON or ZIP Save file.

**Comment by BinaryConstruct** [comment]
I would start with the world file loader class, and Google around for any previously released converters. https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/

**Comment by 641i130** [comment]
Ooh cool I'll defininetly look into that.

**Comment by 641i130** [comment]
Where would I find the world file loader class? Is that in the source code of Terraria or is it some other program?

**Comment by BinaryConstruct** [comment]
Yes: https://github.com/TEdit/Terraria-Map-Editor/blob/master/TEditXna/Terraria/World.FileV2.cs
