### ISSUE TITLE
Tedit world creator closes

### ISSUE THREAD

**Issue by RomanGCastillo** [TEdit/Terraria-Map-Editor#754]
[TEditLog.txt](https://github.com/TEdit/Terraria-Map-Editor/files/175244/TEditLog.txt)

**Comment by KenAlin** [comment]
Please download the latest beta version of TEdit : http://www.binaryconstruct.com/downloads/

Secondly, be sure to use TEdit on a computer where Terraria is installed. In your case, there is `Terraria Data Path: G:\Content` in your log, but I'm not sure this is a correct path ..
