### ISSUE TITLE
Can't load working world with TEdit

### ISSUE THREAD

**Issue by JackShade** [TEdit/Terraria-Map-Editor#757]
Hi.
A month ago I have reinstalled Windows and after that I can't load some worlds that aren't corrupted (just checked them in game).
Well, last time I have loaded these worlds I've used another TEdit version (can't remember which one). And now I'm using 3.5.14228.27 (I have tried another versions from the download list too).
On the screenshot you can see the error details.
If you need the world example file then here it is: 
https://drive.google.com/open?id=0B1uehI58kXsaa0NGOEJKNmN3UVE

![default](https://cloud.githubusercontent.com/assets/18096519/14064138/4b5ba088-f3ff-11e5-9510-566b38590308.jpg)

P.s.:
I can't use the new TEdit versions (betas). Have I start the new "ticket" or I can describe an issue here and show the logo file here too?

**Comment by enigmaquip** [comment]
You cannot load a 1.3+ world in a 3.5 version of TEdit, it will only open a 1.2 world or less...You must use one of the beta 3.6 versions if you want to edit a current world

**Comment by JackShade** [comment]
Oh, I see... Well, the betas don't work on my PC for some reason. They all show me the message:
![error](https://cloud.githubusercontent.com/assets/18096519/14070970/9057a396-f4b6-11e5-9d4e-0251f7c1f473.jpg)

And the log file:
https://drive.google.com/open?id=0B1uehI58kXsaTTctUE9kUk1XZUE

And as I said earlier, some of these betas worked for me before I have reinstalled Windows. That means I've missed some additional soft? Which one can it be? There are MS C++ reist 2005-2015, .Net Framework 3.0-4.5, and XNA Framework 4.0 are installed on my PC.

**Comment by enigmaquip** [comment]
Without being able to access your logfile my first guess would be the DXGI issue referenced in #751, some people have had luck it looks like by upgrading to the latest version of directx11

**Comment by JackShade** [comment]
Have no idea why you cannot grab log file from google drive... Well, maybe you can take it from here: http://ifolder.com.ua/1imrlevx1128.html ?

**Comment by BinaryConstruct** [comment]
Merged with 751
