### ISSUE TITLE
TEdit can't open any worlds, doesn't recognize them.

### ISSUE THREAD

**Issue by JacobRuby** [TEdit/Terraria-Map-Editor#759]
Hello! I'm using TEdit 3 and when I try to open a world it says There is and error reading the world file. And it says that it is not the right format or something! Please tell me how I can fix this

**Comment by enigmaquip** [comment]
If you are using one of the version 3.5's then it will only read up to a
world file of version 1.2 or less.... If you want to open a current world
file you need to use one of the Beta 3.6's, the download page says this as
well.

**Comment by JacobRuby** [comment]
Ok thanks! I'll do that!
