### ISSUE TITLE
Editor screen is blank

### ISSUE THREAD

**Issue by timstrike** [TEdit/Terraria-Map-Editor#760]
Hello everyone. When I try to open the world editor, the large screen that you actually use to edit remains blank. I have tried to load my world and create new ones to no avail. I have tried reinstalling Terraria and tried multiple versions of the editor with no luck. When I maximize the screen, the UI seems to encompass part of the blank screen. 
Any help would be greatly appreciated!

**Comment by BinaryConstruct** [comment]
Can you include a screenshot as well as any log data? dxdiag screenshots are helpful as well.
For example:
![image](https://cloud.githubusercontent.com/assets/456755/14364975/fc9e4538-fcd0-11e5-9475-7f70ffcb1140.png)

**Comment by BinaryConstruct** [comment]
#751
