### ISSUE TITLE
Cant launch TEdit second time

### ISSUE THREAD

**Issue by Electronegative** [TEdit/Terraria-Map-Editor#762]
I downloaded TEdit and opened it. First time it worked but after that a "Unhandled Exceptoin" kept poping up. Here is the text ocument
[TEditLog.txt](https://github.com/TEdit/Terraria-Map-Editor/files/210717/TEditLog.txt)
Thank you for reading this and sorry for my bad english.

**Comment by BinaryConstruct** [comment]
This is a duplicate of #751, please see that issue for some suggestions that might help.
