### ISSUE TITLE
Error on starting editor

### ISSUE THREAD

**Issue by ZitWang** [TEdit/Terraria-Map-Editor#763]
### uh, since i submit this issue for my friend, i didn't know thoroughly about his computer's environment.. 

> The TEdit does not work well on my machine. It suggested that i should submit the log to you( the Github issues ). here i uploaded what was generated during the failure of tedit. Please help me, thx.
> part of the log file (the origin file was below, uploaded.)

## part of the log file
04-12-2016 16:23:28: Starting TEdit 3.6.16071.2036 
04-12-2016 16:23:28: OS: Microsoft Windows NT 6.1.7601 Service Pack 1 
04-12-2016 16:23:32: Terraria Data Path: D:\201603\Steam\steamapps\common\Terraria\Content 
04-12-2016 16:23:37: Creating Undo cache: C:\Users\Administrator\AppData\Roaming\TEdit\undo_2386542 
04-12-2016 16:23:42: Failed to load texture: Images\NPC_17
Failed to load texture: Images\NPC_517 
04-12-2016 16:23:42: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
04-12-2016 16:23:42: Error - HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown
   在 SharpDX.Result.CheckError()
   在 SharpDX.Direct3D11.Device.CreateTexture2D(Texture2DDescription& descRef, DataBox[] initialDataRef, Texture2D texture2DOut)
   在 Microsoft.Xna.Framework.Graphics.Texture2D.CreateTexture()
   在 Microsoft.Xna.Framework.Graphics.Texture2D..ctor(GraphicsDevice graphicsDevice, Int32 width, Int32 height, Boolean mipmap, SurfaceFormat format, SurfaceType type, Boolean shared, Int32 arraySize)
   在 TEditXna.View.WorldRenderXna.LoadTerrariaTextures(GraphicsDeviceEventArgs e) 位置 c:\projects\terraria-map-editor\TEditXna\View\WorldRenderXna.xaml.cs:行号 237 
04-12-2016 16:23:42: Error - HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown
   在 SharpDX.Result.CheckError()
   在 SharpDX.Direct3D11.Device.CreateTexture2D(Texture2DDescription& descRef, DataBox[] initialDataRef, Texture2D texture2DOut)
   在 Microsoft.Xna.Framework.Graphics.Texture2D.CreateTexture()
   在 Microsoft.Xna.Framework.Graphics.Texture2D..ctor(GraphicsDevice graphicsDevice, Int32 width, Int32 height, Boolean mipmap, SurfaceFormat format, SurfaceType type, Boolean shared, Int32 arraySize)
   在 TEditXna.View.WorldRenderXna.LoadTerrariaTextures(GraphicsDeviceEventArgs e) 位置 c:\projects\terraria-map-editor\TEditXna\View\WorldRenderXna.xaml.cs:行号 237 
04-12-2016 16:23:42: Error - HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown
   在 SharpDX.Result.CheckError()
   在 SharpDX.Direct3D11.Device.CreateTexture2D(Texture2DDescription& descRef, DataBox[] initialDataRef, Texture2D texture2DOut)
   在 Microsoft.Xna.Framework.Graphics.Texture2D.CreateTexture()
   在 Microsoft.Xna.Framework.Graphics.Texture2D..ctor(GraphicsDevice graphicsDevice, Int32 width, Int32 height, Boolean mipmap, SurfaceFormat format, SurfaceType type, Boolean shared, Int32 arraySize)
   在 TEditXna.View.WorldRenderXna.LoadTerrariaTextures(GraphicsDeviceEventArgs e) 位置 c:\projects\terraria-map-editor\TEditXna\View\WorldRenderXna.xaml.cs:行号 237 
04-12-2016 16:23:42: Error - HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown
   在 SharpDX.Result.CheckError() 
行号 == Line
在 == In
 位置 == File Path
[TEditLog(1).txt](https://github.com/TEdit/Terraria-Map-Editor/files/214713/TEditLog.1.txt)

**Comment by BinaryConstruct** [comment]
This is due to #751. Please follow progress there. Thanks
