### ISSUE TITLE
TEdit Blank screen on the left side after loading my world and distorted/bugged interface when maximized

### ISSUE THREAD

**Issue by Barnse** [TEdit/Terraria-Map-Editor#768]

**Comment by BinaryConstruct** [comment]
Can you please attach the log and a screenshot?

**Comment by Barnse** [comment]
http://puu.sh/owwD8/5b625ebca6.png There's the screenshot.

[TEditLog.txt](https://github.com/TEdit/Terraria-Map-Editor/files/237035/TEditLog.txt)

I have 2 terraria folders, one in steamapps > common > Terraria and one in My Documents > My Games > Terraira

The one in my documents has my saves and the one in has the game, not sure if this is the issue but i'm choosing the steam version for the directory but when loading a map it takes me to the Terraria folder located in my documents.

**Comment by BinaryConstruct** [comment]
Thanks, this looks like the DXGI issue, but there wasn't anything in the log to indicate that.  Can you try adjusting your windows font scale to 100% and see if that makes any difference?

**Comment by Barnse** [comment]
Changed from 125% to 100% and still no dice

**Comment by Barnse** [comment]
Any idea's please? I'm still very interested in using this program

**Comment by Barnse** [comment]
Never mind I just fixed it, turns out turning to 100% text did fix the issue I just had to restart my PC

**Comment by BinaryConstruct** [comment]
Thanks, good info for the wiki.
