### ISSUE TITLE
Virus Warning

### ISSUE THREAD

**Issue by amazingtroll** [TEdit/Terraria-Map-Editor#770]
DO NOT go to the Binary Download page. After you download the program the page redirects you to a fake warning website that says your computer is infected with a virus

If you click to download and install that software to remove the virus from your computer it installs ransom ware on your computer and demands money from you.

Do not trust shady authors like these assholes when there are MANY safe places they could have stored those binary codes on.

They just stored it on a place infested with Virus's, Spyware, and Ransom ware hoping to make a quick buck they are just assholes.

**Comment by BinaryConstruct** [comment]
Use an ad blocker such as https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm?hl=en
