### ISSUE TITLE
Map loading but not showing.

### ISSUE THREAD

**Issue by serratiger** [TEdit/Terraria-Map-Editor#771]
Hello. 
I recently downloaded TEdit to work on my map built on 1.3 but the software does not display any map although the status marks "render complete". If I resize or move the toolbar, it leaves a lingering imprint on the workspace, even before a map is loaded. I do have updated DotNet Framework and DirectX to the latest version.
Other than that, the map loads and the pointer tells me what type of tiles I'm over, as well as allowing me to edit and save my maps. 

 OS Windows 10, CPU i7-4720HQ, NVIDIA GTX960M ver 10.18.13.6175
Log:
05-02-2016 17:17:19: Starting TEdit 3.6.16071.2036 
05-02-2016 17:17:19: OS: Microsoft Windows NT 6.2.9200.0 
05-02-2016 17:17:19: Terraria Data Path: C:\Program Files (x86)\Steam\steamapps\common\Terraria\Content 
05-02-2016 17:17:20: Creating Undo cache: C:\Users\Serra\AppData\Roaming\TEdit\undo_674428347 

Thank you for your help!

**Comment by BinaryConstruct** [comment]
Can you please include a screenshot?

**Comment by serratiger** [comment]
Here it is. This is after I changed the size of the editor and then loaded the map.
![untitled](https://cloud.githubusercontent.com/assets/19159102/15054386/02495896-12bc-11e6-8378-7cc7c5f5fac6.png)

**Comment by Skilllzy** [comment]
please help binaryconstruct. I'm experiencing the exact same thing. the mini map loads but not the main view. Render is complete as well.

**Comment by BinaryConstruct** [comment]
Do either of you have the DXGI error in the log file listed in #751 ?

**Comment by Ariandel** [comment]
Do either of you have an integrated graphics card AND a dedicated graphics card?

I had this problem, but I fixed it by going into my NVIDIA Control Panel -> Manage 3d Settings -> Set preferred graphics processor to integrated graphics card.

**Comment by serratiger** [comment]
I have not had the DXGI error. 
I have only one graphics card unless I'm confused
