### ISSUE TITLE
Possible issue regarding sand blocks and the Replace All Tiles tool

### ISSUE THREAD

**Issue by RandomGuy331** [TEdit/Terraria-Map-Editor#772]
After I use the 'Replace All Tiles' tool to remove the crimson and hallow from my world, places like the Underground Desert, Pyramids, and places where there are any sand-related blocks seem to render as sand and fall as such:
![broken desert](https://cloud.githubusercontent.com/assets/19160595/14973602/701b3092-10af-11e6-886e-54de51170ef6.png)
This might only occur with repeated usage of the tool, however. Hopefully it gets fixed soon; it happened with previous versions I've noticed as well.

**Comment by BinaryConstruct** [comment]
There is a sand settle plugin. Perhaps it is getting accidentally activated. I'll look into adding promts for its action.

**Comment by enigmaquip** [comment]
There was definitely an issue with the sand settle plugin that has now been fixed, but I don't see a call to sand settle in the replace all tiles plugin
