### ISSUE TITLE
Tedit will be closed

### ISSUE THREAD

**Issue by Render2412** [TEdit/Terraria-Map-Editor#774]
`05-11-2016 13:02:32: Starting TEdit 3.6.16126.1508 
05-11-2016 13:02:32: OS: Microsoft Windows NT 6.1.7601 Service Pack 1 
05-11-2016 13:02:33: Terraria Data Path: D:\Steam\steamapps\common\Terraria\Content 
05-11-2016 13:02:33: Creating Undo cache: C:\Users\Radek\AppData\Roaming\TEdit\undo_943131367 
05-11-2016 13:02:33: Failed to load texture: Images\NPC_17 
05-11-2016 13:02:33: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
05-11-2016 13:02:33: Failed to load texture: Images\NPC_18 
05-11-2016 13:02:33: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
05-11-2016 13:02:33: Failed to load texture: Images\NPC_19 
05-11-2016 13:02:33: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
05-11-2016 13:02:33: Failed to load texture: Images\NPC_20 
05-11-2016 13:02:33: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
05-11-2016 13:02:33: Failed to load texture: Images\NPC_22 
05-11-2016 13:02:33: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
05-11-2016 13:02:33: Failed to load texture: Images\NPC_37 
05-11-2016 13:02:33: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
05-11-2016 13:02:33: Failed to load texture: Images\NPC_38 
05-11-2016 13:02:33: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
05-11-2016 13:02:33: Failed to load texture: Images\NPC_54 
05-11-2016 13:02:33: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
05-11-2016 13:02:33: Failed to load texture: Images\NPC_107 
05-11-2016 13:02:33: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
05-11-2016 13:02:33: Failed to load texture: Images\NPC_108 
05-11-2016 13:02:33: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
05-11-2016 13:02:33: Failed to load texture: Images\NPC_124 
05-11-2016 13:02:33: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
05-11-2016 13:02:33: Failed to load texture: Images\NPC_142 
05-11-2016 13:02:33: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
05-11-2016 13:02:33: Failed to load texture: Images\NPC_160 
05-11-2016 13:02:33: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
05-11-2016 13:02:33: Failed to load texture: Images\NPC_178 
05-11-2016 13:02:33: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
05-11-2016 13:02:33: Failed to load texture: Images\NPC_207 
05-11-2016 13:02:33: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
05-11-2016 13:02:33: Failed to load texture: Images\NPC_208 
05-11-2016 13:02:33: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
05-11-2016 13:02:33: Failed to load texture: Images\NPC_209 
05-11-2016 13:02:33: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
05-11-2016 13:02:33: Failed to load texture: Images\NPC_227 
05-11-2016 13:02:33: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
05-11-2016 13:02:33: Failed to load texture: Images\NPC_228 
05-11-2016 13:02:33: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
05-11-2016 13:02:33: Failed to load texture: Images\NPC_229 
05-11-2016 13:02:33: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
05-11-2016 13:02:33: Failed to load texture: Images\NPC_353 
05-11-2016 13:02:33: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
05-11-2016 13:02:33: Failed to load texture: Images\NPC_369 
05-11-2016 13:02:33: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
05-11-2016 13:02:33: Failed to load texture: Images\NPC_441 
05-11-2016 13:02:33: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
05-11-2016 13:02:33: Failed to load texture: Images\NPC_422 
05-11-2016 13:02:33: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
05-11-2016 13:02:33: Failed to load texture: Images\NPC_493 
05-11-2016 13:02:33: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
05-11-2016 13:02:33: Failed to load texture: Images\NPC_507 
05-11-2016 13:02:33: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
05-11-2016 13:02:33: Failed to load texture: Images\NPC_517 
05-11-2016 13:02:33: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
05-11-2016 13:02:33: Error - HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown
   w SharpDX.Result.CheckError()
   w SharpDX.Direct3D11.Device.CreateTexture2D(Texture2DDescription& descRef, DataBox[] initialDataRef, Texture2D texture2DOut)
   w Microsoft.Xna.Framework.Graphics.Texture2D.CreateTexture()
   w Microsoft.Xna.Framework.Graphics.Texture.GetTexture()
   w TEditXna.View.WorldRenderXna.LoadTerrariaTextures(GraphicsDeviceEventArgs e) w c:\projects\terraria-map-editor\TEditXna\View\WorldRenderXna.xaml.cs:wiersz 238 
05-11-2016 13:02:33: Error - HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown
   w SharpDX.Result.CheckError()
   w SharpDX.Direct3D11.Device.CreateTexture2D(Texture2DDescription& descRef, DataBox[] initialDataRef, Texture2D texture2DOut)
   w Microsoft.Xna.Framework.Graphics.Texture2D.CreateTexture()
   w Microsoft.Xna.Framework.Graphics.Texture.GetTexture()
   w TEditXna.View.WorldRenderXna.LoadTerrariaTextures(GraphicsDeviceEventArgs e) w c:\projects\terraria-map-editor\TEditXna\View\WorldRenderXna.xaml.cs:wiersz 238 
05-11-2016 13:02:33: Error - HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown
   w SharpDX.Result.CheckError()
   w SharpDX.Direct3D11.Device.CreateTexture2D(Texture2DDescription& descRef, DataBox[] initialDataRef, Texture2D texture2DOut)
   w Microsoft.Xna.Framework.Graphics.Texture2D.CreateTexture()
   w Microsoft.Xna.Framework.Graphics.Texture.GetTexture()
   w TEditXna.View.WorldRenderXna.LoadTerrariaTextures(GraphicsDeviceEventArgs e) w c:\projects\terraria-map-editor\TEditXna\View\WorldRenderXna.xaml.cs:wiersz 238 
05-11-2016 13:02:33: Error - HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown
   w SharpDX.Result.CheckError()
   w SharpDX.Direct3D11.Device.CreateTexture2D(Texture2DDescription& descRef, DataBox[] initialDataRef, Texture2D texture2DOut)
   w Microsoft.Xna.Framework.Graphics.Texture2D.CreateTexture()
   w Microsoft.Xna.Framework.Graphics.Texture.GetTexture()
   w TEditXna.View.WorldRenderXna.LoadTerrariaTextures(GraphicsDeviceEventArgs e) w c:\projects\terraria-map-editor\TEditXna\View\WorldRenderXna.xaml.cs:wiersz 238 
05-11-2016 13:02:33: Error - HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown
   w SharpDX.Result.CheckError()
   w SharpDX.Direct3D11.Device.CreateTexture2D(Texture2DDescription& descRef, DataBox[] initialDataRef, Texture2D texture2DOut)
   w Microsoft.Xna.Framework.Graphics.Texture2D.CreateTexture()
   w Microsoft.Xna.Framework.Graphics.Texture.GetTexture()
   w TEditXna.View.WorldRenderXna.LoadTerrariaTextures(GraphicsDeviceEventArgs e) w c:\projects\terraria-map-editor\TEditXna\View\WorldRenderXna.xaml.cs:wiersz 238 
05-11-2016 13:02:33: Error - HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown
   w SharpDX.Result.CheckError()
   w SharpDX.Direct3D11.Device.CreateTexture2D(Texture2DDescription& descRef, DataBox[] initialDataRef, Texture2D texture2DOut)
   w Microsoft.Xna.Framework.Graphics.Texture2D.CreateTexture()
   w Microsoft.Xna.Framework.Graphics.Texture.GetTexture()
   w TEditXna.View.WorldRenderXna.LoadTerrariaTextures(GraphicsDeviceEventArgs e) w c:\projects\terraria-map-editor\TEditXna\View\WorldRenderXna.xaml.cs:wiersz 238 
05-11-2016 13:02:33: Error - HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown
   w SharpDX.Result.CheckError()
   w SharpDX.Direct3D11.Device.CreateTexture2D(Texture2DDescription& descRef, DataBox[] initialDataRef, Texture2D texture2DOut)
   w Microsoft.Xna.Framework.Graphics.Texture2D.CreateTexture()
   w Microsoft.Xna.Framework.Graphics.Texture.GetTexture()
   w TEditXna.View.WorldRenderXna.LoadTerrariaTextures(GraphicsDeviceEventArgs e) w c:\projects\terraria-map-editor\TEditXna\View\WorldRenderXna.xaml.cs:wiersz 238 
05-11-2016 13:02:33: Error - HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown
   w SharpDX.Result.CheckError()
   w SharpDX.Direct3D11.Device.CreateTexture2D(Texture2DDescription& descRef, DataBox[] initialDataRef, Texture2D texture2DOut)
   w Microsoft.Xna.Framework.Graphics.Texture2D.CreateTexture()
   w Microsoft.Xna.Framework.Graphics.Texture.GetTexture()
   w TEditXna.View.WorldRenderXna.LoadTerrariaTextures(GraphicsDeviceEventArgs e) w c:\projects\terraria-map-editor\TEditXna\View\WorldRenderXna.xaml.cs:wiersz 238 
05-11-2016 13:02:33: Error - HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown
   w SharpDX.Result.CheckError()
   w SharpDX.Direct3D11.Device.CreateTexture2D(Texture2DDescription& descRef, DataBox[] initialDataRef, Texture2D texture2DOut)
   w Microsoft.Xna.Framework.Graphics.Texture2D.CreateTexture()
   w Microsoft.Xna.Framework.Graphics.Texture.GetTexture()
   w TEditXna.View.WorldRenderXna.LoadTerrariaTextures(GraphicsDeviceEventArgs e) w c:\projects\terraria-map-editor\TEditXna\View\WorldRenderXna.xaml.cs:wiersz 238 
05-11-2016 13:02:33: Error - HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown
   w SharpDX.Result.CheckError()
   w SharpDX.Direct3D11.Device.CreateTexture2D(Texture2DDescription& descRef, DataBox[] initialDataRef, Texture2D texture2DOut)
   w Microsoft.Xna.Framework.Graphics.Texture2D.CreateTexture()
   w Microsoft.Xna.Framework.Graphics.Texture.GetTexture()
   w TEditXna.View.WorldRenderXna.LoadTerrariaTextures(GraphicsDeviceEventArgs e) w c:\projects\terraria-map-editor\TEditXna\View\WorldRenderXna.xaml.cs:wiersz 238 
05-11-2016 13:02:33: Error - HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown
   w SharpDX.Result.CheckError()
   w SharpDX.Direct3D11.Device.CreateTexture2D(Texture2DDescription& descRef, DataBox[] initialDataRef, Texture2D texture2DOut)
   w Microsoft.Xna.Framework.Graphics.Texture2D.CreateTexture()
   w Microsoft.Xna.Framework.Graphics.Texture.GetTexture()
   w TEditXna.View.WorldRenderXna.LoadTerrariaTextures(GraphicsDeviceEventArgs e) w c:\projects\terraria-map-editor\TEditXna\View\WorldRenderXna.xaml.cs:wiersz 238 
05-11-2016 13:02:33: Error - HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown
   w SharpDX.Result.CheckError()
   w SharpDX.Direct3D11.Device.CreateTexture2D(Texture2DDescription& descRef, DataBox[] initialDataRef, Texture2D texture2DOut)
   w Microsoft.Xna.Framework.Graphics.Texture2D.CreateTexture()
   w Microsoft.Xna.Framework.Graphics.Texture.GetTexture()
   w TEditXna.View.WorldRenderXna.LoadTerrariaTextures(GraphicsDeviceEventArgs e) w c:\projects\terraria-map-editor\TEditXna\View\WorldRenderXna.xaml.cs:wiersz 238 
05-11-2016 13:02:33: Error - HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown
   w SharpDX.Result.CheckError()
   w SharpDX.Direct3D11.Device.CreateTexture2D(Texture2DDescription& descRef, DataBox[] initialDataRef, Texture2D texture2DOut)
   w Microsoft.Xna.Framework.Graphics.Texture2D.CreateTexture()
   w Microsoft.Xna.Framework.Graphics.Texture.GetTexture()
   w TEditXna.View.WorldRenderXna.LoadTerrariaTextures(GraphicsDeviceEventArgs e) w c:\projects\terraria-map-editor\TEditXna\View\WorldRenderXna.xaml.cs:wiersz 238 
05-11-2016 13:02:33: Error - HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown
   w SharpDX.Result.CheckError()
   w SharpDX.Direct3D11.Device.CreateTexture2D(Texture2DDescription& descRef, DataBox[] initialDataRef, Texture2D texture2DOut)
   w Microsoft.Xna.Framework.Graphics.Texture2D.CreateTexture()
   w Microsoft.Xna.Framework.Graphics.Texture.GetTexture()
   w TEditXna.View.WorldRenderXna.LoadTerrariaTextures(GraphicsDeviceEventArgs e) w c:\projects\terraria-map-editor\TEditXna\View\WorldRenderXna.xaml.cs:wiersz 238 
05-11-2016 13:02:33: Error - HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown
   w SharpDX.Result.CheckError()
   w SharpDX.Direct3D11.Device.CreateTexture2D(Texture2DDescription& descRef, DataBox[] initialDataRef, Texture2D texture2DOut)
   w Microsoft.Xna.Framework.Graphics.Texture2D.CreateTexture()
   w Microsoft.Xna.Framework.Graphics.Texture.GetTexture()
   w TEditXna.View.WorldRenderXna.LoadTerrariaTextures(GraphicsDeviceEventArgs e) w c:\projects\terraria-map-editor\TEditXna\View\WorldRenderXna.xaml.cs:wiersz 238 
05-11-2016 13:02:33: Error - HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown
   w SharpDX.Result.CheckError()
   w SharpDX.Direct3D11.Device.CreateTexture2D(Texture2DDescription& descRef, DataBox[] initialDataRef, Texture2D texture2DOut)
   w Microsoft.Xna.Framework.Graphics.Texture2D.CreateTexture()
   w Microsoft.Xna.Framework.Graphics.Texture.GetTexture()
   w TEditXna.View.WorldRenderXna.LoadTerrariaTextures(GraphicsDeviceEventArgs e) w c:\projects\terraria-map-editor\TEditXna\View\WorldRenderXna.xaml.cs:wiersz 238 `

**Comment by enigmaquip** [comment]
See error #751
