### ISSUE TITLE
TEdit does not work

### ISSUE THREAD

**Issue by McSan4ez** [TEdit/Terraria-Map-Editor#775]
When you run the program TEdit, it crashes, it gives error and asks to close the program or find a solution on the Internet. Please help, I installed all the programs, I have installed directx 11. Sorry for my English.
![fsfsdf](https://cloud.githubusercontent.com/assets/19311888/15190911/2732fbe0-17d4-11e6-8274-9f0fc708f1e8.png)
 This problem in the newer versions (beta versions), on the first beta version just launched TEdit but when I run the map, it is not displayed, and I can not edit it. Help me please.

**Comment by McSan4ez** [comment]
05-12-2016 22:52:41: Starting TEdit 3.6.16126.1508 
05-12-2016 22:52:41: OS: Microsoft Windows NT 6.1.7600.0 
05-12-2016 22:52:41: Failed to verify Terraria Paths. TEdit may not run properly. 
05-12-2016 22:52:41: Error - Недопустимый URI-адрес. Путь Dos должен иметь корень, например, 'c:\'.
   в System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   в System.Xml.XmlResolver.ResolveUri(Uri baseUri, String relativeUri)
   в System.Xml.XmlTextReaderImpl..ctor(String uriStr, XmlReaderSettings settings, XmlParserContext context, XmlResolver uriResolver)
   в System.Xml.XmlReaderSettings.CreateReader(String inputUri, XmlParserContext inputContext)
   в System.Xml.Linq.XElement.Load(String uri, LoadOptions options)
   в TEditXNA.Terraria.World.LoadObjectDbXml(String file) в c:\projects\terraria-map-editor\TEditXna\Terraria\World.Settings.cs:строка 132
   в TEditXNA.Terraria.World..cctor() в c:\projects\terraria-map-editor\TEditXna\Terraria\World.Settings.cs:строка 49 
05-12-2016 22:52:41: Error - Инициализатор типа "TEditXNA.Terraria.World" выдал исключение.
   в TEditXna.DependencyChecker.CheckPaths() в c:\projects\terraria-map-editor\TEditXna\DependencyChecker.cs:строка 20
   в TEditXna.App.OnStartup(StartupEventArgs e) в c:\projects\terraria-map-editor\TEditXna\App.xaml.cs:строка 52 
05-12-2016 22:52:41: Unable to locate Terraria. No texture data will be available. 
05-12-2016 22:52:43: Error - Недопустимый URI-адрес. Путь Dos должен иметь корень, например, 'c:\'.
   в System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   в System.Xml.XmlResolver.ResolveUri(Uri baseUri, String relativeUri)
   в System.Xml.XmlTextReaderImpl..ctor(String uriStr, XmlReaderSettings settings, XmlParserContext context, XmlResolver uriResolver)
   в System.Xml.XmlReaderSettings.CreateReader(String inputUri, XmlParserContext inputContext)
   в System.Xml.Linq.XElement.Load(String uri, LoadOptions options)
   в TEditXNA.Terraria.World.LoadObjectDbXml(String file) в c:\projects\terraria-map-editor\TEditXna\Terraria\World.Settings.cs:строка 132
   в TEditXNA.Terraria.World..cctor() в c:\projects\terraria-map-editor\TEditXna\Terraria\World.Settings.cs:строка 49 
05-12-2016 22:52:43: Error - Инициализатор типа "TEditXNA.Terraria.World" выдал исключение.
   в TEditXNA.Terraria.World.get_TileBricks() 
05-12-2016 22:52:43: Error - Адресат вызова создал исключение.
   в System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   в System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   в System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   в System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   в System.Windows.Markup.StaticExtension.GetFieldOrPropertyValue(Type type, String name, Object& value)
   в System.Windows.Markup.StaticExtension.ProvideValue(IServiceProvider serviceProvider)
   в MS.Internal.Xaml.Runtime.ClrObjectRuntime.CallProvideValue(MarkupExtension me, IServiceProvider serviceProvider) 
05-12-2016 22:52:43: Error - Предоставление значения для "System.Windows.Markup.StaticExtension" вызвало исключение.
   в System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   в System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   в System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   в System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   в System.Windows.Application.DoStartup()
   в System.Windows.Application.<.ctor>b__1(Object unused)
   в System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   в MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   в System.Windows.Threading.DispatcherOperation.InvokeImpl()
   в System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   в System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   в System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   в System.Windows.Threading.DispatcherOperation.Invoke()
   в System.Windows.Threading.Dispatcher.ProcessQueue()
   в System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   в MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   в MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   в System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   в MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   в System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   в MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   в MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   в System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   в System.Windows.Application.RunDispatcher(Object ignore)
   в System.Windows.Application.RunInternal(Window window)
   в TEditXna.App.Main() в c:\projects\terraria-map-editor\TEditXna\obj\Release\App.g.cs:строка 0

**Comment by BinaryConstruct** [comment]
It could be an issue with character encoding on foreign language. I'll look into the issue, but it could take some time to correct for localization issues.

**Comment by McSan4ez** [comment]
Well, I will wait for a response. TEdit I worked before reinstalling windows, but unfortunately I do not remember which version I had TEdit. And the old version (3.5) in my work, but when I choose nothing happens card, not the card is loaded. I run some version 3.6 beta, but when you start Tedit 3.6 no where it should be a map, and when I load a map but it is loaded in the window does not appear, and I can not work with it. Sorry for my english.

**Comment by McSan4ez** [comment]
Oh, I tried to start the first TEdit version 3.6 but now even they fly as It was in the screenshot above. :(

**Comment by BinaryConstruct** [comment]
This may have to do with the temp folder for undo/redo. If your windows user name has unicode characters, it may be the issue. Can you try creating a windows user with only us-english a-z characters, run TEdit when logged in as this user, and see if this resolves the issue?

**Comment by BinaryConstruct** [comment]
Could you try version 3.7 and see if there is any improvement?

**Comment by McSan4ez** [comment]
Oh, I downloaded the latest version of the TEdit (TEdit 3_BETA_v3.7.16145.0754.zip) and she earned! Thank you for your help.

**Comment by McSan4ez** [comment]
I have a question. How to enable texture to TEdit?

**Comment by BinaryConstruct** [comment]
You must have the latest version of Terraria through Steam or Gog. Alternatively, you can set the terraria data path in the settings.xml file.

Uncomment this line: 
https://github.com/TEdit/Terraria-Map-Editor/blob/master/TEditXna/settings.xml#L91

References
https://github.com/TEdit/Terraria-Map-Editor/wiki/Settings

**Comment by McSan4ez** [comment]
I have the latest steam version of the game, but the textures do not appear.

**Comment by McSan4ez** [comment]
![fff](https://cloud.githubusercontent.com/assets/19311888/15605447/31507108-2430-11e6-903a-9660bb40ace5.png)
I have a way to Terraria but the textures don't appear.

**Comment by McSan4ez** [comment]
I downloaded a new version, and it worked! Thank you. :)

**Comment by musicus-yn** [comment]
Hello! I have a question. The latest version of the TEdit program stopped working today - "an unhandled exception occurred". Even last day, the program worked, with it no action other than editing maps, I did not commit. Please tell me how to deal with this?
