### ISSUE TITLE
Using it

### ISSUE THREAD

**Issue by ConnorMcName** [TEdit/Terraria-Map-Editor#777]
I have downloaded and extracted the files, none of the files are loose, but I don't understand how to use Tedit

**Comment by BinaryConstruct** [comment]
![image](https://cloud.githubusercontent.com/assets/456755/15416797/d3193a28-1e14-11e6-9a7b-8b2d06b3b9f3.png)

![image](https://cloud.githubusercontent.com/assets/456755/15416815/fa38fc88-1e14-11e6-9ae3-d221313741fa.png)

![image](https://cloud.githubusercontent.com/assets/456755/15416822/06ed80ca-1e15-11e6-9e0b-dc62d073b65d.png)


![image](https://cloud.githubusercontent.com/assets/456755/15416838/39237dce-1e15-11e6-826e-f086896a53e6.png)
