### ISSUE TITLE
Sprite masking?

### ISSUE THREAD

**Issue by megnvaughn** [TEdit/Terraria-Map-Editor#783]
I want to delete all of a type of sprite over a large area without affecting walls or tiles. (Editing out the Crimson/Hallow, need to delete all of the grass and cave deco sprites) Is this possible without individually deleting the sprites with the fill tool?

**Comment by BinaryConstruct** [comment]
You can use the Mask tool or the plugin->replace tiles options.

**Comment by megnvaughn** [comment]
Thanks for responding so quickly!

**Comment by megnvaughn** [comment]
Alternately, It would be a cool feature to have "Remove Corruption/Crimson" and "Remove Hallow" that just auto-replaces all of the crimson, corruption and hallow blocks with their regular versions and eliminated the grass sprites and thorns and vines etc associated with corruption, crimson and hallow

**Comment by enigmaquip** [comment]
I have plans to redo the morph tool with more contaminator like features...
it's been on my to-do list for a little bit... it's just rough finding the
time

**Comment by megnvaughn** [comment]
Thanks for everything you guys do! By no means am I rushing you, this is a kickass editor, and I am definitely getting my money's worth. Again, thanks guys!!!

**Comment by enigmaquip** [comment]
So...... Try the latest version that should be building now, I overhauled the morph tool for better biome modifying... It still doesn't touch the cave decos as they shouldn't affect biome spread

**Comment by megnvaughn** [comment]
3.7.16144.2135?

**Comment by enigmaquip** [comment]
Next one after that..... should be soon, it's all automated..... I took a look at cave decos.... that should be an easy addition as well so I may do that quick too

**Comment by megnvaughn** [comment]
It is everything I'd ever dreamed of and more!!! Best dev team ever!!

**Comment by enigmaquip** [comment]
And I've got cave decos in the mix now too :-) Keep an eye out for another build here soon
