### ISSUE TITLE
IndexOutOfRange when editing close to edge of the rendered area.

### ISSUE THREAD

**Issue by ndwaldner** [TEdit/Terraria-Map-Editor#785]
Here is what the dialog said:
> **Problem signature:**
> Problem Event Name:	CLR20r3
> Problem Signature 01:	teditxna.exe
> Problem Signature 02:	3.6.16141.351
> Problem Signature 03:	573e89d0
> Problem Signature 04:	TEditXna
> Problem Signature 05:	3.6.16141.351
> Problem Signature 06:	573e89d0
> Problem Signature 07:	17e
> Problem Signature 08:	1e7
> Problem Signature 09:	System.IndexOutOfRangeException
> OS Version:			6.1.7601.2.1.0.768.3
> Locale ID:			4105
> Additional Information 1:	151a
> Additional Information 2:	151a2fdd82c6c98a0e166645bb81c7b9
> Additional Information 3:	3081
> Additional Information 4:	3081396f1ff0bdb710239ba9f8229d9b

**Environment:**
Win7 SP1, 64bit, MS XNA 4.0 installed.
Intel Core2, 4GB RAM, nothing but explorer and TEdit 3.6 open in the foreground.

**Context:**
In-game I built a water dock at the edge of the screen at the bottom of the ocean, and just wanted level out the seabed to allow crabs and jellyfish to make it over the structure.

**Reproducing the error:**
1. Deleted blocks outside of the area the player can actually enter (first 40 or so blocks).
2. Used paintbrush to fill in the area with water, everything working fine...
3. Error occurred when trying to use the pencil to place glass blocks at about (39, 400), in the ocean and outside of the area the player can enter.
4. TEdit renders the area, and lets users delete blocks, and fill the area with water: so it might be worthwhile to catch this exception (and warn) or expand the array.

**Attachment:**
Content of three errors logged in Windows Error Reporting.
[TEdit - Windows Error Reports.txt](https://github.com/TEdit/Terraria-Map-Editor/files/277291/TEdit.Error.txt)

**Comment by BinaryConstruct** [comment]
I've added 5bd1746a240c46b918f79f1c5d24630520de5b1f as an attempt to resolve.

**Comment by BinaryConstruct** [comment]
Does this still occur with 3.7?

**Comment by ndwaldner** [comment]
3.7 seems to take care of this issue, was able to edit the area without a crash! Although, it seems the fix might have introduced a small bug with the fill tool while working in this area. When you use the selection tool to select an area that includes the very first column of the map, and then delete or fill your selection, the changes are not applied to the very first column.

**Comment by BinaryConstruct** [comment]
Could you include a screenshot of the issue in action? Sometimes a picture can be worth hours of testing :). Thanks
