### ISSUE TITLE
v3.7 running according to Task manager, but TEdit isn't appearing on screen

### ISSUE THREAD

**Issue by TerrariaJoePrice** [TEdit/Terraria-Map-Editor#790]
So 5 of the v3.7 versions do not appear on screen when I click on them even though they are running according to the task manager.

The 6th version (TEdit3_BETA_v3.7.16144.1744) appears on screen but immediately crashes, producing the following error message:

Problem Event Name:	APPCRASH
  Application Name:	TEditXna.exe
  Application Version:	3.7.16144.1744
  Application Timestamp:	57434198
  Fault Module Name:	StackHash_c560
  Fault Module Version:	6.0.6002.19623
  Fault Module Timestamp:	56ec4641
  Exception Code:	c0000374
  Exception Offset:	00000000000ad9f7
  OS Version:	6.0.6002.2.2.0.768.3
  Locale ID:	4105
  Additional Information 1:	c560
  Additional Information 2:	d18fe4b0f3842dca7398937ff7f8390e
  Additional Information 3:	f763
  Additional Information 4:	461e397bc638e0a97214a049402a3ce0

Before 1.3.1 I was running v3.5.15196.1223 without any problems. I can still open this version currently, and I can even open all of the worlds. It ends up crashing when I hover any of the 1.3.1 items in the worlds as expected.

**Comment by BinaryConstruct** [comment]
In the log, do you see anything like the issue reported in #751 ?
