### ISSUE TITLE
Beta 3.7 doesn't work

### ISSUE THREAD

**Issue by WasteUs** [TEdit/Terraria-Map-Editor#791]
I can't launch 3.7.16145.0754 ver.
log: https://gist.github.com/WasteUs/8ffff8249a6a12d7d332a1ac25439a1f
There's even no process in Task Manager showing. It seems that programm crashes immediately, although it takes some time for error window to appear. There were an option to debug a programm. I tried it, but it doesn't helped. What's more, I had to use Windows Recovery after that >:(

**Comment by BinaryConstruct** [comment]
#751 still happening with 3.7. Merging with existing issue.
