### ISSUE TITLE
SharpDX.SharpDXException

### ISSUE THREAD

**Issue by BZ98** [TEdit/Terraria-Map-Editor#792]
Problem signature:
  Problem Event Name:	CLR20r3
  Problem Signature 01:	TEditXna.exe
  Problem Signature 02:	3.7.16145.754
  Problem Signature 03:	574408b0
  Problem Signature 04:	SharpDX
  Problem Signature 05:	2.6.3.0
  Problem Signature 06:	5450f8ae
  Problem Signature 07:	a4d
  Problem Signature 08:	14
  Problem Signature 09:	SharpDX.SharpDXException

No idea what the problem is since I unzipped the latest beta ( http://www.binaryconstruct.com/downloads/ ) to a folder in C: named "TEdit", and any and all attempts to open it result in a crash. Completely fails to load NPC textures as per the attached log found in My Documents\My Games\Terraria.
[TEditLog.txt](https://github.com/TEdit/Terraria-Map-Editor/files/286006/TEditLog.txt)
 
Maybe I'm missing an XNA installation version and I'm an idiot? I checked and I do have XNA Framework Redistributable 4.0 installed.

**Comment by BinaryConstruct** [comment]
This is the same #751, so check that thread for some suggestions. This is a known issue and is actively being worked on.

**Comment by DKPGROWTOPIA** [comment]
Yes I know it tell me to read some kind of post but... I did everything and it didnt work . My graphics card is Radeon and all my Dll`s and things are updated I also says in "Problem details" Its some kind of thing called "SharpDX" I searched everywhere and i cant find it Please help

Please dont shut down this issue
