### ISSUE TITLE
TEdit crashing on open

### ISSUE THREAD

**Issue by Tymirr** [TEdit/Terraria-Map-Editor#797]
roblem signature:
  Problem Event Name:	CLR20r3
  Problem Signature 01:	TEditXna.exe
  Problem Signature 02:	3.7.16150.1634
  Problem Signature 03:	574b1a33
  Problem Signature 04:	SharpDX
  Problem Signature 05:	2.6.3.0
  Problem Signature 06:	5450f8ae
  Problem Signature 07:	a4d
  Problem Signature 08:	14
  Problem Signature 09:	SharpDX.SharpDXException
  OS Version:	6.1.7601.2.1.0.256.48
  Locale ID:	1033
  Additional Information 1:	d1bb
  Additional Information 2:	d1bb4ba09f73bbd1119123a7b9bfc54e
  Additional Information 3:	98dc
  Additional Information 4:	98dcd34786f8162d2c6f5a3c6ad90567

**Comment by BinaryConstruct** [comment]
Does your log indicate anything like #751

**Comment by Tymirr** [comment]
as far as I know that's not the issue, when I tried to copy the log here It says it exceeds the character limit I have the latest versions of dx11 and .net and I'm using an amd card

**Comment by enigmaquip** [comment]
Based on your initial posting it does seem to us like it's #751 in your log if you open it, you would see a ton of lines that have this [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved] in them

**Comment by enigmaquip** [comment]
an easy way to post the log would be to goto http://gist.github.com copy and paste the contents of the log and post the link here

**Comment by Tymirr** [comment]
I do see the error issues, but how would I fix this on my card? I dont see a similar fix in am catalyst control center

**Comment by enigmaquip** [comment]
Try following the directions here to update to directx 11.1, some people have had luck with doing that
https://support.microsoft.com/en-us/kb/179113

**Comment by yash852** [comment]
same my Tedit is also crashing on load please help if you can :(
