### ISSUE TITLE
TEdit 3.7 beta will not start.

### ISSUE THREAD

**Issue by CreepKill** [TEdit/Terraria-Map-Editor#800]
I'm running Windows Vista, I downloaded the 3.7 beta, but it won't start whenever I try to run the .exe file. No error message shows up or anything, no crashlog, it just doesn't start. I double-click it and nothing happens.

**Comment by CreepKill** [comment]
I'm willing to bet it's because I'm on vista.

**Comment by CreepKill** [comment]
Well, half of everything you can download on the internet doesn't work for Windows XP or Vista anymore. Google Chrome doesn't support Vista anymore, so I'm stuck with the same version until I get a new computer. Also, you probably should upgrade your computer based on this fact.

**Comment by BinaryConstruct** [comment]
Here are some steps to try - 

* You may need to uninstall, reinstall or force update/reinstall any of the dependencies (.net, directx).
* * https://github.com/TEdit/Terraria-Map-Editor/wiki/Install%20Requirements
* Be sure you extract all the files in the zip to the same folder before running TEditXNA.exe

**Comment by CreepKill** [comment]
I have DirectX 11, but I guess I didn't see Miscrosoft .NET, so I guess I'll try that and see if it works.

**Comment by CreepKill** [comment]
It still didn't turn on. It says it's running in the processes section of the task manager, but nothing under applications and TEditXna.exe hasn't popped up on my screen or anything.

**Comment by CreepKill** [comment]
> 07-07-2016 10:19:44: Starting TEdit 3.7.16152.1806 
07-07-2016 10:19:44: OS: Microsoft Windows NT 6.0.6002 Service Pack 2 
07-07-2016 10:19:44: DirectX 10 unsupported. DirectX 11 or higher is required. 
07-07-2016 10:19:49: Terraria Data Path: C:\Program Files\Steam\steamapps\common\Terraria\Content 
07-07-2016 10:19:54: Creating Undo cache: C:\Users\Robert\AppData\Roaming\TEdit\undo_897412294 

I found the log and checked it, so I'm going to try uninstalling and reinstalling DirectX
