### ISSUE TITLE
Tedit 3.7 deleted some chest and sign contents

### ISSUE THREAD

**Issue by Darkstar0001** [TEdit/Terraria-Map-Editor#803]
After saving a world in Tedit, I noticed that the chests were empty for some reason. Not only that, but they lost their custom names as well. Signs were also blank in the area. Curiously, some chests in that same world still contained their normal items, and the announcement boxes on the map still displayed their normal content.

I initially thought that the deletion had occurred in a localized area, as the first preserved chest I saw was an ocean chest, but there was a chest near the other ocean that was emptied, and a chest halfway between the ocean and spawn that was not emptied. The only common thread I can see is that all most of the emptied chests were on the surface layer, but the announcement boxes were, as well, and they remained unaffected. The announcement boxes were completely enclosed in blocks, however. I wouldn't know if that's important, but figured I might as well mention it.

**Comment by enigmaquip** [comment]
can you upload your world from before tedit saved it somewhere, so I can see if I can recreate the issue. If you look in your save folder you'll see a copy of your world file with the .tedit extension, that should be a good copy of before you saved it in tedit

**Comment by Darkstar0001** [comment]
I already tried that, but the previous version already had lost the chest and sign contents. It might be worth noting that all of the unaffected chests were ones that generated with the worlds their structures were originally copied from, and all of the affected ones were added later via TEdit, as well as most of their contents.

**Comment by enigmaquip** [comment]
Just trying to discount the obvious, you are hitting the save button at the bottom of the chest editor every time you make changes correct? it doesn't save changes to a chest unless you do that

**Comment by Darkstar0001** [comment]
The chests were already saved from a previous session, and their contents remained stable for several saves prior to today.

**Comment by BitFracture** [comment]
Chests are ending up empty for me too. All text labels and all chest contents are lost on sections of the map that are copied and pasted.
