### ISSUE TITLE
TEdit 3.7 'undo' sometimes malfunctions

### ISSUE THREAD

**Issue by Darkstar0001** [TEdit/Terraria-Map-Editor#804]
Sometimes when I hit the undo button, only part of my previous action will be undone, and sometimes even after hitting undo several times it won't be undone at all.

For example, if I draw a bunch of blocks in the air and then immediately hit undo, occasionally some of the blocks will not be deleted.

**Comment by Zwod** [comment]
Ive had the same problem

**Comment by Kojirremer** [comment]
Can confirm this as well, and I'll also add the fact that despite the undoing process going wrong, TEdit will think it was completed succesfully, which means if you try to undo again, it will go for the previous action to the one you are trying to revert. If that change is out of the screen, you will probably undo something you weren't intending to without even noticing.

**Comment by rahlzel** [comment]
Confirmed on 3.8.16218.2109 (.129 on the website)

**Comment by vertX89** [comment]
Same problem on 3.10.17116.2025 (.209 on website)

**Comment by jlyon87** [comment]
Is that a "resolved" closed? :)

**Comment by ZhugeSong** [comment]
I don't think so... It still seems to happen on v4.0.0-beta14 for me.
