### ISSUE TITLE
TEdit 3.7 lack of horizontal block meshing near the edge of the map

### ISSUE THREAD

**Issue by Darkstar0001** [TEdit/Terraria-Map-Editor#806]
In TEdit I see this the image on the left, but in the actual game it appears as on the right.
![tedit world edge](https://cloud.githubusercontent.com/assets/19754911/15807832/e833b5b2-2b2c-11e6-908d-712a60b3127d.jpg)

This only occurs near the edge of the world, as edge of the in-game image is the right edge of the traversable world. However, the abnormality goes all the way up to the top of the map and, presumably, down to the Underworld. This happens on the left side of the map too, but it only affects one column of blocks there. If I remove the blocks in-game and manually replace them, they'll connect normally, but if I save the world in TEdit, they'll be disconnected again. This didn't just happen yesterday, so it isn't the result of a very recent update. It is worth noting that this world is of abnormal size, as tall as a large world, but only about half as long.

**Comment by enigmaquip** [comment]
I don't know how tedit can cause this.... Solid tiles don't have sprite mappings like the tiled images do (ie chests and tables and such) it's all calculated during rendering, there's a good explanation here http://seancode.com/terrafirma/uvs.html 

if you do the manual replace step and save in terraria and then reload in terraria do they remain properly blended?

if so can you save a copy that is showing up right and a copy from tedit that isn't showing up right and share them with me on google drive or dropbox or somewhere..... I'd love to do a diff on the two save files and see what differences there are if any

**Comment by Darkstar0001** [comment]
I just tried what you said and, strangely, the blocks unmeshed after reloading Terraria. Perhaps the problem isn't with TEdit after all. I've never seen this in any of my other worlds, though, so I have no idea what could be causing it.

Should I just close this, then?

**Comment by enigmaquip** [comment]
May be an affect of the odd world sizing, feel free to close
