### ISSUE TITLE
Settle Sand Settles Sandstone Brick

### ISSUE THREAD

**Issue by Zwod** [TEdit/Terraria-Map-Editor#810]
The settle sand plugin settles Sandstone brick, which also refuses to be undone by the undo command.
Warning, making backups before testing advised

**Comment by Darkstar0001** [comment]
Sandstone _brick_ too? I observed it settling hardened sand and sandstone, as well as their corrupted variants, but I never tested it with the bricks. I suspect that it settles everything with 'sand' in its name. It should either settle only sand types subject to gravity, or there should be options on what sand types to settle.

**Comment by enigmaquip** [comment]
yea it's a simple "tile contains sand" kind of check, I'll fix it to only sand tiles here in my next push
