### ISSUE TITLE
Invisible Water Candle sprites on world view

### ISSUE THREAD

**Issue by Kojirremer** [TEdit/Terraria-Map-Editor#814]
Hello. Just wanted to report a small issue that has been around forever:
The water candle sprite does exist when doing a sprite search. However, once placed on a world, they can no longer be seen when zooming in and entering texture view. When placing the mouse cursor over the apparently empty space, you will see "Water Candle" written below as the tile name, and when zooming out until you see the color-coded world, they are shown there as dots.

Thanks for your time.

**Comment by Zwod** [comment]
They are currently under blocks as block no. 49.
I havent ever noticed this until now, but yes, they dont have a texture set for them. They will appear as a blue block if textures are off &/or you are zoomed out.
