### ISSUE TITLE
[Feature Request] More Morphs

### ISSUE THREAD

**Issue by Zwod** [TEdit/Terraria-Map-Editor#815]
Currently there is only morphs for Purity, Corruption, Crimson, And Hallow.
Can we have morphs for other biomes as well?
A jungle and snow morph especially, as they are large biomes and very time consuming to make manually.
Other possible morph biomes like Marble, Granite, and Mushroom would also be very appreciated.

**Comment by enigmaquip** [comment]
and what would be the rules for these morphings? I completely rewrote the morph tool based on the clentaminator because it was a hodge podge mess before with lots of missing tile types.

**Comment by Zwod** [comment]
Well for snow it would be this:

Turn these blocks to Snow(147)-
Dirt (0), Grass (2), CorruptGrass (23), Clay (40), Mud (59), JungGrass (60), MushGrass (70), HalGrass (109), CrimGrass (199)

Turn these blocks to Ice (161):
Stone (1), GMoss (179), YMoss (180), RMoss (181), BMoss (182), PMoss (183),

 Eb Stone(25) into Purple Ice (163)
Pearlstone(117) into Pink Ice (164)
Crimstone (203) into Red Ice (200)

Turn these blocks to Slush (224):
Sand (53), EbonSand (112), PeSeand (116), Silt (123), Crimsand (234)

Delete these blocks: 
CorThorns(32), Vines(52), JungVines (62), JungThorn (69), HalVines (115), CrimVine (205), CrimThorn (352), also whatever block Corruption Vines are, as they are unlisted, see new post.

For Snow Walls(40):
2, 15, 54, 55, 56, 57, 58, 59, 60, 61, 63, 64, 65, 69, 70, 81,  170, 171, 185, 188-207,  212-215

Morph these sprites to their respective snow/ice sprites
All Pots (28) to their Frozen counterpart (also under sprite 28)
All Seeds (82) to shiverthorn seed (also 82)
All PotionPlants(83) to Shiverthorn (83)
All Cave Deco (165) to its frozen counterpart
All Small Deco (185) to its snow/frozen counterpart, depending on if its the dirt or something else.
All 3x2 Decos (187) to their frozen counterparts

Delete these sprites: Grass (3) CorPlants (24), Sunflowr (27), JungGrass (61), Mush (71), TallGrass (73), TallJungl (74), HalPlants (110), TallHalPlants (113), CryShards (129), Moss (184), Crim Grass (201),  DyePlants (227), JungleVeg (227), Pumpkin(254), Hive (444)

**Comment by BinaryConstruct** [comment]
Using #533 for future work on morph tool
