### ISSUE TITLE
Logic Sensor for Player Above dead on placement/pasting

### ISSUE THREAD

**Issue by Kojirremer** [TEdit/Terraria-Map-Editor#817]
Hello again. I noticed recently that when placing the "Logic Sensor (Player Above)" mechanism, it becomes a dead sprite. It's indeed the sensor's sprite, but it does not function. In order to make the sensor work, you have to enter the game, break the sensor then place it back in the very same spot.
Now then, I just noticed that after fixing the sensors this way, once you save a schema and then paste it elsewhere, these sprites once again become dead and once again need to be reinserted.

Haven't tested the other sensors BTW. I just noticed the problem with this particular type.

**Comment by enigmaquip** [comment]
This was reported on the forums as well, all sensors are affected. This is
being worked on
