### ISSUE TITLE
TEdit crashing on startup

### ISSUE THREAD

**Issue by FredericoFP** [TEdit/Terraria-Map-Editor#818]
Im getting an error of unanhandled exeption and i would post it here but less than a quarter of it is already over the maximun characters

**Comment by FredericoFP** [comment]
This is the start of it
rting TEdit 3.7.16159.2314 
06-10-2016 20:18:51: OS: Microsoft Windows NT 6.1.7601 Service Pack 1 
06-10-2016 20:18:52: Terraria Data Path: C:\Program Files\Steam\steamapps\common\Terraria\Content 
06-10-2016 20:18:52: Creating Undo cache: C:\Users\sergio\AppData\Roaming\TEdit\undo_258094685 
06-10-2016 20:18:53: Failed to load texture: Images\NPC_17 
06-10-2016 20:18:53: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
06-10-2016 20:18:53: Failed to load texture: Images\NPC_18 
06-10-2016 20:18:53: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
06-10-2016 20:18:53: Failed to load texture: Images\NPC_19 
06-10-2016 20:18:53: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
06-10-2016 20:18:53: Failed to load texture: Images\NPC_20 
06-10-2016 20:18:53: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
06-10-2016 20:18:53: Failed to load texture: Images\NPC_22 
06-10-2016 20:18:53: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
06-10-2016 20:18:53: Failed to load texture: Images\NPC_37 
06-10-2016 20:18:53: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
06-10-2016 20:18:53: Failed to load texture: Images\NPC_38 
06-10-2016 20:18:53: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
06-10-2016 20:18:53: Failed to load texture: Images\NPC_54 
06-10-2016 20:18:53: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
06-10-2016 20:18:53: Failed to load texture: Images\NPC_107 
06-10-2016 20:18:53: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
06-10-2016 20:18:53: Failed to load texture: Images\NPC_108 
06-10-2016 20:18:53: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
06-10-2016 20:18:53: Failed to load texture: Images\NPC_124 
06-10-2016 20:18:53: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
06-10-2016 20:18:53: Failed to load texture: Images\NPC_142 
06-10-2016 20:18:53: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
06-10-2016 20:18:53: Failed to load texture: Images\NPC_160 
06-10-2016 20:18:53: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
06-10-2016 20:18:53: Failed to load texture: Images\NPC_178 
06-10-2016 20:18:53: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
06-10-2016 20:18:53: Failed to load texture: Images\NPC_207 
06-10-2016 20:18:53: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
06-10-2016 20:18:53: Failed to load texture: Images\NPC_208 
06-10-2016 20:18:53: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
06-10-2016 20:18:53: Failed to load texture: Images\NPC_209 
06-10-2016 20:18:53: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
06-10-2016 20:18:53: Failed to load texture: Images\NPC_227 
06-10-2016 20:18:53: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
06-10-2016 20:18:53: Failed to load texture: Images\NPC_228 
06-10-2016 20:18:53: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
06-10-2016 20:18:53: Failed to load texture: Images\NPC_229 
06-10-2016 20:18:53: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
06-10-2016 20:18:53: Failed to load texture: Images\NPC_353 
06-10-2016 20:18:53: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
06-10-2016 20:18:53: Failed to load texture: Images\NPC_369 
06-10-2016 20:18:53: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
06-10-2016 20:18:53: Failed to load texture: Images\NPC_441 
06-10-2016 20:18:53: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
06-10-2016 20:18:53: Failed to load texture: Images\NPC_422 
06-10-2016 20:18:53: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
06-10-2016 20:18:53: Failed to load texture: Images\NPC_493 
06-10-2016 20:18:53: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
06-10-2016 20:18:53: Failed to load texture: Images\NPC_507 
06-10-2016 20:18:53: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
06-10-2016 20:18:53: Failed to load texture: Images\NPC_517 
06-10-2016 20:18:53: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
06-10-2016 20:18:53: Error - HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown

**Comment by enigmaquip** [comment]
This is a known issue, Keep an eye on #751
