### ISSUE TITLE
TEdit crashes on startup

### ISSUE THREAD

**Issue by UltimateShrekFan** [TEdit/Terraria-Map-Editor#820]
Every time I start it, I get a dialog box saying TEdit has stopped working.
Problem signature:
  Problem Event Name:	CLR20r3
  Problem Signature 01:	TEditXna.exe
  Problem Signature 02:	3.7.16163.517
  Problem Signature 03:	575b9ef8
  Problem Signature 04:	SharpDX
  Problem Signature 05:	2.6.3.0
  Problem Signature 06:	5450f8ae
  Problem Signature 07:	a4d
  Problem Signature 08:	14
  Problem Signature 09:	SharpDX.SharpDXException
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	1033
  Additional Information 1:	4cd7
  Additional Information 2:	4cd78688af36abf1733cc40cdbc1fe2f
  Additional Information 3:	91fe
  Additional Information 4:	91fec2be8ad97edc49053f3ca7b3b07e

**Comment by enigmaquip** [comment]
This is a known issue, Keep an eye on #751
