### ISSUE TITLE
Wine won't run it!

### ISSUE THREAD

**Issue by BJP5544** [TEdit/Terraria-Map-Editor#822]
So I was trying to run it through play on mac but every time I try i get this error ( I get the same one with wine bottler and wine)

(https://cloud.githubusercontent.com/assets/17391667/15987751/03c20cce-2ff2-11e6-9d18-2486567178b8.png)

I would like to know if you could resolve this error so that I could allow mac and linux users everywhere to access you amazing program.

**Comment by enigmaquip** [comment]
make sure you have .Net 4.5 installed https://appdb.winehq.org/objectManager.php?sClass=version&iId=25478
Beyond that I can't be of much help, TEdit was built on .NET and WPF. Mono has has stated they will not port over WPF, so cross compiling isn't possible. The entire GUI is WPF based and would require a rather large code rewrite.

**Comment by BinaryConstruct** [comment]
Wine isn't really supported. VMs are about the only way to get full lunux/mac support at the moment.

**Comment by BJP5544** [comment]
So what does the .net 4.5 do I want to know before I try to use it...
enigmaquip could you tell me?

**Comment by BinaryConstruct** [comment]
.net: https://www.microsoft.com/net
