### ISSUE TITLE
Crashing on Startup

### ISSUE THREAD

**Issue by Sidiax** [TEdit/Terraria-Map-Editor#823]
I can't run Tedit, tried 4 different versions.
The newest one crashes instantly on startup.
This is the log from the older version. I'm using Win7 and got DX11.
[TEditLog.txt](https://github.com/TEdit/Terraria-Map-Editor/files/313334/TEditLog.txt)

**Comment by enigmaquip** [comment]
This is related to #751, please watch there for updates
