### ISSUE TITLE
Couple of missing Blocks/Sprites

### ISSUE THREAD

**Issue by Zwod** [TEdit/Terraria-Map-Editor#825]
Corruption Vines are missing from the blocklist
The other sprites for the 3x2 Jungle plants (233) are missing.

**Comment by Zwod** [comment]
The 3x2 Painting of Holly has no sprite (246)

**Comment by Zwod** [comment]
The Team platforms have been added into the list, (427), (435-439), (also just a note, that red is #427 and futher away is strange)
But only one form of their sprites and not the hammered versions

**Comment by Darkstar0001** [comment]
I would like to add that water candles are invisible on the zoomed-in map view, though they appear as light blue dots on the zoomed-out view. For some strange reason they are considered blocks rather than sprites, despite the peace candle being considered a sprite.

**Comment by Kojirremer** [comment]
All magic drippers are invisible on texture view.
