### ISSUE TITLE
Viewer bug

### ISSUE THREAD

**Issue by Aardvael** [TEdit/Terraria-Map-Editor#831]
I'm having an odd issue since installing TEdit 3.7 on my computer. The main window where you view and make edits to the map isn't rendering at all, instead it's either black or bugs out and mirrors the rest of TEdit when I maximize it.

I'm able to open maps and make edits, but the issue is that I just don't see any of the changes I make.

Le specs are
Windows 8.1 64 bit
i7-5700
GTX 970m, updated drivers
Running DX11 up to date
Updated .net framework as well
![6280135324534e6ca8c8b583b1013f1e](https://cloud.githubusercontent.com/assets/456755/16590413/1a943586-429d-11e6-8150-8bf4ec27566b.png)

```
07-04-2016 18:56:39: Starting TEdit 3.7.16172.2152 
07-04-2016 18:56:39: OS: Microsoft Windows NT 6.2.9200.0 
07-04-2016 18:56:39: Terraria Data Path: D:\Steam\steamapps\common\Terraria\Content 
07-04-2016 18:56:39: Creating Undo cache: C:\Users\[...]\AppData\Roaming\TEdit\undo_956034796 
07-04-2016 19:03:08: Removing old undo file: C:\Users\[...]\AppData\Roaming\TEdit\Big_dick_world.autosave 
07-04-2016 19:03:08: Removing old undo file: C:\Users\[...]\AppData\Roaming\TEdit\Big_dick_world.autosave.TEdit 
07-04-2016 19:03:08: Removing undo cache: C:\Users\[...]\AppData\Roaming\TEdit\undo_956034796 

```

**Comment by BinaryConstruct** [comment]
It appears TEdit doesn't have control of the graphics device, were you running any other applications at the time that use the GPU?  This looks very similar to the #751 issue, but that was not in your log, so it could be something else.

**Comment by Aardvael** [comment]
Huh, so I managed to fix it. Since the machine I'm using is a laptop. It has integrated graphics with the Nvidia GPU.

I normally have it set to always use the Nvidia GPU, I went into my control panel and switched it to choose automatically and the integrated graphics both. And either option works! It looks like in the case of laptops it might be the choice of GPU, or something favors integrated.

**Comment by BinaryConstruct** [comment]
I will add this to troubleshooting steps. Thanks for the update

**Comment by Altimismad** [comment]
It worked for me thanks! <3
