### ISSUE TITLE
Brush outline mode doesn't work

### ISSUE THREAD

**Issue by Silveraen** [TEdit/Terraria-Map-Editor#835]
I have this issue where the outline (room) mode of the brush tool isn't working. I somehow managed to get it to work once on accident but was never able to replicate it. Toggling the outline option on and off does not change the effect of the brush. 

Edit: Actually I may have figured out how it works, it just seems a little weird to me.

**Comment by apemanzilla** [comment]
@Silveraen how the heck does it work?

**Comment by enigmaquip** [comment]
Tool was actually broken, should be fixed with the latest version... Having a tile and wall selected and those tools active should create a box with the tile on the outline and the wall in the middle

**Comment by apemanzilla** [comment]
Ah, alright. I'll try the new version, thanks.
