### ISSUE TITLE
Scroll to zoom out does not work

### ISSUE THREAD

**Issue by The-Jynxed** [TEdit/Terraria-Map-Editor#837]
Zooming out with the scroll wheel does not work.

**Comment by BinaryConstruct** [comment]
Can you please add steps to reproduce the issue, such as what tool was active, if you opened a file or created a new world etc. Thanks

**Comment by The-Jynxed** [comment]
Opened a new file. Does not work in pencil, bucket, sprite, or select. I have not tested for other tools, but I can do so later today.

**Comment by enigmaquip** [comment]
Anything special about your mouse or mouse drivers?

**Comment by The-Jynxed** [comment]
Ah, I'm using an Inferno mouse and mouse driver.

It works with a generic mouse and driver. Oddly, it works on the Inferno mouse when the other mouse is left plugged in.

**Comment by BinaryConstruct** [comment]
Closing as hardware/driver issue.
