### ISSUE TITLE
Version 168 VS 172

### ISSUE THREAD

**Issue by TemporalOnline** [TEdit/Terraria-Map-Editor#841]
![clipboard-2](https://cloud.githubusercontent.com/assets/17304575/17008604/232be440-4ec9-11e6-9783-a8dc75ab165b.png)

TY :)

**Comment by jmiwhite** [comment]
Closed as fix with the latest update?

**Comment by TemporalOnline** [comment]
Oh, it worked, thanks! Only problem is that terraria just pushed another update and now it is v173, I am not home to test now.
