### ISSUE TITLE
TEdit 3.8.16203.0354 Unhandled exception on start up.

### ISSUE THREAD

**Issue by Themigratingcoconut** [TEdit/Terraria-Map-Editor#846]
[TEditLog.txt](https://github.com/TEdit/Terraria-Map-Editor/files/377059/TEditLog.txt)
I have the latest version of .Net, Nvidia drivers, and Terreria itself. I tried to start TEdit in multiple Hard drives while running as admin and got same result. 

Thanks in advance for any help c:

**Comment by jmiwhite** [comment]
Check out https://github.com/TEdit/Terraria-Map-Editor/issues/751 - this may or may not be a dupe but the advice there might help you out.

**Comment by Themigratingcoconut** [comment]
Thanks! Installing that windows update manually fixed the problem, that is a very useful link you got there, I hop others see it.
