### ISSUE TITLE
Unable to check version

### ISSUE THREAD

**Issue by DrSkelington** [TEdit/Terraria-Map-Editor#850]
Before update 1.3.2 the TEdit program worked just fine. Now, however, the program, no matter what version I attempt to use, only says that it is "Unable to check version". If a solution exists I would love to know how to fix this issue.

**Comment by DrSkelington** [comment]
Before update 1.3.2 the TEdit program worked just fine. Now, however, the program, no matter what version I attempt to use, only says that it is "Unable to check version". If a solution exists I would love to know how to fix this issue.

**Comment by Darkstar0001** [comment]
I am also having this problem.

**Comment by DrSkelington** [comment]
@Darkstar0001 Just as a heads up, I did some experimenting with the TEdit program and, as long as you have the most recent one [TEdit3_BETA_v3.8.16205.106.zip], you can still work with your maps. I would just be extra careful with it and don't go all out. Hopefully there is a fix so we can feel somewhat safer about this.

**Comment by DrSkelington** [comment]
Also it seems that if you copy a structure the sprites do not come with.

**Comment by enigmaquip** [comment]
Update check fixed
