### ISSUE TITLE
Unhandled Exception while starting TEdit.

### ISSUE THREAD

**Issue by melhior909** [TEdit/Terraria-Map-Editor#851]
07-23-2016 15:15:53: Starting TEdit 3.8.16204.0124 
07-23-2016 15:15:53: OS: Microsoft Windows NT 6.1.7601 Service Pack 1 
07-23-2016 15:15:54: Terraria Data Path: D:\Programy\Steam\steamapps\common\Terraria\Content 
07-23-2016 15:15:54: Creating Undo cache: C:\Users\DOM\AppData\Roaming\TEdit\undo_570598852 
07-23-2016 15:16:00: Failed to load texture: Images\NPC_17 
07-23-2016 15:16:00: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
07-23-2016 15:16:00: Failed to load texture: Images\NPC_18 
07-23-2016 15:16:00: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
07-23-2016 15:16:00: Failed to load texture: Images\NPC_19 
07-23-2016 15:16:00: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
07-23-2016 15:16:00: Failed to load texture: Images\NPC_20 
07-23-2016 15:16:00: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
07-23-2016 15:16:00: Failed to load texture: Images\NPC_22 
07-23-2016 15:16:00: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
07-23-2016 15:16:00: Failed to load texture: Images\NPC_37 
07-23-2016 15:16:00: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
07-23-2016 15:16:00: Failed to load texture: Images\NPC_38 
07-23-2016 15:16:00: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
07-23-2016 15:16:00: Failed to load texture: Images\NPC_54 
07-23-2016 15:16:00: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
07-23-2016 15:16:00: Failed to load texture: Images\NPC_107 
07-23-2016 15:16:00: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
07-23-2016 15:16:00: Failed to load texture: Images\NPC_108 
07-23-2016 15:16:00: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
07-23-2016 15:16:00: Failed to load texture: Images\NPC_124 
07-23-2016 15:16:00: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
07-23-2016 15:16:00: Failed to load texture: Images\NPC_142 
07-23-2016 15:16:00: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
07-23-2016 15:16:00: Failed to load texture: Images\NPC_160 
07-23-2016 15:16:00: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
07-23-2016 15:16:00: Failed to load texture: Images\NPC_178 
07-23-2016 15:16:00: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
07-23-2016 15:16:00: Failed to load texture: Images\NPC_207 
07-23-2016 15:16:00: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
07-23-2016 15:16:00: Failed to load texture: Images\NPC_208 
07-23-2016 15:16:00: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
07-23-2016 15:16:00: Failed to load texture: Images\NPC_209 
07-23-2016 15:16:00: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
07-23-2016 15:16:00: Failed to load texture: Images\NPC_227 
07-23-2016 15:16:00: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
07-23-2016 15:16:00: Failed to load texture: Images\NPC_228 
07-23-2016 15:16:00: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
07-23-2016 15:16:00: Failed to load texture: Images\NPC_229 
07-23-2016 15:16:00: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
07-23-2016 15:16:00: Failed to load texture: Images\NPC_353 
07-23-2016 15:16:00: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
07-23-2016 15:16:00: Failed to load texture: Images\NPC_369 
07-23-2016 15:16:00: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
07-23-2016 15:16:00: Failed to load texture: Images\NPC_441 
07-23-2016 15:16:00: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
07-23-2016 15:16:00: Failed to load texture: Images\NPC_422 
07-23-2016 15:16:00: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
07-23-2016 15:16:00: Failed to load texture: Images\NPC_493 
07-23-2016 15:16:00: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
07-23-2016 15:16:00: Failed to load texture: Images\NPC_507 
07-23-2016 15:16:00: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
07-23-2016 15:16:00: Failed to load texture: Images\NPC_517 
07-23-2016 15:16:00: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown 
07-23-2016 15:16:00: Error - HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown
   w SharpDX.Result.CheckError()
   w SharpDX.Direct3D11.Device.CreateTexture2D(Texture2DDescription& descRef, DataBox[] initialDataRef, Texture2D texture2DOut)
   w Microsoft.Xna.Framework.Graphics.Texture2D.CreateTexture()
   w Microsoft.Xna.Framework.Graphics.Texture2D..ctor(GraphicsDevice graphicsDevice, Int32 width, Int32 height, Boolean mipmap, SurfaceFormat format, SurfaceType type, Boolean shared, Int32 arraySize)
   w TEditXna.View.WorldRenderXna.LoadTerrariaTextures(GraphicsDeviceEventArgs e) w c:\projects\terraria-map-editor\TEditXna\View\WorldRenderXna.xaml.cs:wiersz 238 
07-23-2016 15:16:00: Error - HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown

**Comment by BinaryConstruct** [comment]
#751
