### ISSUE TITLE
Error reading world version 73

### ISSUE THREAD

**Issue by michael-ts** [TEdit/Terraria-Map-Editor#857]
Trying to read the world file from my Android device, I get this error:

> ---------------------------
> World File Error
> ---------------------------
> There was an error reading the world file. This is usually caused by a corrupt save file or a world version newer than supported.
> 
> TEdit v3.8.16212.1916
> 
> TEdit Max World: 173    Current World: 73
> 
> Do you wish to force it to load anyway?
> 
> WARNING: This may have unexpected results including corrupt world files and program crashes.
> 
> The error is :
> 
> Array dimensions exceeded supported range.
> 
> System.OutOfMemoryException: Array dimensions exceeded supported range.
> 
>    at TEditXNA.Terraria.World.LoadV1(BinaryReader reader, String filename, World w) in c:\projects\terraria-map-editor\TEditXna\Terraria\World.FileV1.cs:line 487
> 
>    at TEditXNA.Terraria.World.LoadWorld(String filename) in c:\projects\terraria-map-editor\TEditXna\Terraria\World.cs:line 128
> 
> 
> ---------------------------
> Yes   No   
> ---------------------------
> 

If I say yes, the world name is junk and nothing else is displayed.

**Comment by enigmaquip** [comment]
TEdit only works with the pc version.

**Comment by michael-ts** [comment]
@enigmaquip  Any plans to support the mobile versions in the future?  I found a utility which appears to successfully decrypt and encrypt the world file, but apparently this is not enough as it still errors out when an arithmetic overflow.  I assume the file format is different, but haven't had much luck finding documentation on the format for mobile.

**Comment by BinaryConstruct** [comment]
The PC version is mod friendly and is currently the only planned platform to be supported. 

If at some point in the future the developers of Terraria decide to make mobile or console platforms mod friendly, we can reevaluate our position of PC only.

**Comment by tomek-i** [comment]
Reading the iOS map data is fine.
Saving will corrupt it on mobile devices, I fixed this in my pull request and it is working on iOS mobile.
