### ISSUE TITLE
Weighted pressure plates switching after loading a map in Terraria

### ISSUE THREAD

**Issue by Tutajkk** [TEdit/Terraria-Map-Editor#858]
Not sure if it's a TEdit or Terraria bug, but it's quite annoying. The last time I used TEdit was pre 1.3.2 there were no problems then.
Today when I used TEdit, then loaded my map in Terraria, I noticed all my mechanisms that are wired into a weighted pressure plate are switched reversed. Actuators, lamps and logic switches that all should be only On while standing on a plate, are now On while not standing on them.
Basically, all weighted pressure plates switches once when loading a map, it's also possible to hear the switch noise if they are next to the spawn point. But the thing is, it only happens if I do anything in TEdit and save, then load the map in Terraria.
I tested it quite some times, saving a map in Terraria, then quit, relaunch, everything is fine. If I open TEdit, not even editing anything, just saving, then it happens. Tried it with 3.8.16212.114 and 3.8.16207.112

**Comment by enigmaquip** [comment]
That was my bad, when I added the changes for 1.3.2 I misinterpreted what that info in the save file was. Should be fixed
