### ISSUE TITLE
Modify application version number to use AppVeyor build number

### ISSUE THREAD

**Issue by rahlzel** [TEdit/Terraria-Map-Editor#867]
![1](http://i.imgur.com/VwPyVdb.png)
![2](http://i.imgur.com/EjqzryQ.png)

Unless I'm missing something, none of your users know if their current version is the latest one, which is a pretty major issue if you're wanting people to test and report errors.

On a side note, thanks a lot for keeping this up-to-date. You've done an awesome job with it.

**Comment by enigmaquip** [comment]
That is going to be a great question for @BinaryConstruct to answer as that's in the way appveyor builds the app.
