### ISSUE TITLE
cant install

### ISSUE THREAD

**Issue by Fraxture** [TEdit/Terraria-Map-Editor#868]
[TEditLog.txt](https://github.com/TEdit/Terraria-Map-Editor/files/405974/TEditLog.txt)
Cant install it rip :(

**Comment by Darkstar0001** [comment]
But... you don't have to install it. It should just run if you click on the executable. I cursory glance of the log suggests that TEdit is having trouble finding/accessing your Terraria files, but I could be wrong.

**Comment by enigmaquip** [comment]
You're using an old version (3.5)
Do you continue to get this error in one of the 3.7 versions?

**Comment by Fraxture** [comment]
Terraria is in its normal steam download location but i do use a second hard drive for everything because my main one is a small solid state. And yes i do get the error in the newer versions

**Comment by enigmaquip** [comment]
is this what you get when you try to run it? when you try to open a map?

**Comment by Fraxture** [comment]
It happens the moment i try to open the .exe

**Comment by BinaryConstruct** [comment]
Please download and extract the zip file from the releases page and follow all the pre-requisite steps on the wiki.
