### ISSUE TITLE
Always Crashes on startup

### ISSUE THREAD

**Issue by Venomalix** [TEdit/Terraria-Map-Editor#872]
[TEditLog.txt](https://github.com/TEdit/Terraria-Map-Editor/files/414471/TEditLog.txt)

**Comment by enigmaquip** [comment]
Per the Instructions in the Issue when you created it

If your log includes ***DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved***
This is a known issue, do not create a new issue, please add your comments to #751
People have had the most luck in Windows 7 with updating to DirectX 11.1
This is found in windows update in the optional updates section or by
following directions here https://support.microsoft.com/en-us/kb/179113
