### ISSUE TITLE
TEdit.exe stopped working

### ISSUE THREAD

**Issue by Vanilla727** [TEdit/Terraria-Map-Editor#873]
title, whenever i try to run TEdit, it crashes and it says it stopped working, help plx

**Comment by enigmaquip** [comment]
please attach your teditlog.txt

**Comment by Vanilla727** [comment]
i dont have anything like that lol

**Comment by enigmaquip** [comment]
yes you do, it's created on startup of the app.... check My Documents/my games/Terraria
