### ISSUE TITLE
Hey so Tedit started crashing after I reinstalled Terraria. Here is the log.

### ISSUE THREAD

**Issue by TheShowManV2** [TEdit/Terraria-Map-Editor#877]
[TEditLog.txt](https://github.com/TEdit/Terraria-Map-Editor/files/416985/TEditLog.txt)

**Comment by TheShowManV2** [comment]
IS dump a thing on github?

**Comment by enigmaquip** [comment]
you are extracting all the files from the zip before running it yes?

**Comment by TheShowManV2** [comment]
Yes

**Comment by enigmaquip** [comment]
Do one of the earlier builds of 3.8 work? Or do they all crash

**Comment by TheShowManV2** [comment]
I've resolved the problem myself dw! and I'm not not sure I didn't test. xD
