### ISSUE TITLE
TEdit.exe has stopped working

### ISSUE THREAD

**Issue by cxemLINk** [TEdit/Terraria-Map-Editor#879]
It seems that the problem is with DirectX or something because there is SharpDX.SharpDXException.
There is no log in the program folder (no teditlog.txt file).
Here is the dump

*trying to upload*

*github rejects file because its to big*

Well then, I'll upload it to Google Drive

Link: https://drive.google.com/open?id=0Bx3OxoB2ebAZdkt4dWVVY1hGWkk

**Comment by enigmaquip** [comment]
Log file is in my docs/my games/terraria
