### ISSUE TITLE
T edit not start  

### ISSUE THREAD

**Issue by nipom** [TEdit/Terraria-Map-Editor#880]
**Before you submit an issue please read**
If you get an unhandled exception, please check your log before posting
If your log includes *DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved*
This is a known issue, do not create a new issue, please add your comments to #751
People have had the most luck in Windows 7 with updating to DirectX 11.1
This is found in windows update in the optional updates section or by
following directions here https://support.microsoft.com/en-us/kb/179113

**Comment by nipom** [comment]
08-15-2016 19:05:36: Error - HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown
   em SharpDX.Result.CheckError()
   em SharpDX.DXGI.SwapChain.ResizeBuffers(Int32 bufferCount, Int32 width, Int32 height, Format newFormat, SwapChainFlags swapChainFlags)
   em Microsoft.Xna.Framework.Graphics.GraphicsDevice.CreateSizeDependentResources(Boolean useFullscreenParameter)
   em Microsoft.Xna.Framework.Graphics.GraphicsDevice.Reset(PresentationParameters presentationParameters)
   em TEditXna.View.WorldRenderXna.xnaViewport_SizeChanged(Object sender, SizeChangedEventArgs e) na c:\projects\terraria-map-editor\TEditXna\View\WorldRenderXna.xaml.cs:linha 1972
   em System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   em System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   em System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   em System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   em System.Windows.FrameworkElement.OnRenderSizeChanged(SizeChangedInfo sizeInfo)
   em System.Windows.ContextLayoutManager.fireSizeChangedEvents()
   em System.Windows.ContextLayoutManager.UpdateLayout()
   em System.Windows.Interop.HwndSource.SetLayoutSize()
   em System.Windows.Interop.HwndSource.set_RootVisualInternal(Visual value)
   em System.Windows.Window.SetRootVisual()
   em System.Windows.Window.SetRootVisualAndUpdateSTC()
   em System.Windows.Window.SetupInitialState(Double requestedTop, Double requestedLeft, Double requestedWidth, Double requestedHeight)
   em System.Windows.Window.CreateSourceWindow(Boolean duringShow)
   em System.Windows.Window.ShowHelper(Object booleanBox)
   em System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   em System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   em System.Windows.Threading.DispatcherOperation.InvokeImpl()
   em System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   em System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   em System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   em MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   em System.Windows.Threading.DispatcherOperation.Invoke()
   em System.Windows.Threading.Dispatcher.ProcessQueue()
   em System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   em MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   em MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   em System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   em System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   em System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   em MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   em MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   em System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   em System.Windows.Application.RunDispatcher(Object ignore)
   em System.Windows.Application.RunInternal(Window window)
   em TEditXna.App.Main() na c:\projects\terraria-map-editor\TEditXna\obj\Release\App.g.cs:linha 0

**Comment by BinaryConstruct** [comment]
#751
