### ISSUE TITLE
World File error

### ISSUE THREAD

**Issue by maddock34** [TEdit/Terraria-Map-Editor#883]
Starts fine, says it's unable to check for updates, try to load world and it gives me this error: https://s3.postimg.org/l4o3pch4z/Terraria_error.png

Contents of the log file:
08-19-2016 19:41: Starting TEdit 3.5.15047.30 
08-19-2016 19:41: OS: Microsoft Windows NT 6.1.7601 Service Pack 1 
08-19-2016 19:41: .Net >= 4.0 
08-19-2016 19:41: XNA 4.0 
08-19-2016 19:41: Terraria Data Path: c:/program files (x86)/steam\steamapps\common\terraria\Content 
08-19-2016 19:41: Creating Undo cache: C:\Users\RaptorZ\AppData\Roaming\TEdit\undo_10508820 
08-19-2016 19:41: Error - This method does not accept null for this parameter.
Parameter name: data
   at Microsoft.Xna.Framework.Graphics.Texture2D.CopyData[T](Int32 level, Nullable`1 rect, T[] data, Int32 startIndex, Int32 elementCount, UInt32 options, Boolean isSetting)
   at Microsoft.Xna.Framework.Graphics.Texture2D.GetData[T](Int32 level, Nullable`1 rect, T[] data, Int32 startIndex, Int32 elementCount)
   at TEditXna.View.WorldRenderXna.LoadTerrariaTextures(GraphicsDeviceEventArgs e) 
08-19-2016 19:41: Error - Arithmetic operation resulted in an overflow.
   at TEditXna.View.WorldRenderXna.LoadTerrariaTextures(GraphicsDeviceEventArgs e) 
08-19-2016 19:42: Removing old undo cache: C:\Users\RaptorZ\AppData\Roaming\TEdit\undo_945432833 
08-19-2016 19:42: Removing undo cache: C:\Users\RaptorZ\AppData\Roaming\TEdit\undo_10508820

I have followed the instillation requirements, I do have Dx11 (checked using dxdiag) and have installed by extracting the msi and repaired the currently instillation using the msi. I'm using the most recent stable release. Using Windows 7

**Comment by enigmaquip** [comment]
Are you trying to open a current world file with an old version of TEdit? v3.5 only supports up to a 1.2 file

**Comment by maddock34** [comment]
Oh right. I think I'm on 1.3 (which I guess is the current Terraria version). Does the most recent beta release support 1.3?

**Comment by maddock34** [comment]
Yes it does. Disregard this ticket. Because I'm an idiot that doesn't read, I didn't see the supported version thing at the top

**Comment by enigmaquip** [comment]
Yes, the download page tells you what TEdit ver corresponds to which
Terraria
