### ISSUE TITLE
32-bit version of Windows is not supported?

### ISSUE THREAD

**Issue by mistzzt** [TEdit/Terraria-Map-Editor#885]
Release versions of TEdit are not able to run upon 32-bit Windows, while I have not found any information about that.

I wonder if compiling TEdit with `Platform="x86"` solve this.

**Comment by BinaryConstruct** [comment]
The powershell command that is performing the build is using AnyCPU, and this should be compatible with x86/x64. However, some of the library dependencies such as SharpDX or MonoGame may require a platform. You should be able to build the project yourself if you clone the git repository and run the build_beta.bat script.

``` ps1
Write-Host "Building Solution..."
$msbuild="C:\Windows\Microsoft.NET\Framework\v4.0.30319\MSBuild.exe"
$nuget=".\.nuget\nuget.exe"

& $nuget ('restore', '.\TEditNoInstaller.sln')
& $msbuild ('.\TEditNoInstaller.sln', '/p:Configuration=Release;Platform="Any CPU"', '/verbosity:m')
```
