### ISSUE TITLE
Black Map

### ISSUE THREAD

**Issue by ZDGamer02** [TEdit/Terraria-Map-Editor#886]
![image](https://cloud.githubusercontent.com/assets/21228463/17947791/2875312c-6a1c-11e6-8247-7e25cc58e8ab.png)
 Whenever I load up a world, it shows a black screen where you would see and change the world.  I have tried changing versions and using compatibility mode, but nothing has worked so far.

**Comment by enigmaquip** [comment]
Check your teditlog file in the Terraria save folder and see what it says

**Comment by thatsweetness** [comment]
i have the same problem

**Comment by BinaryConstruct** [comment]
See if following any of the comments in #751 helps.
