### ISSUE TITLE
Failure to paste wire/broken undo/wrong fence name/paint does not show/minimap positioning

### ISSUE THREAD

**Issue by allelsewastaken** [TEdit/Terraria-Map-Editor#888]
Version: TEdit3_BETA_v3.8.16233.135

I have had random but contiguous segments of wire fail to copy/paste, and if pasted over existing blocks the blocks under the wire sometimes are deleted.

The undo command sometimes skips the last few steps and undoes actions from much earlier.

The lead fence is misnamed as metal fence.

When blocks or walls are painted it does not show in the app. When you hover over a cell the info bar at the bottom correctly indicates the presence and color of paint, but the change in color is not displayed visually.

When using the brush tool the minimap obscures part of the options bar at the top of the screen.

**Comment by enigmaquip** [comment]
check latest version for wiring now with the clipboard, yellow wire was missing
pasting over existing blocks would change the block to whatever was copied unless you had 'Paste Tile' unchecked

undo command is a known reported issue, don't know that anyone's working on it though

lead fence was fixed, name was never changed after the 1.2.4 update that changed that wall piece

Paint rendering when zoomed in to texture level is not currently a feature in TEdit 

I reverted my gui changes as I didn't feel they accomplished anything, the options bar is now full width again

**Comment by allelsewastaken** [comment]
Thank you enigmaquip. I can confirm pasting wire appears to work now.

I am still confused about pasting wire replacing existing blocks. In my mind, if I past wire over existing blocks, with "paste empty tiles" deselected, it should just add the wire over the existing block. As it is now, it deletes the blocks before adding the wire? I am probably just really misunderstanding the process, but that seems counter intuitive to me since wire is not the same 'layer' as dirt or stone.

Understood about the undo command. A minor annoyance, easily worked around... (It is VERY broken though :D )

Lead fence confirmed fixed.

I understand about showing paint at texture resolution. It would be a very nice feature to add at some point though.

Thank you for the GUI change. It works much better IMHO.

**Comment by enigmaquip** [comment]
You can see my convo about paint rendering here, it really is on my todo list.... one day :-)

http://forums.terraria.org/index.php?threads/tedit-terraria-map-editor.43822/page-5#post-1051069

I get where you're coming from with 'empty tiles', looks like it was designed around a completely blank tile (nothing in it whatsoever). The idea being to allow odd shaped designs not clearing out a square section. Changing it to not include wiring in the check is kind of a damned if you do damned if you don't kind of situation though
