### ISSUE TITLE
I can't open edited worlds.

### ISSUE THREAD

**Issue by NoopOfficial** [TEdit/Terraria-Map-Editor#889]
That's a new issue. I edited my server map with TEdit and now fails to load. All my server is dead. He had a lot of people playing. Now I lost all my 1 month work. I'm using Terraria 1.3.2.1 and TEdit 3.5

**Comment by NoopOfficial** [comment]
@BinaryConstruct please help.

**Comment by BinaryConstruct** [comment]
I would suggest loading the TEdit backup, your manual backups or the backup
made by Terraria.

**Comment by enigmaquip** [comment]
TEdit 3.5 wont open a 1.3 game file. You need 3.8 as stated on the download page
![image](https://cloud.githubusercontent.com/assets/6134440/18036324/82303382-6d24-11e6-8e91-21e41e1f366e.png)

**Comment by NoopOfficial** [comment]
The Terraria Backups are deleted by TEdit. And from where i can install TEdit 3.8 ??

**Comment by enigmaquip** [comment]
Terraria backups are not deleted by TEdit.... there should be 3 files in your game folder
.wld is the normal world file
.wld.bak is the backup file created by Terraria
.wld.Tedit is the backup file create by TEdit when you save a map

TEdit is available at http://www.binaryconstruct.com/downloads/

**Comment by NoopOfficial** [comment]
Problem fixed. Installed TEdit 3.8 then open the file then save the file and done. Thanks so much.
