### ISSUE TITLE
[Feature] Cleanse Tool

### ISSUE THREAD

**Issue by rahlzel** [TEdit/Terraria-Map-Editor#890]
A tool like the Brush tool that allows you to alter the size of the area. Or, have a checkbox inside the Brush Tool and Pencil Tool options beneath "Extras" or "Paint" - "Cleanse area".

When clicking on the map with the tool, it will turn crimson/corruption/hallow blocks, sand, grass, vines - everything - back to normal, unaltered green grass and stone. Somewhat like the in-game Clentaminator does with green liquid.

**Comment by enigmaquip** [comment]
Are you mayhaps thinking of the morph tool with the purify option? :-)

**Comment by rahlzel** [comment]
Wow. Been using this program for the last few weeks and never saw that for some reason. Oops. Thanks!
