### ISSUE TITLE
.

### ISSUE THREAD

**Issue by Lampshade1234** [TEdit/Terraria-Map-Editor#895]

**Comment by enigmaquip** [comment]
When does that error occur? What were you doing at the time? Trying to open tedit? trying to open a map? Why are you using such an old version of tedit?

**Comment by Lampshade1234** [comment]
opening tedit-

**Comment by enigmaquip** [comment]
make sure you have the lastest versions of .net and directx
https://github.com/TEdit/Terraria-Map-Editor/wiki/Install%20Requirements
and try the latest version of tedit, 3.3 is no longer supported

**Comment by Lampshade1234** [comment]
ok
