### ISSUE TITLE
Liquid Masks

### ISSUE THREAD

**Issue by SirUmnei** [TEdit/Terraria-Map-Editor#900]
Hey. I just got back into Terraria to play the new update (with some of the new mods), and I was wondering if there could be some way of mod compatibility for TEdit (in the form that modded blocks/wall at least appear and aren't invisible/non-existant). I play a heavily modded world, and I wanted to make some heavy edits in the underground, but I can't do it without messing up some of the mod terrain generation. Maybe if there was a way for TEdit to read the mod tiles and add them to the tile list? Or just created an "unknown" block for when it doesn't know what block it is?

As a secondary Request: Can we get Liquid Masks?

**Comment by BinaryConstruct** [comment]
Mod world files may a different structure than the base game, and you would have to write file loaders for every version of every modified client. This is beyond the scope of TEdit. However, liquid masks will be added to the todo list.

**Comment by BinaryConstruct** [comment]
Now part of #1274
