### ISSUE TITLE
Detect installed Terraria version add to startup log

### ISSUE THREAD

**Issue by BinaryConstruct** [TEdit/Terraria-Map-Editor#903]
Add this check to 

https://github.com/TEdit/Terraria-Map-Editor/blob/master/TEditXna/DependencyChecker.cs

e.g.

``` csharp
 public static string GetTerrariaVersion()
 {
    string version = string.Empty;
    try 
    {
       string terrariaExePath = Directory.GetParent(PathToContent).Parent.Fullname + "\\Terraria.exe"
       version = FileVersionInfo.GetVersionInfo().FileVersion
    }
    catch () { /*no message*/}
    return version;
}
```

**Comment by enigmaquip** [comment]
file version is called here
https://github.com/TEdit/Terraria-Map-Editor/blob/master/TEditXna/ErrorLogging.cs#L85
and is added to the log on startup here
https://github.com/TEdit/Terraria-Map-Editor/blob/master/TEditXna/App.xaml.cs#L30
