### ISSUE TITLE
TEdit wont open again, it has worked before but now it wont ever open

### ISSUE THREAD

**Issue by ES9ASANT** [TEdit/Terraria-Map-Editor#904]
## Before you submit an issue, please read
- If you get an unhandled exception, please _**check your log before posting**_.
- If your log includes _**DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved**_
  - This is a known issue, do not create a new issue, please add your comments to #751
  - People have had the most luck in Windows 7 with updating to DirectX 11.1
    This is found in windows update in the optional updates section or by
    following directions here 
  - https://support.microsoft.com/en-us/kb/179113
- Please fill out the questions below
- Instead of copy/pasting text you can attach the entire log file.
- If your world file is less than 25MB, you can attach it as well.

**Comment by BinaryConstruct** [comment]
Please fill out the questionnaire.

**Comment by PurplePoisom** [comment]
Hello, I'm having a problem when I click on the file TEditXna.exe does not start anything, no matter how many times I do it (I'm using windows 10 Pro with Directx updated and I'm sorry for any spelling error because I do not know how to write In English and I'm using a translator)

**Comment by Omio** [comment]
Can you attach the crash log? It should be named "TEditLog.txt". You can find it in the same folder TEdit is in.
