### ISSUE TITLE
Different ShadowOrbSmashed and Chests count and data

### ISSUE THREAD

**Issue by smujaddid** [TEdit/Terraria-Map-Editor#905]
I loaded my world (v176) using TEdit v3.8.16272.143 then saved it to a new file without editing anything.
But, the new file seems to have different value for ShadowOrbSmashed byte and Chests count and data.
My original world only has 483 total chest, but the new file has 491 total chest.

Is this intended?

I can provide my world file if you need to inspect it.

**Comment by smujaddid** [comment]
Looks like TEdit saved extra one chest for every dresser in a map. In the map, there are 8 naturally placed dresser. However, TEdit read the top-right corner of the dresser as a new chest, so that would make an extra chest for every dresser. I think TEdit always consider the 4 tile block in the left as dresser, and the 2 tile block in the right as different chest.

When I clicked the top-right or bottom-right of the dresser in TEdit, it shows as an empty chest type, but the top-left, top-mid, bottom-left, and bottom-mid shows correctly as a dresser chest type.

**Comment by enigmaquip** [comment]
all dressers should be chests, but it sounds like it's a little buggy, I'll look into it

**Comment by enigmaquip** [comment]
found the bug causing dresser issues, and I think I might have fixed the orbs count as well
