### ISSUE TITLE
Possibly missing flag related to mechanical bosses

### ISSUE THREAD

**Issue by Kojirremer** [TEdit/Terraria-Map-Editor#907]
Terraria v.1.3.3.3

I've noticed for a while that after checking all flags on World Properties and making sure that the ones relating to mechanical bosses were also properly checked, the game still won't recognize them as beaten. No steampunker and no life fruits.
I initially though it was a server issue, but just now tried killing the mech bosses (note that, as I said, their flag on World Properties was already checked) and as soon as I did the steampunker arrived as if on queue.

**Comment by enigmaquip** [comment]
There is an extra flag that doesn't show in the world properties tab, you are correct, it should be fixed in the next update so that flag will be autoset when any mech is set
