### ISSUE TITLE
v3.8.16277.145 Error reading world file

### ISSUE THREAD

**Issue by Myonmon** [TEdit/Terraria-Map-Editor#910]
## Before you submit an issue, please read
- If you get an unhandled exception, please _**check your log before posting**_.
- If your log includes _**DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved**_
  - This is a known issue, do not create a new issue, please add your comments to #751
  - People have had the most luck in Windows 7 with updating to DirectX 11.1
    This is found in windows update in the optional updates section or by
    following directions here 
  - https://support.microsoft.com/en-us/kb/179113
- Please fill out the questions below
- Instead of copy/pasting text you can attach the entire log file.
- If your world file is less than 25MB, you can attach it as well.
## What were you doing when the issue occured?

...Saving, then saving to a backup, then closing TEdit, then moving all the past .wld.[number].tedit files except the latest into a seperate folder to tidy up, then failing to launch the .wld file in terraria due to lack of .wld.bak, then trying to open the .wld file in TEdit again
## Can you reproduce the issue?

...Every time I try to load up either the .wld file or the backup .wld file that is stored in a seperate folder, both have the same issue
## What version of Terraria are you using?

[Terraria]1.3.3.3, [TEdit]  TEdit3_BETA_v3.8.16277.145
## Post relevant contents of log or attach log file _**(very important)**_:

https://github.com/TEdit/Terraria-Map-Editor/files/540895/TEditLog.txt

**Comment by enigmaquip** [comment]
can you attach your world file?

**Comment by BinaryConstruct** [comment]
Closed - no response
