### ISSUE TITLE
[Feature Request] Plugin: "Clean Crimson/Corruption/Hallow"?

### ISSUE THREAD

**Issue by Omio** [TEdit/Terraria-Map-Editor#913]
Alright, so it's an admitted pain to try to clean out all the Crimson, Corruption, and Hallow in a world.

Steps as it currently stands:

Ctrl+A, Replace:
- Crimson Grass Block -> Grass Block
- Crimstone Wall -> Stone Wall
- Crimstone Block -> Stone Block
- Crimson Wall 1 -> Dirt Wall 1
- Red Ice Block -> Ice Block
- Crimson Wall 2 -> Dirt Wall 2
- Crimsand Block -> Sand Block
- Crimson Wall 3 -> Dirt Wall 3
- Crimsandstone Block -> Sandstone Block
- Crimson Wall 4 -> Dirt Wall 4
- Crimson Thorns -> Thorns
- Crimson Jungle Wall -> Jungle Wall

...if you get the picture by now, you'll see where I'm headed, but there's a few more things:
Sprite 201, and a couple of others, generated by Hallow, Crimson, and Corruption, also need to get curbed, lest the spread starts again.

Having a plugin for that, even if it's just a plugin that uses the Replace mechanic a hundred times, would be amazingly useful for anyone trying to clear out Crimson, Hallow, or Corruption with TEdit.

**Comment by enigmaquip** [comment]
Try the morph tool, replaces everything that will spread

**Comment by Omio** [comment]
Well, that's progress. Not what I was exactly looking for (not very helpful with large worlds), but it's something functions. Thanks much. =D

**Comment by shadowsyllvet** [comment]
1. Select the area you want with the selection tool
2. Swap to the morph tool
3. Increase the brush size to the maximum
4. Center your cursor inside your selected area
5. Click as needed

Generally if you click outside of the selected area nothing will happen, but occasionally it will affect some unselected tiles. If the click is inside the selection area however, the only affected tiles will be the ones selected, even if the brush size exceeds the selection size. Makes the fill tool so much more useful as well.

**Comment by Omio** [comment]
After speaking with an IRL friend that also uses TEdit, and isn't quite as tech-savvy (and also lags), I have to add the sentiment that the feature I've proposed would disallow the possibility of "missing a sliver", especially when larger areas are concerned.

**Comment by BinaryConstruct** [comment]
Using #533 for future work on morph tool
