### ISSUE TITLE
when i try to analyze the world it crashes + it cant check the worlds ver 

### ISSUE THREAD

**Issue by deathishere420** [TEdit/Terraria-Map-Editor#915]
## Before you submit an issue, please read
 * If you get an unhandled exception, please _**check your log before posting**_.
 * If your log includes _**DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved**_
   * This is a known issue, do not create a new issue, please add your comments to #751
   * People have had the most luck in Windows 7 with updating to DirectX 11.1
     This is found in windows update in the optional updates section or by
     following directions here 
   * https://support.microsoft.com/en-us/kb/179113
 * Please fill out the questions below
 * Instead of copy/pasting text you can attach the entire log file.
 * If your world file is less than 25MB, you can attach it as well.
   
## What version of Terraria are you using? well not sear 
[TEditLog.txt](https://github.com/TEdit/Terraria-Map-Editor/files/589774/TEditLog.txt)
[Avalonia2world.zip](https://github.com/TEdit/Terraria-Map-Editor/files/589783/Avalonia2world.zip)

**Comment by Omio** [comment]
You are using an outdated version of TEdit; TEdit's at 3.9 now.

**Comment by enigmaquip** [comment]
@deathishere420 I finally got around to working some on debugging this, had to tweak the code a bit. It's crapping out on one of your chests, something inside one of them. I'm still trying to find where/what.

**Comment by enigmaquip** [comment]
found it..... an item in a chest had a prefix id of 88 which is outside the bounds of the game's prefixes.... I'm pushing code to not be so stupid when the prefix is greater than the defined list.....
Was this world generated with a mod?

**Comment by BinaryConstruct** [comment]
If possible, TEdit should attempt to preserve the invalid prefix to
minimize impact. Potentially, this could help with mod "support" or at
least lower conflicts for mods that do not modify the file format.

**Comment by enigmaquip** [comment]
The "fix" is just in the name lookup, it's crashing when it tries to grab a location in the prefix name array bigger than the array, so I'm not modifying the prefix in any way

**Comment by enigmaquip** [comment]
It'll just say "Unknown {#}" when chests are opened or analysis is done

**Comment by BinaryConstruct** [comment]
Sounds good to me

**Comment by enigmaquip** [comment]
TEdit3_BETA_v3.9.16334.167
Should correct this issue, please reopen if it doesn't
