### ISSUE TITLE
Unhandled exception crash - can reproduce

### ISSUE THREAD

**Issue by Fix-TEdit-Beta** [TEdit/Terraria-Map-Editor#916]
## What were you doing when the issue occured?
I was zooming in on a crimson desert biome.

## Can you reproduce the issue?
Yes.

## What version of Terraria are you using?
1.3.3.3
[TEditLog.txt](https://github.com/TEdit/Terraria-Map-Editor/files/596203/TEditLog.txt)

**Comment by enigmaquip** [comment]
are all files up to date? are you overwriting every file (including settings.xml) when you update to a new version?

**Comment by Fix-TEdit-Beta** [comment]
I have never updated to a new version. TEdit3_BETA_v3.8.16203.93.zip (the option to download latest version from binaryconstruct.com/downloads/) is the first and only version I have ever used.

**Comment by enigmaquip** [comment]
hmmm apparently the download latest button isn't actually pulling the latest version..... @BinaryConstruct can you check that?

**Comment by Fix-TEdit-Beta** [comment]
Yep it's pulling a version from July 20th. I will try the actual latest version. Should I delete my version of TEdit and install the latest, or use the check for updates function?

**Comment by enigmaquip** [comment]
you can just overwrite all the files from a newer zip.... I wouldn't use today's version if you haven't updated your game to 1.3.4 though

**Comment by Fix-TEdit-Beta** [comment]
I refrained from updating to 1.3.4 because I didn't know if the 2016-11-03 version of TEdit would be compatible with 1.3.4 or if a compatible version of TEdit would be released in a timely fashion. I will update both now. Thanks for all your help! :)
