### ISSUE TITLE
Crash on Load 

### ISSUE THREAD

**Issue by roomm** [TEdit/Terraria-Map-Editor#917]
Every time I try to load this map file (uplaoded below) TEdit crashes:

https://s11.postimg.org/mmnvc46rn/Screenshot_1.png

## What were you doing when the issue occured?
Trying to load the map file.

## Can you reproduce the issue?
Yes, trying to open the map file (uploaded below) 

## What version of Terraria are you using?
Terraria 1.3.3.3  and TEdit 3.8.16308.1456 

## Post relevant contents of log or attach log file _**(very important)**_:
Log File: 
[TEditLog.txt](https://github.com/TEdit/Terraria-Map-Editor/files/592949/TEditLog.txt)
[Mundaken.zip](https://github.com/TEdit/Terraria-Map-Editor/files/592952/Mundaken.zip)

**Comment by broomsa** [comment]
Are you sure about your game version and it's not updated to 1.3.4 today?
New worlds from 1.3.4 are incompatible with TEdit atm.

**Comment by enigmaquip** [comment]
as broomsa said, the world file changed with 1.3.4.... the error msg tells you everything you need to know.... your world is newer than supported.... watch for an update soon
