### ISSUE TITLE
Tedit not showing up than after 1 min just crashes

### ISSUE THREAD

**Issue by Penko72** [TEdit/Terraria-Map-Editor#923]
Its my first time using Tedit, downloaded latest version and i'm using latest version of terraria (1.3.4).

I would love to add Tedit-LOG but it didn't make any logs... just same old folder... i did try to run it as admin and same thing .. 

i did try to download some old versions of tedit and the worked but it was for 1.2 version of the game i think ... tryed to import map than got error (wich is probably normal as its created in newer version of game)

**Comment by Penko72** [comment]
Hope this link stays alive till one of you guys can see the picture.
http://prntscr.com/d9d5ut

There is crash and in background where is the tedit run from and you can see there is no crash log.

**Comment by enigmaquip** [comment]
Tedit log shows up in your local save game folder..... check My Documents/My Games/Terraria/

**Comment by Penko72** [comment]
ok ty, 
[TEditLog.txt](https://github.com/TEdit/Terraria-Map-Editor/files/601735/TEditLog.txt)

**Comment by enigmaquip** [comment]
Looks like you are getting the sharpdx issue mentioned when you open up this issue

 * If your log includes _**DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved**_
   * This is a known issue, do not create a new issue, please add your comments to #751
   * People have had the most luck in Windows 7 with updating to DirectX 11.1
     This is found in windows update in the optional updates section or by
     following directions here 
   * https://support.microsoft.com/en-us/kb/179113

**Comment by Penko72** [comment]
Is there a manual installation for DirectX 11.1 ? i think i just installed dx 11 (got it from PirateBay)... i disabled lots of features on windows like WinUpdate,firewall ... and other stuff

**Comment by enigmaquip** [comment]
There used to be a seperate kb installer, they got rid of it when they did the 'rollup update'

**Comment by Omio** [comment]
A little digging: https://www.microsoft.com/en-us/download/details.aspx?id=36805

**Comment by enigmaquip** [comment]
that's the rollup update, it's a mass update, not just for directx

**Comment by Penko72** [comment]
I'm back just making sure you know you helped me a lot !!! its working now thanks to you guys :)

You have grate respond time and much pantience with retarded ppl (as me) that couldn't find even Tedit log.(i swear i red somwhere it will be in same folder as Tedit) !!!! 
cya guys and i hope i won't need to come here again (at least with no problems)

**Comment by Omio** [comment]
Actually, if you DO have problems, please come back; we'd rather know the problems so we can fix them.

Until then, well... ...I believe this issue can be closed as resolved.
