### ISSUE TITLE
Zooming in no longer shows blocks in detail? 

### ISSUE THREAD

**Issue by DingFandango** [TEdit/Terraria-Map-Editor#924]
I remember previous versions of Tedit a year or so ago would show sprites in detail if you zoomed in but now I can't see any of that. When zooming in even all the way, all I see are colored squares like this: http://i.imgur.com/GmY6gQx.png

**Comment by Omio** [comment]
I know what's going on here; you have the details disabled, lemme get my TEdit up to show you where in the menu you can re-enable those.

**Comment by enigmaquip** [comment]
Do you have a non-normal installation location? if tedit can't find the terreria sprites it wont show them

**Comment by DingFandango** [comment]
I do have a non-normal installation. How do I direct it to the terraria sprites? My show textures is already checked so I'm guessing it's the problem enigma says.

**Comment by enigmaquip** [comment]
Look in the settings.xml file, at around line 90 you'll see the code/example for sprite path

**Comment by DingFandango** [comment]
Do you mean this line?   

I uncommented the <AltC> line and put in where my terraria content folder is but that didn't fix the issue.

**Comment by enigmaquip** [comment]
it's the AltC line
you need to take off the 
make sure it has \Terraria\Content at the end
so it should read
<AltC>Drive:\Folder\Terraria\Content</AltC>

**Comment by DingFandango** [comment]
This is what it looks like at the moment but it isn't fixing the zoom issue. http://i.imgur.com/Kbhitce.png

**Comment by enigmaquip** [comment]
Hmmmm TEdit should've been able to find it anyways, based on the fact it's a steam install....
if it didn't find it it should've prompted you to find it.....

**Comment by enigmaquip** [comment]
Let me make some tweaks real quick

**Comment by enigmaquip** [comment]
Try 3.9.16332.165

**Comment by DingFandango** [comment]
Try putting that as the AltC content?

**Comment by enigmaquip** [comment]
sorry that's the new version number that just got built..... update to latest, then modify your altc again

**Comment by DingFandango** [comment]
http://i.imgur.com/hbS7vDv.png It works now! Thank you so much.
