### ISSUE TITLE
Edited worlds won't save

### ISSUE THREAD

**Issue by Thoisy73** [TEdit/Terraria-Map-Editor#926]
After I edit my worlds they all save as tmp files and not as wld files. When I hit save as TEdit stays on "Save Headers" and doesn't load.  The tmp files are only 130kb each.
![save headers](https://cloud.githubusercontent.com/assets/23778866/20637860/6858b342-b362-11e6-9a5a-bec91da757ec.PNG)
![tedit worlds](https://cloud.githubusercontent.com/assets/23778866/20637867/ae0950cc-b362-11e6-89b4-671db38995da.PNG)

**Comment by enigmaquip** [comment]
Is this from starting a new world from scratch? Upgrade to the most recent
version because it's already been fixed if it's caused by making a brand
new world in tedit

**Comment by Thoisy73** [comment]
The world i'm trying to edit isn't new I have at least 70 hours in it.

**Comment by enigmaquip** [comment]
try the build that should be coming out here in the next few minutes and let me know if that fixed it

**Comment by Thoisy73** [comment]
It works now! Thanks!
