### ISSUE TITLE
Importing images

### ISSUE THREAD

**Issue by AwryWolf** [TEdit/Terraria-Map-Editor#929]
This option doesn't seem to work at all. It opens my folder but no image comes up even though I have tons. I tried downloading 24 bit, etc but no luck. It just doesn't show an image to import. Would really appreciate if anyone could tell me a way to fix this. TY!

**Comment by enigmaquip** [comment]
TEdit only handles png's and bmp's..... And most importantly..... you need to select one or the other in the file drop down instead of schematic
![image](https://cloud.githubusercontent.com/assets/6134440/20695341/6d397534-b5a8-11e6-8bb8-328ad95a3f65.png)

**Comment by AwryWolf** [comment]
Ah I see. But the only thing is when I try import an image it only pastes in the size and removes all the blocks around the paste. Is the picture actually meant to paste or..?

**Comment by enigmaquip** [comment]
It tries to do an exact color match to tiles and if that doesnt work then
walls.... If it doesn't match any colors it will be blank

**Comment by AwryWolf** [comment]
Ah so if the colors are slightly off it doesn't work? I was using terraria
tools which converts an image to a terraria version but still didn't work..
thanks for the help though!

**Comment by BinaryConstruct** [comment]
Your best bet is to export from TEdit and use the colors in the exported
file.

**Comment by enigmaquip** [comment]
I will check out terraria tools and see what colors they're using, but all the tile/wall colors in tedit should match up with the colors in Terraria..... if you'd like to look at what the colors are, they are all in the settings.xml file

**Comment by AwryWolf** [comment]
Right, thanks very much. Also if you could clarify, by exporting you mean taking an image from the world, and by exact colours do you mean you need to have ones perfectly identical to the block? Terraria tools which is an image converter does that and even lists the blocks but no luck. Maybe I'm missing something, have any of you been able to do it?

**Comment by enigmaquip** [comment]
I don't know that that tool is making the terrariafied image the right colors for import, it's telling you what blocks to use, but I don't think it's making the picture actual terraria pixel map colors
