### ISSUE TITLE
New versions of Terraria

### ISSUE THREAD

**Issue by P4ps** [TEdit/Terraria-Map-Editor#931]
TEdit is currently pretty outdated. Have you planned on making the editor work on the worlds created during the latest Terraria version?
I do not mean to rush, it would just be nice to know when or if it's gonna happen.
good job btw, you've gone through a lot of effort for this :p 

Sincerely yours,

Pap

**Comment by enigmaquip** [comment]
No its not, 3.9 is updated for 1.3.4

**Comment by P4ps** [comment]
How come I can't modify my world in the newest TEdit version? (I created it about 2 weeks ago)

[The error message](http://imgur.com/mhiU8mZ)

**Comment by enigmaquip** [comment]
Because you don't have the latest version?

**Comment by enigmaquip** [comment]
Check that you are actually grabbing the top most file from http://www.binaryconstruct.com/downloads/ and not using the 'Download Latest Version' button

**Comment by P4ps** [comment]
Oh, I see. Why is the 'Download Latest Version' button even there if it doesn't do what it is supposed to do? x)
