### ISSUE TITLE
"An unhandled exception has occured" Error and shut down

### ISSUE THREAD

**Issue by AspaLuvi** [TEdit/Terraria-Map-Editor#933]
![teditcrashcapture1](https://cloud.githubusercontent.com/assets/24274949/20760503/3cbf2022-b731-11e6-99bf-d2f09a0c9ead.JPG)
![teditcrashcapture2](https://cloud.githubusercontent.com/assets/24274949/20760501/3cbc1ec2-b731-11e6-8ba1-49804737c514.JPG)
[TEditLog1.txt](https://github.com/TEdit/Terraria-Map-Editor/files/622305/TEditLog1.txt)
[TEditLog2.txt](https://github.com/TEdit/Terraria-Map-Editor/files/622306/TEditLog2.txt)

[worldfiles.zip](https://github.com/TEdit/Terraria-Map-Editor/files/622322/worldfiles.zip)

   
## What were you doing when the issue occured?
Opened TEdit3_BETA_v3.9.16334.169 ,loaded a world created on October 23rd 2016,  I selected an area which includes multiple chests, platforms, backgroung wall, empty/used item frames. Then pressed "copy" button on the left.
## Can you reproduce the issue?
I repeated and same thing happened. Then I removed many empty chests from world. I retried with "one empty chest+wall'platform" , error appeared again. I tried copying an area of just stone slab wall, there was no error.
## What version of Terraria are you using?
Terraria v.1.3.4.3

**Comment by AspaLuvi** [comment]
I also did try a  on world created after last Terraria update with less than 5 user placed chests, again
![teditcrashcapture3](https://cloud.githubusercontent.com/assets/24274949/20761797/3c3eb050-b735-11e6-91d6-9e21312e1c7d.JPG)
 software gave error and closed

**Comment by enigmaquip** [comment]
So it's when you go to copy a chest? not paste it?

**Comment by enigmaquip** [comment]
Nevermind, I can recreate the issue

**Comment by enigmaquip** [comment]
Ok, try it now in the build that should be coming out in the next few mins, should have fixed the issue. If not reopen
