### ISSUE TITLE
TEdit Says "TEdit has stopped working"

### ISSUE THREAD

**Issue by DKPGROWTOPIA** [TEdit/Terraria-Map-Editor#935]
Yes I know it tell me to read some kind of post but... I did everything and it didnt work . My graphics card is Radeon and all my Dll`s and things are updated I also says in "Problem details" Its some kind of thing called "SharpDX" I searched everywhere and i cant find it Please help

Please dont shut down this issue

**Comment by enigmaquip** [comment]
You don't need to post in 3 different issues.
What version of Windows are you using? What version of TEdit?

**Comment by DKPGROWTOPIA** [comment]
Im windows 7 SP1 and my version of TEdit is v3.9.16335.171

**Comment by enigmaquip** [comment]
Follow the instructions in the issue when you started it
Go to 
https://support.microsoft.com/en-us/kb/179113
and follow the info to upgrade to directx 11.1
http://www.microsoft.com/en-us/download/details.aspx?id=36805

**Comment by DKPGROWTOPIA** [comment]
I have directx 11 i didnt know you need 11.1

**Comment by DKPGROWTOPIA** [comment]
How do i update to DirectX 11.1

**Comment by enigmaquip** [comment]
Follow the instructions in the issue when you started it
Go to
https://support.microsoft.com/en-us/kb/179113
and follow the info to upgrade to directx 11.1

**Comment by DKPGROWTOPIA** [comment]
Windows update doesnt work for me
