### ISSUE TITLE
Tedit has stopped working.

### ISSUE THREAD

**Issue by Meraxx** [TEdit/Terraria-Map-Editor#936]
I have no clue about any of this stuff tbh i just want it to work so i can edit one of my worlds :c 
It doesnt load it just says its stopped working and then closes
Im using TEdit3_BETA_v3.8.16203.93, i dont even know if thats the most recent.
[TEditLog.txt](https://github.com/TEdit/Terraria-Map-Editor/files/633370/TEditLog.txt)

**Comment by Omio** [comment]
It looks like it failed to load textures. The most recent version, from binaryconstruct.com, is here:
[|Link - TEdit 3.9.16335.171.zip|](http://www.binaryconstruct.com/downloads/TEdit3_BETA_v3.9.16335.171.zip)

**Comment by enigmaquip** [comment]
If it's still not working you're getting the DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved mentioned when you made the issue
What usually works is upgrading directx to 11.1 as mentioned here https://support.microsoft.com/en-us/kb/179113
More info is also available at #751
