### ISSUE TITLE
TEdit didn't open

### ISSUE THREAD

**Issue by JasonBroadson** [TEdit/Terraria-Map-Editor#939]
PLEASE READ THIS CAREFULLY
When I double click TEdit the TEdit appear in my Task Manager's Processes Tab but didn't show up
I can play Terraria without problem
My Terraria Version : 1.3.4.3
Can anyone help me?

**Comment by Omio** [comment]
Upload TEdit.log so we can get a better look at potential problems. Which version of TEdit are you using, and did you end up trying to build TEdit yourself?

**Comment by JasonBroadson** [comment]
[TEditLog.txt](https://github.com/TEdit/Terraria-Map-Editor/files/638480/TEditLog.txt)
Here's the TEdit.log, I don't understand what do you mean by "Trying to build TEdit yourself" because English isn't my first language. I installed TEdit by downloading it through the BinaryConstruct's Website, and get the rar file, after that I extracted it and there's TEditXNA.exe so I open that file. The first time I open it, it was working like okay, and the second time I open it? It didn't work.
My TEdit Version : 3.9.16342.177, I updated it. Previously it was 3.9.16342.175. Both version didn't work.

**Comment by ZeroDozer** [comment]
I seem to be running into this problem. My version is 3.9.16342.177 as well. My TEdit refuses to open as well, and I am forced to kill the process every time I try to open it. Just like Jason above me, the first time I opened TEditXNA.exe it worked just fine (Well, up to what my machine could handle), but after that...
[TEditLog.txt](https://github.com/TEdit/Terraria-Map-Editor/files/652862/TEditLog.txt)

**Comment by BinaryConstruct** [comment]
@ZeroDozer, your issue is #751. Please see support in that thread.

@JasonBroadson , after updating to the latest version please try https://github.com/TEdit/Terraria-Map-Editor/wiki/Troubleshooting
