### ISSUE TITLE
Can not save the world

### ISSUE THREAD

**Issue by usdanger** [TEdit/Terraria-Map-Editor#942]
The same issue with #926.
Cant save world in V3.8 version. 
The map is an old one, and it built in 1.3.1(never open it in later version terraria)
When click on save, freeze on "Save headers".
I tried what u said previously, (enigmaquip commented 17 days ago: try the build that should be coming out here in the next few minutes and let me know if that fixed it).
But doesn't work. Hope could get some help. 
Thanks so much

**Comment by BinaryConstruct** [comment]
3.8 may not be compatible with 1.3.1 world files, please update the world by loading it with Terraria's latest version or use TEdit 3.7.

**Comment by usdanger** [comment]
Why I ask that question is because my 1.3.3.3 version cant load the map edit by the latest version. However,
1 hour after I post this. The tmod loader update. So I dont need old version now. 
Thank you for that reply. love tedit so much. it is a perfect tool.
