### ISSUE TITLE
Add capability for MoreTerra to also detect Steam cloud save files, or open the folder conveniently, somehow in the UI.

### ISSUE THREAD

**Issue by Pysis868** [TEdit/Terraria-Map-Editor#948]
## What were you doing when the issue occurred?

1. Opened the application.
2. File > Open from the menu bar.

## Can you reproduce the issue?
Yes.

## What version of Terraria are you using?
1.3.4.4.

## Post relevant contents of log or attach log file _**(very important)**_:
12-26-2016 16:08:07: Starting TEdit 3.9.16350.0618 
12-26-2016 16:08:07: OS: Microsoft Windows NT 6.2.9200.0 
12-26-2016 16:08:08: Terraria v1.3.4.4 
12-26-2016 16:08:08: Terraria Data Path: C:\Program Files (x86)\Steam\steamapps\common\Terraria\Content 
12-26-2016 16:08:08: Creating Undo cache: C:\Users\User\AppData\Roaming\TEdit\undo_561196947 

## Other

MoreTerra has a dropdown menu ([Related issue](https://github.com/mike-mo/MoreTerra/issues/7)).  Maybe add one of those that one could populate worlds as entries into it from either source location on the system, or any other fast open method, such as opening a dialog with either folder path as the default location, possibly by a separate menu item.

**Comment by enigmaquip** [comment]
you can default to opening cloud worlds by editing the settings.xml file and adding your steam id to the relevant section

**Comment by BinaryConstruct** [comment]
Perhaps is Terraria or Save folder is not located a popup dialog to choose the folder would help?

**Comment by Pysis868** [comment]
If it was possible with OS or custom dialogs, maybe more-so using the custom approach if it's not a dialog and built-into the UI somehow, like 2 buttons or menu options, just to have the capability for accessing either folder location quickly.

This adds onto what BinaryConstruct said since my folders would still be located, just the first one would be empty, but still opened, not conveniently so.

**Comment by BinaryConstruct** [comment]
Usability Improvements pt.2 #1274
