### ISSUE TITLE
Plugin: whole world biome morph tool

### ISSUE THREAD

**Issue by HAMINPANTS** [TEdit/Terraria-Map-Editor#949]
For a while, I've been really annoyed by the Hallow and Crimson and I have been using TEdit (I think it's awesome and super useful! Keep up the great work!) but I keep missing spots so i was wondering if you add a feature that displays the percentage of your world that is Hallow and Crimson/Corruption (depending on your world type) so its sort of like the Dryads "Status" feature. For tasks like purifying the world, I think it was also be extremely useful if you made a function where you could enter a block type somewhere and it would highlight all of that block in your world! If none of this made sense (because I'm really bad at explaining my ideas :P) then basicly I'm saying "It would be awesome if the was a button or something that would purity your entire world!" Thanks for reading this and I love the tool you made!!!

**Comment by BinaryConstruct** [comment]
This probably a good feature for a plugin.

**Comment by BinaryConstruct** [comment]
Merging with #913
