### ISSUE TITLE
what do i do if i have Windows XP :(

### ISSUE THREAD

**Issue by Kagiusme** [TEdit/Terraria-Map-Editor#950]
## Before you submit an issue, please read
 * If you get an unhandled exception, please _**check your log before posting**_.
 * If your log includes _**DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved**_
   * This is a known issue, do not create a new issue, please add your comments to #751
   * People have had the most luck in Windows 7 with updating to DirectX 11.1
     This is found in windows update in the optional updates section or by
     following directions here 
   * https://support.microsoft.com/en-us/kb/179113
 * Please fill out the questions below
 * Instead of copy/pasting text you can attach the entire log file.
 * If your world file is less than 25MB, you can attach it as well.
   
## What were you doing when the issue occured?
trying to aunch the game
## Can you reproduce the issue?
yes
## What version of Terraria are you using?
1.3.4.4
## Post relevant contents of log or attach log file _**(very im
[TEditLog.txt](https://github.com/TEdit/Terraria-Map-Editor/files/676897/TEditLog.txt)
portant)**_:

**Comment by BinaryConstruct** [comment]
Unfortunately, Microsoft has ended support for XP and it is unlikely that TEdit will work on that operating system.
https://www.microsoft.com/en-us/WindowsForBusiness/end-of-xp-support

**Comment by DumbJoe** [comment]
> 
> 
> Unfortunately, Microsoft has ended support for XP and it is unlikely that TEdit will work on that operating system.
> https://www.microsoft.com/en-us/WindowsForBusiness/end-of-xp-support

But Terraria still runs on XP, even the latest v1.3.5.3, why can't this program also run on windows xp machines?
