### ISSUE TITLE
TEdit stops working

### ISSUE THREAD

**Issue by TombWarBR** [TEdit/Terraria-Map-Editor#952]
I just installed TEdit, and everytime i want to open it, it stops working, and it's every single time i try to open it. (I'm using the latest version of Terraria)
[TEditLog.txt](https://github.com/TEdit/Terraria-Map-Editor/files/679857/TEditLog.txt)

**Comment by BinaryConstruct** [comment]
Check #751

**Comment by TombWarBR** [comment]
Just checked and nothing there really helps me, i don't have NVIDIA, i don't have Geforce, everything is up-to-date and TEdit still doesn't work
