### ISSUE TITLE
Creates Process but never opens window

### ISSUE THREAD

**Issue by Gyroscopickitty** [TEdit/Terraria-Map-Editor#954]
Okay so, I was trying to launch the experimental version for 1.3.4. It launches the process, lags a bit, and never opens a window.

I have directx 11 installed and can run terraria, but I get this message in the log.text

01-03-2017 16:47:06: Starting TEdit 3.9.16350.0618 
01-03-2017 16:47:06: OS: Microsoft Windows NT 6.0.6002 Service Pack 2 
01-03-2017 16:47:06: DirectX 10 unsupported. DirectX 11 or higher is required. 
01-03-2017 16:47:07: Terraria v1.3.4.4 
01-03-2017 16:47:07: Terraria Data Path: c:\program files\steam\steamapps\common\terraria\Content 
01-03-2017 16:47:07: Command Line Open: C:\Program Files\Tedit\whelp.wld 
01-03-2017 16:47:07: Creating Undo cache: C:\Users\Me\AppData\Roaming\TEdit\undo_397703761

**Comment by FyreDemon405** [comment]
I have directx11 installed on a 32bit windows vista and am also having this problem.
here is my log:
02-15-2017 10:40:08: Starting TEdit 3.8.16308.1456 
02-15-2017 10:40:08: OS: Microsoft Windows NT 6.0.6002 Service Pack 2 
02-15-2017 10:40:08: DirectX 10 unsupported. DirectX 11 or higher is required. 
02-15-2017 10:40:09: Terraria Data Path: C:\Program Files\Steam\steamapps\common\Terraria\Content 
02-15-2017 10:40:09: Creating Undo cache: C:\Users\Aidan\AppData\Roaming\TEdit\undo_66534934 
i can see it in task manager taking up 0 cpu using 28,000k memory

**Comment by BinaryConstruct** [comment]
TEdit probably will not work on 32bit os. It has some compile flags for large memory support on x64 systems.
