### ISSUE TITLE
tedit doesn't start

### ISSUE THREAD

**Issue by venrux** [TEdit/Terraria-Map-Editor#955]
## i oppened the programm but it gives me a message that sais that i have to whrite my issue here  
##i can reproduce the issue
 ## i use the newest version of terraria (1.3.4)
[TEditLog.txt](https://github.com/TEdit/Terraria-Map-Editor/files/691820/TEditLog.txt)

**Comment by Tilerawr** [comment]
The same thing happens to me and has happened ever version 1.3 and onward.
