### ISSUE TITLE
Direct Download

### ISSUE THREAD

**Issue by FuristicWolf200** [TEdit/Terraria-Map-Editor#957]
when i try to download the program it takes me to a virus adfly link

**Comment by EEParker** [comment]
https://github.com/TEdit/Terraria-Map-Editor/releases

**Comment by BinaryConstruct** [comment]
There are several ways to download directly without using adfly. 

http://www.binaryconstruct.com/downloads/
![image](https://cloud.githubusercontent.com/assets/456755/22078807/fb838ff2-dd7e-11e6-9077-49a34833a7a5.png)

![image](https://cloud.githubusercontent.com/assets/456755/22078827/1012d928-dd7f-11e6-8ade-4cb0d5946f7c.png)

https://github.com/TEdit/Terraria-Map-Editor/releases
