### ISSUE TITLE
TEditXna.exe started once but doesn't after

### ISSUE THREAD

**Issue by ausguerila** [TEdit/Terraria-Map-Editor#958]
## Before you submit an issue, please read
 * If you get an unhandled exception, please _**check your log before posting**_.
 * If your log includes _**DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved**_
   * This is a known issue, do not create a new issue, please add your comments to #751
   * People have had the most luck in Windows 7 with updating to DirectX 11.1
     This is found in windows update in the optional updates section or by
     following directions here 
   * https://support.microsoft.com/en-us/kb/179113
 * Please fill out the questions below
 * Instead of copy/pasting text you can attach the entire log file.
 * If your world file is less than 25MB, you can attach it as well.

**Comment by ausguerila** [comment]
After downloading TEdit3_v3.9.16350.181 and running the program, the program ran once but all other attempts have not worked. TEditXna.exe comes up in the Processes section of Windows Task Manager, displays around 62,000K - 63,000K memory usage, then the process ends.

**Comment by arduano** [comment]
Same issue, but with 3.10.
restarting my PC let me open it again, but then it crashed after some time.
