### ISSUE TITLE
World not displaying correctly

### ISSUE THREAD

**Issue by whamer100** [TEdit/Terraria-Map-Editor#959]
## What were you doing when the issue occured?
Loading the world, any world for that matter.

## Can you reproduce the issue?
Yes, I just loaded any world from 1.3.4.4 (Using large map)

## What version of Terraria are you using?
1.3.4.4

## Post relevant contents of log or attach log file _**(very important)**_:
TEdit didn't create any logs.

**Comment by whamer100** [comment]
I stand corrected about the logs, here is the log file
[TEditLog.txt](https://github.com/TEdit/Terraria-Map-Editor/files/753319/TEditLog.txt)

**Comment by whamer100** [comment]
I took a screenshot of what TEdit looks like, it appears to be a rendering error 
![render error](https://cloud.githubusercontent.com/assets/10352720/22909060/b5b7ff8e-f206-11e6-8444-a45c1b066bd2.png)

**Comment by MACMAN2003** [comment]
i have the same problem

**Comment by BinaryConstruct** [comment]
Do you have DXGI device removed in the log?
