### ISSUE TITLE
"An Unhandled Exception Has Occured" Whenever I Try To Run TEdit

### ISSUE THREAD

**Issue by AnarchyInExile** [TEdit/Terraria-Map-Editor#960]
## What were you doing when the issue occured?

Trying to run TEdit.

## Can you reproduce the issue?

Yes.

## What version of Terraria are you using?

3.4.4

[TEditLog.txt](https://github.com/TEdit/Terraria-Map-Editor/files/772119/TEditLog.txt)

**Comment by BinaryConstruct** [comment]
It appears TEdit cannot read your games\GOG folder while trying to load
texture data. You may have to run as a different user. You also may be able
to get it to work by modifying the config file to manually point to a
different folder and copying the terraria contents folder to there.
