### ISSUE TITLE
Is there a way to flip selections in TEdit?

### ISSUE THREAD

**Issue by CausticFoil** [TEdit/Terraria-Map-Editor#962]
I'm currently building a PVP arena in TEdit and I've built one side of it. However, instead of spending an hour recreating the other side block for block I was wondering if TEdit has a way of flipping selections so I could take a huge shortcut.

(Not sure if this is the right section to post this. If it isn't please correct me.)

**Comment by BinaryConstruct** [comment]
Yes, copy to clipboard and on the schematic tab click the flip x or y
buttons.

**Comment by CausticFoil** [comment]
Thank you so much.
