### ISSUE TITLE
TEdit doesn't open

### ISSUE THREAD

**Issue by NerdishNoob7** [TEdit/Terraria-Map-Editor#964]
I can't open TEdit. I can see it in the Windows Task Manger, but there is no window. I checked in C:Program Files and C:Program Files (x86), but there was no TEdit 3 Folder.

**Comment by UnoRev3** [comment]
The same happens to me. Did you solve it?

**Comment by NerdishNoob7** [comment]
Nope

**Comment by BinaryConstruct** [comment]
You need to extract the zip file to a folder of your choice. There is no installer or program files folder.
