### ISSUE TITLE
UnHandled exception

### ISSUE THREAD

**Issue by TheDarkPoro** [TEdit/Terraria-Map-Editor#965]
whenever i try to run Tedit it sais that an unhandled exception has occured
here is my log please help
[TEditLog.txt](https://github.com/TEdit/Terraria-Map-Editor/files/870706/TEditLog.txt)

**Comment by AntiseisJoga** [comment]
Same error here, but in my case can be something different, i moved the Tedit folder to the desktop and it worked properly.
What happened is the old folder has a "#" in the path, so it didn't load, resulting in a "UnHandled exception" error too. I have see some strange symbols (consider that i am a Brazillian) in your log. Namely this ones (נימרוד), and the Tedit maybe can't read these, put the folder closer to "C:", like "C:/Tedit" and try again, maybe works, maybe not, but anyway one of the developers will fix it in the future.

**Comment by FierceDragon680** [comment]
same exept it destroyed my world

**Comment by BinaryConstruct** [comment]
Currently there are known issues with paths and special characters. Please install TEdit to a path such as c:\games\tedit with no special characters. You may also need to copy your map files to a location with no special characters such as c:\games\maps
