### ISSUE TITLE
Saving in TEdit corrupts world

### ISSUE THREAD

**Issue by Sylvean** [TEdit/Terraria-Map-Editor#967]
I've been playing Terraria for some days, exploring, killing monsters and bosses, welcoming NPCs, etc...
My world has been in Hardmode for approximately 2 days, and the quick expansion of the Crimson is making me paranoid. Instead of wasting days, weeks, maybe months cleansing it with what I had available (and by that I mean throwing dynamite, and maybe the Clentaminator later in the game), I decided to use an editor to partly remove the Crimson first, then completely purify it when I'll be done with the world. Of course, while modifying the world, I stumbled upon one issue that prevents me from doing anything : Saving doesn't work.
Everytime I open the save in TEdit (I have backups), it works. Then, when I'm done modifying, I choose Save or Save As..., then when I open Terraria, my world has become corrupted and I can't play. The game indicates nothing more than "Load Failed !", so I'm kinda lost. I even get the same problem when I save the map without editing anything !

I have a GOG Version of Terraria 1.3.3, and I've tried version 3.9.16348.180 for 1.3.3 and version 3.9.16350.181 for 1.3.4, they have the same issue.

I've attached my world file with this post, and I remain available for additional details.

[World.zip](https://github.com/TEdit/Terraria-Map-Editor/files/922407/World.zip)

**Comment by enigmaquip** [comment]
Hmmm 3.9.16348.180 is actually further ahead than 1.3.3 so you are saving a world that's too new for your Terraria version.... you could try this one and see if it works for you
https://ci.appveyor.com/project/BinaryConstruct/terraria-map-editor/build/3.8.16253.141/artifacts

**Comment by Sylvean** [comment]
Oh, well you were right. I also bought Terraria on Steam to play with some friends and the automatic version update has allowed me to choose a build that works with my version. Thanks a lot !
