### ISSUE TITLE
Scroll wheel will not zoom out in Windows 10 Creators Update

### ISSUE THREAD

**Issue by LyraelRayne** [TEdit/Terraria-Map-Editor#971]
## What were you doing when the issue occured?
Trying to scroll out using mouse wheel.

## Can you reproduce the issue?
Yes. Any scrolling out using the mouse wheel since installing creator's update doesn't work.

## What version of Terraria are you using?
1.3.4.4 and 1.3.5.1!!! (Looking at the log is how I found out that the game updated lol)

## Post relevant contents of log or attach log file _**(very important)**_:
04-20-2017 10:34:51: Starting TEdit 3.9.17105.0355 
04-20-2017 10:34:51: OS: Microsoft Windows NT 6.2.9200.0 
04-20-2017 10:34:52: Terraria v1.3.5.1 
04-20-2017 10:34:52: Terraria Data Path: E:\Games\SteamLibrary\steamapps\common\terraria\Content 
04-20-2017 10:34:52: Creating Undo cache: C:\Users\Lyrael\AppData\Roaming\TEdit\undo_858449992

**Comment by LyraelRayne** [comment]
I've tried this with both my razer naga using the razer drivers and with a "HID-compliant mouse"

**Comment by enigmaquip** [comment]
Does zoom in work with the scroll wheel? Just not zoom out?

**Comment by LyraelRayne** [comment]
Correct. Zoom in works correctly. Zoom out does not work with scroll wheel, but does work with CTRL+-

**Comment by LyraelRayne** [comment]
Just checked and the problem still exists in TEdit 3.10.17110.0321

**Comment by BinaryConstruct** [comment]
I'm downloading Win10CU to test this out. It may be a while...windows updates aren't exactly `fast`.

**Comment by LyraelRayne** [comment]
Yeah mouse works properly in other apps.  Just tested the latest release and it works now. Thanks :)
