### ISSUE TITLE
Problem when loading up a world

### ISSUE THREAD

**Issue by CongoMonkey31** [TEdit/Terraria-Map-Editor#976]
[TEditLog.txt](https://github.com/TEdit/Terraria-Map-Editor/files/949245/TEditLog.txt)

When I tried to load up my world to edit it, the program just told me to put the log here so here you are

**Comment by enigmaquip** [comment]
It looks like it's unable to find your terraria textures, you'll want to manually set the path to your terraria content folder in the settings.xml file

**Comment by enigmaquip** [comment]
you should see this line when you edit the settings.xml file

```
<!-- Uncomment the following and set Terraria/Content path. Perhaps useful if Terraria isn't installed locally or in a custom location. -->
<!--<AltC>D:\Dev\CODE\Terraria\Content</AltC>-->
```
you need to remove the beginning  from that and edit it to where Terraria is installed

**Comment by CongoMonkey31** [comment]
Thanks for the help

**Comment by enigmaquip** [comment]
Should be fixed in the new version
