### ISSUE TITLE
[1.3.5.2] TEdit does not preserve the "player assigned" state on NPC houses.

### ISSUE THREAD

**Issue by LyraelRayne** [TEdit/Terraria-Map-Editor#977]
## What were you doing when the issue occured?
Saving a world.

## Can you reproduce the issue?
Yes

## What version of Terraria are you using?
Terraria 1.3.5.2
Tedit 3.10.17112.2034

When saving a world, all NPC house assignments are treated as not player assigned (i.e. no gold border) regardless of whether the player assigned it. This is related to the new feature added in 1.3.5 (the gold border is from 1.3.5.2, but I believe the flag in the save file existed in 1.3.5.1).

**Comment by enigmaquip** [comment]
Yeah, I didn't quite implement the save code correctly, I should be able to correct this later tonight and include it in my next build

**Comment by enigmaquip** [comment]
Should be fixed in the new version

**Comment by LyraelRayne** [comment]
Seems to work properly now. Thanks :)
