### ISSUE TITLE
1.3.5.1 Terraria folder is not accepted by TEdit

### ISSUE THREAD

**Issue by lansucker** [TEdit/Terraria-Map-Editor#979]
When I try to launch Tedit it asks me for my content folder which is located in" C:\old\Program Files (x86)\Steam\steamapps\common\Terraria". Every time I use this folder the program tells me that this not the right folder (which it is). When I press cancel the tool loads without problems, but when I try to load one of my maps it always crashes with the following lines: 

04-24-2017 19:56:06: Starting TEdit 3.10.17112.2034 
04-24-2017 19:56:06: OS: Microsoft Windows NT 6.1.7601 Service Pack 1 
04-24-2017 19:56:30: Unable to locate Terraria. No texture data will be available. 
04-24-2017 19:56:30: Creating Undo cache: C:\Users\lansucker\AppData\Roaming\TEdit\undo_925892153 
04-24-2017 19:56:40: Error - Der Wert darf nicht NULL sein.
Parametername: key
   bei System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   bei TEditXna.View.WorldRenderXna.DrawNpcOverlay(NPC npc) in C:\projects\terraria-map-editor\TEditXna\View\WorldRenderXna.xaml.cs:Zeile 1872.
   bei TEditXna.View.WorldRenderXna.DrawPoints() in C:\projects\terraria-map-editor\TEditXna\View\WorldRenderXna.xaml.cs:Zeile 1815.
   bei TEditXna.View.WorldRenderXna.Render(GraphicsDeviceEventArgs e) in C:\projects\terraria-map-editor\TEditXna\View\WorldRenderXna.xaml.cs:Zeile 372.
   bei TEditXna.View.WorldRenderXna.xnaViewport_RenderXna(Object sender, GraphicsDeviceEventArgs e) in C:\projects\terraria-map-editor\TEditXna\View\WorldRenderXna.xaml.cs:Zeile 287.
   bei TEdit.UI.Xaml.XnaContentHost.GraphicsDeviceControl.CompositionTarget_Rendering(Object sender, EventArgs e) in C:\projects\terraria-map-editor\TEditXna\UI\Xaml\XnaContentHost\GraphicsDeviceControl.cs:Zeile 328.
   bei System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   bei System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   bei System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   bei System.Windows.Threading.DispatcherOperation.InvokeImpl()
   bei System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   bei System.Windows.Threading.DispatcherOperation.Invoke()
   bei System.Windows.Threading.Dispatcher.ProcessQueue()
   bei System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   bei MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   bei MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   bei System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   bei System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   bei MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   bei MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   bei System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   bei System.Windows.Application.RunDispatcher(Object ignore)
   bei System.Windows.Application.RunInternal(Window window)
   bei TEditXna.App.Main() 

I also read the "https://github.com/TEdit/Terraria-Map-Editor/issues/337" comment but I do not understand what to do there? I see the line which is posted but what do I have to do with that?

Thanks in advance

**Comment by enigmaquip** [comment]
your folder needs to point to your content folder, not just the terraria folder, so you need to go one deeper.... but the bug that caused this will be fixed shortly, so the next version that comes out will work for you

**Comment by enigmaquip** [comment]
You shouldn't get this error anymore now
