### ISSUE TITLE
World File Error

### ISSUE THREAD

**Issue by AntiSkid** [TEdit/Terraria-Map-Editor#983]
When I try to load my world, it displays this message:
There was an error reading the world file. This is usually caused by a corrupt save file or a world version newer than supported. [My world is 1.3.5]
TEdit v3.9.16350.0618
TEdit Max World: 187         Current World: 194
Do you wish to force it to load anyway?
WARNING: This may have unexpected results including corrupt world files and program crashes.
The error is:
Unable to read beyond the end of the stream.
at System.IO.BinaryReader.ReadString()
at TEdit XNA.Terraria.World.LoadNPCsData(BinaryReader r, World w) in
c:\projects\terraria-map-editor\TEditXna\Terraria\World.FileV2.cs:line 954
at TEditXNA.Terraria.World.LoadV2(BinaryReader b, String filename, World w) in
c:\projects\terraria-map-editor\TeditXna\Terraria\World.FileV2.cs:line 642
at TeditXNA.Terraria.World.LoadWorld(String filename) in c:\projects\terraria-map-editor\TEditXna\Terraria\World.cs:line 128

P.S. The only world files I have of this world is the .wld and .bak.

**Comment by enigmaquip** [comment]
you're trying to load a new world file with an old version of terraria, you need to upgrade to 3.10
