### ISSUE TITLE
Display problem i think

### ISSUE THREAD

**Issue by MACMAN2003** [TEdit/Terraria-Map-Editor#984]
## Before you submit an issue, please read
 * If you get an unhandled exception, please _**check your log before posting**_.
 * If your log includes _**DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved**_
   * This is a known issue, do not create a new issue, please add your comments to #751
   * People have had the most luck in Windows 7 with updating to DirectX 11.1
     This is found in windows update in the optional updates section or by
     following directions here 
   * https://support.microsoft.com/en-us/kb/179113
 * Please fill out the questions below
 * Instead of copy/pasting text you can attach the entire log file.
 * If your world file is less than 25MB, you can attach it as well.
   
## What were you doing when the issue occured?
basically i was trying to do anything
## Can you reproduce the issue?
yes all the time i try to use this
## What version of Terraria are you using?
1.3.5 but happens on all
## Post relevant contents of log or attach log file _**(very important)**_:
04-26-2017 17:14:15: Starting TEdit 3.10.17114.2256 
04-26-2017 17:14:15: OS: Microsoft Windows NT 6.2.9200.0 
04-26-2017 17:14:15: Terraria v1.3.5.3 
04-26-2017 17:14:15: Terraria Data Path: C:\Program Files (x86)\Steam\steamapps\common\Terraria\Content 
04-26-2017 17:14:15: Creating Undo cache: C:\Users\Jackson\AppData\Roaming\TEdit\undo_263447987 
04-26-2017 17:14:16: Creating Undo cache: C:\Users\Jackson\AppData\Roaming\TEdit\undo_225279589 
04-26-2017 17:14:38: Removing undo cache: C:\Users\Jackson\AppData\Roaming\TEdit\undo_225279589 
04-26-2017 17:17:48: Removing undo cache: C:\Users\Jackson\AppData\Roaming\TEdit\undo_263447987 

heres a picture 
![screenshot 26](https://cloud.githubusercontent.com/assets/20659419/25462671/77ca4218-2aa5-11e7-848d-fada27e92c37.png)

**Comment by BinaryConstruct** [comment]
Do you have DXGI device removed in the log?

**Comment by MACMAN2003** [comment]
apparalenty yeah so i used one of the "potential fixes and it worked
