### ISSUE TITLE
Failed to load textures

### ISSUE THREAD

**Issue by LuckyePie** [TEdit/Terraria-Map-Editor#986]
## What were you doing when the issue occured?
Nothing, just waiting the program open
## Can you reproduce the issue?
Yes, we can use skype or discord to talk: Skype: lucket45 Discord:LuckyPie#6056
## What version of Terraria are you using?
1.3.5
## Post relevant contents of log or attach log file _**(very important)**_:

[TEditLog.txt](https://github.com/TEdit/Terraria-Map-Editor/files/966398/TEditLog.txt)

**Comment by BinaryConstruct** [comment]
Please see #751 for some tips on this issue
