### ISSUE TITLE
Can I use the sprites from Terraria installed through steam, on a mac?

### ISSUE THREAD

**Issue by scuellar** [TEdit/Terraria-Map-Editor#987]
I'm using a VB to run TEdit, and seems to work just fine, but doesn't have the sprites. I'm trying to import the content file from my mac installation, but it won't work.

I'm getting the error "The folder doesn't seem to be content".

So the first question is, what is in the content folder you are expecting and what formats are used?

The mac Terraria installation has two similar folders "Contents" and "Content" (both with first capital). I tried both without success.

I just want to know if this is known to be incompatible, if I'm doing wrong or if it is unknown and worth figuring out.

**Comment by scuellar** [comment]
Never mind. Turns out, you have to point to the PARENT folder and not to content itself. It seems to work just fine with mac files. Thanks for the great program!

**Comment by scuellar** [comment]
I have managed to get the program to accept the folder (I guess it only looks for something called "content"). But no the sprites don't load. 

As a side question, is there anywhere I can download the sprites from (in the format TEdit requires)

**Comment by BinaryConstruct** [comment]
The sprites must come from Terraria install directory. If you can download
the steam PC version that should work.
