### ISSUE TITLE
[Feature] Plugin: Spritefinder to search e.g. Enchanded Sword Stone label:Features 

### ISSUE THREAD

**Issue by myghun** [TEdit/Terraria-Map-Editor#991]
Fist, nice program.
2nd, could you add an plugin similar to find plantera's bulb for e.g. Enchanded Sword Stone (like in Enchanded Sword Shrines http://terraria.gamepedia.com/Enchanted_Sword_(item) ).

Those stones (not in a shrine) can also appear in other places. Would be good to find them. 
If easy possible could be even a more global tool to find each sprite. So instead of Plantera bulb or enchanded sword stone you could also select a specific kind of statue, a rare chest type, furniture, altar...

Some more optional features: 
-only search in a specific region (to find e.g. stuff near spawn)
-more global, to not only find sprites also blocks, or any stuff which is same as in currently seleced region

Thanks

**Comment by BinaryConstruct** [comment]
Using #1273 for future work on sprite tools
