### ISSUE TITLE
Living Leaf wall not listed in editor

### ISSUE THREAD

**Issue by allelsewastaken** [TEdit/Terraria-Map-Editor#993]
## Before you submit an issue, please read
 * If you get an unhandled exception, please _**check your log before posting**_.
 * If your log includes _**DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved**_
   * This is a known issue, do not create a new issue, please add your comments to #751
   * People have had the most luck in Windows 7 with updating to DirectX 11.1
     This is found in windows update in the optional updates section or by
     following directions here 
   * https://support.microsoft.com/en-us/kb/179113
 * Please fill out the questions below
 * Instead of copy/pasting text you can attach the entire log file.
 * If your world file is less than 25MB, you can attach it as well.
   
## What were you doing when the issue occured?
NA
## Can you reproduce the issue?
NA
## What version of Terraria are you using?
1.3.5.3
## Post relevant contents of log or attach log file _**(very important)**_:
I cannot find Living Leaf wall in the wall list. I have searched it several times, but it just doesn't seem to be there?

**Comment by vertX89** [comment]
I think it's just listed as moss wall (#60 on the list).
