### ISSUE TITLE
TEdit 3.10 running extremly slowly.

### ISSUE THREAD

**Issue by fwyrl** [TEdit/Terraria-Map-Editor#994]
TEdit 3.10 is running very slowly on my PC. It takes almost 5 minutes to go from having selected the map file to registering the next button press, and all presses after that are processed after about 3 minutes. Out-of program items (such as file selection menu for exporting analysis) work at expected speed, and my PC works as normal - only the program runs slowly.

## What were you doing when the issue occurred?

Anything at all.

## Can you reproduce the issue?

Yes. This is consistent every launch.

## What version of Terraria are you using?

1.3.5

## Post relevant contents of log or attach log file _**(very important)**_:

Log file was short, so I attached the whole thing. No apparent errors, but all button presses took multiple minutes. I also attached the (zipped) save file.

[1.3_Crimson_SP_World.wld.zip](https://github.com/TEdit/Terraria-Map-Editor/files/992937/1.3_Crimson_SP_World.wld.zip)
[TEditLog.txt](https://github.com/TEdit/Terraria-Map-Editor/files/992939/TEditLog.txt)

Edit: *One* function works in a reasonable time - closing the program (and it running cleanup) actually completes in under 1 second.

**Comment by BinaryConstruct** [comment]
TEdit uses a high amount of disk I/O and is fairly computationally expensive, more so than actual gameplay.  Would you mind posting the results from dxdiag.exe?

example:
![image](https://cloud.githubusercontent.com/assets/456755/26089292/2b73a11c-39c2-11e7-8830-48a37bd8dddb.png)
![image](https://cloud.githubusercontent.com/assets/456755/26089283/1f40f214-39c2-11e7-9f10-10cb2faf9661.png)
![image](https://cloud.githubusercontent.com/assets/456755/26089286/2350a994-39c2-11e7-991c-a65630f76e3c.png)
