### ISSUE TITLE
All timers are inactive

### ISSUE THREAD

**Issue by BadScientist** [TEdit/Terraria-Map-Editor#997]
I've placed the "Active" and "Inactive" versions of each timer on my map, but when I load up the game, they're all inactive. Happens with every timer every time.

Terraria version 1.3.5.3

[Timer Bug World.zip](https://github.com/TEdit/Terraria-Map-Editor/files/1048961/Timer.Bug.World.zip)

**Comment by BinaryConstruct** [comment]
I believe this may be related to #1200. Please refer to that issue going forward.
